### ISSUE TITLE
Document pkg/kubectl/cmd/util/openapi

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#100]
Document code under [pkg/kubectl/cmd/util/openapi](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/util/openapi)

- Write a `doc.go` file with an overview and examples
- Audit functions.  Write code comments for any under documented functions

**Comment by jyoti0208** [comment]
@pwittrock I am interested in working for this issue

**Comment by pwittrock** [comment]
cc @seans3 @mengqiy

**Comment by mengqiy** [comment]
@jyoti0208 Any update?

**Comment by Obtin** [comment]
@pwittrock is anybody working on it ? If not I would like to take this issue.

**Comment by seans3** [comment]
Hello @Obtin. Phil is on parental leave until early September. I'm confident that no one is working on this now. So it would be great if you took this issue.

**Comment by dczombera** [comment]
Are there more information which are helpful for this task? I'd like to work on this issue but it seems that as someone who is new to the project I'm lacking the required knowledge to extend the documentation of the code.

**Comment by prksu** [comment]
@seans3 this issue already fixed in https://github.com/kubernetes/kubernetes/pull/67880

maybe the author forgot to reference it.

**Comment by seans3** [comment]
@prksu Thanks for the help
Closing because of:  https://github.com/kubernetes/kubernetes/pull/67880
/close
