### ISSUE TITLE
kubectl Unable to connect to the server Azure Kubernetes Service

### ISSUE THREAD

**Issue by realnikhilkumar** [kubernetes/kubectl#1000]
Hi,

I am getting below error when using kubectl with MS AKS. I had followed all Microsoft documentation and Kubernetes documentation.

kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority

Azure CLI 2.17.1

Please see below output for aks cli install

PS C:\Users\nikhil.kumar1\.kube> az aks install-cli
Downloading client to "C:\Users\nikhil.kumar1\.azure-kubectl\kubectl.exe" from "https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/windows/amd64/kubectl.exe"
Please add "C:\Users\nikhil.kumar1\.azure-kubectl" to your search PATH so the `kubectl.exe` can be found. 2 options:
    1. Run "set PATH=%PATH%;C:\Users\nikhil.kumar1\.azure-kubectl" or "$env:path += 'C:\Users\nikhil.kumar1\.azure-kubectl'" for PowerShell. This is good for the current command session.
    2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window. You only need to do it once
Downloading client to "C:\Users\NIKHIL~1.KUM\AppData\Local\Temp\tmp8fburcp1\kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.7/kubelogin.zip"
Please add "C:\Users\nikhil.kumar1\.azure-kubelogin" to your search PATH so the `kubelogin.exe` can be found. 2 options:
    1. Run "set PATH=%PATH%;C:\Users\nikhil.kumar1\.azure-kubelogin" or "$env:path += 'C:\Users\nikhil.kumar1\.azure-kubelogin'" for PowerShell. This is good for the current command session.
    2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window. You only need to do it once
PS C:\Users\nikhil.kumar1\.kube>

Environment variables were updated.

Regards,
Nikhil

**Comment by Clivern** [comment]
@realnikhilkumar i think this might help to #823

**Comment by realnikhilkumar** [comment]
Hi,

In my case this error was very misleading. It has nothing to do with actual certificate. Microsoft should have done better job in documentation at their end. The error given is incorrect. Error should actually inform user about not have proper runtime setup. AKS is expecting that the user is using a UNIX/Linux terminal not default Azure-CLI. AKS is expecting user to use AKS CLI from a UNIX/Linux terminal/emulator.

I worked with Microsoft Support on this. 

Following is the resolution: (Windows 10 system preferred version 2004 or later)
1. From Control Panel -> Programs -> Turn Windows Features On or Off 
2. Enable Virtual Machine Platform  
3. Enable Windows Subsystem for Linux 
4. Reboot
5. From Windows Store Install Ubuntu 18.04 LTS
6. Launch Ubuntu follow prompt to create user id and password
7. On Ubuntu prompt run command given in option 1 (curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash)
8. Install kubectl by running sudo az aks install-cli
9. login to portal.azure.com and copy the connection instructions for AKS cluster
10. On Ubuntu prompt run az login
11. On Ubuntu prompt paste the AKS cluster connection commands (az account set --subscription and az aks get-credentials)
12. This will create config file with certificates readable through bash shell

Reference links
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
https://docs.microsoft.com/en-us/windows/wsl/about
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

Follow above four links one by one, do not click Next Steps at bottom of the page.

**Comment by PurnachandRaja** [comment]
If you want to avoid the hassle of installing WSL just simply add env variables to path in system variables
Control Panel->System->Advanced system settings->Environment Variables->System variables->Path->Edit->New

Add below paths one after other
C:\Users\nikhil.kumar1.azure-kubectl
C:\Users\nikhil.kumar1.azure-kubelogin

**Comment by PurnachandRaja** [comment]
there should be a \ after system name not sure why it is not showing up in earlier comment
