### ISSUE TITLE
kubectl LIST not always sets resourceVersion on LIST metadata

### ISSUE THREAD

**Issue by embano1** [kubernetes/kubectl#1001]
**What happened**:

`kubectl` does not reliably set the returned `resourceVersion` in the LIST metadata.

LIST output:

```bash
./kubectl get no -o json| jq .metadata.resourceVersion
""
```

LIST with watch output:

```bash
./kubectl get no -o json -w | jq .metadata.resourceVersion
"68067"
```

```bash
# trace snip showing the response has RV
I0108 16:36:47.512320   51023 request.go:1107] Response Body: {"kind":"NodeList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/nodes","resourceVersion":"67388"},"items":[{"metadata":{"name":"
```

**What you expected to happen**:

`kubectl` should always set `resourceVersion` on the LIST metadata field.

**How to reproduce it (as minimally and precisely as possible)**:

See steps above

**Anything else we need to know?**:
Tried the following versions/build (src):

- Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
- kubectl master build from `9a386cdd5d703d310ef82e892501621665c5eb00` (Jan 8th)

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
  - Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
  - - kubectl master build from `9a386cdd5d703d310ef82e892501621665c5eb00` (Jan 8th)

- Cloud provider or hardware configuration: n/a (kind)
- OS (e.g: `cat /etc/os-release`): OSX

**Comment by eddiezane** [comment]
@soltysh

**Comment by soltysh** [comment]
`kubectl` uses `List` as a container for resources retrieved from the server. Since every resource has its own specific List type, eg. `PodList` we can't put multiple different types into those, and `kubectl` allows you to request several different resources at once. We have an open issue here https://github.com/kubernetes/kubectl/issues/984 which asks for documenting the `List` type being used in `kubectl`. For that reason we don't plan nor expect the `resourceVersion` field to be set to any particular value.

/close
