### ISSUE TITLE
Add endpoint count in kubectl get svc

### ISSUE THREAD

**Issue by hrishin** [kubernetes/kubectl#1002]
**What would you like to be added**:
In the `kubectl get svc` add an endpoint count column by default. It may be fine to add it as part of `-o wide` option.
```bash
$ kubectl get service
NAME   TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          Endpoint(S)    AGE
web    NodePort   10.108.X.X    <none>        8080:32170/TCP   2              8s
```

**Why is this needed**:
Often a time working with `service` the important information is required is `endpoints` a `service` pointing to. Especially in the troubleshooting scenarios to get the overview of `services`.

**Comment by eddiezane** [comment]
/priority backlog
/triage accepted
/help
/good-first-issue

This change will need to be done server side.

**Comment by BLasan** [comment]
> /priority backlog
> /triage accepted
> /help
> /good-first-issue
> 
> This change will need to be done server side.

Can I work on this? I'm bit new to the community

**Comment by lauchokyip** [comment]
yea @BLasan go ahead  👍🏼  , just type `/assign` to assign it to you

**Comment by BLasan** [comment]
> yea @BLasan go ahead 👍🏼 , just type `/assign` to assign it to you

Would you mind helping me to fix this issue? How to test these commands separately? Just running `go test` command?

**Comment by lauchokyip** [comment]
@BLasan I just started contributing a month ago but the main code for `kubectl` sits here
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl

**Comment by BLasan** [comment]
> @BLasan I just started contributing a month ago so I can't help you much :/ (only knows some basic) but the main code for `kubectl` sits here
> https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl
> 
> This page has great info of how to get started
> https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md

Thanks a lot :)

**Comment by BLasan** [comment]
The output template was found inside the go_test.go file. Should I start from there by adding the new field? @hrishin

**Comment by hrishin** [comment]
hi @BLasan , I'm sorry to say I've never delved into the kubectl source much. However, I can try to help with some leisure time.
IMO `go_test.go` sounds like the test code. Looking at the glance one can look into 
get command -> https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/get
printers -> https://github.com/kubernetes/cli-runtime/tree/master/pkg/printers
or
nice to check if there is a way to configure `additionalPrinterColumns` for the `service` kind resource(which is least probable as it applied to Custom Resources)

**Comment by BLasan** [comment]
> hi @BLasan , I'm sorry to say I've never delved into the kubectl source much. However, I can try to help with some leisure time.
> IMO `go_test.go` sounds like the test code. Looking at the glance one can look into
> get command -> https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/get
> printers -> https://github.com/kubernetes/cli-runtime/tree/master/pkg/printers
> or
> nice to check if there is a way to configure `additionalPrinterColumns` for the `service` kind resource(which is least probable as it applied to Custom Resources)

yuh, get_test.go is for the testing purposes. I checked the get.go file but was not able to find the relevant implementation. Thanks for the resources :)

**Comment by lauchokyip** [comment]
Thanks @BLasan will start working on it next week

**Comment by rikatz** [comment]
/assign @rikatz 
I'll try to guide you folks during this week, sounds good? :)

**Comment by BLasan** [comment]
> /assign @rikatz
> I'll try to guide you folks during this week, sounds good? :)

That's great :)

**Comment by rikatz** [comment]
OK folks, I'm wondering if this should be shown only if options wide is used. For now this is "simple" to change  but not related exactly with kubectl, but with apiserver and transpassing two objects so we need to figure out if apimachinery folks are ok with this.

So, after digging a bit (aaand greping a bit more) we can see that the file that generates the columns to be printed is this one: https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go

BUT this file is not used by kubectl, but instead, used by apiserver that receives a request of 'print to me the table containing the resources' and return a table object to be printed :)

This is done more or less here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/get/table_printer.go#L58

So we need to change how the apiserver return the columns, adding [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L190) the new column (I would recommend it to be of type Integer and contain a description like [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L184)) and then tell the apiserver how to retrieve the information of this column [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L1135).

As an example of "-o wide" in use and with extra fields, take a look [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L1296-L1299)

Finally, once you add the new column and the logic to fetch that column information (the count of endpoints), compile kube-apiserver and when you do a 'kubectl get svc -o wide' it should print the endpoints. 

But again, what is called is the printService function, that already receives an 'api.Service' object, that does not contain any information about the Endpoint or the EndpointSlices that it manages.

@soltysh @eddiezane ideas on this?

**Comment by rikatz** [comment]
/remove-help
/remove-good-first-issue

So yesterday during sig-cli meeting we've figured out this issue is not as easy as it seems to be :) So we're going to discuss the best approach to this, as it demands some change on the way the API server returns the information (And IF this is possible).

I'm removing the labels for now, and will keep this open until we figure out if and how we can achieve this 

@soltysh will take a look when he gets some time if there's a similar case on internal printers consuming objects from another api kind (like services vs endpoints) and let us know if this can be achieved or not :)

**Comment by soltysh** [comment]
This won't be possible, that data is connected with retrieving additional objects and we're not doing that inside any get output. `kubectl describe` provides that additional information you're requesting, though.

/close
