### ISSUE TITLE
KUBECTL_EXTERNAL_DIFF does not allow parameters with equal sign to be applied

### ISSUE THREAD

**Issue by armingerten** [kubernetes/kubectl#1007]
Unfortunately there is still a small gap with `KUBECTL_EXTERNAL_DIFF`: When using GNU diffutils, some commands (e.g. `--color[=WHEN]`) require an equal sign, which is excluded by the specified regex (`^[a-zA-Z0-9-]+$`)

_See also https://github.com/kubernetes/kubectl/issues/937#issuecomment-703380916_

**Comment by dougsland** [comment]
Patch merged on master, thanks for your report. 
/close
