### ISSUE TITLE
kubectl diff: external command doesn't support sub commands

### ISSUE THREAD

**Issue by meier-christoph** [kubernetes/kubectl#1015]
**What happened**:

The way kubectl handles args defined with a custom diff command (via KUBECTL_EXTERNAL_DIFF) prevents usage of sub commands e.g. `KUBECTL_EXTERNAL_DIFF=kubectl-neat diff` would not work because diff is appended at the end resulting in the final command being `kubectl-neat {from} {to} diff`.

**What you expected to happen**:

The command executed should be `kubectl-neat diff {from} {to}`

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl diff <=> diff -u -N {from} {to}
export KUBECTL_EXTERNAL_DIFF=colordiff -N -u
kubectl diff <=> colordiff {from} {to} -N -u
```

**Anything else we need to know?**:

The current version works fine for flags e.g. `-u -N`, by changing the order on L184 to the same logic as L190 we should be able to support both styles.

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/diff/diff.go#L184
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/diff/diff.go#L190

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
```

**Comment by dougsland** [comment]
Hi @meier-christoph, 

Have you resolved this one as https://github.com/itaysk/kubectl-neat/pull/58 suggested creating a shell script?

Can we close this one?

Thanks!

**Comment by meier-christoph** [comment]
Hi,

I am not sure I would call this fixed, I still believe there is a mistake in the ordering of arguments passed to the diff command but you are right that you can overcome this by using a shell script.

In my case, @sh0rez had the same issue and he chose a more direct approach as a few days ago he created [kubectl-neat-diff](https://github.com/sh0rez/kubectl-neat-diff) which I have been using as well.

If you are afraid that changing it now may break someone else's tool then sure we can leave it as it is and close this issue.

Cheers,
Chris

**Comment by eddiezane** [comment]
@dougsland bump on this
