### ISSUE TITLE
`kubectl config set-context --current --namespace=abc`  fails saying `Error: unknown flag: --current`

### ISSUE THREAD

**Issue by pattnaik-soumitri** [kubernetes/kubectl#1018]
**What happened**:
Permanently saving the namespace for all subsequent kubectl commands in the current context fails in windows but works on Mac. The command is documented [here](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration).

**Command**
```sh
$ kubectl config set-context --current --namespace=abc
```
**Output**
```sh
Error: unknown flag: --current


Examples:
  # Set the user field on the gce context entry without touching other values
  kubectl config set-context gce --user=cluster-admin

Usage:
  kubectl config set-context NAME [--cluster=cluster_nickname] [--user=user_nickname] [--namespace=namespace] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

unknown flag: --current
```

**What you expected to happen**:
It should set the namespace to `abc` in the current context.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This works fine on Mac.

**Environment**:
```sh
$ kubectl version
```

```sh
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.6000", GitCommit:"b02f5ea6726390a4b19d06fa9022981750af2bbc", GitTreeState:"clean", BuildDate:"2020-11-18T09:16:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS: Windows 10 Enterprise

**Comment by dty1er** [comment]
I did not check deeply but seems like kubectl version 1.11.2 is too old and unsupported. (current latest is 1.20.2)
What if you update kubectl to the latest and try again?

**Comment by pattnaik-soumitri** [comment]
> I did not check deeply but seems like kubectl version 1.11.2 is too old and unsupported. (current latest is 1.20.2)
> What if you update kubectl to the latest and try again?

I just installed kubcetl version 1.20.2 as you mentioned, and it works in that. Thanks!
**How do I know in which version this got fixed?**

I will close the issue.

**Comment by pattnaik-soumitri** [comment]
Closing the issue as it not present in the latest version of kubectl.
