### ISSUE TITLE
kubectl is really slow on MacOS BigSur

### ISSUE THREAD

**Issue by lucasyarza** [kubernetes/kubectl#1020]
**What happened**:
In MacOS BigSur the kubectl commands are very slow most of the time. For example, if you run `kubectl get pods` it takes at least 46 seconds.

**What you expected to happen**:
In previous versions it only took about 10 seconds.

**How to reproduce it (as minimally and precisely as possible)**:

On MacOS BigSur execute `kubectl get pods`

**Anything else we need to know?**:
It has been tested with different clusters and cloud providers, as well as with minukube on my local machine.
It has also been tested on different devices with the same result.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider or hardware configuration:
  - Anyone
- OS (e.g: `cat /etc/os-release`):
  - MacOS BigSur Version 11.2
  - Processor: Quad-Core Intel Core i7

**Comment by dougsland** [comment]
Hi @lucasyarza I don't have MacOS BigSur here but I have few questions:

```
How to reproduce it (as minimally and precisely as possible):
On MacOS BigSur execute kubectl get pods
```
Is it only with kubectl get pods command or any other command too?

```
What you expected to happen:
In previous versions it only took about 10 seconds
```
You meant 1.19 and previous versions?


Any insight from:
```
 $ kubectl get pods -v=9
```

@eddiezane

**Comment by lucasyarza** [comment]
Hi @dougsland,
_is it only with kubectl get pods command or any other command too?_
No, it is with all kubectl get <anyresource>

_You meant 1.19 and previous versions?_
I only check this on 1.19 version.

**kubectl get pods -v=9**

```
kubectl get pods --v=9
I0218 08:10:25.667431    2091 loader.go:379] Config loaded from file:  /Users/<username>/.kube/config
I0218 08:11:10.828132    2091 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json" -H "User-Agent: kubectl/v1.20.2 (darwin/amd64) kubernetes/faecb19" -H "Authorization: Bearer <masked>" 'https://api.<host>:6443/api/v1/namespaces/default/pods?limit=500'
I0218 08:11:11.336460    2091 round_trippers.go:445] GET https://api.<host>:6443/api/v1/namespaces/default/pods?limit=500 200 OK in 508 milliseconds
I0218 08:11:11.336497    2091 round_trippers.go:451] Response Headers:
I0218 08:11:11.336506    2091 round_trippers.go:454]     Date: Thu, 18 Feb 2021 07:11:11 GMT
I0218 08:11:11.336516    2091 round_trippers.go:454]     Audit-Id: 656eaf7e-e26b-4093-872b-be7c1e822f3f
I0218 08:11:11.336524    2091 round_trippers.go:454]     Cache-Control: no-cache, private
I0218 08:11:11.336530    2091 round_trippers.go:454]     Content-Type: application/json
I0218 08:11:11.336536    2091 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: c9b72ab5-ed7b-4af9-b4fb-8a851b7c3ea7
I0218 08:11:11.336543    2091 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: 3b56ea3e-a0dc-461a-821c-9e69d81c207b
I0218 08:11:11.336550    2091 round_trippers.go:454]     Content-Length: 2930
I0218 08:11:11.336630    2091 request.go:1107] Response Body: {}
```

**Comment by lucasyarza** [comment]
Hi @dougsland,
Request to API goes as expected. The issue I see is from the first step (loader.go) to the second step (when cli requests API). You can see in the logs this action takes more less one minute.

Regards.

**Comment by eddiezane** [comment]
Can you please try again after removing (make a backup just in case) `~/.kube/http-cache` and `~/.kube/cache`?

How many clusters/users/etc do you have in your `~/.kube/config`?

It looks like the hang up is in the loader.

**Comment by lucasyarza** [comment]
Hi @eddiezane,

I don't have `~/.kube/http-cache`. Y try after deleting `~/.kube/cache` and `~/.kube/config`. First time it works as expected. But when I do second call again takes more than 40 seconds.

If only delete `~/.kube/cache` calls takes more than 40 seconds. I need to delete both `~/.kube/cache` and `~/.kube/config`, to make one call that takes less than 15 seconds. Other calls takes again too much time.

Regards.

**Comment by lucasyarza** [comment]
Hi,
This is the output of `kubectl get pods --v=10`

```
I0224 08:41:45.900775    5113 cached_discovery.go:114] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/servergroups.json
I0224 08:42:00.909464    5113 cached_discovery.go:71] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/events.k8s.io/v1beta1/serverresources.json
...

...
I0224 08:42:00.950469    5113 cached_discovery.go:114] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/servergroups.json
I0224 08:42:15.959664    5113 cached_discovery.go:71] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/metrics.k8s.io/v1beta1/serverresources.json
...

...
I0224 08:42:16.009692    5113 cached_discovery.go:114] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/servergroups.json
I0224 08:42:31.009886    5113 cached_discovery.go:71] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/authentication.k8s.io/v1beta1/serverresources.json
...

...
<output>
```

As you can see kubectl get cache 3 times from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/servergroups.json and takes 15 second for each.

I can see similar lines on the output like:
```
I0224 08:42:31.009946    5113 cached_discovery.go:71] returning cached discovery info from /Users/blablabla/.kube/cache/discovery/api.blablabla.com_6443/apps/v1/serverresources.json
I0224 08:42:31.011332 .........
```
And it doesn't take that long.

I think is related with 114 line of cached_discovery.go

Regards.
