### ISSUE TITLE
Validate certificate format when writing it to kubeconfig

### ISSUE THREAD

**Issue by curusarn** [kubernetes/kubectl#1023]
**What would you like to be added**:
`kubectl config set-cluster <cluster> --certificate-authority=<ca.crt> --embed-certs=true` should validate that the certificate has correct format.

**Why is this needed**:
Kubectl will silently base64 encode the passed certificate even if it's already base64 encoded. This will result in a unusable config. I would expect `kubectl` to never produce a config that is practically broken.

This mistake is easy to make because the certificate is base64 encoded when it is in the config or when it is retrieved from k8s secrets - it makes sense to also pass it base64 encoded to kubectl. The error is hard to spot because the certificate is omitted when `kubectl config view -o json` is used.

**Comment by eddiezane** [comment]
We can initially implement this as a warning. It will require fixing a bunch of tests to actually fail.

/triage accepted
/priority backlog
/assign

**Comment by Cdower** [comment]
I'd like to try fixing tests

**Comment by curusarn** [comment]
There is an open PR for this that was accepted. I'm not an expert on issue lifecycle but it doesn't seem right to close the issue in this case.

/remove-lifecycle rotten
