### ISSUE TITLE
Use git shallow clone when applying configuration from GitHub url

### ISSUE THREAD

**Issue by jgallucci32** [kubernetes/kubectl#1031]
**What would you like to be added**:
When applying a configuration using a direct GitHub url, it appears to be cloning the entire git repository which depending on the project can cause delays (and in some cases timeout) during the operation. An example is applying the Kustomization for the CSI driver for Amazon EBS as follows
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.9"
```
For this particular environment, the WAN is very limited and cloning the entire git repository times. When using a git shallow clone (i.e. `git clone --depth=1`) only the branch is checked out and the clone operation succeeds in a few seconds.

**Why is this needed**:
Projects increasingly rely on pulling software install packages directly from GitHub rather than a package management system and it causes significant delays cloning an entire repository to obtain these files needed for install. Since only a specific branch or tag is required when applying a configuration using the `kubectl` command, the git operation should be using a shallow clone to speed up the process.

**Comment by eddiezane** [comment]
The baked in version of kustomize was [upgraded to v4](https://github.com/kubernetes/kubernetes/pull/98946) and this should be fixed. It will ship with kubectl v 1.21.

If for some reason it's not please reopen on the [kustomize repo](https://github.com/kubernetes-sigs/kustomize/).

/close
