### ISSUE TITLE
kubectl create configmap: Support multiple --from-env-file flags

### ISSUE THREAD

**Issue by lapwat** [kubernetes/kubectl#1033]
**What would you like to be added**:
I would like an error to be raised if multiple `--from-env-file` flags are specified in the `kubectl create configmap` command.

**Why is this needed**:
If multiple `--from-env-file` flags are specified, the last one overrides the previous ones. Therefore, --from-env-file is useless and ambiguous.

[Source](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
> Caution: When passing --from-env-file multiple times to create a ConfigMap from multiple data sources, only the last env-file is used.

**Comment by lauchokyip** [comment]
@eddiezane, if it's accepted I can try working on it since I was working on removing generator for `kubectl create configmap`

**Comment by lapwat** [comment]
Thank you,

Actually I have done it: https://github.com/lapwat/kubectl/commits/master (see last 2 commits)

But cannot push to this repository directly to this repo. Feel free to push copy the changes and push it the staging version of Kubernetes.

**Comment by lapwat** [comment]
(if / when it is accepted)

**Comment by lauchokyip** [comment]
@lapwat thanks! if this adding this feature is confirmed by Kubernetes memberes, you can go ahead and submit a PR :) For now, you can wait for any feedbacks

**Comment by lauchokyip** [comment]
@lapwat thanks! if adding this feature is confirmed by Kubernetes members, you can go ahead and submit a PR :) For now, you can wait to see if there is any followups

**Comment by lapwat** [comment]
Understood for `StringSliceVar`.

I have chosen to forbid several tags because it is the current behavior and was easier to patch.

Allowing multiple flags is not a bad idea neither if you want to specify default values that are common to your different environment. Should we go for this?

**Comment by KnVerey** [comment]
Yes, let's go with supporting multiple instances of the flag, consistent with the current behavior of `--from-file` and `--from-literal`.

/triage-accepted
/retitle kubectl create configmap: Support multiple --from-env-file flags
/assign @lapwat

**Comment by lauchokyip** [comment]
@lapwat any updates ? :)

**Comment by lapwat** [comment]
Yes sorry for the delay do not have the time to do it right away feel free to take it over :) thanks

**Comment by lauchokyip** [comment]
No worries @lapwat , I will take care of that

**Comment by KnVerey** [comment]
@lauchokyip great work on the PR! I just realized that it would make a lot of sense to make the same enhancement for `kubectl create secret`. Would you be interested in working on that as well?

**Comment by lauchokyip** [comment]
Sure! I will make a PR soon 😊
