### ISSUE TITLE
Dots in pod name are not supported in get describe commands

### ISSUE THREAD

**Issue by adambro** [kubernetes/kubectl#1034]
**What happened**:

The pod name after `.` seems to be truncated for describe and get commands. Example:
```
kubectl describe -n kube-system 'fluentd-es-v2.4.0-mwljf'
error: the server doesn't have a resource type "fluentd-es-v2"
```

**What you expected to happen**:

I expect this to be working, because logs command does not have this issue and returns logs as expected:
```
kubectl logs -n kube-system fluentd-es-v2.4.0-mwljf
```
No need to quote the name, so it's not some ZSH (my shell) interpreting dots problem.

**How to reproduce it (as minimally and precisely as possible)**:

I guess any pod name with dot in it will do.

**Anything else we need to know?**:

N/A

**Environment**:

- Kubernetes client and server versions (use `kubectl version`):
```
kubectl version                                                       
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS, not sure that's relevant
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 Desktop

**Comment by pacoxu** [comment]
It should be 
`kubectl describe -n kube-system pod 'fluentd-es-v2.4.0-mwljf'`

/sig cli

**Comment by adambro** [comment]
Indeed, I've made the params order on CLI wrong. Thanks for pointing this out. Beginner mistake I guess.
