### ISSUE TITLE
`kubectl create secret tls` should optionally set `ca.crt` key

### ISSUE THREAD

**Issue by ibotty** [kubernetes/kubectl#1037]
**What would you like to be added**:

It would be great to also allow (optionally) creating ca.crt.

**Why is this needed**:

Some tooling requires a `ca.crt` key in tls certs.  It would be great to easily set it.

**Comment by rikatz** [comment]
/assign @ibotty 
/triage accepted

Agree, this is a good feature to have in kubectl create secret tls, the majority of ingress controllers use this :)

**Comment by excalq** [comment]
Here's a good use-case for this: I'm creating a pod which runs an OpenVPN client, which connects to a remote VPN server. The OpenVPN client config requires a key, cert, and a CA cert (but not the CA key).

I'm able to work around this by creating a `generic` secret for the CA, and mounting it along with a separate `tls` secret for the client. If `--ca` ([PR #100884](https://github.com/kubernetes/kubernetes/pull/100884)) were included, these could be combined into one secret.

**Comment by richardcase** [comment]
We also have need for this functionality.
