### ISSUE TITLE
`kubectl alpha debug` should allow set namespace through `--namespace` flags

### ISSUE THREAD

**Issue by zryfish** [kubernetes/kubectl#1039]
**What would you like to be added**:
Currently, `kubectl alpha debug` set namespace through kubeconfig, not from command line flags. https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/debug/debug.go#L208
```
	// Namespace
	o.Namespace, _, err = f.ToRawKubeConfigLoader().Namespace()
	if err != nil {
		return err
	}
```

**Why is this needed**:
It would be great to support setting namespace through command-line flags, just like `kubectl get po -n kube-system`. I would love to implement this feature if accepted by the community.

**Comment by eddiezane** [comment]
@verb thoughts?

Looks like a good first issue for someone.

**Comment by verb** [comment]
Hi @zryfish, `kubectl debug` already supports the namespace flag:

```
$ kubectl debug --namespace=test iso --image=busybox --copy-to=iso-debug -it 
Defaulting debug container name to debugger-n8699.
If you don't see a command prompt, try pressing enter.
/ # 
```
```
$ kubectl debug shared --namespace=test --image=busybox -it -- sh            
Defaulting debug container name to debugger-2kmmz.
If you don't see a command prompt, try pressing enter.
/ #
```

Could you provide some examples that aren't working for you?

**Comment by zryfish** [comment]
My mistake, it's working now. I got the following error message, mistakenly thinking kubectl couldn't find the pod. 
```
error: ephemeral containers are disabled for this cluster (error from server: "the server could not find the requested resource").
```
