### ISSUE TITLE
Kustomize flags do not work

### ISSUE THREAD

**Issue by astute-engineering** [kubernetes/kubectl#1040]
**What happened**: kubectl kustomize flags do not work as documented in https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#kustomize

**What you expected to happen**: Flags work as expected, or documentation is updated as per current state of kubectl.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a simple kustomization directory (k_dir) with one resource.
`namespace.yml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
```
`kustomization.yml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
```
2. Run the `kubectl kustomize DIR` command with a flag (for this example, I will use --load-restrictor)
`kubectl kustomize k_dir --load-restrictor=LoadRestrictionsNone`
3. Note the error `Error: unknown flag: --load-restrictor`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: minikube hyperkit
- OS (e.g: `cat /etc/os-release`): Client on macOS, Server on minikube hyperkit

**Comment by eddiezane** [comment]
That should work if you grab the latest version of kubectl (v1.21). The version of kustomize that ships with kubectl was just majorly bumped there.

/close
