### ISSUE TITLE
Error schema.go no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" when approving a certificate signing request

### ISSUE THREAD

**Issue by avvertix** [kubernetes/kubectl#1047]
**What happened**:

When approving a CSR request, by using `kubectl certificate approve <name>` the following error was returned

```
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1"
in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

**What you expected to happen**: 

The certificate is approved or a better error is returned

**How to reproduce it (as minimally and precisely as possible)**:

I was following the procedure to configure a new user access to the Kubernetes cluster using certificates as outlined in https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

I generated a private key and a CSR by placing in the CN field the same name as the user I want to create.

I then generated the certificate signing request yaml to apply to the cluster.

```yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user
spec:
  groups:
  - system:authenticated
  request: L...=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
```
 
I saved this file as user.yml and applied to the cluster using the kubeconfig downloaded from the admin panel.

```
kubectl apply -f ./user.yml

kubectl get csr

NAME      AGE   SIGNERNAME                         REQUESTOR  CONDITION
user   62m   kubernetes.io/kube-apiserver-client   DO-email   Pending
```

But when I want to approve it I get back the error

```
kubectl certificate approve user

No resources found
error: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

**Anything else we need to know?**: 

the cluster was clean, I was using the default namespace and the kubernetes version is 1.20.2

**Environment**:

- Kubernetes client and server versions (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", 
BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", 
BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} 
```

Although I was expecting it to be 1.21.0 as I downloaded it from https://dl.k8s.io/release/v1.21.0/bin/windows/amd64/kubectl.exe

- Cloud provider or hardware configuration: **Digital Ocean**
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
Looks like you're using a different executable than the one you downloaded.

You should be able to run `where kubectl` or something similar to track it down.

/close
