### ISSUE TITLE
kubectl freezing mac

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubectl#1053]
**What happened**:

Basic kubectl commands like `kubectl get service` freeze up my mac, making it impossible to click or do anything for minutes at a time.

**What you expected to happen**:

The command should complete quickly without interrupting other macOS applications.

**How to reproduce it (as minimally and precisely as possible)**:

```console
$ kubectl get service
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: EKS

- OS (e.g: `cat /etc/os-release`):

```console
$ cat /etc/os-release
cat: /etc/os-release: No such file or directory

$ uname -a
Darwin lounge.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64
```

**Comment by brianpursley** [comment]
Are you accessing a remote cluster or one running locally (ie. KinD or Minikube)?

**Comment by eddiezane** [comment]
Can you please confirm that you're not using an M1 mac?

Does removing the cache folders from `~/.kube` have any effect?

/triage needs-information

**Comment by Prakhar-FF13** [comment]
M1 Mac - Same Issue - I had 2 services running and my Mac hung up. By hung up I mean I could open things up but they wouldn't close down. I wasn't even able to stop docker desktop. force quit didn't work. I had hard reset the laptop. 
Did not try removing ~/.kube folder.

**Comment by eddiezane** [comment]
@Prakhar-FF13 what is the output of `file $(which kubectl)`?

Please try clearing the cache folders inside `~/.kube` and see if you can reproduce.

**Comment by brianpursley** [comment]
@mcandre Is this still happening?  

Can you try `kubectl get service -v9` and post the output?

Does the command eventually finish and your machine eventually recover on its own after a couple of minutes?

**Comment by seguri-doodle** [comment]
I don't know if it's related, if not I'll open a new issue.

On my macOS 10.15.7, `kubectl` 1.21.1 is not freezing my mac but is not responding anymore:
```
kubectl version -v9
I0528 10:57:16.210888   92555 loader.go:372] Config loaded from file:  ~/.kube/config
I0528 10:57:16.211376   92555 round_trippers.go:435] curl -k -v -XGET  -H "User-Agent: kubectl/v1.21.1 (darwin/amd64) kubernetes/5e58841" -H "Accept: application/json, */*" 'https://mycompany/version?timeout=32s'
W0528 10:57:48.213356   92555 transport.go:260] Unable to cancel request for *exec.roundTripper
```
The iTerm tab title is stuck into `kubectl-oidc_login`.

**Comment by martinohmann** [comment]
My colleges and I were also experiencing kubectl freezes on MacOS Big Sur and started to dig a little bit. The problem occured both for amd64 and arm64 (M1) Macs, with the M1 freezing much more frequently.

In the end the freezes were not causes by kubectl but the anti-virus that was installed on our corporate laptops (Sophos Endpoint in our case). It was not kubectl freezing but an anti-virus process which was then terminated by the kernel with SIGKILL after some seconds (up until a minute). Disabling the anti-virus made the freezes go aware completely. The more frequent freezes on the M1 are probably caused by the fact that there are no arm64 builds of this particular anti-virus yet. So rosetta is involved.

I suspect that it maybe gets hangs itself when reading through the http-cache that kubectl writes.

Hope this helps.

**Comment by Prakhar-FF13** [comment]
I don't really have an anti-virus on my m1 Mac. but it does hang and pattern isn't very clear either.

**Comment by eddiezane** [comment]
@martinohmann thanks a ton for the info! Rosetta has been my suspicion. Anything you can share here about tracing the signals for others to confirm please do.

@Prakhar-FF13 did you catch my reply above?

> @Prakhar-FF13 what is the output of `file $(which kubectl)`?
> 
> Please try clearing the cache folders inside `~/.kube` and see if you can reproduce.

**Comment by Prakhar-FF13** [comment]
Oh sorry, did not catch that one, I was getting frustrated so I uninstalled it. Will update when I reinstall Kubernetes again.

**Comment by martinohmann** [comment]
@eddiezane I ended up tailing the MacOS system log (`Applications` -> `Utilities` -> `Console`) while using kubectl and discovered a pattern of anti-virus process crashes which aligned nicely with the freezes. Maybe there are also other applications other than anti-virus' that could be involved in the freezes.

In my case the log entries looked something along the lines of:
```
<the-date> [<my-hostname>] <namespaced-name-of-anti-virus-process>[<PID>] ... Service exited due to SIGKILL | sent by kernel_task[0]
```

I cannot check for the exact message right now as I'm writing this from my linux box. I'll see if I can grab it from my mac during work tomorrow.

**Comment by eddiezane** [comment]
Thanks!

That would make a ton of sense. The cache directory has and writes out a ton of files.

If antivirus is scrambling to index/scan them all....

```
$  tree ~/.kube
...
2934 directories, 4201 files
```
