### ISSUE TITLE
Allow kubectl explain to display 'kind: Config'

### ISSUE THREAD

**Issue by jonassteinberg1** [kubernetes/kubectl#1055]
**What would you like to be added**:

I would like `kubectl explain` to explain `kind: Config`.

**Why is this needed**:

- there is no explain resource for `kind: Config`
- although it has no entry in the [current kubernetes-api reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#-strong-config-and-storage-apis-strong-) kubeconfig-as-code should be explainable like everything else

**Comment by sftim** [comment]
Aside: the home for KUBECONFIG format documentation would be https://kubernetes.io/docs/reference/config-api/

I'm not expecting `kubectl` to add `explain` support for all these. Maybe `kubectl config explain` might be useful to add though?

**Comment by jaehnri** [comment]
/assign
I wanna help on this

**Comment by eddiezane** [comment]
This has been on my bucket list. I'm not sure what type that docs links is using.

The closest we have to kubeconfig documentation is https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go.

This might also be a duplicate issue.

**Comment by rikatz** [comment]
huum, so about "kubectl config explain" vs "kubectl explain config", and this is my personal opinion, I think this may lead to undesired confusions, like the commands that have "-v/--version/-V" to define version vs verbosity :) 

OTOH, from a CKA/CKAD test perspective, for example, sometimes it's hard to understand and create kubeconfig files. 

Maybe the same logic of explain printer can be used, but locally just using the Config type that Eddie has pointed.

About the types of docs, as far as I could check (but @sftim knows that with much more property than me) it's probably a call to https://github.com/kubernetes-sigs/reference-docs/tree/55bce686224caba37f93e1e1eb53c0c9fc104ed4/gen-compdocs from the main k/website repo.

**Comment by eddiezane** [comment]
The reason the type cannot be explained is because it's not part of the cluster OpenAPI because it's not a part of the actual Kubernetes API (meaning it can't be created/read/etc as a resource in your cluster).

We should get the [Go type](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go) added to the documentation though. Maybe @sftim or @tengqm can help with that?

**Comment by sftim** [comment]
The page where we document this kind of non-API format is https://kubernetes.io/docs/reference/config-api/

The tools we use for that are in https://github.com/kubernetes-sigs/reference-docs/

**Comment by sftim** [comment]
I won't have time to help out with this myself for some time though: I'd need to learn a bunch of tech I'm not yet familiar with.

**Comment by eddiezane** [comment]
Would like to address this one day. Maybe we can merge in our own open OpenAPI schema for this inside the command?

/remove-lifecycle rotten
/triage accepted
/priority backlog

**Comment by apelisse** [comment]
> Would like to address this one day. Maybe we can merge in our own open OpenAPI schema for this inside the command?

that's an option (probably the best one), but how do you generate the openapi for the kubeconfig? That's not super trivial.
