### ISSUE TITLE
[FR] Flatpak / Flathub distribution

### ISSUE THREAD

**Issue by rayfoss** [kubernetes/kubectl#1057]
**What would you like to be added**:
Flatpak manifest for flathub distribution

**Why is this needed**:
This tool is often used once a year and falls out of sync. Flatpaks are the only relyable way to update in RHEL and and other Linux distros. It's also the main container format used by those who don't like centralized Flathub/Snap Store/App Store style lock-in.

**Comment by eddiezane** [comment]
Hi @rayfoss,

Package managers are considered out of scope of the upstream Kubernetes project. We provide binaries and rely on the community to handle distribution via their favorite mechanism.

If you're interested in there being a kubectl flatpak in flathub I'd encourage you to consider submitting one!

https://github.com/flathub/flathub/wiki/App-Submission

Looks like you could use do something similar to this: https://github.com/gbraad/flatpak-kubernetes-client

Grab the latest version: https://storage.googleapis.com/kubernetes-release/release/stable.txt

And download: https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl

/close
/triage unresolved
