### ISSUE TITLE
How to use client-go  judge Pod Terminating Status.

### ISSUE THREAD

**Issue by Sakuralbj** [kubernetes/kubectl#1058]
PodPhase is a label for the condition of a pod at the current time. It contains "Pending" "Running" "Succeeded" "Failed" "Unknown".  How can I get pod which status is Terminating like this with client-go .It seems  that the terminated Pod status is Running .
```
NAME                                      READY   STATUS        RESTARTS   AGE
nginx-deployment-basic-5bf87f5f59-rvc25   1/1     Terminating   0          42h
nginx-deployment-basic-5bf87f5f59-s6lq9   1/1     Terminating   0          5d22h
nginx-deployment-basic-5bf87f5f59-v2jhq   1/1     Terminating   0          6d1h
nginx-deployment-basic-5bf87f5f59-v2tl9   1/1     Terminating   0          42h
nginx-deployment-basic-5bf87f5f59-vbdmz   1/1     Terminating   0          5d14h

```

**Comment by YizhanLin** [comment]
hi @Sakuralbj , do you have any solution about this? thanks!

**Comment by Yenuo** [comment]
你好 这个问题有解决的方法吗？

**Comment by YizhanLin** [comment]
> 你好 这个问题有解决的方法吗？

你好，不知道我这个东西能不能解决你的问题，可以获取pod之后判断 j.ObjectMeta.DeletionTimestamp != nil 如果说==nil,则证明没有被删除，也就是不是Terminating ，如果!=nil 就是Terminating
