### ISSUE TITLE
`kubectl run pod_name --` <tab> doesn't complete anything other than `--image`

### ISSUE THREAD

**Issue by xuhdev** [kubernetes/kubectl#1059]
**What happened**: When I run `kubectl run busybox --<tab>`, it only completes `--image` but not any other options.

**What you expected to happen**: It should also complete other `run` options.

**How to reproduce it (as minimally and precisely as possible)**:

- Enable auto completion by running `source <(kubectl completion bash)`
- Type `kubectl run busybox --`
- Type `<tab>`.

`--image` is auto completed, but it should give a list of options that start with `--`. This sharply contrasts with `kubectl get pod --<tab>`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-alpha.2.210+f7e62dc5bb42c5-dirty", GitCommit:"f7e62dc5bb42c5303b9276c5a90c642eaa80d54a", GitTreeState:"dirty", BuildDate:"2021-05-26T23:28:59Z", GoVersion:"go1.16", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
  ```
- Cloud provider or hardware configuration: minikube
- OS (e.g: `cat /etc/os-release`):

  ```
  PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
  NAME="Debian GNU/Linux"
  VERSION_ID="11"
  VERSION="11 (bullseye)"
  VERSION_CODENAME=bullseye
  ID=debian
  HOME_URL="https://www.debian.org/"
  SUPPORT_URL="https://www.debian.org/support"
  BUG_REPORT_URL="https://bugs.debian.org/"
  ```

**Comment by lauchokyip** [comment]
Hi @xuhdev , bash completion is actually done on `cobra.Command` side which can be found [here](https://github.com/kubernetes/kubernetes/blob/46b9ccd0fcc9522342807b16d750b02e34998d64/vendor/github.com/spf13/cobra/bash_completions.go)

Regarding of the error, I think it's expected because the image flag is [required](https://github.com/kubernetes/kubectl/blob/028e3f5db22abf325aee44da5ea246f7cdb78b58/pkg/cmd/run/run.go#L175)

so if you do
```
kubectl run busybox --image=busybox <tab> it will display all the possibilities.  
```

Hopefully that helps!

**Comment by xuhdev** [comment]
Thanks @lauchokyip , this is really helpful.
