### ISSUE TITLE
kubectl autoscale not outputing namespace during client dry-run

### ISSUE THREAD

**Issue by krishnaarava** [kubernetes/kubectl#1060]
**What happened**:

kubectl autoscale ignores the namespace parameter and creates HPA resource with namespace set to default. 

**What you expected to happen**:

Expect to take a parameter for namespace using -n or --namespace and then create a HPA resource for the provided namespace.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl autoscale Deployment/foo --cpu-percent=90 --min=1 --max=4 --dry-run=client -o yaml -n foo`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0",GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:14:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af",GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: EKS

- OS (e.g: `cat /etc/os-release`): mac os Mojave

**Comment by lauchokyip** [comment]
was able to reproduce, will take a look at this

**Comment by lauchokyip** [comment]
@krishnaarava , sorry I was not able to reproduce. Can you reconfirm the issue?

Here is my namespace
```
$ kubectl get namespace
NAME              STATUS   AGE
default           Active   23h
kube-system       Active   23h
kube-public       Active   23h
kube-node-lease   Active   23h
foo               Active   12h
```
and if I do 
```
$ cat << EOF | kubectl apply -n=foo -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
EOF
```
`deployment.apps bar` will be created

To make sure it's not created in the `default` namespace,
```
$ kubectl get deployments.apps
No resources found in default namespace 

$ kubectl get deployments.apps -n foo
NAME   READY   UP-TO-DATE   AVAILABLE   AGE
bar    1/1     1            1           3m46s

```
Then I applied the command,
```
$ kubectl autoscale Deployment/bar --cpu-percent=90 --min=1 --max=4  -o yaml -n foo
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2021-06-03T16:21:21Z"
  managedFields:
  - apiVersion: autoscaling/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:maxReplicas: {}
        f:minReplicas: {}
        f:scaleTargetRef:
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
        f:targetCPUUtilizationPercentage: {}
    manager: kubectl-autoscale
    operation: Update
    time: "2021-06-03T16:21:21Z"
  name: bar
  namespace: foo
  resourceVersion: "40919"
  uid: c9aa8653-990a-47bb-a645-a3b9710340e5
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bar
  targetCPUUtilizationPercentage: 90
status:
  currentReplicas: 0
  desiredReplicas: 0

```
To check if it's in correct namespace
```
$ kubectl get horizontalpodautoscalers.autoscaling 
No resources found in default namespace.
$ kubectl get horizontalpodautoscalers.autoscaling -n foo
NAME   REFERENCE        TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
bar    Deployment/bar   <unknown>/90%   1         4         1          58s
```

**Comment by krishnaarava** [comment]
From the contribution document I can see this repo is not being used for the code changes related to kubectl cli. Its being done in the staging repo https://github.com/kubernetes/kubernetes.  

I was able to reproduce the issue from that repo and created the fix for the change. Will open a PR to the repo https://github.com/kubernetes/kubernetes

```$ go run cmd/kubectl/kubectl.go autoscale --min=1 --max=4 Deployment/elasticsearch --namespace=foo --dry-run=client -o yaml```
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: elasticsearch
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elasticsearch
status:
  currentReplicas: 0
  desiredReplicas: 0
```

**Comment by lauchokyip** [comment]
Left some comments on the PR

**Comment by lauchokyip** [comment]
/retitle kubectl autoscale not outputing namespace during client dry-run
