### ISSUE TITLE
Add `--sum` or `--aggregate` to `kubectl top`

### ISSUE THREAD

**Issue by xuhdev** [kubernetes/kubectl#1061]
**What would you like to be added**: Support `kubectl top deployment [deployment name]` so that we can see the resource usage of each deployment.

**Why is this needed**: We often want to have an idea of the resource usage of each deployment, not only individual pods or nodes.

The metrics server might not allow a direct query of this info, but `kubectl` performing a local summation of the resource usage of all pods in a deployment may be worthy.

**Comment by eddiezane** [comment]
@kubernetes/sig-instrumentation-leads any thoughts on this on a broader scale?

**Comment by dashpole** [comment]
`kubectl top` already supports  `--selector`, which you can use to filter by pods that belong to a deployment.  Would this essentially be a convenience layer on top of that, or are you looking to show statistics for aggregated metrics that are returned as well (e.g. show the sum of all usage, the average % usage, min/max of pod usage, etc.)?

**Comment by xuhdev** [comment]
@dashpole That's a good point! `--sum` or `--aggregate` sound like a better idea!

**Comment by eddiezane** [comment]
/triage accepted
/help
/retitle Add `--sum` or `--aggregate` to `kubectl top`

Thank you! We would accept a PR with David's suggestions.
