### ISSUE TITLE
Cannot add kubectl completion to /etc/bash_completion.d/ No such file or directory

### ISSUE THREAD

**Issue by pssnyder** [kubernetes/kubectl#1063]
I'm going through the instructions to enable kubectl bash completion so I can autocomplete my pod names instead of having to type them out all the time however, when I get to the point of adding the kubectl completion scripts to bash_completion.d directory, it turns out I don't have that directory. Raspbian GNU/Linux version 10 (buster) , Bash version is 5.0.3, kubectl version is 1.20.0, _init_completion is a valid function. The /etc/bash_completion file exists but no directory.

- Add the completion script to the /etc/bash_completion.d directory:

`kubectl completion bash >/etc/bash_completion.d/kubectl`

`bash: /etc/bash_completion.d/kubectl: No such file or directory`

Is something installed wrong or do I just need to create that .d directory for the kubectl completion file? If so do I need to map it in some specific way?

**Comment by lauchokyip** [comment]
Hi @pssnyder , `/etc/bash_completion.d` directory is where you would store your user defined bash completion script. Make sure you create that directory and run `kubectl completion bash >/etc/bash_completion.d/kubectl` again.

**Comment by pssnyder** [comment]
Thanks didn't realize that.
