### ISSUE TITLE
debug: ability to replicate volume mounts 

### ISSUE THREAD

**Issue by rcoup** [kubernetes/kubectl#1071]
**What would you like to be added**:

When debugging by adding a container to a pod, having the ability to match volume mounts with the target container. 

Specifically:
* [Adding a container to a running pod](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container)
* [Copying a pod while adding a new container](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#copying-a-pod-while-adding-a-new-container).

**Why is this needed**:

From a new debug container added to a running pod, I can't access data other containers can see on volume mounts. Obvious candidates: emptyDir, NFS mounts, configmap/secret mounts, EBS volumes, etc

**Ideas**:

1. Replicate some/all volume mounts from one other container
2. Expose all the volumes available to the pod so they can be mounted by name: `--volume-mount=name:/path` There are a lot of options exposed (subPaths, read-only, etc) though to try and cram into a CLI option.

IMO (1) is probably easiest and solves most use cases. Maybe something like:

* `--with-volume-mounts[=<container>]` Container name to attempt to replicate volume mounts from. Without a container name, uses the container from `--target`.

**Comment by verb** [comment]
This fits within the theme of providing a bit more configurability for `kubectl debug`. I'll add it to the list in kubernetes/enhancements#1441 to inform the design.

@rcoup for your use case does accessing the target container's root filesystem via `/proc/$PID/root` work? (assuming linux containers)

**Comment by rcoup** [comment]
> for your use case does accessing the target container's root filesystem via `/proc/$PID/root` work?

I get `ls: cannot access '/proc/7/root/': Permission denied`, so I guess I need https://github.com/kubernetes/kubernetes/issues/97103 resolved first? (or add caps to / make my original pod privileged?)

**Comment by verb** [comment]
That's interesting. no special capabilities are required when `shareProcessNamespace` is `true`, but otherwise `SYS_PTRACE` is required. I didn't realize that.

Ok, so no, this trick doesn't work for your use case.

**Comment by morremeyer** [comment]
/reopen

This is still a viable feature.

**Comment by morremeyer** [comment]
Can a collaborator please reopen this? This is still a feature that would make sense to be implemented.

**Comment by tonyaw** [comment]
@verb, may I ask the schedule of this feature?
I didn't find it in KEP(https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/277-ephemeral-containers)

Thanks in advance!

**Comment by TheDukeDK** [comment]
A good example of the use case for this is the dotnet monitor. It expects to communicate with the dotnet service over a socket mounted in as a volume. See: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md

Being able to use **ephemeral** containers to debug existing pods in a non intrusive way would be a great thing. ;-)

**Comment by NissesSenap** [comment]
Maybe is a separate issue but I would think it would be interesting to extend this functionality even earlier.
Hopefully most of us don't allow writing to root disk inside our containers but all apps don't need /tmp disks or similar to run.

It would be really nice if a debug container also can attach ephemeral disk to a container or maybe even better any volume you want. 
This way you could save some data from your debugging as well, for example profiling.

**Comment by jbg** [comment]
For anyone who (like me) finds this issue while searching for a solution, I wanted to share that you can do this by making a direct patch to the `ephemeralcontainers` subresource, rather than using `kubectl debug`. For example, I needed to mount the same ca-certificates that were mounted in the target container, in the debug container:

```console
$ kubectl proxy
$ curl http://localhost:8001/api/v1/namespaces/your-namespace/pods/your-pod-name/ephemeralcontainers \
  -X PATCH \
  -H 'Content-Type: application/strategic-merge-patch+json' \
  -d '
{
    "spec":
    {
        "ephemeralContainers":
        [
            {
                "name": "debugger",
                "command": ["sh"],
                "image": "your-debug-image",
                "targetContainerName": "your-target-container-name",
                "stdin": true,
                "tty": true,
                "volumeMounts": [{
                    "mountPath": "/etc/ca-certificates",
                    "name": "ca-certificates",
                    "readOnly": true
                }]
            }
        ]
    }
}'
$ kubectl -n your-namespace attach your-pod-name -c debugger -ti
```

**Comment by nathanmcgarvey-modopayments** [comment]
> For anyone who (like me) finds this issue while searching for a solution, I wanted to share that you can do this by making a direct patch to the `ephemeralcontainers` subresource, rather than using `kubectl debug`. For example, I needed to mount the same ca-certificates that were mounted in the target container, in the debug container:
> 
> ```
> $ kubectl proxy
> $ curl http://localhost:8001/api/v1/namespaces/your-namespace/pods/your-pod-name/ephemeralcontainers \
>   -X PATCH \
>   -H 'Content-Type: application/strategic-merge-patch+json' \
>   -d '
> {
>     "spec":
>     {
>         "ephemeralContainers":
>         [
>             {
>                 "name": "debugger",
>                 "command": ["sh"],
>                 "image": "your-debug-image",
>                 "targetContainerName": "your-target-container-name",
>                 "stdin": true,
>                 "tty": true,
>                 "volumeMounts": [{
>                     "mountPath": "/etc/ca-certificates",
>                     "name": "ca-certificates",
>                     "readOnly": true
>                 }]
>             }
>         ]
>     }
> }'
> $ kubectl -n your-namespace attach your-pod-name -c debugger -ti
> ```

FWIW, I made a shell (zsh, at least) function that copies environment variables, envFrom configuration, and volume mounts and does this manually via a kubectl, jq, and curl commands. Note that the image is hardcoded to alpine:latest, but that's easily changed:

https://gist.github.com/nathanmcgarvey-modopayments/358a84297086de3975f54895a9e7123d

**Comment by bh-tt** [comment]
Can I request that ephemeralcontainers be added to the allowed subresources of Pods for `kubectl patch`? This makes the above 3 steps a bit easier as one can simply run `kubectl patch --type=merge --patch-file=<file>` and then attach, instead of needing to run kubectl proxy as well (which creates a local port, anyone on the same server can send API requests as the person running kubectl proxy).

**Comment by ardaguclu** [comment]
This will be handled with https://github.com/kubernetes/kubernetes/pull/120346 and I'm closing because we'll track this feature from the KEP;
/close

**Comment by bavarianbidi** [comment]
> Sorry to necro this but in the end how do we achieve this functionality ? Its not clear to me if this was implemented or not.
> 
> Cheers
> B.

assuming your POD has a volume named `app-config` you can spin a debug pod with the following command and the attached json saved as `app-profile-config.json`

```
KUBECTL_DEBUG_CUSTOM_PROFILE=true kubectl debug --image=nicolaka/netshoot:v0.13 --custom debug-profiles/app-profile-config.json $(POD) -it
```

```json
{
    "volumeMounts": [
        {
            "mountPath": "/app/config",
            "name": "app-config",
            "readOnly": true
        }
    ],
    "securityContext": {
        "capabilities": {
            "add": [
                "CAP_NET_ADMIN"
            ]
        }
    },
    "env": [
        {
            "name": "DEMO",
            "value": "Hello Conference"
        }
    ]
}
```

brw: as you need a bunch of args, i've created a kubectl plugin to make it more easier to work with debug profiles - https://github.com/bavarianbidi/kubectl-dpm/tree/main

**Comment by aviallon** [comment]
@bavarianbidi is there a way to do something like `kubectl debug pvc/the-pvc-holding-bad-application-state --image busybox`?
The problem is, how do I debug an init container that is immediately crashing because of bad state, without destroying the pod (and preventing it from restarting)?

**Comment by bavarianbidi** [comment]
Hey @aviallon , sorry for the late reply.

in the end it's quite simple, just attach a debug container to your pod.
As the `pvc` is mounted on the corresponding node and the `cgroup` and all the internal stuff already happend, you can attach an ephemeral container directly to your failed pod.

Here is one example:

given a pod where the init-container is immediately crashing:

```k get pod -l run=dev
NAME                   READY   STATUS                  RESTARTS      AGE
dev-68c4465b84-vsl8v   0/1     Init:CrashLoopBackOff   4 (31s ago)   2m4s
```

and you are interested in some files from the pvc ...

create a debug-profile like the following:

```json
{
    "volumeMounts": [
        {
            "mountPath": "/data",
            "name": "task-pv-storage"
        }
    ]
}
```

and run `kubectl debug --namespace default --custom <PATH_TO_YOUR_JSON_PROFILE>.json --image nicolaka/netshoot:v0.14 <POD_TARGET> -it` and you are able to read the data without manipulating the failed pod.

See below deployment example (to match the pv-names, etc...)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dev
  template:
    metadata:
      labels:
        run: dev
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ["sh", "-c", "exit 1"]
          volumeMounts:
            - name: app-config
              mountPath: /conf
            - mountPath: /data
              name: task-pv-storage
      containers:
        - image: localhost:5000/demo-app:latest
          args: ["-metric=127.0.0.1:9090", "-template=/conf/index.tmpl"]
          name: webapp
          volumeMounts:
            - name: app-config
              mountPath: /conf
            - mountPath: /data
              name: task-pv-storage
      volumes:
        - name: app-config
          configMap:
            name: app-config
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
```

**Comment by aviallon** [comment]
@bavarianbidi I remember trying something like that, but somehow, the debug pod failed to start.

What I ended up doing is attaching a super privileged pod to the node itself, and modifying the data by directly modifying the contents of the mounted PV.
