### ISSUE TITLE
Resources in namespaces with a label match/pattern should be listed 

### ISSUE THREAD

**Issue by cihangirbesiktas** [kubernetes/kubectl#1074]
**What would you like to be added**:
I would like `kubectl get` to have a new parameter (e.g. `--namespace-selector`) to list resources in namespaces with the given namespace label.

For example, `kubectl --namespace-selector type=apps get pods` should get all the pods in namespaces which have the label `type: apps`.

**Why is this needed**:
Namespaces can be grouped based on namespace labels, and this will make it possible to list resources belonging to the group of namespace.

**Comment by rikatz** [comment]
@cihangirbesiktas thanks for your issue and idea.

We've discussed this issue during sig-cli bug scrub/triage, and found that while implementing this into kubectl codebase may lead into some performance issues (mainly the recursion over all namespaces and performance loading).

The main "problem" here is that for client side, we should do that recursion over namespaces, while when you proper use "selectors" that already exists (like kubectl get pods -l env=prod) this is processed and returned by the API Server, so this filtering is not done on client side, but on API server side.

There are some ways to do this:

* A plugin can be implemented to this specific case, like "kubectl get-ns-label" or something like that
* Labels are costless for objects, so you can make use of some controller that automatically applies labels into your resources. There are a number of "articles" explaining this, like [Using Kyverno](https://www.cncf.io/blog/2020/12/30/auto-labeling-kubernetes-resources-with-kyverno/) that is an admission webhook (so resources gets automatically labeled) or the most recent [article](https://kubernetes.io/blog/2021/06/21/writing-a-controller-for-pod-labels/) in Kubernetes blog that teaches you how to write a controller

To be honest, we really think there's something already ready outside there :)

I will close this issue, and have added the label of "needs-plugin-prototype" so we can announce for anyone willing to develop this, but if you have any question please feel free to reopen or comment here.

/close
