### ISSUE TITLE
'kubectl exec --tty --stdin' "leaking" proccess inside pod when terminated

### ISSUE THREAD

**Issue by xelxebar** [kubernetes/kubectl#1076]
## Overview

When stopping a local `kubectl exec` process without explicitly exiting the spawned in-pod process, the latter remains running inside the pod. I am unsure whether the `--tty --stdin` flags are relevant.

## Reproducing

Explicitly, the issue I am seeing is a bash process left over inside the pod after going through a procedure like the following:

1. Launch a bash shell inside some pod

```
local$ kubectl exec -ti some-pod -- bash
some-pod# echo $$
<pid>
```

2. Kill above `kubectl` process (*e.g.* by closing terminal, explicit `kill`, *etc.*)

3. Verify that the above `<pid>` still remains inside the pod:

```
local$ kubectl exec -ti some-pod -- bash
some-pod# echo /proc/<pid>/*
```

## Expected Behaviour

I am quite new to k8s overall, so if this is just a naive user error, please forgive the spam. What I expect to happen is for the in-pod `bash` process to also terminate when `kubectl` terminates.

This issue is occurring within the large dev team of my organization. Due to developers running `kubectl exec` under WSL and closing windows instead of properly exiting bash, we are left with pods having hundreds of "trash" processes sticking around. Some of these lingering processes end up tying up resources unexpectedly and causing errors in our application.

## Thoughts

Above, the local `kubectl` process receives `SIGTERM` or `SIGSTOP` depending on how it's killed. On a local machine spawning local processes, one would expect the in-pod "child process" to recieve SIGCHLD and terminate (or handle) accordingly.

Setting `trap 'echo CHLD >test.log' CHLD` within the in-pod `bash` process above confirms that `SIGCHLD` fails to propagate. Does this sound correct? Is this intended?

**Comment by eddiezane** [comment]
@dims any thoughts on this one from docker/containerd upstream?

**Comment by dims** [comment]
@eddiezane if we can recreate using just containerd, we could file a issue in containerd repository

**Comment by soltysh** [comment]
The problem itself is beyond kubectl itself. I'm suggesting to investigate this and open the issue with appropriate container engine. kubectl relies heavily on that behavior for this one.

/close

**Comment by sgielen** [comment]
For future reference - I believe the containerd side of this issue is https://github.com/opencontainers/runc/issues/3359 ?
