### ISSUE TITLE
Publish “kubectl convert” plugin as part of OS packages

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubectl#1079]
**What would you like to be added**:
per https://github.com/kubernetes/website/pull/28740#issuecomment-878418393:
> &hellip;would be nice to have [`kubectl convert`] part of kubectl Yum/Deb repos&hellip;

**Why is this needed**:
When people install `kubectl` using Yum / APT / snap / Chocolatey / `brew` / whatever, they might reasonably expect that `kubectl convert` “just works”.

/sig release

**Comment by eddiezane** [comment]
Package managers are considered out of scope of the project. We provide binaries and rely on the community to handle distribution via their favorite mechanisms.

Anyone looking for advice on getting these changes made can swing by sig-cli on Slack and we might be able to point people in the right direction.

/close
