### ISSUE TITLE
Container in a pod can't get configured to the defined port in the yaml file 

### ISSUE THREAD

**Issue by abcd-ABCD-1234** [kubernetes/kubectl#1081]
**What happened**: I am running kubectl via minikube, and created a single container in a pod using yaml file. Pod got created and container is in running state too. I configured port 5432 to the container in the yaml file, but the container actually is not running on port 5432. 

**What you expected to happen**: Container in a port should run on the port configured in the configuration file.

**How to reproduce it (as minimally and precisely as possible)**:
Here is my yaml file:
~~~
apiVersion: v1
kind: pod
metadata:
  name: first-pod
  labels:
    apps: first-pod
spec:
  containers:
    - name: first-container
      image: postgres:12.1
      ports:
      - containerPort: 5432
~~~
1. Created the pod using : `kubectl create -f config-pod.yaml`
2. Entered into the container using: `kubectl exec -it first-pod -c first-container bash`
3. Installed net-tools, and ran the command: `netstat -ln`
4. Below is the output of `netstat -ln` :
~~~
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
~~~ 
As can be seen, no port has been configured here with my container.

**Anything else we need to know?**: I also entered minikube using `minikube ssh`, and entered : `docker ps`. I could see the container name and that it is running, but the port was blank.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 64 bit Ubuntu system with 64 GB RAM.
- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by eddiezane** [comment]
Kubernetes pods are not accessible outside of the cluster without a service to expose them.

Take a look at the minikube tutorial https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service.

/triage support
/close
