### ISSUE TITLE
"kubectl auth can-i" miss documentation for "--as" parameter

### ISSUE THREAD

**Issue by saryeHaddadi** [kubernetes/kubectl#1082]
**What would you like to be added**: 
- When running`kubectl auth can-i -h`, make mention that the `--as=` parameter is possible.
- When running`kubectl auth can-i -h`, display two examples of the usage of the `--as=` parameter, one for a normal user, and another one for a service account located in a particular namespace.

**Why is this needed**:
- The `--as` parameter is missing in the CLI help doc.
- The usage of  `--as` with a service account is not straight forward for a beginner, given that some prefixes should be mentioned before the actual name of the service account (eg. `--as system:serviceaccount:namespace:name`)

**Comment by lauchokyip** [comment]
`--as` is a global flag that does not just apply to `kubectl auth can-i` that's why you can't find it. Try,
```
kubectl options
``` 

That being said, if the description needs to be improved, one can find where to change over [here](https://github.com/kubernetes/kubernetes/blob/33aba7ee025dfddcc140d20e9ca353ffd425f1ae/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L288)

**Comment by eddiezane** [comment]
There's a pretty detailed explanation of this in the docs https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation.

**Comment by eddiezane** [comment]
We can probably add a link to that docs page in the command description or examples.

Something like "This command pairs nicely with impersonation. See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation."

@chrisnegus want to grab this one?

https://github.com/kubernetes/kubernetes/blob/33aba7ee025dfddcc140d20e9ca353ffd425f1ae/staging/src/k8s.io/kubectl/pkg/cmd/auth/cani.go#L75

**Comment by orsenthil** [comment]
I took the suggestions, and made the code change here - https://github.com/kubernetes/kubernetes/pull/103791

The docs itself has an example of impersonation using `--as` here - https://github.com/kubernetes/website/blob/main/content/en/docs/reference/access-authn-authz/authorization.md#checking-api-access

**Comment by saryeHaddadi** [comment]
Thank you all very much for the explanation and the links, and happy that this issue was found valuble and made its way to the official code.

I have less than a year xp on Kubernetes, if my feedback might interest you as a new K8s user, even though `--as` is a global parameter, all the examples I have seen so far used `--as` paired with`kubectl auth can-i`, so that's why I expected to see at least the keyword `--as` in the CLI documentation of `can-i`.
