### ISSUE TITLE
Use compression in `cp` command

### ISSUE THREAD

**Issue by tpvasconcelos** [kubernetes/kubectl#1084]
**What would you like to be added**:
Apply compression/decompression when using the `cp` command to copy files and directories to and from containers.

The current `cp` command (when used in the context of copying files **from** a container) seems to have similar behavior to
```shell
kubectl exec mypod -- tar cf - /target/dir | tar xf -
```

The feature that I am suggesting is analogous to adding a `z` flag in order to compress/decompress the tarball.
```shell
kubectl exec mypod -- tar czf - /target/dir | tar xzf -
```
It seems that this feature was [considered](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/cp/cp.go#L405) but never implemented?

**Why is this needed**:
Faster transfer times when using the `cp` command.

**Comment by eddiezane** [comment]
There is a bunch of history behind this.

Checkout https://github.com/kubernetes/kubernetes/issues/58512 for context.

We just need someone to own creating a KEP to move this to the CRI.

/triage duplicate
/close
