### ISSUE TITLE
kubectl fails to parse parameters correctly when using full width space

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/kubectl#1085]
**What happened**:
kubectl fails to parse parameters correctly when using full width space

For example:
```sh
➜  ~ kubectl get pod -n 　 prow
Error from server (NotFound): namespaces "\u3000" not found
➜  ~ kubectl get pod -n　prow
No resources found in 　prow namespace.
➜  ~
```

**What you expected to happen**:

Is there any way we can indicate that an invalid space is being used? Or do we it detects the argument that follows and then warns?  Maybe cobra doesn't have such a feature?

**How to reproduce it (as minimally and precisely as possible)**:

```sh
kubectl get pod -n　prow
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```sh
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.700", GitCommit:"8924a6876b2ff4905020e178132365eca3164869", GitTreeState:"clean", BuildDate:"2021-06-28T09:20:44Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```sh
➜  ~ neofetch
                    'c.          rustin@Rustins-MacBook-Pro.local
                 ,xNMM.          --------------------------------
               .OMMMMo           OS: macOS Catalina 10.15.7 19H1217 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 19.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 6 days, 5 hours, 43 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 127 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.7.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Monaco 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i9-9980HK (16) @ 2.40GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, AMD Radeon Pro 55
       .cooc,.    .,coo:.        Memory: 20750MiB / 32768MiB
```

**Comment by hi-rustin** [comment]
I'm not sure if this is the expected behavior, it looks like it parses the full width space and then discards the arguments that follow.

**Comment by eddiezane** [comment]
I imagine this is a cobra thing? Can you provide context on why you are using this character?

**Comment by hi-rustin** [comment]
> I imagine this is a cobra thing? Can you provide context on why you are using this character?

Because I use both Chinese and English, sometimes I may accidentally switch to full width when switching input methods.

**Comment by hi-rustin** [comment]
We could perhaps use noargs to report errors? That would make it less weird?

**Comment by eddiezane** [comment]
I think [`unicode.IsSpace`](https://pkg.go.dev/unicode#IsSpace) is used under the hood which would explain why `\u3000` doesn't register.

I'm not sure `cobra.NoArgs` would help here. Looks like it's used to reject all args for a command?

https://github.com/spf13/cobra/blob/56060d19f88533a20f635116f64aff2065cf260a/args.go#L27-L28

**Comment by hi-rustin** [comment]
Yes, I misunderstood and closed it. I'll keep an eye out for strange characters later.

**Comment by hi-rustin** [comment]
Thanks for your help!
