### ISSUE TITLE
[Enhancement Request] Regex parsing for deleting pods 

### ISSUE THREAD

**Issue by Rubix982** [kubernetes/kubectl#1086]
**What would you like to be added**:

I would like to eliminate and delete multiple pods all together using regex parsing. For example, if I have the following results from `kubectl get pods`,

```bash
NAME                            READY   STATUS                 RESTARTS   AGE
go-helloworld-fcd468f98-xj57q   1/1     Running   0          XmYs
go-helloworld-fcd468f98-x62g9   1/1     Running   0          XmYs
go-helloworld-fcd468f98-xk2gq   1/1     Running   0          XmYs
go-helloworld-fcd468f98-xk2gq   1/1     Running   0          XmYs
```

I would like to remove them all together with the following syntax,

```bash
localhost:/home/vagrant # kubectl delete pod go-helloworld*
```

Where the `*` selector works similar to regex.

I could not find a way to only get the names of the results from `kubectl get pods`. I would imagine it can also work something like,

```bash
localhost:/home/vagrant # kubectl delete pod $(kubectl get pods --suffix=go-helloworld)
```

**Why is this needed**:

Mentioning every pod by itself seems cumbersome.

Thank you.

**Comment by eddiezane** [comment]
Cheers @Rubix982,

I don't think is something we'd want to implement. I could see this introducing a footgun to accidentally delete things.

You could use:

```
kubectl delete $(kubectl get pods -o name | grep go-helloworld)
```

Or jq which is powerful but more verbose:

```
kubectl delete pods $(kubectl get pods -o json | jq -r '.items[].metadata.name | select(contains("go-helloworld"))')
```

**Comment by Rubix982** [comment]
I think this will work just as fine as well,

```
kubectl delete $(kubectl get pods -o name | grep go-helloworld)
```

Thanks, @eddiezane! Closing.
