### ISSUE TITLE
can kubectl return an error code when attempting to submit a tfjob but gpus are not available?

### ISSUE THREAD

**Issue by rbavery** [kubernetes/kubectl#1089]
I see "Pod Unschedulable, insufficient nvidia" in the Workloads UI for Google Cloud but there's no error code returned by kubectl. This is what I ran

```
→ kubectl create -f poi-detector/tf_job/ssd_mobilenet_v1_fpn_schools.yml
tfjob.kubeflow.org/ssd-mobilenet-v1-fpn-schools-test created
```

**Comment by eddiezane** [comment]
@rbavery that sounds like the workload can't be scheduled which kubectl wouldn't return an error for. The cli is responsible for sending the workload to the api server and reports on whether it was received or not.

I'm not familiar with kubeflow but you could try looking at the events of the resource.

```
kubectl describe tfjob.kubeflow.org/ssd-mobilenet-v1-fpn-schools-test
```

My guess is that it's looking for a worker node labeled for an Nvidia GPU which you probably don't have.

**Comment by eddiezane** [comment]
Let me know if that doesn't make sense.

/close
