### ISSUE TITLE
kubectl create clusterrolebinding -o yaml shouldn't create a binding

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubectl#109]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

clusterrolebinding

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Kubernetes version** (use `kubectl version`):
```console
$ ./cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1890+b00c15f1a40162-dirty", GitCommit:"b00c15f1a40162d46fc4b96f4e6714f20aef9e6c", GitTreeState:"dirty", BuildDate:"2017-10-27T17:43:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1890+b00c15f1a40162-dirty", GitCommit:"b00c15f1a40162d46fc4b96f4e6714f20aef9e6c", GitTreeState:"dirty", BuildDate:"2017-10-27T17:43:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
`kubectl create clusterrolebinding -o yaml` is creating cluster role binding in addition to output it to the console:

```console
$ kubectl create clusterrolebinding test-binding --clusterrole=restricted-psp-user --user=joe -o yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2017-10-27T18:12:06Z
  name: test-binding
  resourceVersion: "1815"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/test-binding
  uid: 573abbeb-bb42-11e7-8b10-507b9d2b16b9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-psp-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: joe
$ kubectl create clusterrolebinding test-binding --clusterrole=restricted-psp-user --user=joe -o yaml
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "test-binding" already exists
```

**What you expected to happen**:
It shouldn't create a binding and only show the YAML document.

**How to reproduce it** (as minimally and precisely as possible):
Execute the `kubectl create clusterrolebinding test-binding --clusterrole=restricted-psp-user --user=joe -o yaml` command twice.

**Comment by php-coder** [comment]
`-o` option should imply `--dry-run` option.

**Comment by php-coder** [comment]
I'm also surprised that it uses `rbac.authorization.k8s.io/v1beta1` instead of `rbac.authorization.k8s.io/v1` for `apiVersion`.

**Comment by wackxu** [comment]
Actually, in all `create resource` command, `-o`  option doesn't imply  `--dry-run`  flag true, I think it is the just design purpose. and in my environment I try servral times and  it always use the  `rbac.authorization.k8s.io/v1` for `apiVersion`,I can not recurrent it.

**Comment by apelisse** [comment]
I agree with @wackxu that -o changes the way things are printed, not what is performed.

Feel free to close the issue, or I'll do it in a week or so if you're fine with that @php-coder

**Comment by php-coder** [comment]
Ok, probably you are right.
