### ISSUE TITLE
Migrate config to use a YAML file extension

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubectl#1090]
**What would you like to be added**:

Please transition the configuration file `config` to `config.yaml`.

**Why is this needed**:

Lacking a file extension, the `config` path is not able to highlight correctly in many text editors.

**What about comment hints?**

Some users will instinctively reach for the "But you can always use comments to force the parser." In fact, many important Kubernetes integrations such as awscli for the Elastic Kubernetes Service, drop comments during authentication setup. The file is treated as a machine-generated file in such cases. So no, this is not a reliable option.

Generally, having to write two additional lines, one for Vim-style parser hinting and one for Emacs-style parser hinting, is more often a code smell of a larger problem: Bad file name patterns.

**Comment by eddiezane** [comment]
@dougsland @rikatz what do y'all think about this?

ref: https://github.com/kubernetes/enhancements/issues/2229

**Comment by dougsland** [comment]
> @dougsland @rikatz what do y'all think about this?
> 
> ref: [kubernetes/enhancements#2229](https://github.com/kubernetes/enhancements/issues/2229)

From previous experience, this won't fly (see kubernetes/enhancements#2229) . Users can always do a symbol link.

**Comment by soltysh** [comment]
Based on what @dougsland pointed out this won't be easy nor accepted.
/close
