### ISSUE TITLE
Typo on kubectl describe documentation

### ISSUE THREAD

**Issue by aaronlidman** [kubernetes/kubectl#1091]
https://github.com/kubernetes/kubectl/blob/0f88fc6b598b7e883a391a477215afb080ec7733/pkg/cmd/describe/describe.go#L65

is missing "ds".

It should read `kubectl describe pods -l name=myLabel`.

**Comment by rikatz** [comment]
Hi @aaronlidman and thanks for your issue.

Actually the description is right, as "po" is a shorthand for "pods" in kubectl commands.

You can check it with kubectl describe po your-pod-name and kubectl get po your-po-name

I'm closing this issue, but feel free to re-open if still think this is wrong :)

/close
