### ISSUE TITLE
`kubectl config` hides input errors

### ISSUE THREAD

**Issue by tewe** [kubernetes/kubectl#1092]
I tried to "log out" using `kubectl config unset users.foo.auth-providers.azure.refresh-token`.

**What happened**:

Exit code 0 with the following message, but absolutely no change to the configuration file.

> Property "users.foo.auth-providers.azure.refresh-token" unset.

**What you expected to happen**:

Non-zero exit code and an error message. Either because I mistyped `auth-provider` with a plural S or because no user called "foo.auth-providers.azure.refresh-token" exists.

**How to reproduce it (as minimally and precisely as possible)**:

Type any garbage after `kubectl config unset users.`

**Anything else we need to know?**:

The place to fix this would be the map key guessing game in `pkg/cmd/config/navigation_step_parser.go`, but I can't think of a way that wouldn't **introduce proper escaping/quoting**.

**Environment**:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"**v1.21.1**", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by eddiezane** [comment]
Let's track this in #1093. Should be the same fix.

/close

**Comment by tewe** [comment]
Note that this can be reproduced even when `auth-providers` is misspelled, so a fix just for #1093 would not help. But of course when that code is touched it makes sense to fix both things.
