### ISSUE TITLE
kubectl create secret: Support multiple --from-env-file flags

### ISSUE THREAD

**Issue by KnVerey** [kubernetes/kubectl#1094]
**What would you like to be added**: Same as https://github.com/kubernetes/kubectl/issues/1033, but for `kubectl create secret` as well. 

**Why is this needed**: These two creation commands both have the flag in question, so it should continue to behave the same way, i.e. it needs to be made repeatable on both.

/assign @lauchokyip 
/triage accepted
/sig cli

**Comment by lauchokyip** [comment]
Thanks!
