### ISSUE TITLE
Support length in JSONPath

### ISSUE THREAD

**Issue by leobellaera** [kubernetes/kubectl#1099]
**What happened**: I run the following cmd `kubectl get crd --selector="svcat=true" -o=jsonpath='{.items[0].spec.names.categories.length()`

**What you expected to happen**: I expected the command to return the length of the categories list, as JSONPath has [length function defined](https://github.com/json-path/JsonPath#functions)

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client: 1.20 - Server: 1.16

**Comment by eddiezane** [comment]
After discussing we recommend you use jq here. It will have much more features than are basic jsonpath implementation.

/close
