### ISSUE TITLE
Refactor kubectl run + expose and kubectl create xxx to use shared code

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#11]
The `kubectl run` and `kubectl expose` commands can be used to create various workloads and services.  `kubectl create xxx` commands can also create the same resources, but use different code and have support for different flags.

Refactor the commands that create the same objects to use common code and bring feature parity

**Comment by alexandercampbell** [comment]
@pwittrock I assume that the syntax and options of `kubectl {run,expose}` must remain identical. Can you confirm?

**Comment by alexandercampbell** [comment]
For what it's worth, `kubectl create`, `kubectl run`, and `kubectl expose` generally diverge to the same codepath already (by calling generate).


| command | generate call |
| - | - |
| `create` | [`obj := options.StructuredGenerator.StructuredGenerate()`](https://github.com/kubernetes/kubernetes/blob/012ffed6d3e3222e0e004e1edf60e7bc814546f4/pkg/kubectl/cmd/create.go#L254) |
| `run` | [`obj := createGeneratorObject()`](https://github.com/kubernetes/kubernetes/blob/012ffed6d3e3222e0e004e1edf60e7bc814546f4/pkg/kubectl/cmd/run.go#L262) |
| `expose` | [`object := generator.Generate()`](https://github.com/kubernetes/kubernetes/blob/012ffed6d3e3222e0e004e1edf60e7bc814546f4/pkg/kubectl/cmd/expose.go#L227) |

I can do some consolidation of the duplicated error checking (example: [first](https://github.com/kubernetes/kubernetes/blob/012ffed6d3e3222e0e004e1edf60e7bc814546f4/pkg/kubectl/cmd/run.go#L238-L239), [second](https://github.com/kubernetes/kubernetes/blob/012ffed6d3e3222e0e004e1edf60e7bc814546f4/pkg/kubectl/cmd/create_deployment.go#L83-L84)) but if compatibility must be maintained, these functions won't get much shorter.

**Comment by alexandercampbell** [comment]
Differences in available flags when you switch from `kubectl run` to `kubectl create deployment`:
https://gist.github.com/alexandercampbell/c7e34370e48bc5d7b33c7a0680b7bbe6

**Comment by pwittrock** [comment]
Awesome:

What should add the following to the create command.  We should figure out how to test this so it doesn't get worse again.  Maybe create a white list of flags that can differ, and enforce that all the other flags present in `run` exist for `create`

- attach=false
- command=false
- env=[]
- hostport=-1
- image-pull-policy=''
-image
  - why doesn't the format match?  We should make it match.
- include-extended-apis=true
  - don't know what this does, we should figure it out
- leave-stdin-open=false
- limits=''
- no-headers=false
- overrides=''
- pod-running-timeout=1m0s
- port=''
---quiet=false
- record=false
- requests=''
  - don't know what this does, we should figure it out
- restart='Always'
- rm=false
  - don't know what this does, we should figure it out
- save-config=false
- schedule=''
  - don't know what this does, we should figure it out
- show-labels=false
  - don't know what this does, we should figure it out
- sort-by=''
  - don't know what this does, we should figure it out
- i, --stdin=false
- l, --selector=''
  - don't know what this does, we should figure it out
- r, --replicas=1
- t, --tty=false

**Comment by alexandercampbell** [comment]
@pwittrock I've made progress in one of my branches at consolidating the common options to a common struct. I like the idea of the whitelist, good call.

**Comment by alexandercampbell** [comment]
FYI `include-extended-apis` is [deprecated](https://github.com/kubernetes/kubernetes/blob/ec1fcbed74846a9ab17dc83c7ff8a28a3f1710e4/pkg/kubectl/cmd/util/helpers.go#L613-L616).

**Comment by alexandercampbell** [comment]
The "kubectl run" flags I will be porting to "kubectl create deployment" are:

1. command
2. env
3. hostport
4. image-pull-port
5. labels
6. limits
7. port
8. replicas
9. requests

We do not want to support the "--expose" family of flags in "create deployment".
Thanks @janetkuo for helping me come up with this list.

**Comment by shiywang** [comment]
@pwittrock @alexandercampbell I'm not sure if @adohe still working on this  https://github.com/kubernetes/kubernetes/pull/44936 , if not could we also continue his work in this pr?

**Comment by alexandercampbell** [comment]
@shiywang thank you for linking me to that PR! I knew a separation of that kind was being discussed but I was not aware anyone had begun coding.

After a quick look it doesn't look like it will interfere too much with my work on this issue. The work I am doing here is more compatibility between the commands than it is a code quality improvement.

**Comment by shiywang** [comment]
@alexandercampbell ok, you are welcome

**Comment by alexandercampbell** [comment]
I have a branch where I have implemented three of these flags: `--labels`, `--replicas`, `--env`

I will open a PR as soon as https://github.com/kubernetes/kubernetes/pull/48950 is merged. A couple of things have come up during implementation:

1. I can't add `--port` unless we add service support to "kubectl create deployment", which we've already decided is a bad idea.
2. I *could* add `--command` but it would have to be an array because we support multiple deployment images. It would look something like this: `k create deploy --images img1,img2 --command cmd1,cmd2`. Thoughts?

**Comment by alexandercampbell** [comment]
Finished implementing `--requests` and `--limits`.
My branch is here: https://github.com/kubernetes/kubernetes/compare/master...alexandercampbell:kubectl-add-remaining-flags-to-create-deployment?expand=0

**Comment by alexandercampbell** [comment]
After a quick discussion with @pwittrock I'm going to try implementing `--command` but validated so that it will be rejected unless the number of images is exactly 1. This way you can still perform the functionality of "run".

**Comment by pwittrock** [comment]
cc @kubernetes/sig-cli-feature-requests

**Comment by prksu** [comment]
> I have a branch where I have implemented three of these flags: `--labels`, `--replicas`, `--env`
> 
> I will open a PR as soon as [kubernetes/kubernetes#48950](https://github.com/kubernetes/kubernetes/pull/48950) is merged. A couple of things have come up during implementation:
> 
> 1. I can't add `--port` unless we add service support to "kubectl create deployment", which we've already decided is a bad idea.
> 2. I _could_ add `--command` but it would have to be an array because we support multiple deployment images. It would look something like this: `k create deploy --images img1,img2 --command cmd1,cmd2`. Thoughts?

@alexandercampbell @janetkuo why adding `--port` or `--expose` is a bad idea in here?

i have an idea for dealing with multiple deployment images. currently `--image` is StringSlice, how about change it to StringArray and then we matching the first `--image` with first `--port` flag as first container and second `--image` with second `--port` flag as second container (i use example --port, it can be any flag that parsed to podSpec). `--image` will not accept separated by `,`

So `kubectl create deployment mydep --image=nginx --port=8000 --image=mysql --port=3306 --dry-run -o yaml` will generated like this

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydep
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8000
        resources: {}
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
status: {}
```

cc @pwittrock @soltysh @seans3
