### ISSUE TITLE
Kubectl version command enhancement 

### ISSUE THREAD

**Issue by backtrackshubham** [kubernetes/kubectl#1102]
**What would you like to be added**: 
- Command `kubectl version` shall only return version information rather it also tries to access cluster, which is not expected
- **Current Behaviour**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
- **Expected behaviour**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```

**Why is this needed**:
- Upon running the above command even though by semantics the command got successfully executed but the shell output variable `$?` is getting a non-zero value, hence not only it would help there but also adhere to the semantics of command `kubectl version` given `kubectl` being a client for K8.

**Comment by jaehnri** [comment]
If this issue gets the `triage/accepted` label, I would like to give it a try. 
Thanks!

**Comment by eddiezane** [comment]
As João pointed out this is the expected behavior. If you're looking for just the client version please pass the flag.

/close
