### ISSUE TITLE
kubectl cp fails with Error unexpected EOF

### ISSUE THREAD

**Issue by shanmukha511** [kubernetes/kubectl#1103]
**What happened**:
**Copying either a large file, or a large directory from one pod to other pod via kubectl cp results in the error of 
Error: unexpected EOF and a failure to transfer.**

**What you expected to happen**:

The file has to be copied successfully from one pod to other pod successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Copy some large files between pods and may get the EOF error

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", Git
TreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.900", GitCommit:"1facb91642e16cb4f5be4e4a632c488aa470
0382", GitTreeState:"clean", BuildDate:"2021-06-28T09:19:58Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}     
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
- Cloud provider or hardware configuration:
GKE 1.18.20-gke

- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
Cheers @shanmukha511,

Your kubectl version is out of support for your cluster version.

> WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

Please update your client and provide more information for us to reproduce if you still encounter this.

/triage needs-information

**Comment by shanmukha511** [comment]
Hi @eddiezane,

my server version 1.18 and i used kubectl version earlier 1.17,1.18 and 1.19 as well to ensure new updated versions has fix for that issue but nothing helped much before version. So updated to 1.21.
None of kubectl version (1.18,1.19,1.20) not fixing the issue.
If u want i can revert backup to older version kubectl but i doesnt help much.

**Comment by eddiezane** [comment]
I am not able to reproduce this and suspect it might be an environment issue. I was able to copy a 10gb file back and forth a few times without issue.

What else can you share to help us reproduce?

**Comment by shanmukha511** [comment]
Hi @eddiezane,

Even we can copy 100's GB data between pods most time but there are some times were we get into issue.The error intermittent.
Is ther any way from kubectl that we can resume copy where it had got stopped?

**Comment by nnseva** [comment]
TWIMC

I have had this problem trying to copy files from/to server 1.19+ using client 1.22.

```
seva@SEVA-WORK:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```
It disappeared when I've downgraded the client to the version corresponding to the server:

```
seva@SEVA-WORK:~$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by almson** [comment]
This is a common issue, see https://stackoverflow.com/questions/67624630/unable-to-copy-data-from-pod-to-local-using-kubectl-cp-command
