### ISSUE TITLE
Install kubectl via the new winget package manager

### ISSUE THREAD

**Issue by psmorandi** [kubernetes/kubectl#1105]
**What would you like to be added**:
Possibility to install kubectl with the new package manager for windows (winget).

**Why is this needed**:
It's easier to use then other package managers and also soon it will available by default in windows machines.

**Comment by eddiezane** [comment]
Cheers @psmorandi,

Please see https://github.com/kubernetes/kubectl/issues/968#issuecomment-725604167.

/triage duplicate
/close
