### ISSUE TITLE
`kubectl config set-credentials` should support impersonations fields

### ISSUE THREAD

**Issue by jutley** [kubernetes/kubectl#1106]
**What would you like to be added**:
The `AuthInfo` struct contains fields `Impersonate`, `ImpersonateGroups`, and `ImpersonateUserExtra`, which are defined in YAML with the fields `as`, `asGroups`, and `asUserExtra` (not sure on the casing). The `kubectl config set-credentials` should allow us to set these fields, as it allows for every other field.

**Why is this needed**:
Most, if not all other fields are able to be defined with `kubectl config set-credentials`. This enhancement works towards completeness, and also allows users to fully configure their kubeconfig without having to use additional utilities.

**Comment by eddiezane** [comment]
There is a `kube config set users.my-user.act-as admin` (you'd use the [json value](https://github.com/kubernetes/kubernetes/blob/1c1d2e4edca391805db4a944c93d611081d9145e/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go#L126)) command but that unfortunately would not work with slices or maps.

https://github.com/kubernetes/kubernetes/blob/8975906dfc87732e063bb30e36b181a031988a52/staging/src/k8s.io/kubectl/pkg/cmd/config/set.go#L153-L197

We'd rather see the `set` expanded than add more flags. There may already be an issue tracking that..

**Comment by jutley** [comment]
Is there any documentation on how to use `kubectl config set`? I can't find any, and am trying to use it to construct my config from scratch. I can't seem to set any `exec` values for my user.

```
➜  k config set users.oidc.exec.command foo
error: unable to parse one or more field values of users.oidc.exec.command
```

**Comment by eddiezane** [comment]
It definitely needs a bit of work 😅. If you're building kubeconfigs you'll have a much better time using [clientcmd](https://pkg.go.dev/k8s.io/client-go@v0.22.1/tools/clientcmd).

```go
package main

import (
	"fmt"

	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
)

func main() {
	config := clientcmdapi.NewConfig()
	user := &clientcmdapi.AuthInfo{
		AuthProvider: &clientcmdapi.AuthProviderConfig{
			Name: "oidc",
			Config: map[string]string{
				"client-id": "kubernetes",
				"client-secret": "abc123",
				"idp-issuer-url": "https://example.com",
			},
		},
	}
	config.AuthInfos["admin"] = user
	cfg, err := clientcmd.Write(*config)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(cfg))
}
```

**Comment by eddiezane** [comment]
We'll track this in another issue for improving `kubectl config set`

/close
