### ISSUE TITLE
client-go credential plugins ignores 'expirationTimestamp' field

### ISSUE THREAD

**Issue by fox-md** [kubernetes/kubectl#1109]
**What happened**:
As per https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins it is possible to use external app to retrieve token from a webservice and use to authenticate against kube-api. 
Also from guide:
```
Optionally, the response can include the expiry of the credential formatted as a RFC3339 timestamp. Presence or absence of an expiry has the following impact:

- If an expiry is included, the bearer token and TLS credentials are cached until the expiry time is reached, or if the server responds with a 401 HTTP status code, or when the process exits.
- If an expiry is omitted, the bearer token and TLS credentials are cached until the server responds with a 401 HTTP status code or until the process exits.
```
I am sending below response to kubectl using go app. 
```
{
  "apiVersion": "client.authentication.k8s.io/v1",
  "kind":"ExecCredential",
  "status": {
	"token": "7f39e2f2-130a-11ec-b87d-f875a41a5b56",
	"expirationTimestamp":"2021-09-12T02:12:54+00:00"
  }
}
```
Despite of the fact that **expirationTimestamp** field exists in status response, kubectl still tries to get a new token on each execution. This means part `If an expiry is included, the bearer token and TLS credentials are cached until the expiry time is reached` is confusing and non-functional.

Can you please advise, I am using this field in a wrong way? Or how can I make kubectl use "cached" token until it is expired?

**What you expected to happen**:
Expected kubectl to use token from its "cache", whatever that means.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dummy app that returns response from the guide, include expirationTimestamp field in response and log all executions to see exact number of execution attempts.

**Environment**:
```
kubectl version --client
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
```
kubeconfig
```
apiVersion: v1
kind: Config
users:
- name: my-user
  user:
    exec:
      command: "auth-go"
      apiVersion: "client.authentication.k8s.io/v1"
      # Text shown to the user when the executable doesn't seem to be present. Optional.
      installHint: |
        example-client-go-exec-plugin is required to authenticate
        to the current cluster.  It can be installed:

        On macOS: brew install example-client-go-exec-plugin

        On Ubuntu: apt-get install example-client-go-exec-plugin

        On Fedora: dnf install example-client-go-exec-plugin
        ...        
      provideClusterInfo: false
      interactiveMode: Never
clusters:
- name: my-cluster
  cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.48.30:6443
contexts:
- name: my-cluster
  context:
    cluster: my-cluster
    user: my-user
current-context: my-cluster
```

**Comment by eddiezane** [comment]
@fox-md the token is cached for a single kubectl execution - it will be used for all the API requests under that run, for api discovery, etc.

We do not cache those tokens beyond a single invocation of kubectl.

Does that make sense?

**Comment by fox-md** [comment]
Hi @eddiezane,

Thank you for your answer. I understood caching in a bit different way. Now it is more clear what happens "under the hood".

**Comment by ryodocx** [comment]
@fox-md
Probably, it satisfies your needs.
https://github.com/ryodocx/kube-credential-cache
