### ISSUE TITLE
Kubectl describe nodes with Multi containers may display error quota

### ISSUE THREAD

**Issue by qixiaobo** [kubernetes/kubectl#1110]
**What happened**:
When I use kubectl to describe nodes
It may display error quota like below
![image](https://user-images.githubusercontent.com/2881751/133418107-6984b398-8122-46bd-b0d8-a5d321bdc69e.png)
![image](https://user-images.githubusercontent.com/2881751/133418220-d95cc904-c956-44b9-ba53-40c16c79adba.png)
In fact ,I never  make a cpu limit and request.
![image](https://user-images.githubusercontent.com/2881751/133418568-b1d5c089-d614-4e1c-a2b4-65a22dbbbbd9.png)
I found init container may cause this.

**What you expected to happen**:
Not show 100m cpu , the value not set may not  be computed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I found this code may be related.

https://github.com/kubernetes/kubectl/blame/159a770147fb28337c6807abb1b2b9db843d0aff/pkg/describe/describe.go#L4034

https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/util/resource/resource.go#L34

```go
// addResourceList adds the resources in newList to list
func addResourceList(list, new corev1.ResourceList) {
	for name, quantity := range new {
		if value, ok := list[name]; !ok {
			list[name] = quantity.DeepCopy()
		} else {
			value.Add(quantity)
			list[name] = value
		}
	}
}

```
When quantity is 0 , we cannot  just simply add

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by qixiaobo** [comment]
https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/util/resource/resource.go#L34

**Comment by eddiezane** [comment]
We are potentially only looking at init containers here.

**Comment by eddiezane** [comment]
@qixiaobo can you please provide a simple manifest to reproduce this?

**Comment by lauchokyip** [comment]
@qixiaobo  When quantity is 0, we can add the value to it. This is what is being done in `kubectl top` 

[It first create the resource as 0 and then add the current value to it](https://github.com/kubernetes/kubectl/blob/159a770147fb28337c6807abb1b2b9db843d0aff/pkg/metricsutil/metrics_printer.go#L256-L266)

```go
	podMetrics := make(v1.ResourceList)
	for _, res := range MeasuredResources {
		podMetrics[res], _ = resource.ParseQuantity("0")
	}

	for _, c := range m.Containers {
		for _, res := range MeasuredResources {
			quantity := podMetrics[res]
			quantity.Add(c.Usage[res])
			podMetrics[res] = quantity
		}
	}
```

**Comment by qixiaobo** [comment]
> @qixiaobo When quantity is 0, we can add the value to it. This is what is being done in `kubectl top`
> 
> [It first create the resource as 0 and then add the current value to it](https://github.com/kubernetes/kubectl/blob/159a770147fb28337c6807abb1b2b9db843d0aff/pkg/metricsutil/metrics_printer.go#L256-L266)
> 
> ```go
> 	podMetrics := make(v1.ResourceList)
> 	for _, res := range MeasuredResources {
> 		podMetrics[res], _ = resource.ParseQuantity("0")
> 	}
> 
> 	for _, c := range m.Containers {
> 		for _, res := range MeasuredResources {
> 			quantity := podMetrics[res]
> 			quantity.Add(c.Usage[res])
> 			podMetrics[res] = quantity
> 		}
> 	}
> ```

Yeah , your are right.
So it makes a mistake.
But maybe  this case 0 indicates unlimited. 
So when  unlimited plus any value maybe also unlimited in limit

**Comment by lauchokyip** [comment]
@qixiaobo , can you provide a way to reproduce the error as @eddiezane suggested? That would really help us to fix this issue. Thank You.

**Comment by qixiaobo** [comment]
> @qixiaobo , can you provide a way to reproduce the error as @eddiezane suggested? That would really help us to fix this issue. Thank You.

I will try to make a repo later

**Comment by qixiaobo** [comment]
https://github.com/qixiaobo/k8s-quota-test/blob/main/myapp.yaml
You may apply -f
Then you can  invoke 

```bash
kubectl describe  nodes `kubectl get pods -o wide -l app=myapp|tail -n +2|awk '{print $7}'`
```

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/133621640-d9e15425-2ebe-4011-abcc-c870404b1952.png)

**Comment by qixiaobo** [comment]
You can see not set myapp container cpu limit or request 
Just set init container,I don't think not set may be treated as zero to make a plus

**Comment by harjas27** [comment]
The output show for the `describe node` command reflects the quotas used for  scheduling the pod on the node, with the logic: https://github.com/kubernetes/kubernetes/blob/a48a2efbd45ad77901dd09f2665d8cc1e1d8dbf6/staging/src/k8s.io/api/core/v1/types.go#L2977-L2980
```
// The resourceRequirements of an init container are taken into account during scheduling
// by finding the highest request/limit for each resource type, and then using the max of
// of that value or the sum of the normal containers. Limits are applied to init containers
// in a similar fashion.
```
this is taken care by this code:
https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/util/resource/resource.go#L74-L85
Instead of showing the exact quota of the pod (which will be the entire node's resources in this case), the output shows only what was taken into account during scheduling.
A similar scenario may occur when a pod contains multiple containers but some of them do not have the quota set. It will show a summation of the values for those containers which had the limit/resource available.

**Comment by qixiaobo** [comment]
> The output show for the `describe node` command reflects the quotas used for scheduling the pod on the node, with the logic: https://github.com/kubernetes/kubernetes/blob/a48a2efbd45ad77901dd09f2665d8cc1e1d8dbf6/staging/src/k8s.io/api/core/v1/types.go#L2977-L2980
> 
> ```
> // The resourceRequirements of an init container are taken into account during scheduling
> // by finding the highest request/limit for each resource type, and then using the max of
> // of that value or the sum of the normal containers. Limits are applied to init containers
> // in a similar fashion.
> ```
> 
> this is taken care by this code:
> https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/util/resource/resource.go#L74-L85
> 
> 
> Instead of showing the exact quota of the pod (which will be the entire node's resources in this case), the output shows only what was taken into account during scheduling.
> A similar scenario may occur when a pod contains multiple containers but some of them do not have the quota set. It will show a summation of the values for those containers which had the limit/resource available.

Yeah  , so it may cause misunderstanding
