### ISSUE TITLE
When the node is abnormal, the output format of the Top node is incorrect

### ISSUE THREAD

**Issue by wujiangfa-xlauncher** [kubernetes/kubectl#1111]
**What happened**:
![image](https://user-images.githubusercontent.com/53930349/133578619-0704113b-198a-4e13-a7ea-a4ebfc94a07f.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/53930349/133578703-f382e3a8-f0f2-412a-9626-eb33a0dd57c7.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by lauchokyip** [comment]
kubectl is using a built in [`tabwriter`](https://github.com/kubernetes/kubectl/blob/159a770147fb28337c6807abb1b2b9db843d0aff/pkg/metricsutil/metrics_printer.go#L167) to output the value. 

I was able to reproduce the error, will take a look
```
NAME      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%     
kmaster   790m         19%    1090Mi          28%         
knode0    687m         17%    1039Mi          27%         
foo       <unknown>                           <unknown>               <unknown>               <unknown>    
```

/triage accepted

**Comment by lauchokyip** [comment]
@wujiangfa-xlauncher , I saw the PR you opened https://github.com/kubernetes/kubectl/pull/1114, do you want to open the PR in the main repo https://github.com/kubernetes/kubernetes so we can get that merged?

**Comment by lauchokyip** [comment]
Closing this because https://github.com/kubernetes/kubernetes/pull/105121 was merged
/close
