### ISSUE TITLE
failed label selector should not return code 0

### ISSUE THREAD

**Issue by jonassteinberg1** [kubernetes/kubectl#1115]
**What happened**:
```
# made up label selector key and value
> kubectl -n istio-system get po -l 'gate in (publics)'
No resources found in istio-system namespace.

# return code in bash shell
> echo $?
0
```

**What you expected to happen**:
```
> echo $?
1
```

**How to reproduce it (as minimally and precisely as possible)**:
run the first command above and give bogus key and value for label selector
then `echo $?`

**Comment by jonassteinberg1** [comment]
For the record maybe this is how this should work.  I was trying to script something like:

`kubectl -n istio-system get po -l 'gate in (publics)' || fail action`

but now that I look closer..._maybe_ incorrect tags is not the same thing as a failure.  We'll see.

**Comment by lauchokyip** [comment]
Hi @jonassteinberg1 , you are right, I think `resource no found ` is not considered an error by kubectl
https://github.com/kubernetes/kubectl/blob/159a770147fb28337c6807abb1b2b9db843d0aff/pkg/cmd/get/get.go#L593-L600

**Comment by eddiezane** [comment]
There's a KEP for refactoring the exit codes.

@rikatz how do you want to track all these?

https://github.com/kubernetes/enhancements/pull/2574

**Comment by eddiezane** [comment]
This will be addressed by the exit code overhaul KEP.

/close
