### ISSUE TITLE
Waiting for pods hangs indefinitely if a pod is concurrently scheduled for termination and removed by a deployment

### ISSUE THREAD

**Issue by ringerc** [kubernetes/kubectl#1120]
**What happened**:

When `kubectl wait --for=condition=ready pod --all` is used to wait for all existing pods to reach the ready state, if any deployment-managed pods existed when the wait started then were removed the wait command will wait forever.

A second `kubectl wait --for=condition=ready pod --all` command launched a few seconds later will succeed because the pod that the first command is waiting for has already been terminated by the time `kubectl` collects its list of pods to wait for. But the first wait will remain stuck, because it doesn't know the pod is gone and never coming back.

There is a race between kubectl's capture of the pods to wait for and the removal of pods by a deployment. 

**What you expected to happen**:

If a pod no longer exists and was selected by a pattern match like a label or `--all`, it should no longer be waited on as it no longer matches the expression used to select pods to wait for.

Either:

* Skip over and ignore removed pods when `kubectl` was invoked with `--all`, a label pattern, or anything other than an explicit list of pod names; or
* Detect that a pod being waited for has been removed and return an error condition and a distinctive exit code that can be matched in order to retry the wait operation

**How to reproduce it (as minimally and precisely as possible)**:

* Define a deployment that spawns a set of pods
* `kubectl apply -f the-deployment.yaml`
* `kubectl wait --for=condition=available deployment --all --timeout=30s`
* `kubectl wait --for=condition=ready pod --all --timeout=30s`

Often the last wait step will exit with a nonzero return code and an error like

```
error: timed out waiting for the condition on pods/deployment-name-foo-bar-869bc686d-jls5d
```

but re-running the command will succeed.

`kubectl get pod deployment-name-foo-bar-869bc686d-jls5d` will indicate (correctly) that the pod does not exist.

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes client and server versions (use `kubectl version`) `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}` `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: `kind` cluster on x64 Fedora 33 laptop
- OS (e.g: `cat /etc/os-release`): Fedora 33, linux `5.12.11-200.fc33.x86_64`

**Comment by ringerc** [comment]
This issue tends to arise when reconfiguring a deployment.

The kube cluster will spin up new pods and terminate old pods asynchronously. Waiting for the new deployment to reach minimum availability does not guarantee that pods from the old deployment are terminated.

**Comment by ringerc** [comment]
A workaround is to retry `kubectl wait` with a short timeout in a loop, rather than letting `kubectl wait` run with a full timeout then give up after one try.

**Comment by ringerc** [comment]
See related https://github.com/kubernetes/kubernetes/issues/83242

**Comment by tleerai** [comment]
I've found this can happen with init pods, so running it like this has helped:

`kubectl wait -n <namespace> --for=condition=Ready --timeout=5m pod --all || kubectl wait -n <namespace> --for=condition=Ready --timeout=5m pod --all`
