### ISSUE TITLE
Kubeconfig's clusters server can support multiple IP addresses.

### ISSUE THREAD

**Issue by zhengqisong** [kubernetes/kubectl#1121]
Kubeconfig's clusters server can support multiple IP addresses.

At present, when accessing apiserver externally, the third-party load balancing is usually used. Can we directly support multi IP access capability in kubernetes.

**What would you like to be added**:
apiVersion: v1
clusters:
  - cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://**192.168.133.128;192.168.133.129**:6443
  name: kubernetes
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
**Why is this needed**:

**Comment by eddiezane** [comment]
Supporting a list of servers would open the doors for more issues like different ways to choose the server used, favoring the one with the lowest latency, how retries work upon an error.

Ultimately we decided there's no way to implement this while making everyone happy in the end. It's best to leave the load balancing implementation up to the user.

/close

**Comment by yoe** [comment]
So in other words, you're letting the perfect be the enemy of the good.

You could just say "we'll try the first and follow the list until something replies" and make it clear that proper load balancing is out of scope 🤷

**Comment by termermc** [comment]
I would love to see this supported. I agree with @yoe
