### ISSUE TITLE
Request: Support multiple documents in KUBECONFIG

### ISSUE THREAD

**Issue by robotrapta** [kubernetes/kubectl#1123]
**What would you like to be added**:

It sure would be handy if I could put multiple YAML documents into my KUBECONFIG file, separated by `---`.  Each one should be able to create its own contexts, and the cluster and user references should be scoped to within that document.  The context names themselves would have to share a global namespace.  If there were name collisions on the context names I think it would just have to throw an error.

**Why is this needed**:

We work with lots of different clusters, dynamically building them for various tasks.  Various tools like microk8s and eksctl are happy to generate a complete kubeconfig needed to access the cluster.  But merging the kubeconfigs together is error-prone.  I've seen many a smart engineer flustered for quite a while because there's a mistake in there caused by not merging them properly.

With this change it would be much easier to merge them because in almost every case you could just append `---` and the generated full kubeconfig from whatever source you got it from, and the only change you'd need to make would be to the name of the context.

**Comment by eddiezane** [comment]
We've discussed this before in the form of supporting the XDG config spec. If we could do things over from the start we would make these changes but the issue is that now it would cause widespread issues for other tooling in the ecosystem.

https://github.com/kubernetes/enhancements/pull/2111

/close
