### ISSUE TITLE
kubectl doesn't understand ~ abbreviation in path for plugins

### ISSUE THREAD

**Issue by tillig** [kubernetes/kubectl#1125]
**What would you like to be added**:

I would like `kubectl` to respect `~` in a shell path, particularly with respect to location of plugins. `~` should be expanded to be the current user's home directory prior to evaluating paths.

For example, I am trying to use `krew` and have added the folder `~/.krew/bin` to my path, but `kubectl` won't find plugins there. However, if I manually execute them (basically as shell scripts), they're found.

**Why is this needed**:

On MacOS (and perhaps others), the easiest way to add a user-specific path that works across _all shells_ is to add it to `/etc/paths` or add a file in `/etc/paths.d` with the path in a format like `~/.krew/bin`. This will automatically be added to any shell, for all users, and "just work."

However, given the current path evaluation mechanism, the well-known `~` is not expanded before plugins are located and the location fails.

**Additional context**:

It appears the fix would probably be [somewhere around here where the `PATH` is retrieved from the environment](https://github.com/kubernetes/kubectl/blob/5920119027082fe88d3c01c334d2a5ed586b020e/pkg/cmd/plugin/plugin.go#L108).

**Comment by tillig** [comment]
Example output for `kubectl plugin list` to illustrate another side-effect of not understanding `~` paths:

My path is:

`/usr/local/microsoft/powershell/7:/usr/local/opt/python@3.8/libexec/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin:/Applications/Beyond Compare.app/Contents/MacOS:~/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/tillig/.krew/bin`

(I've updated my `krew` directory to be fully qualified to work around this)

Ouptut from `kubectl plugin list`:

```text
The following compatible plugins are available:

/usr/local/bin/kubectl-krew
Unable to read directory "~/go/bin" from your PATH: open ~/go/bin: no such file or directory. Skipping...
Unable to read directory "~/.dotnet/tools" from your PATH: open ~/.dotnet/tools: no such file or directory. Skipping...
/Users/tillig/.krew/bin/kubectl-neat
```

**Comment by tillig** [comment]
I will have to try `$HOME` in `/etc/paths` to see if it makes a difference.

It may not be good to assume bash is the shell - I generally use PowerShell, for example, but `~` is a well-understood cross-shell shorthand, so using it in `/etc/paths` means it doesn't matter which shell is used, it always "just works." Using `/etc/paths` also means I don't have to configure each shell's individual profile to expand the path out - set it once, works for all shells... If `~` gets expanded. It also means I can set it up once and have it work for multiple users/profiles rather than seeing it up for each user for each shell.

But, again, I'll see if `$HOME` makes a difference. Maybe that's the answer.

**Comment by brianpursley** [comment]
Ah I forgot you are using /etc/paths.

If $HOME doesn't work there, you can try setting PATH in /etc/profile
