### ISSUE TITLE
Kubectl Windows installer - Winget / Standalone installer

### ISSUE THREAD

**Issue by ssrahul96** [kubernetes/kubectl#1130]
**What would you like to be added**:
Windows installer for Kubectl

**Why is this needed**:
Easy installation with Winget

**Comment by ssrahul96** [comment]
https://github.com/helm/helm/issues/8203#issuecomment-941047825, I have made a sample installer for helm, which can be used for kubectl package also

https://github.com/ssrahul96/helm-windows-installer

Check whether this can be used.

**Comment by sftim** [comment]
Are there any enabling pieces of work that would allow a downstream automation to consume some data and make a package / installer / etc? If so, what are those enabling pieces of work?

**Comment by ssrahul96** [comment]
This installer need not be build on CicleCI, as helm was built over there, I ve submitted a PR for this, the same logics can be used for any CI pipeline, 

build and installer stage generation should be separated. this would act like an additional way of installing kubectl (specially installing using `Winget`)

**Comment by eddiezane** [comment]
Cheers @ssrahul96,

I checked with folks on the release team and maintaining a Windows installer is not something we want to do at the moment. This would be a great place for the community to take up the reins and show demand.

/close
