### ISSUE TITLE
Display used seccomp profile on `kubectl describe`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubectl#1133]
**What would you like to be added**:

Determining the used seccomp profile for a container is a non-trivial task in Kubernetes. The security context features a dedicated `SeccompProfile` field: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#seccompprofile-v1-core
There are also the deprecated seccomp annotations. Both, annotations as well as the field are available per pod and per container. This also means that containers can overwrite the pod values, whereas the container values get inherited by the pod if not set.

This logic could be built into kubectl describe, making it easy for users to determine the used seccomp profile of a container.

cc @sftim

**Comment by eddiezane** [comment]
/triage accepted
/priority backlog
/good-first-issue

This work would need to done in https://github.com/kubernetes/kubernetes/blob/91ff1f9840278ec9c58089d891d6d594e5055bab/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L692.

**Comment by lauchokyip** [comment]
Hi @ncapps , are you still working on this? If not, would you mind giving it out to one of my friend who is a newcomer ? Thanks!!!

@williamyeh

**Comment by ncapps** [comment]
I apologize for the delay. Feel free to pick this up @williamyeh

**Comment by williamyeh** [comment]
@vinamra28 Hi I have it almost done, will submit a PR soon, thanks
