### ISSUE TITLE
Improper input validation on -o flag

### ISSUE THREAD

**Issue by kbasgall** [kubernetes/kubectl#1134]
**What happened**:
I want to write my docker-registry secret to a file.  This command line option is supported, so I run:

```bash
kubectl create secret docker-registry example-token --dry-run=client <credential flags ommitted> -o  example-token.yaml
```

This command results in a segmentation fault, as the correct usage of the command line option is `-o yaml > example-token.yaml`.  Error output is as follows:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1918de0]
```

**What you expected to happen**:
I expect the command in this case to display a specific command regarding usage of the `-o` flag rather than failing with a segmentation fault. 

**How to reproduce it (as minimally and precisely as possible)**:

```bash
kubectl create secret docker-registry example-token --dry-run=client  --docker-server=<hidden> --docker-username=<hidden> --docker-password=<hidden> --docker-email=<hidden> -o example-token.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04

**Comment by lauchokyip** [comment]
Thank you @kbasgall for catching that !!
