### ISSUE TITLE
Missing command to label Pods of a Kubernetes Workload

### ISSUE THREAD

**Issue by chirangaalwis** [kubernetes/kubectl#1136]
**What would you like to be added**:
Currently, there is no command to overwrite or add new label(s) to Pods of an existing Kubernetes Workload such as, Deployment, StatefulSet, DaemonSet, etc.

I would like to suggest a command of following nature.

```
# Adds a new label to Deployment selector and Pods created with it
# indicated by --pods to avoid conflicting the update of Deployment's labels
kubectl label deployment foo --pods purpose=test

# Overwrite existing label(s) of the Deployment selector and Pods created with it
kubectl label deployment foo --overwrite --pods purpose=test
```

**Why is this needed**:
Removes the need to patch or edit a workload definition which as per my experience is cumbersome especially for a new user. `kubectl label` command gives a user friendly approach to add or overwrite resource labels and given that we use these high level workloads often, than naked Pods.

**Comment by soltysh** [comment]
`kubectl label` does exist, have you tried it? 
/close

**Comment by chirangaalwis** [comment]
@soltysh but this does not consider all the Pods of a workload (e.g. a Deployment) as a whole and label them does it?
We need to use the selector to first select the relevant Pods and then label them using the label command. And AFAIK this does not update the label selector of the workload (e.g. relevant Deployment)
What I mean is to use the label command to update the labels of a workload’s Pod template labels + the label selector of the workload.

**Comment by soltysh** [comment]
All pods of a deployment are controlled by the deployment, you can either modify a set of resources using `--selector` flag or more preferably modify the pod template of a deployment. 

I'm not envisioning doing what you're proposing here. 

/close
