### ISSUE TITLE
Consider provide kubectl-plugin-scaffolding repository as a public template for Go

### ISSUE THREAD

**Issue by Dentrax** [kubernetes/kubectl#1138]
**What would you like to be added**:

The idea is inspired by [terraform-provider-scaffolding](https://github.com/hashicorp/terraform-provider-scaffolding) project, which makes life easier to create _custom providers_ from scratch. But Kubernetes, currently uses [sample-cli-plugin](https://github.com/kubernetes/sample-cli-plugin) to demonstrate how can we create _custom plugins_ from scratch.

We (w/@developer-guy) are proposing to create brand-new batteries-included [public template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) for the developer who do not want to do _chore_ things and lost in _how-to_ articles around there. [^1]

**Why is this needed**:

To provide batteries-included project:

* `.gitignore`
* `.goreleaser.yml`
* `.golangci-lint.yml`
* `docs/`
* `.github/`
*  * dependabot
*  * ISSUE + PR Templates
* * workflows: `test` + `build`
* CONTRIBUTING.md
* OWNERS
* LICENSE
* [.krew.yaml](krew.sigs.k8s.io/)
* [just](https://github.com/casey/just) or [make](https://man7.org/linux/man-pages/man1/make.1.html) file
* * build: go build (ldflags for version)
* * test: unit + integrations
* * fmt: format checking
* * lint: linters
* * krew: test + build + send a pr to krew using [Automating plugin updates](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)

Easy instructions to build new plugin from scratch:
1. Click `Use this template` button
2. Clone the forked repository and cd into it
3. Build the plugin using the make command:

---

If you liked the idea we can drop a proposal in the [kubernetes/enhancements](https://github.com/kubernetes/enhancements) repository. Any feedback would be appreciated!

[^1]: https://www.google.com/search?q=writing+OR+extending+kubectl+plugins

**Comment by eddiezane** [comment]
Hi @Dentrax!

We discussed this today during our bi-weekly meeting and don't think we need to add another repo but would love for y'all to upstream some of these suggestions to the current sample repo.

No KEP is needed but PRs must be made against the main kubernetes/kubernetes repo since the sample plugin is a "staging repo".

Please tag me on any PRs you make there.

https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-cli-plugin

**Comment by Dentrax** [comment]
Hi @eddiezane!

Thanks for the suggestions and review. That makes sense to continue with current repo. _I did not know the detail that we could change the current repos as the _public templates_, I thought we can only do that during the repo creation!_

So, If you agreed the glossary that we wrote in the _"Why is this needed"_ section, we (w/ @developer-guy @erkanzileli) can starting working on a PR!

Please note that this work _might_ bring a tremendous amount of change and refactor across the entire repo. But at the end of the day, developers will be able to create their own kubectl plugins with one single click! :)

**Comment by Dentrax** [comment]
Hey @eddiezane, any additional updates here? You can assign us if you're agreeing the proposal, so we can start working on W.I.P PR! 🤗

**Comment by Dentrax** [comment]
Kindly ping. 🤞

**Comment by eddiezane** [comment]
Apologies for the delay here.

If you're still interested in working on this please feel free to open smaller PRs against the existing repo. Especially when it comes CI/vendor implementations and we can discuss there.

/triage accepted
/assign @Dentrax
