### ISSUE TITLE
Add PowerShell friendly CLI

### ISSUE THREAD

**Issue by soroshsabz** [kubernetes/kubectl#1139]
ITNOA

# Description of the new feature/enhancement

As you can know PowerShell is great Scripting Language for Automation and Administration of system. and it is built for Object-oriented scripting.

Kubernetes API, on the other hand, is also completely object-oriented, so I think it is very good for kubectl to get compatible with PowerShell and make native PowerShell [Cmdlet](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-13?view=powershell-7.1).

In this area we can see below command instead of Linux legacy CLI style like `kubectl get node` 

* `Get-Node`

And all of them is object and we can work with them in OOP area with modern and great and consistent experience in PowerShell World.

# Proposed technical implementation details (optional)

I think PowerShell has many guideline and documentation about writing and designing great Cmdlet and modules that winget-cli teams have to follow it for example

[Windows PowerShell Cmdlet Concepts](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/windows-powershell-cmdlet-concepts?view=powershell-7.1)
[Writing a Windows PowerShell Module](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/writing-a-windows-powershell-module?view=powershell-7.1)
[PowerShell Script Module Design: Building Tools to Automate the Process](https://mikefrobbins.com/2018/11/01/powershell-script-module-design-building-tools-to-automate-the-process/)
[Powershell: DSL design patterns](https://powershellexplained.com/2017-03-13-Powershell-DSL-design-patterns/)

VMWare [PowerCLI](https://www.altaro.com/vmware/vmware-powercli-guide/) is an example for similar large scale software that use PowerShell for CLI.

**Comment by eddiezane** [comment]
All of the autocomplete functionality (and cli bits) for kubectl is provided through the Go library [Cobra](https://github.com/spf13/cobra).

It doesn't look like this is something Cobra provides yet https://github.com/spf13/cobra/blob/master/shell_completions.md#powershell-completions - or would it need to be separate entirely?

QOL improvements for Powershell users are certainly something we'd consider merging if a PR surfaced.

Might be worth tagging @JamesWTruher.

cc @marckhouzam

**Comment by marckhouzam** [comment]
IIUC this is something different than command completion.  I'm not very familiar with PowerShell but it may be an improvement than could possibly be generic enough to be done on Cobra so that it would be available to many clis.  Having something working in kubectl or another project would be a good proof that such a feature works well. 

Someone would need to step up and do the work however.

**Comment by soroshsabz** [comment]
@eddiezane It is very beyond than just auto complete, it is about new culture of CLI.

**Comment by eddiezane** [comment]
Thanks for explaining!

I'd recommend opening this in Cobra if you want to get the ball rolling.

/close
