### ISSUE TITLE
[UMBRELLA] Kubectl independence

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#114]
The goal of this issue is to track research, implementations and improvements that can be done in order to have a more independent development of Kubectl features.

This effort is based on @pwittrock documents: https://goo.gl/2RYvqG and https://goo.gl/j2hnrG

Kubectl independence would lead to less friction with other Kubernetes development, increased velocity, simplification of the testing infrastructure, of code components, and maybe its own release cadence.

Orthogonal to that issue would be a split of kubectl outside of the core repository.

Here is the list of things that needs to be figured out to improve the independence of Kubectl development:
- #115 Testing
- #116 Releasing
- #117 code refactoring
- #118 documentation

**Comment by seans3** [comment]
Another related issue: #80

**Comment by soltysh** [comment]
Closing as duplicate of https://github.com/kubernetes/kubectl/issues/83
/close
