### ISSUE TITLE
Can I download the kubectl package through go install now?

### ISSUE THREAD

**Issue by lizhifengones** [kubernetes/kubectl#1140]
**What happened**:
`go install: k8s.io/kubectl@v0.22.3: module k8s.io/kubectl@v0.22.3 found, but does not contain package k8s.io/kubectl`
**What you expected to happen**:
Use kubectl package
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
The main file for kubectl still lives in the kubernetes/kubernetes repo https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/kubectl.go.

It's a large effort and there's very active work in progress right now (and a new KEP being written) to be able to build and release kubectl independently. We're hoping to tackle this for 1.24 or 1.25.

For now you'll still need to `make kubectl` from k/k.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1020-kubectl-staging
https://github.com/kubernetes/kubernetes/pull/106078

Closing this as we're tracking elsewhere.

/close

**Comment by liubog2008** [comment]
Any progress about this? @eddiezane It seems no accepted KEP about it until now
