### ISSUE TITLE
Kubectl commands not working on MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by Shanmugapriya03** [kubernetes/kubectl#1142]
**What happened**:
I upgraded MacOS to Monterey 12.0.1 and executed kubectl commands. Got the below error:

```
kubectl apply -f some_file.yaml
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x194b60e, 0x21)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff598 sp=0x7ff7bfeff578 pc=0x1029da1
runtime.goenvs()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff5c8 sp=0x7ff7bfeff598 pc=0x1027923
runtime.schedinit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff620 sp=0x7ff7bfeff5c8 pc=0x102c664
runtime.rt0_go(0x7ff7bfeff650, 0x6, 0x7ff7bfeff650, 0x1000000, 0x6, 0x7ff7bfeff830, 0x7ff7bfeff849, 0x7ff7bfeff84f, 0x7ff7bfeff852, 0x7ff7bfeff870, ...)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff628 sp=0x7ff7bfeff620 pc=0x1052834
Unable to connect to the server: getting credentials: exec: executable heptio-authenticator-aws failed with exit code 2
```

**What you expected to happen**:
 It should have applied the configuration

**How to reproduce it (as minimally and precisely as possible)**:

A basic yaml file with minimal configuration required to create a deployment.
Execute this command : `kubectl apply -f some_file.yaml`

**Anything else we need to know?**:
Using `heptio-authenticator-aws` for fetching aws credentials
**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
kubectl version --client
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
```

```
➜  ~ kubectl version
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x194b60e, 0x21)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff5c8 sp=0x7ff7bfeff5a8 pc=0x1029da1
runtime.goenvs()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff5f8 sp=0x7ff7bfeff5c8 pc=0x1027923
runtime.schedinit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff650 sp=0x7ff7bfeff5f8 pc=0x102c664
runtime.rt0_go(0x7ff7bfeff688, 0x6, 0x7ff7bfeff688, 0x0, 0x1000000, 0x6, 0x7ff7bfeff868, 0x7ff7bfeff881, 0x7ff7bfeff887, 0x7ff7bfeff88a, ...)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff658 sp=0x7ff7bfeff650 pc=0x1052834
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: getting credentials: exec: executable heptio-authenticator-aws failed with exit code 2
```

- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
```
➜  ~ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
➜  ~ uname -a
Darwin Shanmugas-MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

**Comment by bitti** [comment]
I get the same error with older `kubectl` binaries after upgrading to Monterey. The stacktrace similar and is pointing to the same line in /usr/local/go/src/runtime/asm_amd64.s:

```
$ ./kubectl-1.12.10 version --client
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x23d3b5f, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff4d8 sp=0x7ff7bfeff4b8 pc=0x1028ff1
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff508 sp=0x7ff7bfeff4d8 pc=0x1026b73
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff570 sp=0x7ff7bfeff508 pc=0x102b8e6
runtime.rt0_go(0x7ff7bfeff5a8, 0x3, 0x7ff7bfeff5a8, 0x0, 0x1000000, 0x3, 0x7ff7bfeff7b8, 0x7ff7bfeff7ca, 0x7ff7bfeff7d2, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff578 sp=0x7ff7bfeff570 pc=0x1052174
```
And as you can see it's evening happening when providing the `--client` option for `version`. I tried different binaries from https://storage.googleapis.com/kubernetes-release/release and it's happening up and including to `v1.12.10`. `v1.13.0` and above is working fine as far as I can see (although I didn't test every single version of course).

**Comment by Shanmugapriya03** [comment]
@bitti I found another [thread](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/409#issuecomment-959724187) with a similar issue, and someone mentioned that anything installed as binaries is not working after the macOS Monterey update, but brew install works fine. In my case, it was `heptio-authenticator-aws `which is available only in binary format. I switched to `aws-iam-authenticator` as it was available in the brew install method.

To temporarily unblock yourself, `remove the kubectl binaries and use the brew install` method

**Comment by brianpursley** [comment]
A related issue (https://github.com/golang/go/issues/49425) and page (https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue).

I wonder if heptio-authenticator-aws was compiled with an older, unsupported version of go (<= 1.10).

Can you use [aws-iam-authenticator](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html) or `aws eks get-token`?

**Comment by bitti** [comment]
> @bitti I found another [thread](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/409#issuecomment-959724187) with a similar issue, and someone mentioned that anything installed as binaries is not working after the macOS Monterey update, but brew install works fine. 

I can't confirm that, since as mentioned the `kubectl` binaries since `v1.13.0` are working fine for me, only the earlier ones are making problems.

> To temporarily unblock yourself, `remove the kubectl binaries and use the brew install` method

I don't think brew provides a way to install different versions in parallel?

**Comment by Shanmugapriya03** [comment]
@bitti You can install multiple versions using brew, but yes you will not be able to use them in parallel. Each and every time when you need a particular version, you will have to make that version active and use.

**Comment by aqHi** [comment]
+1

**Comment by eddiezane** [comment]
As Brian points out this is an issue with running binaries built with older versions of Go.

Please upgrade your binaries.

For context `heptio-authenticator-aws` became [`aws-iam-authenticator`](https://github.com/kubernetes-sigs/aws-iam-authenticator) in [2018](https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/678cdff0f43d3ae4a1d9d68a5347042f14a168a8) and Kubernetes 1.12 is also from 2018.

/close

**Comment by roeera** [comment]
Same error when trying to search history "ctrl + R"... any idea ?!

**Comment by bitti** [comment]
> Same error when trying to search history "ctrl + R"... any idea ?!

Do you use `fzf` for command history? It's written in Go, so try to update/reinstall it via `brew`.

**Comment by aqHi** [comment]
` brew update` then `brew upgrade` may help

**Comment by ed-at-agari** [comment]
I had to do a `which -a aws-iam-authenticator`, delete both results, then `brew reinstall aws-iam-authenticator`

**Comment by razvanphp** [comment]
For me the problem was an old version of `google-cloud-sdk`

```
Your current Cloud SDK version is: 211.0.0
You will be upgraded to version: 370.0.0
