### ISSUE TITLE
Provide a function that returns the limits and requests of active containers only in pods

### ISSUE THREAD

**Issue by chilanti** [kubernetes/kubectl#1146]
**What would you like to be added**:
We would like [this module](https://github.com/kubernetes/kubectl/blob/master/pkg/util/resource/resource.go) to provide a function such as `ActiveContainersPodRequestsAndLimits` (vs. just `PodRequestsAndLimits`) that returned the requests and limits *only* of the active containers, vs. returning the max(init_containers, active_containers). 

**Why is this needed**:
This function is being used by tools such as @robscott's [kubecapacity](https://github.com/robscott/kube-capacity) and we noticed a discrepancy between the totals that it produces vs the actual totals of the running containers - it wasn't until we looked at the "fine print" of `PodRequestsAndLimits` that we realized that init containers are taken into account (when their requests/limits exceed those of running pods). 
See also [this issue](https://github.com/robscott/kube-capacity/issues/53#issuecomment-962830325).
Thanks.
cc: @kmlefebv

**Comment by eddiezane** [comment]
I think we would take a PR that added such a function as long as it's not duplicated code.

@lauchokyip any thoughts? I know you just worked in this area.

**Comment by lauchokyip** [comment]
@eddiezane.  I believe this is the same issue as this, https://github.com/kubernetes/kubectl/issues/1110 and this.

Would it make sense for @g1bl3t to take a look at this. 
@brianpursley might be able to chip in too

**Comment by eddiezane** [comment]
Following up here we decided that the requested changes are minimal enough that they can be reimplemented in the project that needs it.

/close
