### ISSUE TITLE
`kubectl-diff` last applied configuration

### ISSUE THREAD

**Issue by georgettica** [kubernetes/kubectl#1147]
**What would you like to be added**:
I would like for there to be an easy way of diffing between the last applied configuration.
Also that it won't require a live k8s object but a local file aswell

See issue I opened in a similar tool on this
https://github.com/knight42/kubectl-blame/issues/5

**Why is this needed**:
To easily check what has changed (used after the fact by an admin with no audit access

**Comment by eddiezane** [comment]
We discussed this and decided that this should ultimately be achieved by `git diff` on the manifest. It would be an anti pattern to rely on the config last applied field to determine this and is not something we want to add support for.

cc @seans3 

/close
