### ISSUE TITLE
404 on Kubectl installation

### ISSUE THREAD

**Issue by vitaliy-zinchenko** [kubernetes/kubectl#1149]
This page give https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux instruction how to install kubectl.
And this command from the doc above:
`curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"` returns 404.

**What happened**:
I get a `404` response:

```
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

curl: (3) nested brace in URL position 631:
https://dl.k8s.io/release/<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  ...
```

**What you expected to happen**:

The artifact is downloaded

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
@vitaliy-zinchenko this is due to an active incident. Should be working shortly.

https://status.cloud.google.com/incidents/6PM5mNd43NbMqjCZ5REh

/close
