### ISSUE TITLE
Clarify apply -l option with multiple labels

### ISSUE THREAD

**Issue by collimarco** [kubernetes/kubectl#1150]
Page: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

```
selector | -l |  Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
```

The description of the `-l` flag is not clear when you list multiple labels.

What does this mean `key1=value1,key2=value2`? Is it equivalent to:

1. match objects that have `key1=value1 AND key2=value2`
2. match objects that have `key1=value1 OR key2=value2`

Please clarify.

Note: since you can use `--prune -l` it is very important to make it clear the effects of the condition

**Comment by sftim** [comment]
We _do_ have https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ that explains how selectors work.

**Comment by eddiezane** [comment]
/triage accepted
/priority backlog

We believe this is an AND operation and can be should be documented as such.
