### ISSUE TITLE
Using `helmCharts` doesn't work with charts that use `.Release` fields

### ISSUE THREAD

**Issue by anvouk** [kubernetes/kubectl#1151]
**What happened**:
Deploying `kustomization.yaml` with `helmCharts` doesn't set `.Release` properties.

This breaks some popular charts in a very hard to debug manner (for example, [bitnami kafka helm chart](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L3) which relies on `.Release.Namespace` for cluster connections).

**What you expected to happen**:
When launching `kubectl kustomize <FOLDER> --enable-helm`, `.Release` properties should have correct values and not default ones.

At least, provide a way to manually set them inside `kustomization.yaml`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Download, unzip and deploy with `kubectl kustomize test --enable-helm | kubectl apply -f -` the following example: [broken-example](https://github.com/kubernetes/kubectl/files/7553317/test.zip)
2. pod's has wrong `.Release.Namespace` and `.Release.Name` set:
```yaml
        env:
        - name: release-name
          value: RELEASE-NAME # <-- wrong. should be `test`
        - name: release-namespace
          value: default  # <-- wrong. should be `test`
```

**Anything else we need to know?**:
I know the `helmCharts` feature is quite new, but we really need better documentation.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
kubectl: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`
helm: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`
- Cloud provider or hardware configuration:
`minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b`
- OS (e.g: `cat /etc/os-release`):
`NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by eddiezane** [comment]
@anvouk I think this issue is specific to kustomize. Can you please open it at https://github.com/kubernetes-sigs/kustomize instead? We unfortunately can't migrate issues across GitHub orgs. 

/close
