### ISSUE TITLE
Unify kubectl usage output across help output

### ISSUE THREAD

**Issue by explogx** [kubernetes/kubectl#1156]
**What would you like to be added**:

Some subcommands such as `kubectl describe` accept formatted arguments that aren't explicitly marked as valid inside the `--help` output. For instance, `kubectl describe --help` reports that only the following syntax is accepted:

`kubectl expose (-f FILENAME | TYPE NAME)`

When it should be:

`kubectl expose (-f FILENAME | TYPE NAME | TYPE/NAME)`

**Why is this needed**:

To have consistency over the manpages.

**Comment by eddiezane** [comment]
@explogx we would accept a PR if you'd like to audit the help outputs for this.

/triage accepted
/priority backlog

**Comment by explogx** [comment]
@eddiezane sure I'll do this when I have time
