### ISSUE TITLE
refreshPod should be true at first? active Pod should equal to freshPod

### ISSUE THREAD

**Issue by LetLifeStop** [kubernetes/kubectl#1158]
https://github.com/kubernetes/kubectl/blob/d7da6ad9f193e3afdc754527c0a5ac9390c053fb/pkg/drain/drain.go#L285
```
refreshPod := false
...
activePod := pod
if refreshPod {
    freshPod, err := getPodFn(pod.Namespace, pod.Name)
   // We ignore errors and let eviction sort it out with
   // the original pod.
   if err == nil {
       activePod = *freshPod
   }
  re.freshPod = false
}
```

**Comment by eddiezane** [comment]
@LetLifeStop can you please provide more info here? Did you come across this as an issue for something?

**Comment by pandaamanda** [comment]
> @LetLifeStop can you please provide more info here? Did you come across this as an issue for something?

can not find code where set refreshPod = true.  should set refreshPod := true, or set  at other place.

**Comment by LetLifeStop** [comment]
> 
["can not find code where set refreshPod = true. should set refreshPod := true, or set at other place." ], that‘s what I mean。


> <img alt="@eddiezane" width="40" height="40" src="https://avatars.githubusercontent.com/u/959573?s=88&amp;v=4">

**Comment by LetLifeStop** [comment]
> > @LetLifeStop can you please provide more info here? Did you come across this as an issue for something?
> 
> can not find code where set refreshPod = true. should set refreshPod := true, or set at other place.

yeah, that's what I mean

**Comment by LetLifeStop** [comment]
> can not find code where set refreshPod = true. should set refreshPod := true, or set at other place.

can not find code where set refreshPod = true. should set refreshPod := true, or set at other place.

**Comment by eddiezane** [comment]
We would accept a PR here that has a test which demonstrates the correct behavior either way.

/triage accepted
/priority backlog
