### ISSUE TITLE
Print ingress class name while describing ingress resource(s)

### ISSUE THREAD

**Issue by akshitgrover** [kubernetes/kubectl#1160]
**What would you like to be added**:
Add `spec.ingressClassName` in the output of `kubectl describe ingress <ingressName/no-name-but-list>`

**Why is this needed**:
Now that ingress controllers use spec.ingressClassName to decided weather it should implement that particular ingress or not, It is important for a person maintaining the cluster to know which ingress is being implemented by which ingress controller thus class.

**Comment by akshitgrover** [comment]
I am willing to work on it once it's triaged
Thank you

**Comment by rikatz** [comment]
I see no reason why we shouldn't do this :) 

Also, maybe adding this to the kubectl get ingress is something desired? IMO it is

**Comment by akshitgrover** [comment]
That makes sense too
It should be added in both get and describe outputs

**Comment by eddiezane** [comment]
/triage accepted
/priority backlog
/help

This work would be done here https://github.com/kubernetes/kubernetes/blob/afd254a18f1a3ac44f8cdb7b6f0f1a83d35f3a37/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L2544

**Comment by rikatz** [comment]
/assign @akshitgrover 
/remove-help
/remove-good-first-issue

@akshitgrover this gots accepted. As you are willing to work on it, go for it!

**Comment by mpuckett159** [comment]
Hey not sure if this is still actively being worked on but was poking around. It looks like the class got added in `kubectl get ingress` at some point. Looks like a simple one(-ish) liner to get this added to the describe output. I can push a PR for it but wanted to make sure I wasn't stepping on anyone's toes.
