### ISSUE TITLE
Rollout status hangs for 5 minutes after success message

### ISSUE THREAD

**Issue by RalphDriessen** [kubernetes/kubectl#1163]
**What happened**:
After running 
```
kubectl rollout status deployment/my-app
``` 
the client returns `deployment "my-app" successfully rolled out`. After this it's stuck for ~5 minutes causing our pipeline to run for a long time because this happens for every service for which we call `rollout status` (also happens when running from a local client). This is happening only on the cluster that we recently upgraded to kubernetes v1.21.8. On the clusters running kubernetes v1.19.7 this is issue is not happening. I tried passing `--watch=false`, selecting a specific revision and not providing the namespace but those didn't change anything.

**What you expected to happen**:
I expect the process to finish shortly after the success message is displayed (as is happening on the clusters running the older kubernetes version).

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl rollout status deployment/my-app
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
- OS:
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by eddiezane** [comment]
Please check if this is happening with the latest version of kubectl (v1.23.1) and please rerun with verbose logging turned on `-v 10`.

**Comment by RalphDriessen** [comment]
Still happens using Client version:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1",
 GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
```
Running with verbose logging turned on resulted in the log in the attachment.
[kubectllog.txt](https://github.com/kubernetes/kubectl/files/7846221/kubectllog.txt)

**Comment by eddiezane** [comment]
Thanks for the logs.

```
I0111 10:23:01.067928   87513 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.23.1 (darwin/arm64) kubernetes/86ec240" -H "Authorization: Bearer <masked>" 'https://rancher.domain/k8s/clusters/c-8wtls/apis/apps/v1/namespaces/default/deployments?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dmy-app&resourceVersion=12167090&timeoutSeconds=566&watch=true'
deployment "my-app-deployment" successfully rolled out
I0111 10:32:27.113863   87513 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 566057 ms Duration 566057 ms
```

`timeoutSeconds=566` `ServerProcessing 566057 ms Duration 566057 ms` `10:23 10:32`

That timeout is definitely being hit. I wonder if it could be this 

https://github.com/kubernetes/kubernetes/pull/107460
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1218

Are you able to upgrade to 1.21.9 and test?

**Comment by RalphDriessen** [comment]
Unfortunately not... We are using Rancher and currently on v2.6.2 which only support Kubernetes versions up to v1.21.8. As soon as we can upgrade we will certainly try and I'll report back.
Thanks for the help!

**Comment by eddiezane** [comment]
I'm going to close this to get it out of our queue but please reopen if you're still seeing this after that upgrade.

/close

**Comment by RalphDriessen** [comment]
Unfortunately this issue is still happening after upgrading to v1.21.9:
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
I attached the logs of the latest run.
[kubectllog-2.txt](https://github.com/kubernetes/kubectl/files/8246014/kubectllog-2.txt)

**Comment by harjas27** [comment]
@RalphDriessen I notice that the success message does not appear this time in the logs

**Comment by RalphDriessen** [comment]
> @RalphDriessen I notice that the success message does not appear this time in the logs

Hm, guess it actually failed that time.. Here is another log from today where the success message is actually there.
[kubectllog-3.txt](https://github.com/kubernetes/kubectl/files/8361487/kubectllog-3.txt)

**Comment by eddiezane** [comment]
We need to look into where this connection is supposed to be closed. A context is timing out. Might be client might be server.

**Comment by brianpursley** [comment]
I also tried to reproduce this, but was not able.

Here is a bash script I was using:
```
#!/bin/bash

kubectl apply -f - << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: bar
        image: busybox:1.30
        command: ['sh', '-c', 'echo Container bar is running! && sleep 9999999']
EOF
kubectl rollout status deployment/foo

for VERSION in 1.31 1.32 1.33 1.34 1.35
do
  kubectl set image deploy/foo bar=busybox:$VERSION
  kubectl rollout status deployment/foo
done

kubectl delete deploy foo --wait=false
```

@RalphDriessen Does this problem happen for all deployments, or just this one deployment?  Does the deployment use any volumes, or have any other dependencies?  I'm trying to understand if there is some situation particular to your deployment that would make this reproducible.  Would you be able to share your deployment's manifest, even if some of the info is redacted?

Alternatively, would you be able to run a test using the bash script like what I posted above?

**Comment by RalphDriessen** [comment]
> @RalphDriessen Does this problem happen for all deployments, or just this one deployment? Does the deployment use any volumes, or have any other dependencies? I'm trying to understand if there is some situation particular to your deployment that would make this reproducible. Would you be able to share your deployment's manifest, even if some of the info is redacted?
> 
> Alternatively, would you be able to run a test using the bash script like what I posted above?

@brianpursley Thanks for your reply! It indeed happens for all our deployments which outside of our own apps contain mysql and redis images. The bash script you send ran fine and had no delay on the rollout status. 
Our deployment has some dependencies, this is the manifest (couldn't upload yaml so it's txt):
[manifest.yaml.txt](https://github.com/kubernetes/kubectl/files/8409168/manifest.yaml.txt)

**Comment by KokoBello** [comment]
We are experiencing the same issue. We're running the a rancher rke cluster, behind a reverse proxy, and the rolluout command only hangs when accessing through the reverse proxy, not while running from "inside"

**Comment by eddiezane** [comment]
@reylejano are you able to reproduce this or aware of any known issues specific to Rancher?

**Comment by reylejano** [comment]
I'm not able to reproduce this
@KokoBello @RalphDriessen 
Are you running `kubectl rollout status` through the Rancher proxy or using the authorized cluster endpoint?

**Comment by KokoBello** [comment]
> I'm not able to reproduce this
> @KokoBello @RalphDriessen 
> Are you running `kubectl rollout status` through the Rancher proxy or using the authorized cluster endpoint?

Rancher proxy

**Comment by reylejano** [comment]
> timeoutSeconds=566 ServerProcessing 566057 ms Duration 566057 ms 10:23 10:32

> That timeout is definitely being hit. I wonder if it could be this

> Are you able to upgrade to 1.21.9 and test?

@KokoBello @RalphDriessen , if you are able to upgrade Rancher:
- Rancher 2.6.3 has 1.21.10
- Rancher 2.6.4 has 1.21.10 and 1.22.7

I suggest to test bypassing the Rancher authentication proxy with the [authorized cluster endpoint](https://rancher.com/docs/rancher/v2.6/en/overview/architecture/#4-authorized-cluster-endpoint-ace) and if the issue is not reproduced then there may be a nuance with going through the Rancher proxy and being behind a reverse proxy.

**Comment by RalphDriessen** [comment]
@reylejano, I upgraded kubernetes to 1.22.7 but that unfortunately had no effect on this. However, accessing through the authorized cluster endpoint actually did 'fix' the issue... Could then be a new issue in rancher proxy because we don't have the problem in our clusters running on an older version of rancher (2.5.1). Thanks for your help!

**Comment by reylejano** [comment]
@RalphDriessen @KokoBello , since using the authorized cluster endpoint 'fixed' the issue, we can close this issue and can you create an issue on https://github.com/rancher/rancher and we can continue there

**Comment by RalphDriessen** [comment]
Created issue at [Rancher](https://github.com/rancher/rancher): https://github.com/rancher/rancher/issues/37241. Closing this issue.
