### ISSUE TITLE
Add an option to set-image that reuses the current image name and only changes the tag

### ISSUE THREAD

**Issue by wederbrand** [kubernetes/kubectl#1164]
**What would you like to be added**:
Normally I change the image on a deployment by just changing the tag, but I have to type out the complete image name. I would like for an option to only set the tag.

Example
`kubectl set image deployment web-frontend *=:1.2.3`

**Why is this needed**:
Save time and produce less errors when running set-image

**Comment by danishprakash** [comment]
That sounds like a nice addition, @eddiezane if and when we (triage and)accept this, mind If I take a shot at this?

**Comment by eddiezane** [comment]
Thanks for the valid request!

We discussed this and determined the trade off of complexity + risk does not outweigh the convenience here.

We recommend scripting this as a bash function.

/triage unresolved
/close
