### ISSUE TITLE
kubectl logs --tail shorthand

### ISSUE THREAD

**Issue by John4266** [kubernetes/kubectl#1167]
**What would you like to be added**:
I would like shorthand of `--tail` argument to be added.
Maybe something like `-t`

**Why is this needed**:
Just to make using logs with `tail` a bit easier/faster.

**Comment by danishprakash** [comment]
looks trivial to add https://github.com/danishprakash/kubernetes/commit/ab72ba1f2ebc864e1f79813e2c8cecc1b910a935 cc/ @eddiezane

**Comment by danishprakash** [comment]
Seems to be a small enough change https://github.com/danishprakash/kubernetes/commit/ab72ba1f2ebc864e1f79813e2c8cecc1b910a935 cc/ @eddiezane

**Comment by eddiezane** [comment]
The change is indeed small but kubectl has been suffering from flag creep for a while. Take a look at the output of `kubectl get --help`.  https://github.com/kubernetes/kubernetes/pull/104736 will help with the formatting but as maintainers we've been trying to avoid introducing new flags unless absolutely necessary.

While a valid request I don't think this warrants the saved 4 keystrokes.

**Comment by eddiezane** [comment]
We discussed this and recommend using a bash alias here.

```
alias klogt="kubectl logs --tail=-1"
```

/close
