### ISSUE TITLE
Kubectl querying the wrong resource

### ISSUE THREAD

**Issue by rgherta** [kubernetes/kubectl#1168]
**What happened**:

[admin@somehost tmp]$ kubectl create ingress demo-localhost --class=haproxy   --rule=/*=demo:80 --v=2
error: failed to create ingress: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found

I deleted the entire ingress-nginx namespace, no more resources from previous ingress only the ingressclass
I deleted also the .cache dir

NAME                                                              READY   STATUS    RESTARTS   AGE
pod/demo-764c97f6fd-hhlvd                                         1/1     Running   0          97m
pod/demo-764c97f6fd-j8rcf                                         1/1     Running   0          97m
pod/demo-764c97f6fd-s86k8                                         1/1     Running   0          131m
pod/example-deployment-794c55fbbd-cmt2v                           1/1     Running   0          11h
pod/example-deployment-794c55fbbd-pmpjz                           1/1     Running   0          11h
pod/haproxy-kubernetes-ingress-5dbb66955f-df5ht                   1/1     Running   0          11m
pod/haproxy-kubernetes-ingress-5dbb66955f-xqvd6                   1/1     Running   0          11m
pod/haproxy-kubernetes-ingress-default-backend-59dc4b55d9-5pfmd   1/1     Running   0          11m
pod/haproxy-kubernetes-ingress-default-backend-59dc4b55d9-7tqqm   1/1     Running   0          11m

NAME                                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                     AGE
service/demo                                         NodePort    172.168.84.200   <none>        80:32220/TCP                                131m
service/haproxy-kubernetes-ingress                   NodePort    172.168.160.61   <none>        80:32445/TCP,443:31545/TCP,1024:30117/TCP   11m
service/haproxy-kubernetes-ingress-default-backend   ClusterIP   None             <none>        8080/TCP                                    11m
service/kubernetes                                   ClusterIP   172.168.0.1      <none>        443/TCP                                     12h

NAME      CONTROLLER                               PARAMETERS   AGE
haproxy   haproxy.org/ingress-controller/haproxy   <none>       11m
nginx     k8s.io/ingress-nginx                     <none>       151m

**What you expected to happen**:

I expect to create an ingress for the haproxy class

I deleted the ingressclass nginx and I still have this attempt to call the admission controller of nginx, what is happening here.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): Centos Stream 9

**Comment by koba1t** [comment]
nginx-ingress installer was deploy to ValidatingWebhookConfiguration [here](https://github.com/kubernetes/ingress-nginx/blob/d16e0dec4865cbd5b937dbffb957423c308331c5/deploy/static/provider/cloud/deploy.yaml#L628-L660) and ValidatingWebhookConfiguration resources is not in Namespaced [^1] . 
Therefore, this resource is not cleanup when delete ingress-nginx namespace.


Try to delete from installer yaml file or delete this resource with command.
```
# Example
$ kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml

# or delete this resource with command
$ kubectl delete validatingwebhookconfigurations/ingress-nginx-admission
```

[^1]: [not-all-objects-are-in-a-namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace)
