### ISSUE TITLE
[UMBRELLA] Kubectl independence: code refactoring

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#117]
Part of #114.

Improve Kubectl independence by refactoring the code into well-documented, well-tested, re-usable pieces with mockable/fakeable interfaces. These pieces of code should have a limited number of dependencies (to avoid spaghetti).

The goal of this issue is to track the refactoring efforts.

- [ ] #132 Walking/Reading/Writing to Unstructured types with OpenAPI
- [ ] #133 Move packages from `k8s.io/kubernetes/pkg/kubectl` to `k8s.io/kubectl/pkg`

**Comment by seans3** [comment]
Closing this because we're tracking this issue here: 
https://github.com/kubernetes/kubectl/issues/80
/close
