### ISSUE TITLE
kubectl get --watch should update resource statuses in place

### ISSUE THREAD

**Issue by ryankrawz** [kubernetes/kubectl#1170]
When running a command like the following:
```
$ kubectl get pods -n dev --watch
```
The shell will continue to print lines whenever a pod undergoes a status change. As an example, as the pod `dev-data-0` spins up, the output below occurs.
```
NAME                                                         READY   STATUS              RESTARTS   AGE
dev-data-0                                                   0/1     Init:0/1            0          14s
dev-data-0                                                   0/1     PodInitializing     0          15s
dev-data-0                                                   0/1     Running             0          2m19s
dev-data-0                                                   1/1     Running             0          2m33s
```
The additional lines create a lot of noise and make the resource information difficult to read. Instead, updates to a single resource's status should occur **in place** and remain on a single line. Below is the previous example with the improved behavior.
```
NAME                                                         READY   STATUS              RESTARTS   AGE
dev-data-0                                                   0/1     Init:0/1            0          14s
```
After first update:
```
NAME                                                         READY   STATUS              RESTARTS   AGE
dev-data-0                                                   0/1     PodInitializing     0          15s
```
After second update:
```
NAME                                                         READY   STATUS              RESTARTS   AGE
dev-data-0                                                   0/1     Running             0          2m19s
```
After third update:
```
NAME                                                         READY   STATUS              RESTARTS   AGE
dev-data-0                                                   1/1     Running             0          2m33s
```

**Comment by eddiezane** [comment]
One day I'd like to have a more rich terminal UI like experience where we can do things like this easier. Maybe a kubeconfig context editor.

We could probably fake that now with an ANSI escape to clear the terminal but I'm not sure that works on Windows.

I actually use the `watch` utility instead to handle this for now which will just call the command every x seconds.

```
watch kubectl get pods -n dev
```

/triage accepted
/priority backlog

**Comment by sftim** [comment]
Also see: [kui](https://github.com/kubernetes-sigs/kui#readme)
