### ISSUE TITLE
kubectl describe ingress command should not default to hard-coded default backend in the kube-system namespace

### ISSUE THREAD

**Issue by alex-vmw** [kubernetes/kubectl#1172]
kubectl describe ingress command should not default to hard-coded default backend in the kube-system namespace (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L2636):
```
			// Ingresses that don't specify a default backend inherit the
			// default backend in the kube-system namespace.
			def = &networkingv1.IngressBackend{
				Service: &networkingv1.IngressServiceBackend{
					Name: "default-http-backend",
					Port: networkingv1.ServiceBackendPort{
						Number: 80,
					},
				},
			}
```
If the Ingress does not have a defined default backend, why not simply leave the default backend field empty?

On our Kubernetes clusters (and I am sure on many others), regular Kubernetes users do NOT have any permissions to the `kube-system` namespace, so every time users run `kubectl describe ingress` command they see a nasty permissions error like below:
```
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" is forbidden: User "REDACTED" cannot get resource "endpoints" in API group "" in the namespace "kube-system">)
```

**Comment by sftim** [comment]
The actual behavior of v1 Ingress in respect of a default backend, where none is explicitly specific, is controller-dependent - see https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

**Comment by eddiezane** [comment]
`default-http-backend` appears to be the [convention name](url) and not defined in the spec. https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1453-ingress-api#path-matching-semantics

@rikatz do you know?

Behavior-wise I'm not sure we should change it but we can wrap the error a bit better.

@alex-vmw do you have a suggestion for what would be more clear to your users?

**Comment by alex-vmw** [comment]
> @alex-vmw do you have a suggestion for what would be more clear to your users?

@eddiezane If the Ingress does not have an explicitly defined default backend, why not simply leave the default backend field empty?

**Comment by eddiezane** [comment]
@alex-vmw that's a possibility. I don't know the context behind why it was defaulted to this yet.

**Comment by eddiezane** [comment]
@soltysh to take a look

**Comment by Slayug** [comment]
> 
> On our Kubernetes clusters (and I am sure on many others), regular Kubernetes users do NOT have any permissions to the `kube-system` namespace, so every time users run `kubectl describe ingress` command they see a nasty permissions error like below:
> 
> ```
> Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" is forbidden: User "REDACTED" cannot get resource "endpoints" in API group "" in the namespace "kube-system">)
> ```

Yes it's also my case, is there any solution to allow these users to deploy their Ingress without giving them the permissions to `kube-system` namespace ?

**Comment by sftim** [comment]
> is there any solution to allow these users to deploy their Ingress without giving them the permissions to `kube-system` namespace ?

You can deploy an [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) that manages IngressClass etc for users that only have access to some namespaces. I don't know if an operator already exists that does so; what I do know is that it's not something that `kubectl` itself could help with.

**Comment by Slayug** [comment]
Thanks, I finally just added the default `defaultBackend` to my ingress.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
```

**Comment by jlsong01** [comment]
> With [kubernetes/kubernetes#108506](https://github.com/kubernetes/kubernetes/pull/108506) merged, is there more to do here?

IMO, no further work needed. Close it.
/close
