### ISSUE TITLE
add an option for `kubectl diff` to exit 0 when differences are found

### ISSUE THREAD

**Issue by jbouchery** [kubernetes/kubectl#1173]
**What would you like to be added**:
Hi ! I would like an option in the `kubectl diff` command to return an exit code 0 when diff are found instead of 1.

**Why is this needed**:
I need this because i would like to use `kubectl diff` in my CI/CD and actually it fails when exiting 1.

Thank you !

**Comment by lauchokyip** [comment]
This will be tracked here (https://github.com/kubernetes/enhancements/pull/2574)

**Comment by brianpursley** [comment]
Can you just do this using shell features?  like:
```
<your command> || true
```

**Comment by eddiezane** [comment]
Cheers there is a KEP for normalizing all exit codes in kubectl.

https://github.com/kubernetes/enhancements/pull/2574

/close

**Comment by jbouchery** [comment]
> Can you just do this using shell features? like:
> 
> ```
> <your command> || true
> ```

@brianpursley  actually i can't because it will return true on errors (exit codes >1).

Actually, i found out that many diff tools use this strategy for exit codes : 0, 1 and <1. But eventually, if i use a diff tool that provide a command to not return 1 on differences it works (like this project : [https://github.com/homeport/dyff](https://github.com/homeport/dyff))

```
export KUBECTL_EXTERNAL_DIFF="dyff between --omit-header"
```

@eddiezane, i'm not sure that this KEP resolves my issue, normalizing exit codes could resolve my issue to not return 1 when finding diffs?

Even if i can have my issue resolved i still think that this option could be possible.
