### ISSUE TITLE
When CRDs and CRs are deployed in the same apply, the apply will fail due to race condition

### ISSUE THREAD

**Issue by dniasoff** [kubernetes/kubectl#1179]
**What would you like to be added**:
I would like kubectl to optionally wait for CustomResourceDefinitions to be established before attempting to apply a Custom Resource that is dependent on it.

A suitable workflow is to just apply all CRDs, do the equivalent of ```kubectl wait --for=condition=established -f crds.yaml`` and then apply other resources

**Why is this needed**:
When deploying CRDs and CRs in the same apply, the apply of CRs will initially fail. Although you can then run another apply which will then work, this is messy

See https://github.com/kubernetes-sigs/kustomize/issues/3502

**Comment by eddiezane** [comment]
We've discussed this before and decided to keep kubectl unbiased on the resources it is applying.

We do have a better warning message planned though https://github.com/kubernetes/kubernetes/pull/107363

/close
