### ISSUE TITLE
Enable `kubectl` to complete `kubectl get pod/...`

### ISSUE THREAD

**Issue by dhirschfeld** [kubernetes/kubectl#1180]
**What would you like to be added**:
Testing in PowerShell, `kubectl` can complete the pod name if you use a space:
```
kubectl get pod <pod-name>
```
However if you use a forward-slash the completion doesn't work:
```
kubectl get pod/<pod-name>
```

**Why is this needed**:
It would be nice if the completions supported both formats since `kubectl` itself accepts both formats.

**Comment by eddiezane** [comment]
This is possible and Marc may be working on it.

/triage accepted
/priority backlog
/assign @marckhouzam

**Comment by marckhouzam** [comment]
PR now available: https://github.com/kubernetes/kubernetes/pull/108493

Feedback welcomed.
