### ISSUE TITLE
Path completion after `apply -k` not working when using kubectl alias

### ISSUE THREAD

**Issue by mtovmassian** [kubernetes/kubectl#1181]
**What happened**:
When using an alias for `kubectl` (here `k`) if I use the subcommand `apply` or `delete` with the Kustomize flag `-k` I cannot have path completion. Ex:
```bash
$ k apply -k <TAB>
```

**What you expected to happen**:
By hitting tab after the `apply -k` subcommand files and directories present in the current working directory should be listed:
```bash
$ k apply -k <TAB>
dir_a/ dir_b/ file_a file_b
```

**How to reproduce it (as minimally and precisely as possible)**:

Create a Bash alias that points to `kubectl` command and extend kubectl auto-completion for this alias like documented in the [official documentation](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/#bash)

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.23.4 / v1.23.1
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.4 LTS
- Shell: Bash

**Comment by marckhouzam** [comment]
Hi @mtovmassian, I cannot reproduce the problem myself.

Do you get file completion if you use the `-f` flag instead? E.g., `k apply -f [tab][tab]`?

**Comment by mtovmassian** [comment]
Hi @marckhouzam,
In my case completion works fine with the `-f` flag...

**Comment by eddiezane** [comment]
Hi @mtovmassian - I tested with a fresh Ubuntu 20.04 VM and I am also not able to reproduce this.

Have you tried deleting the completion file and creating it again?

**Comment by mtovmassian** [comment]
Hi @eddiezane,
I have deleted and recreated the completion file and issue is still the same.

I guess you can experienced the issue within an Ubuntu 20.04 Docker container after completing these steps:
- `apt-get update && apt-get install -y curl`
- `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"`
- `install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl`
- `apt-get install bash-completion`
- `source /usr/share/bash-completion/bash_completion`
- `echo 'source <(kubectl completion bash)' >>~/.bashrc`
- `echo 'alias k=kubectl' >>~/.bashrc`
- `echo 'complete -F __start_kubectl k' >>~/.bashrc`
- `source ~/.bashrc`

Then you should able to reproduce this kind of behaviour:
```bash
root@10f4b639b9dd:/# kubectl apply -k <TAB>
.dockerenv  bin/        dev/        home/       lib/        lib64/      media/      opt/        root/       sbin/       sys/        usr/        
.r/         boot/       etc/        kubectl     lib32/      libx32/     mnt/        proc/       run/        srv/        tmp/        var/ 
root@10f4b639b9dd:/# k apply -k <TAB>
```

**Comment by brianpursley** [comment]
It looks like I am able to reproduce it on my machine (Ubuntu 20.04 using kubectl 1.24)

Works:
* `kubectl apply -k <TAB>`
* `kubectl apply -f <TAB>`
* `k apply -f <TAB>`

Does not work:
* `k apply -k <TAB>`

If I recall, there is some environment variable that can be used to tell cobra to write a debug log for completions.  I wonder if that might have some information about what is happening.

**Comment by eddiezane** [comment]
Thanks @mtovmassian! I was able to reproduce it with your instructions.

> If I recall, there is some environment variable that can be used to tell cobra to write a debug log for completions. I wonder if that might have some information about what is happening.

 `export BASH_COMP_DEBUG_FILE=somefile` and then tail it

```
__kubectl_handle_word: c is 0 words[c] is k
__kubectl_handle_command: c is 0 words[c] is k
__kubectl_handle_command: looking for _kubectl_root_command
__kubectl_handle_word: c is 1 words[c] is apply
__kubectl_handle_command: c is 1 words[c] is apply
__kubectl_handle_command: looking for _kubectl_apply
__kubectl_handle_word: c is 2 words[c] is -k
__kubectl_handle_flag: c is 2 words[c] is -k
__kubectl_handle_flag: looking for -k
__kubectl_handle_flag: found a flag -k, skip the next argument
__kubectl_handle_reply
```

But this is no different from `-f`

```
__kubectl_handle_word: c is 0 words[c] is k
__kubectl_handle_command: c is 0 words[c] is k
__kubectl_handle_command: looking for _kubectl_root_command
__kubectl_handle_word: c is 1 words[c] is apply
__kubectl_handle_command: c is 1 words[c] is apply
__kubectl_handle_command: looking for _kubectl_apply
__kubectl_handle_word: c is 2 words[c] is -f
__kubectl_handle_flag: c is 2 words[c] is -f
__kubectl_handle_flag: looking for -f
__kubectl_handle_flag: found a flag -f, skip the next argument
__kubectl_handle_reply
```

**Comment by marckhouzam** [comment]
I was concerned this was a bug with Cobra so I investigated some more and I believe I found the problem.
The trick was to run this:
```
$ complete | grep kubectl
complete -o default -F __start_kubectl kubectl
complete -F __start_kubectl k
```
Notice the missing `-o default` for the `k` alias.  For bash, `-o default` means to use the default completion settings which include doing file completion.  So the command to make the alias work should actually be `echo 'complete -o default -F __start_kubectl k' >>~/.bashrc`

It looks like the documentation is at fault: https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/#bash

And we were unlucky in our investigation because the `-f` flag explicitly enables file completion as it filters on `.yaml|.yaml|.json` files, so it wasn't affected by the problem.

@mtovmassian could you try doing `complete -o default -F __start_kubectl k` and let us know if it fixes the problem?

**Comment by mtovmassian** [comment]
Thank you @marckhouzam,
Indeed it seems to be just a documentation issue.
I edited my _.bashrc_ with `complete -o default -F __start_kubectl k` and now path completion after `-k` flag works as expected!

**Comment by eddiezane** [comment]
Nice find, Marc!

@mtovmassian can I tempt you into opening a PR to fix the docs :innocent:?

**Comment by marckhouzam** [comment]
This is waiting for this website PR to be merged: https://github.com/kubernetes/website/pull/32127
