### ISSUE TITLE
kubectl scale doesn't work with piped file input

### ISSUE THREAD

**Issue by dgidwani-tibco** [kubernetes/kubectl#1183]
**What happened**:
While scaling deployments using piped input, it throws an error
`cat test_deployment.json | kubectl scale --replicas=0 -f -`
 _error: no objects passed to scale_

**What you expected to happen**:
kubectl scale should work from piped file (-f -) and it should scale those resources

**How to reproduce it (as minimally and precisely as possible)**:
1. create a simple nginx deployment and then Scale the nginx deployment using piped file input
```
kubectl create deployment nginx --image=nginx
kubectl get deploy nginx -o json  | kubectl scale --replicas=0 -f -
```

 ( it throws an error _error: no objects passed to scale_ )

**Anything else we need to know?**:
If we store the output of kubectl get deploy nginx -o json to a file and then use that filename, the scale command works fine
```
kubectl get deploy nginx -o json > test_deployment.json
kubectl scale --replicas=0 -f test_deployment.json
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.21.5(client)/v1.21.5-eks-bc4871b(server)
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): MacOS ( 11.6 )
<img width="553" alt="Screen Shot 2022-03-07 at 10 54 33 AM" src="https://user-images.githubusercontent.com/30919559/157069368-28c8643a-80a5-4103-ac92-6981386dce9d.png">

**Comment by harjas27** [comment]
I am able to reproduce the same using the steps provided in description.
Digging into the code, there are two `Visit(fn VisitorFunc)` calls:
https://github.com/kubernetes/kubectl/blob/fdbcc2710435e59cee996dccd6d219b4ed98fff3/pkg/cmd/scale/scale.go#L213-L238
the function does not traverse the resources the second time and thus there is no increment to the counter which leads to the error
This behaviour is documented in `k8s.io/cli-runtime/pkg/resource/result.go` :
```
// Note that some visitor sources are not traversable more than once, or may
// return different results.  If you wish to operate on the same set of resources
// multiple times, use the Infos() method.
```
As a fix, need to reuse the `infos` returned from the first call as is done in other commands like `describe`

**Comment by eddiezane** [comment]
@harjas27 are you interested in working on this?

/triage accepted
/priority backlog

**Comment by harjas27** [comment]
@eddiezane  yes, I will work on this
/assign @harjas27
