### ISSUE TITLE
Make cache-dir configurable wih env variable

### ISSUE THREAD

**Issue by strigazi** [kubernetes/kubectl#1184]
**What would you like to be added**:
Make kubectl use an optional environment variable to configure the cache-dir.

https://kubernetes.io/docs/reference/kubectl/kubectl/
--cache-dir string     Default: "$HOME/.kube/cache"
Default cache directory

**Why is this needed**:
At the moment, users have to pass the --cache-dir option on every kubectl execution, with an environment variable (similar to KUBECONFIG), they will have to set it once.

**Comment by ardaguclu** [comment]
`cache-dir` is used by discovery and kubectl commands using discovery are `api-resource`, `create` and a few others(`autoscale`, `version`).There is no need to pass `cache-dir` in every execution, if you need to customize `cache-dir`. You can just pass `cache-dir` for the commands using discovery.

I understand the inconvenience in here(From the user perspective, how user knows which command uses discovery and which one not). But there is an ongoing work on discovery caching. Even though it is small, there is a probability that `cache-dir` will be removed. At that point, I think we might not want to add new environment variable.

**Comment by traylenator** [comment]
I'd take a step back as to what we were trying to achieve.

The default cache is `$HOME/.kube/cache`

We want to be able to make the default cache `$XDG_RUNTIME_DIR}kubecache`
since it is a much quicker filesystem. 

It's probably a better default generally though possibly a bit linuxy "sic" for sure.
