### ISSUE TITLE
Support changing Service resource type with "kubectl set"

### ISSUE THREAD

**Issue by pcgeek86** [kubernetes/kubectl#1188]
**What would you like to be added**:

Implement the ability for the `kubectl set` command to change the type of a Kubernetes `v1\Service` resource.

```
kubectl set service argocd-server --type LoadBalancer
```

**Why is this needed**:

At the moment, the process for changing the `type` of a `Service` resource is confusing for newcomers, as you have to resort to using the `kubectl patch` command and pass in some specific JSON text that's hard to remember.

```
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
```

**Comment by eddiezane** [comment]
Set is an imperative command and we want to avoid expanding it in this way. We recommend using apply.

We would consider a generic solution but deeply setting values akin to `kubectl config set`.

/triage unresolved
