### ISSUE TITLE
KUBECONFIG not exporting all files in definition

### ISSUE THREAD

**Issue by MushiTheMoshi** [kubernetes/kubectl#1195]
**What happened**:
when exporting KUBECONFIG env var, not able to switch between contexts defined in variable
export KUBECONFIG=$KUBECONFIG:~/.kube/dev:~/.kube/qa

**What you expected to happen**:
after exporting KUBECONFIG I should be to kubectl config set-context dev/qa which is not working it's always pointing to one or another.

**How to reproduce it (as minimally and precisely as possible)**:
export KUBECONFIG=$KUBECONFIG:~/.kube/dev:~/.kube/qa
kubectl config set-context qa
kubectl config set-context dev

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- aws-cli/2.1.24 Python/3.7.3 Linux/4.14.262-200.489.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off
- OS (e.g: `cat /etc/os-release`):
- NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

Hope you can help me!

Thanks in advance,
Julio

**Comment by KnVerey** [comment]
> not able to switch between contexts defined in variable

Were you intending to use `kubectl config use-context` rather than `kubectl config set-context`? The former switches and the latter modifies. I did a couple tests and was able to use both of those commands with similarly combined kubeconfigs without issue.

/triage not-reproducible

**Comment by MushiTheMoshi** [comment]
Thanks for the quick response! 

You are right is working using use-context also the kubeconfig view is now working!

Please close this.

Thank you so much for your help!
