### ISSUE TITLE
Work with Multiple Clusters Simultaneously 

### ISSUE THREAD

**Issue by tigerpeng2001** [kubernetes/kubectl#1197]
**What would you like to be added**:
Work with multiple clusters simultaneously by specifying the cluster name on the command line.

**Why is this needed**:
Sometimes, I need to monitor multiple clusters, as well as make changes to another one at the same time.

**Comment by brianpursley** [comment]
Have you looked at [kubectx](https://github.com/ahmetb/kubectx)?

**Comment by tigerpeng2001** [comment]
> 

kubectx let me switch around the cluster. as kubectx and kubectl all use one ~/.aws/config so it is globally. 
Could kubectl (and kubectx) have --local config like git?
