### ISSUE TITLE
Add kubectl create for missing workloads

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#12]
Add new `kubectl create` commands for missing workloads.  Flags for fields shared between all workloads - e.g. `image` (and everything else in Pod or PodTemplate) should be factored into a single library.  Flags for field shared between many workloads should be factored into another library - e.g. `replicas`.

- `create statefulset`
- `create daemonset`
- `create replicaset`
- `create pod`

**Comment by zjj2wry** [comment]
@pwittrock @alexandercampbell seems intersting with this. Can I have a go at this?

**Comment by alexandercampbell** [comment]
/unassign
/assign @zjj2wry 
Sure, go for it.

**Comment by zhangxiaoyu-zidif** [comment]
Good to see it :) :+1:

**Comment by dixudx** [comment]
@pwittrock and others I'm working on `statefulset`. Already submitted a [PR #51944](https://github.com/kubernetes/kubernetes/pull/51944). PTAL.

**Comment by dixudx** [comment]
@pwittrock and others I'm working on `replicaset`. Already submitted a [PR #51946](https://github.com/kubernetes/kubernetes/pull/51946). PTAL.

**Comment by nikhita** [comment]
This is still relevant, right? Please close this PR again if it is no longer relevant.

/remove-lifecycle rotten
/assign

**Comment by seans3** [comment]
@pwittrock This work has been completed--right?

**Comment by TheKangaroo** [comment]
This is still not possible with kubectl v1.13.1, right?

**Comment by prksu** [comment]
interested doing for it
