### ISSUE TITLE
Cannot autocomplete kubectl bash aliases

### ISSUE THREAD

**Issue by calind** [kubernetes/kubectl#120]
The default `kubectl` complete function `__start_kubectl` does not work with bash aliases:

```
# ~/.aliases
alias k="kubectl"
complete -o default -F __start_kubectl k
```

__Actual output:__
```
~$ k [TAB]
k kubectl

~$ k k [TAB]
k kubectl
```

__Expected output:__
```
~$ k [TAB]
annotate        convert         expose          rolling-update
api-versions    cordon          get             rollout
apply           cp              label           run
attach          create          logs            scale
auth            delete          options         set
autoscale       describe        patch           taint
certificate     drain           plugin          top
cluster-info    edit            port-forward    uncordon
completion      exec            proxy           version
config          explain         replace
```

**Comment by drywheat** [comment]
I can confirm the same behavior on my end

**Comment by amalucelli** [comment]
I don't know if this is the best/right solution, but I made `k` autocomplete by doing `source <(kubectl completion bash | sed 's/kubectl/k/g')`.

**Comment by saj** [comment]
https://github.com/cykerway/complete-alias is kind of amazing.  With this, there is no need to modify the original completion functions, and it works with lazily-loaded completions.

**Comment by josephspurrier** [comment]
Same issue on my end in OS X.

**Comment by mengqiy** [comment]
Can someone help to update the vendor to pick up the fix in cobra?

**Comment by weibeld** [comment]
With Zsh, completion works with aliases as well, but with Bash not. Probably the best workaround is to use [complete-alias](https://github.com/cykerway/complete-alias). Install it by sourcing the main file in your `~/.bashrc`. Then, for every alias for which you want to enable completion, add the following to your `~/.bashrc` file:

~~~bash
complete -F _complete_alias my-alias
~~~

**Comment by briantopping** [comment]
@weibeld `complete-alias` doesn't work on Mac. I've spent the last hour trying to make it work, no dice. The author ignored a patch to make it work. I gave it props in a stack exchange discussion, it does work on Linux. But it's not a generalized solution.

**Comment by weibeld** [comment]
@briantopping `complete-alias` works on Mac, but not with Bash 3.2, which is the default on Mac. You can install Bash 5.0 (see for example [here](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)) and it will work. It also depends on [`bash-completion`](https://github.com/scop/bash-completion) 2.0+ (current version is 2.8).

So, if you don't use outdated tools, like the default Bash on Mac, `complete-alias` is a general solution too, the only dependencies are Bash 4.1+ and `bash-completion` 2.0+. I didn't yet try the Cobra solution, but it looks good too.

**Comment by briantopping** [comment]
> So, if you don't use outdated tools, like the default Bash on Mac

Yah, I'm a total putz at this stuff. Playskool "My First Mac" obviously wasn't enough training for something so monumental as getting aliases working. I stand corrected.

**Comment by nir-logzio** [comment]
@weibeld it doesn't work on mac. I followed your instructions here as well as your very elaborated posts on itnext.io but as @briantopping said, no dice.

**Comment by weibeld** [comment]
@nir-logzio what is your version of Bash and bash-completion?

**Comment by nir-logzio** [comment]
@weibeld
bash: 5.0.2(1)-release
completion: stable 2.8 (bottled)

**Comment by weibeld** [comment]
> @weibeld
> bash: 5.0.2(1)-release
> completion: stable 2.8 (bottled)

So what doesn't work? It's just that the completion of the aliases doesn't work, or is there an error message?

**Comment by nir-logzio** [comment]
The completion of aliases doesn't work. It starts by adding the original command to the completion instead of its options.

**Comment by weibeld** [comment]
Did you try with different aliases and commands? Maybe you can create a screencast and share it on [asciinema](https://asciinema.org/).

**Comment by nir-logzio** [comment]
@weibeld The original description from Nov 2017 describes it perfectly. No need to bother with a screencast

**Comment by weibeld** [comment]
@nir-logzio You did `complete -F _complete_alias k` (if `k` is your alias for `kubectl`) and the output is still like in the original post?

**Comment by briantopping** [comment]
@nir-logzio: Give a try to the solution @amalucelli provided above. That's what I am using. Upgrading bash is an option, but one I personally prefer to avoid for every new developer.

**Comment by nir-logzio** [comment]
@briantopping yes I've considered this option but as it is quite a hack I'm currently planning on trying zsh and perhaps gaining a few more advantages at the same time

**Comment by briantopping** [comment]
"Perfect is the enemy of the good..." :D

**Comment by weibeld** [comment]
@nir-logzio if you do `complete -F __start_kubectl k`, then obviously it doesn't work, because complete-alias is not used at all. You have to do `complete -F _complete_alias k` for every alias for which you want to enable completion.

@briantopping with this solution you can only have aliases for the base command, e.g. `k` for `kubectl`. But with complete-alias, you can have aliases like `alias kg='kubectl get'` and completion will propose options and arguments for `kubectl get` (not the sub-commands of `kubectl`).

**Comment by briantopping** [comment]
@weibeld: That doesn't matter much if complete-alias doesn't work. Thanks tho.

**Comment by weibeld** [comment]
@briantopping it just doesn't work on Bash 3.2 (which is more than 11 years old), but on every Bash version of 4.1 or greater, it should work perfectly, no matter if it's on Linux or Mac.

**Comment by infa-ddeore** [comment]
> I don't know if this is the best/right solution, but I made `k` autocomplete by doing `source <(kubectl completion bash | sed 's/kubectl/k/g')`.

I added this into ~/.basg_profile

**Comment by YoninL** [comment]
I followed official guide and the issue is gone.

https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

What I was missing is
```
echo 'complete -F __start_kubectl k' >>~/.bashrc
```

**Comment by whereisaaron** [comment]
The [official instructions](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion) are not working for me with `bash` 4.3 and 4.4. After adding the commands below, completing with `kubectl` works fine, but `k` doesn't. If I type 'k', 'space' and then press tab is expands to 'k kubectl' and then if I press tab again it starts completing `kubectl` commands. Do the official approach only work with `bash` 5.x?

This does not work, `k ` completes to `k kubectl`:
```
source <(kubectl completion bash)
alias k=kubectl
complete -F __start_kubectl k
```

Using [`complete_alias`](https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias) does work:
```
source <(kubectl completion bash)
alias k=kubectl
complete -F _complete_alias k
```

And this workaround of duplication the completions does also work:
```
source <(kubectl completion bash)
source <(kubectl completion bash | sed 's/kubectl/k/g')
```

**Comment by brianpursley** [comment]
Did you try this?
```
echo 'complete -F __start_kubectl k' >>~/.bashrc
```

**Comment by weibeld** [comment]
It should work with any Bash version 4.1+... @whereisaaron do you use macOS or Linux, and which version of [bash-completion](https://github.com/scop/bash-completion) do you have installed?

**Comment by brianpursley** [comment]
@whereisaaron Does this return anything for you?
```
declare -F | grep __start_kubectl
```

**Comment by vyaslav** [comment]
I came up with [this](https://gist.github.com/vyaslav/42a82ede8b8732f93177b40545e180b1) to autocomplete common aliases `kgp` `kl` `kex` ...

**Comment by jbeaudetupgrade** [comment]
I followed the [official instructions for macOS](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-mac/) and couldn't get it to work either without complete-alias. Bash version is `5.1.16(1)-release`. The output of `declare -f __start_kubectl` is the following :
```
$ declare -f __start_kubectl
__start_kubectl ()
{
    local cur prev words cword split;
    COMPREPLY=();
    if declare -F _init_completion > /dev/null 2>&1; then
        _init_completion -n "=:" || return;
    else
        __kubectl_init_completion -n "=:" || return;
    fi;
    __kubectl_debug;
    __kubectl_debug "========= starting completion logic ==========";
    __kubectl_debug "cur is ${cur}, words[*] is ${words[*]}, #words[@] is ${#words[@]}, cword is $cword";
    words=("${words[@]:0:$cword+1}");
    __kubectl_debug "Truncated words[*]: ${words[*]},";
    local out directive;
    __kubectl_get_completion_results;
    __kubectl_process_completion_results
}
```
Happy to provide more info if needed.

**Comment by marckhouzam** [comment]
@jbeaudetupgrade  if you run
```
complete | grep kubectl
```
You should see the standard `kubectl` entry (`complete -o default -F __start_kubectl kubectl`).

Do you see a line for your alias as well? You should. If not, then please re-execute the instructions you mentioned.

Hope this helps.

**Comment by jbeaudetupgrade** [comment]
@marckhouzam Yes I do see the entry on my `k` alias but somehow it's still not working : 
```
$ complete | grep kubectl
complete -o default -F __start_kubectl kubectl
complete -o default -F __start_kubectl k
```

**Comment by marckhouzam** [comment]
@jbeaudetupgrade  does the completion work when you don't use the alias but the full `kubectl`?

**Comment by jbeaudetupgrade** [comment]
@marckhouzam yes it works properly with `kubectl`.

**Comment by whereisaaron** [comment]
This is what still works for me on Linux. Based on the `bash_completion` source code this is tailor-made to expand the `k` alias as if I had entered `kubectl`. So it may be the 'right' way?
```
source <(kubectl completion bash)
alias k=kubectl
complete -F _complete_alias k
```
This is what the OG `kubectl` instructions said, but it has never worked:
```
# This didn't work
#complete -F __start_kubectl k
```

@weibeld bash 4.3, 4.4 and now 5.0.17 and I'm using Linux not a Mac. My `~/.bash_completion` mentions no version number, just:

```
#!/bin/bash

##  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
##  automagical shell alias completion;
##  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

##  ============================================================================
##  Copyright (C) 2016-2018 Cyker Way
```

@brianpursley my `declare -f __start_kubectl`
```
$ declare -f __start_kubectl
__start_kubectl ()
{
    local cur prev words cword;
    declare -A flaghash 2> /dev/null || :;
    declare -A aliashash 2> /dev/null || :;
    if declare -F _init_completion > /dev/null 2>&1; then
        _init_completion -s || return;
    else
        __kubectl_init_completion -n "=" || return;
    fi;
    local c=0;
    local flags=();
    local two_word_flags=();
    local local_nonpersistent_flags=();
    local flags_with_completion=();
    local flags_completion=();
    local commands=("kubectl");
    local must_have_one_flag=();
    local must_have_one_noun=();
    local has_completion_function;
    local last_command;
    local nouns=();
    __kubectl_handle_word
}
```

**Comment by neitrinoweb** [comment]
I was able to solve this problem on macOS by upgrading my bash version from 3.2 to 5.1.
