### ISSUE TITLE
kubectl fails to read token when run as non-root inside a pod

### ISSUE THREAD

**Issue by fireba11** [kubernetes/kubectl#1200]
**What happened**:
kubectl fails trying to read /root/.kube/config

**What you expected to happen**:
kubectl reading the token

**How to reproduce it (as minimally and precisely as possible)**:
have a non-root container call kubectl

**Anything else we need to know?**:
it seems to try (in that order)
* /home/[current user]/.kube/config
* /root/.kube/config
* access token mounted into the pod

to be that does not make any sense. if your container is running as non-root (as it should) and the current user doesn't have any kubeconfig there seems to be no sense in trying to read the kubeconfig from root since that should really not be readable.
also it seems to fail and stop there instead of looking for the token

current workaround i found
set env KUBECONFIG="/dev/null"
that seesm to avoid the read access to roots home folder and then finds the token -_-

**Environment**:
- Kubernetes client version (use `kubectl version`): 1.23.5

**Comment by eddiezane** [comment]
kubectl will not look specifically in `/root` for a config.

Can you please share a full reproduction example?

Also see https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides

**Comment by fireba11** [comment]
@eddiezane it seems the issue is caused by the official telegraf container i used. somewhere between 1.17.2 and 1.22.0 they changed how telegraf is run in the container.
old one just ran as root
new one runs as non-root but got some magic since telegraf might need to open ports etc. a normal user is not allowed to.
the latter causing my issues, the process most likely still has the env from root
