### ISSUE TITLE
Broken output schema running `kubectl apply --prune --dry-run=xyz -o yaml/json` with a single resource created.

### ISSUE THREAD

**Issue by cube2222** [kubernetes/kubectl#1201]
### What happened?

When applying a single resource (and instructed to -o yaml/json) kubectl will print that object directly, instead of printing it in an "items" array - as it does when applying multiple objects.

However, if instructed to also --prune resources then it will print the pruned resources but won't take them into account in this output schema decision.

So it ends up printing the raw objects one after each other, which in the case of yaml means it prints a big object with duplicate fields (that's a "merge" of all the created and pruned resources). For json that means it will print the json objects one after the other, without nesting them in an array.

### What did you expect to happen?

I'd expect it to print an array of items whenever it wants to print more than one object - whether those objects are created or pruned.

### How can we reproduce it (as minimally and precisely as possible)?

Apply a resource of any kind (i.e. a secret). Then apply another different resource with --prune (while not applying the first one, so that it gets pruned). Use `kubectl apply --dry-run=server -o yaml/json --prune`.

### Kubernetes version

<details>

```console
$ kubectl version
v1.23.5
```

</details>

**Comment by eddiezane** [comment]
@apelisse any thoughts here?

**Comment by apelisse** [comment]
First, prune is not really supported (@seans) so I don't know how much we'll want to support this.

Also, what do you mean you would expect "an array of items"?

**Comment by seans3** [comment]
/assign

Is `dry-run=server` supported?

**Comment by apelisse** [comment]
Yep, that's how you ask things to the server. Somewhere we must build a list but we don't with pruning?
