### ISSUE TITLE
Documentation of field-selector

### ISSUE THREAD

**Issue by AssafKatz3** [kubernetes/kubectl#1202]
**Adding field-selector command**: Which will print the possible options for field-selector parameter, similar to api-versions command (or maybe subcommand of it).

**Why is this needed**: Currently this information isn't publicly available [documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields) contains only:
`Supported field selectors vary by Kubernetes resource type. All resource types support the metadata.name and metadata.namespace fields. Using unsupported field selectors produces an error.`

**Comment by seans3** [comment]
Unfortunately, kubectl does not have access to the field selectors, so there is no way to do this in a maintainable way.

/close
