### ISSUE TITLE
kubectl create job: Specify --from and command

### ISSUE THREAD

**Issue by Warfront1** [kubernetes/kubectl#1206]
**What would you like to be added**: 
When you currently issue the following command (assuming you have a valid cronjob called `mycronjob`):
`kubectl create job --from=cronjob/mycronjob -- date`
You receive the following [error](https://github.com/kubernetes/kubectl/blob/18a5313a74f7d83f6b54377d72b421b5ebfa66c9/pkg/cmd/create/create_job.go#L173):
`error: cannot specify --from and command`

I would like to be able to execute this command without receiving an error.
I would like to be able to choose from a pre-existing cronjob, and also change the command at the same time while using `kubectl create job`

**Why is this needed**:
The current work arounds for this are [very rough looking](https://stackoverflow.com/questions/67187122/kubectl-create-job-from-cronjob-and-override-args), when simply allowing these two flags to work at the same time could save a lot of time and confusion. 
Essentially, most of the work arounds involve ripping the yaml config, manipulating it with an external tool (yq typically) and feeding it back in. 
But the use case of having to change the command seems so common, having it internal to kubectl seems appropriate; especially considering both flags are already available.

**Comment by soltysh** [comment]
We don't expect to introduce an option to modify jobs created from cronjobs. The idea was to have a one-offs only, without the ability to modify them. The available alternatives are sufficient for the rare cases where this is needed.
/close

**Comment by Wopple** [comment]
I'm just noting that this would be extremely useful for me as well. Honestly this feels like a missing feature. There's so much offered by `kubectl` that I have never and probably will never use. This however would be amazing.

**Comment by IllyaMoskvin** [comment]
> The available alternatives are sufficient for the rare cases where this is needed.

What are the available alternatives?
