### ISSUE TITLE
kubectl exec does not display errors on network disconnection and exits with code 0

### ISSUE THREAD

**Issue by chibbert** [kubernetes/kubectl#1208]
**What happened**:
kubectl exec does not display any errors and has exit code 0 if there is the network error while the command is running.

**What you expected to happen**:
kubectl should display an error describing the network condition and exit with a non-zero exit code.

**How to reproduce it (as minimally and precisely as possible)**:

```
# Start a pod running busybox (any image with sleep will do
kubectl run busybox --image=busybox:1.28 -- sleep 9999

# Exec into it an launch a long running command
kubectl exec busybox -- sleep 123

# Take down your network connection on the machine where kubectl is running (e.g. pull network cable or disconnect wifi etc)

# Observe that kubectl has exited without any error messages

# Exit code is 0:
echo $!

# Reconnect your network

# See that the "sleep 123" process we launched is still running
kubectl exec busybox -- ps aux

```
**Anything else we need to know?**:
Have tried a variety of docker containers with the same affect.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Server: 1.21.11
Client: 1.21.11 (also tried 1.20.10, 1.22.8, 1.23.5, 1.24.0)
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration:
GKE - cluster version 1.21.11-gke.1100
- OS (e.g: `cat /etc/os-release`):
WSL2 Ubuntu 20.04.1
`NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`

**Comment by brianpursley** [comment]
> echo $!

did you mean `echo $?`?

---

However, assuming you meant `$?`, I'm trying to reproduce this and am unable to so far.

After trying a couple of times, I modified your exec command a little so it would output something, like this:
```
kubectl exec busybox -- /bin/sh -c "for i in `seq -s ' ' 1 100`; do echo \$i && sleep 1; done"
```

When I turn off my wifi, kubectl remains running, but no output is displayed obviously.  Then after 20 seconds or so, when I turn wifi back on, it immediately "catches up" and I see all the numbers that where printed while I was disconnected.

My setup is different than yours though...
* I am using Ubuntu, not WSL2
* My cluster is self hosted, not GKE
* I'm using kubernetes version 1.25.0-alpha (I tried using kubectl 1.21.0 and still unable to reproduce it)

I wonder if any of those things might account for the difference.  Maybe I will see if I can try this on a GKE cluster.

Questions for you:
1. When you disconnect your network, does kubectl exit right away?
2. What container runtime is your cluster using?  Can you post the output of `kubectl describe node | grep "Container Runtime Version:"`

**Comment by eddiezane** [comment]
Please let us know if you can reproduce with the above ask.

/close

**Comment by HaxiSnake** [comment]
> Please let us know if you can reproduce with the above ask.
> 
> /close

Hello, I met this issue too.
And I do like this:
1. run a long time single command on a remote pod
`
kubectl exec busybox -- /bin/sh -c "sleep 600"
`
2.  turn off wifi, wait kubectl exit
3.  oberserve that  `sleep 600` still run in the pod
4. use echo $? to see it's return code, it returns 0, but I expect it  return non-zero.

Also, I try the command provided by @brianpursley , when kubectl exit, it's return code is 130, 
so i think the different between the command is that one is single commond, the other is multy command, is this will beheave differently at the return code?

Environment:

`
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
`
