### ISSUE TITLE
jsonpath patch

### ISSUE THREAD

**Issue by kaovilai** [kubernetes/kubectl#1213]
**What would you like to be added**:
Allow patching custom resource fields with jsonpath.

Example:
```sh
kubectl patch $(kubectl get csv -n openshift-adp -oname | grep oadp) -n openshift-adp --type='jsonpath' --patch "{.spec.install.spec.deployments[?(@.name=='openshift-adp-controller-manager')].spec.replicas}"  --patch-val "0"
```

**Why is this needed**:
It is already easy to query jsonpath on custom resource.
```sh
kubectl get $(kubectl get csv -n openshift-adp -oname) -n openshift-adp -ojsonpath="{.spec.install.spec.deployments[?(@.name=='openshift-adp-controller-manager')].spec.replicas}"
```

It is impossible to update this value without knowing ahead of time position of object in array with said name with `kubectl patch` today.

References:
https://stackoverflow.com/questions/43009349/jsonpatch-path-to-update-array-object-by-object-id

**Comment by soltysh** [comment]
We don't expect adding this kind of functionality to `kubectl patch`. The current mechanism is sufficient for majority of use cases we've run into. 
/close
