### ISSUE TITLE
Add junit output for kubectl apply for CI pipelines

### ISSUE THREAD

**Issue by galshi** [kubernetes/kubectl#1218]
**What would you like to be added**: A new output format for kubectl apply logs in the form of JUnit XMLs.

**Why is this needed**: When managing a cluster with GitOps I would also like to test the validity of the yamls in my CI pipeline before deploying, `kubectl apply --dry-run=server` seems to be the best option when you have network access to a cluster in your CI pipe, JUnit is a popular output format for testing tools that is supported by multiple related tools (for example, gitlab knows how to visualize the JUnit output of testing tools in merge requests).

I think this is a worthwhile feature to add as more and more people will begin to manage their clusters/apps in git, here's a little python script I made for myself while developing my own GitOps CI pipeline for reference https://github.com/galshi/validate-kubernetes-manifests/blob/main/validate_kubernetes-manifests/__main__.py.

**Comment by soltysh** [comment]
We don't expect adding XML output, I'd suggest creating your own transformer based on yaml/json output.
/close

**Comment by galshi** [comment]
@soltysh I don't have access to a k8s cluster, I work with openshift, but `oc apply --dry-run=server -o json/yaml` seems to just output the jsons/yamls to apply (while the normal output displays whatever applying an object succeeded or any resulting errors).
I assume the same is true for `kubectl` but can't check it, if that's the case I think some form of structured output for the results of `kubectl apply` is necessary.

**Comment by galshi** [comment]
Hi @soltysh, I think you've misunderstood the issue and that it's still relevant, please look at my previous comment.
