### ISSUE TITLE
kubectl wait timeout argument is poorly documented and ill-suited to waiting on multiple resources

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/kubectl#1219]
This is just a re-submit of https://github.com/kubernetes/kubectl/issues/754 which, despite being confirmed & assigned, was closed as stale without any fix.

**What happened**:

Run `kubectl wait` with a selector matching more than one resource and a timeout

**What you expected to happen**:

The timeout should apply to the wait command, not to the individual resources.

With the timeout applying to resources sequentially, it makes waiting on more than one resource with any kind of timeout basically unusable.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a deployment scaled to 2 or more replicas, and a label that can be used to match it
2. Run: `kubectl wait pod --selector=... --timeout=30s`
3. Observe that this runs for N*30s, where N is the number of pods

**Anything else we need to know?**:

cc @eranreshef the original reporter and @JabusKotze who assigned the prior issue to themselves

**Comment by vitalyrychkov** [comment]
Hello,

We have a similar problem, expecting kubectl wait to wait for X seconds in total with "--timeout=Xs", e.g.:

    kubectl  wait --for=condition=available --timeout=10m deployment --all

However it waits for X seconds * Number of deployments with not-ready pods. Could you please consider also our scenario in the fix?

Kind Regards,

Vitaly

**Comment by ardaguclu** [comment]
/remove-lifecycle stale

If anyone is not willing to take it, I can work on that.

**Comment by R-Studio** [comment]
**Workaround for those using `kubectl` or `oc` before v1.27**
You can use `timeout` before the `kubectl wait` or `oc wait`. For example with a timeout of max. 305s (the timeout of the `timeout` command should be a little larger then the timeout of the `kubectl` command):
```bash
timeout $((300+5)) kubectl wait --for=condition=Ready --all pod --timeout=300s
```
