### ISSUE TITLE
Kubectl drain ignore DaemonSet still gets DaemonSets

### ISSUE THREAD

**Issue by phillebaba** [kubernetes/kubectl#1220]
**What happened**:

When draining a node and ignoring DaemonSets kubectl will always fetch the owning DaemonSet if the Pod is owned by a DaemonSet.

**What you expected to happen**:

I would expect kubectl to completly ignore Pods owned by Daemonsets when filtering the Pods.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with kind.
```shell
kind create cluster
```

Dry run a drain and view the API calls.
```shell
kubectl drain kind-control-plane --ignore-daemonsets=true --dry-run=server -v=8
```

The DaemonSet on the node will be fetched.
```
I0526 17:28:22.796571  341196 round_trippers.go:463] GET https://127.0.0.1:38773/apis/apps/v1/namespaces/kube-system/daemonsets/kindnet
I0526 17:28:22.796582  341196 round_trippers.go:469] Request Headers:
I0526 17:28:22.796587  341196 round_trippers.go:473]     Accept: application/json, */*
I0526 17:28:22.796593  341196 round_trippers.go:473]     User-Agent: kubectl/v1.24.0 (linux/amd64) kubernetes/4ce5a89
I0526 17:28:22.797506  341196 round_trippers.go:574] Response Status: 200 OK in 0 milliseconds
I0526 17:28:22.797520  341196 round_trippers.go:577] Response Headers:
I0526 17:28:22.797525  341196 round_trippers.go:580]     Content-Type: application/json
I0526 17:28:22.797530  341196 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: a18e07ff-6940-45a1-a131-549ae8d386dd
I0526 17:28:22.797534  341196 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: bbe19b74-280f-4d20-845d-2868cfdcb516
I0526 17:28:22.797539  341196 round_trippers.go:580]     Date: Thu, 26 May 2022 15:28:22 GMT
I0526 17:28:22.797543  341196 round_trippers.go:580]     Audit-Id: d684746b-d035-4307-84f4-a395efc2200a
I0526 17:28:22.797548  341196 round_trippers.go:580]     Cache-Control: no-cache, private
I0526 17:28:22.797616  341196 request.go:1073] Response Body: {"kind":"DaemonSet","apiVersion":"apps/v1","metadata":{"name":"kindnet","namespace":"kube-system","uid":"a0e2ef5a-87ec-47fc-a1b9-bcbed5302209","resourceVersion":"406","generation":1,"creationTimestamp":"2022-05-26T15:26:38Z","labels":{"app":"kindnet","k8s-app":"kindnet","tier":"node"},"annotations":{"deprecated.daemonset.template.generation":"1"},"managedFields":[{"manager":"kubectl-create","operation":"Update","apiVersion":"apps/v1","time":"2022-05-26T15:26:38Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deprecated.daemonset.template.generation":{}},"f:labels":{".":{},"f:app":{},"f:k8s-app":{},"f:tier":{}}},"f:spec":{"f:revisionHistoryLimit":{},"f:selector":{},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{},"f:k8s-app":{},"f:tier":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"kindnet-cni\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"CONTROL_PLANE_ENDPOINT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"HOST_IP\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fiel [truncated 3553 chars]
```

**Anything else we need to know?**:

It is pretty questionable if this is actually an issue. It is from my part not expected that there is code which is getting each DaemonSet when you explicitly ignore DaemonSets. It might just be an oversight or behavior that is actually wanted.

The following code is where my issue is at. It will always check that a Pod is not orphaned by a DaemonSet.

https://github.com/kubernetes/kubectl/blob/1d7e71a12f476bb95d1eb550130505678d0d3c08/pkg/drain/filters.go#L190-L203

It is not really a big deal, but changing the order of these function calls can decrease the RBAC permissions needed to drain a node.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"archive", BuildDate:"2022-05-04T15:25:22Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Kind
- OS (e.g: `cat /etc/os-release`): Arch Linux

**Comment by pacoxu** [comment]
> is this resulting in an actual error to the user if they don't have permission?

Yes, I tried to fix it in https://github.com/kubernetes/kubernetes/pull/109610.
