### ISSUE TITLE
wrong example in configmap help

### ISSUE THREAD

**Issue by rgstori** [kubernetes/kubectl#1221]
**What happened**:
the fourth example in the configmap help (_Create a new config map named my-config from the key=value pairs in the file_) seems wrong - it's the same command as the first example:

```
Examples:
  # Create a new config map named my-config based on folder bar
  kubectl create configmap my-config --from-file=path/to/bar
  
  # Create a new config map named my-config with specified keys instead of file basenames on disk
  kubectl create configmap my-config --from-file=key1=/path/to/bar/file1.txt --from-file=key2=/path/to/bar/file2.txt
  
  # Create a new config map named my-config with key1=config1 and key2=config2
  kubectl create configmap my-config --from-literal=key1=config1 --from-literal=key2=config2
  
  # Create a new config map named my-config from the key=value pairs in the file
  kubectl create configmap my-config --from-file=path/to/bar
  
  # Create a new config map named my-config from an env file
  kubectl create configmap my-config --from-env-file=path/to/foo.env --from-env-file=path/to/bar.env

```
**What you expected to happen**:

have the fourth example use the `--from-env-file` option instead?

**How to reproduce it (as minimally and precisely as possible)**:

run `kubectl create configmap --help`                               

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): MacOS 12.4

**Comment by praveenrewar** [comment]
> have the fourth example use the --from-env-file option instead?

Then I think that the 4th and 5th example would be similar. Maybe we can combine them to have one example? Something like this:
```
# Create a new config map named my-config from the key=value pairs in an env file
  kubectl create configmap my-config --from-env-file=path/to/foo.env --from-env-file=path/to/bar.env
```

/assign

**Comment by watany-dev** [comment]
I found it, so I'll think of a simple idea and try to PR
