### ISSUE TITLE
Kubectl cp cannot parse Windows drive letters

### ISSUE THREAD

**Issue by Napokue** [kubernetes/kubectl#1225]
**What happened**:
When using the following command:
```bash
kubectl cp d:/test/ /etc/test
```

I am getting the error that the pod cannot be found. Which is true as the "d" specifies the pod.

**What you expected to happen**:
I expect that the "d" driver letter is getting parsed correctly as the "d" drive.

**How to reproduce it (as minimally and precisely as possible)**:
Using the command that I wrote above or an equivalent, should result in the error.

**Anything else we need to know?**:
It is totally understandable why this happens, as the ":" (colon) is used as a separation character to specify what is the pod and what is the path. This can be seen here: https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/cp/cp.go#L171.

The problem arises when as a Windows user I want to use the "D" (or any other drive letter) to make use of a full path.

A possible solution could be to add a flag that is specifically used to indicate that the copy happens from a Windows path.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.9
```
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`): Windows

**Comment by brianpursley** [comment]
It is actually not just a Windows problem, as it is valid to create a directory containing a colon in it on Linux:
```
~ $ mkdir foo:bar
~ $ cd foo:bar
~/foo:bar $
```

I'm guessing this would have the same problem.

As a workaround, can you do something like this?
```
pushd d:
kubectl cp /test/ SomePod:/etc/test
popd
```

One solution might be to change kubectl cp to always consider a quoted path to be a local path, like this:
```
kubectl cp "d:/test/" SomePod:/etc/test
```

Or to change kubectl cp to allow the colon to be escaped, like this:
```
kubectl cp d\:/test/ SomePod:/etc/test
```

Or both.  Both of those seem to be supported in Linux at least, like this:
```
~ $ cd foo\:bar
~/foo:bar $ cd ..
~ $ cd "foo:bar"
~/foo:bar $ 
```

**Comment by Napokue** [comment]
> The suggested workaround is not feasible in my case, as I have files that I want to copy from my D drive. My own temporary solution is that I moved those files to my C drive.

I did not completely read upon the suggested workaround, but now I did and this workaround does actually work. The `pushd d:` and `popd` commands wrapped around the `kubectl cp` command solves my issue for now.

**Comment by brianpursley** [comment]
@Napokue see also that instead of pushd/popd, apparently you can craft a UNC path that is equivalent without having to use `:`.

https://github.com/kubernetes/kubernetes/issues/110120#issuecomment-1139144611

So I guess something like this might work too:
```
kubectl cp \\.\d\test SomePod:/etc/test
```

**Comment by eddiezane** [comment]
@Napokue we would accept a PR to add this to the help text of `kubectl cp` if you'd like to make one!

/close

**Comment by Napokue** [comment]
@eddiezane Could you help me out what the "help text" is and where it is located. I am not familiar with the codebase at the point, so would be appreciated! What solution do you want me to include? The one about the `pushd` command or the one to craft the UNC path, or both? Thanks!

**Comment by brianpursley** [comment]
I think Eddie is talking about adding an example to the help text, to help other Windows users.

You can make the change in [/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go](
https://github.com/kubernetes/kubernetes/blob/8fb423bfabe0d53934cc94c154c7da2dc3ce1332/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L42-L67).

That gets displayed when you use the `--help` flag and is also extracted to build the content for the [Kubectl Reference Docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp)

As for which one to include, I think at least the one with the UNC path.  I personally like that one the most because it doesn't require any other commands (like pushd/popd).

**Comment by Napokue** [comment]
I tried testing the provided solution with UNC paths in Windows, but I cannot get it to work on my machine. Before I can commit the changes to the documentation I first need to get it working, as I need to verify that it would be working solution. As far as I have read the Windows documentation this would not be possible without having a network drive.

**Comment by Napokue** [comment]
I have tested the following pathing formats that the `cp` command does correctly handle:"

```
\\127.0.0.1\d$\foo\bar\
\\localhost\d$\foo\bar\
\\.\unc\localhost\d$\foo\bar\
\\127.0.0.1\d$\foo\bar\
```

All of these pathings are Windows specific as far as I have read. How do we want to include this in the documentation? Is there a convention for specifying OS specific documentation?

**Comment by Napokue** [comment]
@brianpursley sorry for the ping, but would you like to answer my question about my comment above? I would like to contribute but I am not sure how I would specify abovementioned text in the docs, thanks!

**Comment by brianpursley** [comment]
> I have tested the following pathing formats that the `cp` command does correctly handle:
> 
> ```
> \\127.0.0.1\d$\foo\bar\
> \\localhost\d$\foo\bar\
> \\.\unc\localhost\d$\foo\bar\
> \\127.0.0.1\d$\foo\bar\
> ```
> 
> All of these pathings are Windows specific as far as I have read. How do we want to include this in the documentation? Is there a convention for specifying OS specific documentation?

I'm not really a Windows user, so I don't know if there is a better way. This definitely feels like a big time workaround, and not optimal. It would be good if `kubectl cp` just supported paths that have `:` then it would be a non-issue.

Of the examples you provided, I think `\\localhost\d$\foo\bar\` is the least ugly.

We don't have a good way to handle platform-specific help text, and in general we try to avoid needing it.  There are a couple of commands that mention Windows in their help text `kubectl edit` and `kubectl completion`, but that is it.

Perhaps the simplest way to help people out would be to add an example, and in the comment line before the example, say `# On Windows systems, when specifying an absolute path, you must use a UNC path instead, to avoid a colon`, or something along those lines.
