### ISSUE TITLE
Display Service Account when describing Pod

### ISSUE THREAD

**Issue by aufarg** [kubernetes/kubectl#1226]
**What would you like to be added**:

A row for Service Account assigned to the Pod

**Why is this needed**:

Knowing which Service Account tied to the Pod can be useful when debugging apps running in a Pod. The information can be found easily from `kubectl get`, but it requires you to look through the content via machine format or use `jsonpath` output. The latter doesn't quite work to provide an at-a-glance look of the Pod state.

**Comment by jaehnri** [comment]
Hi!

@aufarg, please, let me know if you can't work on this issue right now. I would like to tackle it if it's the case. 

Thanks!

**Comment by aufarg** [comment]
@jaehnri Yes, sorry it took me quite a bit of time to read the contributing guidelines
