### ISSUE TITLE
kubectl exec -it <pod> bash hangs after you type exit

### ISSUE THREAD

**Issue by farazoman** [kubernetes/kubectl#1228]
**What happened**:
If you run the following
```
kubectl exec -it <pod> bash
# exit
```

Conditionally it will hang instead of returning control to the user in the shell. This is due to various changes to how go-dockerclient handles attach and exec. This happens after running `eksctl create cluster -f - --timeout 60m` through ansible, all the pods that are created will hang when `exit` is ran from an interactive shell, and when running ctrl+c it still won't exit the process. 

When restarting any pod, and following the steps above, we can see that the issue is no longer reproducible and exit works fine.

Note: additionally when running non-interactive commands, when the command finishes, it will hang as well and never exit that process until ctrl+c is ran.

**What you expected to happen**:
exit should work normally and exit the interactive shell

**How to reproduce it (as minimally and precisely as possible)**:

unfortunately, we are not sure how to reproduce it. As it doesn't happen 100% of the time

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`:
``` 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by brianpursley** [comment]
I'm trying to reproduce this problem, but it seems to exit fine when I do this:

```
~ $ kubectl run test --image=bash -- sleep 99999
pod/test created
~ $ kubectl exec -it test -- bash
bash-5.1# exit
exit
~ $ 
```

Does that work for you, or does it hang?

Am I doing something different than what you are?

**Comment by mpuckett159** [comment]
/triage needs-information

I'm unsure if this is useful information to have because you noted that the issue goes away after a pod restart but do you know if there are images that this happens most frequently on, or is it just an issue across all images? I also see that you're using eks and wonder if there may be something on the AWS side that could possibly be causing this. Have you reached out to AWS support for any potential issues on their side?

**Comment by eddiezane** [comment]
Maybe the version of bash is the image using?

Ref https://github.com/kubernetes/kubectl/issues/1175#issuecomment-1033312860.

Please reopen if you can reliably reproduce.

/close
