### ISSUE TITLE
kubectl edit fails with 'error: there was a problem with the editor "vi"' when you search for something that is not in the file

### ISSUE THREAD

**Issue by felipeek** [kubernetes/kubectl#1232]
**What happened**:

The bug is very simple. If you use `kubectl edit` to edit a resource and your editor is `vi/vim`, then if you try to search for something in the file, and your search fails because nothing was found in the file, then whenever you save your changes, vim will error out with:

> error: there was a problem with the editor "vi"

It doesn't matter what you do before or after the search, this error will always occur. In fact, even if you don't do anything with the file, just search and quit (:q), the error will already appear.

The search I am mentioning is done via `/<text>` in vim.

Also, if you search for something that actually exists, the error does not occur.

**What you expected to happen**:

kubectl edit should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run `kubectl edit <any resource>` making sure that your editor is vi/vim.
2. Type `/randomTextThatDoNotExistInTheFile`, which will search for a word that does not exist.
3. Type `:wq` to leave vim

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-02-16T11:18:16Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```
- Cloud provider or hardware configuration:
I think this happens with all cloud providers, but this was done in AWS.
- OS (e.g: `cat /etc/os-release`):
MAC OS X Monterey 12.4

Also,
```
vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 19 2022 21:41:43)
```

**Comment by eddiezane** [comment]
/triage support
/close

Let us know if that doesn't help.

**Comment by VamsiBal89** [comment]
> I'm not seeing this on Ubuntu, but since you are using a mac, I wonder if you are running into [this problem posted on StackOverflow](https://stackoverflow.com/a/69735583/5074828).
> 
> The default editor is `vi`, and although this is symlinked to vim, it appears that on a mac there is some conditional logic based on how it was invoked that changes some behavior. See the StackOverflow answer I linked above for more info about this.
> 
> What if you change the editor to be `vim`, like this?
> 
> ```
> KUBE_EDITOR=vim kubectl edit cm nginx-config
> ```
> 
> Or, alternatively...
> 
> ```
> EDITOR=vim kubectl edit cm nginx-config
> ```
> 
> Does that change anything for you?

Thanks for the instructions post adding the command with EDITOR = vim, I was able to edit my deployment files. It is a bit challenging to use Linux in arm, as there is less support for third party software's.

**Comment by arunkush5** [comment]
@brianpursley Thanks for sharing. I was looking for a solution like this. I had previously tried exporting the values to KUBE_EDITOR and EDITOR, but didn’t get the expected results. However, I’ve now managed to set it up by adding it to my ~/.bashrc, so I no longer need to type it every time.

```shell
echo 'export kubedit="KUBE_EDITOR=vim kubectl edit"' >> ~/.bashrc
```
```shell
source ~/.bashrc
```
then easy to use
```shell 
kubedit <resource> <resource_name>
```
