### ISSUE TITLE
kebectl error: unknown command "token admin-user"

### ISSUE THREAD

**Issue by hueifeng** [kubernetes/kubectl#1233]
**What happened**:

When I execute the fetch token, it doesn't seem to work properly

![image](https://user-images.githubusercontent.com/34702552/175524798-408808cc-738b-47cb-98d3-fc6fb18f9509.png)

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
X:\Users\HueiFeng>kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
```
- OS (e.g: `cat /etc/os-release`):

Microsoft Windows [version 10.0.19044.1766]

**Comment by ardaguclu** [comment]
Are you sure that `create token` command is in v1.22.5. I'd upgrade my kubectl and try with that.

/help

**Comment by hueifeng** [comment]
> Are you sure that `create token` command is in v1.22.5. I'd upgrade my kubectl and try with that.

@ardaguclu Is this.

![image](https://user-images.githubusercontent.com/34702552/175532579-8c74379e-c4b0-4806-8e8a-c97086f551c3.png)

**Comment by ardaguclu** [comment]
@hueifeng your kubectl is old.

**Comment by hueifeng** [comment]
Resolved, close this issue
