### ISSUE TITLE
[feature request] add option to show diff before `kubectl apply`

### ISSUE THREAD

**Issue by tigerinus** [kubernetes/kubectl#1234]
**What would you like to be added**:

```bash
$ kubectl apply -f some.yaml --show-diff
(shows diff first and only proceed if user enters `Y`)
```

**Why is this needed**:

Having to manage multiple contexts in the same CLI is prone to error. I often applied some yaml to the wrong context. I have enabled some visual (tmux and vscode) to indicate the current context, but this can still happen when careless.

As a better practice, I often do `kubectl diff` first before `kubectl apply`, only when I remember.

It'd be nice to make `diff` part of `apply` which helps a lot.

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by eddiezane** [comment]
The theory around this is that when using `kubectl apply` the diff should ideally be a `git diff`. We discussed this at our recent [KubeCon EU update session](https://youtu.be/eOxy1PS5TyQ?t=778).

I understand what you're asking for in the form of something like `terraform apply/plan`. This would be a good candidate for a plugin implementation.

/close

**Comment by tigerinus** [comment]
@eddiezane I see this issue is closed as completed...what exactly is the command for me to use as a general user?

**Comment by ardaguclu** [comment]
@tigerinus this request might not be applicable to `kubectl apply` and as @eddiezane said it is a good candidate for plugin.

I created this simple plugin https://github.com/ardaguclu/kubectl-dapply for that reason and that might solve your problem.

**Comment by brianpursley** [comment]
Coincidentally, I too just hacked together a similar plugin, although with a somewhat different approach.  It is very new, and I'm not trying to compete with @ardaguclu's plugin but will post it here in case you're interested in checking it out.

https://github.com/brianpursley/kubectl-confirm

It is not in the krew index yet, but I'm hoping to get it included soon.

**Comment by ardaguclu** [comment]
> Coincidentally, I too just hacked together a similar plugin, although with a somewhat different approach. It is very new, and I'm not trying to compete with @ardaguclu's plugin but will post it here in case you're interested in checking it out.
> 
> https://github.com/brianpursley/kubectl-confirm
> 
> It is not in the krew index yet, but I'm hoping to get it included soon.

Indeed it is an interesting coincidence :). My plugin is just a wrapper of `apply` and `diff` and I'm not planning to add it in krew index. @brianpursley but when I looked at your plugin, it looks like a complete and well written plugin and deserves to be in krew index.

**Comment by brianpursley** [comment]
Thanks, @ardaguclu.  I was working on this the past couple of days and when I saw your comment, I didn't want you to think I created this in response to what you created, which is why I decided to mention it now :sweat_smile: 

Your plugin's approach looks solid to me.  Maybe there is a use case for either of them, depending on what people are trying to do.
