### ISSUE TITLE
delete service account token

### ISSUE THREAD

**Issue by pycgo** [kubernetes/kubectl#1237]
**What would you like to be added**:
`kubectl delete token xxxx`

**Why is this needed**:
if i create a service account token for 1 year for service account to somebody, After a few months, what should I do if I want to withdraw my permission in advance

For reference, create the command as follows
`kubectl -n customspace create sa satest`
`kubectl -n customspace create token satest --duration=8760h`

**Comment by arno01** [comment]
Any updates on this? I'm also wondering...

```
kubectl create sa kubelet-api-test
kubectl create clusterrolebinding kubelet-api-test --clusterrole=system:kubelet-api-admin --serviceaccount=default:kubelet-api-test
TOKEN="$(kubectl create token kubelet-api-test)"

curl -sk -H "Authorization: Bearer $TOKEN" https://localhost:10250/metrics


kubectl delete clusterrolebinding kubelet-api-test
kubectl delete sa kubelet-api-test
```


After that `curl` still works :/

**Comment by gerardnico** [comment]
The doc has a [section about it](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#delete-token)
but I can't find the secret :(
