### ISSUE TITLE
[E2E_TEST] Move run_initializer_tests into runTests()

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubectl#124]
In `hack/make-rules/test-cmd-util.sh` e2e function [run_initializer_test](https://github.com/kubernetes/kubernetes/blob/5590c1fb94e09f9a2b7a09c9776e8d6535b18304/hack/make-rules/test-cmd-util.sh#L4968) was not being record by function `record_command`, it would be better if we can records its output/error messages in junit format

**Comment by mengqiy** [comment]
@shiywang It seems `run_initializer_tests` never runs anywhere.

**Comment by shiywang** [comment]
@mengqiy agree, @wackxu are you still working on this #55295?

**Comment by spiffxp** [comment]
I closed #55295 due to inactivity if someone else wants to try taking this on
