### ISSUE TITLE
kubectl create NetworkPolicy

### ISSUE THREAD

**Issue by jehutyy** [kubernetes/kubectl#1240]
**What would you like to be added**:

`kubectl create NetworkPolicy|netpol` would create said network policy.

**Why is this needed**:
This would allow to only use kubectl instead of kubectl plugin or home made templating

**Comment by eddiezane** [comment]
We'd like to see this addressed in a broader way to move away from the builtin create/generators to an OpenAPI driven generator implementation.

We'll gather feedback and thoughts at https://github.com/kubernetes/kubectl/issues/914

/close
