### ISSUE TITLE
Adopt JMESPath in kubectl 

### ISSUE THREAD

**Issue by aduzsardi** [kubernetes/kubectl#1241]
Would be possible to adopt JMESPath https://jmespath.org/specification.html in a future version of kubectl instead of the current jsonpath library ?
JMESPath seems to be the closest thing to a standard on json query , and we would probably not need **jq** or other third party tools for more advanced queries on json outputs.

**Comment by eddiezane** [comment]
Thank you for the suggestion! We are not currently interested in adding support for this. We can revisit if the broader Kubernetes community starts showing interest in JMESPath.

/close

**Comment by bbrummer** [comment]
> Thank you for the suggestion! We are not currently interested in adding support for this. We can revisit if the broader Kubernetes community starts showing interest in JMESPath.
> 
> /close

Ok.  I'm here, part of the community, showing interest.

JMESPath is far easier to use, far more powerful, and trivial to implement.  Not for nothing, it's also the standard adopted by both AWS and Azure for their CLI tools.  Perhaps they're onto something?

JSONPath offers a sub-optimal user experience.

At least as a work-around -o json can be piped through jp, but it's not ideal.  Really this gets to the larger issue that kubectl's mixing of concerns (querying and output format) into a single -o argument is sub-optimal.  The AWS CLI for example, clearly demarcates the two with --query and --output, allowing for --query "items[].podIP" --output text to get a clean list of pod IP addresses for example.

**Comment by dosmanak** [comment]
Jsonpath can not address list item by it's content hence the jsonpatch can patch for example different container in pod if the pod template changed. Jmespath or jq syntax is more powerfull.
