### ISSUE TITLE
An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts 

### ISSUE THREAD

**Issue by aliridha1510** [kubernetes/kubectl#1243]
Hello, i'm having this error when try get pods or any resource in my k8s cluster with kubectl.

**What happened**:

$ kubectl get pods

An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.

An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.

An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.

An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.

An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Windows 64
- kubectl version
An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255
- aws -version
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
- IAM user:([AdministratorAccess])
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

I hope help, thanks.

**Comment by brianpursley** [comment]
This sounds like an AWS-specific problem.

Maybe try creating an IAM user and authenticate using that, instead of using your AWS root account.

/kind support
