### ISSUE TITLE
Enhancement: Add a flag to present additional annotation columns to `kubectl get`

### ISSUE THREAD

**Issue by aslafy-z** [kubernetes/kubectl#1245]
**What would you like to be added**:

There's an (extremely helpful) option to add a column based on a particular label to the output of `kubectl get`:

```
$ kubectl help get | grep -- '-L'
  -L, --label-columns=[]: Accepts a comma separated list of labels that are going to be presented as columns. Names are case-sensitive. You can also use multiple flag options like -L label1 -L label2...
```

It'd be great if there were a similar option for annotations (`-A` / `--annotation-columns` for eg.)

**Why is this needed**:

This helps adding custom rows to add visibility over custom configurations as annotations for example.

**Additional informations**:

This issues was sort of copied from the closed https://github.com/kubernetes/kubernetes/issues/64529
This may be added in addition to that feature https://github.com/kubernetes/kubernetes/issues/98368

**Comment by eddiezane** [comment]
We don't want to add a specific flag for this but someone is going to look into reviving https://github.com/kubernetes/kubernetes/pull/102819.

/close
