### ISSUE TITLE
kubectl completion takes 5s if default context is unreachable

### ISSUE THREAD

**Issue by jsoref** [kubernetes/kubectl#1247]
**What happened**:

Each time I open a shell on macOS 12.4, it takes at least 5s (just for kubectl completion)

**What you expected to happen**:

New terminals should open quickly

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a GKE kubernetes
2. Add a firewall rule that blocks access to the control plane from the internet (or at least where the user will be running `kubectl completion ...`)
3. Run `time kubectl completion bash` (or some other shell, the precise shell doesn't matter)

Here, I have a default context pointing to a GKE instance with a firewall that prevents me from accessing it:
```
time kubectl completion bash > /dev/null
I0724 10:21:38.912741   90049 versioner.go:56] Remote kubernetes server unreachable
kubectl completion bash > /dev/null  0.45s user 0.27s system 14% cpu 5.128 total
```

For reference, if I set the default context pointing to a localhost (rancher) that is running but isn't running Kubernetes, it's fast:
```
time kubectl completion bash > /dev/null
I0724 10:20:30.971567   90042 versioner.go:58] Get https://127.0.0.1:6443/version?timeout=5s: dial tcp 127.0.0.1:6443: connect: connection refused
kubectl completion bash > /dev/null  0.08s user 0.06s system 60% cpu 0.242 total
```

**Anything else we need to know?**:

It's ok for commands beneath `kubectl x` to talk to the current context to get extra bits as part of dynamic completion, but it isn't ok to wait a full 5s as part of `kubectl completion bash` or similar.

Note that the times are equivalent for:

```
% time kubectl completion powershell > /dev/null
I0724 10:23:33.190086   90158 versioner.go:56] Remote kubernetes server unreachable
kubectl completion powershell > /dev/null  0.44s user 0.27s system 13% cpu 5.230 total
% time kubectl completion zsh > /dev/null
I0724 10:23:58.093916   90257 versioner.go:56] Remote kubernetes server unreachable
W0724 10:23:58.095636   90257 transport.go:243] Unable to cancel request for *exec.roundTripper
kubectl completion zsh > /dev/null  0.45s user 0.28s system 13% cpu 5.224 total
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```
% time kubectl version
I0724 10:25:22.618328   90555 versioner.go:56] Remote kubernetes server unreachable
W0724 10:25:22.619033   90555 transport.go:243] Unable to cancel request for *exec.roundTripper
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Unable to connect to the server: dial tcp ...:443: i/o timeout
kubectl version  0.79s user 0.46s system 3% cpu 35.807 total
```
- Cloud provider or hardware configuration: GKE (I suppose?) + Firewall blocking access from my client IP
- OS (e.g: `cat /etc/os-release`): 12.4 (21F79)

**Comment by eddiezane** [comment]
See my response in https://github.com/kubernetes/kubectl/issues/1248#issuecomment-1218291893 for the "why".

But I think this one may be something we can fix. My guess is that `kubectl completion` is triggering discovery which we should skip for this command.

/triage accepted
/priority backlog

**Comment by ardaguclu** [comment]
The point that I don't understand in this case;

`kubectl completion` command does not send any request to apiserver and even does not use discovery https://github.com/kubernetes/kubernetes/blob/67e692d521a5904aaaea446fd1642d2696cab61f/staging/src/k8s.io/kubectl/pkg/cmd/completion/completion.go#L147

@jsoref  What is the output of; `kubectl completion bash --v=99`?

**Comment by brianpursley** [comment]
I wonder if this has something to do with the GKE auth plugin.

@jsoref what happens if you run your completion command, specifying a context that doesn't exist, like this?
```
time kubectl completion bash --context=foo
```

It should not make a difference since it is not supposed to communicate with the server, but I am curious what would happen in your case.

Also, this is strange:
```
I0724 10:21:38.912741   90049 versioner.go:56] Remote kubernetes server unreachable
```

I can't find any file called versioner.go.  I wonder if that is coming from the GKE auth plugin?

**Comment by jsoref** [comment]
I'm thinking it is indeed a problem w/ the GKE auth plugin (which is being removed).

Here's a hit for it:
https://github.com/flavio/kuberlr/blob/a68d3cba285076ac6febb24037dc33ba693fa689/internal/finder/versioner.go#L56

**Comment by jsoref** [comment]
Ok, sorry, so, this isn't a problem in `kubectl`, it's a problem w/ https://github.com/flavio/kuberlr...

**Comment by brianpursley** [comment]
Still, I am curious why kubectl feels like authentication needs to occur in order for completions to be generated 🤔
