### ISSUE TITLE
`kubectl version` takes 35s if context is unreachable

### ISSUE THREAD

**Issue by jsoref** [kubernetes/kubectl#1248]
**What happened**:

`kubectl version` takes 35s when the server is inaccessible due to a firewall rule

**What you expected to happen**:

A single request that times out after 5s should be more than enough. Most commands do this. I can't think of any reason to make 7 serialized requests.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a GKE kubernetes
2. Add a firewall rule that blocks access to the control plane from the internet (or at least where the user will be running `kubectl version`)
3. Run `time kubectl version`

Here, I have a default context pointing to a GKE instance with a firewall that prevents me from accessing it:
```
I0724 10:25:22.618328   90555 versioner.go:56] Remote kubernetes server unreachable
W0724 10:25:22.619033   90555 transport.go:243] Unable to cancel request for *exec.roundTripper
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Unable to connect to the server: dial tcp ...:443: i/o timeout
kubectl version  0.79s user 0.46s system 3% cpu 35.807 total
```

For reference, if I set the default context pointing to a localhost (rancher) that is running but isn't running Kubernetes, it's fast:
```
I0724 10:32:57.227273   90806 versioner.go:58] Get https://127.0.0.1:6443/version?timeout=5s: dial tcp 127.0.0.1:6443: connect: connection refused
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
kubectl version  0.09s user 0.04s system 94% cpu 0.130 total
```

**Anything else we need to know?**:

If a user asks for the version of the server, it's ok to make them wait 5s in order to tell them that the server isn't reachable.
It'd be better if after 1s there was a warning that the server hasn't been reached yet and note that it's possible there's a firewall interfering with access.

It isn't ok to try 7 times w/o telling the user that's what's going on.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```
% time kubectl version
I0724 10:25:22.618328   90555 versioner.go:56] Remote kubernetes server unreachable
W0724 10:25:22.619033   90555 transport.go:243] Unable to cancel request for *exec.roundTripper
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Unable to connect to the server: dial tcp ...:443: i/o timeout
kubectl version  0.79s user 0.46s system 3% cpu 35.807 total
```
- Cloud provider or hardware configuration: GKE (I suppose?) + Firewall blocking access from my client IP
- OS (e.g: `cat /etc/os-release`): 12.4 (21F79)

**Comment by eddiezane** [comment]
> It isn't ok to try 7 times w/o telling the user that's what's going on.

Can you please share a bit more about where you are seeing 7 requests being made? Is this an assumption of the 5 seconds you are expecting and the 35 seconds you are seeing?

There should only be one request being made. What I think you are seeing is a difference between a connection refusal and a dial timeout. You can see this from the output you posted.

```
Unable to connect to the server: dial tcp ...:443: i/o timeout
```
```
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```

When you have the firewall rule in place your OS is dropping the packets at the kernel level so no connection is established. This drop is not reported to the program. This is where the dial timeout fails out of the request. You will see this behavior with any program and a firewall rule (the timeout being reached).

The latter is instantaneous because it can actually make the connection and finds nothing is listening (kernel reports back connection refused).

Hopefully this makes sense.

/triage support
/close

**Comment by eddiezane** [comment]
Also it's worth calling out that there is a `kubectl version --client=true` flag to skip the server check.
