### ISSUE TITLE
Enhance `kubectl debug` to set security context 

### ISSUE THREAD

**Issue by thejasn** [kubernetes/kubectl#1252]
**What would you like to be added**:
Currently, `kubectl debug` doesn't not support configuring container `securityContext` although `EphemeralContainers` API does support it. Some of the fields in `securityContext` are frequently used during debugging such as `runAsUser`, `runAsGroup`, etc. Such fields could be configurable inline within `kubectl debug`.

**Why is this needed**:
Currently, the way to set `securityContext` is to utilize `kubectl replace --raw /api/v1/namespaces/default/pods/<pod-name>/ephemeralcontainers -f pod.json` where the `ephemeralContainers: []` has been updated in the `pod.json`.

**Comment by ardaguclu** [comment]
There is an ongoing process to add more debugging profiles in here https://github.com/kubernetes/kubernetes/pull/110526. But as a new `securityContext` flag if you mean, better to ask @verb @knight42

**Comment by thejasn** [comment]
> There is an ongoing process to add more debugging profiles in here [kubernetes/kubernetes#110526](https://github.com/kubernetes/kubernetes/pull/110526). But as a new `securityContext` flag if you mean, better to ask @verb @knight42

Thanks @ardaguclu, 
Debugging profiles would surely help, but we would still have a restriction on what fields under `securityContext` can be configured. (especially fields like `runAsUser`, `runAsGroup`). 

Although I do understand that having a bunch of flags with `kubectl debug` to configure all fields is not really a good user experience, we could have solution that combines debugging profiles (populates most of the fields in `securityContext`) and options (flags) for customizing some of them. (`capabiities`, `runAsUser`, `runAsGroup`, etc).

**Comment by verb** [comment]
I agree that debugging profiles covers some but not all of this feature request, and you're right that the challenge here is balancing flags vs features. One way I've considered improving this is to allow the user to add additional debugging profiles, but this would be a follow-up KEP if it's even possible.

@thejasn this is the first request I've seen for configuring `runAsUser` and `runAsGroup`. So far I guess everyone has been content to debug as root. Could you explain a bit more your use case? Would a custom container image that configures `USER` be a work around until there's support in `kubectl debug`?

**Comment by thejasn** [comment]
> One way I've considered improving this is to allow the user to add additional debugging profiles, but this would be a follow-up KEP if it's even possible.

Are you picturing this to be something like providing a file with the required security context as a JSON/YAML? 

> @thejasn this is the first request I've seen for configuring runAsUser and runAsGroup. So far I guess everyone has been content to debug as root. Could you explain a bit more your use case?

So I was using ephemeral containers to run a `delve` debugging server that attaches to the primary container in order to start a debugging session on a running container. I hit some snags with the following errors, 
```bash
2022-07-26T13:03:46Z info layer=debugger attaching to pid 1
Could not attach to pid 1: current user does not own the process
```
. This along with the podsecurity policy set to `restricted` kind of led me down the path of needing to configure security context. Although in the end ended up running as root. So I don't entirely have a concrete use case either. 

> Would a custom container image that configures USER be a work around until there's support in kubectl debug?

I was using this as a workaround as well, but since I was testing on Openshift and it uses the annotation (`openshift.io/sa.scc.uid-range`) to generate defaults when `securityContext.runAsUser` isn't set. This leads to the user id for the primary container being generated at random. Since this is default behavior of Openshift, most workload don't manually specify `securityContext.runAsUser`.

**Comment by verb** [comment]
> Are you picturing this to be something like providing a file with the required security context as a JSON/YAML?

Yes, something like this, but it's just an idea at this point and would need work to develop.

> So I was using ephemeral containers to run a `delve` debugging server that attaches to the primary container in order to start a debugging session on a running container. I hit some snags with the following errors,
> 
> ```shell
> 2022-07-26T13:03:46Z info layer=debugger attaching to pid 1
> Could not attach to pid 1: current user does not own the process
> ```

I think for now the supported solution will be to run a container as root with debugging profile that sets the required capabilities.

> I was using this as a workaround as well, but since I was testing on Openshift and it uses the annotation (`openshift.io/sa.scc.uid-range`) to generate defaults when `securityContext.runAsUser` isn't set. This leads to the user id for the primary container being generated at random. Since this is default behavior of Openshift, most workload don't manually specify `securityContext.runAsUser`.

That's a cool feature of openshift. Maybe it could be updated to better support ephemeral containers. If it's implemented by something like a mutating admission controller it could mutate the `securityContext` of the ephemeral container to set the same `runAsUser` that it set for the primary container.

**Comment by thejasn** [comment]
> Yes, something like this, but it's just an idea at this point and would need work to develop.

I'd be open to creating a rough draft PR or an enhancement. Do you think now is an appropriate time for something like this since there is still active work going being done on debugging profiles?

> I think for now the supported solution will be to run a container as root with debugging profile that sets the required capabilities.

Do you think for now we could document how we can work with ephemeral containers using `kubectl replace --raw` in order to update fields that are aren't exposed with `kubectl debug`? If you agree, I can probably raise a PR.

**Comment by eddiezane** [comment]
Let's consolidate this with https://github.com/kubernetes/kubectl/issues/1258

/close
