### ISSUE TITLE
Beginning of help text is cut off for apply's --filename flag

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubectl#1253]
**What happened**:
```
kubectl apply help
```

Output for the `--filename` flag looks like the beginning is cut off:
```
    -f, --filename=[]:
	that contains the configuration to apply
```

**What you expected to happen**:
The description of this flag should be a proper sentence, like other flag descriptions.

**How to reproduce it (as minimally and precisely as possible)**:
See "what happened" above

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `Client Version: v1.24.3`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.4 LTS`

**Comment by kaustubhbabar5** [comment]
I would like to pick this up.

**Comment by peizhouyu** [comment]
I tried to reproduce the problem with kubectl compiled against the latest master branch, but the result is that f, --filename=[]: and the following are not "cut off", is there any more explanation about this problem. Thanks. @brianpursley 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/13448072/181225971-73ad48f0-de7b-4582-948b-f199073b1e54.png">

**Comment by brianpursley** [comment]
I don't know, I just felt like `that contains the configuration to apply` seems like it should have something before "that", like maybe it had something previously and it was accidentally dropped.

My suggestion would be something like: `The files that contain the configurations to apply.`

But am open to other ideas.

**Comment by peizhouyu** [comment]
> I don't know, I just felt like `that contains the configuration to apply` seems like it should have something before "that", like maybe it had something previously and it was accidentally dropped.
> 
> My suggestion would be something like: `The files that contain the configurations to apply.`
> 
> But am open to other ideas.

It sounds good, thanks.

**Comment by brianpursley** [comment]
/close 

Fixed by https://github.com/kubernetes/kubernetes/pull/111486
