### ISSUE TITLE
Display "error: proto: cannot parse invalid wire-format data" when apply yaml

### ISSUE THREAD

**Issue by sontt-1215** [kubernetes/kubectl#1260]
**What would you like to be added**:
When i run kubectl apply..., response as above
**Why is this needed**:
Has anyone had this problem yet? Please help me
![image](https://user-images.githubusercontent.com/49391617/182567070-d03094a3-be0d-4882-a82d-4c4400cfdf16.png)

**Comment by sontt-1215** [comment]
![image](https://user-images.githubusercontent.com/49391617/182649043-02711216-a549-4648-8cdd-3171b9047332.png)
this is my config yaml

**Comment by ardaguclu** [comment]
@sontt-1215, this looks like grpc problem. Could you please assure that your apiserver is running properly?. Can you run any `kubectl` commands?. As a general can you  access your cluster?

**Comment by eddiezane** [comment]
Please provide more info including the versions you are using.

/close

**Comment by sontt-1215** [comment]
thanks for reply, i newbie k8s.
i solved it after installing minikube.
