### ISSUE TITLE
kubectl describe ingress doesn't show the ingressClassName

### ISSUE THREAD

**Issue by broomfn** [kubernetes/kubectl#1261]
**What happened**:

"kubectl describe ingress" doesn't show the ingressClassName

**What you expected to happen**:

ingressClassName to be shown in the describe output

**How to reproduce it (as minimally and precisely as possible)**:

"kubectl describe ingress <NAME>" 

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.24.1
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): Windows 11

**Comment by ardaguclu** [comment]
@broomfn  According to here https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L2667, it shows. In which version you tested?

**Comment by broomfn** [comment]
@ardaguclu , thanks for the assist, I'm currently on Kubernetes version 1.22.6

**Comment by ardaguclu** [comment]
@broomfn with these versions it seems not possible to be empty. Do you mean it shows `<none>`?. Could you please provide the steps to reproduce the issue?. Thanks.

**Comment by broomfn** [comment]
It doesn't display <none> it just doesn't display anything:

Name:             ionapp-ingress
Labels:           app.kubernetes.io/managed-by=Helm
Namespace:        default
Address:          10.100.102.11
Ingress Class:    nginx
Default backend:  <default>
TLS:
  ionapp-tls-secret terminates www.xxxxxxxxx.com
Rules:
  Host                         Path  Backends
  ----                         ----  --------
  www.xxxxxxx.com
                               /   ionapp-service:80 (10.102.0.171:80)
Annotations:                   cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
                               meta.helm.sh/release-name: ion-app
                               meta.helm.sh/release-namespace: default
Events:
  Type    Reason  Age                    From                      Message
  ----    ------  ----                   ----                      -------
  Normal  Sync    4m6s (x2241 over 18h)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    4m6s (x2241 over 18h)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    65s (x2460 over 20h)   nginx-ingress-controller  Scheduled for sync
  Normal  Sync    5s (x2462 over 20h)    nginx-ingress-controller  Scheduled for sync

**Comment by ardaguclu** [comment]
@broomfn because `ingressClassName` is shown in `Ingress Class:` field(ref: https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L2723).

 It is shown in your above example in;

```
Ingress Class:    nginx
```

**Comment by broomfn** [comment]
@ardaguclu Thanks!!!!!!! Ignore me, I'm a tool, sorry :-(

**Comment by broomfn** [comment]
Many thanks for the assistance

**Comment by ardaguclu** [comment]
No worries!
