### ISSUE TITLE
Kubectl does not give cm using get all with -l option

### ISSUE THREAD

**Issue by shyamsubbu** [kubernetes/kubectl#1264]
**What happened**:
Kubectl does not cm under get all
**What you expected to happen**:
cm to be listed

**How to reproduce it (as minimally and precisely as possible)**:

```
Label a configmap and statefulset(sts)

kubectl  -n default get all -A -l nso-version=5.7.5.1

NAMESPACE   NAME                     READY   STATUS    RESTARTS   AGE
default     pod/ts43demo-cnc-cfp-0   0/1     Running   0          8m11s

NAMESPACE   NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP                                                                    PORT(S)          AGE
default     service/ts43demo-cnc-cfp   LoadBalancer   10.129.119.926   k8s-default-ts43demo-haha-a355f455f60591.elb.us-east-1.amazonaws.com   8090:32460/TCP   8m53s

NAMESPACE   NAME                                READY   AGE
default     statefulset.apps/ts43demo-cnc-cfp   0/1     8m53s

NO Configmap to be found above
---------------------------------------------------------------------------------
But if you query cm separately, it is found.

kubectl -n default get cm  -l nso-version=5.7.5.1
NAME                        DATA   AGE
ts43demo-cnc-cfp-nso-conf   1      8m6s
```
**Anything else we need to know?**:

**Environment**:
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- AWS CP
- cat /etc/*-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

**Comment by eddiezane** [comment]
ConfigMaps are not included in the `all` group so this is working as expected.

/close
