### ISSUE TITLE
Exclude metadata.generation field from the output of kubectl diff command

### ISSUE THREAD

**Issue by superbrothers** [kubernetes/kubectl#1267]
**What would you like to be added**:

I want to exclude `metadata.generation` field from the output of `kubectl diff` command.

**Why is this needed**:

By https://github.com/kubernetes/kubernetes/pull/111319, the output of `kubectl diff` command no longer includes managed-fields by default, making diffs much easier to read. However, currently, when a diff exists, `metadata.generation` field is incremented and therefore output as a diff. This is redundant.

```
$ kubectl version --client
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7

$ kubectl diff -f nginx.yaml
diff -u -N /tmp/LIVE-2978127705/apps.v1.Deployment.default.nginx /tmp/MERGED-2861968783/apps.v1.Deployment.default.nginx
--- /tmp/LIVE-2978127705/apps.v1.Deployment.default.nginx       2022-08-28 10:50:39.099818887 +0900
+++ /tmp/MERGED-2861968783/apps.v1.Deployment.default.nginx     2022-08-28 10:50:39.099818887 +0900
@@ -4,7 +4,7 @@
   annotations:
     deployment.kubernetes.io/revision: "1"
   creationTimestamp: "2022-08-28T01:36:11Z"
-  generation: 2
+  generation: 3
   labels:
     app: nginx
   name: nginx
@@ -30,7 +30,7 @@
         app: nginx
     spec:
       containers:
-      - image: nginx
+      - image: nginxinc/nginx-unprivileged
         imagePullPolicy: Always
         name: nginx-unprivileged
         resources: {}
```

**Comment by brianpursley** [comment]
We talked about this in the CLI bug scrub meeting today, and the consensus was that kubectl should not exclude any fields beyond managedFields.  While generation may not be of interest to some users, it might be to others.

The recommended approach is to store your manifests in source control and diff against that (ie. git diff) to compare one version to another version.

`kubectl diff`serves a slightly different purposes, to give you a preview of what the change will be, if applied,  The subtle difference is that it is a comparison against what is running in the server, not what was previously applied.

As a workaround, you might be able to use the [`KUBECTL_EXTERNAL_DIFF`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#diff) environment variable to override the diff command that is used to ignore specific fields (https://stackoverflow.com/questions/4434346/how-to-ignore-some-differences-in-diff-command).

**Comment by superbrothers** [comment]
I agree with you, but it seems to me that everyone would be happy if we provided options like managedFields. Like `-show-generation'.

**Comment by superbrothers** [comment]
> As a workaround, you might be able to use the KUBECTL_EXTERNAL_DIFF environment variable to override the diff command that is used to ignore specific fields.

If that is not acceptable, I would consider using a workaround.

**Comment by eddiezane** [comment]
Agree with Brian.

/close

**Comment by mac2000** [comment]
For anyone landed here in attempt to find an workaround demo and/or explanation of how it suppose to work

here is how it may look like

**/Users/mac/Downloads/kubediff/diff.sh**

```bash
#!/usr/bin/env bash

tmp1=$(mktemp -d)
tmp2=$(mktemp -d)

for f in $1/*
do
  cat $f | grep -v generation: > $tmp1/$(basename $f)
done

for f in $2/*
do
  cat $f | grep -v generation: > $tmp2/$(basename $f)
done

# diff -u -N $1 $2 # original
diff -u -N $tmp1 $tmp2
```

> Note: this is just a demo, but technically it should be enough to do anything with files before they are passed to diff command

Under the hood, kubectl calls diff like so:

```bash
diff -u -N /tmp/live/ /tmp/merged/
```

where arguments are folders with yaml manifests

our script just iterates over both directories, modifies manifests and stores them in new place

right after we are using the same diff command but passing folders with modified manifests - profit

usage example:

```bash
KUBECTL_EXTERNAL_DIFF=/Users/mac/Downloads/kubediff/diff.sh kubectl diff -f /Users/mac/github.com/mac2000/kube/dev/mactemp2/
```

other ideas: 

- `yq` may be used to make some complex changes
- we may substitute /tmp/long/path/to/live/manifests so diff is smaller
- we may exclude whole files if we want by just deleting them
- ...

**Comment by debovema** [comment]
Based on previous messages, here's an updated version that I use:
```shell
#!/bin/sh

for f in $(find $1 $2 -type f)
do
  sed -i '/    app.kubernetes.io\/instance/d' $f
  sed -i '/    argocd.argoproj.io\/tracking-id/d' $f
  sed -i '/    operators.coreos.com/d' $f
  sed -i '/  generation:/d' $f
  sed -i '/  labels:/d' $f
done

diff --color -u -N $1 $2
```

* `    argocd.argoproj.io/tracking-id` is the annotation used by ArgoCD when resource tracking is set as *annotation* or *annotation+label* (https://argo-cd.readthedocs.io/en/latest/user-guide/resource_tracking/)
* `    app.kubernetes.io/instance` is the annotation used by ArgoCD when resource tracking is set as *label* or *annotation+label* (https://argo-cd.readthedocs.io/en/latest/user-guide/resource_tracking/)
* `    operators.coreos.com` is the prefix of label added on `Subscription` resources of OLM operators
* `  generation:` is the field to ignore initially in this thread
* this list can certainly be improved
