### ISSUE TITLE
Empty patch when performing a rollout restart on a deployment

### ISSUE THREAD

**Issue by ido-vcita** [kubernetes/kubectl#1268]
From time when we are restarting a deploy using `kubectl rollout restart` we are getting a message saying that the deploy was restarted and then that the patch is empty.
Bellow is the shell out put:
```
kubectl get deployment -n automation -o 'jsonpath={.items[?(@.metadata.annotations.meta\.helm\.sh/release-name=="vcita-automation")].metadata.name}' | \
xargs kubectl rollout restart deploy -n automation

10:22:35  deployment.apps/vcita-automation restarted
10:22:35  deployment.apps/vcita-automation-resque restarted
10:22:35  deployment.apps/vcita-automation-resque-scheduler restarted
10:22:35  failed to create patch for vcita-automation: empty patch
10:22:35  failed to create patch for vcita-automation-resque: empty patch
10:22:35  failed to create patch for vcita-automation-resque-scheduler: empty patch
```

**What you expected to happen**:
I expect the deploy to restart and the command to exit successfully
**How to reproduce it (as minimally and precisely as possible)**:
Restart a deployment using the `kubectl rollout restart` command

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client: v1.19.0
Server: v1.21.14-eks-18ef993
- Cloud provider or hardware configuration:
AWS EKS
- OS 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by ardaguclu** [comment]
I could have reproduced the issue. `rollout restart` command relies on update of `kubectl.kubernetes.io/restartedAt` annotation with the time in [here ](https://github.com/kubernetes/kubernetes/blob/9f3384f02f472b0095fe3675139c08e7aaa7e711/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go#L41). This creates a patch difference and command does strategic patching for restart. But time precision is in second and if you do subsequent `rollout restart` within a second, it can not determine any patch diff(in programmatic cases, this is not unusual).

Instead using `time.RFC3339` format, I tried with `RFC3339Nano` and it worked without any problem and looks there is no side effect.  I think we can switch to Nano time format(by also changing https://github.com/kubernetes/dashboard/blob/a64a975388c5906142660e5e87f1e20121700581/src/app/backend/resource/deployment/rollout.go#L116) but from the point of side effects, we need approvers opinions.

**Comment by ido-vcita** [comment]
@ardaguclu Thank you for taking the time and looking at this.
Seems interesting let's see what the approver will have to say about it.
