### ISSUE TITLE
go v1.16.15 and v1.17.10 has high and medium severity Prisma vulnerabilities associated with kubectl version v1.22.6 and v1.23

### ISSUE THREAD

**Issue by joroddy** [kubernetes/kubectl#1269]
go v1.16.15 and v1.17.10 has high and medium severity Prisma vulnerability associated with kubectl versions v1.22.6 and v1.23. go version needs to be updated to the latest go version to remediate Prisma vulnerabilities. We're using kubectl v1.22.6. Please remediate. Thank you!

**Comment by eddiezane** [comment]
Thanks for reporting and sorry for the delay. This should be sorted now.

/close
