### ISSUE TITLE
Replace type "switch" statements with KindVisitor in "rollback"

### ISSUE THREAD

**Issue by mahdix** [kubernetes/kubectl#127]
This is a follow-up ticket from https://github.com/kubernetes/kubectl/issues/73

Quoting @janetkuo:

> Btw, based on the description, this issue is more general than just HistoryViewer? For example, rollback.go uses type switches too: https://github.com/kubernetes/kubernetes/blob/33f873dbbee58caffcff9e7b44f174a32ec1df92/pkg/kubectl/rollback.go#L59-L69

**Comment by mahdix** [comment]
I will work on this.

**Comment by apelisse** [comment]
Thanks for working on this @mahdix!
