### ISSUE TITLE
Dangerous behaviour to not fail on `-n <namespace> --all`

### ISSUE THREAD

**Issue by m0un10** [kubernetes/kubectl#1272]
**What happened**:

I accidentally ran `kubectl delete crd -n <namespace> --all`. It deleted all of my CRDs and broke my cluster beyond repair.
It warned that the CRD isn't namespaced but it didn't fail.

**What you expected to happen**:

I expect if `-n <namespace> --all` is set that it should fail indicating that it's a namespaced resource as opposed to simply warning. The warning is useless when the deletion has already happened to everything. Seems like a modern and more dangerous equivalent of `rm -rf $unsetvar/` but more preventable.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl delete crd -n <namespace> --all`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by brianpursley** [comment]
This seems like a similar failure mode as prune (https://github.com/kubernetes/kubernetes/issues/110905)

There are probably a few cases where this might happen:

1. The one @m0un10 mentioned in this issue: `kubectl delete crd -n something --all`
2. You're trying to delete a single cluster-scoped resource: `kubectl delete crd mycrd -n something`
3. You delete from a file(s) (`-f` or `-k`) and specify a namespace, but the file contains cluster-scoped resources: `kubectl delete -f mycrd.yaml -n something`

As @m0un10  said, it does print a warning saying `deleting cluster-scoped resources, not scoped to the provided namespace`, but continues to perform the deletion.
https://github.com/kubernetes/kubernetes/blob/b7e82ad2fd03b23b53ab94de66c5b3c30863724a/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete.go#L321

@KnVerey thoughts on this?  Should this be handled in a way similar to pruning cluster-scoped resources?

**Comment by KnVerey** [comment]
I agree with you on the conceptual similarities, but unlike pruning (which is an alpha flag), `kubectl delete` is a GA command. This has actually come up many times before, and the SIG has concluded that we cannot just change this, as it would be a breaking behaviour difference. For more context, see [this long thread](https://groups.google.com/g/kubernetes-sig-cli/c/MHk8jEGMAYo) and [this closed KEP](https://github.com/kubernetes/enhancements/pull/2777). This could be something we address through [kuberc](https://github.com/kubernetes/enhancements/pull/3392). 

Duplicate of https://github.com/kubernetes/kubectl/issues/1056 and many others linked from the mailing list thread.

cc @eddiezane
