### ISSUE TITLE
Add an option to generate a kubeconfig for a service account

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kubernetes/kubectl#1274]
**What would you like to be added**:
It would be nice to have an inbuilt ability for `kubectl` to generate a kubeconfig for a service account with one command something like:
```
kubectl config generate-context --serviceaccount someSA --namespace someNamespace --path=~/.kube/someConfig
```

**Why is this needed**:
It is often required when you provide non-admin rights for a user.
I know there are scripts, like the ones, described here: https://stackoverflow.com/questions/47770676/how-to-create-a-kubectl-config-file-for-serviceaccount
Also, there are at least one plugin with this feature (I have not tried it myself, though): https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin
It is possible to generate a kubeconfig for SA using Lens as well.

But what about the inbuilt feature? 
Creating a kubeconfig without using scripts or third-party tools is pretty painful. Also, those changing APIs in different `kubectl` versions -right now it is `client.authentication.k8s.io/v1beta1` for the latest `kubectl`.

**Comment by eddiezane** [comment]
This isn't something we would want to add. There is a process that kubectl walks through when deciding where to pull a config from and it differs from in/out of a cluster.

See https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides

/close
