### ISSUE TITLE
error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

### ISSUE THREAD

**Issue by albylamar** [kubernetes/kubectl#1278]
I'm creating a yaml fike with kubctl and I am getting error of [apiversion not set, kind not set] if you choose these errors turn validation off with --validate=off

I am using bitbucket-pipelines, all my yaml files has apiversion and kind with the exception of the bitbucket pipelines yaml
-->

is there a way to exclude to exclude kubectl apply -f  

these are the name of my yaml files
namespace.yaml
rbac.yaml
secret.yaml
pvc.yaml
service.yaml
ingress.yaml
app-deployment.yaml
bitbucket-pipelines.yaml

I am new to bitbucket pipelines

**Comment by ardaguclu** [comment]
That sounds like an issue needs to be asked in bitbucket-pipeline communication channels?

I'm closing this issue now. Feel free to open it if you assure that it is related to kubectl and that would be great if you can add more steps how we can reproduce the issue.

/close

**Comment by OneCricketeer** [comment]
> asked in bitbucket-pipeline communication channels

Why? It's not a kubernetes resource, so it shouldn't even be included in the `kubectl apply` file list

> a way to exclude

Just manually apply each file that is valid kubernetes resource
