### ISSUE TITLE
port-forward try to wrong target port

### ISSUE THREAD

**Issue by zzunny97** [kubernetes/kubectl#1281]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.22.14
- Cloud provider or hardware configuration: On-prem
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04

<img width="876" alt="스크린샷 2022-09-16 오후 4 28 23" src="https://user-images.githubusercontent.com/39353616/190582020-5968a8cb-ba6b-4dfa-b735-c6f2a7b01e00.png">

**Comment by ardaguclu** [comment]
@zzunny97 Thanks for the issue. Would you mind adding reproducement steps?, how that happened?, is it possible to try that in latest version?.

Because according to the issue description, port-forward command should be broken for all cases but we know that it is not :)
