### ISSUE TITLE
Allow events to be filtered by source

### ISSUE THREAD

**Issue by atzawada** [kubernetes/kubectl#1282]
**What would you like to be added**:

I would like to see the the option for being able to filter by component when retrieving events. I think this could be accomplished by adding `source.component` as a field selector for event objects. For example:
```
kubectl get events --field-selector source.component=my-component
```

**Why is this needed**:

For teams/organizations that maintain operators/controllers that spit out events, it would be nice to filter for events that come out of our custom components.

**Comment by ardaguclu** [comment]
Thanks for the issue @atzawada. `kubectl get events` supports `involvedObject` as field selector(eg. `--field-selector involvedObject.name=`). What is the reason not using that command?. Moreover, we have a new command `kubectl alpha events` which accepts `--for` and I'd recommend to have a look at(eg. `kubectl alpha events --for=`) with the source you  want to list events.

Besides that could you please elaborate what does `source.component` mean in kubernetes. For example does it refer to CRD?.

**Comment by ardaguclu** [comment]
This seems like a feature supported by `kubectl alpha events`.

/close

**Comment by tallaxes** [comment]
@atzawada, this is already supported, but the field selector used is just `source`, for historical reasons (https://github.com/kubernetes/kubernetes/issues/41743)
@ardaguclu, `source.component` is the name of the component that created the event, e.g. `kubelet`
