### ISSUE TITLE
kubectl rollout status doesn't wait/ensure deployment is finished

### ISSUE THREAD

**Issue by cawoodm** [kubernetes/kubectl#1284]
**What happened**:
During deployment of new apps we run `kubectl set image deployment/ourApp <tagName>` followed by `kubectl rollout status deployment/ourApp` to wait for the deployment to complete before we run tests.

Unfortunately the tests run on the old version of the app although we assume `kubectl rollout status` is supposed to wait until the rollout is complete.

**What you expected to happen**:
We expect that after `kubectl rollout status` concludes, only new versions of the pod are running.
This is definitely not the case.
We run functional tests on the deployment and can see that it is still the old versions of the pods running.
`kubectl exec -it deploy/ourApp -- npm run testf`

**How to reproduce it (as minimally and precisely as possible)**:
```
2022-09-20T09:02:54.7995327Z Updating existing deployment ourApp:1.6.0.354025...
2022-09-20T09:02:54.7997326Z # Applying New Image Tag to Deployment...
2022-09-20T09:02:54.8000652Z set image deployment/ourApp ourApp=repo.ourdomain.com/ourApp:1.6.0.354025
2022-09-20T09:02:55.0553961Z # deployment.apps/ourApp image updated
2022-09-20T09:02:55.0587266Z #  Waiting for rollout to complete
2022-09-20T09:02:55.0589084Z rollout status deployment/ourApp
2022-09-20T09:02:55.3098146Z Waiting for deployment "ourApp" rollout to finish: 1 old replicas are pending termination...
2022-09-20T09:02:56.7265203Z Waiting for deployment "ourApp" rollout to finish: 1 old replicas are pending termination...
2022-09-20T09:02:57.2686980Z deployment "ourApp" successfully rolled out
2022-09-20T09:02:57.2730971Z # Checking correct version was installed
2022-09-20T09:02:57.2733132Z get deployment ourApp -o=jsonpath='{$.spec.template.spec.containers[:1].image}'
2022-09-20T09:02:57.4797466Z # OK, ourApp:1.6.0.354025 installed... or not?
```
**Anything else we need to know?**:
We are always passing a namespace and a context to all commands: `-n foo--context=dev`.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `v1.23.6+k3s1`
- Cloud provider or hardware configuration: On-Prem Ubuntu 20.04.4
- OS (e.g: `cat /etc/os-release`): See Below

### kubectl version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
### /etc/os-releas
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by eddiezane** [comment]
Can you please provide a better reproduction example so we can take a look at this?

**Comment by cawoodm** [comment]
Hello again, I really don't know how to provide you with our environment so you can reproduce it.
Some issues can't be reproduced exactly and it's up to the developer to look at the logs and figure out from source code how it *could* happen.

What we are consistently seeing is that `kubectl rollout status` concludes BEFORE the new pods are up and running. Is this behaviour by design or a bug?

**Comment by emanuel-gjini** [comment]
Having the same issue as @cawoodm on the latest version shipped through k3s

**Comment by blueowlgreenfish** [comment]
Same issue.
`kubectl rollout status` says `deployment "deployment-name" successfully rolled` before my app is updated.
Currently, I can not rely on the status message so I need to wait usually 3 or more seconds to see my app actually updated.

**Comment by akk29** [comment]
Facing this issue
