### ISSUE TITLE
kubectl man page, please?

### ISSUE THREAD

**Issue by harridu** [kubernetes/kubectl#1291]
Would it be possible to provide an "old fashioned" flat man page for kubectl? Something providing the big picture, not just a small fragment shown by kubectl --help?

Working with kubectl I would prefer to stay in my usual work flow on the command line. Opening a browser GUI to search through a bazillion of web pages (made for a different version) is not part of it. kubectl is a command line tool. I am very happy with this. Reading the documentation on the command line is not possible. That is hardly reasonable.

**Comment by eddiezane** [comment]
Most package managers should ship the manpage along with the binary. If yours doesn't you can build and install it manually.

Check out how homebrew does it.

https://github.com/Homebrew/homebrew-core/blob/ea772d3bdb4a2881c283edf9c7902e90a4d0c9c8/Formula/kubernetes-cli.rb#L45-L48

/close
