### ISSUE TITLE
Support 'kubectl get' for owner objects or owned objects through ownerReferences

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes/kubectl#1292]
**What would you like to be added**:

kubectl support for a flag that allows you to see the objects that own a specific object or are owned by this object.

For example:

- See owned objects: `kubectl get deployment nginx --owned`. Shows the owned replicasets and pods.
- See owner objects: `kubectl get replicaset nginx-abcd --owners`. Shows the owner deployment.

**Why is this needed**:

- Ownership is important for understanding the ultimate effects of a custom resource.
- Need to see what objects will be affected if one object is edited or deleted.
- Need to see which objects may be stopping an object from being deleted, due to garbage collection rules.

We work with CRDs that have ownership hierarchies 3 levels deep. We are using a custom kubectl plugin to correlate these ownership trees (and other information) into a summary, like kubectl describe. It would be nice to see this kind of query generalized so that it works on any object.

**Complications**:

Owners are relatively easy to get through the ownerReference field on the current object.

Owned objects are hard to get because it could be any object of any type. This query would be expensive. Maybe it could be limited by type using a flag input. Not sure.

**Comment by jainpratik163** [comment]
this can also be achieved by kubectl plugin **tree**

**Comment by eddiezane** [comment]
> this can also be achieved by kubectl plugin **tree**

Have a look at https://github.com/ahmetb/kubectl-tree and https://github.com/kubernetes-sigs/kubectl-check-ownerreferences

/close
