### ISSUE TITLE
kubectl get all does not show configmaps

### ISSUE THREAD

**Issue by devzer01** [kubernetes/kubectl#1293]
**What happened**:

i typed kubectl get all and i expect to see config-maps, but they are not listed

**What you expected to happen**:

to see configmaps listed

**How to reproduce it (as minimally and precisely as possible)**:
create a configmap 
and then 
kubectl get all 

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate
:"2022-09-22T02:38:06Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDat
e:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

**Comment by newtondev** [comment]
Also check out the kubectl addon: https://github.com/corneliusweig/ketall

**Comment by sftim** [comment]
/remove-kind bug
/kind support

I think `kubectl` is working as designed, although this behavior can be confusing.
