### ISSUE TITLE
Kubectl on MacOS Montery 12.6 causing networking crash, requires restart

### ISSUE THREAD

**Issue by awbacker** [kubernetes/kubectl#1299]
When I execute `kubectl version` on my recently upgraded OSX 12.6 Macbook Pro (Intel), the network stack appears to crash.  This requires a restart.

This appears to be related to IPv6 in some way:

* Wifi DHCP provies 2 servers: `192.168.1.254` and `fe80::c6e5:32ff:...`
* Manually setting to `8.8.4.4` or another IPv4 _fixes the issue_

Perhaps `kubectl` is triggering some MacOS network stack bug?

**What happened**:

```
Unable to connect to the server: dial tcp: lookup {...}.eks.amazonaws.com: i/o timeout
```

- The entire network stack stops responding
- Network settings page blanks out completely
- `kubectl version` can't be exited with ctrl+c
- `kill -9` on the `kubectl` process results in `(kubectl)` in `ps aux` output, it never leaves
- Restarting causes MacOS to force quit apps such as firefox, they can't shutdown cleanly

**What you expected to happen**:

Expected it would show the version.

**Environment**:
- Connecting to AWS EKS 
- Kubernetes server v1.21
- `kubectl` clients v1.21, v1.24, v1.25
- Tested with AWS's provided EKS as well as official distributions
- Mac OS 12.6, Intel

I found a comment in an issue in `helm` (https://github.com/helm/helm/issues/11306#issuecomment-1256745270) which solved this for me:  Change to IPv4 only in DNS.

> I was running into the same issue and discovered it was being caused by a weird IPv6 DNS record in my System Settings. These greyed out rules were set automatically (based on my network setup I think), but after manually setting just 192.168.1.254 as my sole DNS server my issues were resolved instantly. System Preferences -> Network -> Advanced -> DNS

**Comment by dims** [comment]
@awbacker you mentioned `Related issue I ran into, which gave me the solution`... can you please comment what exactly you had to do?

**Comment by awbacker** [comment]
@dims 
> Manually setting to 8.8.4.4 or another IPv4 fixes the issue

The specific comment is https://github.com/helm/helm/issues/11306#issuecomment-1256745270

**Comment by eddiezane** [comment]
This appears to be an upstream Go issue. Let's follow it there.

https://github.com/golang/go/issues/52839

/close
