### ISSUE TITLE
how to debug kubectl source code after setting up a local development environment

### ISSUE THREAD

**Issue by oneslideicywater** [kubernetes/kubectl#1300]
Following the instruction of [Development Guide](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md), I add some code in the directory of [kubernetes repo](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl) , the code isn't work after run `make WAHT=cmd/kubectl` cause the binary is built using the code under this repo- kubernetes/kubectl.

which repo should I add the custom debug code ? under  `staging/src/k8s.io/kubectl` of kubernetes/kubernetes or current repo ? 

how can I build a kubectl binary to make my newly added code take effect?

**Comment by ardaguclu** [comment]
`make kubectl` should give you the correct binary which is stored under `_output/bin/kubectl`. Have you checked there?

**Comment by oneslideicywater** [comment]
@ardaguclu 
> the code isn't work after run make WAHT=cmd/kubectl cause the binary is built using the code under this repo- kubernetes/kubectl.

  I actually successfully build kubectl binary under `_output/bin/kubectl`, but my code modified under [kubernetes repo](https://github.com/kubernetes/kubernetes) dir `staging/src/k8s.io/kubectl` doesn't take effect.  

  [kubectl](https://github.com/kubernetes/kubectl) repo has the same code as the code under `staging/src/k8s.io/kubectl`, so should I change the code here? or how can I make my code change in kubectl take effect in my local dev environment?

**Comment by eddiezane** [comment]
All development work for kubectl is done under `staging/src/k8s.io/kubectl` of the main kubernetes repo.

See https://github.com/kubernetes/kubernetes/blob/master/staging/README.md

For more help try asking on the Kubernetes Slack.

/close
