### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Leviathan321** [kubernetes/kubectl#1307]
**What happened?**:
I am deploying istio in my cluster with several applications. From time to time no services can be deployed. When inspecting the events, following message is displayed:

```
118s        Warning   FailedCreate                   replicaset/grafana-68746b898         Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": x509: certificate has expired or is not yet valid: current time 2022-10-17T12:39:46+02:00 is before 2022-10-17T11:53:00Z
**What you expected to happen**:
Pods are deployed.
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client/server versions:

Client Version: 

```
version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```
- OS: linux
- K3s version: k3s version v1.24.6+k3s1 (a8e0c66d)

**Comment by ardaguclu** [comment]
Thanks for opening this issue @Leviathan321.

However, it seems that problem stems from istio webhook or something related to that(probably misconfiguration of webhook?) and kubectl has no effect on this part. I'd suggest asking this to istio folks.

Thus, I'm closing this issue.
/close
