### ISSUE TITLE
Please add fish completion

### ISSUE THREAD

**Issue by wgordon17** [kubernetes/kubectl#131]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "fish"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I would like to be able to run `source (kubectl completion fish)` from my `fish` based shell to enable `kubectl` completion

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:26:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by shiywang** [comment]
FYI: https://github.com/kubernetes/kubernetes/issues/30763

**Comment by GuiSim** [comment]
In the meantime, I use https://github.com/evanlucas/fish-kubectl-completions

**Comment by babilen** [comment]
https://github.com/spf13/cobra/pull/754 might be of interest in this context.

**Comment by pickfire** [comment]
> Another approach would be to ship automatically generated manpages as fish will parse those as well.

Kubectl man pages is neither human readable nor fish-manpage-completions parsable.

I use https://gist.github.com/terlar/28e1c2e4ac9a27be7a5950306bf45ab2 in the meantime.
