### ISSUE TITLE
Make `kubectl logs` aware of network connection changes

### ISSUE THREAD

**Issue by shreemaan-abhishek** [kubernetes/kubectl#1313]
I usually use my mobile hotspot to connect to the internet on my laptop with my mobile being connected to my home wifi. When there is a power cut, my phone reconnects to the internet using cellular data.

In such conditions, when I am collecting logs using the `kubectl logs` command with/without the `-f` flag and a power failure occurs, I get the following error:

`error: http2: client connection lost`

This happens when I connect to or disconnect from a VPN connection while collecting logs.

An elegant solution to such use cases might be a retrying logic that is triggered when the HTTP connection is lost or a flag `--retry=true`.

Although I am very unfamiliar with the codebase, if possible, I would like to work on this issue with some guidance from the maintainers.

**Comment by Ritikaa96** [comment]
> @Ritikaa9
> 
> > I think you are talking about a retry period such as retryAfterSeconds
> > Umm, yes. But such an option is not available for `kubectl logs`.
> 
> > I am curious does this error occur only when you are collecting logs or it occur in no command situation and after a while get solved itself?
> 
> So far, I have faced this issue only while collecting logs. And I could not understand the latter part of your sentence, could you please reframe it? sweat_smile

Hi @shreemaan-abhishek, apologies for the late reply. I meant does it happen with `kubectl logs` or with other commands as well?

**Comment by shreemaan-abhishek** [comment]
@Ritikaa96 not sure if this happens with other commands.

**Comment by eddiezane** [comment]
I think this may be a SPDY issue that we're hoping to fix - similar to port-forward.

https://github.com/kubernetes/kubernetes/issues/111825

It may be addressed in https://github.com/kubernetes/kubernetes/pull/113639 but we'll have to dig into it.

**Comment by Ritikaa96** [comment]
@shreemaan-abhishek 

> I think this may be a SPDY issue that we're hoping to fix - similar to port-forward.
> 
> [kubernetes/kubernetes#111825](https://github.com/kubernetes/kubernetes/issues/111825)
> 
> It may be addressed in [kubernetes/kubernetes#113639](https://github.com/kubernetes/kubernetes/pull/113639) but we'll have to dig into it.

Does this seems similar to your issue?
