### ISSUE TITLE
kubectl apply -f on empty directory fails

### ISSUE THREAD

**Issue by githubcdr** [kubernetes/kubectl#1318]
**What happened**:

This fails if the directory is empty or only contains a .gitkeep file

```
kubectl apply -f directory/
```
error

```
error: error reading [directory]: recognized file extensions are [.json .yaml .yml]
```

**What you expected to happen**:

- I would expect kubectl to ignore hidden files
- kubectl to only scan for .yml and .yaml files
- kubectl not throw an error if the directory is empty

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

kubectl version 1.25.3

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
> kubectl not throw an error if the directory is empty

This is the intended behavior.

> I would expect kubectl to ignore hidden files
> kubectl to only scan for .yml and .yaml files

This is the current behavior. You will see the same error message if the directory is empty. Getting more specific on the error would probably be more effort than it's worth.

See https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects

/close
