### ISSUE TITLE
kubectl not looking in local directory for kubelogin

### ISSUE THREAD

**Issue by hakabo** [kubernetes/kubectl#1319]
**What happened**:
With  kubectl 1.25.0 when running commands kubelogin is not found when adjacent to kubectl in the local working directory. kubelogin is only found when in the PATH

**What you expected to happen**:
I would hope that kubectl would look in the local working directory as well as all the directories in the PATH.

**How to reproduce it (as minimally and precisely as possible)**:
`
PS C:\ProgramData\Apps1> .\kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.0",
    "gitCommit": "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2",
    "gitTreeState": "clean",
    "buildDate": "2022-08-23T17:44:59Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "windows/amd64"
  },

  "kustomizeVersion": "v4.5.7"
}
Unable to connect to the server: getting credentials: exec: executable kubelogin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

PS C:\ProgramData\Apps1> dir .\kubelogin.exe

    Directory: C:\ProgramData\Apps1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          09/08/2022    19:35       45491712 kubelogin.exe
`

**Anything else we need to know?**:
Behaviour not seen with 1.24

**Environment**:
kubectl 1.25.0
PSVersion 7.2.4 Core
Windows 10 20H2
AKS 1.24.6

**Comment by eddiezane** [comment]
> I would hope that kubectl would look in the local working directory

This is not the case. It will not load it from being in the same directory. You need to make sure it's in your PATH.

Check out the docs here https://github.com/Azure/kubelogin#setup-windows.

/triage support
/close
