### ISSUE TITLE
Kubectl independence: Walking/Reading/Writing to Unstructured types with OpenAPI

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#132]
It'd be nice to be able to use Unstructured types as easily as actual Go types.

We could give some thoughts to use OpenAPI to provide a nice framework to find fields, read values, and changes some fields.

This issue will track these efforts.

This is also orthogonal to fixing the union types in the kubernetes API (issue #?).

**Comment by apelisse** [comment]
I'm working on this, but if anybody wants to help, I'd be more than happy to share some of the work. I'll probably come-up with a more detailed plan.

**Comment by shiywang** [comment]
@apelisse hi, is this still wip, anything I could help here ?

**Comment by apelisse** [comment]
Hi @shiywang, yeah I'm still working on this. If you need help finding something useful to do, I think we could talk on slack!

**Comment by soltysh** [comment]
This should be possible currently with dynamic client and Unstructured type.
/close
