### ISSUE TITLE
Error: flags cannot be placed before plugin name: `--alsologtostderr`

### ISSUE THREAD

**Issue by carlosjgp** [kubernetes/kubectl#1324]
**What happened**:

Error when running a command with `--alsologtostderr`

**What you expected to happen**:
`alsologtostderr` is allowed to be used on any position

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl --alsologtostderr --namespace kube-system delete daemonset aws-node --dry-run=client
Error: flags cannot be placed before plugin name: --alsologtostderr

$ kubectl --alsologtostderr --namespace kube-system get daemonset aws-node --dry-run=client
Error: flags cannot be placed before plugin name: --alsologtostderr

$ kubectl --namespace kube-system delete daemonset aws-node --dry-run=client
daemonset.apps "aws-node" deleted (dry run)

$ kubectl  --namespace kube-system get daemonset aws-node --dry-run=client --alsologtostderr
error: unknown flag: --dry-run
See 'kubectl get --help' for usage.

$ kubectl --namespace kube-system delete daemonset aws-node --dry-run=client --alsologtostderr
Flag --alsologtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
daemonset.apps "aws-node" deleted (dry run)

$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: `AWS EKS 1.22`
- OS (e.g: `cat /etc/os-release`): BootleRocket

**Comment by eddiezane** [comment]
Cheers @carlosjgp - please take a look at this issue https://github.com/kubernetes/kubectl/issues/884. 

This is an unfortunate limitation where you need to provide an equal sign if you are using flags early.

e.g. `kubectl --alsologtostderr --namespace=kube-system delete daemonset aws-node --dry-run=client`

We should be giving a better error message though which we can look into.

/assign @brianpursley 
/triage accepted
/priority backlog
