### ISSUE TITLE
Add `--editor` option to `kubectl get`

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubectl#1328]
**What would you like to be added**:

An `--editor` option to `kubectl get` that will open the manifest in an editor just as `kubectl edit` does it.

**Why is this needed**:

An editor usually offers syntax highlighting and makes it easier to nagivate a manifest. I curently use `kubectl edit` for this, even in situation where I do not want to edit anything. This has some issues:
* It can result in accidentally applying a change
* `kubectl edit` doesn't have all the functionality that `kubectl get` has, for example it is currently unable to show managed fields (despite having an option for that)

The idea was originally suggested by @henvic in https://github.com/kubernetes/kubectl/issues/1322#issuecomment-1317351825

**Comment by henvic** [comment]
@ardaguclu,

Doesn't `--output` control only the output format and filtering with json_path, or is there anything else that I'm not aware of? If there isn't, it doesn't conflict.

If it conflicts, maybe we can make it exclusive so you can only use --output or --editor at once or (a little bit riskier) make it smart enough to fail when it's not possible to use both.

What do you think? I won't be able to attend the sig-cli meeting today, unfortunately. I'd appreciate it if this could be clarified there.

**Comment by apelisse** [comment]
Wait, I'm confused, `kubectl edit` doesn't open in your editor? Have you properly set & exported your `$EDITOR` shell variable? Because AFAIK, it's supposed to use that and do the right thing.

**Comment by ardaguclu** [comment]
I think we can close this issue, since there seems to be a consensus about the solution in here https://github.com/kubernetes/kubectl/issues/1322

Feel free if I'm missing something
/close
