### ISSUE TITLE
Re pull image

### ISSUE THREAD

**Issue by antonio-tg** [kubernetes/kubectl#1329]
I've an openshift cluster and an Azure Container Registry from I pull my images, When I push a change in an image I would like to re pull the image to the cluster without affect the other resources in the project.

I hope you can helpme.
Best regards.

**Comment by ardaguclu** [comment]
@antonio-tg thanks for filing an issue.

However, kubectl has nearly no role on pulling images. You may want to ask OpenShift folks with some reproduce steps and versions of your cluster.

/close
