### ISSUE TITLE
Add new interactive flag into delete command

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubectl#1330]
**What would you like to be added**:
Add a new interactive flag into delete command to ask user to proceed or not(something like `--interactive`, `-i`, `--confirm`?).

**Why is this needed**:
As already known delete command should be used carefully because it is disruptive command. However, we could not have added interactivity("do you want to proceed or not") as default into delete, since it is a breaking change. In addition to that,
up to that time, there is no big difference between: `kubectl delete --all` and `kubectl delete --all -i`. Because user types it, already confirms it.

However, after the kuberc will be ready for use, users will be able to set default flags for built-in commands. To allow users set their default `delete` with interactivity. We need a flag to support that.

**Comment by MayukhSobo** [comment]
Hey @ardaguclu I was thinking about taking this up. Can you please give me a user experience once this tag with delete would be present. For example
1. Do we still ask the user for confirmation for all the resource when `--all` is used with `--interactive`?
2. Do we only support it with `delete` as of now?
3. This seems pretty straightforward. Why this is not there yet?

**Comment by ardaguclu** [comment]
@MayukhSobo thanks for your interest on this issue.

However, I have already started implementation. I'll let you know, if I need some help in the future.

> 
> 1. Do we still ask the user for confirmation for all the resource when `--all` is used with `--interactive`?

I think, yes, we should especially ask when `--all` is passed.
> 2. Do we only support it with `delete` as of now?

Delete is disruptive command and basically, at least for now, we need it for only delete
> 3. This seems pretty straightforward. Why this is not there yet?

We could not enable this interactivity by default because it breaks all CI jobs and current users. As a new flag, this will be the foundational work for kuberc and users will be able to set this flag as default in their kuberc file.

**Comment by ardaguclu** [comment]
I'm closing this issue, since we are going to track this via https://github.com/kubernetes/enhancements/issues/3895 KEP

/close
