### ISSUE TITLE
Bug : kubectl cp doesn't work when filename contains brackets

### ISSUE THREAD

**Issue by STYNET** [kubernetes/kubectl#1335]
**What happened**:
The "kubectl cp" command doesn't work when a filename contains bracket character.

**What you expected to happen**:
That it work ^^
or that return warning message (currently, the return code is 0).

**How to reproduce it (as minimally and precisely as possible)**:
Example :  my source filename is : TEST[0]
`kubectl cp -c <container> /tmp/TEST\[0\] <namespace>/<pod>:/directory/`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
kubectl cp has had a few CVE's in the past so we've purposefully limited the functionality. Supporting special characters is not a door we want to open.

/close
