### ISSUE TITLE
Write `kubectl alpha apply`

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#134]
@pwittrock has written a great new piece of code to do apply using openapi. It's much easier to read, modify and use. It's not used at all for now though. It would be nice to build a new `kubectl alpha apply` to start using it. Maybe also fix the bugs.

We could also, on top of that, add new layers to fix the broken behavior in `kubectl apply` that we can't fix with the existing code.

@pwittrock Can you please write a list of these broken behaviors?

**Comment by seans3** [comment]
Apply logic is moving to the server side. This issue is obsolete. Closing.
