### ISSUE TITLE
kubectl diff and invalid spec

### ISSUE THREAD

**Issue by sherlant** [kubernetes/kubectl#1353]
hi

i have an issue with `kubectl diff` cmd.

when i try to use it, i have this result :
```
$ kubectl diff -f build/
The StatefulSet "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
kubectl version : v1.25.3
kubeadm version : v1.19.16
i know that i must delete and recreate my sts if i want really apply the new configuration, but i think the diff must show me the difference.
Any way to can do this ?

thx

**Comment by ardaguclu** [comment]
It seems that you are trying to update forbidden field(`vault`) and this error comes from api server. If you try to actually apply this spec, apply will also return the same error message. `diff` command is designed behaving the way of how `apply` works.

**Comment by ardaguclu** [comment]
I'm closing this issue. If you think that I'm missing something, feel free to re-open it. 

/close
