### ISSUE TITLE
Support Websocket client

### ISSUE THREAD

**Issue by liziwl** [kubernetes/kubectl#1354]
As discussed at here https://groups.google.com/g/kubernetes-users/c/3rNcfmwTAzQ/m/fdslOHHxCgAJ

**What would you like to be added**:

upgrade kubectl to use WebSocket.

**Why is this needed**:

In above discussion, 
> eventually we will have to.

Most clients (Java/Python/JavaScript) use Websocket to establish channel. And Websocket is a modern protocol. SPDY is going to be deprecated.

* [Deprecating SPDY - The Cloudflare Blog](https://blog-cloudflare-com.webpkgcache.com/doc/-/s/blog.cloudflare.com/deprecating-spdy/)
* [Transitioning from SPDY to HTTP/2](https://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html)
* https://github.com/kubernetes/kubernetes/issues/7452
* https://github.com/kubernetes/kubernetes/issues/89163

**Comment by brianpursley** [comment]
I reopend https://github.com/kubernetes/kubernetes/issues/89163 where there was already a lot of history and information.

Let's track this feature there for now.

/close

**Comment by derkoe** [comment]
A workaround for `kubectl exec` is to use https://github.com/jpts/kubectl-execws which works over Websockets.
