### ISSUE TITLE
kubectl run should have a flag for nodeSelector

### ISSUE THREAD

**Issue by pkbhowmick** [kubernetes/kubectl#1357]
**What would you like to be added**:
I think, kubectl run command should have a flag for running the pod in a specific node. Basically it should have a flag like nodeSelector

**Why is this needed**:
While working with kubectl run, I need to run a pod in a specific node which is not possible currently!

**Comment by brianpursley** [comment]
kubectl run is not meant to handle every case of what you want to run.

The best approach would be to create yaml and use `kubectl apply -f`

You can use the `--dry-run=server` flag to generate yaml if you want to have a starting point.

/close
