### ISSUE TITLE
Why is kubectl attempting to use bash when only /bin/sh is installed

### ISSUE THREAD

**Issue by wrothe** [kubernetes/kubectl#1358]
**What happened**:
```
$ KUBE_EDITOR="sed -i '/some_pattern_to_delete/d;'" kubectl edit cm some_configmap
error: there was a problem with the editor "/bin/bash -c sed -i '/some_pattern_to_delete/d;'"
```
**What you expected to happen**:
A more useful output would have helped.  
There is no bash installed, I expect it to use `/bin/sh` Bourne shell/Almquist shell (Almquist in this case)

**How to reproduce it (as minimally and precisely as possible)**:
`some_configmap` with a line matching `some_pattern_to_delete`  
`KUBE_EDITOR="sed -i '/some_pattern_to_delete/d;'" kubectl edit cm some_configmap`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Azure

- OS (e.g: `cat /etc/os-release`):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.8
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by wrothe** [comment]
A workaround is to `export SHELL=/bin/sh`

**Comment by brianpursley** [comment]
`/bin/bash` is the default shell if one is not set.

I don't know how prevalent this problem is, but there is a workaround (setting the `SHELL` environment vasriable).  

Let's update the docs and/or help text to mention that you can override the shell location by setting `SHELL=/bin/sh` or whatever you want it to be,

/triage accepted
/priority backlog
/good-first-issue

**Comment by Sajiyah-Salat** [comment]
Hello @brianpursley I got the issue. but I dont know which file to change. Let me with this.

**Comment by brianpursley** [comment]
`kubectl edit` help text is found here:
https://github.com/kubernetes/kubernetes/blob/83c98542aa4b09198ec3c399666b5798f314cbd2/staging/src/k8s.io/kubectl/pkg/cmd/edit/edit.go#L40

I believe this also automatically gets propagated to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#edit

**Comment by salasberryfin** [comment]
Hi @brianpursley,

I see this issue has no updates since your last message, can I pick it up?

Thanks.

**Comment by Sajiyah-Salat** [comment]
> In the event an error occurs while updating, a temporary file will be created on disk that contains your unapplied changes. The most common error when updating a resource is another editor changing the resource on the server. When this occurs, you will have to apply your changes to the newer version of the resource, or update your temporary saved copy to include the latest resource version.

Hello @brianpursley I think you are talking about this paragraph. Also can you confirm that do we need code contribution here or adding some lines probably above and make small tweaks, we can add it there?

**Comment by turkmenkaan** [comment]
@Sajiyah-Salat are you still working on this? If not, I'd be happy to take this on.

**Comment by Sajiyah-Salat** [comment]
hello @turkmenkaan I want to work on this issue as this a good first issue. But I am confused in implementation part. If you want we can work together.
