### ISSUE TITLE
Install kubectl via winget - in 2023

### ISSUE THREAD

**Issue by Bjego** [kubernetes/kubectl#1359]
Dear kubernetes team,
I would like to have the option to install kubectl via winget. I already asked for this feature years ago #968 , but now things have changed and with winget 1.4 it is possible to deploy / install zip files and portable apps.

See this announcement: https://devblogs.microsoft.com/commandline/windows-package-manager-1-4/ 

**Why is this needed**:
This is a great benefit for developers working on windows to have an opportunity to easily install the correct kubectl version according to their kubernetes cluster version and it's all done with just one cli call.

Could you guys please check, if there is now a solution for this feature request?

And thank you for your great work in general! I love the kubernetes platform and the whole kubernetes ecosystem!

Kind regards,
Bjego

**Comment by brianpursley** [comment]
The kubernetes org builds binaries for each release, but generating (and maintaining) all the various package manager packages for different platforms is out of scope of this SIG.

/close

**Comment by ohads-MSFT** [comment]
Well I'm not sure who to thank but the package exists now (`Kubernetes.kubectl`): 
https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/Kubernetes/kubectl

It's also officially documented: 
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-nonstandard-package-tools
