### ISSUE TITLE
kubectl rollout status deployment has no response

### ISSUE THREAD

**Issue by martin-majorov** [kubernetes/kubectl#1362]
### What happened?

Running the `kubectl rollout status deployment` without specifying deployment name raises no error and gives back no response.

### What did you expect to happen?

Should either throw an error or give status for at least the existing deployment(s)

### How can we reproduce it (as minimally and precisely as possible)?

1. Run any deployment
2. run `kubectl rollout status deployment`

### Kubernetes version

<details>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
Locally with Minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by brianpursley** [comment]
It seems like it should show a message like `No resources found in default namespace.` similar to when you do `kubectl get deployment`.

/triage accepted

**Comment by martin-majorov** [comment]
> It seems like it should show a message like `No resources found in default namespace.` similar to when you do `kubectl get deployment`.
> 
> /triage accepted

Indeed. I used to have version 1.23.3, and this command was freezing in both cases (with or without a deployment). After upgrading to 1.26.1 it is showing the response in case there is a deployment and shows no response in case there is none. This is the issue I'm trying to address here. I think it should give a proper response in case there is nothing deployed.

**Comment by murthy95** [comment]
I want to work on this issue. @martin-majorov

**Comment by ardaguclu** [comment]
As far as I can see, nobody has assigned this issue yet. @murthy95 feel free to work on it. It would be great if you also add some testing steps(integration test probably) to assure that your fix is working.

**Comment by ardaguclu** [comment]
@murthy95 did you have any chance working on this issue?

**Comment by gxwilkerson33** [comment]
@ardaguclu @brianpursley 
From reading through this issue it sounds like the fix is to show the no resources found message when no deployments are running. Otherwise this command is functioning properly? Thats what my testing is showing. Any other concerns here?

I will work on tests to ensure the fix is working as mentioned by @ardaguclu. Does this fix require release note?
Thanks
