### ISSUE TITLE
Bash completion does not use --kubeconfig

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubectl#1366]
**What happened**:
Bash completion does not rely on `--kubeconfig` flag to fetch resources and it does not list anything.

**What you expected to happen**:
Bash completion can fetch resources when `--kubeconfig` flag is passed(KUBECONFIG is unset). 

**How to reproduce it (as minimally and precisely as possible)**:
```sh
$ mv ~/.kube/config ~/.kube/test_config
$ export KUBECONFIG=~/.kube/test_config
$ kubectl get namespaces <tab>
list all namespaces as expected

$ unset KUBECONFIG
$ kubectl get --kubeconfig=~/.kube/test_config namespaces <tab>
does not list namespaces.
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.1.279+8e20effbb7b99c-dirty", GitCommit:"8e20effbb7b99c9c5caad4b8f947ca645bbaf21b", GitTreeState:"dirty", BuildDate:"2023-02-08T09:50:09Z", GoVersion:"go1.20", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
kind cluster
- OS (e.g: `cat /etc/os-release`):

**Comment by marckhouzam** [comment]
It works for me @ardaguclu.  I tried with `1.26.1` and building off the `master` branch.

I wonder if you may be using an old version of the completion script?  Can you try this:
```
source <(kubectl completion bash)
unset KUBECONFIG
kubectl get --kubeconfig=~/.kube/test_config namespaces <tab>
```

**Comment by ardaguclu** [comment]
@marckhouzam thanks a lot for your message.

You are right. I was using old version of completion script. After executing `source <(kubectl completion bash)`, it worked.

/close
