### ISSUE TITLE
Allow deletion of resources specified by name across all namespaces 

### ISSUE THREAD

**Issue by michsp97** [kubernetes/kubectl#1371]
**What would you like to be added**:

Hello, I would like to allow kubectl command to delete resources specified by name across all namespaces. This is specially useful when you want to delete all resources within your cluster that meet a certain criteria, for example I wrote a command to delete all services of type LoadBalancer, used `kubectl get` command to filter all the services that met the criteria, and feed the output to `kubectl delete` command. When using --dry-run flag it does the desired action:
```
kubectl get service -A -o json | jq '.items[] | select (.spec.type=="LoadBalancer")' | jq '.metadata.name' | xargs kubectl delete services --dry-run=client
service "foo-example-service-1" deleted (dry run)
service "bar-example-service-2" deleted (dry run)
service "baz-example-service-3" deleted (dry run)
service "nlb-sample-service" deleted (dry run)
```

The problem is that the resources are in different namespaces, so it is needed to perform the deletion across all namespaces, to ensure **all** the services of type LoadBalancer (or specified criteria) are **deleted from the kubernetes cluster**. This should be easily achieved with `--all-namespaces` flag being compatible with `kubectl delete` command:
```
kubectl get service -A -o json | jq '.items[] | select (.spec.type=="LoadBalancer")' | jq '.metadata.name' | xargs kubectl delete services --all-namespaces
error: a resource cannot be retrieved by name across all namespaces
```

Currently `kubectl delete` doesn't have the capability to delete resources specified by name across multiple namespaces. The xargs command would make this integration adjust perfectly, since the output in the `kubectl get` is in the required format for the `kubectl delete` command.

**Why is this needed**:
With the accelerated growth of cloud computing, containerization and infrastructure management, it is needed to ensure proper deletion of resources is achieved, having this capability will facility automation workflows and ensure k8s clusters healthiness with easier management of kubernetes clusters.

**Comment by mpuckett159** [comment]
/close
The intention of the `-A/--all-namespaces` flag is not intended to be used to delete resources by name. This work can be accomplished by using the label selectors (see below). We would consider deleting resources specified by name across all namespaces out of scope for kubectl.

```bash
$ k delete pod -l "foo=bar" -A
pod "nginx" deleted
pod "nginx" deleted
```

**Comment by michsp97** [comment]
Hey @mpuckett159 we get into the same issue following the procedure you mention, we cannot label all kubernetes resources that meet a certain criteria across multiple namespace. Could we then enable the functionality to filter a label k8s resources based on a specified criteria?
```
kubectl label service $(kubectl get service -A -o json | jq '.items[] | select (.spec.type=="LoadBalancer")' | jq '.[metadata.name]') test=deleteme --all-namespaces

error: a resource cannot be retrieved by name across all namespaces
```

If we enable this functionality the we could accomplish the deletion of all labeled resources

**Comment by mpuckett159** [comment]
I'll bring this up next meeting but I believe that the answer is going to be the same, that this is not an intended use case of kubectl and is considered out of scope for the tool.

**Comment by michsp97** [comment]
Yes please do, to me it makes completely sense to label all resources at once that meet certain criteria, specially as infrastructure complexity grows over time. 

Thank you @mpuckett159

**Comment by mpuckett159** [comment]
The reason I believe it is unlikely that sig-cli will accept this is because the label and delete commands are what are called imperative commands, as opposed to declarative commands. You can find more details in the links of this issue:
https://github.com/kubernetes/kubectl/issues/1374#issuecomment-1457312834

Long story short, imperative commands are really only for simple cases, where declarative commands are intended for more complex and production grade cases, and so yes, as workloads get more complex and scale larger, the imperative commands no longer apply as well, but that's where the declarative ones come in.

**Comment by michsp97** [comment]
I understand, but the `kubectl get` command is also imperative, and you can add a little bit more complexity than just simple basic commands. 
Please bring this issue to the table, I really think labeling resources on multiple namespaces would be a nice addition to k8s cli and will be useful for future users.

**Comment by mpuckett159** [comment]
This was discussed again on the bug scrub and it was reiterated that these commands should have as limited of scopes as possible to help prevent users from causing unintentional changes in their environments. It is also possible to script these tasks to iterate through the namespaces and accomplish the task you're trying to do.

**Comment by michsp97** [comment]
That's a shame @mpuckett159 , we could say the same about `kubectl get --all-namespaces` it could be scripted too to iterate on each namespace and create a whole script for it. The purpose of labeling across multiple namespaces was to make things easier and add more capabilities to **kubectl** command, this is why the flag was needed. Thank you for getting involved tho, hopefully this suggestion to label resources on multiple namespaces is bring back in the future and receive further support.
