### ISSUE TITLE
kubectl debug: Add integration and unit tests for new profiles

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubectl#1372]
**What would you like to be added**:
New profiles were added into kubectl debug command. 
We need to add more integration tests for these profiles into https://github.com/kubernetes/kubernetes/blob/master/test/cmd/debug.sh

We need to add more unit tests for these profiles in `TestGeneratePodCopyWithDebugContainer`
and `TestGenerateNodeDebugPod` functions. EphemeralContainer unit tests are already
covering these profiles.

**Why is this needed**:
To increase confidence and prevent possible regressions in the future.

**Comment by ardaguclu** [comment]
@sding3 @wedaly
Would you be interested in working on this?

**Comment by ardaguclu** [comment]
This https://github.com/kubernetes/kubernetes/pull/115839 covers the unit tests. Thanks @wedaly

**Comment by sding3** [comment]
@ardaguclu - friendly ping on https://github.com/kubernetes/kubernetes/pull/115909

**Comment by ardaguclu** [comment]
I think we can close this issue, since integration and unit tests were added in referenced PRs.
