### ISSUE TITLE
kubectl explain node / oc explain node delivers wrong information

### ISSUE THREAD

**Issue by erdincay** [kubernetes/kubectl#1377]
**What happened**:

I executed `oc explain node` and received wrong information what a node is. It stated that a node is a worker node, which is wrong.

**What you expected to happen**:

I expected it to write: a node is a worker node **or a master node**.

**How to reproduce it (as minimally and precisely as possible)**:

`oc explain node`

**Anything else we need to know?**:

Open Shift Version from `oc version`:
![grafik](https://user-images.githubusercontent.com/11290149/220595689-1dd10011-ca16-41c3-8744-12645f4c02ba.png)

**Environment**:

RHEL 8.6, platform:el8

**Comment by ardaguclu** [comment]
I'm going to close this issue because as far as I know, `kubectl explain node` does not contain any data indicating that node is worker or master. Feel free to re-open it, if I'm missing something.

/close

**Comment by erdincay** [comment]
I created an issue on the API docs repository: https://github.com/kubernetes/api/issues/47
