### ISSUE TITLE
kubectl diff does not report missing ConfigMap keys

### ISSUE THREAD

**Issue by mbehm** [kubernetes/kubectl#1378]
I have noticed that when using `kubectl diff` to compare a YAML file containing a ConfigMap to the current state of the ConfigMap in the cluster, missing key-value pairs in the YAML file that exist in the current state of the ConfigMap are not reported as differences. This can lead to unexpected changes to the ConfigMap when applying the YAML file with kubectl apply.

For example, if a key-value pair exists in the current ConfigMap in the cluster but is not present in the YAML file, and I apply the YAML file with `kubectl apply`, the key-value pair will be removed from the ConfigMap. However, `kubectl diff` does not report this as a difference, even though it would result in a change to the ConfigMap. It'll only be listed as changed if the key exist in the file but has a different value than what's in the cluster.

I believe that removing a key-value pair from a ConfigMap is just as much a change as modifying its value. Therefore, I suggest that kubectl diff should report missing ConfigMap keys in the same way that it reports modified values. This would make it easier to identify situations where a key-value pair would be removed from the ConfigMap if the YAML file were applied.

Thank you for your attention to this issue.

**Comment by ardaguclu** [comment]
@mbehm in which version are you using?, could you please provide steps for reproducing this issue?. Thanks.

**Comment by mbehm** [comment]
Tried to create a small test case to reproduce it and my bad it seems if the key doesn't exist in the new ConfigMap then apply will leave the current value in the cluster as is, I must have accidentally used create or done something to completely overwrite the existing one.

Sorry for the inconvenience, closing the issue.
