### ISSUE TITLE
Unable to install kubectl

### ISSUE THREAD

**Issue by Annihilatopia** [kubernetes/kubectl#1379]
**What happened**:
https://packages.cloud.google.com/apt/doc/apt-key.gpg results in 500 error

**What you expected to happen**:
adding the apt-key should be successful

**How to reproduce it (as minimally and precisely as possible)**:
https://packages.cloud.google.com/apt/doc/apt-key.gpg

**Anything else we need to know?**:
```sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg```

**Comment by benoittgt** [comment]
https://github.com/GoogleCloudPlatform/gcsfuse/issues/961#issuecomment-1446073052

**Comment by pfuntner** [comment]
My team has an image that's built in Jenkins daily.  It failed for this issue this morning but it also failed yesterday (2023-02-27 around 1030Z) for the same reason but it did not fail on Saturday.  Something must have happened between 2023-02-26 1030Z and 2023-02-27 1030Z.

**Comment by ardaguclu** [comment]
There are duplicates of this issue and it would be tracked in one of them(since it is known issue)
https://github.com/kubernetes/kubernetes/issues/116068
https://github.com/kubernetes/kubernetes/issues/116087

Thereby, I'm closing this one.

/close

**Comment by dims** [comment]
See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
