### ISSUE TITLE
Use structured generator for kubectl autoscale

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubectl#138]
`kubectl autoscale` is using parameter injection style generator at the moment.

It should implement the [structured generator interface](https://github.com/kubernetes/kubernetes/blob/c3ed0f26636d0fc5c3905a0c09bf4886da8512c9/pkg/kubectl/generate.go#L49-L52) like deployment generator: https://github.com/kubernetes/kubernetes/blob/c3ed0f26636d0fc5c3905a0c09bf4886da8512c9/pkg/kubectl/deployment.go#L119-L147.
After implementing the interface, we should
- refactor `kubectl autoscale` to use  the new generator
- create [`kubectl create hpa`](https://github.com/kubernetes/kubernetes/issues/39833) (optional)

When implementing the interface, make sure you generate a external type object.

**Comment by wackxu** [comment]
I can help fix it

**Comment by mengqiy** [comment]
Great!
I found I can't assign it to you. So I will assign it to myself for now. Ping me on slack when the PR is ready or you have some question.

**Comment by wackxu** [comment]
@mengqiy Ok, Thanks

**Comment by mengqiy** [comment]
This is fixed by #55913. Closing.
