### ISSUE TITLE
kubectl 1.24.10 fails with DBus error System.Error.E2BIG Argument list too long

### ISSUE THREAD

**Issue by robotrapta** [kubernetes/kubectl#1380]
**What happened**:

I ran `kubectl` on a workstation that had been successfully using `kubectl` for a long time.  Instead of doing anything useful it just says

```
internal error, please report: running "kubectl" failed: cannot create transient scope: DBus error "System.Error.E2BIG": [Argument list too long]
```

Exactly the same regardless of whether I say `kubectl get pods` or `kubectl version` or just `kubectl`. 

**What you expected to happen**:

I expect the usual great things I've come to love about using kubectl.

**How to reproduce it (as minimally and precisely as possible)**:

This is on an ubuntu 22.04.1 LTS machine, running kubectl from snap, v1.24.10 from stable channel.  Funny thing is that other users on the same machine get kubectl to work.  Deleting the `.kube/confg` file doesn't get it to run.  Getting rid of all of `~/.kube` doesn't get it to run either. 

**Anything else we need to know?**:

Well this is really the question, isn't it?  Why is it failing?  I don't know.  Why does it work for other users?  I don't know.  But it says "please report" so here I am.

**Environment**:

Ubuntu 22.04.1 LTS, x86
Running kubectl from snap, v1.24.10 from stable channel
Server is irrelevant - never gets that far.

**Comment by robotrapta** [comment]
Rebooting fixes the problem.  :/

**Comment by ardaguclu** [comment]
as far as I know, snap daemon had a problem and after rebooting, it healed. There seems to be no issue with kubectl;

/close

**Comment by robotrapta** [comment]
I don't disagree with the conclusion that this doesn't need attention, but I'm confused about how the snap daemon would be involved.  When I run `kubectl` that's just running the local executable on the disk which the snap daemon put there long ago.  Shouldn't `kubectl` work regardless of what state snap is in?
