### ISSUE TITLE
kubectl disable probes for troubleshooting

### ISSUE THREAD

**Issue by migs35323** [kubernetes/kubectl#1384]
**What would you like to be added**:

Can we have a kubectl command to TEMPORARILY disable the readiness/liveness/startup probes while inside a kubectl exec so we can troubleshoot containers?

**Why is this needed**:

in a deployment lifetime sometimes stuff in the containers get wrong, for example, data got somewhat corrupted in a DB, an app is crashing because a bug that only showed up later in it's life..
there are plenty of situations where one can just exec into the container to quickly check whats going on with the container like performing some DB commands or check if the app is having problems communicating with another pod, check logs that are inside the container and not exported by default, 
however the probes get in the way of the troubleshooting, while we are inside the container it just restarts and it gets very frustrating for quickly troubleshooting an app

I understand that for troubleshooting we can use a standalone side pod or remove the probes from the deployment but i feel this is not desirable for quickly solve issues since we are relying in either creating a pod with the same configs and envs, or redeploy stuff...

**Comment by ardaguclu** [comment]
@migs35323 thanks for the issue. This looks more like a `kubectl debug` command use case instead `kubectl exec`. Have you tried it?

**Comment by migs35323** [comment]
> @migs35323 thanks for the issue. This looks more like a `kubectl debug` command use case instead `kubectl exec`. Have you tried it?

woa, been working with k8s for a year and i was not aware of kubectl debug...
by default does it remove the probes or creates an exact replica of a pod?
does it have access to all the mounted volumes and envs?
i need to test it later, but probably is exactly what i was looking for,
I had a few deployments in the past that for some reason the app decided to give up working 
or some apps where they are in a crashloop and i couldn't grab the logs that are saved internal in the pod (that get gone after ther restart)

**Comment by ardaguclu** [comment]
> by default does it remove the probes or creates an exact replica of a pod?

yes exactly, I think `kubectl debug` is exactly the command you are looking for. I'm closing this issue. Feel free to re-open it, if you think I'm missing something.

/close
