### ISSUE TITLE
Kustomize v5 Support

### ISSUE THREAD

**Issue by thebeanogamer** [kubernetes/kubectl#1386]
**What would you like to be added**:

Kubectl is currently using Kustomize v4.5.7, however there are several features in Kustomize v5 that it would be helpful to be able to use.

```
$ kubectl version --short
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.25.6-eks-48e63af
```

Apologies if this is already in motion, I was unable to find any documentation around the process for merging new releases of Kustomize.

**Why is this needed**:

Kustomize v5 has a number of breaking changes, adding new features and deprecating some old ones. Until the new release of Kustomize is merged into Kubectl, to use these features we have to revert back to `kustomize build | kubectl apply -f -`.

**Comment by eddiezane** [comment]
This will release [soon](https://www.kubernetes.dev/resources/release/#timeline) with v1.27!

https://github.com/kubernetes/kubernetes/pull/116598

/close
