### ISSUE TITLE
Port-forward more resource types

### ISSUE THREAD

**Issue by jacobtomlinson** [kubernetes/kubectl#1387]
**What would you like to be added**:
Currently `Service` resources can be port-forwarded by looking up the pod selector of the service and then choosing a Pod to port-forward.

It would be nice if other resource types could be port-forwarded, especially custom resources.

Perhaps one solution to this would be to make the Service code more generic to support any resource with a pod selector. The flow would remain the same, look up the resource, check if it has a selector, if so select the pods, if there are pods choose one and port forward it.

**Why is this needed**:
When custom resources create services if the user wants to port-forward them they need to look up the name of the service that is owned by the custom resource. It would improve user experience if they could port forward the custom resource directly.

**Comment by sftim** [comment]
How would `kubectl` know that a custom resource represents something you can port forward to, or that a field named `selector` is meant to select Pods? If something has a `port` field, that might represent a wholly different concept (such as a StorageFabricChannelAllocation CRD used to support dynamic resource allocation).

**Comment by jacobtomlinson** [comment]
Yeah I think the API today doesn't allow for this easily. It would be great if I could somehow specify in my CRD metadata that a field is a Pod selector. Then `kubectl` could know what to do.

Should I open an issue elsewhere for that?

**Comment by mpuckett159** [comment]
Yes this should be transferred to the api-machinery SIG I believe.
