### ISSUE TITLE
Add `kubernetes_feature_enabled` metric to `cluster-info dump`

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubectl#1388]
> Add `kubernetes_feature_enabled` metric series to track whether each active feature gate is enabled.

https://github.com/kubernetes/kubernetes/pull/112690 was merged in v1.26 cycle.  It can fix partially on the issue https://github.com/kubernetes/kubernetes/issues/87869 and I wondered if we can add the metrics info into `kubectl cluster-info dump`

_Originally posted by @pacoxu in https://github.com/kubernetes/kubernetes/issues/87869#issuecomment-1465626709_
     
            
```
kubectl get --raw /metrics  | grep kubernetes_feature_enabled
```

**Comment by pacoxu** [comment]
good idea.

**Comment by mpuckett159** [comment]
/close
We will let the [KEP](https://github.com/kubernetes/enhancements/pull/3920) drive this.
