### ISSUE TITLE
kubectl logs Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy)

### ISSUE THREAD

**Issue by zzq392342084** [kubernetes/kubectl#139]
kubectl create command works correctly,but kubectl logs and kubectl exec not : 
Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy)

**Comment by stewart-yu** [comment]
have your cluster RABC opened? and can you provide more information about your cluster

**Comment by apelisse** [comment]
I strongly suspect this is just mis-configured RBAC rules. Please clarify.

I'll try to close that in a week or so if no updates.

**Comment by apelisse** [comment]
Feel free to re-open if needed! Thanks
