### ISSUE TITLE
error: --show-labels option cannot be used with custom-columns=NAME

### ISSUE THREAD

**Issue by nitinware** [kubernetes/kubectl#1392]
**What happened**:
I am trying to list all nodes on my cluster and their associated availability zones

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

kubectl get nodes --show-labels -o=custom-columns=NAME:.metadata.name,AVAILABILITY_ZONE:.metadata.labels.topology\.kubernetes\.io/zone

error: --show-labels option cannot be used with custom-columns=NAME:.metadata.name,AVAILABILITY_ZONE:.metadata.labels.topology.kubernetes.io/zone printer

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): MAC OS

**Comment by eddiezane** [comment]
You can drop the `--show-labels` flag and just grab the label you care about escaping the `.`'s.

```
kubectl get nodes -o custom-columns=NAME:.metadata.name,ZONE:"metadata.labels.topology\.kubernetes\.io/zone"
NAME                                          ZONE
ip-192-168-30-13.us-west-2.compute.internal   us-west-2b
ip-192-168-35-70.us-west-2.compute.internal   us-west-2a
```

/close

**Comment by nitinware** [comment]
@eddiezane Thnx for ur suggestion, appreciate it.
