### ISSUE TITLE
Optimize the help context when command has a sub-command.

### ISSUE THREAD

**Issue by LronDC** [kubernetes/kubectl#1395]
The helping context of a command which has a sub-command is a little ambiguous.
For example when creating secret it says:
```shell
$ kubectl create secret -h
Create a secret using specified subcommand.

Available Commands:
  docker-registry   Create a secret for use with a Docker registry
  generic           Create a secret from a local file, directory, or literal value
  tls               Create a TLS secret

Usage:
  kubectl create secret [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
in `Usage` part
```shell
Usage:
  kubectl create secret [flags] [options]
```
In fact it's not `'[flags]'` but `'[subcommands]'` or just `'[commands]'`
Also
```shell
Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
is an ambiguous expression(I think), it would be better if it shows
```shell
Use "kubectl create secret <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
or remove these two sentences e.g. configmap or other resources. 
After a short research I do realize that these two sentences are general expressions of commands which have sub-commands, but it still could be more clear with the specific commands.

**What would you like to be added**:
```shell
$ kubectl create secret -h
Create a secret using specified subcommand.

Available Commands:
  docker-registry   Create a secret for use with a Docker registry
  generic           Create a secret from a local file, directory, or literal value
  tls               Create a TLS secret

Usage:
  kubectl create secret [commands] [options]

Use "kubectl create secret <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
```shell
$ kubectl create -h
...
Usage:
    ...
Use "kubectl create <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
Clearer expression and guidance.
**Why is this needed**:
**--help** options are usually for learners and beginners, which should be more concise clearer, and helpful.

If you think it should be optimized, please let me know and let me work on it, I've already done some research.

**Comment by LronDC** [comment]
cc @seans3 @mengqiy

**Comment by mpuckett159** [comment]
/triage accepted
/priority backlog
It is possible to pass something to the `Use` property of the cobra Command object. Whoever takes this up should check to see how this affects the "Usage" string. It's possible that cobra simply does a concatenation of all the strings and may mangle what is output in the help text.

**Comment by mpuckett159** [comment]
Yes feel free to take it and thank you for looking into it ❤️

**Comment by LronDC** [comment]
@mpuckett159 Hi👋, I opened a PR of this issue [#117930](https://github.com/kubernetes/kubernetes/pull/117930), would you please review this and give some advice?
/cc @seans3 @mengqiy
