### ISSUE TITLE
Add kubectl get events short flag or alias to `--sort-by=lastTimestamp`

### ISSUE THREAD

**Issue by mjura** [kubernetes/kubectl#1396]
**What would you like to be added**:

We would like to add simple flag to  `kubectl get events`  which will be alias to `--sort-by=lastTimestamp`. For example `kubectl get events -t` this should print events sorted with `lastTimestamp`

**Why is this needed**:

To make our life easier!

**Comment by eddiezane** [comment]
Thank you for the feature request but we are avoiding adding more short flags unless necessary.

/close
