### ISSUE TITLE
kubectl completion file for zsh does not include __start_kubectl anymore

### ISSUE THREAD

**Issue by remyd1** [kubernetes/kubectl#1397]
**What happened**:

I tried to install the last version of kubectl and set the `k` alias, like described in the [official install documentation](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#enable-shell-autocompletion).

`kubectl` (and its completion) works great, however, `k` alias results in :

```
command not found: zsh: __start_kubectl: 
```

I have found this related [stackoverflow issue](https://stackoverflow.com/questions/70649249/command-not-found-start-kubectl), however nothing works.

**What you expected to happen**:

`k` alias autocompletion works, like with `kubectl`.

**How to reproduce it (as minimally and precisely as possible)**:

Just follow the official install section.

**Anything else we need to know?**:

I have many `oh-my-zsh` plugins, but even if I disable many of those plugins, it still does not work. I thought it was an issue with autocomp or my zsh completion plugins, but I think I have found the real issue:

I tried to download old releases, just to check if `__start_kubectl` function exists, and it does.
..Indeed, in older kubectl versions, it exists... For example:

```bash
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
chmod +x ./kubectl
./kubectl completion zsh > _kubectl.zsh
grep '__start_kubectl()' _kubectl.zsh
# Ok => __start_kubectl()
```

So, I tried to put the generated completion file `_kubectl.zsh` in my `~/.oh-my-zsh/custom/completions/` directory, however, I have now another error:

```
__kubectl_type:2: = not found
```

Finally, I just checked the differences with `meld` tool, but there are too many differences to quickly fix this myself.

**Environment**:

- Kubernetes client and server versions (use `kubectl version`): tested with `1.26.0`, `1.26.3`
- Cloud provider or hardware configuration: gcp, rancher rke2, ...
- OS (e.g: `cat /etc/os-release`): 
```ini
NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
```

**Comment by marckhouzam** [comment]
I believe you have followed the instructions for bash. For zsh you do not need to do anything for aliases: they work automatically. If you look on the same documentation page, there’s a separate tab for zsh.

Please also see https://github.com/kubernetes/kubectl/issues/1135#issuecomment-949737182

**Comment by remyd1** [comment]
Hi;

Ok. If I remove `compdef __start_kubectl k`, I have no error anymore, however, zsh completion still does not work. With `k`, it tries to autocomplete with directories, contrary to `kubectl` which is working as expected.

Can you provide me a working sample `.zshrc` file, that I could compare with mine.

Here is mine:

```
autoload -Uz compinit
compinit
export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true"
DISABLE_LS_COLORS="true"
plugins=(git autojump zsh-autosuggestions docker k zsh-completions fzf enhancd tmux tmux-cssh kubectl)
source $ZSH/oh-my-zsh.sh
alias gits="git status"
alias gitp="git push"
alias gpl="git pull"
alias gitd="git diff"
alias gitco="git commit -a -m"
alias x="exit"
alias cat="bat --theme=gruvbox-light"
alias ls="exa"
alias manu="tldr"
alias chrome="flatpak run com.google.Chrome"
alias chromium="flatpak run org.chromium.Chromium"
alias r="fc -s"
export FCEDIT=vim
source <(kubectl completion zsh)
alias kn="kubectl neat"
alias kubens="kubectl-ns"
alias kubectx="kubectl-ctx"
alias k="kubectl"
if [ -f /etc/profile.d/lt.sh ]; then
   source /etc/profile.d/lt.sh
fi
export $ENHANCD_DISABLE_DOT=1
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
setopt completealiases
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fpath=(~/.oh-my-zsh/custom/completions ~/.oh-my-zsh/plugins/kubectl ~/.oh-my-zsh/plugins/tmux-cssh ~/.oh-my-zsh/plugins/tmux ~/.oh-my-zsh/custom/plugins/enhancd ~/.oh-my-zsh/plugins/fzf ~/.oh-my-zsh/custom/plugins/zsh-completions ~/.oh-my-zsh/custom/plugins/k ~/.oh-my-zsh/plugins/docker ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ~/.oh-my-zsh/plugins/autojump ~/.oh-my-zsh/plugins/git ~/.oh-my-zsh/functions ~/.oh-my-zsh/completions ~/.oh-my-zsh/cache/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.9/functions ~/.oh-my-zsh/custom/plugins/zsh-completions/src)
```

As I already said, I also tried to remove many plugins, including k, kubectl, enhancd, zsh-{autosuggestions,completions}...

<small>Note `lt.sh` is just a basic shell function to do `ls -lt |head -N`  with argument `N` for head</small>

**Comment by remyd1** [comment]
It works (see EDIT in previous message).

Thanks.
