### ISSUE TITLE
`kubectl scale` completion does not include statefulset

### ISSUE THREAD

**Issue by sanderploegsma** [kubernetes/kubectl#14]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): A bit of both, I guess.

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: Macbook Pro 2016
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12.4
- **Kernel** (e.g. `uname -a`): `Darwin Sanders-MacBook-Pro-2.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64`
- **Install tools**: `gcloud components install kubectl`?
- **Others**: Running zsh

**What happened**: When trying to scale my statefulset using `kubectl`, autocomplete only offers `--replicas             deployment             job                    replicaset             replicationcontroller`.

**Comment by pwittrock** [comment]
@foxish Are you the right person for this?
