### ISSUE TITLE
kubectl -n kube-system and kubectl --all-namespaces, differ in behavior

### ISSUE THREAD

**Issue by naisanza** [kubernetes/kubectl#140]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kube-system all-namespaces 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug?

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): 4.4.0-98-generic
- **Install tools**: `zfs` `bidge`
- **Others**:

**What happened**:
kubectl -n kube-system get sa:
```
root@bigma:~# kubectl -n kube-system get sa
NAME                         SECRETS   AGE
attachdetach-controller      1         18h
bootstrap-signer             1         18h
certificate-controller       1         18h
cronjob-controller           1         18h
daemon-set-controller        1         18h
default                      1         18h
deployment-controller        1         18h
disruption-controller        1         18h
endpoint-controller          1         18h
flannel                      1         18h
generic-garbage-collector    1         18h
horizontal-pod-autoscaler    1         18h
job-controller               1         18h
kube-dns                     1         18h
kube-proxy                   1         18h
kubernetes-dashboard         1         18h
namespace-controller         1         18h
node-controller              1         18h
persistent-volume-binder     1         18h
pod-garbage-collector        1         18h
replicaset-controller        1         18h
replication-controller       1         18h
resourcequota-controller     1         18h
service-account-controller   1         18h
service-controller           1         18h
statefulset-controller       1         18h
token-cleaner                1         18h
ttl-controller               1         18h
```

kubectl --all-namespaces get sa:
```
root@bigma:~# kubectl --all-namespaces get sa
Error: unknown command "sa" for "kubectl"

Did you mean this?
        set
        cp

Run 'kubectl --help' for usage.
```

**What you expected to happen**:
Both to exhibit the same behavior, whether `-n` is used or `--all-namespaces` is used

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by naisanza** [comment]
@steward-yu should this be fixed to have universal behavior?

**Comment by stewart-yu** [comment]
In my opinion, you should follow command line rules: `-n` is `kubectl `command options, but `--all-namespaces` response to `kubectl <commandname>`. In other word, `-n` and `--all-namespaces`  are use in different level. @naisanza

**Comment by apelisse** [comment]
I agree with @stewart-yu.

Having ... `kubectl --all-namespaces create ...` makes no sense, while `kubectl -n some-namespace create ...` does.

**Comment by apelisse** [comment]
@naisanza I'd be happy to know why you disagree? :-)

**Comment by liggitt** [comment]
looks like a flag parsing issue in cobra/spf13

`kubectl get sa --all-namespaces` works fine

**Comment by liggitt** [comment]
the flags must come after the command to which they apply. `--all-namespaces` belongs to the `get` command. `-n` and `--namespace` are global options

/close
