### ISSUE TITLE
dns-over-https prevents kubectl from connecting to API

### ISSUE THREAD

**Issue by michalschott** [kubernetes/kubectl#1401]
**What happened**:
We're using [Twingate](https://www.twingate.com), recently an option to force dns-over-https was enabled. While client is on and running, I'm unable to connect to EKS API (using dns resolution) with kubectl, although curl works. If server dns name in kubectl config is replaced with IP address, connection works.

```
~ k cluster-info -v10
I0330 16:20:18.609075   66186 loader.go:374] Config loaded from file:  /Users/ms/.kube/config
I0330 16:20:18.609522   66186 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.24.10 (darwin/arm64) kubernetes/5c1d2d4" 'https://82ca537954000562b2f3178ba5423915.sk1.eu-west-1.eks.amazonaws.com/api?timeout=32s'
I0330 16:20:49.130875   66186 round_trippers.go:495] HTTP Trace: DNS Lookup for [REDACTED].eks.amazonaws.com resolved to []
I0330 16:20:49.131116   66186 round_trippers.go:553] GET https://[REDACTED].eks.amazonaws.com/api?timeout=32s  in 30521 milliseconds
I0330 16:20:49.131196   66186 round_trippers.go:570] HTTP Statistics: DNSLookup 30001 ms Dial 0 ms TLSHandshake 0 ms Duration 30521 ms
I0330 16:20:49.131217   66186 round_trippers.go:577] Response Headers:
I0330 16:20:49.131385   66186 cached_discovery.go:119] skipped caching discovery info due to Get "https://[REDACTED].eks.amazonaws.com/api?timeout=32s": dial tcp: lookup [REDACTED].eks.amazonaws.com: i/o timeout
I0330 16:20:49.134016   66186 round_trippers.go:466] curl -v -XGET  -H "User-Agent: kubectl/v1.24.10 (darwin/arm64) kubernetes/5c1d2d4" -H "Accept: application/json, */*" 'https://[REDACTED].eks.amazonaws.com/api?timeout=32s'
^C
~ curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.24.10 (darwin/arm64) kubernetes/5c1d2d4" 'https://[REDACTED].eks.amazonaws.com/api?timeout=32s'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying [REDACTED IP ADDRESS]:443...
* Connected to [REDACTED].eks.amazonaws.com ([REDACTED IP ADDRESS]) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Request CERT (13):
* (304) (IN), TLS handshake, Certificate (11):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**What you expected to happen**:
I should be able to connect to API.

**How to reproduce it (as minimally and precisely as possible)**
* launch twingate client, connect to the network with DoH enabled

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): EKS/kubectl 1.24.10
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Mac M1

**Comment by michalschott** [comment]
Also affected versions: 1.25.X, 1.26.X

Tested with 1.27.1, problem is gone, assume 1.27.0 also works. Can we have a backport please?

**Comment by eddiezane** [comment]
There's nothing obvious from the 1.27 release notes on why this would happen and what would need to be backported.

To help us out please go through a [git bisect](https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination) to find the commit that fixes it in 1.27. You can probably start at 1.26.4.

```
git bisect start

# v1.26.4
git bisect good f89670c3aa4059d6999cb42e23ccb4f0b9a03979

# v1.27.0
git bisect bad 1b4df30b3cdfeaba6024e81e559a6cd09a089d65
```

You can build kubectl with `make kubectl` from the root of the [kubernetes/kubernetes repo](https://github.com/kubernetes/kubernetes). And then do your testing using the built binary at `_output/bin/kubectl`.

Please let me know if you get stuck.

The other possibility is that this was an upstream Go bug that was fixed. A minor release of Kubernetes usually sticks to a given version of Go so you could try building 1.26 with the latest version (go1.20.3).

**Comment by michalschott** [comment]
@eddiezane turns out this is most likely issue with go 1.19 - looks like kubectl <=1.26 is being build with go 1.19 and k 1.27 is being build with go 1.20.

Same issue is present in https://github.com/stern/stern - where recompiling it myself with go 1.20(.3 in my case) fixed networking issue.

**Comment by michalschott** [comment]
@eddiezane can confirm building kubectl with go 1.20.3 fixed the problem.

**Comment by eddiezane** [comment]
Awesome thanks for helping debug.

There's no an action to take here because we won't bump a Go version for a past release. Hopefully using 1.27 is possible or one you've built yourself.

/close
