### ISSUE TITLE
Kubectl diff not producing any changes when fields are removed from manifest

### ISSUE THREAD

**Issue by rsafonseca** [kubernetes/kubectl#1403]
**What happened**: kubectl diff isn't producing the expected output when ***kubectl.kubernetes.io/last-applied-configuration*** isn't present in a resource. When a field is removed from a resource manifest, the diff doesn't show the field as removed, but running apply indeed removes the field. This behaves as expected for adding or modifying existing fields, but not for removing fields.

**What you expected to happen**: kubectl diff should produce the differences between the live object and the one being compared/applied, not only for modified or added fields, but also for removed fields

**How to reproduce it (as minimally and precisely as possible)**: 
- Dump the yaml of a live object that does not contain the ***kubectl.kubernetes.io/last-applied-configuration*** annotation to a file (e.g. kubectl get pod <some pod> -o yaml > pod.yaml
- Remove any field from the file you just created
- Run kubectl diff -f pod.yaml (this generates no diff/output)
- Run kubectl apply -f pod.yam (this removes the field, even if the diff showed no changes)

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", 
GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Irrelevant
- OS (e.g: `cat /etc/os-release`):
Tested with mac and linux

**Comment by rsafonseca** [comment]
I forgot to add, running kubectl apply with dry run also produces an incorrect representation of the final object, it doesn't account for the field removal, but doing a non-dry run execution removes it

**Comment by sftim** [comment]
Can you specify the exact commands and inputs that let you reproduce this problem @rsafonseca ? (you might need to make a new sample manifest / apply intent in order to answer my question)

**Comment by ardaguclu** [comment]
`kubectl.kubernetes.io/last-applied-configuration` annotation is crucial for client side apply. Therefore, `kubectl diff` calculates diff by using this annotation. If it is removed, then that would be not possible to calculate diff.
On the other hand, server side apply does not rely on `last-applied-configuration`, which means that if your resources are applied using server side apply, `kubectl diff --server-side` will still calculate patches without last applied configuration annotation.

These are all working as designed, thereby I'm closing this issue. Feel free to re-open it, if you think I'm missing something.

/close
