### ISSUE TITLE
Enable wide output per configuration or environment variable

### ISSUE THREAD

**Issue by eht16** [kubernetes/kubectl#1404]
**What would you like to be added**:
A configuration option or environment variable that when set enables the wide output of `kubectl get pods` and `kubectl get deploy` as if they were called with `-o wide`.

I don't have any preference if it would be an option in the configuration (e.g. `~/.kube/config`) or if it can be enabled by defining an environment variable. Both would equally comfortable for me.

**Why is this needed**:
In my daily use, I usually need the wide output of `kubectl get pods` and `kubectl get deploy` in most cases. So it would be handy to have the wide output enabled per configuration and not to be requested via command line option.

**Comment by ardaguclu** [comment]
Kuberc would definitely solve that issue. WDYT? @mpuckett159

**Comment by mpuckett159** [comment]
Yeah agreed this would be covered by the [kuberc KEP](https://github.com/kubernetes/enhancements/issues/3104).
