### ISSUE TITLE
Wrong kubectl diff command sometimes exit with code 1 (same as when diff is found)

### ISSUE THREAD

**Issue by maingoh** [kubernetes/kubectl#1408]
**What happened**:

The doc says:
```
Exit status: 0 No differences were found. 1 Differences were found. >1 Kubectl or diff failed with an error.
```

But it seem the parser still exit with 1 in some cases:
```
$ kubectl diff -f; echo $?
Error: flag needs an argument: 'f' in -f
See 'kubectl diff --help' for usage.
1

$ kubectl diff -k; echo $?
Error: flag needs an argument: 'f' in -f
See 'kubectl diff --help' for usage.
1

$ kubectl diff; echo $?
error: must specify one of -f and -k
2
```

When command is built dynamically we cannot differenciate wether a diff has been found or the command line is invalid.

**What you expected to happen**:

Make sure exit code 1 is only when a diff is found.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16-gke.1100", GitCommit:"822bbca3cfca1ac13d8c759cc72496ffd10b5f59", GitTreeState:"clean", BuildDate:"2023-02-02T09:48:18Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: gcp
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by akash-kumar-saw** [comment]
Hi @maingoh,

I Highly feel that you are writing the command wrong.

```bash
kubectl diff -f FileName
```
Instead of **FileName** provide the filename, directory, or URL to files contains the configuration to diff.

**Comment by maingoh** [comment]
Hello @akash-kumar-saw 

I am indeed writing the command wrong but this is the issue in my opinion: wether we write the command wrong or write it valid it can return the same exit code (when a diff is found). 

When the command is wrong it should return > 0. 

Related to https://github.com/kubernetes/kubectl/issues/707

**Comment by ankritisachan** [comment]
Hi, it seems the issue was fixed via https://github.com/kubernetes/kubernetes/pull/105445. 
Please consider upgrading to a newer version >= v1.23 probably for the correct output. Thanks!
