### ISSUE TITLE
`port-forward` connects to a terminating Pod resulting in connection refused

### ISSUE THREAD

**Issue by Stausssi** [kubernetes/kubectl#1409]
**What happened**:

I am currently working on deploying (via GitHub Actions) my Pod containing a Mosquitto MQTT Broker to AKS. After deploying and restarting the deployment (`kubectl rollout restart` followed by `kubectl rollout status`) I forward the port (`8883`) to the host (GitHub Actions) via `kubectl port-forward --namespace FOO deployment/my-deployment 8883`. The forwarding itself seems to work (log shows `Forwarding from 127.0.0.1:8883 -> 8883`). However, after trying to connect to the MQTT Broker with a Python script in the following script I'm presented with the following error message:

```
Handling connection for 8883
E0412 13:45:28.732463    5301 portforward.go:407] an error occurred forwarding 8883 -> 8883: error forwarding port 8883 to pod b798c6533243dca30d0b804c889acc704b815fce8a0e0ba69f300772c0a4e3be, uid : failed to execute portforward in network namespace "/var/run/netns/cni-6baa8d42-9438-5c94-d16a-e2d5b2cb8398": failed to connect to localhost:8883 inside namespace "b798c6533243dca30d0b804c889acc704b815fce8a0e0ba69f300772c0a4e3be", IPv4: dial tcp4 127.0.0.1:8883: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found 
E0412 13:45:28.732780    5301 portforward.go:[233] lost connection to pod
```

The logs of the MQTT Broker itself show no connection attempt.

Additionally, if I execute `kubectl get pod --namespace FOO` just after restarting the Deployment, I'm presented with two Pods. The first one has the status ``TERMINATING`` while the second one is ``RUNNING``. 

If I wait for the ``TERMINATING`` Pod to actually terminate, the `port-forward` works fine and I can connect to the broker.

**What you expected to happen**:

Either `kubectl port-forward` chooses the running Pod to connect to, or `kubectl rollout status ` waits for ``TERMINATING`` Pod to actually terminate, thus allowing a connection to the broker inside the Pod from outside the AKS network.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a GitHub workflow using `azure/k8s-deploy@v4` to deploy a Pod containing at least a Mosquitto MQTT Broker (`docker.io/library/eclipse-mosquitto:latest`) with a `startupProbe` for the TCP socket and exposed port (default for MQTT is `1883`) inside a namespace `FOO`
2. In the step following `azure/k8s-deploy@v4` restart the Pod using `kubectl rollout restart` with namespace and deployment information.
3. Wait for the deployment via `kubectl rollout status --namespace FOO deployment/my-deployment`. Confusingly, this should log something along the lines of `Waiting for deployment [...] rollout to finish: 1 old replicas are pending termination...`
4. Ensure two Pods are running in the deployment via `kubectl get pods --namespace FOO`
5. Directly afterwards, execute `nohup kubectl port-forward --namespace FOO deployment/my-deployment 1883 &> forward.log &`. `nohup` and `&` are necessary for the process to keep running in the background.
6. Try connecting to the port. For testings sake, `curl localhost:8883` is sufficient.
7. Print the log of `port-forward`, e.g. with `cat forward.log`

**Anything else we need to know?**:

I can assure of the following:
1. The `port-forward` itself and the following connection to the broker runs without issues if the Pod is not restarted beforehand (or if there is only one Pod running in the deployment)
8. The MQTT port `8883` is exposed in the deployment spec
9. The credentials used to connect to the broker are correct
10. The MQTT container has a `startupProbe` waiting for a `tcpSocket` on `8883`
11. The error ``IPv6 dial tcp6: address localhost: no suitable address found`` is not related to the problem at hand; If there is just one Pod running, the same command (`port-forward`) works without any issues

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-30T18:18:41Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AKS running on Azure, GitHub actions running on a custom runner based on the ubuntu runner (see OS).
- OS (e.g: `cat /etc/os-release`): 
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -r
5.15.0-1035-azure
```

**Comment by brianpursley** [comment]
I was able to reproduce it.  Thank you for the excellent detail, @Stausssi 

It is timing-sensitive, in that you need to run `kubectl port-forward` quickly after `kubectl rollout restart`.  The code that determines which pod from the deployment to use doesn't consider whether the pods have a deletion timestamp or not, and it prefers pods that are older, which is why it is choosing the terminating pod.

/triage accepted

**Comment by Stausssi** [comment]
Glad to see you were able to reproduce and fix it!

In the meantime, I managed to work around this issue by only allowing one replica of the Pod and waiting for the successful termination before starting the new Pod
