### ISSUE TITLE
Allow to use external kustomize binary as subcommand of kubectl

### ISSUE THREAD

**Issue by MalKeshar** [kubernetes/kubectl#1412]
kubectl always ship outdated version of kustomize. As outcome it didn't allow to use some functionality.
```
$ kubectl kustomize 
error: json: unknown field "additionalValuesFiles"
```
I didn't find any methods to ask kubectl to use external binary
Possible solutions:
* Embed kustomize for backward compatibility, but allow to override it and call external binary instead of.
F.e. allow change behavior via config or system variables. Or check availability of kustomize binary in the PATH on the start 
* Remove kustomize completely and allow to install it as external plugin
I checked, kubectl now ignores kubectl-kustomize binary

I know that it's possible run kustomize binary by itself, but why do we need kustomize subcommand in kubectl then?

Btw, if you suffered from this as I, you can use shell wrapper as  workaround

Create script with kubectl name
```
#!/bin/bash

if [ "$1" == "kustomize" ]; then
  shift
  kustomize build "$@"
else
  /usr/local/bin/kubectl "$@"
fi
```

**Comment by marckhouzam** [comment]
> I checked, kubectl now ignores kubectl-kustomize binary.

As a workaround you could call the plugin binary something like `kubectl-kustom` and then call `kubectl kustom ...`

**Comment by natasha41575** [comment]
> We discussed this during bug scrub and don't think there's any action to take here. The version shipped with kubectl is documented and part of the kubectl version output.

I'm inclined to agree. I'm not sure that I understand how having `kubectl` to shell out to a specific kustomize binary has any benefits over using the standalone kustomize binary itself. Why do you need a shell wrapper instead of just always calling `kustomize build`?

**Comment by MalKeshar** [comment]
If you don't see any reason for allowing using latest kustomize version within kubectl utiliy then I suggest closing this issue. I aware of standalone binary and we will switch to using it.
