### ISSUE TITLE
kubectl completion powershell doesn't work with CompletionPredictor 

### ISSUE THREAD

**Issue by shellwhale** [kubernetes/kubectl#1415]
**What happened**: The [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor) module does not work with the `kubectl` completion script generated by the `kubectl completion powershell` command. Predictive completion does not work for `kubectl` commands.

**What you expected to happen**: Predictive completion should work for `kubectl` commands after importing the `CompletionPredictor` module and generating the kubectl completion script.

**How to reproduce it (as minimally and precisely as possible)**:
1. Import the `CompletionPredictor` module with `Import-Module -Name CompletionPredictor`
2. Set the `PredictionSource` option to `HistoryAndPlugin` with `Set-PSReadLineOption -PredictionSource HistoryAndPlugin`
3. Generate and execute the kubectl completion script with `kubectl completion powershell | Out-String | Invoke-Expression`
4. Type a `kubectl` command and try to use predictive completion.

**Anything else we need to know?**: None.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: v1.25.4
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows 10

**Comment by eddiezane** [comment]
I think we should track this upstream in cobra.

https://github.com/spf13/cobra/issues/1949

/close
