### ISSUE TITLE
`kubectl proxy --accept-hosts` appears to filter destination, not source.

### ISSUE THREAD

**Issue by wrossmann** [kubernetes/kubectl#142]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version**:
- Client: v1.8.3
- Server: v1.7.8-gke.0

**Environment**:
- **Cloud provider**: Google [GKE]
- **OS**:
    - Client: CentOS 6/7 [client]
    - Server: cos-stable-61-9765-66-0
- **Install tools**: gcloud

**What happened**:
In my development VM [10.0.1.100] I started kubectl proxy to provide full access to the Dashboard UI to my workstation [10.0.2.200], but not everyone else in the office. The command used was:

    kubectl proxy --port=8080 --address=10.0.1.100 --accept-hosts='^10\.0\.2\.200$'

as well as many variants of the regular expression with/without `\.`, `^`, and `$`

Which yielded the following for all endpoints:

    <h3>Unauthorized</h3>

It was suggested in the `#kubernetes-users` Slack channel that it may be running the regex against a hostname, but I've double-checked and we do not have reverse lookups enabled for our network, and I don't think that `kubectl` would be looking up NetBIOS info.

It can be made to work with `--accept-hosts='^.*$'` as you would expect, however I also decided to try `--accept-hosts='^10\.0\.1\.100$'` on a hunch, which ended up working the same as the wildcard, allowing *anyone on the network* access to the proxy.

**What you expected to happen**:

1. `--accept-hosts='^10\.0\.2\.200$'` should allow *only* the stated IP access to the proxy.
    - actual: universal inaccessibility
2. `--accept-hosts='^10\.0\.1\.100$'` should allow only local requests, similar to the `127.0.0.1` defaults.
    - actual: open access to all

**How to reproduce it**:

With two hosts attached to the same network:
- Host A: `kubectl proxy --port=8080 --address=HOST_A_IP --accept-hosts='^HOST_B_IP$'`
- Host B: `curl http://HOST_A_IP:8080/`

**Anything else we need to know**:

This has wider implications than me simply being paranoid about my local network. In searching for solutions to this problem I found pages upon pages of people stating `--accept-hosts='^.*$'` and `--disable-filter=true` as general solutions, even in the face of machines with public-facing interfaces. The supposed workarounds for this issue are causing people to unwittingly expose very sensitive information and APIs to potentially the entire world unless they take additional action to prevent it, eg: firewall rules.

eg: See the discussion in https://github.com/kubernetes/dashboard/issues/692

**Comment by apelisse** [comment]
I don't know who knows about proxy. @liggitt ?
