### ISSUE TITLE
Please don't ignore bug reports

### ISSUE THREAD

**Issue by schlichtanders** [kubernetes/kubectl#1420]
**What would you like to be added**:
There a many issues on kubectl where people reported valid bug reports, which then became rotten by fejta-bot.

Here is one example I just run into: https://github.com/kubernetes/kubectl/issues/555. There never was a single real response from someone from kubectl, but nevertheless it got rotten and closed.

Such policies which simply ignore bug reports by default if no one finds time to look into them are probably worth changing.
Suggestion: block issues from being rotten when they are in the initial stage "Needs Triage". 

**Why is this needed**:
A software which does not care about bug reports is not to be recommended for production use. Still I think kubectl is actually intended for being used in production.

**Comment by eddiezane** [comment]
We made some changes to the bot last year https://groups.google.com/a/kubernetes.io/g/dev/c/PAWC56nUWJY/m/ns8E51bLAAAJ but the reality is as the bot says,

> The Kubernetes project currently lacks enough active contributors to adequately respond to all issues and PRs.

A 5 year old issue is ~15 releases of Kubernetes. The project sees hundreds of new issues being opened every week and it is difficult for us to keep up with all of them. The bot closes older ones and important ones usually rise back up.

> A software which does not care about bug reports is not to be recommended for production use. Still I think kubectl is actually intended for being used in production.

I understand you were frustrated with the issue you ran into but comments like this are unproductive. We certainly care about bug reports.

Kubernetes is an open source project and many of us are volunteers. If you or your employer are using Kubernetes in a production environment or even as a hobby, please consider joining us.

/close
