### ISSUE TITLE
kubectl create --idempotent would be great

### ISSUE THREAD

**Issue by guettli** [kubernetes/kubectl#1421]
**What would you like to be added**:

I would like to add `--idempotent` to `kubectl create`.

**Why is this needed**:

Up to now this pattern gets used often:

```
kubectl create secret generic foo \
    --from-literal=foo=bar --save-config \
	--dry-run=client -o yaml | kubectl apply -f -
```

Some days ago,  I needed to understand why this gets done this way: idempotency.

It would be much easier to understand if `kubectl` had an `--idempotent` options which applies the value, if it already exists.

Additionally it would be less error-prone.

Today I added `--kubeconfig` to the command. But I added it only to the first kubectl. This means it got applied to the wrong cluster :-(

**Comment by mpuckett159** [comment]
/close

We recognize that it not being obvious what cluster a kubectl command will be running against is a foot gun for kubectl, however this is not a method we would look to implement to reduce that problem. For this specific case I believe you could write a custom bash function to handle this more elegantly by doing a get to verify the object exists before doing the create and apply, if all you are trying to do is verify that the object exists first, or the opposite if you are trying to verify that the object does not exist first.

With respect to making calls to the wrong cluster, we are working on implementing a new KEP to implement an rc like file where users can create custom actions and aliases similar to bashrc files where you can set default flags and create aliases for commands. I can add this as a user story for the KEP.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/3104-introduce-kuberc

**Comment by danktec** [comment]
apply is the idempotent way to deploy a resource, if the resource does not exist, it will be created and if it already exists it will be left alone or updated.

Create is imperative and Apply is declarative.
