### ISSUE TITLE
kubectl --dry-run -validate isn't picking up label errors

### ISSUE THREAD

**Issue by soudamsu** [kubernetes/kubectl#1424]
**What would you like to be added**:
kubectl --dry-run -validate isn't picking up label errors, but where as applying these on cluster will reject incorrect labels

**Why is this needed**:
This will help us to validate prior to merging our PR's in git, so as to unblocking the argocd applying these yamls on to the cluster

**Comment by ardaguclu** [comment]
@soudamsu I think, `--dry-run=server` what you are looking for. Could you please try it?

**Comment by ardaguclu** [comment]
I think, `--dry-run=server` can be used for this and it is the recommended way. I'm closing this.

/close
