### ISSUE TITLE
Allow setting --all-namespaces as a namespace

### ISSUE THREAD

**Issue by non7top** [kubernetes/kubectl#1427]
**What would you like to be added**:
Continuing on [/kubernetes/kubernetes/issues/79678](/kubernetes/kubernetes/issues/79678)
Currently it is possible to set a namspace in context and that namespace is used by default. Please make it possible the --all-namespace to be set as a default namespace so that kubectl operates on all namespaces when this is set.

**Why is this needed**:
Right now there is an option to set a specific namespace to be used as default. Setting all namespaces to be the default should also be an option.

**Comment by ardaguclu** [comment]
Thanks for raising this issue @non7top 

Although I'd not recommend setting `--all-namespace` as default, new feature kuberc (https://github.com/kubernetes/enhancements/issues/3104) can be used to set default flags for commands(possibly including `--all-namespace`), when it is released.

I'm closing this issue, since kuberc will automatically support the request in here.

/close

**Comment by non7top** [comment]
> Although I'd not recommend setting `--all-namespace` as default, 

yeah, that is why I raised this request. I don't want anything like that to be a default. But if I want to set exactly that way for my current context, I'd like to be able to do that. kuberc options will totally defeat this purpose as they will become global always-on enforced options.


> new feature kuberc ([kubernetes/enhancements#3104](https://github.com/kubernetes/enhancements/issues/3104)) can be used to set default flags for commands(possibly including `--all-namespace`), when it is released.

this will be exactly what is discouraged in [/kubernetes/kubernetes/issues/79678](https://github.com/kubernetes/kubernetes/issues/79678).

But yeah, I guess I will just have to do some more hacks and aliases to make things work.
