### ISSUE TITLE
kubectl exec breaking while running the php seeding command

### ISSUE THREAD

**Issue by 123Blessed** [kubernetes/kubectl#1429]
**What happened**: I am using trying to set up github action to deploy to GKE. while deployong it keep breaking on the following command. " kubectl exec deploy/medsitter-command -c medsitter-web-edition -- php artisan migrate:fresh --seed" with exit code 137.
I try to increased memory resources on the pods as well as increasing php memory limit but it keep failing. I don't believe it's a OOM issue at this point.

**What you expected to happen**: I expected the deployment to GKE to be successful by deploying to one container, then php migration, and then deploy to another container.
I also notice that the issue is only happening with the php seeding command because when I use  "kubectl exec deploy/medsitter-command -c medsitter-web-edition -- php artisan inspire", the deployment is successful.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: I also notice that it break at this part of the migration.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
[logs_442.zip](https://github.com/kubernetes/kubectl/files/11491339/logs_442.zip)

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.13-gke.500", GitCommit:"32ffda74dbad40622a077c20f274104038d6dd7f", GitTreeState:"clean", BuildDate:"2023-04-19T09:31:53Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1

- Cloud provider or hardware configuration: GCP

- OS (e.g: `cat /etc/os-release`):  
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Attached is the log file from most recent deployment using Github action

**Comment by brianpursley** [comment]
This seems like it might be coming from the command being executed and not with `kubectl exec` itself.

I don't know much about php, but a quick search shows that it could be one of these things:

* a php memory limit config setting https://stackoverflow.com/a/74134524/5074828 - Could it be OOM from php itself, and not from the pod?
* a timeout error https://stackoverflow.com/a/57674930/5074828

**Comment by mpuckett159** [comment]
/close

There may be some confusion here regarding the source of the exit code. When you run kubectl exec, it will return the exit code from the binary it is running within the container, so the 137 exit code (process is using too much memory) is coming from the container you are running the exec command within.

For now this appears to be a PHP issue and not a kubectl one. If there is more evidence that this is a kubectl issue please reopen the case and we can investigate further.
