### ISSUE TITLE
`externalize` argument: easily move services to the outside of a Kubernetes application

### ISSUE THREAD

**Issue by peterbecich** [kubernetes/kubectl#1434]
**What would you like to be added**:

Suggestion: an argument which automatically moves a service outside of Kubernetes, onto the host machine

It might look like this:

```
kubectl apply -k ./ --externalize service-2
```

which would modify the Kubernetes application from the upper diagram to the lower diagram.

![dQPzS](https://github.com/kubernetes/kubectl/assets/6315338/b2a14c04-f089-4a62-9a16-7e6face96c52)

Furthermore, this should be usable for any subset of the services, i.e.:

```
kubectl apply -k ./ --externalize service-2 --externalize service-3
```

I understand that the configuration of a Kubernetes application will specify all of the links between services: DNS names, port forwards, etc.

Today, these links can be manually re-configured to point outside of the application. i.e. a `Service` is reconfigured to be an `ExternalName`.

Could `kubectl` support a feature that does this automatically? And be transparent to the services?

**Why is this needed**:

This supports fast development iteration of a service, outside of a container, on the host system. A developer can quickly re-compile their work on the host system. I am aware of products which assist this; my understanding is these workflows are containerized.

My colleagues wrote a helper script to do this for our Kubernetes application. The application included a handful of microservices under development, plus database and other supporting services. Any subset of the microservices under development could be quickly set to run outside of Kubernetes, without requiring the developer to alter any of the Kubernetes configuration manually. I feel it would be immensely useful to generalize this feature to any service(s) in any Kubernetes application.

Thank you

**Comment by Ritikaa96** [comment]
Seems like a developer friendly approach. the [@kubernetes/sig-cli-feature-requests](https://github.com/orgs/kubernetes/teams/sig-cli-feature-requests) might be good to raise your feature request to.
[Here](https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md#feature-requests) is the link for info on how feature requests can be raised. Good luck!

**Comment by mpuckett159** [comment]
/close
This sounds like a really interesting idea but I believe that it is outside the goals of the kubernetes project in general. After some discussion in the bug scrub, this is a cool approach, and sounds like a really valuable workflow and idea, however, in this is something that seems like a good add on to kubernetes, as evidenced by the fact that your co-worker developed a helper script to accomplish this task.

**Comment by peterbecich** [comment]
@mpuckett159 , thank you for feedback. So I could implement this as an Kubernetes Addon like https://kubernetes.io/docs/concepts/cluster-administration/addons/ which would provide this feature in `kubectl`?

**Comment by dfsdevops** [comment]
I think I may be one of the colleagues that @peterbecich is referring to. We did something like this with a custom Job that deleted itself for local docker desktop where host.docker.internal would route back to the local network, but I could also see this being useful in other situations in cloud environments where you are running services that are directly routable, need to quickly triage something on an instance or something. It almost seems like `kubectl expose` could do it, it even lets you use `type: ExternalName`, but it sadly doesn't allow you to specify the externalName or update existing services. It seems like a limited extension of the scope of `kubectl expose`.

**Comment by mpuckett159** [comment]
Sorry I meant plug-in not add on.

https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
