### ISSUE TITLE
kubectl logs -A

### ISSUE THREAD

**Issue by guettli** [kubernetes/kubectl#1438]
**What would you like to be added**:

I would like to add the option `-A` (--all-namespaces).

Most other kubectl subcommands have this option.

**Why is this needed**:

I would like to get all logs (from all namespaces) from the last N minutes.

**Comment by Ritikaa96** [comment]
/sig cli
/area kubectl
It will also be better to take the opinion of sig experts regarding this to get it's triage accepted.

**Comment by guettli** [comment]
@sbdtu5498 will you ask in #sig-cli? Please mention me, too. Thank you

**Comment by sbdtu5498** [comment]
@guettli sure thing!

**Comment by mpuckett159** [comment]
/close
I checked some of the plugins that are available via krew and found [stern](https://github.com/stern/stern). It is a plugin that could handle this feature for you. We believe this would be best served as a plugin at this stage. Please let me know if this is an acceptable solution for your use case.

**Comment by guettli** [comment]
@mpuckett159 of course I could use Go (or the krew plugin stern) and help myself. But I still think it would be convenient if `kubectl log` would have the `-A` option like other kubectl sub-commands have it.
 
 I don't have time to implement it in the next weeks. But maybe someone else has time.
 
 @mpuckett159 If there is a motivated developer, is it likely that a PR would get accepted?
