### ISSUE TITLE
Debug profiles don't remove startup probe on pod copy

### ISSUE THREAD

**Issue by macostea** [kubernetes/kubectl#1440]
**What happened**:
When using `kubectl debug` with any of the profiles that don't copy labels and probes, the copied pod will still have a startup probe.

**What you expected to happen**:
When using debug profiles that remove labels and probes I expect all labels and probes to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod that has a startupProbe
2. `kubectl debug -it myapp --copy-to=myapp-debug --profile=general -- bash`

**Anything else we need to know?**:
Looks like only liveness and readiness probes are removed:
https://github.com/kubernetes/kubectl/blob/81c007005029fcac8aaf15936c0a07ec3ad00d11/pkg/cmd/debug/profiles.go#L215-L221

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): client: 1.27.2, server 1.25.9
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.2 LTS

**Comment by ardaguclu** [comment]
Agree, seems like a bug;
/triage accepted
/priority backlog
