### ISSUE TITLE
Link `k8s.io/kubectl` 404's 

### ISSUE THREAD

**Issue by userbradley** [kubernetes/kubectl#1447]
**What happened**:

Checking the link `k8s.io/kubectl` on the README goes to a 404 page on the site 

**What you expected to happen**:

Goes to the Kubectl page on the k8s site

**How to reproduce it (as minimally and precisely as possible)**:

Navigate to `https://k8s.io/kubectl`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

I am happy to update this, provided someone tell me where to fix it

**Comment by Ritikaa96** [comment]
@userbradley Are you talking about these:

> The **k8s.io/kubectl** repo is used to track issues for the kubectl cli distributed with **k8s.io/kubernetes**. It also contains packages intended for use by client programs. E.g. these packages are vendored into k8s.io/kubernetes for use in the [kubectl](https://github.com/kubernetes/kubernetes/tree/master/cmd/kubectl) cli client. That client will eventually move here too.

**Comment by Ritikaa96** [comment]
it is talking about **https://github.com/kubernetes/kubectl** and **https://github.com/kubernetes/kubernetes** i.e. github repos.

If it is confusing you can change that in the README file itself.
Please read [this](https://github.com/kubernetes/kubectl/blob/master/CONTRIBUTING.md) before  making a contribution.
