### ISSUE TITLE
kubectl wait --for=condition=Ready pod failing due to pod moving to fast from Container Creating to Completed

### ISSUE THREAD

**Issue by kalib** [kubernetes/kubectl#1451]
**What happened**:
When deploying a job to my cluster I am using a script that will deploy that job with a helm chart and the script will wait until the job is Ready/Running so it can start reading the logs.

So I have:

`
echo "Waiting for the job to start..."
    kubectl wait --for=condition=Ready pod my-pod-name -n my-namespace --timeout=60s
    ret_code=$?
    if [ $ret_code != 0 ]; then
        echo -e "failed to deploy"
        exit $ret_code
    fi

    echo "Pod deployed, reading logs..."
    log_file="/tmp/mylog.logs"
    kubectl logs -f -l job-name=my-pod-name -n my-namespace | tee $log_file
`
As I watch my job, I can that it actually runs, it finishes the task it's supposed to, but the deployment is so fast, that it feels like it moves from Pending to ContainerCreation, and from Container Creation to Completed directly, without ever going to Ready/Running state, so my wait is there hanging waiting for it to become Ready, when the job is in fact already completed. So it hangs until it times out after the timeout I specified.

**What you expected to happen**:
It was expected to meet the condition once the job is Ready.

**How to reproduce it (as minimally and precisely as possible)**:
Using the script a listed above for example.

As a job to test it, a simple sleeper.yaml job did it for me. Sometimes it worked, others it hanged as decribed above until it times out:

`
apiVersion: v1
kind: Pod
metadata:
  name: sleeper
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep 10" ]
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-a5565ad", GitCommit:"23f44c7dd4e8e23856387345e7cb80bf0f93ced6", GitTreeState:"clean", BuildDate:"2023-06-15T21:19:39Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS - EKS
- OS (e.g: `cat /etc/os-release`): OS X Ventura 13.3.1

**Comment by mpuckett159** [comment]
This could be a very complex issue but before we get into that, can you resolve this by running the following instead?
`kubectl wait --for=condition=complete pod my-pod-name -n my-namespace --timeout=60s`

**Comment by ardaguclu** [comment]
As we discussed this in our last cli bi-weekly; only improvement we can do is adding  a union of conditions capability such as `--for=condition=complete|ready`, other than that I'd suggest trying the command above.
I'm closing this issue. Feel free to re-open it, if I'm missing something. Thanks.

/close
