### ISSUE TITLE
kubectl diff/ apply secret does not remove key

### ISSUE THREAD

**Issue by IvoGoman** [kubernetes/kubectl#1453]
**What happened**:
I have created a secret from kubectl `kubectl create secret generic data-secret --from-literal=firstEntry=first --from-literal=secondEntry=second`. 
Edited the yaml of this secret to remove **firstEntry** and wanted to see the change with `kubectl diff --server-side` or even `kubectl apply -f --dry-run=server -o yaml`
However, the diff is empty and the apply shows both keys. Also the apply without dry-run does not change the secret.

**What you expected to happen**:
I have expected that the diff shows that **firstEntry** gets removed and that the apply also shows the key as removed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the secret`kubectl create secret generic data-secret --from-literal=firstEntry=first --from-literal=secondEntry=second`

2. Get the yaml representation `kubectl get secret data-secret -o yaml > test.yaml`
3. Remove the data entry **firstEntry** from the test.yaml
4. Run `kubectl diff  -f test.yaml --server-side=true` => no diff
5. Run `kubectl apply -f test.yaml --dry-run=server -o yaml` => shows both initial data entries

**Anything else we need to know?**:
I have looked for similar issues but only found one similar issue with secrets using stringData [kubernetes#89938](https://github.com/kubernetes/kubernetes/issues/89938). I am opening a new issue since the mentioned issue explicitly says the issue is with stringData.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:38:14Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/arm64"}
```
- Cloud provider or hardware configuration:
Kind Cluster
- OS (e.g: `cat /etc/os-release`):
MacOS 13.4.1

**Comment by sftim** [comment]
I think Kubernetes server-side apply is working as designed. Not sure about the `kubectl diff`, though.

**Comment by mpuckett159** [comment]
/close
It is important that you do not mix imperative (create) and declarative (apply) commands. Please see more details [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/) for a text document detailing the issues this can cause.

**Comment by IvoGoman** [comment]
Fair point, when using the declarative approach to create the secret it shows the expected diff for a server-side apply dry-run.

The `kubectl diff` output does not seem right to me though.

Example:
1. `kubectl create secret generic data-secret --from-literal=firstEntry=first --from-literal=secondEntry=second --dry-run -o yaml > test.yaml`, then `kubectl apply -f test.yaml`
2. Remove _secondEntry_ from the test.yaml
    ```
    kubectl diff  -f test.yaml --server-side=true
    diff -u -N /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/LIVE-1631383948/v1.Secret.default.data-secret /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/MERGED-1965381926/v1.Secret.default.data-secret
    --- /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/LIVE-1631383948/v1.Secret.default.data-secret	2023-08-17 09:03:52
    +++ /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/MERGED-1965381926/v1.Secret.default.data-secret	2023-08-17 09:03:52
    @@ -6,7 +6,7 @@
     metadata:
       annotations:
         kubectl.kubernetes.io/last-applied-configuration: |
    -      {"apiVersion":"v1","data":{"firstEntry":"Zmlyc3Q=","secondEntry":"c2Vjb25k"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"data-secret","namespace":"default"}}
    +      {"apiVersion":"v1","data":{"firstEntry":"Zmlyc3Q="},"kind":"Secret","metadata":{"creationTimestamp":null,"name":"data-secret","namespace":"default"}}
       creationTimestamp: "2023-08-16T23:05:52Z"
       name: data-secret
       namespace: default
    ```
    Expected: The diff shows that _second entry_ was removed and all secret data should be redacted
    Actual: The diff only shows the diff in the `kubectl.kubernetes.io/last-applied-configuration` annotation but not in  the _data_. Also the diff shows secret data in plain text.

3. Add a third entry to the secret's `data`
   ```
    kubectl diff  -f test.yaml --server-side=true
    diff -u -N /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/LIVE-2228163381/v1.Secret.default.data-secret /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/MERGED-4045884020/v1.Secret.default.data-secret
    --- /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/LIVE-2228163381/v1.Secret.default.data-secret	2023-08-17 09:04:44
    +++ /var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/MERGED-4045884020/v1.Secret.default.data-secret	2023-08-17 09:04:44
    @@ -2,11 +2,12 @@
     data:
       firstEntry: '***'
       secondEntry: '***'
    +  thirdEntry: '***'
     kind: Secret
     metadata:
       annotations:
         kubectl.kubernetes.io/last-applied-configuration: |
    -      {"apiVersion":"v1","data":{"firstEntry":"Zmlyc3Q=","secondEntry":"c2Vjb25k"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"data-secret","namespace":"default"}}
    +      {"apiVersion":"v1","data":{"firstEntry":"Zmlyc3Q=","secondEntry":"c2Vjb25k","thirdEntry":"c2Vjb25k"},"kind":"Secret","metadata":{"creationTimestamp":null,"name":"data-secret","namespace":"default"}}
       creationTimestamp: "2023-08-16T23:05:52Z"
       name: data-secret
       namespace: default
  ```
  Expected: diff shows that a new entry in _data_ was added and this change is redacted.
  Actual: diff shows the redacted change of adding the new value in _data_. However, the diff in the `kubectl.kubernetes.io/last-applied-configuration` shows the secret without redaction.

 @mpuckett159 could you reopen the issue as part of my question w.r.t. the diff is still open:
- `kubectl diff` does not show a diff for a secret if an entry in data is removed
- `kubectl diff` does not redact secret data in `kubectl.kubernetes.io/last-applied-configuration`

**Comment by IvoGoman** [comment]
@ardaguclu I checked everything with `kubectl diff --server-side=true`
> --server-side=false:
	If true, apply runs in the server instead of the client.

**Comment by ardaguclu** [comment]
But once you execute this imperative command `kubectl create secret generic data-secret --from-literal=firstEntry=first --from-literal=secondEntry=second --dry-run -o yaml > test.yaml` you have already created last-applied-annotation and entered the client-side apply tunnel. What about even creating the resource via `kubectl apply --server-side` and run `kubectl diff --server-side`?

**Comment by IvoGoman** [comment]
Yes shows the intended result 🙈  Thank you for the explanation 💯
