### ISSUE TITLE
`kubectl delete deploy,ns -n foo  --all` deletes all namespaces

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubectl#1461]
### What happened?

`kubectl delete deploy,ns -n foo --all` deleted all namespaces
which in theory could be know, but is very unexpected

### What did you expect to happen?

to either fail and say "namespaces are not namespaced!" or noop since no namespace has this namespace

### How can we reproduce it (as minimally and precisely as possible)?

- create 2 namespaces
- delete one of them with `kubectl delete deploy,ns -n foo  --all`
- verify it other still exists

### Anything else we need to know?

Basic bug seems to be that `get ns -n foo` returns all namespaces, so that could be a way to solve this.
Only patching `namespaces` to be 1-off protected would be good but not help other things like clusterrole (and similar) when users don't know they are namespaced and then break a whole cluster by accident.

### Kubernetes version

1.27

### Cloud provider

local

### OS version

NA

### Install tools

NA

### Container runtime (CRI) and version (if applicable)

NA

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NA

**Comment by Ritikaa96** [comment]
@cben added many good ideas [here](https://github.com/kubernetes/kubernetes/issues/75706#issuecomment-560386534).
I'd like to add something , don't know if it is good or not.
- Adding a warning before deleting resources might be a good start. for eg.
``` console
$ kubectl delete po,ns foo --all
Are you sure you want to delete NUMBER_OF_RESOURCES ? Yes/No
```
this will give the user a slight idea that something is going wrong. and will be as per this statement:




> "this behavior must be preserved for backwards compatibility" ... I think mostly because namespace can be set globally and then suddenly `get node` would stop working facepalm

**Comment by Ritikaa96** [comment]
I think this is possible and in case this is accepted i would love to help with this issue. 
@kubernetes/sig-cli-feature-requests
@kubernetes/sig-cli-misc might be of help

**Comment by ardaguclu** [comment]
I think, there is not much thing we can do about this problem due to backwards compatibility and for these cases, we will suggest passing `--interactivity` flag for preview first https://github.com/kubernetes/enhancements/issues/3895

**Comment by Ritikaa96** [comment]
I understand this but in case user doesn't have idea of the `--interactivity` flag or it is done accidentally like many times in past issues it's been mentioned, then won't a small warning with options: YES/NO would be good?
Will it have a problem due to backward compatibility?

**Comment by ardaguclu** [comment]
> I understand this but in case user doesn't have idea of the `--interactivity` flag or it is done accidentally like many times in past issues it's been mentioned, then won't a small warning with options: YES/NO would be good? Will it have a problem due to backward compatibility?

Yes problem due to backwards compatibility. Moreover `--all` flag should be used cautiously and from the name itself tells this flag will delete all in the context you give. I think, it warns user in some sense.

**Comment by ardaguclu** [comment]
Thanks for raising this issue @grosser. As duplicates were closed already, I think we can close this one too. Because it is known and discussed several times.
/close

**Comment by grosser** [comment]
Could a KEP be successful for opt-in env flag "don't delete unnamespaced when namespace is give".
Because then backward argument does not count right ?
