### ISSUE TITLE
kubectl create namespace with annotations and labels

### ISSUE THREAD

**Issue by phoenix-bjoern** [kubernetes/kubectl#1465]
Rancher uses annotations and labels to assign new NS to a project and apply RBACs. As a user without cluster level API privileges for get/list namespaces you might be able to execute „kubelctl create namespace“ but then you won’t be able to access it. It would require to set annotations and labels so that the NS gets created within the Rancher project. 

Another approach is use „kubectl apply“ with a prepared YAML but that creates several errors as the user is not allowed to get/list/watch namespaces:

namespace.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    myannotation: test
  labels:
    mylabel: test
  name: my-new-namespace
```

`kubectl apply -f namespace.yaml` output in Rancher managed cluster:
```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "my-new-namespace", Namespace: ""
from server for: "namespace.yaml": namespaces "my-new-namespace" is forbidden: User "u-xyz" cannot get resource "namespaces" in API group "" in the namespace "my-new-namespace"
```

As of now the only proper approach is to use the Rancher UI/CLI to create a new namespace. 

I am sure there might be other use cases (like OPA) where setting annotations or labels right on namespace creation instead of applying the afterwards. 

For the described use case IMHO it would be best to extend „create namespace“ with additional parameters to set annotations and labels by a single command: `kubectl create namespace my-new-namespace --annotations="myannotation: test" --labels="mylabel: test"`

**Comment by mpuckett159** [comment]
/close
SIG CLI's policy is that we will not be extending the idempotent commands (e.g. create, here) and if users wish to create resources with more complex needs that they should be using declarative commands (apply) to create these resources. Additionally, users will require the necessary permissions to execute these commands.
