### ISSUE TITLE
Fix punctuation or reword the error message: "cannot delete Pods declare no controller"

### ISSUE THREAD

**Issue by wvxvw** [kubernetes/kubectl#1467]
```
cannot delete Pods declare no controller
```

Is a... broken English? What were you trying to say here? Please make this error message make sense.

This is found in `kubectl` 1.25, but I'm not sure it's coming from `kubectl` itself, maybe it's from somewhere else. But due to the incomprehensible nature of this message I cannot even begin to guess where this may come from.

NB. The complete error message might look something like this:

```
error: unable to drain node "node005" due to error:cannot delete Pods declare no controller (use --force to override):
```

So, the formatting is also broken (missing space after colon).

**Comment by Ithrael** [comment]
When you drain a node, if there are direct pods on that node (meaning the pods have no owner, such as pods generated by a deployment which have owners), this error will occur.

[        return MakePodDeleteStatusWithError(unmanagedFatal)](https://github.com/kubernetes/kubectl/blob/0266cec8bce880387a33c4d948673749defeb0bc/pkg/drain/filters.go#L244)
