### ISSUE TITLE
"kubectl describe" events query is too specific

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#147]
Right now if I run a command like `kubectl describe service foo -v=10` I see that the query to retrieve `Events` is like:

`I1120 14:07:00.770878   34700 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.8.2 (darwin/amd64) kubernetes/bdaeafa" https://35.192.225.48/api/v1/namespaces/doctor/events?fieldSelector=involvedObject.kind%3DService%2CinvolvedObject.uid%3D8c1f404b-ce32-11e7-b2c9-42010a8000f2%2CinvolvedObject.name%3Dlb-16%2CinvolvedObject.namespace%3Ddoctor`

To parse that `fieldSelector` out:
- involvedObject.kind=Service
- involvedObject.uid=8c1f404b-ce32-11e7-b2c9-42010a8000f2
- involvedObject.name=lb-16
- involvedObject.namespace=doctor

Are all these field selectors really necessary? I feel like `involvedObject.uid=8c1f404b-ce32-11e7-b2c9-42010a8000f2` would be sufficient?

I'm not sure how fieldSelectors works internally, or whether this whole thing needs to be sent over the wire for some reason (maybe altogether it forms the ObjectReference or something). I'm not sure if this has a performance burden on the API/etcd either. Just wanted to point out if it's an oversight and can be made more concise.

**Comment by apelisse** [comment]
@caesarxuchao Would you happen to know that, or someone who might now? Thanks

**Comment by nikhita** [comment]
/remove-lifecycle rotten

This still looks relevant.

/assign

**Comment by soltysh** [comment]
I'm leaving this closed, since for `kubectl describe`  I think this is fine. We will be adding a separate command for accessing events, see https://github.com/kubernetes/enhancements/issues/1440
