### ISSUE TITLE
Kubectl restart command without specific deployment will restart all deployments

### ISSUE THREAD

**Issue by maxy9** [kubernetes/kubectl#1474]
**What happened**:

I executed `kubectl --context <my-context> -n <my-namespace> rollout restart deployment` and all the deployments in the namespace performed a rolling restart.

**What you expected to happen**:

I would expect this to return an error stating that a specific deployment name is required.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a cluster and create more than 1 deployment.
1. Execute `kubectl --context <my-context> -n <my-namespace> rollout restart deployment`
1. Notice that all deployments perform a rolling restart.

**Anything else we need to know?**:

**Environment**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
- AWS EKS
- MacOS: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

**Comment by ardaguclu** [comment]
I think, it was intentionally designed that way but that would be better to add an example in the help text to mention this behavior.

**Comment by ldouchy** [comment]
Seems like a default behaviour that we do not find in other kubectl commands.


> I think, it was intentionally designed that way but that would be better to add an example in the help text to mention this behavior.

@ardaguclu Any idea where we can confirm this?

**Comment by Ithrael** [comment]
> I think, it was intentionally designed that way but that would be better to add an example in the help text to mention this behavior.

Yeah, Add an example similar to "kubectl get po".
<img width="1263" alt="image" src="https://github.com/kubernetes/kubectl/assets/38208715/c89bbac8-5204-4698-b1e0-67b223c9ab1d">

**Comment by ardaguclu** [comment]
Issue has been fixed;
/close
