### ISSUE TITLE
`kubectl wait --for=condition=Ready pod/abc` sometimes signals ready for pending POD

### ISSUE THREAD

**Issue by lcmgh** [kubernetes/kubectl#1477]
**What happened**:

`kubectl wait --for=condition=Ready pod/abc` sometimes resolves successfully even POD is in state pending _**according to**_ `kubectl port-forward` error message

I even tried executing 2. two times and it made the error appear less often but it still happens occasionally.

1.  `kubectl run random_pod_name --restart=Never --image=alpine/socat it --rm --port=$port --command -- -- timeout 8h socat tcp-listen:$port,fork,reuseaddr tcp-connect:$host:$port || true`
2. ``kubectl wait --for=condition=Ready pod/random_pod_name ``
3. `kubectl port-forward pod/random_pod_name $localport:$port`

Commands are triggered in a script so there is minimal waiting time between them.

**What you expected to happen**:

Port-forward to be only executed when pod is ready and not pending.

**Anything else we need to know?**:

**Environment**:
- Kubernetes v1.24 
- kubectl version:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255
```

**Comment by lcmgh** [comment]
Output from script: 
![image](https://github.com/kubernetes/kubectl/assets/98088021/3b3cf634-f163-4173-a0f2-23d011cf5f13)

You can see `kubectl wait` outputs its ready and 3 sec later `kubectl port-forward` says it is not.

**Comment by ardaguclu** [comment]
@lcmgh Thanks for opening this issue. There were some improvements in `kubectl wait` command in newer versions than 1.25. Is it possible to test this case in newer client?. Also could you please add a some kind of sleep between wait and port-forward commands to ensure that is it a timing issue or not?.

**Comment by brianpursley** [comment]
I'm going to go ahead and close this for now.  If the issue occurs with a newer version of kubectl, we can re-open.

**Comment by lcmgh** [comment]
> Also could you please add a some kind of sleep between wait and port-forward commands to ensure that is it a timing issue or not?.

I am currently executing the wait command twice. Colleague running on 1.28 on windows is still facing the same problem.
