### ISSUE TITLE
kubectl proxy doesnt support proxy-url

### ISSUE THREAD

**Issue by jwcesign** [kubernetes/kubectl#1478]
**What happened**:

Please see https://github.com/kubernetes/kubernetes/issues/120318

**What you expected to happen**:

Please see https://github.com/kubernetes/kubernetes/issues/120318

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Please see https://github.com/kubernetes/kubernetes/issues/120318

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by ardaguclu** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/120318;
/close
