### ISSUE TITLE
kubectl create service: ignores extra positional arguments

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#148]
See:

    $ kubectl create service loadbalancer --tcp=80:80 lb-1 lb-2 lb-3
    service "lb-1" created

it will silently ignore `lb-2` and `lb-3` arguments. If command takes exactly 1 positional argument, it should fail when executed command is not exactly 1.

**Comment by stewart-yu** [comment]
i will have a look  about it.

**Comment by apelisse** [comment]
Assigning to me since I can't assign @stewart-yu. Thanks for taking a look at it!
