### ISSUE TITLE
Compatibility of kubectl with goaway-chance  enabled k8s api server.

### ISSUE THREAD

**Issue by kaushiksrinivas** [kubernetes/kubectl#1480]
Hi Team,

This is with regard to this GOAWAY feature introduced within the kubernetes. 
_The goaway-chance option in the Kubernetes API server helps prevent HTTP/2 client connections from being stuck on a single API server instance, by randomly closing a connection. When the connection is closed, the client will try to reconnect, and will likely land on a different API server as a result of load balancing._

We wanted to understand below aspects regarding the same. 
1. Does kubectl support this feature ?
2.  We know that kubectl internally uses a go http client to interact with the api server. Is the error handling or retries when a goaway response is received managed within the kubectl client ? OR, Is the user who is invoking kubectl commands responsible for reacting with retry attempts in case a goaway response is received ?

**Comment by kaushiksrinivas** [comment]
Any information on this ?

**Comment by poornachandratejasvi** [comment]
from which version of kubectl if support goaway ?

**Comment by poornachandratejasvi** [comment]
Based on the K8s client-go REST request and net package, which is internally also used by kubectl as well so goaway will be handled.

kubectl Issue/Query: Compatibility of kubectl with goaway-chance enabled k8s api server. · Issue #1480 · kubernetes/kubectl · GitHub
Reference for handling in client-go request/net package: 
https://github.com/kubernetes/kubernetes/blob/b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d/staging/src/k8s.io/client-go/rest/request.go#L948
https://github.com/kubernetes/apimachinery/blob/4b14f804a0babdcc58e695d72f77ad29f536511e/pkg/util/net/http.go#L95
