### ISSUE TITLE
Allow `--labels` and `--annotations` options for every `kubectl create ...` subcommand

### ISSUE THREAD

**Issue by dionysius** [kubernetes/kubectl#1483]
**What would you like to be added**:
Add `--labels` and `--annotations` options to all/specific* `kubectl create` commands.

**Why is this needed**:
_Preamble: I wish this enhancement for all resources, I am just using the secrets as an example._
I recently stumbled upon a change in serviceaccounts, that since k8s 1.22 they don't automatically create token secrets.
> Versions of Kubernetes before v1.22 automatically created long term credentials for accessing the Kubernetes API. This older mechanism was based on creating token Secrets that could then be mounted into running Pods. In more recent versions, including Kubernetes v1.28, API credentials are obtained directly by using the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API, and are mounted into Pods using a [projected volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume).

[To currently create long-lived tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount) you'll need to write a full yaml:
> ```yaml
> kubectl apply -f - <<EOF
> apiVersion: v1
> kind: Secret
> metadata:
>   name: build-robot-secret
>   annotations:
>     kubernetes.io/service-account.name: build-robot
> type: kubernetes.io/service-account-token
> EOF
> ```

There exists so much to almost create a functioning oneliner:
```
$ kubectl create secret -n somenamespace generic build-robot-token --type kubernetes.io/service-account-token
error: failed to create secret Secret "build-robot-token" is invalid: metadata.annotations[kubernetes.io/service-account.name]: Required value
```

It would be really great, if we could add the required annotation directly. Because of the error, you can't use `kubectl annotate` as it **already blocks us from even creating the secret**. It would be really handy to just add the required annotation in the create command, for example:
```
$ kubectl create secret -n somenamespace generic build-robot-token --type kubernetes.io/service-account-token --annotations kubernetes.io/service-account.name=build-robot
```

While this was now an example for secrets, **labels and annotations are an integral part of every resource** - every resource needs/has the metadata object otherwise you couldn't even give a name to it. This is in my opinion a useful property for every resource and thus this enhancement request is asking for adding `--labels` and `--annotations` for every resource.

I see two possible criterias on where and how it can be added (* from above):

1. _all create commands_: Every `kubectl create` command has those two new options available. Pro: The options are tied to the `create` subcommand. Con: Every subcommand of `create` must be changed and now also read these properties and apply it to their implementation (or ignore it). Quirk: `kubectl create -f` probably should ignore those options, since you already have to define a full YAML and with it you can define the labels and annotations there.
2. _specific create subcommands_: If there is a subcommand to `create` - e.g. `create role`, `create secret`, `create job` and many more - those places should get also those `--labels` and `--anotations`. Pro: Only places where useful get those options. Con: All those places get those options so it is not centrally specified in `create` command. They all also have specific examples already specifying that they have custom options. To list a few:
```
  # Create a job from a cron job named "a-cronjob"
  kubectl create job test-job --from=cronjob/a-cronjob

  # Create a new secret named my-secret using a combination of a file and a literal
  kubectl create secret generic my-secret --from-file=ssh-privatekey=path/to/id_rsa --from-literal=passphrase=topsecret

  # Create a new config map named my-config with key1=config1 and key2=config2
  kubectl create configmap my-config --from-literal=key1=config1 --from-literal=key2=config2

  # Create a new ClusterIP service named my-cs (in headless mode)
  kubectl create service clusterip my-cs --clusterip="None"

  # Create a deployment named my-dep that runs the busybox image and expose port 5701
  kubectl create deployment my-dep --image=busybox --port=5701

  # Create an ingress with a default backend
  kubectl create ingress ingdefault --class=default \
  --default-backend=defaultsvc:http \
  --rule="foo.com/*=svc:8080,tls=secret1"
```

I'm leaning towards 2: Any create subcommand can benefit from allowing to set directly labels and annotations during creation.

Note: `kubectl run` command has those options (I inherited the naming of the options from there to keep it consistent):
```
      --annotations=[]: Annotations to apply to the pod.
  -l, --labels='': Comma separated labels to apply to the pod. Will override previous values.
```

**Comment by brianpursley** [comment]
We're hesitant to add new flags.  Using kubectl apply would be a better choice in this case.

See also this comment for a similar feature requested: https://github.com/kubernetes/kubectl/issues/1465#issuecomment-1681390198

Creating a kubectl plugin might be helpful if this is something you need frequently.  After kubectl version 1.27, kubectl allows plugins for subcommands of create, so this might be a good use case for that new functionality if you want to make a plugin for it.
