### ISSUE TITLE
Add `kubectl log` as an alias for `kubectl logs`

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubectl#1484]
### What would you like to be added?

It will be great if `kubectl log` could be added as an alias for `kubectl logs`.

### Why is this needed?

1. Most kubectl commands work as singular and plural for the resource name. It always confuses me which is the correct one for logs. I understand `logs` is the `verb` part.

2. I also use git which has commands like `git log --oneline`. I can never never when to use `log` and when to use `logs`.

**Comment by krmayankk** [comment]
you can also get the opinion on kubernetes.slack.com slack , on the channel #sig-cli

**Comment by Ritikaa96** [comment]
I think [this](https://github.com/kubernetes/community/blob/master/sig-cli/README.md#meetings) will be helpful as well. will recommend to join sig meeting today if you want to discuss this . please go through the [community page](https://github.com/kubernetes/community/blob/master/sig-cli/README.md) for more information.

**Comment by ardaguclu** [comment]
this can easily be managed via aliases and I doubt about the usefulness of this feature if we add it in kubectl. I'd prefer closing this issue.
