### ISSUE TITLE
 debug: ability to copy environment variables from source container (or specify envFrom=<configMap>)

### ISSUE THREAD

**Issue by nathanmcgarvey-modopayments** [kubernetes/kubectl#1486]
**What would you like to be added**:

The API accepts a "envFrom" parameter for ephemeral containers to set environment variables (E.g. from a config map).
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#ephemeralcontainer-v1-core

I'm suggesting either a `--env-from` parameter to the `kubectl debug` command be added that maps to that API field, or there is an option to copy environment variables from a source container to the debug/ephemeral container. 

**Why is this needed**:

Currently, `kubectl debug` does not copy, nor does it allow you to specify a "envFrom". When using environment variables to specify things like application parameters or database credentials or temporary tokens, it can make the debugging process both more difficult and less secure as an operator may manually start copy and pasting credentials/tokens/environment configurations around in terminals.

**Comment by nathanmcgarvey-modopayments** [comment]
Related in a similar though process (another missing CLI flag that exists in the API): https://github.com/kubernetes/kubectl/issues/1071

**Comment by ardaguclu** [comment]
I'm planning to propose custom profile https://github.com/kubernetes/kubernetes/pull/120346 as a KEP to cover such cases.

**Comment by nathanmcgarvey-modopayments** [comment]
FWIW, I made a shell (zsh, at least) function that copies environment variables, envFrom configuration, and volume mounts and does this manually via a `kubectl`, `jq`, and `curl` commands. Note that the image is hardcoded to alpine:latest, but that's easily changed:

https://gist.github.com/nathanmcgarvey-modopayments/358a84297086de3975f54895a9e7123d

**Comment by ardaguclu** [comment]
/triage accepted
since this will be covered by a KEP.

**Comment by satyampsoni** [comment]
can I work on this?

**Comment by murthy95** [comment]
@satyampsoni are you working on this ?

**Comment by ardaguclu** [comment]
@satyampsoni @murthy95 thanks for your interest on this issue. I'm currently working on a KEP to overcome this issue and I'll let you know in case there are any tasks.

**Comment by ardaguclu** [comment]
This is the KEP https://github.com/kubernetes/enhancements/pull/4293 I'm working on. I'm closing this issue.

/close
