### ISSUE TITLE
Enhancement: `kubectl wait --for=existence`

### ISSUE THREAD

**Issue by guettli** [kubernetes/kubectl#1487]
**What would you like to be added**:

I would like to add `kubectl wait --for=existence`

**Why is this needed**:

When I develop in the context of Cluster-API I wait for the kube-config of the workload-cluster which gets created.

The controller creates the kube-config in a secret in the management cluster.

I an Makefile I wait until the secret is available.

Up to now I use 

```
 $(TIMEOUT) 5m bash -c "while ! kubectl -n $(NAMESPACE) get secrets | grep $(CLUSTER_NAME)-kubeconfig; do sleep 1; done"
```

On Mac it is `gtimeout`, on Linux it is `timeout`. And you can't interrupt this waiting with ctrl-c.

I think there are many use-cases for waiting until a resource gets created.

Discussion on [#sig-cli kubectl wait --for=existence](https://kubernetes.slack.com/archives/C2GL57FJ4/p1694426460959429)

As discussed it would be nice to combine with several `--for` arguments:

```
kubectl wait --for=existence --for=condition=Available things/foo
```

**Comment by sftim** [comment]
`kubectl` should be able to use a watch to wait for the existence, assuming the user is authorized to **list**.

**Comment by sftim** [comment]
Is this a duplicate of https://github.com/kubernetes/kubectl/issues/1516?

**Comment by guettli** [comment]
@sftim thank you for the link. Yes, this is a duplicate.
