### ISSUE TITLE
How can get the kubectl describe output to a table format

### ISSUE THREAD

**Issue by vivuu1989** [kubernetes/kubectl#1491]
I am using Kubernetes VPA as a resource recommender tool for my cluster and its generating the recommended specification for each deployment. But I would like to get a automated way to create the vpa recommendation to all the existing VPAs in a much readable format ( preffered way is table format) dynamically. 

I tried to create an Azuredevops pipeline and when parsing the json path from the kubectl get command I am not getting the resulted output.

    k get  vpa myvpa -n mynamespace -o jsonpath='{status.recommendation.containerRecommendations.containerName[*]}'

**Comment by akash-kumar-saw** [comment]
Hi @vivuu1989,

To create a table format output from the VPA recommendations, you can use tools like jq to parse the JSON output and format it as a table. Here's how you can achieve this:

**Step 1 :** Ensure you have jq installed on your system. If it's not installed, you can typically install it using your package manager (e.g., apt-get, brew, yum, etc.).

**Step 2 :** Run the kubectl get command to retrieve the VPA recommendations and pipe the output to jq for formatting. You can use the --output flag with jq to format the data as a table. Here's an example command:
```bash
kubectl get vpa -n mynamespace -o json | jq -r '.items[] | [.metadata.name, .status.recommendation.containerRecommendations[].containerName] | @tsv'
```
This command retrieves the VPA recommendations in JSON format, extracts the VPA name and container recommendations, and formats the output as a tab-separated table.

I hope you find this helpful : )

**Comment by ardaguclu** [comment]
I believe that this https://github.com/kubernetes/kubectl/issues/1491#issuecomment-1732034732 could be a useful workaround. I don't think, we would want to add this in kubectl describe as it's main aim is to print the data in a human readable way in terminal.

/close
