### ISSUE TITLE
missing libresolv.so.2 

### ISSUE THREAD

**Issue by hermanbanken** [kubernetes/kubectl#1497]
Reproduction:

```
docker run gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine sh -c "gcloud components install -q kubectl && kubectl"
```

I'm using the alpine label resolving to `sha256:2902130096be3d4f276addd14d44854a1b4f902a2f9d3d7131592148cfb02252` (platform=linux/arm64).

Output:

```
Error loading shared library libresolv.so.2: No such file or directory (needed by /google-cloud-sdk/bin/kubectl)
Error relocating /google-cloud-sdk/bin/kubectl: __res_search: symbol not found
```

Workaround:
```
docker run gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine sh -c "gcloud components install -q kubectl && apk add gcompat && kubectl"
```

Caused by https://github.com/golang/go/issues/59305.
Cross-post from https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/344.

**Comment by ardaguclu** [comment]
I don't think there is anything we can do as kubectl maintainers with respect to this issue. I'd suggest contacting with the gcp folks.
