### ISSUE TITLE
Allow --enable-exec flag for kustomize commands

### ISSUE THREAD

**Issue by sebhoss** [kubernetes/kubectl#1498]
**What would you like to be added**:

`kubectl kustomize` and other kustomize related commands allow to specify `--enable-alpha-plugins` but not yet `--enable-exec`. That flag should be added to all commands that somehow interact with kustomize, like `kubectl kustomize`, `kubectl diff --kustomize` and `kubectl apply --kustomize`.

**Why is this needed**:

That flag is required to use the new [exec functions](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/) in recent kustomize versions. Without this flag no exec functions are executed.

**Comment by sebhoss** [comment]
I have found https://github.com/kubernetes-sigs/kustomize/issues/4556 & https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2953-kustomize-plugin-graduation just now which are relevant to this.

**Comment by ardaguclu** [comment]
With respect to this https://github.com/kubernetes/enhancements/issues/4706, I don't think we'll implement this feature. I'd recommend opening this issue in kustomize repository, if it is relevant in it. Other than that, I'd prefer closing this. 

/close

**Comment by davireis** [comment]
Now that https://github.com/kubernetes/enhancements/issues/4706 has been closed with the decision of keeping kustomize in kubectl, should --enable-exec be reconsidered? In my particular case I am running from skaffold, which calls kubectl and I can't pass --enable-exec to it.
