### ISSUE TITLE
Bash completion missing for `kubectl explain`

### ISSUE THREAD

**Issue by credativ-dar** [kubernetes/kubectl#1499]
**What happened**:
`kubectl explain` *double tab*
-> only local files are offered for completion

**What you expected to happen**:
Offer/complete available resources like when using `kubectl get` etc.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl explain` *double tab*

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: v1.25.11
Kustomize Version: v4.5.7
Server Version: v1.27.3
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
```

- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`): Fedora 37

**Comment by marckhouzam** [comment]
There is also #694 which I think should be reopened

**Comment by ardaguclu** [comment]
I'm closing this, in favor of https://github.com/kubernetes/kubectl/issues/694;
/close
