### ISSUE TITLE
Remove Registry usage in kubectl

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubectl#150]
Echo what @caesarxuchao said in https://github.com/kubernetes/kubernetes/pull/55388#issuecomment-346227092:
```
In short, I think we should try to refactor kubectl to not depending on the install packages, rather than exporting them.
Users (including kubectl) should only need to populate scheme by calling AddToScheme.

Compared to AddToScheme, the additional things done by the install package are populating the GroupFactoryRegistry and the Registry, but neither seem to be useful.

I searched the code it seems no one is using the GroupFactoryRegistry.

As for the Registry, it has two functionalities,

- Building RESTMapper, but we are moving to build the mapper dynamically, so no one should need that.
- Recording what group/versions are registered and enabled. I think kubectl should allow any group/versions that are recognized by its scheme,
  so registry is not useful. I don't see how other users will need the registry either.
  - I think registry is useful in tests, but each test should just create their own registry.
```

IMO we can (should) get rid of `Registry` and `GroupFactoryRegistry` in [`legacyscheme`](https://github.com/kubernetes/kubernetes/blob/4e2f5e2212b05a305435ef96f4b49dc0932e1264/pkg/api/legacyscheme/scheme.go#L28-L33) and [`kubectl's scheme`](https://github.com/kubernetes/kubernetes/blob/4e2f5e2212b05a305435ef96f4b49dc0932e1264/pkg/kubectl/scheme/scheme.go#L30-L34).
It seems kubectl is the only consumer of `Registry` now.

> Building RESTMapper, but we are moving to build the mapper dynamically, so no one should need that.

IIUC what RESTMapper does is just map `<Group, Version, Kind>` to a URL. So if kubectl need to run in standalone mode (e.g. --local),  it doesn't need a RESTMapper. IOW, it doesn't need to construct the RESTMapper from `Registry`. But we need to refactor kubectl's `builder` pkg to make it possible.

Did I miss something important?

@lavalamp @smarterclayton @liggitt @sttts Thoughts or concerns?

cc: @pwittrock @fabianofranz @monopole

**Comment by apelisse** [comment]
@mengqiy what's the status on this one? are you working on it?

**Comment by mengqiy** [comment]
I'm not working on it now.

**Comment by sttts** [comment]
I would like to see pkg/kubectl/scheme/install.go go away soon'ish. This code should never have passed review and being merged. Compare https://github.com/kubernetes/kubernetes/pull/55388/commits/f0a0d641a0f42268f0992feae86ae7cbcb307a8c

**Comment by mengqiy** [comment]
Why you want that piece of code to go away? Is it causing trouble for you?

Should legacy kubectl use its own scheme? If so, we need to register types using the following 2 lines, right?
```
v1.AddToGroupVersion(Scheme, schema.GroupVersion{Version: "v1"})
scheme.AddToScheme(Scheme)
```

**Comment by sttts** [comment]
> Why you want that piece of code to go away? Is it causing trouble for you?

It copies code that is tightly coupled with the API types and should be shipped with the API types. It's deep knowledge that should not be in some CLI file. Compare e.g. pkg/apis/apps/install/install.go in kube. The code in the kubectl is a copy of that. Any mistake in keeping both in sync will be hard to debug and will lead to unexpected, inconsistent behaviour.

In https://github.com/kubernetes/kubernetes/pull/55388, we made this install.go code available via k8s.io/api. But eventually we concluded that this is unnecessary as kubectl should not need the Registry related code at all, compare https://github.com/kubernetes/kubernetes/pull/55388#issuecomment-346227092.

> Should legacy kubectl use its own scheme? If so, we need to register types using the following 2 lines, right?

Client-go has this scheme already: https://github.com/kubernetes/client-go/blob/master/kubernetes/scheme/register.go. I think you refer to this snippet (which you can copy if you need another scheme; do not mutate the one of client-go, better create you own with those two lines if you need that): https://github.com/kubernetes/client-go/blob/master/kubernetes/scheme/register.go#L58.

**Comment by apelisse** [comment]
Let's be honest, this is never going to happen. We should close that issue.

**Comment by sttts** [comment]
@soltysh any progress here?

**Comment by soltysh** [comment]
This should be done by now. Kubectl uses only external types and has its own scheme. I doubt we'll be reaching the point where each command has its own scheme. 
/close
