### ISSUE TITLE
add "kubectl change namespace"

### ISSUE THREAD

**Issue by migs35323** [kubernetes/kubectl#1501]
**What would you like to be added**:
a way so we can easily change namespaces in the current cluster.
so we could make operations more quickly

**Why is this needed**:

i find it easier to type "kubectl -n namespace" everytime i need to do something but it gets cubbersome if we need to do several operations in a row....
kubectl config set-context --current --namespace=<namespace-name>
this one is too long for changing namespace in the fly...

Probably i could add an alias in my setup but i believe this feature would benefit loads of people.

**Comment by ardaguclu** [comment]
This sounds like a good idea for a plugin and if gets attraction as plugin, it would be good to consider this to get in as a standard command in kubectl.

**Comment by Ithrael** [comment]
kubens changenamespace
kubectx change cluster 
https://github.com/ahmetb/kubectx

**Comment by ardaguclu** [comment]
Since there is already a plugin for the same functionality, I don't think we need this new command and I'd prefer closing this issue;

/close
