### ISSUE TITLE
kubectl debug: add optional CLI argument to specify an imagePullSecret

### ISSUE THREAD

**Issue by MShekow** [kubernetes/kubectl#1506]
**What would you like to be added**:

`kubectl debug` lacks the ability to set an `imagePullSecret` used to pull the specified `--image`.

**Why is this needed**:
Often, corporate Kubernetes clusters enforce the usage of custom registries (with a pull-through mirror, e.g. Harbor) that also require an image pull secret.

**Comment by ardaguclu** [comment]
I think, this feature request will be covered in this KEP https://github.com/kubernetes/enhancements/pull/4293 automatically.

**Comment by ardaguclu** [comment]
I have added this feature request into the KEP ^. So I'm closing this;
/close

**Comment by dennis-benzinger-hybris** [comment]
> I think, this feature request will be covered in this KEP [kubernetes/enhancements#4293](https://github.com/kubernetes/enhancements/pull/4293) automatically.

@ardaguclu, this KEP allows you to specify a partial container spec but the `imagePullSecret` is on the pod level:
https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/#PodSpec

So, how does this KEP help for the use case of this ticket here?

**Comment by ardaguclu** [comment]
I agree with you. Please see https://github.com/kubernetes/kubectl/issues/1671
