### ISSUE TITLE
kubectl forwards the service port, access fails.

### ISSUE THREAD

**Issue by yuluo-yx** [kubernetes/kubectl#1507]
**What happened**:

When the kubectl forwarding service port is not set with `--address`, it cannot be accessed through the IPv4 (192.168.2.13) address, and can only be accessed through the local loopback address (127.0.0.1).

When I use kubectl to forward the port, if I do not specify the --address option, use the following command:
`kubectl port-forward grafana-5f9b8c6c5d-jnd6n -n istio-system 3000:3000`
Then I use curl to verify curl 127.0.0.1:3000, successfully echoed the html text.

But when I use the ip address `192.168.*.*` to access, gets an error:
```shell
$: curl 192.168.2.13:3000
curl: (7) Failed to connect to 192.168.2.13 port 3000 after 0 ms: Connection refused
````
**I'm sure my address is `192.168.2.13`**.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Install minikube
2. Install kubectl
3. install Istio
4. Install grafana
5. `kubectl port-forward grafana-5f9b8c6c5d-jnd6n -n istio-system 3000:3000`

**Environment**:
1. Kubernetes client and server versions: 
    ```shell
    Client Version: v1.28.3
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.27.4
    ```
7. OS:
    Vmware ubuntu 22.04 server

**Comment by ardaguclu** [comment]
Running the same port-forward command with `-v=9` would shed some light on the issue and give a clue about what is happening.

**Comment by yuluo-yx** [comment]
@ardaguclu Thanks, this issue is solved, close now!
