### ISSUE TITLE
kubectl get all does not list all resources in a namespace

### ISSUE THREAD

**Issue by tback** [kubernetes/kubectl#151]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
get all, get all resources 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.2-gke.0", GitCommit:"52ea03646e64b35a5b092ab32bb529400c296aa6", GitTreeState:"clean", BuildDate:"2017-10-24T23:31:18Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
gke
- **OS** (e.g. from /etc/os-release):
macos 10.12.6

**What happened**:
`kubectl get all` does not list all resources in a namespace.

**What you expected to happen**:
As a user performing `kubectl get all` I expect to see all objects in the current context, including limits.

**How to reproduce it** (as minimally and precisely as possible):
```
kubectl create namespace tmp
kubectl create -f https://k8s.io/docs/tasks/administer-cluster/memory-defaults.yaml --namespace=tmp
kubectl get all --namespace tmp
namespace "tmp" created
limitrange "mem-limit-range" created
No resources found.
```

**Comment by stewart-yu** [comment]
`kubectl get all --namespace tmp` is wrong, you may use `kubectl get all --n tmp`

**Comment by tback** [comment]
@stewart-yu: Double dash and short form (`kubectl get all --n tmp`) *doesn't work*!

Both variants below *do work*:
`kubectl get all --namespace tmp`
`kubectl get all -n tmp`

You can look that up in `kubectl options`:
```
...
-n, --namespace='': If present, the namespace scope for this CLI request
...
```

**Comment by stewart-yu** [comment]
Sorry, my mistakes. I will have a look about it

**Comment by stewart-yu** [comment]
I will fix it ASAP

**Comment by stewart-yu** [comment]
cc @smarterclayton  Described as above. We can not get `limitRange` for it is `unknown objects`?

**Comment by stewart-yu** [comment]
cc @fabianofranz

**Comment by fabianofranz** [comment]
> As a user performing kubectl get all I expect to see all objects in the current context, including limits.

There are some rules about which resources must fall under "all", take a look [here](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all). Are the resources you want covered there?

**Comment by tback** [comment]
Yes, limits are covered there (Rule 2: No namespace admin level resources (limits, quota, policy, authorization rules)).
This leaves me frustrated though:

1. `kubectl help get` describes `kubectl get all` as `List all resources with different types.` so I think I am right to expect *all* resources to be listed.
2. It might be ok if adminstrative resources are hidden from a normal user. As a cluster admin I *need* an easy way to see *everything* in a namespace to decide if i can delete it or not.

**Comment by smarterclayton** [comment]
There's an open issue for that - I'd like to see it solved, but it requires
some other work to happen because there are resources that exist, but
aren't deletable.

**Comment by HartS** [comment]
I'd like to see a documentation improvement, as well as a new 'type' to use to *actually* show all resources in a namespace, as the current meaning of `all` is both unintuitive and *not documented anywhere*. Just fixing kubectl wouldn't help users figure out what's going on for older versions, so I think a new name (`everything` ?) would be helpful for retaining consistency with older client versions.

Currently I know that `all` *doesn't* refer to the following types of resources:
* resources which are not namespace (this makes sense... though with `--all-namespaces` it might be useful to include these): `clusterrolebindings
* configmaps
* rolebindings
* roles

`all` *does* refer to the following types of (namespaced) resources:
* pods (though completed pods are still omitted without `--show-all`
* services
* replicasets
* deployments

This is only a partial list, as I have no way of knowing what are kinds of resources are listed by `all`

I think there needs to be better documentation around resources in general, and a better explanation of the magic `all` resource pseudo-type.

**Comment by joaosousafranco** [comment]
Same issue here. Its returning only deployments, replicasets and pods

**Comment by mengqiy** [comment]
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

**Comment by DamonStamper** [comment]
@HartS 
When running `kubectl get` I'm shown a list of resource types. 

That might be a decent place to start for documentation.

For reference I got the below against my v1.10.0 Kube setup.
```
  * all
  * certificatesigningrequests (aka 'csr')
  * clusterrolebindings
  * clusterroles
  * componentstatuses (aka 'cs')
  * configmaps (aka 'cm')
  * controllerrevisions
  * cronjobs
  * customresourcedefinition (aka 'crd')
  * daemonsets (aka 'ds')
  * deployments (aka 'deploy')
  * endpoints (aka 'ep')
  * events (aka 'ev')
  * horizontalpodautoscalers (aka 'hpa')
  * ingresses (aka 'ing')
  * jobs
  * limitranges (aka 'limits')
  * namespaces (aka 'ns')
  * networkpolicies (aka 'netpol')
  * nodes (aka 'no')
  * persistentvolumeclaims (aka 'pvc')
  * persistentvolumes (aka 'pv')
  * poddisruptionbudgets (aka 'pdb')
  * podpreset
  * pods (aka 'po')
  * podsecuritypolicies (aka 'psp')
  * podtemplates
  * replicasets (aka 'rs')
  * replicationcontrollers (aka 'rc')
  * resourcequotas (aka 'quota')
  * rolebindings
  * roles
  * secrets
  * serviceaccounts (aka 'sa')
  * services (aka 'svc')
  * statefulsets (aka 'sts')
  * storageclasses (aka 'sc')
```

**Comment by mrezaei00** [comment]
@liggitt does `kubectl api-resources` replace the functionality as well or this just means `kubectl get all` is going to be deprecated and there will not be any support for searching labels in a namespace?

My use case is the same as the issue:
```
$ kubectl get all -l <label>=<value> -n <namespace>
NAME         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/...

NAME                DESIRED   CURRENT   READY     AGE
rs/...

NAME                      READY     STATUS    RESTARTS   AGE
po/...

NAME      TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                      AGE
svc/...
```
which doesn't return secrets, for example:
```
$ kubectl get secret -l <label>=<value> -n <namespace>
NAME                         TYPE      DATA      AGE
secret-1...
```

**Comment by roshankadasani** [comment]
Try - `kubectl get all --all-namespaces`

**Comment by liggitt** [comment]
> @liggitt does kubectl api-resources replace the functionality as well or this just means kubectl get all is going to be deprecated and there will not be any support for searching labels in a namespace?

`kubectl api-resources` enumerates the resource types available in your cluster. 

this means you can combine it with `kubectl get` to actually list every instance of every resource type in a namespace:

```
kubectl api-resources --verbs=list --namespaced -o name \
  | xargs -n 1 kubectl get --show-kind --ignore-not-found -l <label>=<value> -n <namespace>
```

**Comment by jeremyjjbrown** [comment]
Why is this closed? Some complex xargs stuff does not mitigate the fact at "all" is indeed a falsehood that does not return all objects.

**Comment by liggitt** [comment]
> Some complex xargs stuff does not mitigate the fact at "all" is indeed a falsehood that does not return all objects.

`all` will not be extended because of compatibility concerns, and is not referenced in help any longer because it is misleading, as you point out

**Comment by jeremyjjbrown** [comment]
Is there some other literate way to <verb> all by label?

**Comment by Diaphteiros** [comment]
> ```
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -l <label>=<value> -n <namespace>
> ```

This also has the disadvantages of not only being unintuitive, but also slow as hell ...

**Comment by 2rs2ts** [comment]
that also doesn't work:

```
error: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by staranto** [comment]
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -l <label>=<value> -n <namespace>
> ```

A nifty trickery and all that I'd certainly go for, but api-resources doesn't exist in kubectl < 1.11.  I'm not sure why there's a debate about the definition of all.  All is all, save for any boundaries around security.

**Comment by juanvallejo** [comment]
> Do we know why this happens? I'm seeing the same issue.

Error handling for that command was recently improved in https://github.com/kubernetes/kubernetes/pull/73035. It no longer fails on a single error

**Comment by sassanh** [comment]
My current situation is that I have a cluster with some namespaces, I try to delete a namespace and it's stuck in `Terminating` state. I know this situation is mentioned in other issues here, but unfortunately those are closed too. I'm not going to ask how to solve this problem, instead I want to invest time and understand what's going on, if same problem happened with a resource in Linux operating system I could understand why exactly it's happening by reading logs and running commands and reading their outputs and wouldn't ask Linus Torvalds about it in Linux git repository. In order to decide that kubernetes is a reliable tool for my company I need to make sure same thing can happen in kubernetes too, I wanna make sure someone can reach to a point with kubernetes that he can solve the unknown problems by reading logs, seeing states of resources, etc instead of creating issues in kubernetes repository and waiting for someone to reply. I think for kubernetes to be considered mature it should be self diagnosable (like Linux with its logs and commands, Python with its shell and pdb, JS with devtools, etc).

So I think it should be in high priority to:
1. Add features like the one mentioned in this issue to the API as soon as possible.
2. Provide workarounds until such features are added, and for those who are using older versions.

For my mentioned problem I thought maybe something in the undeletable namespace is pending another resource in another namespace so I wanted to see all resources in the default namespace to see if my theory makes sense or not. Not being able to list all resources (including custom resources) is really annoying stopped me and a problem that could probably solved by myself by investing time is now only solvable by either opening an issue here and waiting unknown time for someone to answer or invest much more time reading the source code of kubernetes and compile it with debug directives and see what's going on.

**Comment by javabrett** [comment]
This really has the capacity to trip-up new (and old) users alike in interesting and frustrating ways.  If `all` isn't `all` and _never will be_ `all` again, surely it has to be deprecated?  Is it actually a compatibility issue - is this command porcelain for scripting?

Example of getting caught:

`kubectl get all --namespace ns1`
(nothing)
`kubectl get pvc --namespace ns`
(1 pvc is listed)

Ah - so `helm delete` didn't remove my persistent volumes ... I wish `all` had told me that.

**Comment by BenWUKFast** [comment]
Agreed on the deprecation comment.

Perhaps instead of breaking backwards compatibility we could allow a glob syntax, so for example `*role*` would return `role`,`rolebinding`,`clusterrole`,`clusterrolebinding` and `*` would return everything. I'm glad that `all` is no longer a resource, so perhaps we can with this approach distinct between a resource type and syntax.

**Comment by sarunask** [comment]
This post really helps:
https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-401039268
So you need to delete `finalizers` from your NS and all CRD's or resources you have - and NS would be deleted

**Comment by antoineco** [comment]
@sarunask that's a terrible idea, this method bypasses finalizers so it leaves all the objects belonging to the namespace inside your cluster.

See #73405 and https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-429754733 instead.

**Comment by oudream** [comment]
kubectl api-resources -o name | xargs -I {} kubectl get {} --show-kind --ignore-not-found

##
##

**Comment by oudream** [comment]
master $ kubectl api-resources -o name
bindings
componentstatuses
configmaps
endpoints
events
limitranges
namespaces
nodes
persistentvolumeclaims
persistentvolumes
pods
podtemplates
replicationcontrollers
resourcequotas
secrets
serviceaccounts
services
mutatingwebhookconfigurations.admissionregistration.k8s.io
validatingwebhookconfigurations.admissionregistration.k8s.io
customresourcedefinitions.apiextensions.k8s.io
apiservices.apiregistration.k8s.io
controllerrevisions.apps
daemonsets.apps
deployments.apps
replicasets.apps
statefulsets.apps
tokenreviews.authentication.k8s.io
localsubjectaccessreviews.authorization.k8s.io
selfsubjectaccessreviews.authorization.k8s.io
selfsubjectrulesreviews.authorization.k8s.io
subjectaccessreviews.authorization.k8s.io
horizontalpodautoscalers.autoscaling
cronjobs.batch
jobs.batch
certificatesigningrequests.certificates.k8s.io
leases.coordination.k8s.io
events.events.k8s.io
daemonsets.extensions
deployments.extensions
ingresses.extensions
networkpolicies.extensions
podsecuritypolicies.extensions
replicasets.extensions
ingresses.networking.k8s.io
networkpolicies.networking.k8s.io
runtimeclasses.node.k8s.io
poddisruptionbudgets.policy
podsecuritypolicies.policy
clusterrolebindings.rbac.authorization.k8s.io
clusterroles.rbac.authorization.k8s.io
rolebindings.rbac.authorization.k8s.io
roles.rbac.authorization.k8s.io
priorityclasses.scheduling.k8s.io
csidrivers.storage.k8s.io
csinodes.storage.k8s.io
storageclasses.storage.k8s.io
volumeattachments.storage.k8s.io

**Comment by bdowling** [comment]
> kubectl api-resources -o name | xargs -I {} kubectl get {} --show-kind --ignore-not-found

@oudream thanks for that.  Slight improvement since most use cases of this is dealing with a particular _NAMESPACE_ ...

kubectl -n _NAMESPACE_ api-resources **--namespaced=true** -o name | xargs --verbose -I {} kubectl -n _NAMESPACE_ get {} --show-kind --ignore-not-found

**Comment by mxplusb** [comment]
I'm going to jump in here and provide feedback that while the `xargs` stuff is better than nothing, it's not an option on Windows. And yes, I am aware there are other workaround with Powershell.

The fact this has been broken for several years and it's just being punted from release to release is immensely frustrating. Replace or remove the `all` functionality but leaving it languish like this is a terrible user experience.

**Comment by liggitt** [comment]
> Replace or remove the all functionality but leaving it languish like this is a terrible user experience.

The `all` alias won't be removed for compatibility reasons but has been removed from command help for several releases. I agree it should not be promoted as it is confusing.

**Comment by UkiahSmith** [comment]
`kubectl get all` is deceptive and could lead to issues with it's use. 

It should be deprecated and removed or it should be enhanced to actually list all resources in a namespace.

At the very least when the current implementation is used it should display a warning.

**Comment by dims** [comment]
There's discussion from way back in 2016 on what items should be in `all` : https://github.com/kubernetes/kubernetes/pull/28955#issuecomment-232737113

Agree with @liggitt that we should not promote its use

**Comment by dims** [comment]
@seans3 @liggitt  we should probably just start the deprecation process for this?

**Comment by liggitt** [comment]
The `all` category is entirely specified server-side in discovery docs, and resolved generically client-side like any other category. It's unclear how we would communicate it was deprecated to users of that feature without adding special case logic specific to "all" client-side, which we do not want to do.

**Comment by mxplusb** [comment]
@liggitt @seans3 is there a compelling reason the deprecation process cannot be started?

**Comment by akavel** [comment]
Snippet listing all resources as in [@oudream's comment](https://github.com/kubernetes/kubectl/issues/151#issuecomment-509897509), with `$()` speedup from [@bdowling's comment](https://github.com/kubernetes/kubectl/issues/151#issuecomment-510345342), and with another simplification replacing `tr|sed` with `paste`:

`kubectl get $(kubectl api-resources --verbs=list -o name | paste -sd, -) --ignore-not-found --all-namespaces
`

**Comment by mxplusb** [comment]
@liggitt @seans3 any updates on getting this functionality removed?

**Comment by bnason** [comment]
For some reason when I add a label selector that *should not* match anything to the command @akavel provided, it returns 3 ComponentStatus items
```
$kubectl get $(kubectl api-resources --verbs=list -o name | paste -sd, -) --ignore-not-found --all-namespaces -l random=label
NAME                                 AGE
componentstatus/controller-manager   <unknown>
componentstatus/scheduler            <unknown>
componentstatus/etcd-0               <unknown>
```

**Comment by liggitt** [comment]
> For some reason when I add a label selector that _should not_ match anything to the command @akavel provided, it returns 3 ComponentStatus items

ComponentStatus is an unusual API with a custom list implementation, and did not pay any attention to label selectors until https://github.com/kubernetes/kubernetes/pull/78438 fixed that in 1.17

**Comment by bnason** [comment]
Thanks @loggit for the fast response, for now I can simply filter it out using grep.
`kubectl get $(kubectl api-resources --verbs=list -o name | grep -v componentstatus | paste -sd, -) --ignore-not-found --all-namespaces -l random=label`

**Comment by mxplusb** [comment]
@liggitt @seans3 any updates on getting this functionality removed?

**Comment by liggitt** [comment]
Not really. Removing it from documentation, help, and examples was the first step to reducing confusion for new users. Like I said, it's not clear how we would communicate effectively that the alias was deprecated (we don't have API documentation for those like we do API types)

**Comment by intelligent002** [comment]
may be silly question but still ... may the output be filter based:

**kubectl get all** - list all resources of all types
**kubectl get <resourceTypes>** - list all resources of required types
**kubectl get -l <label>=<value>** - list all resources of all types with label filtering
**kubectl get <resourceTypes> -l <label>=<value>** - list all resources of required types with label filtering
**kubectl get <resourceTypes> -l <label>=<value> -n <nameSpaces>** - list all resources of required types with label and namespace filtering

etc ...

**Comment by mxplusb** [comment]
> it's not clear how we would communicate effectively that the category was deprecated (we don't have API documentation for those like we do API types)

The deprecation policy has a set of rules that could be applied to start Occam's Razor on deprecating this.

* _Rule 1: API elements may only be removed by incrementing the version of the API group._
  * **It's not an API type, just a category, so it wouldn't apply, correct?**
* _Rule 2: API objects must be able to round-trip between API versions in a given release without information loss, with the exception of whole REST resources that do not exist in some versions._
  * **It's not an API object, just a category, so this wouldn't apply, correct?**
* _Rule 3: An API version in a given track may not be deprecated until a new API version at least as stable is released._
  * **It's neither a type nor an object, so this wouldn't apply, correct?**
* _Rule 4a: Other than the most recent API versions in each track, older API versions must be supported after their announced deprecation for a duration_
  * **It's neither a type nor object, so this wouldn't apply, correct?**
* _Rule 4b: The “preferred” API version and the “storage version” for a given group may not advance until after a release has been made that supports both the new version and the previous version_
  * **It's not a storage type, so this doesn't apply.**
* _Rule 5a: CLI elements of user-facing components (e.g. kubectl) must function after their announced deprecation_
  * **It's already been removed in client-side references, and since it's not client-side code, this wouldn't apply, correct?**
* _Rule 5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation_
  * **It's already been removed in client-side references, and since it's not client-side code, this wouldn't apply, correct?**
* _Rule 7: Deprecated behaviors must function for no less than 1 year after their announced deprecation_
  * **Okay, so after it's been removed in a release, it has to keep functioning for a year.**
* _Rule 8: Feature gates must be deprecated when the corresponding feature they control transitions a lifecycle stage as follows._
  * **Would this need a feature gate?**
* _Rule 9: Deprecated feature gates must respond with a warning when used._
  * **Depends on the answer to Rule 8**

Based off my understanding of the policy and the internals of this feature (without diving into the code), here are the core requirements which would have to be applied:

* After it's been deprecated, it has to keep functioning for a year.
* Will likely need a feature flag.

It could also be argued this falls under the [Exception section of the policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#exceptions), as well:

> No policy can cover every possible situation. This policy is a living document, and will evolve over time. In practice, there will be situations that do not fit neatly into this policy, or for which this policy becomes a serious impediment. Such situations should be discussed with SIGs and project leaders to find the best solutions for those specific cases, always bearing in mind that Kubernetes is committed to being a stable system that, as much as possible, never breaks users. Exceptions will always be announced in all relevant release notes.

To me, it sounds more like this is an exception to the core policy since it's mostly internal, server-side code handling a category with no objects or types associated with it. The exception section's second sentence starts with _[t]his policy is a living document_, maybe it's time to dive into what that looks like, and understand the aspect of deprecating a category, and how that will work? I suggest that knowing it's not a fast process, and that it can take time to have discusses and get feedback.

@liggitt which SIG would this fall under? I'm thinking it'd be API Machinery since it's API functionality, or do you think it would fall under a different one?

**Comment by liggitt** [comment]
> To me, it sounds more like this is an exception to the core policy since it's mostly internal, server-side code handling a category with no objects or types associated with it.

That is not accurate. The "all" category is associated with particular group/version/resources, and is returned in discovery API responses by the server. The closest rule in the deprecation policy that applies is:

> Rule 1: API elements may only be removed by incrementing the version of the API group.

That would mean the "all" category would continue to be associated with all existing group/version/resources, and could be removed on a per-resource basis as those resources reached a new version. For example:
* v2 pods, replicationcontrollers, services, 
* batch/v2 jobs, cronjobs
* autoscaling/v2 horizontalpodautoscalers
* apps/v2 daemonsets, deployments, replicasets, statefulsets

Given there are no plans in progress to begin work on v2 versions of most of those resources (only horizontalpodautoscalers have a v2 in progress), an announced deprecation would have no planned timeline it would take effect.

**Comment by mxplusb** [comment]
It sounds like the most reasonable time to remove the "all" category would be when the horizontalpodautoscalers formally announce their intent for v2? That way it wouldn't get blocked for an unknown amount of time with v2 resources, then blocked on v3, etc.

I guess in all of this, what is the end result realistically going to be? Would just ensuring "all" returns everything be easier than trying to get the category deprecated? This limbo area is miserable from a user experience standpoint.

**Comment by liggitt** [comment]
Movement in either direction (to make it include all resources, or to make it stop including some and eventually any resources) has potential to break callers.

With the limited visibility of the existence of the "all" category, and removal from all documentation and user guides we control, I'm curious whether its continued existence to satisfy compatibility concerns is actually impacting users that much.

**Comment by jfekete1** [comment]
Just write a simple script to get all the resources...

<code>
#!/usr/bin/perl

my $k8sResources = `kubectl api-resources | awk '{print \$1}'`;
my @resources = split("\n", $k8sResources);
shift @resources;

foreach $resource (@resources)
{
  my $command = 'kubectl get ' . $resource . ' --all-namespaces';
  print "############################################################################\n";
  print "Getting resources of type: " . uc($resource) . "\n\s\s -with command: $command";
  system($command);
  print "############################################################################\n\n\n\n\n";
}
</code>

**Comment by danmutblix** [comment]
> @stewart-yu: Double dash and short form (`kubectl get all --n tmp`) _doesn't work_!
> 
> Both variants below _do work_:
> `kubectl get all --namespace tmp`
> `kubectl get all -n tmp`
> 
> You can look that up in `kubectl options`:
> 
> ```
> ...
> -n, --namespace='': If present, the namespace scope for this CLI request
> ...
> ```

Yes, agreed. Doesn't really matter where you put the -n arg

`kubectl get -n tmp po,sts,svc,whatever` also works

Not that it matters in here, but just a side-note, I think it's easier to just add **-A** instead of **--all-namespaces**

`kubectl get all -A`

**Comment by danmutblix** [comment]
> > @liggitt does kubectl api-resources replace the functionality as well or this just means kubectl get all is going to be deprecated and there will not be any support for searching labels in a namespace?
> 
> `kubectl api-resources` enumerates the resource types available in your cluster.
> 
> this means you can combine it with `kubectl get` to actually list every instance of every resource type in a namespace:
> 
> ```
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -l <label>=<value> -n <namespace>
> ```

> **-Perfect!**

**Comment by danmutblix** [comment]
@liggitt 

This works for me

`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind -A 2>/dev/null`

Ignore errors

**Comment by david-in-perth** [comment]
The *kubectl-conventions.md* doc linked to above still exists at [a different location][1] ([permalink][1 permalink]),
and still has the section titled *Rules for extending special resource alias - "all"*.

Should that section be updated to make that clear that the "all" alias is obsolete / is only being kept for backwards-compatibility?

[1]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all
[1 permalink]: https://github.com/kubernetes/community/blob/10a7245/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

**Comment by moebius87** [comment]
Meanwhile I worked around the problem by using **[ketall](https://github.com/corneliusweig/ketall#via-krew)** (it can be installed via [krew](https://github.com/kubernetes-sigs/krew)).

```console
kubectl krew install get-all
kubectl get-all
```
I know, this isn't what you're looking for but it's not so bad.
I hope you'll find it useful anyway. :)

**Comment by rkand4** [comment]
> @stewart-yu: Double dash and short form (`kubectl get all --n tmp`) _doesn't work_!
> 
> Both variants below _do work_:
> `kubectl get all --namespace tmp`
> `kubectl get all -n tmp`
> 
> You can look that up in `kubectl options`:
> 
> ```
> ...
> -n, --namespace='': If present, the namespace scope for this CLI request
> ...
> ```

Is there an equivalent of this in Client Java SDK ? I cannot figure it out at all.

**Comment by sraillard** [comment]
I know it's a old discussion, but why I arrived here is very simple: I was searching for a simple way to list ***all*** the objects created in a namespace, hence, I have found the existence of the `all` keyword.

This `all` keyword really makes sens for me. Then I discover that `all` isn't listing all kind of objects... Hence my discovery of this ticket!

Honnestly, it's hard to understand why this keyword was removed from the documentation and never implemented to fully return all kind of objects. 

There is no simple alternative.

**Comment by antoineco** [comment]
@sraillard see the answer from @moebius87 https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672

**Comment by sraillard** [comment]
This plugin seems to be nice and do the work! My question is more why this kind of tool isn't integrated by default in kubectl?

**Comment by rkand4** [comment]
Is there an equivalent of listing all kubernetes objects matching a label like below using **Kuberentes java client SDK**? (https://github.com/kubernetes-client/java)

The goal is to list all .yml files this particular application has an example is the below label can match DaemonSet, Deployment, Service

kubectl get all -l app=RatingsService

**Comment by antoineco** [comment]
@rkand4 this is a question for StackOverflow or discuss.kubernetes.io.

The short answer is **no**. You have to range over all the APIs returned by [`getAPIVersions`](https://github.com/kubernetes-client/java/blob/cbc1d385dfa02da38e07e4b22498971b7b464680/kubernetes/docs/ApisApi.md), list the resources inside each returned API (only the `preferredVersion` of each API), and finally get the objects for these resources in each namespace. There is no shortcut.

**Comment by danmutblix** [comment]
Soo, can we just close this for now, the answers are already answered
through this thread. Thanks

**Comment by gothrek22** [comment]
Just to add a workaround for:
```Error: uninstallation completed with 1 error(s): could not get apiVersions from Kubernetes: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request```

run:
```kubectl delete apiservice v1beta1.external.metrics.k8s.io```

**Comment by 4c74356b41** [comment]
its funny how you implement something sloppy and then you have an issue open for 3 years where you make all sorts of excuses why this should stay this way.

**Comment by cah-prakash-kalaiarasu01** [comment]
_kubectl get all --all-namespaces_

will list the resources from all the namespace

**Comment by micktg** [comment]
It's not a 100% solution, but for me works the following

`kgetall='kubectl get namespace,replicaset,secret,nodes,job,daemonset,statefulset,ingress,configmap,pv,pvc,service,deployment,pod --all-namespaces'`
and just call
`kgetall`
But obviously I expected that behavior from
`kubectl get all --all-namespaces`
in the first place.

**Comment by antoineco** [comment]
@micktg that only lists a very small subset of resources.

To list _all_ resources, like the issue's title suggests, see https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672

**Comment by micktg** [comment]
> @cah-prakash-kalaiarasu01 and @micktg: that only lists a very small subset of resources.
> 
> To list _all_ resources, like the issue's title suggests, see [#151 (comment)](https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672)

Of course, I am aware of that. It is suitable for me personally in most cases and miles better than `kubectl get all --all-namespaces` That's what I wanted to say.

**Comment by dene14** [comment]
If someone still suffers from that problem, please check this script: https://gist.github.com/dene14/7253685cdedde2b6d16e8fc1df450d4f

**Comment by antoineco** [comment]
@dene14 "Migrate releases from helm2 to helm3" sounds very much off topic to me.

**Comment by greatvovan** [comment]
Crazy... Instead of fixing the buggy command they removed it from documentation.

**Comment by kesor** [comment]
A much faster alternative to using `xargs -n1` would be something like this:

```
kubectl get --show-kind --ignore-not-found $(kubectl api-resources --verbs=list --namespaced -o name | paste -s -d,) $@
```

and if you put that into a file called `kubectl-everything` that has the execute bit and sits somewhere in your path, then you can even do `kubectl everything -n mynamespace` to list all resources in a specific namespace.

**Comment by bitti** [comment]
@kesor Note however that under MacOS one has to add a `-` parameter to `paste` (or install the GNU version of paste), because defaulting to stdin isn't implied in BSD paste.

**Comment by davidbIQ** [comment]
upvote to fix

**Comment by antoineco** [comment]
@davidbIQ I'm not a Kubernetes contributor, but this issue is closed and most likely not monitored by anyone.

Is anything stopping you from using the [`kubectl get-all`](https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672) plugin, as suggested in https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672? It sounds like a perfect use-case for a plugin to me.

**Comment by danmutblix** [comment]
@davidbIQ there are plenty of different answers in this thread, if you can't find a suitable one, then script one for your self.

**Comment by qgeffard** [comment]
Is there a reason on why the kubectl get-all is not integrated to the native/vanilla kubectl and also documented?

**Comment by antoineco** [comment]
@qgeffard the short answer is that the "all" special keyword was explicitly removed because it didn't play well with the way `kubectl` interacts with CRD categories.

Long answer, read on:

`kubectl get` has essentially 2 modes:
* `kubectl get <concrete kind>` returns a list of all objects of a given **kind** (e.g. `kubectl get pod`)
* `kubectl get <any word>` is a _fallback_ which returns all objects of a given **category** ([documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories))

For example, consider that you install a Kubernetes-native solution such as [Istio](istio.io/) (example picked semi-randomly, simply because it is popular). Now imagine that Istio uses the mechanism of [categories](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories) mentioned above to tag each of their CRD with the "istio" category. You can now list all Istio-related objects with `kubectl get istio`. Neat!

Now imagine that some of those category names, like "all", are reserved. You end up in a situation where a given keyword can have not one, not two, but three (!) different meanings. This is likely to confuse users and CRD authors alike so, instead of _reserving_ some special keywords, it was decided that no category should be treated differently (in other words, "all" is a perfectly valid category as well).

Thankfully, plugins are first-class citizens in `kubectl`, so special and opinionated features such as `kubectl get all` were encouraged to be supported by those community-maintained plugins. Using the [Krew](https://krew.sigs.k8s.io/) plugin manager, it is even super easy to search and install such plugins, regardless of the platform you use.

I hope I helped understanding the "why" 🙏

**Comment by bzub** [comment]
The `xargs` based command resulted in multiple `List` resources. The following seems faster, and results in one `List` of resources.

```sh
kinds="$(
for namespaced in "true" "false"; do
  kubectl api-resources --verbs="list" -o name --no-headers --namespaced="${namespaced}"
done | sed -z 's/\n/,/g;s/,$/\n/'
)"

kubectl get "${kinds}" -A -o yaml > all_resources.yaml
```

**Comment by scratchmex** [comment]
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found

Just to note that to **truly** list all resources you should remove the `--namespaced`. For example these 2 are not namespaced and does not show up with that command:
```
mutatingwebhookconfigurations.admissionregistration.k8s.io
validatingwebhookconfigurations.admissionregistration.k8s.io
```

**Comment by 1dropaflame** [comment]
> @davidbIQ I'm not a Kubernetes contributor, but this issue is closed and most likely not monitored by anyone.
> 
> Is anything stopping you from using the [`kubectl get-all`](https://github.com/corneliusweig/ketall) plugin, as suggested in [#151 (comment)](https://github.com/kubernetes/kubectl/issues/151#issuecomment-594978672)? What you are trying to achieve is the exact reason why those plugins exist.

Because one cannot install anything on the CKAD exam.

**Comment by davidbIQ** [comment]
I'm using powershell so I'm not sure that would work, & I don't really want to install a plugin.
I think part of it is all a lie; they should rename it to kubectl get some (and add ingress to it), or make all mean all...
as when I posted this I was new to kubernetes, I was confused why some things just weren't there that I thought should have been there.  It looks like they removed it from the docs which is both a step forwards & backwards... but the functionality is still there;   I'm still of the opinion though that all should mean all, and add some other catagory options like global (for global scoped resources only etc).

**Comment by Alestrix** [comment]
> Just to note that to **truly** list all resources you should remove the `--namespaced`.

Have a look at the issue's title: "... list all resources ***in a namespace***"

**Comment by Sandeep-Prajapati** [comment]
Use the **kubectl** plugin [get-resources](https://github.com/Sandeep-Prajapati/kubectl-get-resources) to retrieve namespace-scoped resources, cluster-scoped resources, or both.

For installation
`kubectl krew install get-resources`

Check available options
`kubectl get-resources --help`
