### ISSUE TITLE
Incorrect ordering in --sort-by

### ISSUE THREAD

**Issue by fireflycons** [kubernetes/kubectl#1517]
**What happened**:

Pods are not sorted in the correct order when using `--sort-by .metadata.name`

**What you expected to happen**:

Pods are sorted correctly, `1..35` followed by `a..z`

**How to reproduce it (as minimally and precisely as possible)**:

I think this bug is long standing. Repro as follows

```bash
for n in {a..z} ; do kubectl run $n --image=nginx:alpine ; done
for n in {1..35} ; do kubectl run $n --image=nginx:alpine ; done 

kubectl get po --sort-by=.metadata.name 
```

Pods `u`, `m`, `n`, `k` come out first in the order and in that order.

**Anything else we need to know?**:

I have traced this to here

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/get/sorter.go#L276

These pod names are incorrectly being identified as SI quantities, when without a numerical quantity they should be treated as plain strings. Having said that, a pod name is *never* an SI quantity, so perhaps this logic should only be used for fields where a quantity can be expected.

**Environment**:
-   Client Version: v1.28.1
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.1

- Killercoda playground, although as mentioned I think this is long standing
- Ubuntu 20.04 LTS

**Comment by fireflycons** [comment]
Raised related issue - https://github.com/kubernetes/apimachinery/issues/165

**Comment by Ithrael** [comment]
For these letters "eEinumkKMGTP", ParseQurantity will parse them as SI, which is likely its normal logic. I believe in the 'orderby name' use case, we wouldn't expect 'name' to be parsed as SI, hence we may need to add an option? Something like --parse-qurantity=false(default true)

**Comment by fireflycons** [comment]
Hmm that smells too much of a workaround. "Ok, I want to sort by `metadata.name`, but I have to remember to use `--parse-quantity=false` to not get odd results". That'll be a bit much for learners.

Much nicer (and I know, much more work), would be to encode that in the internal representation of an object's schema so that the sorter can use this information. Bit more work for CRD developers too.

**Comment by fireflycons** [comment]
Perhaps SI values are an entirely new type in the type system?

**Comment by fireflycons** [comment]
Either that, or to be treated as SI, a value *must* have a numeric component prior to any recognizable unit. Issue is that a string literal value of e.g. `k` is assumed to be SI, when it clearly isn't.
