### ISSUE TITLE
Include CronJob timezone in kubectl output

### ISSUE THREAD

**Issue by command-tab** [kubernetes/kubectl#1519]
Following the [addition of CronJob timezone support](https://github.com/kubernetes/enhancements/issues/3140), it would be very helpful to have those timezones displayed in the output of `kubectl`. Currently, listing CronJobs shows their schedule/cron expressions, but the timezone is absent.

**What would you like to be added**:

Either in the SCHEDULE column, or perhaps a separate column — whichever makes the most sense — include each CronJob's timezone.

**Why is this needed**:

Knowing the CronJob's timezone is equally as important as the cron expression itself. Absence of the timezone can very easily cause confusion about when the CronJob is expected to run versus when it will actually run.

**Comment by ardaguclu** [comment]
In which command's output?. Could you please check describe command for this resource. If timezone is not added there, I think, it is reasonable to add in describe.
