### ISSUE TITLE
The Test Framework should not require special treatment in pre-commit.sh

### ISSUE THREAD

**Issue by totherme** [kubernetes/kubectl#152]
There is an MVP of the test framework discussed in #87 , but it relies on having special treatment in pre-commit.sh to pass the travis tests. In particular:

- The test framework directory is currently exempt from having to run `go test ./...`
- Instead, a custom script `pkg/framework/test/scripts/run-tests.sh` is called, which runs the tests using the ginkgo CLI

The tests of the test framework should be changed so as not to require this special treatment. At first glance, this will involve:

- Changing the framework to bring up etcd and the apiserver on random unused ports, instead of the default ones
- Having sensible defaults for all environment variables that the framework relies on.

This issue began as a conversation with @apelisse in #149

**Comment by totherme** [comment]
@hoegaarden and I would like to work on this please.

cc @seans3 @mengqiy I would like to take this

**Comment by apelisse** [comment]
Since you are part of the org, I think you can just do `/assign` to get it assigned to you.

/assign @totherme @hoegaarden
