### ISSUE TITLE
Make `kubectl log deployment/foo` read logs from **all** pods

### ISSUE THREAD

**Issue by guettli** [kubernetes/kubectl#1520]
**What would you like to be added**:

Up to now, `kubectl log deployment/foo` outputs the logs of **one** pod:

```
❯ kubectl logs deployments/foo --follow >> foo.log
Found 2 pods, using pod/foo-647ffff4b6-k9c5c
```

It would be very handy if `kubectl` could output the logs of all pods of the deployment.

**Why is this needed**:

The workaround is to use label selectors:

```
kubectl logs -l app=myapp
```

But that's not easily automated.

Imagine you get the name and the namespace of a deployment in a script.

There is no easy and automated way to get the matching label selector.

It would be great if `kubectl` could support reading the logs from **all** pods of a deployment.

Related thread on slack: https://kubernetes.slack.com/archives/C2GL57FJ4/p1700558613585049?thread_ts=1700558613.585049&cid=C2GL57FJ4

**Comment by apelisse** [comment]
@ankritisachan is the best person to work on this feature, thanks for taking this!

**Comment by soltysh** [comment]
`kubectl logs --help` is your friend, you'll find there:
```
...
Options:
    --all-containers=false:
	Get all containers' logs in the pod(s).
...
```
That flag should do what you're looking for.

**Comment by soltysh** [comment]
Misread the bit about `--all-pods`.

**Comment by ardaguclu** [comment]
I needed this feature a couple of times and support the implementation.

**Comment by ahmetb** [comment]
What would the behavior be while the `kubectl logs` command is running, and new pods spin up (or go away)? Would these be noted explicitly?
Third-party tools like https://github.com/stern/stern or https://github.com/boz/kail support this scenario to some extent.

**Comment by guettli** [comment]
@ahmetb good question. I would like to see the logs of the new pods, too.

**Comment by cmwylie19** [comment]
> @cmwylie19 has a PR ready to ship soon for this.

/assign

**Comment by eddiezane** [comment]
@ahmetb to answer your question I think that functionality should be coupled to `--follow` instead of us adding a `--all-pods` here. Should be a separate issue if we decide to change the functionality for new pods/replicas/etc.

Thoughts?

**Comment by cmwylie19** [comment]
WIP - https://github.com/kubernetes/kubernetes/pull/123874
