### ISSUE TITLE
kubectl config set-credentials add`interactive-mode` and `provide-cluster-info` options

### ISSUE THREAD

**Issue by luisyonaldo** [kubernetes/kubectl#1521]
#### What would you like to be added:
Add `--exec-interactive-mode` and  `--exec-provide-cluster-info` to `kubectl config set-crendtials` command.

Example:
```console
kubectl config set-credentials NAME --exec-command=<command> --exec-api-version=<version> \
    --exec-interactive-mode=<mode>
    --exec-provide-cluster-info
```

#### Why is this needed:
`interactiveMode` is a required field in`client.authentication.k8s.io/v1` API version , which means it is not possible to set the minimum set of fields/options needed to [configure](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration) client-go credential plugins via `kubectl`. 

Manual configuration of `kubeconfig` is needed to add both `interactiveMode` and `provideClusterInfo`.

**Comment by ardaguclu** [comment]
As stated in the description of issue, `interactiveMode` and `provideClusterInfo` fields are required fields for exec plugins and to generate a working credentials exec plugin configuration in kubeconfig, user has to specify `interactiveMode` and current without these flags, generated config is incomplete and invalid. Thus, I'm reopening this;

/reopen
/triage accepted
/priority backlog

**Comment by ardaguclu** [comment]
Could you please run `kubectl version`? and could you please run `kubectl config set-credentials --help` (and can you see the flag in there)?

**Comment by ardaguclu** [comment]
I am not sure how this can be possible if the kubectl is the latest version.

**Comment by VF-mbrauer** [comment]
```
./kubectl version                                                                    
Client Version: v1.30.0-alpha.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

```
    --exec-interactive-mode='':
	InteractiveMode of the exec credentials plugin for the user entry in kubeconfig

    --exec-provide-cluster-info=false:
	ProvideClusterInfo of the exec credentials plugin for the user entry in kubeconfig

    --password='':
	password for the user entry in kubeconfig

    --token='':
	token for the user entry in kubeconfig

    --username='':
	username for the user entry in kubeconfig

Usage:
  kubectl config set-credentials NAME [--client-certificate=path/to/certfile] [--client-key=path/to/keyfile]
[--token=bearer_token] [--username=basic_user] [--password=basic_password] [--auth-provider=provider_name]
[--auth-provider-arg=key=value] [--exec-command=exec_command] [--exec-api-version=exec_api_version] [--exec-arg=arg]
[--exec-env=key=value] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by ardaguclu** [comment]
And you ran the command like the one in the example `kubectl config set-credentials cluster-admin --exec-command=/path/to/the/executable
--exec-api-version=client.authentication.k8s.io/v1beta1 --exec-interactive-mode=Never` and it didn't work?

**Comment by ardaguclu** [comment]
This command works for me;

```sh
$ kubectl config set-credentials cluster-admin --exec-command=/path/to/the/executable --exec-api-version=client.authentication.k8s.io/v1beta1 --exec-interactive-mode=IfAvailable
```

**Comment by VF-mbrauer** [comment]
OK, was a caching issue wrong path to the binary. My fault. Works also on my side. Thanks for the time and sorry for the confusion.
