### ISSUE TITLE
The Test Framework's test fakes shouldn't be so tightly coupled with the implementations they test

### ISSUE THREAD

**Issue by totherme** [kubernetes/kubectl#153]
In the test framework MVP (discussed in #87 ), there is currently a tight coupling between the test fakes `pkg/frameworks/test/assets/fakeetcd/` and `etcd.go`. In particular, both of these currently know the exact flags that `etcd` ought to be called with. There is a similar issue with the apiserver fake.

We should find a way to adequately test this wiring which doesn't leave us with tightly coupled test-doubles like this. This might involve leaning more heavily on the integration tests for the happy path, and removing the unit-level happy path tests.

This issue began as a conversation with @apelisse in #149

**Comment by totherme** [comment]
After investigating, we think that fixing this issue will make #152 easier, so we'd like to start with this.

@hoegaarden and I would like to work on this please.

cc @seans3 @mengqiy I would like to take this

**Comment by hoegaarden** [comment]
As #154 & #155 are merged, this issue can be closed.
@totherme @apelisse

**Comment by apelisse** [comment]
I think you can use `/close` or something :D
