### ISSUE TITLE
kubectl debug attach broken in 1.29.0 (?)

### ISSUE THREAD

**Issue by tberreis** [kubernetes/kubectl#1539]
kubectl debug doesn't wait for containers to start running, even with --attach=true

**What happened**:
Running a simple command like the following shows some changes between 1.28.4 and 1.29.0:

```
[root ~ ☸️:(e2e1-prd:traefik)]# time ./kubectl-1.29.0 debug --attach traefik-5fc566d649-ff6dj --image=docker.io/curlimages/curl:latest --profile=restricted -- /bin/sh -c "$(printf 'sleep 10; foobar 2>/dev/null; echo "$?"')"
Defaulting debug container name to debugger-h855p.

real    0m0.364s
user    0m0.087s
sys     0m0.042s

[root ~ ☸️:(e2e1-prd:traefik)]# time ./kubectl-1.28.4 debug --attach traefik-5fc566d649-ff6dj --image=docker.io/curlimages/curl:latest --profile=restricted -- /bin/sh -c "$(printf 'sleep 10; foobar 2>/dev/null; echo "$?"')"
Defaulting debug container name to debugger-4hwsg.
If you don't see a command prompt, try pressing enter.
127

real    0m11.156s
user    0m0.089s
sys     0m0.062s
```

**What you expected to happen**:
- same output as with 1.28.4
- attach as if 'kubectl attach ...' were called

**How to reproduce it (as minimally and precisely as possible)**:

see command above

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: v1.28.4 / v1.29.0
- Cloud provider or hardware configuration:
AKS 1.28.3, Ubuntu 22.04.3 LTS
- OS (e.g: `cat /etc/os-release`):
Oracle Linux Server release 9.3

**Comment by ardaguclu** [comment]
/assign
I'm investigating this

**Comment by ardaguclu** [comment]
Thanks for opening this issue @tberreis. That is indeed a bug and I opened a PR to fix it.
