### ISSUE TITLE
Minor fix in the --help output for "kubectl create secret tls"

### ISSUE THREAD

**Issue by adityasamant25** [kubernetes/kubectl#1541]
**What happened**:
On executing `kubectl create secret tls --help`, the output is as follows
Examples:
   Create a new TLS secret named tls-secret with the given key pair
  `kubectl create secret tls tls-secret --cert=path/to/tls.cert --key=path/to/tls.key`

There is no extension as .cert

**What you expected to happen**:
The --cert=path/to/tls.cert should be changed to --cert=path/to/tls.crt

**How to reproduce it (as minimally and precisely as possible)**:

Run `kubectl create secret tls --help`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.29.0
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.3 LTS

**Comment by kushalShukla-web** [comment]
issue open ?

**Comment by adityasamant25** [comment]
> issue open ?

I upgraded to kubectl version 1.29.3

```
kubectl version --client
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

I see the issue still exists in this version. I am unsure in which version the fix in PR https://github.com/kubernetes/kubernetes/pull/122523 will be released.

```
kubectl create secret tls --help

Examples:
  # Create a new TLS secret named tls-secret with the given key pair
  kubectl create secret tls tls-secret --cert=path/to/tls.cert --key=path/to/tls.key
```

**Comment by mpuckett159** [comment]
/close
Looks like the PR got merged for this already.
