### ISSUE TITLE
kubectl v1.29.1 delay is very high.

### ISSUE THREAD

**Issue by ByteFlyCoding** [kubernetes/kubectl#1552]
# Problem
After I install kubectl@v1.29.1.(`curl -LO "https://dl.k8s.io/release/v1.29.1/bin/darwin/arm64/kubectl"`). I found that the kubectl delay is very high when I use kubectl command such as `kubectl get pod` 、`kubectl get node`. But when I use kubectl@v1.23.5, the command response is very quick. Why not appear this phenomenon？

```
xxx@xxx-MBP ~ % kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
xxx@xxx-MBP ~ % time kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
kubectl version  0.04s user 0.02s system 1% cpu 5.083 total
xxx@xxx-MBP ~ % time kubectl get pod
No resources found in default namespace.
kubectl get pod  0.06s user 0.02s system 1% cpu 5.092 total
xxx@xxx-MBP ~ % time kubectl get node
NAME             STATUS   ROLES           AGE    VERSION
docker-desktop   Ready    control-plane   167m   v1.29.1
kubectl get node  0.06s user 0.02s system 1% cpu 5.087 total
xxx@xxx-MBP ~ %
xxx@xxx-MBP ~ % 
xxx@xxx-MBP ~ % 
xxx@xxx-MBP ~ % cd go/bin
xxx@xxx-MBP bin % time ./kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.1", GitCommit:"bc401b91f2782410b3fb3f9acf43a995c4de90d2", GitTreeState:"clean", BuildDate:"2024-01-17T15:41:12Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.23) and server (1.29) exceeds the supported minor version skew of +/-1
./kubectl version  0.04s user 0.02s system 73% cpu 0.081 total
xxx@xxx-MBP bin % time ./kubectl get pod
No resources found in default namespace.
./kubectl get pod  0.07s user 0.06s system 34% cpu 0.353 total
xxx@xxx-MBP bin % time ./kubectl get node
NAME             STATUS   ROLES           AGE    VERSION
docker-desktop   Ready    control-plane   170m   v1.29.1
./kubectl get node  0.05s user 0.02s system 84% cpu 0.078 total
xxx@xxx-MBP bin % 
```

**Comment by ByteFlyCoding** [comment]
This issue is the same to my face.

**Comment by ardaguclu** [comment]
The referenced issue is more about the commands that don't talk to API server. As far as I can see, your case is when you talk to API server.
* Have you checked that the 1.23.5 works good against 1.29.1 cluster? or you tested 1.23.5 against 1.23.5 cluster?
* There are new features introduced in newer versions comparing to 1.23.5 such as aggregated discovery, etc.. I'd suggest to run commands with `-v=9` to see which API request particularly slow.
* If this is a freshly installed cluster, perhaps there are some services running to achieve until stabilization?

**Comment by ByteFlyCoding** [comment]
This maybe cause by domain name. I found that it can work normal when I modify `clusters.cluster.server=https://kubernetes.docker.internal:6443` into `https://127.0.0.1:6443`  in the kubeconfig file. `127.0.0.1 kubernetes.docker.internal` was added into /etc/hosts by docker-desktop.

**Comment by mpuckett159** [comment]
Hi, yes this sounds like it is likely a timeout issue related to DNS lookups that eventually fails back to looking at /etc/hosts where it can properly resolve the name. I believe that this is not a kubectl issue but like you say a DNS issue. If you find this to be a kubectl issue please re-open.

/close
