### ISSUE TITLE
secure kubectl write oprations

### ISSUE THREAD

**Issue by Zeel-Patel** [kubernetes/kubectl#1563]
Hi, can we have a feature on kubectl command executions which takes user confirmation before executing any write operation on the cluster?

So, if I do
kubectl delete nodes --all

`It tells me that the current context is this. Continue? `

So that users do not execute any write operations on a wrong cluster accidentlly.
It can be made optional if one wants to enable safe writes or not.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/kubectl/issues/1234#issuecomment-1199296638

**Comment by sftim** [comment]
If we built this in to `kubectl`, I'd want an environment variable that specifies a command to do the confirming, and built-in code unless one isn't specified.

I have a [similar thing](https://github.com/sftim/environment-public/blob/ffd2e1c76742cc1a338812ce4164f7501b73a981/bin/getconfirm-pinentry) I use locally, not specific to `kubectl`:
```bash
confirm ()
{
    args=("$@");
    getconfirm-pinentry "$( printf "%q " "${args[@]}" )" && "$@"
}
```

Example usage: `confirm kubectl delete namespace production` (which will give me a GUI prompt and a button to click if I think I'm sure). It'd be nice to let people integrate with this kind of existing tooling.

**Comment by Zeel-Patel** [comment]
@carlory, is this in production? how do I use this feature?

**Comment by ardaguclu** [comment]
It has been enabled by default by 1.29 and upwards

**Comment by Zeel-Patel** [comment]
ack, thanks all.
