### ISSUE TITLE
goleak in RunNoErrOutput

### ISSUE THREAD

**Issue by Zeel-Patel** [kubernetes/kubectl#1566]
## What is the issue?
I am trying to write UTs for a function which internally calls cli.RunNoErrOutput(command)

cli -> "k8s.io/component-base/cli"

But there seems to be goleak
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 25 in state select, with k8s.io/klog/v2.(*flushDaemon).run.func1 on top of the stack:
k8s.io/klog/v2.(*flushDaemon).run.func1()
	external/io_k8s_klog_v2/klog.go:1157 +0xec
created by k8s.io/klog/v2.(*flushDaemon).run in goroutine 43
	external/io_k8s_klog_v2/klog.go:1153 +0x19c
]
```

What can be possible reason?

## How to reproduce?

Define run method

```
func run(args []string) error {
	command := cmd.NewDefaultKubectlCommandWithArgs(cmd.KubectlOptions{
		PluginHandler: cmd.NewDefaultPluginHandler(plugin.ValidPluginFilenamePrefixes),
		Arguments:     args,
		IOStreams:     genericclioptions.IOStreams{In: os.Stdin, Out: os.Stdout, ErrOut: os.Stderr},
		ConfigFlags: genericclioptions.NewConfigFlags(true).
			WithWrapConfigFn(func(c *rest.Config) *rest.Config {

				return c
			}),
	})
	return cli.RunNoErrOutput(command)
}
```

Define test for run() in test file
```
func Test_run(t *testing.T) {

	tests := []struct {
		name    string
		args    []string
		wantErr bool
	}{
		{
			name:    "success",
			args:    []string{"kubectl", "get", "--help"},
			wantErr: false,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := run(test.args)
			if test.wantErr {
				require.NotNil(t, err)
			} else {
				require.Nil(t, err)
			}
		})
	}
}
```

Run test, test run will fail with error above

**Comment by mpuckett159** [comment]
/needs-information
Please provide a method of reproduction so we can verify this and investigate further.

**Comment by Zeel-Patel** [comment]
@mpuckett159 , edited the question with info.

**Comment by mpuckett159** [comment]
/close
Closing the issue, this seems to be related to klog according to the output in the error trace (if I'm wrong please correct me) which is not something that SIG-CLI owns, this would be better suited in the kubernetes/klog repo, but as I also understand this is a fork of golang/glog, so this may be something to fix even farther upstream in that repo, I'm unsure. If the fix truly needs to happen in our code, we would accept a PR to fix it.
