### ISSUE TITLE
weird behaviour of kubectl debug set-image under ohmyzsh

### ISSUE THREAD

**Issue by warjiang** [kubernetes/kubectl#1569]
**What would you like to be added**:
![image](https://github.com/kubernetes/kubectl/assets/6478745/68f80f9f-9581-43b8-b97a-4d6bcc3601d4)
change the example of set-image option

```shell
kubectl debug mypod --copy-to=my-debugger --set-image="*=busybox"
kubectl debug mypod -it --copy-to=my-debugger --image=debian --set-image="app=app:debug,sidecar=sidecar:debug"
```

**Why is this needed**:

when i follow the examples in ` kubectl debug -h`, when i try to set-image for debug containers, a mistake occured like following: 
![image](https://github.com/kubernetes/kubectl/assets/6478745/9a9ae41e-da83-4910-9691-af9eaa0163cc)

and i found a releated issue of ohmyzsh: https://github.com/ohmyzsh/ohmyzsh/issues/31
after add double quote, it worked as expecte. 
![image](https://github.com/kubernetes/kubectl/assets/6478745/76dd962d-89d2-4a15-8e5c-a034baa6a9a4)

so i suggest that correct the example.

**Comment by ah8ad3** [comment]
This issue is not a `kubectl` issue, many commands have the same issue when using `ohmyzsh`, did you consider this comment?
https://github.com/ohmyzsh/ohmyzsh/issues/31#issuecomment-359728582
> `unsetopt nomatch`

**Comment by warjiang** [comment]
> This issue is not a `kubectl` issue, many commands have the same issue when using `ohmyzsh`, did you consider this comment? [ohmyzsh/ohmyzsh#31 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/31#issuecomment-359728582)
> 
> > `unsetopt nomatch`
yeah, maybe the maintainer of kubectl can update the example, this will be useful for people who not very familiar with kubectl. When i first use kubectl debug command, it make me confused.

**Comment by eddiezane** [comment]
Going to close the issue but we would accept a PR if you want to make one and tag me.

/close
