### ISSUE TITLE
Update kustomize to a version that supports oci repos

### ISSUE THREAD

**Issue by Griznah** [kubernetes/kubectl#1572]
**What would you like to be added**:
A current version of kustomize, ie. https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.3.0
**Why is this needed**:
To use built in kustomize with OCI helm repos as added in https://github.com/kubernetes-sigs/kustomize/pull/5167

**Comment by lucsoft** [comment]
Took me a while to find out that my newest version of kubectl doesn't ship with the newest version of kustomize? Tried to debug why oci helm charts arent working... now i found the issue. Why does kubectl not just use the latest version of kustomize?

**Comment by lucsoft** [comment]
Current main has pinned a version for over 10 months, thats crazy :D 
![image](https://github.com/kubernetes/kubectl/assets/11093382/5c96df1c-b698-4630-bd69-0c9e971664cd)

**Comment by eddiezane** [comment]
@koba1t how do you want to handle bumping kustomize in kubectl going forward?

**Comment by koba1t** [comment]
@eddiezane 
I plan to `kustomize maintainer` update kustomize in kubectl when we release a new version.
I think it means we keep the current flow.

**Comment by koba1t** [comment]
I created a PR that updates kustomize-in-kubectl.
https://github.com/kubernetes/kubernetes/pull/124217#issuecomment-2041367976

**Comment by ardaguclu** [comment]
I believe that this is completed;

/close
