### ISSUE TITLE
Support for ignoring files when using `kubectl apply -f .`

### ISSUE THREAD

**Issue by wiktor-k** [kubernetes/kubectl#1583]
**What would you like to be added**:

Support for ignoring files when using `kubectl apply -f .`, e.g. by introducing the `.kubeignore` file (similar to `.gitignore`, `.dockerignore`).

**Why is this needed**:

I'm using ApplySets to manage a consistent state of the cluster that matches a directory:

```sh
KUBECTL_APPLYSET=true kubectl apply -f . --recursive --prune --applyset=apps --namespace apps
```

And in the same directory I need to keep a couple of files that help in development (e.g. [kubelinter](https://github.com/stackrox/kube-linter)). Currently the output is:

```
service/currencies unchanged
cronjob.batch/turn-checker unchanged
...
error: error validating ".kube-linter.yml":
error validating data: [apiVersion not set, kind not set];
if you choose to ignore these errors, turn validation off with --validate=false
```

Of course I don't want to disable the validation.

Alternative solution would be ignoring hidden files (prefixed with a `.`).

(I've searched the issues and except for [this ticket](https://github.com/kubernetes/kubectl/issues/1318) there were no matches).

Thanks for your time and work on this great tool! :wave:

**Comment by ah8ad3** [comment]
I am not sure but think you can achieve this by using [Kustomize](https://kustomize.io/).
But seems like a good idea to have this option too, +1 for me, but IDK about limitation there might be some. I'll try to ask this in SIG's meeting next week.

**Comment by mpuckett159** [comment]
/close
In addition to kustomize this could also be accomplished via shell scripting or a plugin. Closing this issue as it is possible using other tooling.
