### ISSUE TITLE
kubectl: Pod with deletionTimestamp shown as Terminating after Failed/Succeeded

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubectl#1595]
### What happened?

A pod with a finalizer and a deletion timestamp is listed as "Terminating" in kubectl get and describe, even after the phase is Failed/Succeeded

### What did you expect to happen?

The phase Failed or Succeeded to be shown

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a long running pod with a finalizer
2. Issue a pod delete
3. Use `kubectl get -o wide` or `kubectl describe` to see the pod.

### Anything else we need to know?

This causes confusion, as the Pod doesn't account for any resource usage when its Failed or Succeeded.
This should be backported to all supported versions.

### Kubernetes version

<details>

master

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mpuckett159** [comment]
In addition to the linked PR, in pkg/describe it looks like this is being set statically/manually (search for "Terminating") and this will probably be confusing and need to be cleaned up as well so that describe is not setting things that contradict get.

/triage accepted

**Comment by brianpursley** [comment]
My only concern is whether users need to know that a finalizer is pending, but "Terminating" status doesn't distinguish between waiting for containers to exit and waiting for finalizers to complete, so this change makes it more clear what is happening.

If people need to know that finalizers are pending, versus just seeing Completed or Failed, we could potentially show a status of "Finalizing", but that hasn't been asked for yet as far as I know.
