### ISSUE TITLE
error when deploying 'e2e-test-images/agnhost' via "Hello Minikube" tutorial on Windows

### ISSUE THREAD

**Issue by SergeiPavlitz** [kubernetes/kubectl#1599]
**What happened**:
I've got an error during deploying 'e2e-test-images/agnhost' via "Hello Minikube" tutorial on Windows.
The report is created regarding this [comment](https://github.com/kubernetes/website/issues/46219#issuecomment-2100146915).
To bypass the problem I used the following command:
kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0 ([from section 4](https://minikube.sigs.k8s.io/docs/start/)).

**What you expected to happen**:
The deployment without errors.

**How to reproduce it (as minimally and precisely as possible)**:
to reproduce look [here](https://github.com/kubernetes/website/issues/46219#issue-2280343125).

**Anything else we need to know?**:

**Environment**:
My OS: Windows 10 home. I use docker driver, because Hyper-V doesn't exist in windows 10 home.

**Comment by gnufred** [comment]
If I understand your issue properly, you ran the following command:

```
kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080
```

And you got the following error?

```
Warning Failed pod/hello-node-7c7b95ff98-phftk Error: failed to start container "agnhost": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "C:/Program Files/Git/agnhost": stat C:/Program Files/Git/agnhost: no such file or directory: unknown
```

The command works as expected for me with my current setup.

**Please provide more information on this issue.**

First, can you tell me which version of kubectl you have installed while running this command?

Could you run `kubectl -v=10 create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080` and provide the result here? Please make sure to remove your personnal folders and IPs from the logs.

**Comment by brianpursley** [comment]
I don't think Windows cmd.exe knows how to handle the `--` separator.

Can you try it using Powershell?

Or wsl?

**Comment by mwanser1** [comment]
> I don't think Windows cmd.exe knows how to handle the `--` separator.
> 
> 
> 
> Can you try it using Powershell?
> 
> 
> 
> Or wsl?

I ran into this issue today running the command from a git bash terminal on windows 10. Kubectl version 1.30, Minikube 1.33.1.  

But it did work in powershell and cmd.  

I did confirm that when running from git bash the container command does have the C:/Program Files/Git/agnhost which was suspected as the culprit in the original [issue](https://github.com/kubernetes/website/issues/46219#issuecomment-2097621625)

**Comment by Ahnaf-Ahmed** [comment]
> > I don't think Windows cmd.exe knows how to handle the `--` separator.
> > Can you try it using Powershell?
> > Or wsl?
> 
> I ran into this issue today running the command from a git bash terminal on windows 10. Kubectl version 1.30, Minikube 1.33.1.
> 
> But it did work in powershell and cmd.
> 
> I did confirm that when running from git bash the container command does have the C:/Program Files/Git/agnhost which was suspected as the culprit in the original [issue](https://github.com/kubernetes/website/issues/46219#issuecomment-2097621625)

Thanks so much. Can second that using git bash causes issues and powershell works in windows 11 kubectl v1.30.0 and Minikube v1.33.1

**Comment by JonesKwameOsei** [comment]
@Ahnaf-Ahmed thanks for the info. powershell worked for me too.

**Comment by jude-san** [comment]
Thanks guys 🙌

**Comment by ardaguclu** [comment]
I think, problem seems to be resolved and there is no bug in kubectl
/close
