### ISSUE TITLE
Confirmation Prompt for Delete Commands

### ISSUE THREAD

**Issue by amrabdelshafi97** [kubernetes/kubectl#1602]
**Description:**
To enhance safety and minimize human error, especially given recent incidents where a single delete command resulted in the deletion of all resources within a namespace, I propose the addition of a confirmation prompt following the execution of a delete command. This prompt should first display the resources that will be affected by running the equivalent `get` command and then ask the user to confirm whether they truly want to proceed with the deletion.

**Implementation Details:**
1. **Command Execution:**
   - When a delete command is issued, the system should automatically run the equivalent `get` command to list the resources that match the delete criteria.
   
2. **Display Resources:**
   - Display the list of resources that will be affected by the delete command to the user.
   
3. **Confirmation Prompt:**
   - Prompt the user with a message asking for confirmation to proceed with the deletion.
   - Example message: “You are about to delete the following resources: [list of resources]. Do you want to continue? (yes/no)”

**Why This Is Needed:**
- To enhance safety by providing a visual confirmation of the resources that will be deleted.
- To reduce the risk of accidental deletion of critical resources.
- To provide an additional step for the user to verify their intent, thereby mitigating the risk of human errors.

**Comment by ardaguclu** [comment]
This feature exists https://github.com/kubernetes/kubectl/blob/382ad8ff117ae966d9efd9380295d77d00c6cb7e/pkg/cmd/delete/delete_flags.go#L163-L165 and tracked by https://github.com/kubernetes/enhancements/issues/3895

**Comment by amrabdelshafi97** [comment]
Do you think this flag should be true by default instead? Is it something you are planning to do in the future?

**Comment by ardaguclu** [comment]
Unfortunately it can't be true as it breaks all the scripts currently running successfully. We are planning to introduce a new preferences feature https://github.com/kubernetes/enhancements/issues/3104 and `--interactive` flag can be set to true as default within this preferences file.

**Comment by ardaguclu** [comment]
As this has already done, I'm closing this issue;
/close
