### ISSUE TITLE
Symlink support for kubectl apply --recursive=true

### ISSUE THREAD

**Issue by cospeedster** [kubernetes/kubectl#1603]
**What would you like to be added**:

Symlink support for `kubectl apply --filename=. --recursive=true`

```text
.
├── all
│   └── policies.yaml
├── dev
│   └── manifests
│       ├── all-manifests -> ../../all/
│       └── example-manifest.yaml
├── prod
│   └── manifests
│       ├── all-manifests -> ../../all/
│       └── example-manifest.yaml
└── stage
    └── manifests
        ├── all-manifests -> ../../all/
        └── example-manifest.yaml
```

**Why is this needed**:

Sometimes we organize manifests per environment in different directories. But some manifests are equal in each environment. for this we have an `all` directory with manifests which have to be applied for all environments like policies.

**Comment by ardaguclu** [comment]
In my opinion, this would negatively impact the security. Bad actors would define symlinks of various unlisted yaml definitions and blindly applying these resources seems to be not preferable.

**Comment by cospeedster** [comment]
Unfortunately, this sounds like a valid point.

Maybe we could think about an cli option to accept this behavior explicitly? I don't know if that's a good idea.

**Comment by cospeedster** [comment]
Yes, there is definitely a workaround. There is almost always one. That just makes our deployments a little more complex.

I can live with that, but I still wanted to put the topic up for discussion here.
