### ISSUE TITLE
kube-apiserver drops connection from kubectl after 1 minute

### ISSUE THREAD

**Issue by los93sol** [kubernetes/kubectl#1606]
**What happened**:
I have ingress-nginx in front of kube-apiserver in a k3s setup on bare metal.  I have configured all the timeout settings in ingress-nginx proxy-read-timeout, proxy-send-timeout, etc.  Running kubectl exec or kubectl port-forward both work, but the connection just closes unexpectedly after approx. 1 minute.  I'm at a loss as to what the cause is or how to find more info.  I have also tried enabling PortForwardWebsocket feature gate and verified it was working, but regardless what I do, I end up with an error from kubectl about SPDY Ping failures.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.30
- Cloud provider or hardware configuration: bare-metal
- OS (e.g: `cat /etc/os-release`): k3s

**Comment by ardaguclu** [comment]
SPDY pings causing problems is a well known issue and I don't think there is alternative solution apart from using this feature https://github.com/kubernetes/enhancements/issues/4006

**Comment by ardaguclu** [comment]
Enabling `PortForwardWebsocket` is not sufficient, you also need to enable in kubectl side by exporting the environment variable `KUBECTL_PORT_FORWARD_WEBSOCKETS=true`

**Comment by los93sol** [comment]
This ended up not being caused by asymmetric routing.
