### ISSUE TITLE
kubectl create --validate flag help has excessive spacing between sentences.

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubectl#1613]
**What happened**:
`kubectl create --help`

Notice excessive spacing before some sentences.
```
    --validate='strict':
	Must be one of: strict (or true), warn, ignore (or false). 		"true" or "strict" will use a schema to validate
	the input and fail the request if invalid. It will perform server side validation if ServerSideFieldValidation
	is enabled on the api-server, but will fall back to less reliable client-side validation if not. 		"warn" will
	warn about unknown or duplicate fields without blocking the request if server-side field validation is enabled
	on the API server, and behave as "ignore" otherwise. 		"false" or "ignore" will not perform any schema
	validation, silently dropping any unknown or duplicate fields.
```

**What you expected to happen**:
There should be regular spacing between sentences.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl create --help`

**Anything else we need to know?**:
Looks like the problem is here. I don't think the flag usage argument can handle newlines, so it should probably just format it as a single paragraph with no newlines.
https://github.com/kubernetes/kubernetes/blob/5300466a5c8988b479a151ceb77f49dd00065c83/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go#L451-L458

/good-first-issue

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `Client Version: v1.31.0-alpha.0.496+a9eded097d0923-dirty`
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): `Ubuntu 22.04.4 LTS`

**Comment by harpreet9ja** [comment]
cc @brianpursley cc @seans3 @mengqiy I would like to take this
