### ISSUE TITLE
VSCode as kubectl editor is not returning to terminal until I quit VSCode completely

### ISSUE THREAD

**Issue by parveenksharma** [kubernetes/kubectl#1616]
On my mac Ventura in my ~/.bash_profile  I have :
`export KUBE_EDITOR='open -a "Visual Studio Code" --wait'`

and it is opening the new VSCode window with command on terminal:
`kubectl edit pod fooapp`

The problem is once I am done editing the yml and save it and close the associated VSCode window  the control is not returning to terminal.
For that I have to Quit VSCode completely.

This is very inconvenient as this is resulting in closing all my other open / work in progress files with VSCode .

Please suggest.

**Comment by mpuckett159** [comment]
I suspect that Visual Studio Code is doing something that prevents kubectl from detecting if the window that was spawned is ever closed, and so it thinks that the edit is still in progress and you have to kill the entire VSCode process to get it to see that the window is closed. This feature was created quite a while ago and I think it expects there to be separate process or something that it can watch to stop and the way VSCode works doesn't allow for that. If these suggestions that Brian made don't work, I don't think we can accomadate how VSCode works unfortunately.

/close
