### ISSUE TITLE
Port forwarding dies after cancelling a TCP request

### ISSUE THREAD

**Issue by ramondeklein** [kubernetes/kubectl#1620]
I use `kubectl port-forward` to forward traffic to a service and sometimes the service is not reachable anymore. After some investigation it looks like the port forwarding cannot handle with cancelled TCP requests and the port-forwarding locks up and showed the following error message:
```
E0705 12:50:42.897359   76107 portforward.go:394] error copying from local connection to remote stream: read tcp6 [::1]:8080->[::1]:44368: read: connection reset by peer
E0705 12:50:42.897360   76107 portforward.go:381] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:44368: write tcp6 [::1]:8080->[::1]:44368: write: broken pipe
```
The `kubectl` process keeps running, but the port-forwarding is dead. Restarting `kubectl port-forward` brings the service back alive.

I have created a very [basic application (in Go)](https://github.com/ramondeklein/k8s-portforward-bug/blob/master/server.go) that serves a 32MiB file and it can be invoked using `curl -o /dev/null http://localhost:8080` and it will complete the download. When running `curl http://localhost:8080`, it will cancel the download after the request, because it won't display binary data. This application works fine locally.

When run in Kubernetes and using `kubectl port-forward server 8080:8080` it works fine when files are downloaded, but it locks up when a download is cancelled. It looks like `kubectl` is still accepting requests on port 8080, but doesn't seem to be able to contact the pod anymore.

I tested with both Kubernetes v1.30 (using a single node [Kind](https://kind.sigs.k8s.io/) cluster) and in Kubernetes v1.29 using AKS (MS Azure). A full ready-to-run reproduction is available on https://github.com/ramondeklein/k8s-portforward-bug.

**Comment by ramondeklein** [comment]
Maybe a duplicate of https://github.com/containerd/containerd/issues/9875, but my repo may add a test scenario.

**Comment by mpuckett159** [comment]
Sorry to ask this but we just enabled websockets as the default protocol for port forwarding, which should (I think) resolve this. It graduated to Beta in 1.31 (so it's on by default) could you try upgrading to that version or running this on that version? If not you can try enabling the alpha version of the feature on a 1.30 cluster, but you need access to be able to edit the flags provided to the api-server to enable it fully.

`PortForwardWebsockets=true` for the api-server flag and `KUBECTL_REMOTE_COMMAND_WEBSOCKETS=true` for the kubectl environment variable to enable the feature in 1.30.

**Comment by mpuckett159** [comment]
/close
Closing for now, please let me know if websockets did not solve this for you.

**Comment by ramondeklein** [comment]
Sorry for the delay, but I was pretty busy. I tested using Kubernetes v1.30:
```bash
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```
I deployed a new cluster using Kind and enabled the `PortForwardWebsockets=true` feature gate:
```json
$ kubectl get pod -n kube-system kube-apiserver-wstest-control-plane -o jsonpath='{.spec.containers[0].command}' | jq .
[
  "kube-apiserver",
  "--advertise-address=172.21.0.19",
  "--allow-privileged=true",
  "--authorization-mode=Node,RBAC",
  "--client-ca-file=/etc/kubernetes/pki/ca.crt",
  "--enable-admission-plugins=NodeRestriction",
  "--enable-bootstrap-token-auth=true",
  "--etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt",
  "--etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt",
  "--etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key",
  "--etcd-servers=https://127.0.0.1:2379",
  "--feature-gates=PortForwardWebsockets=true",
  "--kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt",
  "--kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key",
  "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
  "--proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt",
  "--proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key",
  "--requestheader-allowed-names=front-proxy-client",
  "--requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt",
  "--requestheader-extra-headers-prefix=X-Remote-Extra-",
  "--requestheader-group-headers=X-Remote-Group",
  "--requestheader-username-headers=X-Remote-User",
  "--runtime-config=",
  "--secure-port=6443",
  "--service-account-issuer=https://kubernetes.default.svc.cluster.local",
  "--service-account-key-file=/etc/kubernetes/pki/sa.pub",
  "--service-account-signing-key-file=/etc/kubernetes/pki/sa.key",
  "--service-cluster-ip-range=10.96.0.0/16",
  "--tls-cert-file=/etc/kubernetes/pki/apiserver.crt",
  "--tls-private-key-file=/etc/kubernetes/pki/apiserver.key"
]
```
I ran the port-forward with websockets enabled, but it still doesn't work correctly:
```
$ KUBECTL_REMOTE_COMMAND_WEBSOCKETS=true kubectl port-forward service/server 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
E0815 16:15:42.722121  963229 portforward.go:385] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:60354: write tcp6 [::1]:8080->[::1]:60354: write: broken pipe
Handling connection for 8080
E0815 16:16:12.476117  963229 portforward.go:351] error creating error stream for port 8080 -> 8080: Timeout occurred
```
These are the commands that I issued:
```
$ curl http://localhost:8080
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
$ curl http://localhost:8080
curl: (56) Recv failure: Connection reset by peer
```
As you can see, the first HTTP response was received, but `curl` terminated the request (that is also what is causing this issue). The second request fails.

@mpuckett159  Switching to web-sockets doesn't seem to fix this issue...

**Comment by ramondeklein** [comment]
I also tried with the v1.31 version, but that has the same results.

These are the exact versions (I kept `PortForwardWebsockets=true` feature gate to make sure it is enabled):
```
$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0
```
I also ran `kubectl` with `KUBECTL_REMOTE_COMMAND_WEBSOCKETS=true` enabled.

**Comment by alongwill** [comment]
I think I'm seeing the same issue when use port-forwarding for https://docs.victoriametrics.com/victorialogs/.

```sh
kubectl port-forward -n monitoring service/vlogs 9428
Forwarding from 127.0.0.1:9428 -> 9428
Forwarding from [::1]:9428 -> 9428
```

If I query victoria logs and let all the log JSON be written to the terminal it works fine.
```sh
curl http://localhost:9428/select/logsql/query -d 'query=_time:1m'
...
```
However if I pipe it into `less` and then quit I see this error from curl:
```sh
curl http://localhost:9428/select/logsql/query -d 'query=_time:1m'  | less
100 96848    0 96834  100    14  52150      7  0:00:02  0:00:01  0:00:01 52181
curl: (23) Failure writing output to destination, passed 5349 returned 0
```
and this error from the `port-forward`:
```sh
Handling connection for 9428
E1212 09:40:36.927599   53516 portforward.go:398] "Unhandled Error" err="error copying from local connection to remote stream: writeto tcp6 [::1]:9428->[::1]:65046: read tcp6 [::1]:9428->[::1]:65046: read: connection reset by peer"
E1212 09:40:36.928006   53516 portforward.go:385] "Unhandled Error" err="error copying from remote stream to local connection: readfrom tcp6 [::1]:9428->[::1]:65046: write tcp6 [::1]:9428->[::1]:65046: write: broken pipe"
```

Subsequent curl requests to port 9428 no longer work, and I have to recreate the port-forward. I'm using:

```sh
kubectl version
Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.31.2
```
