### ISSUE TITLE
`kubectl explain` not re-wrapping lines

### ISSUE THREAD

**Issue by dhaiducek** [kubernetes/kubectl#1623]
**What happened**:

A description like this block that wraps at 100 characters:
```golang
 // Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pulvinar in libero id sagittis.
 // Aliquam sem enim, vehicula et urna ac, vehicula ullamcorper sem. Morbi turpis arcu, aliquet at 
 // eros quis, sodales dignissim eros. Quisque ut lectus quis magna maximus elementum a nec felis. 
 // Nulla ultricies pulvinar quam, id tincidunt. 
```

Appears like this in `kubectl explain`, with weird line breaks:
```
key <type>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pulvinar in
  libero id sagittis.
  Aliquam sem enim, vehicula et urna ac, vehicula ullamcorper sem. Morbi turpis 
  arcu, aliquet at 
  eros quis, sodales dignissim eros. Quisque ut lectus quis magna maximus 
  elementum a nec felis. 
  Nulla ultricies pulvinar quam, id tincidunt.
```

**What you expected to happen**:

OpenAPIv3 is [formatted as Markdown](https://swagger.io/specification/#rich-text-formatting), so I'd expect `kubectl explain` to reflow each `description` to realign line breaks, according to the rules of Markdown (i.e. respecting lists and the like):
```
key <type>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pulvinar in
  libero id sagittis. Aliquam sem enim, vehicula et urna ac, vehicula 
  ullamcorper sem. Morbi turpis arcu, aliquet at eros quis, sodales dignissim 
  eros. Quisque ut lectus quis magna maximus elementum a nec felis. Nulla 
  ultricies pulvinar quam, id tincidunt.
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
  ```
  Client Version: v1.29.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.9+8ca71f7
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MacOS (Darwin)

**Comment by ah8ad3** [comment]
Thanks for raising this, @dhaiducek `kubectl explain` already has that wrap mechanism, but it may be acting wired in some scenarios. I will take a look at this.
/assign
