### ISSUE TITLE
Allow kubeconfig option load a list of kubeconfig files

### ISSUE THREAD

**Issue by warjiang** [kubernetes/kubectl#1626]
**What would you like to be added**:
I used to think the `KUBECONFIG` environment variable has the same effect as the `--kubeconfig`, but when I execute some `kubectl config` subcommand and find the difference, apart from the loading order, the `KUBECONFIG` envrionment variable can load a list of kubeconfig file, but `--kubeconfig` can only load one kubeconfig file,

![image](https://github.com/user-attachments/assets/3ff9db2c-3251-42c3-8132-47a814df3c95)

**Why is this needed**:
The scenario of my use-case is to combine multi kubeconfig files into one kubeconfig, if no this feature, the only way i can do is use the environment var, like `export KUBECONFIG=config1:config2:config3`, and i need to set and unset the `KUBECONFIG` var, if the feature supported, i can specify `--kubeconfig=config1,config2,config3`, it will be more elegant.

**Comment by mpuckett159** [comment]
Would it be acceptable to accomplish this like:
```shell
KUBECONFIG=config1:config2:config3 kubectl blah blah
```
Then you at least have visibility that the command is having multiple non-default/default configs passed into it.

**Comment by warjiang** [comment]
@mpuckett159  Yeah, it works. 
At first I try the following code
```
KUBECONFIG=config1:config2:config3 
kubectl config view --flatten > merged.config
```
but it doesn't work, and I changed `KUBECONFIG=config1:config2:config3 ` to `export KUBECONFIG=config1:config2:config3` to make the merge of multi kubernetes config works, but  use `export` need extra recover like 

```
if [ -n "${KUBECONFIG+x}" ];then
  CURR_KUBECONFIG=$KUBECONFIG # backup current kubeconfig
fi


// to-do 
// merge of multi cluster kubeconfig

function recover_kubeconfig {
  if [ -n "${CURR_KUBECONFIG+x}" ];then
    export KUBECONFIG="${CURR_KUBECONFIG}"
  else
    unset KUBECONFIG
  fi
}
```
so I want the team of kubectl to support mulit kubeconfig files in the options which have the same effect as `KUBECONFIG` env. But the method you metioned works, and it solved my problem.

**Comment by Ritikaa96** [comment]
@kubernetes/kubectl-maintainers  tagging the experts to give an opinion. i think this can be useful.
/sig cli

**Comment by mpuckett159** [comment]
Sorry I should have closed this. I know that the preference would be to use a flag but, uh, the code that loads kubeconfigs by flag is very very old and I have tried fixing it before and failed. We currently have a KEP working on improving kubeconfig functionality, but I'm not sure when it is targeted to land, or if it will help fix the problems with loading kubeconfigs that I ran into when trying to fix this problem before.
/close

**Comment by Ritikaa96** [comment]
@mpuckett159 is https://github.com/kubernetes/enhancements/pull/4031 the KEP you are talking about?
I dont know if i understand right but it will be brilliant in case we can just define one directory for all config files we want to use and then can list them using a fixed nomenclature for the file name.

**Comment by warjiang** [comment]
if use the KUBECONFIG var, I need to 


if [ -n "${KUBECONFIG+x}" ];then
  CURR_KUBECONFIG=$KUBECONFIG
fi


function recover_kubeconfig {
  if [ -n "${CURR_KUBECONFIG+x}" ];then
    export KUBECONFIG="${CURR_KUBECONFIG}"
  else
    unset KUBECONFIG
  fi
}

> @mpuckett159 is [kubernetes/enhancements#4031](https://github.com/kubernetes/enhancements/pull/4031) the KEP you are talking about? I dont know if i understand right but it will be brilliant in case we can just define one directory for all config files we want to use and then can list them using a fixed nomenclature for the file name.

@mpuckett159 Cloud you make sure that is kep#4031 is the kep you mentioned? I also want to track the releated KEP and get the right order to load the kubeconfig.
