### ISSUE TITLE
"kubectl rollout status" not waiting for previous replica termination

### ISSUE THREAD

**Issue by GavBurke** [kubernetes/kubectl#1628]
**What happened**:

When performing our deployments, often we have our pod still doing work so we wait for the graceful shutdown.  On our deployment we wait until kubectl rollout status says it's done so then our verify scripts can run to ensure the new pod is picking up the work correctly, but we are finding that the rollout status prematurely says the rollout is complete.  We see logs of `Waiting for deployment "deployment-name" rollout to finish: 1 old replicas are pending termination...` for quite a few minutes but then reports `deployment "deployment-name" successfully rolled out` even though in this case the previous replica was still in the Terminating state for another 26 minutes.

**What you expected to happen**:

The rollout status to wait until _only_ the new replicas are the pods that exist, i.e. the old replicas have now been deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Get a deployment with pod up and running and give it a task you know which will take like 30 mins (something noddy as an image with an entrypoint of `sleep 1800` could work)
Change something on the deployment, i.e. sleep for 1801 or different image
Deploy the change (we use Helm for our deploys)
Run the `kubectl rollout status` and see it will not wait for 30 mins until it says the rollout is complete, it will most likely tell the old pod to terminate, which the graceful_shutdown_period of 3600 should prevent immediately, and then start a new pod and report done as soon as this new pod is running

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.29.6 client - 1.29.7-gke and 1.29.2-aks server
- Cloud provider or hardware configuration: Both GCP and Azure
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 12 (bookworm)

**Comment by mpuckett159** [comment]
/close
/kind feature
/remove-kind bug
Rollout is only meant to handle the deployment of the "current" generation of resources, and does not handle the previous generation beyond emitting the termination signal. If you want to wait for the previous generation to complete terminating you will need to wait on those pods some other way, e.g. with kubectl wait, or shell scripting via checking the status of the pods and waiting for terminating pods to disappear.
