### ISSUE TITLE
Unclear built-in help for `kubectl set`

### ISSUE THREAD

**Issue by Parkofadown** [kubernetes/kubectl#1639]
Page is automatically generated
As of 3:52 PM on 8/7/24 
Synopsis states: Configure application resources. These commands help you make changes to existing application resources.

Recommend clarifying what application resources you can configure. Second sentence should be worded as: This command helps you make changes to existing application resources.
Recommend adding an example usage field

Thanks,
PARKOFADOWN

**Comment by sftim** [comment]
/retitle Unclear built-in help for `kubectl set`

**Comment by ah8ad3** [comment]
I think we talked about these documents few months ago in the SIG, i can't recall what was the decision. The team will see and triage it.

The doc on the command itself is more clear try: `kubectl set -h` @Parkofadown
