### ISSUE TITLE
Understand and potentially remove `k8s.io/kubernetes/pkg/kubectl/testing`

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#164]
I don't understand what this is for. The `doc.go` file is plain wrong as it's just been copy-pasted from somewhere else (likely `k8s.io/kubernetes/pkg/kubectl`) and left unmodified.

Also the code is barely used anywhere, I'm wondering if we could remove that.

**Comment by mengqiy** [comment]
Totally agree. The only usage in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/testing/zz_generated.deepcopy.go is generated. I believe it can be safely removed.

**Comment by wackxu** [comment]
It also been used in https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers_test.go#L62,
It needs to implement  interface  `runtime.object`  for printers test use

**Comment by Lion-Wei** [comment]
We can still remove doc.go. : )
Since 'testing' package only have `testing.TestStruct`, and it only used in printers_test.go, maybe we can move it to `printers_test.go`.

**Comment by apelisse** [comment]
Do we need that structure at all, in printers_test.go? Can we look at it and see if we could use something else, replace it somehow?

**Comment by Lion-Wei** [comment]
I think it can be replaced. I'll try to do that. : )
