### ISSUE TITLE
`wait` command produces error on quoted conditions

### ISSUE THREAD

**Issue by tvandinther** [kubernetes/kubectl#1646]
**What happened**:
The parsing of this command seems to be affected by quoting the argument.
```sh
$ kubectl wait --for "jsonpath='{.status.readyReplicas}'" deployment/coredns -n kube-system
error: unexpected path string, expected a 'name1.name2' or '.name1.name2' or '{name1.name2}' or '{.name1.name2}'
```

**What you expected to happen**:
```sh
$ kubectl wait --for "jsonpath='{.status.readyReplicas}'" deployment/coredns -n kube-system
deployment.apps/coredns condition met
```
just as the following unquoted example:
```sh
$ kubectl wait --for jsonpath='{.status.readyReplicas}' deployment/coredns -n kube-system
deployment.apps/coredns condition met
```
From my understanding, this should not affect things.
```sh
$ echo hello | wc -c
6
$ echo "hello" | wc -c
6
```

**How to reproduce it (as minimally and precisely as possible)**:
```sh
kubectl wait --for "jsonpath='{.status.readyReplicas}'" deployment/coredns -n kube-system
```

**Anything else we need to know?**:
Some tools that manage subprocess always execute arguments as these quoted variants which makes the `kubectl wait` command fail with the error shown above.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
`1.30.2`
- OS (e.g: `cat /etc/os-release`):
Ubuntu linux BASH or sh, or any other shell I've tried (zsh, nu, etc.)

**Comment by tvandinther** [comment]
It turns out the single quotes aren't necessary and when removed the quoted command words. Although the help message specifies that these are required in the syntax. I am unsure why the differences.

**Comment by ardaguclu** [comment]
Isn't this issue trying to achieve similar behavior with https://github.com/kubernetes/kubernetes/issues/127073?.

**Comment by tvandinther** [comment]
I think the difficulty may have been averted with a different error message. There seems to be something wrong with it:
```
error: unexpected path string, expected a 'name1.name2' or '.name1.name2' or '{name1.name2}' or '{.name1.name2}'
```
It has duplicate options for:
- `'name1.name2'`
- `'{name1.name2}'`

What it should probably cover (and perhaps, what it is trying to say) is:
- `'name1.name2'`
- `'{name1.name2}'`
- `name1.name2`
- `{name1.name2}`

The duplicate of each syntax format has single quotes but should not have them.

**Comment by ardaguclu** [comment]
I think it tries to enumerate;
* `name1.name2`
* `.name1.name2`
* `{name1.name2}` 
* `{.name1.name2}`
quotes in warning message is just to emphasize the value
