### ISSUE TITLE
https://dl.k8s.io/release/stable.txt report the wrong version

### ISSUE THREAD

**Issue by mavimo** [kubernetes/kubectl#1656]
**What happened**:

From the public documentation reported in:
* https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux

We should relay on the version reported in:
 * https://dl.k8s.io/release/stable.txt

to know the last released version.

A few days ago the version `1.31.1` was released: 
 * https://github.com/kubernetes/kubectl/releases/tag/v0.31.1

and the `stable.txt` was properly updated (we know because we have automation that check the version reported every day to automate some update)

2 days ago the file start reporting that the last version is the `1.31.0` instead `1.31.1`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
curl -L -s https://dl.k8s.io/release/stable.txt
```
should report `1.31.1` instead of `1.31.0`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): not relevant
- Cloud provider or hardware configuration: not relevant
- OS (e.g: `cat /etc/os-release`): not relevant

**Comment by unexge** [comment]
Not sure if it's related – but seems like `https://dl.k8s.io/release/stable.txt` is down at the moment. Requests stuck and fails with:
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>fastly-reader@k8s-infra-releases-prod.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details>
</Error>
```
after some time.

**Comment by ardaguclu** [comment]
It seems to be fixed and we can close it;
/close
