### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by siddhi46** [kubernetes/kubectl#1658]
<img width="1460" alt="Screenshot 2024-09-23 at 18 42 50" src="https://github.com/user-attachments/assets/d3df416c-a112-4c4b-95e5-e375ec60a811">

Facing error for kubectl get node command for EKS cluster (AWS)

History from AWS CLI :
eksctl create cluster \
  --name my-cluster \
  --region us-west-2 \
  --nodegroup-name my-nodes \
  --node-type t3.medium \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed

**Comment by ardaguclu** [comment]
Looks like your cred exec plugin is not installed correctly or has issues
/kind support
