### ISSUE TITLE
Add kubectl get secret x --base64-decode

### ISSUE THREAD

**Issue by yegli** [kubernetes/kubectl#1680]
**What would you like to be added**:
`kubectl get secret x -o yaml` is a very useful command. I have had multiple use cases where I have secrets in our dev environment and I must verify the base64 encoded information. Unfortunately kubectl doesn't support a flag such as `--base64-decode`, which allows printing the secret to the cli in a human readable form.

I could create a function on my device that takes the intended value base64 encodes it and then compares the given value with the value provided from the secret, but this isn't intuitive and is hard to share with other developers.

I'd love to take over the according implementation once approved.

The flag `--base64-decode` should print the secret in yaml format with secret values decoded.
```
apiVersion: v1
data:
  password: Password!
  username: bob
kind: Secret
metadata:
  creationTimestamp: "2024-11-27T08:20:05Z"
  name: demo-secret
  namespace: default
  resourceVersion: "4887086"
  uid: 5172e5c1-bcc9-4df5-844b-90f5da16712d
type: Opaque
```
/sig cli

**Why is this needed**:
To improve the workflow of troubleshooting secrets and verifying that the base64 data also matches the intended values.

**Comment by ardaguclu** [comment]
`get` command approaches all the resources generic, that said there is no custom code specific for secrets. So it is not possible to add this flag in get. I'd recommend writing a script for this.

**Comment by yegli** [comment]
@ardaguclu Thanks a lot for your quick response I see the issue at hand. Do you know of any efficient way to share the code with other developers as I see this issue to be a widespread desire?

**Comment by ardaguclu** [comment]
I'd add it in here and if someone stumble upon the same issue, they can use it from here.

**Comment by yegli** [comment]
I have found this short command to be very useful and to work with all types of secrets.
`kubectl get secrets demo-secret -o yaml | yq '.data |= with_entries(.value |= @base64d)'`

which returns the entire secret in its yaml form with decoded data fields as shown here
```
(base) ☁  ~  k get secrets demo-secret -o yaml | yq '.data |= with_entries(.value |= @base64d)'
apiVersion: v1
data:
  password: Password!
  username: bob
kind: Secret
metadata:
  creationTimestamp: "2024-12-02T20:09:11Z"
  name: demo-secret
  namespace: default
  resourceVersion: "1190"
  uid: 87d2962d-0461-4107-ae3b-876bf5f21466
type: Opaque
```
