### ISSUE TITLE
Update the code review comments link in README

### ISSUE THREAD

**Issue by NRKirby** [kubernetes/kubectl#1684]
**What would you like to be added**:

The code review [comments link](https://github.com/golang/go/wiki/CodeReviewComments) on the the main README points to a page the says the page has moved to go.dev 

<img width="570" alt="image" src="https://github.com/user-attachments/assets/86f0e566-bf9f-4a3d-9127-970f080c8d02">

The new page should be this: https://go.dev/wiki/CodeReviewComments

**Why is this needed**:

The link should be correct

**Comment by kundan2707** [comment]
@NRKirby  link if pointing to correct page which is giving info of updated link.
so no need to changes

**Comment by ardaguclu** [comment]
I agree that there seems to be no issue in here;
/close
