### ISSUE TITLE
Refactor to use the functions in component-helpers to calculate pod resource 

### ISSUE THREAD

**Issue by lixiv** [kubernetes/kubectl#1688]
**What would you like to be added**:

Refactor the code to use library functions in component-helpers:
https://github.com/kubernetes/kubectl/blob/master/pkg/util/resource/resource.go#L40
https://github.com/kubernetes/kubectl/blob/master/pkg/util/resource/resource.go#L96

**Why is this needed**:

PodRequests and PodLimits method exists in `staging/src/k8s.io/component-helpers/resource/helpers.go`. Refactor the code to avoid duplicating podRequests and podLimits method.

**Comment by ardaguclu** [comment]
When I checked in the referenced PR, there are plenty of changes and it is really hard to confirm that this won't create any regressions. In my opinion, we can leave it as is. However, maintainers can still drop comments on the PR but there is no need to have a separate issue for this;
/close
