### ISSUE TITLE
Cannot ssh into (hanging) init container

### ISSUE THREAD

**Issue by lenalebt** [kubernetes/kubectl#170]
**What keywords did you search in Kubernetes issues before filing this one?** bash, init, exec

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
/kind FeatureRequest

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

(but did not work in minikube 0.24.1 with an 1.8 cluster as well)

**Environment**:
- **Cloud provider or hardware configuration**: n/a
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a
- **Others**: n/a

**What happened**:
Have a hanging init container that I'd like to debug. It writes some log files, but does not write everything to stdout. Sources are not under my control.

    [brueder:~/projects … e/caas/kubernetes/helm/caas] feature/CAAS-365-mongo-cluster(+4/-4)+* ± 
    kubectl exec -it caas-mongo-0 -- /bin/bash
    error: unable to upgrade connection: container not found ("caas-mongo")

    [brueder:~/projects … e/caas/kubernetes/helm/caas] feature/CAAS-365-mongo-cluster(+4/-4)+* ± 
    kubectl get po
    NAME                                 READY     STATUS     RESTARTS   AGE
    caas-mongo-0                         0/1       Init:1/3   0          52m

**What you expected to happen**:
I'd expect "kubectl exec" to be able to ssh into that init container. If not naturally, then with "-c $init_container_name", as in "kubectl logs", for example

    kubectl exec -c $init_container_name -it caas-mongo-0 -- /bin/bash

**How to reproduce it** (as minimally and precisely as possible):
n/a

**Anything else we need to know**:
I can ssh into the host node and then "docker exec" into the init container. This only works because I have access to the nodes directly, but it should not be necessary.

**Comment by apelisse** [comment]
Not sure what specifically fails here, but I'm not sure this is kubectl related...

**Comment by lenalebt** [comment]
So, my request is about adding a "-c" flag to `kubectl exec`, to make its behaviour similar to `kubectl logs` when talking about init containers. Why should this not be kubectl-related?

**Comment by apelisse** [comment]
OK totally makes sense to me now! That's a good idea. I'll update the labels.

**Comment by lenalebt** [comment]
Hi @vithati - will do on monday or tuesday and report back :)

**Comment by vithati** [comment]
@lenalebt , Did you get chance to verify this issue with client version 1.10 and server version 1.11 (or with latest client and server version).  Can you share repro steps, it is not working for you.

**Comment by vithati** [comment]
This issue not occurring with v1.10 and latest version, we can close this issue.

**Comment by apelisse** [comment]
please re-open if it still happens.

**Comment by soltysh** [comment]
Closing per previous comment.

**Comment by cbluth** [comment]
I am experiencing the same problem.

```
kubectl exec -it buffer-57f49548f8-m692g sh
error: unable to upgrade connection: container not found ("buffer")
```

This error stopped happening after this:
```
kubectl -n kube-system delete pod -l component=kube-apiserver
￼```
