### ISSUE TITLE
deprecate the print flag `--template`

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubectl#174]
**What keywords did you search in Kubernetes issues before filing this one?** :
'template'  'printer'  'kubectl'
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**What happened**:

Recently I was learning code about printer. Little confused about the flag `--template`.
The flag `--template` have a description: "Template string or path to template file to use when -o=go-template, -o=go-template-file."
But base the code:
```go
	if flag := flags.Lookup("template"); flag != nil {
		if flag.Value.Type() == "string" {
			templateFile = GetFlagString(cmd, "template")
		}
	}
	if len(outputFormat) == 0 && len(templateFile) != 0 {
		outputFormat = "template"
	}
```
This flag be useful only if don't have `-o` flag.

And also, this flag have the same function with `-o go-template=****`. I'm not sure why we have this flag, is there any other reasons I don't know? If so, I think we should at least change the description of this flag.

Besides, since `-o template\-o templatefile` is same with `-o go-template\-o go-template-file`, can we chose one? There don't have any hint in `-o` flag about `-o template\-o templatefile` .

**What you expected to happen**:
1. Maybe deprecate the flag `--template` if we can make sure this flag is useless.
2. Change the description of flag `--template` if it still useful.
3. Maybe chose one in `-o template`\`-o templatefile` and  `-o go-template`\`-o go-template-file`.

**Anything else we need to know**:

**Comment by shiywang** [comment]
I would like to keep the redundancy, give user more choices, but if you feel description of `--template` provide some inaccurate information, we can make it more accurate.

**Comment by Lion-Wei** [comment]
@shiywang Thanks for replaying. If so, I will do that. 
And also, there don't have any hint about `-o templatefile`, should we add this information or should we take this as a hidden function?
