### ISSUE TITLE
Watch flag should indicate when a resource is deleted

### ISSUE THREAD

**Issue by EmpireJones** [kubernetes/kubectl#185]
Feature suggestion/improvement:
`kubectl get pods --watch` should indicate when a pod is actually deleted.

Currently it just appends another line or two indicating that it has a terminating status, around when it gets deleted.

This might apply to other resource types too.

**Kubernetes version** (use `kubectl version`):
Client: 1.8.4
Server: 1.8.0 (via minikube v0.24.1)

**Environment**:

Minikube v0.24.1

Host Env:
Ubuntu 17.10
Linux Laser 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:

    $ kubectl get pods --watch
    NAME                               READY     STATUS        RESTARTS   AGE
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6          11m
    my-pod-7bcddb9489-j4qzz   1/1       Running       0          51s
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6         11m
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6         11m

**What you expected to happen**:
There should be some sort of 'Terminated' or 'Deleted' status.

**How to reproduce it** (as minimally and precisely as possible):

- run `kubectl get pods --watch` while deleting pods. 

**Anything else we need to know**:
- ran via bash shell
- I created/deleted pods via helm, but that shouldn't matter

**Comment by EmpireJones** [comment]
This might also just be an issue of the lines not getting cleared properly in the bash shell, when a row is supposed to go away.

**Comment by zjj2wry** [comment]
```-a, --show-all=false: When printing, show all resources (default hide terminated pods.)```
@EmpireJones maybe this flag can help you

**Comment by EmpireJones** [comment]
@zjj2wry thanks for the tip, but I couldn't get that flag to make it show terminated pods (server/client v1.9.0)

**Comment by darkowlzz** [comment]
Created a PR implementing this https://github.com/kubernetes/kubernetes/pull/57947 . Some feedback would be great :)

**Comment by G-Harmon** [comment]
I'd like to see this feature. It'd help with rapid deletion/creation of the same pod.

/remove-lifecycle rotten
