### ISSUE TITLE
Default output from kubectl when getting a CRD named Status is wrong

### ISSUE THREAD

**Issue by mortenlj** [kubernetes/kubectl#186]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Status

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
╼ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: minikube
╼ minikube version
minikube version: v0.24.1

**What happened**:
When listing objects of a CRD called Status, the output is blank, except for headers that are not what I was expecting.

**What you expected to happen**:
I expected something along the lines of what you get when you list other objects, such as name and possibly other relevant fields. 

**How to reproduce it** (as minimally and precisely as possible):
```
fimojoha@fimojoha-w530:/tmp$ minikube start --kubernetes-version v1.8.0
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
fimojoha@fimojoha-w530:/tmp$ kubectl create -f - <<EOF
> apiVersion: apiextensions.k8s.io/v1beta1
> kind: CustomResourceDefinition
> metadata:
>   name: statuses.fiaas.schibsted.io
> spec:
>   group: fiaas.schibsted.io
>   names:
>     kind: Status
>     listKind: StatusList
>     plural: statuses
>     shortNames:
>     - status
>     - fs
>     singular: status
>   scope: Namespaced
>   version: v1
> EOF
customresourcedefinition "statuses.fiaas.schibsted.io" created
fimojoha@fimojoha-w530:/tmp$ kubectl create -f - <<EOF
> apiVersion: fiaas.schibsted.io/v1
> kind: Status
> metadata:
>   labels:
>     app: nginx-example
>   name: nginx-example
>   namespace: default
> result: RUNNING
> EOF
Error from server: error when creating "STDIN": 
fimojoha@fimojoha-w530:/tmp$ kubectl get statuses.fiaas.schibsted.io
STATUS    REASON    MESSAGE
                    
fimojoha@fimojoha-w530:/tmp$ kubectl get statuses.fiaas.schibsted.io -ocustom-columns=NAME:.metadata.name,KIND:.kind
NAME            KIND
nginx-example   Status
fimojoha@fimojoha-w530:/tmp$ kubectl get statuses.fiaas.schibsted.io -oyaml
apiVersion: v1
items:
- apiVersion: fiaas.schibsted.io/v1
  kind: Status
  metadata:
    clusterName: ""
    creationTimestamp: 2017-12-19T12:48:55Z
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    initializers: null
    labels:
      app: nginx-example
    name: nginx-example
    namespace: default
    resourceVersion: "253"
    selfLink: /apis/fiaas.schibsted.io/v1/namespaces/default/statuses/nginx-example
    uid: f984002d-e4ba-11e7-8296-0800274322ad
  result: RUNNING
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
fimojoha@fimojoha-w530:/tmp$ kubectl get statuses.fiaas.schibsted.io nginx-example -oyaml
Error from server: 
fimojoha@fimojoha-w530:/tmp$ 
```

**Anything else we need to know**:

**Comment by stewart-yu** [comment]
If don't mind, i'm glad to help it.

**Comment by apelisse** [comment]
I can't assign you, I'm assigning to me as a placeholder. Thanks @stewart-yu !

**Comment by stewart-yu** [comment]
The method you create `Status` are wrong @mortenlj 
```shell
kubectl create -f - <<EOF
> apiVersion: fiaas.schibsted.io/v1
> kind: Status
> metadata:
>   labels:
>     app: nginx-example
>   name: nginx-example
>   namespace: default
> result: RUNNING
> EOF
```
So when you get it,  just output nil

**Comment by mortenlj** [comment]
@stewart-yu : I'm not sure I understand you. In what way is this a wrong way to create an object?

This is a custom resource definition, of an object that happens to have `kind: Status`, but it is *not* the status-field of a parent object (like PodStatus for instance). 

The object is created, and it's there if you use alternative output formats. If you don't use kubectl, but use the API directly, it seems to work as it should.

**Comment by liggitt** [comment]
I think something in the client path is confusing the response for a v1 Status object

**Comment by nikhita** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/42521, https://github.com/kubernetes/apiextensions-apiserver/issues/11

**Comment by liggitt** [comment]
No, mishandling an object named Status is different

**Comment by sttts** [comment]
We send back `<group>/<version>` Status objects instead of `meta/v1` Status. Hence, we get a conflict here. IMO we have to exclude `Status` from the valid kind names in CRDs.

**Comment by adohe** [comment]
We may have other built in names, I think `Spec`, `Status` should be both excluded.

**Comment by liggitt** [comment]
> I think Spec, Status should be both excluded.

Spec isn't a top level type.

**Comment by mortenlj** [comment]
Is the conclusion here that this is not a bug in the output, but rather a bug that I was allowed to create a CRD kind named `Status`? Do I now have to change the name of my CRD?

**Comment by sttts** [comment]
@mortenlj yes. With today's way the api works, we cannot allow a CRD of kind `Status`.

Renaming a CRD means to create a new one and copy over the objects. We don't have a mechanism for that (= CRDs do not support cohabitation; that's the feature this would need). And even if we had, it would likely not work correctly with `Status`.

Sorry for the bad news.

**Comment by mortenlj** [comment]
If the conclusion is that creating a CRD named Status shouldn't be allowed, I don't think there is any more action needed on this bug. I have renamed my CRD to avoid the issue.

**Comment by nikhita** [comment]
> If the conclusion is that creating a CRD named Status shouldn't be allowed, I don't think there is any more action needed on this bug.

We still need to give an error to the user that they are not allowed to use the name though. :)

**Comment by liggitt** [comment]
get now works properly in master:
```
kubectl get statuses
NAME            AGE
nginx-example   33s
```

**Comment by liggitt** [comment]
`kubectl create` creates the object successfully, but outputs incorrectly:
```
kubectl create -f status.yaml 
Error from server: error when creating "status.yaml": 
```

**Comment by liggitt** [comment]
fixed `kubectl create` behavior in https://github.com/kubernetes/kubernetes/pull/77368
