### ISSUE TITLE
kubectl run --env option restricts the format of the variable values

### ISSUE THREAD

**Issue by ddcprg** [kubernetes/kubectl#19]
**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T23:29:08Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:22:45Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS**: Mac OS Sierra v10.12.4
- **Kernel**: Darwin mylaptop.localdomain 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin
- **Others**:
    - minikube version: v0.19.0
    - Docker version 17.03.1-ce, build c6d412e

**What happened**:

I'm invoking `kubectl run` with the `--env` option. For my deployment I must pass a JSON string as the value of an environment variable. It seems like `kubectl` doesn't accept image environment variable values that are not C identifiers although If my JSON string has only one attribute then `kubectl` accepts the command. The 2 commands can be found in the *How to reproduce it* section below.

The relevant code seems:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/run.go#L863

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L178

**What you expected to happen**:

The environment variable should have been accepted and the image started.

**How to reproduce it**:

This works:

```
$> kubectl run consul --image=consul:0.8.3 --image-pull-policy=IfNotPresent --port=8500 --env="CONSUL_LOCAL_CONFIG={'acl_datacenter':'dc1'}"
deployment "consul" created
```

This does not:

```
$> kubectl run consul --image=consul:0.8.3 --image-pull-policy=IfNotPresent --port=8500 --env="CONSUL_LOCAL_CONFIG={'acl_datacenter':'dc1','acl_default_policy':'allow','acl_down_policy':'extend-cache','acl_master_token':'the_one_ring','bootstrap_expect':1,'datacenter':'dc1','data_dir':'/usr/local/bin/consul.d/data','server':true}"
error: invalid env: 'acl_default_policy':'allow'
```

With the latter, even adding a single attribute seems to prevent `kubectl` from processing the command - perhaps related to the comma in the string.

**Anything else we need to know**:

All this is running in a local development environment on my laptop. The versions of the software I'm using are specified above.

**Comment by mengqiy** [comment]
```
cmd.Flags().StringSlice("env", []string{}, "Environment variables to set in the container")
```
I think there are 2 issues here.
1. Cobra is trying to split the flag by comma when using [StringSlice](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run.go#L120). We should use StringArray().
2. Maybe we should not restrict it.

I will send a fix soon.

This is not a blocking issue for 1.7, since it already exists in 1.6.
