### ISSUE TITLE
kubctl explain resourcequota.spec.hard incomplete 

### ISSUE THREAD

**Issue by dyson** [kubernetes/kubectl#190]
/kind bug

**What happened**:
Ran:
```
kubectl explain resourcequota.spec.hard
```

**What you expected to happen**:
To see list of available hard resource quota limits.
Instead there is only a link to a page that 404's.

**How to reproduce it (as minimally and precisely as possible)**:
Run:
```
kubectl explain resourcequota.spec.hard
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
:; kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05",GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4",GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME=Buildroot
VERSION=2017.02
ID=buildroot
VERSION_ID=2017.02
PRETTY_NAME="Buildroot 2017.02"
```

**Comment by huzhengchuan** [comment]
I test in my kubernetes clusters, the link response is not 404 error. 
<pre>
[root@xxx-master1 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

[root@xxx-master1 ~]# kubectl explain resourcequotas.spec.hard  
FIELD: hard <map[string]string>

DESCRIPTION:
     Hard is the set of desired hard limits for each named resource. More info:
     https://kubernetes.io/docs/concepts/policy/resource-quotas/
</pre>

I see your cluster is v1.8.0, what is the 404 error link. I know in kubernetes 1.8, the document link is change. see more details kubernetes/community#1010

**Comment by dyson** [comment]
Sorry I totally should have included the output! This is from minikube running 1.8:

```
:; kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05",GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4",GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
:; kubectl explain resourcequota.spec.hard
FIELD: hard <map[string]string>

DESCRIPTION:
     Hard is the set of desired hard limits for each named resource. More info:
     https://git.k8s.io/community/contributors/design-proposals/admission_control_resource_quota.md
```

And running against our gke cluster, running 1.8.4
```
:; kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05",GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.0", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-11-27T19:19:56Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
:; kubectl explain resourcequota.spec.hard
FIELD: hard <map[string]string>

DESCRIPTION:
     Hard is the set of desired hard limits for each named resource. More info:
     https://git.k8s.io/community/contributors/design-proposals/admission_control_resource_quota.md
```

**Comment by huzhengchuan** [comment]
the link is 404 error, is because the change kubernetes/community#1010.
it had been fixed in master branch. you can close the issue.
