### ISSUE TITLE
kubectl apply includes raw and useless data into the error message

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubectl#197]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"error when retrieving current configuration"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
/kind bug

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0-beta1", GitCommit:"3258431", GitTreeState:"clean", BuildDate:"2018-01-04T16:20:36Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.1.556+af78b9bac4d34e-dirty", GitCommit:"af78b9bac4d34eeec4adcf48f90845d5b325e081", GitTreeState:"dirty", BuildDate:"2018-01-08T14:52:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
`kubectl apply` includes Golang struct into the error message that makes it unreadable and unhelpful to user.

**What you expected to happen**:
1) the error message should be more clear about what's wrong and how I can fix it
2) the error message shouldn't show addresses in the memory that are useless

**How to reproduce it** (as minimally and precisely as possible):
```
$ kubectl apply -f nnp-test.yaml 
error: error when retrieving current configuration of:
&{0xc420094300 0xc420bc6310 default  nnp-test.yaml 0xc4220eb4a8  false}
from server for: "nnp-test.yaml": resource name may not be empty
$ cat nnp-test.yaml
kind: Pod
apiVersion: v1
metadata:
  generateName: testing-nnp-
spec:
  restartPolicy: Never
  initContainers:
  - name: init-container
	image: busybox
	command:
	- grep NoNewPriv /proc/self/status
  containers:
  - name: simple-container
	image: busybox
	command:
	- grep NoNewPriv /proc/self/status
```

**Anything else we need to know**:
```
$ kubectl apply --loglevel=8 -f nnp-test.yaml 
...
I0108 16:42:00.839592    5121 decoder.go:224] decoding stream as YAML
I0108 16:42:00.843520    5121 request.go:624] Error in request: resource name may not be empty
F0108 16:42:00.844222    5121 helpers.go:119] error: error when retrieving current configuration of:
&{0xc4212beb40 0xc420b68070 default  nnp-test.yaml 0xc422ea58c8  false}
from server for: "nnp-test.yaml": resource name may not be empty
```

**Comment by mengqiy** [comment]
>error: error when retrieving current configuration of:
&{0xc420094300 0xc420bc6310 default  nnp-test.yaml 0xc4220eb4a8  false}

The first half is not very helpful.

> from server for: "nnp-test.yaml": resource name may not be empty

The second half is complaining that `metadata.name` is missing since it is one of the preconditions:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L616

You are welcome to send to a PR to update the error message to make it more useful.

**Comment by Lion-Wei** [comment]
I can help to fix this problem, but I'm not quiet sure what error information we should keep. Here are the error message after I fixed:
```
F0111 10:38:11.309613   22663 helpers.go:119] error: error when retrieving current configuration of:
default/
from server for: "lw.yaml": resource name may not be empty
```
The second line is `namespace/name`, but don't have name in this case, so only namespace. I think this is the original intention.

**Comment by mengqiy** [comment]
IMO it could be more explicit:
```
error: error when retrieving current configuration of:
namespace: "default", name: ""
from server for: "lw.yaml": resource name may not be empty
```
@Lion-Wei It would be great if you can help.

**Comment by Lion-Wei** [comment]
Sure thing. : )
