### ISSUE TITLE
Kubectl errors when it needs to be updated instead of notifying.

### ISSUE THREAD

**Issue by jeremyjjbrown** [kubernetes/kubectl#2]
It would be nice if kubectl would provide a hint when it just needs an update.

Using a slightly older version of kubectl against Api server 1.6 and I got

```bash
kubectl get pods
error: group map[autoscaling:0xc8203c7110 batch:0xc8203c72d0 policy:0xc8203c6070 rbac.authorization.k8s.io:0xc8203c60e0 storage.k8s.io:0xc8203c6150 componentconfig:0xc8203c73b0 extensions:0xc8203c6000 federation:0xc8203c69a0 :0xc8203c6e70 apps:0xc8203c6ee0 authentication.k8s.io:0xc8203c6f50 authorization.k8s.io:0xc8203c70a0 certificates.k8s.io:0xc8203c7340] is already registered
```

Needless to say the user likely is going to waste a lot of time troubleshooting this before replacing kubectrl that was working just fine minutes before.

**Comment by pwittrock** [comment]
Can you provide steps to reproduce.  Using kubectl 1.5 with a 1.6 server should work.

**Comment by pwittrock** [comment]
Closing.  Reopen if you can reproduce.
