### ISSUE TITLE
Kubectl through a proxy

### ISSUE THREAD

**Issue by sybeck2k** [kubernetes/kubectl#216]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
http proxy, https proxy
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}`

**Environment**:
Windows 10, server is deployed on AWS running K8S 1.8.2

**What happened**:
I'm using kubectl through an authenticating proxy for OIDC. I cannot use the OIDC authenticator provided with kubectl because I cannot get auto refresh of tokens to work with my iDP (keycloak). To prevent users from relogging constantly, I'm proxying the K8S api with an OIDC authenticator - which in turn injects appropriate auth headers to the API.
I can confirm that the proxy is working correctly:
`curl -k --proxy http://192.168.99.100:3000 https://prod-k8s.dev.ci5.io/apis` returns a JSON object with correct headers.
On the other hand, using `kubectl` with `HTTPS_PROXY=http://192.168.99.100:3000 kubectl  --insecure-skip-tls-verify get namespaces -v=10` will not work:
```
I0122 11:17:18.382819   15568 round_trippers.go:436] GET https://prod-k8s.dev.ci5.io/api 200 OK in 373 milliseconds
I0122 11:17:18.382819   15568 round_trippers.go:442] Response Headers:
I0122 11:17:18.382819   15568 round_trippers.go:445]     Content-Type: application/json
I0122 11:17:18.382819   15568 round_trippers.go:445]     Date: Mon, 22 Jan 2018 10:17:17 GMT
I0122 11:17:18.383799   15568 request.go:836] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.20.1.90:443"}]}
I0122 11:17:18.385754   15568 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl.exe/v1.8.3 (windows/amd64) kubernetes/f0efb3c" -H "Authorization: Basic dXNlbGVzczp1c2VsZXNz" https://prod-k8s.dev.ci5.io/apis
I0122 11:17:18.394554   15568 round_trippers.go:436] GET https://prod-k8s.dev.ci5.io/apis 200 OK in 8 milliseconds
I0122 11:17:18.394554   15568 round_trippers.go:442] Response Headers:
I0122 11:17:18.394554   15568 round_trippers.go:445]     Content-Type: application/json
I0122 11:17:18.394554   15568 round_trippers.go:445]     Date: Mon, 22 Jan 2018 10:17:17 GMT
I0122 11:17:18.396505   15568 request.go:836] Response Body:
I0122 11:17:18.397484   15568 cached_discovery.go:126] skipped caching discovery info due to 0-length response
F0122 11:17:18.397484   15568 helpers.go:120] error: 0-length respons
```
As you can see, the `/api` call goes through with a correct reply. The subsequent request to `/apis` instead returns an empty body. 
Investigating the logs of my OIDC proxy show that there is no request to `/apis` going through the proxy, there are instead 2 calls to `/api` only.
Notice that I use a fake user in kubectl config (because a user is required) - the Authentication header is removed automatically from the proxy that will replace it according to OIDC authentication.

**What you expected to happen**:
Kubectl should work through the local proxy.

**How to reproduce it** (as minimally and precisely as possible):
(Requires OIDC authenticator and an identity provider)
- Run the OIDC authenticator:
```
docker run -d --name kc-proxy -p 3000:3000 quay.io/gambol99/keycloak-proxy:latest --discovery-url=https://kcauth/auth/realms/myrealm \
--client-id=kubernetes \
--client-secret=xxxx \
--redirection-url=http://192.168.99.100:3000 \
--listen=0.0.0.0:3000 \
--enable-forwarding=true \
--forwarding-username=user \
--forwarding-password="password" \
--forwarding-domains=myk8s.domain
```
- let kubectl use the proxy to connect: `HTTPS_PROXY=http://192.168.99.100:3000 kubectl  --insecure-skip-tls-verify get namespaces -v=10`

**Anything else we need to know**:
Using `curl` to access the K8S API through the authenticating proxy works correctly.

**Comment by apelisse** [comment]
@liggitt You probably know more about proxies than I do.

**Comment by liggitt** [comment]
sounds like a possible bug in how the discovery client is constructed

**Comment by nikhita** [comment]
/remove-lifecycle rotten

This still looks relevant.

/assign

**Comment by dmargrave** [comment]
i can confirm that on kubectl 1.9 it will honor the HTTPS_PROXY env var and I can access a cluster through a proxy

**Comment by anabioz-1861** [comment]
curl format: curl --proxy http://192.168.99.100:3000
kubectl format: HTTPS_PROXY=socks5://192.168.99.100:3000 kubectl
