### ISSUE TITLE
Error: error validating "": error validating data: kind not set

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kubectl#217]
i have a deployment and the service yaml files as follows

service.yaml 
apiVersion: v1
kind: Service
...
deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
i am using helm but i believe this is kubectl issue

below  is the version of kubectl  i am using
lient Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

is the problem to do with the kind or is further down the file. i am not sure what it is trying to validate as it is blank

**Comment by apelisse** [comment]
Do we have logs? I'm really unsure what is being passed to kubectl at this point. I've tried to apply an empty deployment, but it doesn't fail with the same error.

**Comment by apelisse** [comment]
Is there any way to get logs? so that we know what it's trying to do?

**Comment by anitakumar** [comment]
I had the Chart.yaml sitting in the templates directory of the helm folder. i believe helm was trying to process this and it was validating against something that did not exist as the Chart file is not a template to deploy or create service. once i removed it from there and put it where it needs to be, the deployment worked. i also did not use helm create to create the release. i just created a directory and subdirectories and one file got misplaced.
