### ISSUE TITLE
error trying to create a Role

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kubectl#224]
i tried to create the Role with a cluster running in aws using the file below
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: dev1
  name: developer
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
```
kubectl create -f <filename>
```
errror
```
Error from server (Forbidden): error when creating "nodejs-role1.yaml": roles.rbac.authorization.k8s.io "developer" is forbidden: attempt to grant
 extra privileges: [PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Ver
bs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["
create"]} PolicyRule{Resources:["depl
```
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

i have seen something on the internet about google cloud there is a workaround.
is there something similar for aws

**Comment by apelisse** [comment]
I think you should try to apply this configuration as an admin. Because you're trying to give `developer` more privilegies than your current user has.

**Comment by liggitt** [comment]
> I think you should try to apply this configuration as an admin. Because you're trying to give developer more privilegies than your current user has.

that's exactly right. you cannot define a role with more permissions than you currently have.

see https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping for more information about what permissions you must have to create roles

/close
