### ISSUE TITLE
Consider preferring USERPROFILE as the home path more often on Windows

### ISSUE THREAD

**Issue by dls314** [kubernetes/kubectl#227]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** : homedrive

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug-feature report-request

**Kubernetes version** (use `kubectl version`): 1.8.2

**Environment**:
- **Cloud provider or hardware configuration**: Docker for Windows, Minikube
- **OS** (e.g. from /etc/os-release): Windows 10
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a
- **Others**: n/a

**What happened**:
**What you expected to happen**:
**How to reproduce it** (as minimally and precisely as possible):
**Anything else we need to know**:

The `.kube` directory and `.kube\config` are being located inconsistently among some set of tooling including Docker for Windows CE 18.02.0-ce-rc1-win50 (15489) and kubectl 1.8.2.

I noticed this because `kubectl config get-clusters` returned an empty list, but I expected to see `docker-for-desktop` and `minikube` based on the contents from my `%USERPROFILE%\.kube\config` file.

I'm in a corporate environment where HOMEDRIVE HOMEPATH and HOMESHARE are in use to redirect home directories to a network drive. I only mention this because it leads to these paths differing from USERPROFILE.

In minikube, I think that the preference/fallback order leads to picking USERPROFILE as in this code:
https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/libmachine/mcnutils/utils.go#L30-L33

In kubectl, I think that the preference/fallback order leads to picking HOMEDRIVE + HOMEPATH as in this code:
https://github.com/kubernetes/kubectl/blob/master/pkg/pluginutils/plugin_client.go#L41-L44

In docker ce, I think that the preference/fallback order leads to picking USERPROFILE as in this code:
https://github.com/docker/docker-ce/blob/master/components/engine/pkg/homedir/homedir_windows.go

Those are only my best guesses about relevant code, and there are lots of other places in the wider codebases where you can find `os.Getenv("USERPROFILE")` or `os.Getenv("HOMEPATH")`, but for this narrow combination, based on behavior, I think that kubectl is the odd one out.

I think a different fallback order that prefers USERPROFILE as the other tools seem to would be nice.

**Comment by dls314** [comment]
As far as I know, the relevant windows feature here is best described by this topic:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb776911(v=vs.85).aspx

And the values of known folders are often specified relative to the user profile (search for %USERPROFILE% in this list)
https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx

The HOMEDRIVE and HOMEPATH variables aren't mentioned in discussions of the known folders API. Instead, they're usually mentioned in discussions of active directory, folder redirection, and roaming profiles.

Super importantly, only certain folders are subject to folder redirection, and the `%USERPROFILE%\.kube` folder isn't one of them.

I could see moving .kube into roaming app data which would be `%USERPROFILE%\AppData\Roaming\.kube` and would be subject to redirection, but that's a much bigger ecosystem change (no tools that I know of use this path now).

**Comment by dwalleck** [comment]
I encountered this same issue after trying to use Kubernetes that had been installed by Docker on my corporate laptop. It added my new cluster info to %USERPROFILE%\.kube\config, so I went crazy for an hour or so trying to understand why my new cluster hadn't appeared. It doesn't appear that I can change my HOMEDRIVE and HOMEPATH, which makes this config directory an outlier in relation to my other configs which are all in %USERPROFILE%.

**Comment by asalkeld** [comment]
It looks like this was fixed in 1.16 commit https://github.com/kubernetes/kubernetes/commit/448e3f792a2993ae3b3133740904ed87c4515fd0
