### ISSUE TITLE
kubectl does not set container name according to deployment manifest

### ISSUE THREAD

**Issue by minherz** [kubernetes/kubectl#24]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`): `Linux k8s-master-42728370-0 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux``
- **Install tools**:
- **Others**: The host is kubernetes master host

**What happened**:
When deploying a manifest that defines `name` for container, the actual name that is assigned is in a form `k8s_dicom-viewer.bd9132cf_dicom-viewer-deployment-665650083-5tl7f_prototype3_765a98cf-4aef-11e7-891b-000d3a304426_35acc9a7` where `dicom-viewer-deployment` is a name of the deployment.

**What you expected to happen**:
I would expect that a container will have a name that was defined in manifest file under spec/template/spec/containers/name

**How to reproduce it** (as minimally and precisely as possible):
1. create kubernetes cluster using acs-engine
2. deploy a container with a name

**Anything else we need to know**:
The cluster has Windows agent nodes.
Additionally, it is impossible to pull logs (via kubernetes dashboard). It shows `Get https://42728acs9001:10250/containerLogs/prototype3/minio-deployment-3747382929-07jk9/minio?timestamps=true: dial tcp: lookup 42728acs9001 on 10.7.224.100:53: no such host` error message.

**Comment by mengqiy** [comment]
I think the name in the pod template will just get ignored when running controller managed pods. @janetkuo Is this correct?

**Comment by minherz** [comment]
Okey. It is possible that i placed a wrong issue description then. I have two deployments, both with services and then from a container of the app1 i cannot access or `ping` service2 using `service2.deploymentnamespace.svc.cluster.local` URL. If it is relevant, my deployments run on Windows agent.
The `ipconfig /all` outpout from the container that runs app1 is:
```
Ethernet adapter vEthernet (Container NIC 7201c900):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #8
   Physical Address. . . . . . . . . : 00-15-5D-93-86-61
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::25a8:b01d:e641:69f0%56(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.2.231(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC 2fce3b5f):

   Connection-specific DNS Suffix  . : reddog.microsoft.com
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #9
   Physical Address. . . . . . . . . : 00-15-5D-7F-E3-07
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::993f:60b6:2ac7:3ba3%60(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.24.233.136(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.24.224.1
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Disabled
```
I am not sure that DNS server `10.0.0.10` belongs to Kubernetes.

**Comment by mengqiy** [comment]
> from a container of the app1 i cannot access or ping service2 using service2.deploymentnamespace.svc.cluster.local URL.

@MrHohn This seems to be an network issue.

If we confirm this is a network issue, we should move this issue to the main repo.

**Comment by MrHohn** [comment]
> I am not sure that DNS server 10.0.0.10 belongs to Kubernetes.

10.0.0.10 should be kube-dns service's vip, you could try `kubectl get svc kube-dns --namespace=kube-system` to see.

Also, don't think pinging service ip work: https://github.com/kubernetes/kubernetes/issues/47156.

BTW, although it may be the same, the correct FQDN should be `service2.service2namespace.svc.cluster.local`.

**Comment by minherz** [comment]
Thanx. Answering the questions, the original settings was to use `service2.service2namespace.svc.cluster.local` but it didn't work and wasn't resolved. Eventually i had to use local environment variables to identify IP:Port of the service (which isn't desired behavior).
This is happening when my application resolves DNS name vs. NIC which doesn't have correct DNS. In the example above it will be `Container NIC 2fce3b5f`.
The `10.0.0.10` *is* kubernetes DNS. However, the above NIC does not have it set. This is the issue.
When a cluster is created using Azure portal UI, both NICs have this DNS. However, when it is created using ACS engine it seems not to be. I still not sure whether it is ACS problem or kubernetes setup on windows machine.

**Comment by mengqiy** [comment]
Closing since this is not a kubectl issue.
Please move the discussion to the main repo or ask for help in the slack channel. Thanks.

**Comment by mengqiy** [comment]
@minherz feel free to reopen this if you still believe this is a kubectl issue.

**Comment by minherz** [comment]
thanx. I will do a follow up on this. If the problem persist I will create an issue with more correct titling and more details
