### ISSUE TITLE
Figure out the story for examples - where do they live.  CLA bot for cncf?  etc

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubectl#287]
/assign @grodrigues3

**Comment by grodrigues3** [comment]
@pwittrock does this mean examples for tutorial/learning purposes or examples in the same way that helm uses charts?  More production ready?  Do you think this entails drafting process documentation for contributing to the repo/adding new examples?  Do we need some kind of automation or testing setup?

**Comment by grodrigues3** [comment]
CLA bot setup for example repos.  More complete picture around examples forthcoming.

**Comment by apelisse** [comment]
Should we close this?
