### ISSUE TITLE
Tutorial for kinflate commands (3)

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#290]
init, add, set, inflate, patch overlay, 

How polished should this be:
- Tutorial on the K8s docs page on how to use this.  
- Aim for a 10-15 minute tutorial. 
- Should work on a mac or mobile devices
- Shouldn't have to install programs in order to follow tutorial

**Comment by droot** [comment]
This is completed in this PR https://github.com/kubernetes/kubectl/pull/297
