### ISSUE TITLE
Make watch flag `-w` usable also for `kubectl get all`

### ISSUE THREAD

**Issue by StegSchreck** [kubernetes/kubectl#298]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
* `watch`
* `-w`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I would like to use the watch flag `-w` not only for single resource types, but also for the summary of all resources. I would like to see that it is possible to call `kubectl get all -w`

**Kubernetes version** (use `kubectl version`):
Client 1.9.1
Server 1.9.1

**Comment by Lion-Wei** [comment]
@apelisse Is this what we need to do?

**Comment by apelisse** [comment]
I don't think it's unreasonable. But I'm somehow expecting roadblocks.

**Comment by oscarlofwenhamn** [comment]
/reopen

This is definitely a feature that would be nice. Especially in combination with helm deployments, being able to easily monitor an entire namespace would greatly improve efficiency. 
I imagine it would be a bit iffy to sort out, however, seeing as `-w` adds changes to the bottom line, but perhaps something like 
```
NAME                                               READY   STATUS                       RESTARTS   AGE
pod/foo                                            0/1     ContainerCreating         0             5s
...

NAME                                  TYPE          CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/bar                           ClusterIP            ...
...

RECENT CHANGES
pod/foo                                            1/1     Running                   0             25s
...
```
would be good enough.

**Comment by oscarlofwenhamn** [comment]
Fair enough.
