### ISSUE TITLE
Support symlinks for kubectl plugins directory

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes/kubectl#302]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

- plugins
- symlink

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
```

**What happened**:

If `~/.kube/plugins` is a symlink running `kubectl plugin` does not find plugins.

```
$ ln -s ~/src/github.com/kubernetes/kubernetes/pkg/kubectl/plugins/examples ~/.kube/plugins
$ kubectl plugin
error: no plugins installed.
```

**What you expected to happen**:

Running `kubectl plugin` lists the plugins at the target of the symlink.

```
$ ln -s ~/src/github.com/kubernetes/kubernetes/pkg/kubectl/plugins/examples ~/.kube/plugins
$ kubectl plugin
Runs a command-line plugin.

Plugins are subcommands that are not part of the major command-line distribution and can even be provided by
third-parties. Please refer to the documentation and examples for more information about how to install and write your
own plugins.

Available Commands:
  aging       Aging shows pods by age
  hello       I say hello!

Usage:
  kubectl plugin NAME [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Anything else we need to know**:

While this can also be solved by using the `KUBECTL_PLUGINS_PATH` environment variable having the ability to setup a symlink at `~/.kube/plugins` would be more convenient to manage in my opinion.

Looking at the [plugin loading code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/plugins/loader.go#L71) it would seem the reason this doesn't work currently is due to the fact that `filepath.Walk` does not [expand symlinks](https://golang.org/pkg/path/filepath/#Walk). As a quick test I added a call to `filepath.EvalSymlinks` for the path that will get passed to `filepath.Walk` which results in the plugins being correctly enumerated.

```go
	base, err = filepath.EvalSymlinks(base)
	if err != nil {
		return nil, err
	}
```

If this idea seems reasonable I'm happy to implement the change and submit a PR.

**Comment by seans3** [comment]
Because of the new plugin mechanism, I believe this issue is obsolete. I'm assigning to @juanvallejo for a determination. If it's obsolete, please close this--thanks.

**Comment by juanvallejo** [comment]
Yep, under the new plugin design, plugin executables can exist anywhere in a user's PATH.
You are also able to symlink an executable that exists somewhere outside of your PATH to a location within your PATH: `sudo ln -s ~/.plugins/kubectl-foo /usr/local/bin/kubectl-foo`

/close
