### ISSUE TITLE
get --watch specifying a resource uses "watch list" instead of "watch" API

### ISSUE THREAD

**Issue by jethrogb** [kubernetes/kubectl#305]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): watch

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): 4.4.0-104-generic #127-Ubuntu
- **Install tools**: kubeadm
- **Others**:

**What happened**:
When running `kubectl get RESOURCETYPE --watch OBJECTNAME`, it uses the "watch list" API with a fieldSelector on the resource name. If the current role doesn't allow watch list for this resource type, this results in a 403.

**What you expected to happen**:
I expected the "watch" API to be used.

**How to reproduce it** (as minimally and precisely as possible):
```
# Setup RBAC on your account to allow watch but not watch list
$ kubectl --v=6 get cm -n swdist swdist --watch|&grep GET
I0220 22:20:41.482970    2907 round_trippers.go:436] GET https://10.245.0.1:443/api/v1/namespaces/swdist/configmaps/swdist 200 OK in 9 milliseconds
I0220 22:20:41.492379    2907 round_trippers.go:436] GET https://10.245.0.1:443/api/v1/namespaces/swdist/configmaps?fieldSelector=metadata.name%3Dswdist&resourceVersion=0&watch=true 403 Forbidden in 1 milliseconds
```

**Anything else we need to know**:

**Comment by stealthybox** [comment]
I just noticed this in the 1.12 release notes.
It looks like this is intentional behavior of client-go.
`/watch` is now deprecated in favor of passing `?watch=true`.

ref: https://github.com/kubernetes/kubernetes/pull/65147

**Comment by liggitt** [comment]
as of 1.11, watch requests with a fieldSelector scoped to a single metadata.name can be authorized using an individual watch permission. see https://github.com/kubernetes/kubernetes/pull/63469

/close

**Comment by jethrogb** [comment]
Great!
