### ISSUE TITLE
Kubectl should warn when resources aren't found and discovery failed

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubectl#31]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Aggregator

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

```
$ k version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.527+bb877f1ee6b30c", GitCommit:"bb877f1ee6b30c0f70068aa5ffc4324e6443c89c", GitTreeState:"clean", BuildDate:"2017-06-13T12:26:12Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.527+bb877f1ee6b30c", GitCommit:"bb877f1ee6b30c0f70068aa5ffc4324e6443c89c", GitTreeState:"clean", BuildDate:"2017-06-13T12:21:56Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

I set up an API service with the aggregator that had an SSL certificate which was signed with the wrong DNS name.  The API service resource had a good status, but I would get 'resource not found' errors from kubectl trying to use it.  Eventually with @deads2k's help we found that there were discovery errors against the aggregated API group.  See a gist with relevant details here: https://gist.github.com/pmorie/0e8d5ba6c43d0c7000cd05a39a8ae190

**What you expected to happen**:

I would expect kubectl to warn that discovery failed instead of just saying that the resource didn't exist.

**How to reproduce it** (as minimally and precisely as possible):

Set up an API service resource with an incorrectly signed cert and try to use one of the aggregated resources.

**Comment by nikhita** [comment]
/remove-lifecycle rotten
/reopen

This still looks relevant
