### ISSUE TITLE
Too many functions are coupled to cobra.Command

### ISSUE THREAD

**Issue by alexandercampbell** [kubernetes/kubectl#32]
Many of the functions in `kubectl/cmd` require instances of `cobra.Command`, a complex and occasionally counterintuitive struct. In many cases the business logic of our application is very tightly coupled to `cobra.Command`.

This is bad for a few reasons:
1. Switching to an alternative configuration system for any reason is impossible.
2. Testing even simple methods requires "stubbing" `&cobra.Command{}`.
3. We can't refactor similar commands to use a common codepath (as in #11) without introducing unpredictability due to the differences in the Command instances.

`cobra.Command` would be better used as a value retrieval system.

**Comment by alexandercampbell** [comment]
Progress visible here: https://github.com/alexandercampbell/kubernetes/compare/cleanup-in-kubectl...alexandercampbell:kubectl-32-cobra-command-refactoring?expand=0

**Comment by smarterclayton** [comment]
Introduction of something like Assert is somewhat dubious, we've generally pushed back on that in the past - can you give an example of where you intend to use it?

**Comment by smarterclayton** [comment]
Re: coupling to cobra the rules of thumb have been (but not always enforced):

1. Nothing beyond the `Complete()` method may refer to the command
2. No utility function outside of `pkg/kubectl/...` should accept either the command or the command factory
3. Interfaces should be defined for FlagSets to avoid binding to pflag directly (we have a set of them, but use them lazily, which meant that some places were inconsistent)
4. The command factory was always intended to be a set of loose interfaces - code should never expect a command factory, but the interfaces that they layer (or subset interfaces defined in place like Go encourages)

**Comment by alexandercampbell** [comment]
@smarterclayton thanks for the feedback. I will likely rebase the Assert commit out of the branch before opening the pull request. I am curious to know why we've pushed back on Assert thus far, since I find it to be an excellent way to document expectations in the code.

I agree with all of the numbered points you gave. Unfortunately it seems that very little code follows them :)

**Comment by smarterclayton** [comment]
Re: Assert has come up mostly in cases where the preconditions are clear and would panic anyway (in which case the assert doesn't add a ton).  We also try to enforce less complex stateful inputs at interface boundaries, or guard anyway with if blocks.  Just hasn't been a great example of it being needed.

pkg/kubectl/cmd deserves a good separation pass - many of the early commands predated the decisions I mentioned above, and new contributors tended to follow the downhill slope.  The "options" pattern was not aggressively enforced early either, although we've done a better job of separation.  OpenShift has more commands that cross boundaries and so many of those patterns were retroactively enforced upstream (contrast the older https://github.com/openshift/origin/tree/master/pkg/cmd/cli/cmd with https://github.com/openshift/origin/tree/master/pkg/cmd/admin)

**Comment by alexandercampbell** [comment]
I've rebased out the Assert commit. Thanks again for your feedback.

I'd love to see (or work on) the kind of `kubectl/cmd` separation pass you're talking about.

Some background: My end goal is to consolidate the code underlying `kubectl run` and `kubectl create deployment` to solve issue #11. To that end, I am refactoring the Run functions to depend less on the details of a particular `cobra.Command`. I am making progress, but it's slow going, simply due to the [complex behavior](https://github.com/kubernetes/kubernetes/blob/2d023ab085c43b36ecbe56b250f00e7e70357fa5/pkg/kubectl/cmd/run.go#L139) of these functions.

**Comment by eddiezane** [comment]
Will be closed by #1046

**Comment by eddiezane** [comment]
Actually let's track at #1046 
/close
