### ISSUE TITLE
[kinflate] Override resources if redefined on overlays 

### ISSUE THREAD

**Issue by ant31** [kubernetes/kubectl#330]
**What happened**:
1, I created  'base-package' with a default configmap:
cat package/Kube-manifest.yaml
```
configmaps:
- name: app-env
  env: configmap/app.env
```

2. Created an overlay and modified the file app.env
```
configmaps:
- name: app-env
  env: configmap/new-app.env
```

3. Kinflate returned an error:
```
$ kinflate inflate -f . 
error: there is already an entry: "v1_ConfigMap_app-env.yaml"
```
**What you expected to happen**:
I expected that the configmap 'redefined' in the overlay to override the parent one.

Beside configmap, I think that all resources declared in an overlay should not conflict with the parent one and just replace them.

**Comment by monopole** [comment]
I'm moving issues to the new repo, or closing those that are a bit out of date.  Sorry we missed this, but i this behavior is different now.  See https://github.com/kubernetes-sigs/kustomize/blob/master/demos/configGeneration.md
