### ISSUE TITLE
Error message swapping arguments

### ISSUE THREAD

**Issue by joaocc** [kubernetes/kubectl#332]
---
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
When a config map specifies ```[]``` instead of ```{}``` the returned message is:
```
error: error validating "./ingress-controller-tcp-udp-map": error validating data: ValidationError(ConfigMap.data): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
The message should say ```got "array", expected "map";```

**How to reproduce it** (as minimally and precisely as possible):
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-controller-config-udp
  namespace: kube-system
data: []
```

**Anything else we need to know**:

**Comment by mengqiy** [comment]
@apelisse Looks like it's a bug in our openapi validation code.

**Comment by apelisse** [comment]
I see, the problem is that it should be `got "array", expected "map"`. Yeah, that sounds simple enough to fix. Thanks for reporting!

**Comment by apelisse** [comment]
If anybody wants to try to fix this, I'd be happy to help!

**Comment by zjj2wry** [comment]
I tried to reproduce it, but I found that master works fine. and maybe it fix by https://github.com/kubernetes/kube-openapi/pull/23
