### ISSUE TITLE
[plugin] kubectl plugin env variable is not incorrect

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubectl#337]
I am experimenting with writing plugins for kubectl. One issue I found is that `KUBECTL_PLUGINS_GLOBAL_FLAG_AS_GROUP` flag is set to `[]` when this flag is not set.
```
KUBECTL_PLUGINS_GLOBAL_FLAG_AS_GROUP=[]
```
When I try to set this env value back via `pflag.Set()`, it is considered as `[]string{"[]"}`. .This causes `DefaultClientConfig(flags)` to throw error. You can find my demo code here: https://github.com/tamalsaha/kubectl-plugin-demo/blob/master/root.go#L79

The real problem seems to be that [`String()`](https://github.com/spf13/pflag/blob/master/string_array.go#L30) and [`Set(val string)`](https://github.com/spf13/pflag/blob/master/string_array.go#L16) methods of `stringArrayValue` in pflag library does not properly handle "empty" value for flags.

**Comment by carolynvs** [comment]
I hit a similar (maybe the same?) bug in spf13/viper. Here's a related open PR: https://github.com/spf13/viper/pull/398.

I was able to work around the problem by switching to `StringSlice` instead of `StringArray`. https://github.com/kubernetes-incubator/service-catalog/pull/1700/files#diff-bac754e10d86591646bb672b9577e16bR74

**Comment by seans3** [comment]
Is this still relevant with the new plugin mechanism? Please close if this is obsolete.

**Comment by juanvallejo** [comment]
This should no longer be an issue with the updated plugin mechanism. Environment variables are now passed as-is, and user-defined command flags and parameters are now passed straight through to a plugin executable.

/close
