### ISSUE TITLE
`kubectl top nodes/pods` doesn't show Storage usage

### ISSUE THREAD

**Issue by hasanatkazmi** [kubernetes/kubectl#34]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Mostly feature

On running,
>> kubectl top -h
Display Resource (CPU/Memory/Storage) usage. 

Though it says but there is no option to get storage information. 
Storage information should also be displayed by `kubectl top nodes/pods` 

**Kubernetes version** (use `kubectl version`):

1.6

**Environment**:
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
mac
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by smarterclayton** [comment]
Top is an alpha command - the intent has been to rewrite it when the master metrics API is delivered in stable form (targeted for 1.8).  For now, dropping the help text seems reasonable.

**Comment by pwittrock** [comment]
@hasanatkazmi Would like to file a PR to drop the help text?
