### ISSUE TITLE
[plugin] Value must be assigned for boolean flags

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubectl#345]
With spf13/pflag library, you can just specify a boolean flags as `--flagname` to set the flag value to `true`. When a boolean flag is used in a kubectl plugin, this results in an error. Setting the flag to `--flagname=true` works as expected.

This is what the error message looks like:

```
$ kubectl plugin kubectl-plugin-demo env --analytics
Error: flag needs an argument: --analytics
```
Example plugin: https://github.com/tamalsaha/kubectl-plugin-demo

/kind bug

**Comment by carolynvs** [comment]
I have an open PR to address this gap https://github.com/kubernetes/kubernetes/pull/58768

**Comment by seans3** [comment]
@carolynvs @juanvallejo If this issue is obsolete or has been addressed with the new plugin mechanism, let's close this.

**Comment by carolynvs** [comment]
@seans3 Thanks for the reminder on this one. Yes now that kubectl is moving to the git plugin model, this is no longer an issue and is safe to close.

/close
