### ISSUE TITLE
cmd.Flags().Set() accepts invalid configurations in create_service_test.go

### ISSUE THREAD

**Issue by sandoracs** [kubernetes/kubectl#35]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.644+2ddde09a6ca650-dirty", GitCommit:"2ddde09a6ca6504f200572b44282dc9983641618", GitTreeState:"dirty", BuildDate:"2017-06-16T20:43:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-30T22:03:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  MacBook Pro mid 2015
- **OS** (e.g. from /etc/os-release): OS X 10.11.6 (15G1510)
- **Kernel** (e.g. `uname -a`): 15.6.0 Darwin Kernel Version 15.6.0

**What happened**:
cmd.Flags().Set() accepts invalid configurations in pkg/kubectl/cmd/create_service_test.go, e.g. cmd.Flags().Set("tcp", "8080:X") 

**What you expected to happen**:
Invalid configs should fail in tests

**How to reproduce it** (as minimally and precisely as possible):
Change cmd.Flags().Set("tcp", "8080:8080") to cmd.Flags().Set("tcp", "8080:X") in pkg/kubectl/cmd/create_service_test.go and run go test

**Comment by pwittrock** [comment]
@sandoracs Interested in filing a PR to fix?

**Comment by sandoracs** [comment]
Sure, why not! I'll take a look at it.

**Comment by sandoracs** [comment]
I was wrong, the second port (targetPort) can be a string. Therefore, cmd.Flags().Set("tcp", "8080:X") is valid. However, I've found other issues (int32 allowed as port) but I could fixed them.

**Comment by apelisse** [comment]
Looks like this is indeed stale. Feel free to re-open if it's a problem.
