### ISSUE TITLE
kubectl create clusterrolebinding: must error if --namespace is specified

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#361]
Users can easily confuse

```
kubectl create rolebinding serviceaccounts-view \
  --clusterrole=view \
  --group=system:serviceaccounts:my-namespace \
  --namespace=my-namespace
```

and

```
kubectl create clusterrolebinding serviceaccounts-view \
  --clusterrole=view \
  --group=system:serviceaccounts:my-namespace \
  --namespace=my-namespace
```

In latter command, the `--namespace` argument is SILENTLY IGNORED because clusterrolebinding is not a namespaced resource.

In such cases (silently ignoring something) we should be explicit and if `--namespace` is specified, `kubectl create clusterrolebinding` should error out!

**Comment by liggitt** [comment]
`--namespace` is a global flag. It can be passed to any kubectl command. The effect it has is to set the "current" namespace. There is no effective difference between using a `$KUBECONFIG` file containing a "current-context" which includes a namespace, and setting the `--namespace` flag on the command line. When working with cluster-scoped resources, the current namespace is not relevant, and is ignored.

Changing cluster-scoped resources to fail in this scenario would be a breaking change.

/close

**Comment by ahmetb** [comment]
@liggitt the tl;dr of this issue is that "silently ignoring passed flags is not a good idea", which your comment doesn't address as far as I can tell.

I think there's room for improvement in this case. I have previously opened bugs (and got them fixed) about "this command accepts --some flag and silently ignores it" for flags like `-o/--output`.

**Comment by liggitt** [comment]
the difference is that `-o`/`--output` isn't a global flag, and `--namespace` is. whether you specify `--namespace` or not, every kubectl command has a "current namespace".
