### ISSUE TITLE
Current bash-completion instructions do not work on Mac OS 10.11.6 and bash 3.2

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/kubectl#37]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):  "bash-completion"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Local env
- **OS** (e.g. from /etc/os-release):  Mac OS 10.11.6 
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:  
- **Others**:  bash 3.2

**What happened**:
Following instructions here https://kubernetes.io/docs/tasks/tools/install-kubectl/#on-macos-using-bash, bash autocompletion did not work for me.  

**What you expected to happen**:
Expected bash-completion to work.

**How to reproduce it** (as minimally and precisely as possible):
* Manually install kubectl
* Install bash-completion using homebrew
* `source <(kubectl completion bash)`

To get my bash completion to work, I had to follow a final step that is hinted at here: https://kubernetes.io/docs/user-guide/kubectl/v1.6/#completion.  I had to write the bash completion output to a file and then source that file.  

```
kubectl completion bash > ~/.kube/completion.bash.inc
printf "\n# Kubectl shell completion\nsource '$HOME/.kube/completion.bash.inc'\n" >> $HOME/.bash_profile
source $HOME/.bash_profile
```

**Anything else we need to know**:
Seems at least one other person has experienced this, but I couldn't find an open issue: https://github.com/kubernetes/kubernetes/issues/27876#issuecomment-272137153

**Comment by apelisse** [comment]
Thanks for opening the issue @ryanwalls.

It looks like the `bash-completion` code is not sourced properly. 

Can you verify that your `~/.bash_profile` has something like this:
```
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi
```

if this fixes the issue, we'll make sure we update the documentation to include that.

Credit goes to: http://davidalger.com/development/bash-completion-on-os-x-with-brew/

**Comment by ryanwalls** [comment]
@apelisse Yes, when I installed `bash-completion` it had said to put this in my `.bash_profile`:
```
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
```

So I did.  But it didn't fix the issue on my machine.

**Comment by apelisse** [comment]
Can you remind me what is the issue exactly?

> Following instructions here https://kubernetes.io/docs/tasks/tools/install-kubectl/#on-macos-using-bash, bash autocompletion did not work for me.

Can you elaborate what didn't work? Did you get an error?

**Comment by ryanwalls** [comment]
@apelisse No errors.  When I typed `kubectl` and then tabbed, it just showed the contents of the current directory instead of showing the available commands.  

When I looked in my environment `set | less` there were no references to `kubectl` auto complete commands.  So for me, `source <(kubectl completion bash)` did not work.  I don't know why.  Feel free to close if you feel this is just a one off problem.

**Comment by apelisse** [comment]
Yeah that's weird. Not much we can do about that :-/

**Comment by iamrandys** [comment]
I had the same issue and found that the bash installed by brew does not have this problem.

This is the version I'm running now.  The only version difference from what I was running before is the darwin version 17.0.0.

GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin**17.0.0**)

**Comment by knityster** [comment]
@apelisse , is very useful, thank you.

**Comment by Vickey-Wu** [comment]
I use bellow commands can use kubectl completion on my xshell but only when i close the window or new a window and retype these commands again can kubectl complete. I hope someone can help me do these work only once
```
apt install bash-completion
// locate bash_completion
source /usr/share/bash-completion/bash_completion
source <(kubectl completion bash)
```

**Comment by odrzutowiec** [comment]
I found this workaround
```
kubectl completion bash > $(brew --prefix)/etc/bash_completion.d/kubectl

```
then add this to .bashrc
```
if [ -f $(brew --prefix)/bash_completion.d/kubectl ]; then
. $(brew --prefix)/bash_completion.d/kubectl
fi
```

**Comment by mvillafuertem** [comment]
> I found this workaround
> 
> ```
> kubectl completion bash > $(brew --prefix)/etc/bash_completion.d/kubectl
> ```
> then add this to .bashrc
> 
> ```
> if [ -f $(brew --prefix)/bash_completion.d/kubectl ]; then
> . $(brew --prefix)/bash_completion.d/kubectl
> fi
> ```

doesn't work 

Mac OS Sierra 10.12.6 (16G1710)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

**Comment by kke** [comment]
Instead of

```
$ source <(kubectl completion bash)
```

you can use this on the legacy-bash on mac:

```
$ source /dev/stdin <<<"$(kubectl completion bash)"
```

**Comment by kke** [comment]
My solution only worked on the bash 3 that ships (shipped?) with MacOS.

**Comment by tudyzhb** [comment]
> The above command `source /dev/stdin <<<"$(kubectl completion bash)"` produces the following when I hit tab after typing `kubectl ge`:
> 
> `thomashavlik$ kubectl getbash: _get_comp_words_by_ref: command not found`
> 
> I have not found a way to get bash completion working on MacOS after following both official documentation and issues here on github.
> 
> MacOS: 10.14.5
> Bash: 5.0.7(1)-release
> kubectl: v1.15.1

You should check the bash version of your terminal session:

```
echo $BASH_VERSINFO
```

If `$BASH_VERSINFO` <= 3:
[change your default shell like this](https://stackoverflow.com/questions/23059662/how-can-i-get-iterm-to-use-the-newer-version-of-bash-that-brew-shows-change-a-u)
