### ISSUE TITLE
Kinflate should allow configMap overlay.

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes/kubectl#374]
Considering the base and instances for spring-boot example: https://github.com/kinflate/spring-boot-helloworld
The base defines a configmap from file application.properties.
The staging instance wants to use the same configmap but with a different application.properties file.
Currently kinflate inflate gives the error as:
`there is already an entry: "v1_ConfigMap_demo-configmap.yaml"`

**Comment by monopole** [comment]
done
