### ISSUE TITLE
inconsistencies when using flag '-o json'

### ISSUE THREAD

**Issue by aguilbau** [kubernetes/kubectl#38]
**kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- aws
- coreos
- `Linux ip-10-0-65-22 4.11.2-coreos #1 SMP Tue May 23 22:04:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux`
- tectonic installer:

**What happened**:
I have a daemonset, running on 5 nodes. When I kill a pod of this daemonset and get it's status
with kubectl, I will notice inconsistencies with the json output ( `-o json` )

For example, when I kill the pod and run
`kubectl get pod "$POD_NAME"`,
it's status will be `Terminating`

But, killing it and running
`kubectl get pod "$POD_NAME" -o json | jq '.status.phase'`,
I will get `Running`

Also, as I said, this pod is from a daemonset.
When I do `kubectl get daemonset "$DAEMONSET_NAME" -o json`,
the output of `status` will sometime be inconsistent too.
for example, after killing a pod and waiting for it to be up again ( status Running ),
the status of the daemonset will look like that
```
    "status": {
        "currentNumberScheduled": 5,
        "desiredNumberScheduled": 5,
        "numberAvailable": 4,
        "numberMisscheduled": 0,
        "numberReady": 4,
        "numberUnavailable": 1,
        "observedGeneration": 3,
        "updatedNumberScheduled": 5
    }
```

**What you expected to happen**:

Both command should give me the same result, ie `Terminating`

**How to reproduce it** (as minimally and precisely as possible):

- kill a pod
- get it's status using `kubectl get pod "$POD_NAME"`
- kill another pod
- get it's status using `kubectl get pod "$POD_NAME" -o json | jq '.status.phase'`

**Comment by pwittrock** [comment]
Thanks for the issue.

For some resources `get` does some logic instead of just printing what is in the yaml so this is expected.
