### ISSUE TITLE
kubectl config view: should error out on positional argument

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#386]
/sig cli
/kind bug

`kubectl config view` does not complain when I give it a positional argument.

Apparently this command only uses the current-context set.

So I've been confused for 5 minutes straight why 

    kubectl config view A
    kubectl config view B

are returning the same thing.

Please make this command exit with ERROR message/code when someone passes an unused/silently-ignored positional argument.

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/70413 (thanks @Pingan2017!)

/close
