### ISSUE TITLE
Scaling a deployment always sets 'schedulerName' to 'default-scheduler' (kubectl 1.5.7, master 1.6.4)

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubectl#39]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
'schedulerName', 'scale'

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
```
$ ./kubectl-1.5.7 version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): client: darwin and linux(alpine 3.5.2).  Server Debian 7.
- **Kernel** (e.g. `uname -a`): client darwin 15.6.0 and Debian 3.16.39-1.  Server Debian 3.16.39-1
- **Install tools**: GKE for master.  Curl'ed version of kubectl from GCS
- **Others**:

**What happened**:
When scaling a replication controller or deployment a using version 1.5.7 of kubectl against a 1.6.4 master`kubectl scale` sets the schedulerName attribute of podspec within the controller to 'default-scheduler' regardless of the original value.  All new pods created by the controller have their schedulerName attribute then set to 'default-scheduler'.

**What you expected to happen**:
The value of 'schedulerName' should not be set to default-scheduler.

**How to reproduce it** (as minimally and precisely as possible):
Complete example showing the problem:
```
$ cat deployment.yaml 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: third-party
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

$ ./kubectl-1.5.7 create -f deployment.yaml 
deployment "nginx-deployment" created
$ ./kubectl-1.5.7 get deployment nginx-deployment -o yaml | grep schedulerName
      schedulerName: third-party
$ ./kubectl-1.5.7 scale deployment nginx-deployment --replicas=3
deployment "nginx-deployment" scaled
$ ./kubectl-1.5.7 get deployment nginx-deployment -o yaml | grep schedulerName
      schedulerName: default-scheduler
```

**Anything else we need to know**:
The system works as expected if you have a 1.6.4 version of kubectl.  Additionally I would expect other scalable controllers to have this issue; I just tested with deployments and replication controllers.  As seen in my example the system allows you to create a deployment with a schedulerName set to a value of 'third-party' just the patching of the object during the scale operation seems to cause the problem.

**Comment by cameronbrunner** [comment]
Since the already released version of kubectl can't be changed to fix this its just something people will likely have to live with.  I think this adds more weight to the discussion in https://github.com/kubernetes/kubernetes/issues/42392 around highly recommending keeping the major and minor versions of the client and server in sync (or a newer client than server).  

What is particularly troubling about this one is that this overwrite happens transparently and involves an operation that may occur frequently in a running cluster.  One old client could easily mess up a cluster that utilizes schedulers other than the default.

**Comment by pwittrock** [comment]
Thanks for the bug.  Yes this would require a patch release, which if someone was going to install we would recommend they just upgrade to 1.6 for their cluster.

**Comment by cameronbrunner** [comment]
No problem.  Main reason for the submission was to make sure that if someone else saw this type of behavior at least the issue would be documented.  It may be worth a quick check in the patch code to see if other values being are being or could be overwritten.
