### ISSUE TITLE
kubectl config set: parameter name split with space in --help

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#397]
kubectl v1.10.0
/kind bug
/sig cli

See the space in `PROPERTY _NAME` and `PROPERTY _VALUE` occurrences below:

```
$ kubectl config set --help
Sets an individual value in a kubeconfig file

PROPERTY _NAME is a dot delimited name where each token represents either an attribute name or a map key.  Map keys may
not contain dots.

PROPERTY _VALUE is the new value you wish to set. Binary fields such as 'certificate-authority-data' expect a base64
encoded string unless the --set-raw-bytes flag is used.

Options:
      --set-raw-bytes=false: When writing a []byte PROPERTY_VALUE, write the given string directly without base64
decoding.

Usage:
  kubectl config set PROPERTY_NAME PROPERTY_VALUE [options]
```

**Comment by someword** [comment]
I took a run at this and failed to find a good resolution.    Anywhere templates.LongDesc is called like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/set.go#L48 goes through the markdown processor here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/templates/normalizers.go#L34.   The characters *, _, & and [ (possibly others) get prepended by a space.

The following test run in the https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/templates directory demonstrate the problem.


`  

    package templates
    
    import (
    	"fmt"
    	"testing"
    )
    
    func TestLongDesc(t *testing.T) {
    	fmt.Println("testing testy tester")
    	testData := []struct {
    		n        string
    		expected string
    	}{
    		{"A_underscore", "A_underscore"},
    		{"A[bracket", "A[bracket"},
    		{"A&ampersand", "A&ampersand"},
    		{"A*asterisk", "A*asterisk"},
    	}
    
    	for _, d := range testData {
    		actual := LongDesc(d.n)
    		if actual != d.expected {
    			t.Errorf("LongDesc: expected %s, actual %s", d.expected, actual)
    		}
    	}
    }
`

I traced the problem to the private callback methods here https://github.com/russross/blackfriday/blob/master/markdown.go#L366-L381 but could not pry any deeper.    It seems like the proper solution would be to set different per character callback methods but I couldn't figure out how to do that.

**Comment by nikhita** [comment]
This is still relevant.
/remove-lifecycle stale

But this does not meet the criteria for help-wanted because the general direction for the solution is not yet defined.
/remove-help
