### ISSUE TITLE
Cant set context

### ISSUE THREAD

**Issue by owenmorgan** [kubernetes/kubectl#4]
When using kubectl 

`kubectl version                                                                                                                                                            (jd-uat/default)
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

i have 2 different contexts set in config trying to set context from one to another doesn't switch.

`▶ kubectl config current-context                                                                                           
od-uat

~
▶ kubectl config set-context oi-uat
Context "oi-uat" set.

~
▶ kubectl config current-context
od-uat`

And the config file still shows as 

`current-context: od-uat`

**Comment by mengqiy** [comment]
You should use `kubectl config use-context`.

**Comment by owenmorgan** [comment]
Doh!

**Comment by ollyde** [comment]
Doesn't follow a proper pattern and it doesn't throw an error for ```kubectl config set-context``` kinda silly.

**Comment by sfusco-kryptowire** [comment]
If set-context doesn't change the context... what does it do?

**Comment by raweber42** [comment]
@sfusco-kryptowire from the docs:

> Set a context entry in kubeconfig.
[Source](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-context/)

Naming is quite confusing, I agree.
`set-context` is used to create or update a context in your Kubernetes configuration file. It allows you to _define_ the cluster, user, and namespace for a context, which defines the environment in which your Kubernetes commands will operate.

So it's only for the _definition_ part :D
