### ISSUE TITLE
kubectl zsh completion cause directory path completion has extra space

### ISSUE THREAD

**Issue by zerda** [kubernetes/kubectl#407]
**Is this a BUG REPORT or FEATURE REQUEST?** : BUG REPORT

**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Aliyun ECS
- **OS**: Ubuntu 16.04.4 LTS
- **Kernel**: 4.4.0-105-generic
- **Install tools**: zsh 5.1.1

**What happened**:

When hit <kbd>tab</kbd> to complete a sub directory path, zsh added an extra space after the directory path. 
It causes press <kbd>tab</kbd> repeatly to complete additional path impossible.

**What you expected to happen**:

Like bash completion, only file completion with extra space, there should be no space after directory.

**How to reproduce it**:

1. Says there is a file `foo/bar.yaml`;
1. Typing `kubectl apply -f f`, then press <kbd>tab</kbd>;
1. It complete with `foo/<space>`, instead of `foo/`;
1. I need to delete this extra space, then press <kbd>tab</kbd> again to complete the file `bar.yaml`。 

But there is another situation working correctly.
1. Same as `~/foo/bar.yaml`;
1. Typing `kubectl apply -f ~/f`, then press <kbd>tab</kbd>, it finished with `kubectl apply -f ~/foo/`. 

**Anything else we need to know**:

From debug log,  I got this for `f` completion.
```
_filedir @(json|yaml|yml) cur=f
RET=foo len=1
```

Got this for `~/f` completion.
```
_filedir @(json|yaml|yml) cur=~/f
RET= len=0
```

It seems there is something different in `RET=( $(compgen -f) )` of [completion.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion.go#L239).

**Comment by luciano-numen** [comment]
Any update on this?

**Comment by dijitali** [comment]
Can also reproduce on the below environment.  Similar to the working situation above with the tilde, autocompletion of`kubectl apply -f ./f` does not cause this issue.

**Kubernetes version:**
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
```
**Environment:**
**OS:** macOS Mojave 10.14.1
**Kernel:** Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
**Install tools:** zsh 5.6.2

**Comment by dennisxrow** [comment]
A workaround for me is to just remove kubectl's completion for the "-f" flag and let it fallback to the standard zsh file / path completion.

I used

```sh
source <(kubectl completion zsh | sed '/"-f"/d')
```

instead of 

```sh
source <(kubectl completion zsh)
```

**Comment by HaveFun83** [comment]
Same issue here

**Comment by ortizmj12** [comment]
Same issue here

**Comment by danielhanold** [comment]
Same issue here. 

### kubectl version info
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}

### zsh version info
zsh 5.8 (x86_64-apple-darwin19.3.0)

**Comment by knight42** [comment]
I have filed a PR https://github.com/kubernetes/kubernetes/pull/89479 to fix this issue, please give it a try and feel free to tell me any problem you encountered.

**Comment by jamylak** [comment]
> A workaround for me is to just remove kubectl's completion for the "-f" flag and let it fallback to the standard zsh file / path completion.
> 
> I used
> 
> ```shell
> source <(kubectl completion zsh | sed '/"-f"/d')
> ```
> 
> instead of
> 
> ```shell
> source <(kubectl completion zsh)
> ```

I had to do the following, I just replaced with `foo` cause I was a bit frustrated

in this file
```
 ~/.o/p/k/kubectl.plugin.zsh                                                                                                                                                  
 if (( $+commands[kubectl] )); then
     __KUBECTL_COMPLETION_FILE="${ZSH_CACHE_DIR}/kubectl_completion"
 
     if [[ ! -f $__KUBECTL_COMPLETION_FILE || ! -s $__KUBECTL_COMPLETION_FILE ]]; then
         kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
     fi
```

```
vim ~/.oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh
```

Change

```
kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
```

->

```
(kubectl completion zsh | sed "s/kubectl_apply/foo/g") >! $__KUBECTL_COMPLETION_FILE
```

then

```
rm ~/.oh-my-zsh/cache/kubectl_completion
```

then start new shell
