### ISSUE TITLE
kubectl config set hangs on some invalid property names

### ISSUE THREAD

**Issue by jheiss** [kubernetes/kubectl#415]
(Previously reported by someone else in kubernetes/kubernetes#29312)

I haven't quite figured out exactly what the pattern is, but property names that are almost but maybe not quite right seem to trigger it. For example, this hangs: `kubectl config set users.jheiss.exec.command test`

**Comment by natefox** [comment]
I see this hang too. Appears it was introduced at v1.10 as the v1.9.8 binary gives a quick failure. Ultimately hoping for kubernetes/kubernetes#64751

```
$ /tmp/kubectl-1.9.8 config set users.aws.exec.command blah -v=10 --kubeconfig=/tmp/k
I0618 16:40:37.672411   23422 loader.go:357] Config loaded from file /tmp/k
F0618 16:40:37.672627   23422 helpers.go:119] error: can't set a map to a value: map[aws:0xc420941180]

$ /tmp/kubectl-1.10.4 config set users.aws.exec.command blah -v=10 --kubeconfig=/tmp/k
I0618 16:40:43.418784   23450 loader.go:357] Config loaded from file /tmp/k
^C  #hangs forever
```

**Comment by adohe** [comment]
I would take a look. but whats the relation between this issue and #64751?

**Comment by sellers** [comment]
@adohe I think @natefox referenced it because the commands that @jheiss was trying to run are related the the feature request.    It's tangential.     I hope that helps.

**Comment by pswica** [comment]
I tried to fix this in the PR above
