### ISSUE TITLE
Kinflate: dec.DisallowUnknownFields undefined

### ISSUE THREAD

**Issue by karan** [kubernetes/kubectl#418]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kinflate
kinflate json

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Macbook Pro
- **OS** (e.g. from /etc/os-release): MacOS 10.13.3
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 17.4.0
- **Install tools**:
- **Others**: go 1.9.2

**What happened**:

Tried to install kinflate:

```
$ go get k8s.io/kubectl/cmd/kinflate
# k8s.io/kubectl/pkg/kinflate/app
../../../kubectl/pkg/kinflate/app/application.go:253:5: dec.DisallowUnknownFields undefined (type *json.Decoder has no field or method DisallowUnknownFields)

```

**What you expected to happen**:

Install succeeds.

**How to reproduce it** (as minimally and precisely as possible):

Try to install kinflate using go1.9.2 on MacOS.

**Anything else we need to know**:

**Comment by karan** [comment]
Ah `DisallowUnknownFields` is supported in go 1.10. That explains it.

So now the issue really is whether `DisallowUnknownFields` is *really* needed, and if not we can support go1.9

**Comment by monopole** [comment]
moved the code to https://github.com/kubernetes-sigs/kustomize, now moving issues.

Feel free to open an issue there to support 1.9 if you wish, thanks!
