### ISSUE TITLE
"kubectl label all" skips secrets

### ISSUE THREAD

**Issue by przemek-sl** [kubernetes/kubectl#425]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubectl label secrets

---

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS**: Mac OS X (10.13.2, build 17C88)
- **Kernel**: 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

**What happened**:
`kubectl label all` skips labelling secrets. They have to be set explicitly in parameters.

```
$ kubectl label all --all key2=value2
pod "lunging-spaniel-myproject-85c64d89df-7vsjx" labeled
service "kubernetes" labeled
service "lunging-spaniel-myproject” labeled
deployment.extensions "lunging-spaniel-myproject" labeled
replicaset.extensions "lunging-spaniel-myproject85c64d89df" labeled
deployment.apps "lunging-spaniel-myproject" not labeled
replicaset.apps "lunging-spaniel-myproject-85c64d89df" not labeled

$ kubectl label secrets --all key2=value2
secret "default-token-sjjdm" labeled
secret "lunging-spaniel-myproject" labeled
secret "lunging-spaniel-myproject-jwt" labeled
````

**What you expected to happen**:
`kubectl label all` should label all resources, without any exceptions.

**Comment by liggitt** [comment]
> kubectl label all should label all resources, without any exceptions.

for historical reasons, the `all` category does not include some resources. see https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all for guidance on what is included:
 •	No cluster scoped resources 
 •	No namespace admin level resources (limits, quota, policy, authorization rules) 
 •	No resources that are potentially unrecoverable (secrets and pvc) 
 •	Resources that are considered "similar" to #3 should be grouped the same (configmaps)
