### ISSUE TITLE
Cannot use Windows paths in create secret --from-file

### ISSUE THREAD

**Issue by jordansissel** [kubernetes/kubectl#427]
**What keywords did you search in Kubernetes issues before filing this one?** kubectl create secret generic from-file windows "is not a valid key name for a Secret"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Kubernetes version** (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): Windows 10
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: Chocolatey
- **Others**:

**What happened**:

```
> kubectl create secret generic example --from-file .\example\thing.txt
error: ".\\example\\thing.txt" is not a valid key name for a Secret: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**What you expected to happen**:

The contents of the file `.\example\thing.txt` should be used to create the secret named `example`

**How to reproduce it** (as minimally and precisely as possible):

```
# On windows (PowerShell)
> mkdir example
> echo foo | out-file .\example\thing.txt
> kubectl create secret generic example --from-file .\example\thing.txt
```

**Anything else we need to know**:

* If the file does not exist, you get a different error:

```
> rm .\example\thing.txt
> kubectl create secret generic example --from-file .\example\thing.txt
error: error reading .\example\thing.txt: The system cannot find the file specified.
```

* You can work around this by using unix-style paths:

```
> kubectl create secret generic example --from-file .\example\thing.txt
<fails>

> kubectl create secret generic example --from-file ./example/thing.txt
secret "example" created
```

**Comment by vithati** [comment]
This issue fixed with this commit https://github.com/kubernetes/kubernetes/commit/17e62d91af7d1afc4be7185c6a490a176c0afe12  and fix available from kubectl v1.11.0-beta.0 version onwards.

**Comment by SurferJeffAtGoogle** [comment]
Thank you vithati!

**Comment by idealhack** [comment]
Thanks!

/close
