### ISSUE TITLE
kubectl --sort-by not working in 1.7.0

### ISSUE THREAD

**Issue by fiksn** [kubernetes/kubectl#43]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Kubernetes cluster is running on CoreOS

VERSION=1409.5.0
VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"

Kernel 4.11.6-coreos-r1, but that should be pretty irrelevant as it seems the problem is in kubectl.
Tried on MacOS 10.12.5 with 1.7.0 kubectl and on various GNU/Linux machines. It doesn't work also against a 1.6.6 Kubernetes cluster so I am quite confident this is a client issue.

**What happened**:
$ kubectl get pods --sort-by='{.metadata.name}'
error: unknown type *api.Pod, expected unstructured in map[reflect.Type]*printers.handlerEntry{}

**What you expected to happen**:
A list of pods sorted by name should have appeared as was the case with 1.6.6.

**Comment by mengqiy** [comment]
/assign @shiywang
Do you have bandwidth to look into this?

**Comment by shiywang** [comment]
@mengqiy sure

**Comment by shiywang** [comment]
already found the root cause, will submit a patch soon
