### ISSUE TITLE
Consolidate the Deployment Generators

### ISSUE THREAD

**Issue by alexandercampbell** [kubernetes/kubectl#44]
Issue type: refactor

### Description

[`pkg/kubectl/deployment.go`](https://github.com/kubernetes/kubernetes/blob/cb712e41d435dbb42519bded680fef4043dd23b3/pkg/kubectl/deployment.go) is the same 100 lines copy/pasted. `DeploymentBasicAppsGeneratorV1` and `DeploymentBasicGeneratorV1` are identical except they return `extensionsv1beta1.Deployment` and `appsv1beta1.Deployment` respectively.

If I consolidate these structs to use the same codepath, I don't have to make [the same changes twice](https://github.com/alexandercampbell/kubernetes/pull/1) to add new parameters (like `--label`, for instance).

### Acceptance criteria

- [ ] `--label` can be added to the "kubectl create deployment" Generators without making the same changes in two places.
- [ ] Generator behavior is exactly the same as it is in master.

**Comment by alexandercampbell** [comment]
fyi @pwittrock 
I decided to create a separate issue for this since it's a well-defined block of work.

**Comment by mengqiy** [comment]
FYI, difference between `extensionsv1beta1.Deployment` and `appsv1beta1.Deployment` is the defaulting for `RevisionHistoryLimit` is different.
But I don't think generator support setting `RevisionHistoryLimit` at this time.

**Comment by alexandercampbell** [comment]
That's an interesting bug.
The commit is in master, if anyone's curious: https://github.com/kubernetes/kubernetes/commit/d74ac3785eafd8644a1ac2c9757f613105d76a4f
