### ISSUE TITLE
kubectl exec should take a deploy as an argument

### ISSUE THREAD

**Issue by rcorre** [kubernetes/kubectl#444]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

```
is:issue kubectl exec  in:title deploy in:title
```
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Feature**

`kubectl logs deploy/mydeploy` gets the logs for one pod of the deployment. It would be nice to have a parallel command for `exec`, where `kubectl exec deploy/mydeploy -it -- /bin/sh` gets me a shell onto one of the pods from `mydeploy`.

Right now I get:

```
error: invalid resource name "deploy/mydeploy": [may not contain '/']
```

**Comment by nesl247** [comment]
It's a little frustrating to always have to get a pod which has an unknown name. This would certainly make it a lot easier.
