### ISSUE TITLE
kubectl get pods --all-namespaces returns error 

### ISSUE THREAD

**Issue by nikhilagrawal577** [kubernetes/kubectl#475]
/kind bug
/sig cli

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
1.8.5

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

- **Kernel** (e.g. `uname -a`):
Linux mo-635ef62b9 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
With AWS, when i try to get all the pods in the cluster, it shows error. 
```
FVFV50CPJ1WV:kubernetes i076657$ kubectl get pods --all-namespaces
Stream error http2.StreamError{StreamID:0x33, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry
```

**What you expected to happen**:
It should show all the pods available in all the namespaces. 

**How to reproduce it** (as minimally and precisely as possible):

kubectl get pods --all-namespaces 

**Anything else we need to know**:

**Comment by seans3** [comment]
Based on the error message this appears to be a transient networking problem. Based on the lack of activity, I'm closing this issue. If it is reproducible, please reopen.
