### ISSUE TITLE
kubectl shows localized messages even though LC_MESSAGES=C

### ISSUE THREAD

**Issue by majewsky** [kubernetes/kubectl#476]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): Arch Linux
- **Kernel** (e.g. `uname -a`): Linux hostname 4.16.7-1-ARCH #1 SMP PREEMPT Wed May 2 21:12:36 UTC 2018 x86_64 GNU/Linux
- **Install tools**: curl

`kubectl --help` prints some messages localized to German even though I explicitly forbade that in my locale settings.

```
$ env | grep $'LC\nLANG'
LANG=de_DE.UTF-8
LANGUAGE=
LC_MESSAGES=C
$ kubectl set --help
Configure application resources

These commands help you make changes to existing application resources.

Available Commands:
  env            Update environment variables on a pod template
  image          Aktualisiere das Image einer Pod-Template
  resources      Aktualisiere Resourcen requests/limits auf Objekten mit Pod-Templates
  selector       Setze den Selektor auf einer Resource
  serviceaccount Update ServiceAccount of a resource
  subject        Update User, Group or ServiceAccount in a RoleBinding/ClusterRoleBinding

Usage:
  kubectl set SUBCOMMAND [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by majewsky** [comment]
:clap:

/remove-lifecycle stale

**Comment by m1kola** [comment]
It looks like kubectl currently only supports the `LANG ` env var, it makes perfect sense to me to allow to set `LC_MESSAGES` to override just messages [1]. However, I'm not sure if we want to support `LC_ALL` and `LANGUAGE` env vars as well to more closely follow [this priority order](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html).

I've decided to implement only `LC_MESSAGES` for now in https://github.com/kubernetes/kubernetes/pull/69500

[1] BTW, kubectl doesn't support other categories of locales, at the moment.
