### ISSUE TITLE
Provide the ability to clear the current kubectl context without explicitly setting a new one

### ISSUE THREAD

**Issue by zentron** [kubernetes/kubectl#483]
**Feature Request**

When attempting to run scripts we sometimes want to create and use a "temporary" context that can be easily cleaned up afterward. (as opposed to appending the `--server` etc arguments to every command since they may be externally loaded)

e.g
```
...
$originalContext = $(kubectl config current-context)
kubectl config set-context tempcontext --user=tempuser --cluster=tempcluster
kubectl config use-context tempcontext 
...

do some stuff
...
kubectl config use-context $originalContext
kubectl config delete-context tempcontext 
kubectl config delete-cluster tempcluster
...etc

```
However the `delete-context` result may end up with `warning: this removed your active context, use "kubectl config use-context" to select a different one` if there was no original context set (lets say on a fresh machine).  Although the context can start as "" in the config, there is no way to just set it to "" since `kubectl config use-context` with no context _name_ results in an error due to "unexpected args"

It would be nice if we could either 
1. Use the `use-context` command and provide a null or empty context (or some `--clear` arg)
2. Or provide a `kubectl config clear-context`

**Comment by jeremyjh** [comment]
@zentron do you have a workaround for this? When I'm not actively working with Kubernetes I'd like to clear my context so it doesn't take up room in my prompt.

**Comment by zentron** [comment]
@jeremyjh for my purposes I ended up just setting the `KUBECONFIG` environment variable (https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable) so that i could create a temporary context and then delete it for clean up once my operation is complete. Given this work-around I'm happy to consider this task as closed for my purposes.

**Comment by grugnog** [comment]
Another use case for this - if you use a combination of minikube (or other "dev" clusters) and production clusters I find it helpful to set the context at the beginning of a session and explicitly clear it afterwards. This helps avoid accidentally running commands against the wrong cluster.

I have the current context on my prompt using the fantastic Go Bullet Train (GBT) to remind me to what the context is (and to clear it afterwards!).

Currently I have the following alias to do this:
```alias kubeclr='sed -i"" -e"s/^current-context:.*$/current-context:/" ~/.kube/config'```

**Comment by madAndroid** [comment]
It looks like this might already have been implemented? I was looking for a way of doing this, and was able to achieve this using:
```
$ kubectl config unset current-context
Property "current-context" unset.
```

**Comment by tdmalone** [comment]
@madAndroid is correct - this has already been implemented, and thus this ticket should be allowed to close.

Is possible like this:
```
$ kubectl config unset current-context
Property "current-context" unset.
```

fwiw I was previously using this workaround, which is not actually needed:
```
alias kclear='sed -i.bak -e"s/^current-context:.*$/current-context:/" ~/.kube/config'
```

**Comment by seans3** [comment]
@tdmalone Thanks for the explanation.  Closing.

/close

**Comment by safaci2000** [comment]
For those stumbling on this ticket:  ` kubectl config unset current-context`
