### ISSUE TITLE
Have an option to print the URL and body of the request that will be sent to the server

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubectl#494]
For educational purposes it would be cool if you could request to have kubectl dump to stdout or stderr the REST path and request body corresponding to the kubectl command you run. Perhaps if this were implemented it would make sense to also have a "dry run" mode so you would only get this output and not actually make the request to the server.

**Comment by adohe** [comment]
@davidopp what's the difference between using high log level and using this option? use `--v=10` will also print the URL and request body that will be sent to the server. As for `dry-run` I think many of kubectl commands has implement this functionality.

**Comment by davidopp** [comment]
Oh cool, I didn't realize --v=10 already did this. Thanks!
