### ISSUE TITLE
Way to get list of pods running in a service

### ISSUE THREAD

**Issue by vidhill** [kubernetes/kubectl#495]
**Is this a request for help?** no

**What keywords did you search in Kubernetes issues before filing this one?** pods service
---

**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

I think this is a feature request, but perhaps it does exist but isn't easy to find.
I searched quite a bit, but couldn't find an answer.

I want to get a list of pods that are selected/exposed by a particular service..

I found a workaround, using a bash script but it feels like something I would have expected to be in kubectl.

https://gist.github.com/vidhill/20d4c6ae231aa84e34078ac83e10c5f0

**Comment by seans3** [comment]
The kubectl issues repo is used for tracking problems and code progress. Please look on Stackoverflow for information on using kubectl. For your query, please have a look at "kubectl get pod -l <service label selector>".
