### ISSUE TITLE
kubectl set --help : please add examples 

### ISSUE THREAD

**Issue by DStorck** [kubernetes/kubectl#496]
kubectl version 1.10.0
/kind documentation
/sig cli

**Is this a request for help?** : No, but it would be very helpful. The [Kubernetes references docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#set) do not provide examples either for `kubectl set`

**What keywords did you search in Kubernetes issues before filing this one?** :` kubectl`,  `set`  - there is a [similar issue](https://github.com/kubernetes/kubectl/issues/398) filed for `kubectl config set` but I'd like to see example for `set` on its own as well

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

Many other kubectl commands give lots of examples with `--help` , but there are none, so it is tough to know quickly what kinds of things this can be used with. It just inconsistent, most other commands have examples. 

Current display: 
```$ kubectl set --help
Configure application resources

These commands help you make changes to existing application resources.

Available Commands:
  env            Update environment variables on a pod template
  image          Update image of a pod template
  resources      Update resource requests/limits on objects with pod templates
  selector       Set the selector on a resource
  serviceaccount Update ServiceAccount of a resource
  subject        Update User, Group or ServiceAccount in a RoleBinding/ClusterRoleBinding

Usage:
  kubectl set SUBCOMMAND [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).```

**Comment by MasayaAoyama** [comment]
Hello, 

we can see "kubectl set env -h" or "kubectl set * -h".
and "kubectl create service -h" also don't show examples, and "kubectl create service loadbalancer -h" show examples.

Maybe I think it is policy of kubectl, maybe.
Do you think we need examples for "set env", "create service", and so on?
If need, I would like to implement.

**Comment by DStorck** [comment]
it would probably be enough to just include several examples in `kubectl set -h` to give people an idea of how to work with the command, those examples could even carry over into `kubectl set * -h` as you mentioned.  But right now there it very difficult to find examples anywhere.

**Comment by MasayaAoyama** [comment]
now, we can get examples "kubectl set env -h", "kubectl set image", and so on.
we also need "kubectl set -h"?

**Comment by adohe** [comment]
`kubectl set env -h` is always what we want, no need to give examples in `kubectl set -h`.

**Comment by chenyb4** [comment]
In kubectl v1.11.2 was exist examples.

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

 kubectl set env -h
Update environment variables on a pod template.

List environment variable definitions in one or more pods, pod templates. Add, update, or remove container environment
variable definitions in one or more pod templates (within replication controllers or deployment configurations). View or
modify the environment variable definitions on all containers in the specified pods or pod templates, or just those that
match a wildcard.

If "--env -" is passed, environment variables can be read from STDIN using the standard env syntax.

Possible resources include (case insensitive):

  pod (po), replicationcontroller (rc), deployment (deploy), daemonset (ds), job, replicaset (rs)

Examples:
  # Update deployment 'registry' with a new environment variable
  kubectl set env deployment/registry STORAGE_DIR=/local

  # List the environment variables defined on a deployments 'sample-build'
  kubectl set env deployment/sample-build --list

  # List the environment variables defined on all pods
  kubectl set env pods --all --list
