### ISSUE TITLE
Misleading printout of forward-ports

### ISSUE THREAD

**Issue by neopaf** [kubernetes/kubectl#498]
**Kubernetes version** (use `kubectl version`):

```
rualpe-ws:pbrf-k8s paf$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
rualpe-ws:pbrf-k8s paf$ 
```

**Environment**:

```
rualpe-ws:pbrf-k8s paf$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
rualpe-ws:pbrf-k8s paf$ 
```

**What happened**:

```
rualpe-ws:pbrf-k8s paf$ kubectl --namespace monitoring port-forward service/grafana 3000:80
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

**What you expected to happen**:

Since port 3000 is forwarded to port 80, I expected printout to show "-> 80".

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by MasayaAoyama** [comment]
Hello :)
Service is "80(service port) > 3000(pod port)",
Port-forward is "3000(localport) > 3000(pod port)".

And we operate port-forwarding 
  1. "local port > pod port" for pod, or 
  2. "service port > pod port" for service.

But actually we can only use port-forward to pod.
If we use "port-forward service", kubectl choose 1 pod from pods related the service.
So, I think output is "3000(localport) > 3000(pod port)".

for example, 
* service port(8080)
* local port (2020)
* pod port (80)

```
$ kubectl port-forward service/sample-clusterip 2020:8080
Forwarding from 127.0.0.1:2020 -> 80
Forwarding from [::1]:2020 -> 80
```

What do you think?

**Comment by neopaf** [comment]
I think this is very understandable, and maybe reasonable.
Yet kinda confusing.
In a command I talk about port-forwarding to a service, and not about port-forwarding to pod.

Maybe add small "(pod)" to clarify what's going on?
To look it like this (continuing your example):
```bash
$ kubectl port-forward service/sample-clusterip 2020:8080
Forwarding from 127.0.0.1:2020 -> 80 (pod)
```

Other option:
```bash
$ kubectl port-forward service/sample-clusterip 2020:8080
Forwarding from 127.0.0.1:2020 -> 8080 (service) -> 80 (pod)
```
;)

**Comment by bhavin192** [comment]
@neopaf I think the first one is more correct, as MasayaAoyama said it actually port-forwards to the pod not the service.

**Comment by neopaf** [comment]
Maybe. Yet second gives a bit more insight as to what was done. 
Not insisting on that second ;)
