### ISSUE TITLE
Remove kubectl dependencies on unversioned kubernetes API packages

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#50]
Change libraries that rely on unversioned API structs from kubernetes/kubernetes to use externally available versioned structs from kubernetes/api

**Comment by mengqiy** [comment]
Also see:https://github.com/kubernetes/kubernetes/issues/48564

**Comment by pwittrock** [comment]
Closing in favor of kubernetes/kubectl#83
