### ISSUE TITLE
kubectl set image does not work on initContainers

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubectl#503]
kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
kubectl set image deployment/abcxyz abcxyz="123"
Error from server (NotFound): deployments.extensions "abcxyz" not found
```

When a container by that name does exist - but it is defined in 'initContainers'.

**Comment by ahmetb** [comment]
> Error from server (NotFound): deployments.extensions "abcxyz" not found

points to the fact that abcxyz deployment doesn't exist. You should be getting an error:

> error: unable to find container named "foo"

but I'm guessing you're still right, `set image` probably doesn't support init containers.

**Comment by willmao** [comment]
same issue

**Comment by faghani** [comment]
same issue!

**Comment by kamushadenes** [comment]
:+1:

**Comment by ivakinpavel** [comment]
So is there any workaround to set image for init container?
I trying to run migrations with "fresh" image on init container.
Thanks for any help!
