### ISSUE TITLE
`get nodes -w` works differently to all other `get x -w`

### ISSUE THREAD

**Issue by mlda065** [kubernetes/kubectl#506]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* `get nodes`
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

I've tried two environments, with the same behaviour happening on both

* Azure Kubernetes Service
  * "basic networking"
  * no RBAC
  * disabled "HTTP Application Routing"
  * Australian region
  * v1.10.3
* Openstack, deployed with rancher
   * Rancher v2.0.4
   * Mirantis Openstack
   * Ubuntu 16.04
   * v1.10.3
   * I don't know the other details of this deployment. I'm just a user of Rancher and Openstack. Other people in my company manage them. I can go ask around for hardware etc if required, but since the same behaviour happens on Azure, I think it's not important.

**What happened**:

`kubectl get nodes -w` continually prints duplicates of previous lines. Even though the nodes are not changing state, every second or so a new line is printed. 

This is inconsistent. It is different behaviour to `kubectl get pods -w`, `kubectl get services -w`, `kubectl get deployments -w` etc.

```
$ k get nodes -w
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     7m        v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     7m        v1.10.3
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     7m        v1.10.3
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     7m        v1.10.3
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     8m        v1.10.3
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     8m        v1.10.3
```

**What you expected to happen**:

A list of nodes is printed. Nothing else is printed, except for nodes changing state or new nodes being added

```
$ k get nodes -w
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-23999449-0   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-1   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-2   Ready     agent     22h       v1.10.3
aks-agentpool-23999449-3   Ready     agent     7m        v1.10.3
```

and **nothing else** (unless I'm adding new nodes, or a node fails, gets upgraded etc)

**How to reproduce it** (as minimally and precisely as possible):

`kubectl get nodes -w`

**Anything else we need to know**:

I want to run `kubectl get nodes -w` and then add a new node. I expect to see the list of existing nodes, and then see the new node being privisioned. It's hard to see what's happening to the new node (if anything) because my stdout is flooded with redundant info about the old nodes which haven't changed at all.

**Comment by liggitt** [comment]
node objects do change every few seconds, as their status is updated by the kubelet (outputting in yaml format would reveal the changes)

/close
