### ISSUE TITLE
`kubectl config` seems to hash file names when --client-certificate is given a path

### ISSUE THREAD

**Issue by carlosonunez** [kubernetes/kubectl#507]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.10.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS `m3.medium`
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): `Linux ad33c053e9d5 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 Linux`
- **Install tools**: 
- **Others**:

**What happened**:

Trying to run `set-credentials` for a given cluster fails when I give `--client-certificate` a path that is not in the current working directory.

The resultant error looked like this:

```
error: error reading client-certificate data from /data/6a9444ae3eb1.pem: open /data/6a9444ae3eb1.pem: no such file or directory
```

when `--client-certificate` was set to `/data/ca.pem`.

I'm able to read the file correctly, and this does not occur when I set `--client-certificate` to `ca.pem`. However, the documentation suggests that I should be able to provide a path.

This does not happen with `set-cluster`.

**What you expected to happen**:

The command below should have returned 0:

```bash
kubectl config set-cluster carlosnunez.me-develop         --certificate-authority="/data/ca.pem"         --embed-certs=true         --server=https://34.235.65.81,:6443    --kubeconfig=hostname.kubeconfig &&   kubectl config set-credentials system:node:hostname       --client-certificate="/data/hostname,pem"             --client-key="/data/hostname-key.pem"      --embed-certs=true         --kubeconfig=hostname.kubeconfig &&  kubectl config set-context default         --cluster=carlosnunez.me-develop                --user=system:node:hostname             --kubeconfig=hostname.kubeconfig &&  kubectl config use-context default --kubeconfig=hostname.kubeconfig &&  mv hostname.kubeconfig /data
```

**How to reproduce it** (as minimally and precisely as possible):

1. Create worker and controller certificates per [these instructions](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md)
2. Run the command above.

**Anything else we need to know**:

I ran the above command in a Docker container. This happened while bootstrapping the cluster, so no cluster was available during the time at which this bug occurred.

**Comment by carlosonunez** [comment]
I am an idiot; that hash was my Docker container. Don't code while sleep deprived, kids!

**Comment by nikhita** [comment]
> Don't code while sleep deprived, kids!

:)
