### ISSUE TITLE
kubectl set resource/selector/subject -o yaml doesn't return the expected format

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubectl#51]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.1821+7c87bdd628715c-dirty", GitCommit:"7c87bdd628715c3a12a90267c689bdacaf99a069", GitTreeState:"dirty", BuildDate:"2017-08-14T02:21:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.1821+7c87bdd628715c-dirty", GitCommit:"7c87bdd628715c3a12a90267c689bdacaf99a069", GitTreeState:"dirty", BuildDate:"2017-08-14T02:21:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
```
# kubectl set subject rolebinding/admin --user=user1 --group=group1 -o yaml
rolebinding "admin" subjects updated
```

**What you expected to happen**:
```
# kubectl set subject rolebinding/admin --user=user1 --group=group1 -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2017-08-14T02:26:11Z
  name: admin
  namespace: default
  resourceVersion: "381"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/admin
  uid: f0238ea3-8097-11e7-ab4c-7427ea6f0fe3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foo1
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user1
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group1
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CaoShuFeng** [comment]
> \# kubectl set subject rolebinding/admin --user=user1 --group=group1 -o yaml
rolebinding "admin" subjects updated

In my cluster, when I run with -o yaml nothing is printed.

**Comment by apelisse** [comment]
Marking as enhancement since I don't think this has been thought through nor ever worked.

**Comment by mengqiy** [comment]
IMO kubectl should print the object that API server returned in yaml format when `-o yaml`.
