### ISSUE TITLE
Kubectl top nodes/pods background url

### ISSUE THREAD

**Issue by dj13may91** [kubernetes/kubectl#510]
I wanted to know how kubectl top nodes or kubectl top pods fetches the information as in what api does it hit. i couldn't find it in the kubernetes api docs : https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/
neither there is any function in the library : https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md

**Comment by dims** [comment]
run kubectl with `--v=10` and you can see all the HTTP requests being sent
