### ISSUE TITLE
Create ConfigMap from http source

### ISSUE THREAD

**Issue by cbluth** [kubernetes/kubectl#514]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `"from-file" "http"`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
`FEATURE REQUEST`

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
bare-metal, 3 masters, 6 worker nodes, kubespray
- **OS** (e.g. from /etc/os-release):
```
root@master1:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@master1:~# 
```
- **Kernel** (e.g. `uname -a`):
`Linux master1 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- **Install tools**:
- **Others**:

**What happened**:
```
cbluth@dl7490:~/x$ kubectl -n platform create configmap nets-config --from-file=https://raw.githubusercontent.com/pires/kubernetes-nats-cluster/master/nats.conf
error: error reading https://raw.githubusercontent.com/pires/kubernetes-nats-cluster/master/nats.conf: no such file or directory
cbluth@dl7490:~/x$
```

**What you expected to happen**: I thought this would work

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by prksu** [comment]
ping @kubernetes/sig-cli-feature-requests
