### ISSUE TITLE
kubectl not working properly : unable to upgrade connection: Unauthorized

### ISSUE THREAD

**Issue by JaroVojtek** [kubernetes/kubectl#518]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): client/server: v1.11.0

**Environment**:
- **Cloud provider or hardware configuration**:  On Premise
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
- **Kernel** (e.g. `uname -a`):
3.10.0-862.9.1.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:

I have generated my own certificates for kubernetes cluster and stored them in /etc/kubernetes/pki/ folder before kubernetes cluster initialization

Kubernetes cluster initialization went without problems and all kube-system pods are up and running.

However i am not able to perform some commands with kubeclt like 

```
kubectl logs weave-net-qfk8c -n kube-system -c "weave"
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log weave-net-qfk8c))

[root@qa053 kubernetes]# kubectl -n kube-system port-forward tiller-deploy-759cb9df9-rltzf 44134
error: error upgrading connection: unable to upgrade connection: Unauthorized

```

I have checked /etc/kubernetes/manifests/kube-apiserver.yaml file and I can see proper link to certificates
```
--client-ca-file=/etc/kubernetes/pki/ca.crt

--kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
--kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
```

**What you expected to happen**:
wokring normally as certificates are avilable in those paths

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by vishal49naik49** [comment]
@JaroVojtek - I am getting told error while running kubectl port-forward command.
I have generated my own certs. Can you please advise how you fixed your issue?

**Comment by vishal49naik49** [comment]
Thank you @JaroVojtek!!
I was able to fix this issue actually. The Kubelet client certificate supplied to the Kube-api service had Auth type as ‘server’. I changed it to ‘client’ and it worked like charm.
