### ISSUE TITLE
[Windows] kubectl run not accepting valid JSON as --override on Windows (same JSON works on Mac) 

### ISSUE THREAD

**Issue by psreed** [kubernetes/kubectl#519]
/kind bug

**What happened**:
- "kubectl run" with --overrides is rejected with "error: Invalid JSON Patch" on WINDOWS
- exact same command verified works fine on MacOS

**What you expected to happen**:
Patch applied to my kubectl run. See proper expected output from Mac OS run below.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run pfa --image=myimage --overrides='{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}' --dry-run -o yaml
```
**Anything else we need to know?**:
Output on Windows:
```
error: Invalid JSON Patch
```

Output on Windows (with -v6 added to the end of the command):
```
I0810 12:11:06.986876  135292 round_trippers.go:405] GET https://192.168.99.100:8443/apis/apps/v1beta1?timeout=32s 200 OK in 11 milliseconds
I0810 12:11:06.987852  135292 loader.go:359] Config loaded from file C:\Users\paul/.kube/config
F0810 12:11:06.992733  135292 helpers.go:119] error: Invalid JSON Patch
```

Output on MacOS:
```apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pfa
  name: pfa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: pfa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pfa
    spec:
      containers:
      - image: myimage
        imagePullPolicy: Always
        name: pfa
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Windows Version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Mac OS Version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
using minikube 0.28.2 with --vm-driver=virtualbox in both Windows and Mac OS cases.

- OS (e.g. from /etc/os-release):
Windows 10 & MacOS
- Kernel (e.g. `uname -a`):
Darwin <my_machine_name> 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

- Install tools:
minikube and kubernetes-cli installed using brew on MacOS, and using chocolatey on Windows.
- Others:

**Comment by vithati** [comment]
Using " instead of ' around --overrides input working for me in Windows. example:- kubectl run test --image=myimage --overrides="{\"apiVersion\":\"apps/v1beta1\",\"spec\":{\"template\":{\"spec\":{\"imagePullSecrets\":[{\"name\":\"myregkey\"}]}}}}" --dry-run -o yaml

**Comment by hashtoes** [comment]
FWIW replacing `'` with `"` technique didn't work for me.
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by woodwardmatt** [comment]
I'm sharing this having gone through the same battle yesterday with the kubectl run command. If you're running this on Windows using Powershell you'll need to create a variable and assign the JSON (using the ConvertTo-Json routine) first. Then use that variable in your kubectl commands.

From the OP's code:

`kubectl run pfa --image=myimage --overrides='{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}' --dry-run -o yaml`

Becomes:

```
$myjson = '{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}'
kubectl run pfa --image=myimage --overrides=$myjson --dry-run -o yaml
```

Hope that helps! :)

**Comment by vithati** [comment]
> FWIW replacing `'` with `"` technique didn't work for me.
> 
> ```
> $kubectl version
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
> ```

In my example I missed escaping " inside --overrides input.
```kubectl run test --image=myimage --overrides="{\"apiVersion\":\"apps/v1beta1\",\"spec\":{\"template\":{\"spec\":{\"imagePullSecrets\":[{\"name\":\"myregkey\"}]}}}}" --dry-run -o yaml```

'{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}' | ConvertTo-Json does samething. It gives same output ```"{\"apiVersion\":\"apps/v1beta1\",\"spec\":{\"template\":{\"spec\":{\"imagePullSecrets\":[{\"name\":\"myregkey\"}]}}}}"```

**Comment by hashtoes** [comment]
Thanks both. I followed @woodwardmatt 's way and it worked, with a couple of caveats:
1. $myjson cannot contain new line characters `\n`
1. $myjson cannot contain spaces in any of the value fields of JSON, for instance,
    ```
    '{ "name": "John_Smith" }' # <- works
    '{ "name": "John Smith" }' # <- doesn't work
   ```
Both of above results in `error: Invalid JSON Patch`, at least in my local environment.

**Comment by sguidos** [comment]
I still had this problem on kubectl v1.15.5; and escaping the inner double-quotes with a \ backslash did not work.  Very frustrating.  Just for the hell of it, I escaped each inner double-quote with the C# styled a triple-double-quote, and it worked!  Go figure, LOL

`--overrides '{ """apiVersion""": """v1""","""spec""":{"""ports""":[{"""port""":2830,"""protocol""":"""TCP""","""targetPort""":2830,"""nodePort""":30031}]}}'`

**Comment by oliverroer** [comment]
The solution suggested by @woodwardmatt works for me, however, I don't understand why converting a string of JSON to JSON is the solution here. 🤔

**Comment by eddiezane** [comment]
@oliverroer are you running into this with the latest version of kubectl (1.21.2)?

**Comment by t-l-k** [comment]
Triple double quotes per @sguidos comment is only thing which worked for me. Never would have guessed that.

```
pwsh 7.1.3
kubectl Client Version v1.20.4
Server Version v1.19.11
```

To avoid others suffering, I'll leave my more complete Powershell snippet here (starting of a remote interactive `pwsh` session). I composed it via hashtables to avoid any other syntax errors, and I've left the depth hint in as well as compress, as others may have more complicated overrides:

```
$overrides =  (@{ 
        "spec" = @{
            "imagePullSecrets" = @(@{"name" = $ImagePullSecretName})
        }
    } | convertto-json -depth 10 -Compress) -replace '"', '"""'
    
& kubectl run -i --tty my-pod --image=my-image --restart=Never --image-pull-policy="Always" --pod-running-timeout=10m --overrides=$overrides -- pwsh
```

**Comment by tcetco** [comment]
try with escaping double quotes sign like this
 --overrides="{\"spec\": { \"nodeSelector\": {\"pool\": \"win3\"}}}"

**Comment by gopihc** [comment]
> I'm sharing this having gone through the same battle yesterday with the kubectl run command. If you're running this on Windows using Powershell you'll need to create a variable and assign the JSON (using the ConvertTo-Json routine) first. Then use that variable in your kubectl commands.
> 
> From the OP's code:
> 
> `kubectl run pfa --image=myimage --overrides='{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}' --dry-run -o yaml`
> 
> Becomes:
> 
> ```
> $myjson = '{"apiVersion":"apps/v1beta1","spec":{"template":{"spec":{"imagePullSecrets":[{"name":"myregkey"}]}}}}' | ConvertTo-Json
> kubectl run pfa --image=myimage --overrides=$myjson --dry-run -o yaml
> ```
> 
> Hope that helps! :)
> 
> Approach originally found at: https://stackoverflow.com/a/53481499/40593

this worked for me..

**Comment by Kaiass** [comment]
For those who are struggling on Windows I can suggest the easier alternative to making a variable.

You need to escape each `"` sign, i.e. replace it with `\"`

For exampe I struggled with patching configmap for knative.
The desired command was
`kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}'`

It resulted in Bad Json.
The next command is working fine:
`kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{\"data\":{\"ingress-class\":\"kourier.ingress.networking.knative.dev\"}}'`
