### ISSUE TITLE
`kubectl run --expose` continues after error (missing parameter)

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubectl#52]
**Versions**:

```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.3005+04a648105961ce", GitCommit:"04a648105961cef6126cb6cbcc751b3548c572f1", GitTreeState:"clean", BuildDate:"2017-08-16T13:29:04Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-11T16:58:53Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl get nodes
NAME       STATUS    AGE       VERSION
minikube   Ready     26m       v1.7.3
```

**What happened**:

When using `--expose`, it's necessary to specify `--port` and kubectl correctly terminates with an error, but the deployment is still created.

```
$ kubectl run nginx --image=nginx --replicas=2 --expose
error: --port must be set when exposing a service

$ echo $?
1

$ kubectl get deploy
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     2         2         2            2           3s

$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-4217019353-4btgl   1/1       Running   0          6s
nginx-4217019353-ndk1d   1/1       Running   0          6s

$ kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   29m
```

**What you expected to happen**:
I expected the kubectl wouldn't proceed with the action and nothing would be created.

**How to reproduce it** (as minimally and precisely as possible):
Run `kubectl run nginx --image=nginx --replicas=2 --expose` without specifying a port.

**Anything else we need to know**:
Tested on kubectl compiled from source (2017-08-16) and minikube 0.21.0 with Kubernetes 1.7.3

**Comment by zjj2wry** [comment]
who can help closes this issue, i forget write ```closes xxx``` so that it keep open~

**Comment by zjj2wry** [comment]
@kargakis

**Comment by gtirloni** [comment]
@kargakis was this closed by accident?

**Comment by zjj2wry** [comment]
@gtirloni this issue has fixed. you can check this by use master kubectl. thanks

**Comment by kargakis** [comment]
> @kargakis was this closed by accident?

Fixed by https://github.com/kubernetes/kubernetes/pull/50834

**Comment by gtirloni** [comment]
Sorry, I got lost with all the messages here. Thanks for fixing this, much appreciated.

```
$ kubectl run nginx --image=nginx --replicas=2 --expose
error: --port must be set when exposing a service
See 'kubectl run -h' for help and examples.
```
