### ISSUE TITLE
Kubectl exec output is not binary clean

### ISSUE THREAD

**Issue by donbowman** [kubernetes/kubectl#521]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): binary

---

**Is this a BUG REPORT or FEATURE REQUEST?** BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: kube-spawn
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**What happened**:

```
$ kubectl exec -it POD sum /bin/bash
50572  1088

$ kubectl exec -it POD cat /bin/bash > /tmp/bash; sum /tmp/bash
34079  1092
```

**What you expected to happen**:

I expect that the output path of kubectl exec is binary clean.

**How to reproduce it** (as minimally and precisely as possible):

Run the kubectl exec commands above.

**Anything else we need to know**:

**Comment by apelisse** [comment]
I suspect the shell is going to interpret some characters differently if you're in interactive mode.

What are you trying to do? If you want to copy the file, you could use `kubectl cp` instead. If you want to use `kubectl exec` (maybe you're generating some output), use non-interactive mode: `kubectl exec -t POD cat /bin/bash > /tmp/bash; sum /tmp/bash` (note t Styling with Markdown is supported
he lack of `i`) does what you want.

Feel free to re-open if I mis-understood and there is indeed a bug.
