### ISSUE TITLE
kubectl get service doesn't work without -w

### ISSUE THREAD

**Issue by dnltsk** [kubernetes/kubectl#522]
`kubectl get service my-service -w` works fine and outputs

`my-service   LoadBalancer   10.0.xxx.xxx   104.46.xxx.xxx   3030:31053/TCP   37m`

The same command without `-w` or `--watch` outputs the following exception message

```
No resources found.
Error from server (NotAcceptable): unknown (get services my-service)
```

A similar exception message is also outputted when firing other commands like `kubectl get pods` or `kubectl get nodes`

The Kubernetes cluster is running on AKS. I'm using OSX High Sierra.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

How can I solve this?

**Comment by adohe** [comment]
@dnltsk I am afraid you need to make sure the client version match the service version, or at least within version scope.

**Comment by dnltsk** [comment]
your suggestion fixed my issue. Thanks.

after running `az aks install-cli --client-version v1.7.7` to sync the server and client version everything works perfectly fine.

**Comment by seans3** [comment]
I'm closing this.
