### ISSUE TITLE
Add --cascade or --force flag to kubectl delete namespace, for non-empty namespaces

### ISSUE THREAD

**Issue by johanot** [kubernetes/kubectl#525]
Today, if you drain a node, kubectl will prompt you for confirmation in the form of `--ignore-daemonsets` and `--delete-local-data` if applicable. This is fine and a nice guard for doing something dangerous.

Along the same lines, I would like some sort of `--force` or `--cascade` flag for deleting namespaces, in case the namespace contains objects. This would imply `kubectl get -n <namespace> all` before the actual delete is executed.

/kind feature
/sig cli

**What happened**:
My namespace and all objects within it was deleted without confirmation or questioning.

**What you expected to happen**:
A warning or bail out asking for a confirmation or a "I-know-what-I'm-doing-flag` before proceeding.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl delete ns <any-namespace>`

**Comment by rctl** [comment]
This looks like a nice feature to prevent accidental deletion of namespaces that have objects, I like this. I would like to take a look at implementing this.

**Comment by juanvallejo** [comment]
We expect the `kubectl delete` command to behave generically with any resource.
It would not make sense to special-case it to behave differently with a specific resource.

A solution that has been discussed in the past would consist of leveraging annotations on resources as a means of marking them "not safe to delete", similar to the work in https://github.com/kubernetes/kubernetes/pull/17740#issuecomment-160785800

An immediate workaround would involve using [admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks) to create this protection
