### ISSUE TITLE
unexpected error during validation: unable to resolve Kubernetes cluster API URL dns: lookup api.clust1.kube.devopsimran.com on 172.31.0.2:53: server misbehaving

### ISSUE THREAD

**Issue by imran21** [kubernetes/kubectl#526]
In Route53 the A record is not created. 
When I run
 ./kops validate cluster
Its getting error as below

 <unexpected error during validation: unable to resolve Kubernetes cluster API URL dns: lookup api.clust1.kube.devopsimran.com on 172.31.0.2:53: server misbehaving>
my nodes in EC2 is all creating fine and successfully but i cant to anything on ( ./kops validate cluster) and (kubectl)

Could anyone help me to solve this.

**Comment by ponnuru11** [comment]
In Git bash  
when I run
kops validate cluster
Its getting error as below

Error: validation failed: unexpected error during validation: unable to resolve Kubernetes cluster API URL dns: lookup api.k2.in on 172.31.0.2:53: no such host

Could anyone help me to solve this.
