### ISSUE TITLE
Need a real "get-all" command

### ISSUE THREAD

**Issue by schollii** [kubernetes/kubectl#527]
**FEATURE REQUEST**:

Add a get-all command that really shows *all* objects, with some flags to filter on certain types (namespaced vs non-namespaced, etc). 

Similarly, the dashboard should have a mode to show all resources (again, dashboard does not show networkpolicy objects, not even in pod descriptions to say "this pod is selected by this networkpolicy object". But dashboard improvement should be implemented separately, as the most important and urgent one is the kubectl new command. 

**Kubernetes version** (use `kubectl version`):

1.11.2

**What happened**:

`kubectl get all` only shows a small subset of kubernetes objects in a cluster, and there does not seem to be a command to get all objects (secrets, network policies, etc). This caused me hours of wasted time because I was trying to replicate a deployment object from another cluster into a new cluster, and didn't see that there was a networkpolicy needed for the service to expose that deployment. 

**What you expected to happen**:

That `kubect get all` would show all, not just a small number of types of resources. 

**How to reproduce it** (as minimally and precisely as possible):

Create a networkpolicy then do `kubectl get all`, it doesn't show up. However, it does show up with `kubectl get netpol` and `kubectl api-resources -o name   | xargs -t -n 1 kubectl get --ignore-not-found --show-kind | grep SOMETHING_IN_NAME`

**Comment by juanvallejo** [comment]
This functionality sounds like something that'd be great to implement as a plugin

**Comment by schollii** [comment]
Where would I start? I know some Go and I have lots of software dev experience so that part is not a problem, it's more the logistics : how do I mark that I'm working on this so people know, where do I publish it for peer review, for downloading, etc. I found https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/, are there other links that I should look at?

**Comment by juanvallejo** [comment]
@schollii 
> Where would I start?

I am currently updating the docs for plugins, so that they are up to date with the current plugin system: https://github.com/kubernetes/website/pull/10259, see https://github.com/kubernetes/website/blob/c20a616f572ada305d346c2a560271b2915874db/content/en/docs/tasks/extend-kubectl/kubectl-plugins.md (while that PR merges) for an accurate doc on the current state of plugins.

You can also take a look at https://github.com/kubernetes/sample-cli-plugin for a detailed example of writing a plugin in Go.

> how do I mark that I'm working on this so people know, where do I publish it for peer review, for downloading, etc

Although there's no official registry or repo where you would formally declare your work on a plugin (for now), you are always welcome to host it on a repo of your own, and link to it in the [slack channel for SIG-CLI](https://kubernetes.slack.com/messages/sig-cli), as well as request peer review there.

I'd be happy to help review it as well. Feel free to reach out on Slack with any questions.
Thanks

**Comment by juanvallejo** [comment]
@schollii plugin documentation has now been updated. You can find a guide for writing plugins under the new mechanism at: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#writing-kubectl-plugins

**Comment by corneliusweig** [comment]
@schollii Have a look at https://github.com/corneliusweig/ketall . It is also available via krew, so that it can be installed via `kubectl krew install get-all`. Please raise an issue, if this doesn't fully meet your requirements.

**Comment by rohantmp** [comment]
kubectl get $(kubectl api-resources| awk '{ print $1 }'|grep -v "NAME"|xargs|sed -e 's/ /,/g')

**Comment by alexkreidler** [comment]
I firmly believe that this functionality belongs in the core. It is unrealistic to say that you are displaying all kubernetes resources and it is misleading.

**Comment by foobarbecue** [comment]
This the weirdest, most confusing thing about learning k8s . If "all" doesn't mean "all," rename it "common" or "basic" something.

**Comment by nsvijay04b1** [comment]
please /reopen

**Comment by bendavis78** [comment]
Note that you can pass a comma-separated list of resource kinds to the `get` command:

    $ kubectl get deployments,services,ingresses -l app=myapp

You can use the following command (no xargs required) to get literally all resource types:

    $ kubectl get $(kubectl api-resources --verbs=list --namespaced -o name | paste -sd ',') -l app=myapp

**Comment by schollii** [comment]
Does anyone know how hard it would be to implement @bendavis78 idea in the kube source code? The API is already there, so that `kubectl get all -l app=myapp` should be very simple. I don't mind doing it I just don't know where to start.

**Comment by eddiezane** [comment]
I'm not sure the historical context on this one but we can reopen until we get an official word out.

/remove-lifecycle rotten
/remove-priority P3
/triage needs-information
/reopen

**Comment by eddiezane** [comment]
Following up..

`kubectl get all` is a legacy command and is actually implemented with a hardcoded server side list that is not easy to maintain. There is potential that it will be removed in the future and therefore will not be expanded upon or improved at this time.

We recommend using [ketall](https://github.com/corneliusweig/ketall) which can be installed standalone or via [krew](https://krew.sigs.k8s.io/).

/close

**Comment by foobarbecue** [comment]
Wow. You have to install extra stuff to do something this basic? Bizarre.

**Comment by schollii** [comment]
I was going to ask exactly that. I've outlined a solution, plus we could adapt code from ketall.

/reopen please

**Comment by akvadrako** [comment]
That plugin hasn't been updated in two years.

**Comment by guettli** [comment]
BTW, I wrote a small to dump all resources: https://github.com/guettli/dumpall
