### ISSUE TITLE
`kubectl describe pod/xxx` should show what resources selected the pod

### ISSUE THREAD

**Issue by schollii** [kubernetes/kubectl#528]
**FEATURE REQUEST**:

Add a flag or command that shows which objects have selected a specified pod, or for each pod, what objects selected it. For example, if I create a network policy with a selector, then each pod that matches this selector should show this in its description, something like this: 

Selected-by: 
   networkpolicy/name-of-policy
   service/name-of-service

Similarly, the dashboard should show that information. But dashboard improvement should be implemented separately, as the most important and urgent one is the kubectl extension. 

**Kubernetes version** (use `kubectl version`):

1.11.2

**What happened**:

`kubectl describe pod/name` does not show that there are networkpolicy that selected it, this caused hours of wasted time because I was trying to replicate a deployment object from another cluster into a new cluster, and didn't see that there was a networkpolicy needed for the service to expose that deployment's pods.

**Comment by prksu** [comment]
@seans3 do we still need this feature?

**Comment by schollii** [comment]
The feature as described would be nice but might be too complicated to implement. 

At the very least the NetworkPolicy "describe" should show which pods it has selected and what is enabled/disabled for each one. If this is not too difficult, I could give it a shot. 

Also the fact (IIUC - I have not tested that rigorously but that seems to be the case) that when a policy is in place in a namespace, every pod, even those not selected by any policy, defaults to not reachable. If a pod is not reachable, this should be visible in its describe output, and service should say if the pods it has selected are not reachable. Similarly, if this is not too difficult, I could give it a shot.
