### ISSUE TITLE
Long run of "kubectl run" does not refresh IAM token

### ISSUE THREAD

**Issue by adubkov** [kubernetes/kubectl#534]
**BUG REPORT**

**Kubernetes version** : v1.11.1

**Environment**:
- **Cloud provider or hardware configuration**: Kubernetes cluster on EKS, kubectl on Mac

**What happened**:

When I'm running container with `--stdin=true` on EKS cluster for 20-30min, container app complete  successful, but `kubectl` return an error:
```
$ time kubectl run --rm -i sleep --restart=Never --image=ubuntu:precise -- sleep 999
If you don't see a command prompt, try pressing enter.
pod "sleep" deleted
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))

real	16m41.928s
user	0m0.332s
sys	0m0.125s
```

It seems that `kubectl run` does internally call `get pods` and it doesn't refresh IAM token.

**What you expected to happen**:
Check creds exprication ttl and refresh them as needed.

**How to reproduce it** (as minimally and precisely as possible):

```
$ time kubectl run --rm -i sleep --restart=Never --image=ubuntu:precise -- sleep 999
```

**Comment by adubkov** [comment]
I'm using this workaround currently, to run jobs for long time and get logs from them:
```bash
kubectl run sleep --restart=Never --image=ubuntu:precise -- sleep 999

until [[ `kubectl get pod sleep -o json | jq -r '.status.phase'` =~ (Succeeded|Failed) ]]; do
  sleep 10
done

kubectl logs sleep

kubectl delete pod sleep
```

**Comment by pswica** [comment]
I'm not sure if I'd classify this as a bug. I think AWS has something specifically for re-authenticating kubeconfigs:

https://github.com/kubernetes-sigs/aws-iam-authenticator

**Comment by pswica** [comment]
@seans3 
Given that the issue is with AWS IAM (not kubectl), and given that AWS has a tool for this (see above), do you think we can close this issue?

**Comment by seans3** [comment]
Yes. I agree with @pswica. Closing this issue.

/close
