### ISSUE TITLE
Selector does not work for service.

### ISSUE THREAD

**Issue by J-Siu** [kubernetes/kubectl#535]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: VirtualBox
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux u64s01 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: apt

```sh
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
```

- **Others**:

**What happened**:

Selector does not work for service. 

**What you expected to happen**:

Selector should work for service.

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy ghost:

```
kubectl run ghost --image=ghost --port 2368 --expose=true
```

2. Verify service:

```
$ kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE       SELECTOR
ghost        NodePort    10.100.72.171   <none>        2368:30538/TCP   1d        run=ghost
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP          1d        <none>
```

3. Try with selector:

```
$ kubectl get svc -o wide -l run=ghost
No resources found.

$ kubectl delete svc -l run=ghost
No resources found
```

**Anything else we need to know**:

It work if I select k8s-app
```
$ kubectl get svc -o wide --all-namespaces
NAMESPACE     NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE       SELECTOR
default       ghost           NodePort    10.100.72.171   <none>        2368:30538/TCP   1d        run=ghost
default       kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP          1d        <none>
kube-system   kube-dns        ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP    1d        k8s-app=kube-dns
kube-system   tiller-deploy   ClusterIP   10.104.224.90   <none>        44134/TCP        9h        app=helm,name=tiller

$ kubectl get svc -o wide --all-namespaces -l k8s-app=kube-dns
NAMESPACE     NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE       SELECTOR
kube-system   kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   1d        k8s-app=kube-dns

$ kubectl get svc -o wide --all-namespaces -l run=ghost
No resources found.
```

**Comment by m1kola** [comment]
I can reproduce it. It's wired. When I add a new label to the service, I can select the service using this label:

```
kubectl label svc ghost app=something

kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE       SELECTOR
ghost        ClusterIP   10.100.76.186   <none>        2368/TCP   14m       run=ghost
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP    54d       <none>

kubectl get svc -o wide -l app=something
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE       SELECTOR
ghost     ClusterIP   10.100.76.186   <none>        2368/TCP   14m       run=ghost
```

but `run=ghost` still doesn't return any results

```
kubectl get svc -o wide -l run=ghost
No resources found.
```

I'll look, if I can find the cause and if it.

**Comment by J-Siu** [comment]
@m1kola

Arrrrr. I understand what you saying after I went through it a few times. As I am new to kubernetes and confusing between labels/selectors and also the -l option. But after some search and try with --show-labels, it becomes clear:

```txt
$ kubectl get svc -o wide --all-namespaces --show-labels
NAMESPACE     NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE       SELECTOR               LABELS
default       ghost           ClusterIP      10.97.101.35    <none>        2368/TCP         13d       run=ghost              <none>
default       hn              LoadBalancer   10.96.66.191    <pending>     8080:30673/TCP   12d       run=hn                 run=hn
default       kubernetes      ClusterIP      10.96.0.1       <none>        443/TCP          14d       <none>                 component=apiserver,provider=kubernetes
kube-system   kube-dns        ClusterIP      10.96.0.10      <none>        53/UDP,53/TCP    14d       k8s-app=kube-dns       k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS
kube-system   tiller-deploy   ClusterIP      10.104.224.90   <none>        44134/TCP        13d       app=helm,name=tiller   app=helm,name=tiller
```

Thank you!!
