### ISSUE TITLE
[Plugin] [1.12] plugin binaries are overshadowed by themselves if they appear in PATH twice

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#539]
**Kubernetes version** (use `kubectl version`): 1.12.0-beta.2

**What happened**:

I have added a directory that contains my plugins to my $PATH twice, like:

```
export PATH="$HOME/.krew/bin:$PATH:$HOME/.krew/bin"
```

then I ran `kubectl plugin list` only to find out the plugins are overshadowed by themselves, e.g.

```
[...]
/Users/ahmetb/.krew/bin/kubectl-open-svc
  - warning: /Users/ahmetb/.krew/bin/kubectl-open-svc is overshadowed by a similarly named plugin: /Users/ahmetb/.krew/bin/kubectl-open-svc
```
(not the paths are exact)

Also `kubectl open-svc` doesn't work because of this now.

**What you expected to happen**:

Deduplication of exact path names.

**How to reproduce it** (as minimally and precisely as possible):

1. Create an executable `kubectl-foo` in a dir
2. add that dir to $PATH twice
3. run `kubectl plugin list`.
4. Observe plugins are overshadowed by exactly themselves.

/cc @soltysh
^ apologies if this is not the correct person to cc.
/cc @lbb

**Comment by juanvallejo** [comment]
> Also kubectl open-svc doesn't work because of this now.

Please note that this is because the plugin executable needs to include an underscore, and not due to a warning under `kubectl plugin list`, per our discussion in https://github.com/kubernetes/kubectl/issues/540#issuecomment-424553028, otherwise, `kubectl-open-svc` is split into subcommands: `kubectl open svc`
