### ISSUE TITLE
[1.12] plugin commands with dashes cannot be invoked with their original names

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#540]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT
**Kubernetes version** (use `kubectl version`): 1.12.0-beta.2

**What happened**:

There are already plugins named with dashes (`-`) in the plugin name, such as:
- `open-svc`
- `ca-cert`
- `rm-standalone-pods`

in the [krew package manager](https://github.com/GoogleContainerTools/krew-index/tree/4bcf63c95a3f42a37fbaca1d735f2efb981d4d65/plugins). There are also many plugins **outside** krew, such as:

- [decode-secret](https://github.com/brosandilabs/kubectl-decode-secret)
- [rbac-lookup](https://github.com/reactiveops/rbac-lookup)
- ...

kubectl 1.12 splits the names of these plugins into separate subcommands, such as:

| previously called | now called as |
|--|--|
| `kubectl plugin open-svc` | `kubectl open svc [...]` |
| `kubectl plugin rm-standalone-pod` | `kubectl rm standalone pod [...]` |

**What you expected to happen**:

This new behavior is quite unexpected for me. This makes it:

1. impossible to write plugins with dashes in the name

     For example, if I write a plugin named `port-forward-better`, my users have to invoke it as `kubectl port forward better` (not desirable) as opposed to `kubectl port-forward-better`.

1. Undesired categorization of plugins that share the same prefix:

     For example, if I'm writing a plugin named `rm-standalone-pods` installing a plugin with another `rm-` prefix (such as `rm-completed-jobs`). They will be (someday) grouped under `kubectl rm` despite they're different plugins.

**I Expected:** if a plugin named `kubectl-delete-all` exists, I should be able to call it `kubectl delete-all`. Being able to call it as `kubectl delete all` _may_ still be ok as the artifact of the feature, but it should not prevent `kubectl delete-all` invocation.

I am sorry I wasn't there to review the design but I think design won't work for the broader plugin ecosystem.

/cc @soltysh 
/cc @lbb

**Comment by ahmetb** [comment]
@juanvallejo That sounds like good news! It's not a great hack but it seems like it can do the trick. I'll close this once I verify.

**Comment by juanvallejo** [comment]
@ahmetb 
> That sounds like good news! It's not a great hack but it seems like it can do the trick. I'll close this once I verify.

Thanks. To clarify, this does not prevent underscores from being used as part of a command's name, rather it means that plugin commands with underscores can be invoked either with an underscore or a dash:

```
$ kubectl dash-test
I am a plugin with a dash in my name
```

```
$ kubectl dash_test
I am a plugin with a dash in my name
```

**Comment by ahmetb** [comment]
@juanvallejo Yes, I see now. I think this gives us enough to refactor existing krew plugins to work. Thanks.
