### ISSUE TITLE
Can't access successfully created context

### ISSUE THREAD

**Issue by tech509201941** [kubernetes/kubectl#544]
I want to create a kubectl context within my docker container.
This fails, although kubectl responds that "Context "kubernetes-admin" created.":

```
$ kubectl config --kubeconfig=SenecaMeshBase/kubernetes/access/config set-context kubernetes-admin
Context "kubernetes-admin" created.
$ kubectl config get-contexts
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE
$ kubectl config use-context kubernetes-admin
error: no context exists with the name: "kubernetes-admin".
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

How can this be the case?
Thanks a lot :)

**Comment by Freyert** [comment]
@tech509201941 I've figured it out :P 

Remove the `=` from `--kubeconfig=`

**Comment by moudidx** [comment]
make sure that kubernetes has a kubeconfig configured. i had the same error, it was resolved when i added this line to my bashrc file: export  KUBECONFIG=$KUBECONFIG:~/.kube/config
