### ISSUE TITLE
kubectl get pod -n default  -l " "  output behaviour 

### ISSUE THREAD

**Issue by hebbarsushma** [kubernetes/kubectl#545]
FEATURE REQUEST
*Kubernetes version** (use `kubectl version`):all

**What happened**:
>kubectl get pod -n default -l  " "    
Above command lists all the pod present in default namespace

**What you expected to happen**:
Since -l " " does not match with any of the pod  label  command  should produce  output as
>No resources found . 

Can anyone explain this behaviour.

**Comment by juanvallejo** [comment]
An empty `-l` or `--selector` value is meant to be a no-op. https://github.com/kubernetes/cli-runtime/blob/7915b4409361b23932e7af013a2ec31d5753e001/pkg/genericclioptions/resource/builder.go#L398

This is not a bug.

/close
