### ISSUE TITLE
rsync behavior to copy files from pod to pod, perhaps for `kubectl cp`

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubectl#551]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

/sig cli
/area kubectl
/kind feature

Right now looks like `kubectl cp` only allows copying local/remote and remote/local. This works for most cases by what if somebody wants to sync files from pod to pod

It would be nice to have something like this:

`kubectl cp <namespace1>/<pod1>:/tmp/foo.txt <namespace2>/<pod1>:/tmp/foo.txt`

This would probably also require a change in the `kube-apiserver`.

**Kubernetes version** (use `kubectl version`):

```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Any
- **OS** (e.g. from /etc/os-release): Any
- **Kernel** (e.g. `uname -a`): Any
- **Install tools**: kubectl
- **Others**: N/A

**What happened**:

`kubectl cp` supports local/remote or remote/local

**What you expected to happen**:

Support remote/remote

**How to reproduce it** (as minimally and precisely as possible):

Run any `kubectl cp` command.

**Anything else we need to know**:

Some background [info](https://stackoverflow.com/questions/53070742/how-to-copy-files-from-pod-in-one-namespace-to-pod-in-another-namespace)

**Comment by gajus** [comment]
Note that there is a community product ksync, https://github.com/vapor-ware/ksync.

**Comment by bhack** [comment]
@gajus ksync doesn't not support volumes/cri-o https://github.com/vapor-ware/ksync/issues/251 https://github.com/vapor-ware/ksync/issues/265 https://github.com/vapor-ware/ksync/issues/274.
 
Check instead https://github.com/ernoaapa/kubectl-warp

**Comment by bhack** [comment]
Please don't stale

**Comment by soltysh** [comment]
The state and history of decision behind `kubectl cp` can be bound in https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190920-future-of-kubectl-cp.md. Also, other pointed at other solutions. With that I'm going to close this issue, since I don't think we'll be addressing it.
/close

**Comment by paleozogt** [comment]
The link to https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190920-future-of-kubectl-cp.md is broken. :(

**Comment by eddiezane** [comment]
@paleozogt looks like the structure has since changed.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2381-future-of-kubectl-cp
