### ISSUE TITLE
Support for waiting on multiple deployments to complete and also support for timeouts

### ISSUE THREAD

**Issue by wknapik** [kubernetes/kubectl#554]
**Is this a request for help?**
No.

**What keywords did you search in Kubernetes issues before filing this one?**
rollout status

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
N/A

**Environment**:
- **Cloud provider or hardware configuration**:
N/A
- **OS** (e.g. from /etc/os-release):
N/A
- **Kernel** (e.g. `uname -a`):
N/A
- **Install tools**:
N/A
- **Others**:
N/A

**What happened**:
```
% kubectl rollout status -w deployment/{foo,bar}
error: rollout status is only supported on individual resources and resource collections - 2 resources were found
%
```
```
% kubectl rollout status --help|grep -ci timeout
0
%
```
 
**What you expected to happen**:
I expected kubectl to wait until both deployments were complete and I also expected to be able to set a timeout.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl rollout status -w deployment/{foo,bar}`
`kubectl rollout status --help|grep -ci timeout`

**Anything else we need to know**:
No.

**Comment by wknapik** [comment]
Yeah, so do I, but if you need to wait for several deployments, it becomes more complicated - https://gist.github.com/wknapik/315f52a20a2af43da35be5412625794a. I don't think this should require that much coding.

**Comment by soltysh** [comment]
I'd suggest checking `kubectl wait` since that'd be a better fit for multiple wait condition. If it doesn't support it would be a nice addition there. I don't think we will support multiple deployments in `kubectl rollout status`.
/close
