### ISSUE TITLE
kustomize follow ups

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#570]
- Make resource builder call a library that has options instead of the `builder.NewCmdBuild`
- Throw an error if the directory contains kustomization files **by checking the GVK**
- Check if the target is a kuztomization file by GVK, not filename

**Comment by monopole** [comment]
Jingfang is working on bullet 1 as a distinct issue.

The other 2 bullets need more discussion.

We currently [require](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/kustomization.go#L168) the kustomization file to have a GVK with Kind==Kustomization.

However, we don’t use that as a signal for which files to read.

We’ve had over 260 issues in kustomize - bugs and feature requests - none have complained about the Well-Known File approach.

In the context of kubectl/kustomize, the Well-Known File implies that the atomic unit of your configuration is a directory, and your overlays, if you have them, are directories too, and you are disallowed from mixing two different configurations in one directory.  In each directory, it’s obvious where to look for the file that defines the config.  A base is specified as a directory or git repo URL, and one is not required to read every file in the target to find the kustomization that defines it.

The documentation and examples reflect this structure.  We don’t have examples where one would, say, put multiple (different) overlays and their base in one directory, and thus have _no idea_, short of reading all files and mapping it all out, how to think about the configuration provided.  In such a situation, you wouldn’t even know what command to run - which file to read as the ‘top’ overlay. 

Anyway, i don't have the context for this.  What problem are we solving and is it worth all the file scanning, and new class of error, longer specification of a base, and new sources of confusion?

**Comment by Liujingfang1** [comment]
I put some effort into modifying the code (both in cli-runtime and kustomize) to check if the `-f` target is a Kustomization file by GVK. Based on my observations, this approach creates more problems than it solves. 

The files specified by `-f` need to be read twice. The first time is to determine if it is a kustomization file, the second time is to load its content to build resources. As @liggitt pointed out, this will break the use case of `kubectl apply -f <(command to get content)`.

The above point is for the top level kustomization file. When it comes bases used by the top level kustomization, things become worse. The base is specified as a relative path to a directory. If we don't use the default name `kustomization.yaml`, we have to look up every file in this directory to find the one with the Kustomization GVK. Assume the resource files are in the same base directory, we will end up with reading all the files twice.

**Comment by liggitt** [comment]
> We currently require the kustomization file to have a GVK with Kind==Kustomization.

https://github.com/kubernetes-sigs/kustomize/blob/a5c6938c6591c7311ddd42e7d5b79868cb8117d5/pkg/types/kustomization.go#L168-L181

That check needs to be strengthened to require both the version and kind fields before delivering this in kubectl. Assuming a missing version or kind means it is a version we understand means that a typo or mis-indented version lets us process a file that is definitely not the right version.

https://github.com/kubernetes-sigs/kustomize/blob/a5c6938c6591c7311ddd42e7d5b79868cb8117d5/pkg/types/kustomization.go#L25

The apiVersion without an api group is also unexpected... is there a reason this wasn't scoped to kubectl or kustomize or a *.k8s.io API group?

> We’ve had over 260 issues in kustomize - bugs and feature requests - none have complained about the Well-Known File approach."

it's not surprising the kustomize tool pins to a well-known file specific to kustomize. It is much more surprising for kubectl to do that, especially as an addition to current behavior

> In the context of kubectl/kustomize, the Well-Known File implies that the atomic unit of your configuration is a directory, and your overlays, if you have them, are directories too, and you are disallowed from mixing two different configurations in one directory.

That can make sense in the context of kustomize, which reasonably has a singular view of the world. I think that is a less reasonable statement to make about kubectl, which has multiple ways it can process files/directories.

**Comment by liggitt** [comment]
> I put some effort into modifying the code (both in cli-runtime and kustomize) to check if the `-f` target is a Kustomization file by GVK. Based on my observations, this approach creates more problems than it solves.

My primary concern is the guarantees around what the user types into kubectl (the `-f ...` parameter value). Once the handler has determined it is processing a kustomize file and delegates handling of the file's content to the kustomize library, I have no objection to the kustomize handler pinning to well-known files in referenced base directories.

**Comment by monopole** [comment]
Plan B:

We allow the file name `kustomization.yaml` to remain useful/special in the kustomize code path (in kubectl), but not treat it as special on _the kubectl command line_.

Specifically:

```
kubectl apply -f dirA/dirB/filename.yaml
```
should

 1. open `filename.yaml`
 2. if it's got Kind==Kustomization, trigger the kustomize code path, else do legacy path.

Nothing else changes.  i.e., the command
```
kubectl apply -f dirA/dirB
```
does what it always did, and doesn't scan files for `kind==Kustomization`, doesn't care if a file in `dirB` is called `kustomization.yaml`, and doesn't execute, for lack of a better word, kustomization code.

The only way to trigger a kustomization is to specify a kustomization file (kind==Kustomization) as argument, and the file name doesn't matter (though sane people will call it kustomization.yaml).

Once in kustomize code, nothing else changes, in particular, people are still expected to have one config per dir, bases need no specification beyond directory name, and we demand (i.e. _reserve_) use of the kustomization.yaml file name.

@liggitt make sense?

**Comment by monopole** [comment]
BTW, the legacy code path will look at kustomization.yaml files in the `...` case and presumably throw up its hands and ignore them like it would any unrecognized Kind.

**Comment by liggitt** [comment]
> Specifically:
> 
> ```
> kubectl apply -f dirA/dirB/filename.yaml
> ```
> should
> 
> 1. open `filename.yaml`
> 2. if it's got Kind==Kustomization, trigger the kustomize code path, else do legacy path.
> 
> Nothing else changes. i.e., the command
> 
> ```
> kubectl apply -f dirA/dirB
> ```
> does what it always did, and doesn't scan files for `kind==Kustomization`, doesn't care if a file in `dirB` is called `kustomization.yaml`, and doesn't execute, for lack of a better word, kustomization code.

yes, that sounds more reasonable to me.


> The files specified by -f need to be read twice. The first time is to determine if it is a kustomization file, the second time is to load its content to build resources. As @liggitt pointed out, this will break the use case of kubectl apply -f <(command to get content).

Looking at where the kustomization visitor was added in kubectl, I think the problems stem from where it was added. I think it would make more sense and be less disruptive here:

```go
// Visit in a FileVisitor is just taking care of opening/closing files
func (v *FileVisitor) Visit(fn VisitorFunc) error {
	...
	// TODO: add an intermediate visitor that intercepts the content coming from the stream visitor and routes resource.Info objects with kustomization content to the kustomization handler for expansion, along with the containing directory, which we can pull from v.Path
	return v.StreamVisitor.Visit(fn)
}
```

**Comment by Liujingfang1** [comment]
> > The files specified by -f need to be read twice. The first time is to determine if it is a kustomization file, the second time is to load its content to build resources. As @liggitt pointed out, this will break the use case of kubectl apply -f <(command to get content).

> Looking at where the kustomization visitor was added in kubectl, I think the problems stem from where it was added. I think it would make more sense and be less disruptive to the file input streaming here:
> ```
> // Visit in a FileVisitor is just taking care of opening/closing files
> func (v *FileVisitor) Visit(fn VisitorFunc) error {
>	...
>	// TODO: add an intermediate visitor that intercepts the content coming from the stream visitor and routes resource.Info objects with kustomization > content to the kustomization handler for expansion, along with the containing directory, which we can pull from v.Path
>	return v.StreamVisitor.Visit(fn)
> }
> ```
This looks good to me. Thank you for your suggestion @liggitt.

**Comment by monopole** [comment]
@liggitt , your copy/paste omitted my paragraph about what happens once in kustomization code, and the comment about the file name `kustomization.yaml` still being special and reserved for this purpose.  

Still objecting?

**Comment by liggitt** [comment]
> @liggitt , your copy/paste omitted my paragraph about what happens once in kustomization code, and the comment about the file name `kustomization.yaml` still being special and reserved for this purpose.
> 
> Still objecting?

nope, edited to include those post-post

**Comment by monopole** [comment]
yay.  thanks for your help and comments.  

i don't care which api group (since this isn't api), so hoping someone with more clarity on it can pick one for us.

**Comment by monopole** [comment]
i was specifically considering a _mix_.

If it works right (some kustomized, some not - all merged in the end) for free, i don't mind, but want to be conscious of it.

**Comment by monopole** [comment]
> That would also mean if you pointed kubectl at a dir of files, one containing kustomize content would get expanded in place as it was visited, which also seems like a reasonable outcome.

It's impossible to be too clear here.

We still agree that _the command line_ is the dispatch point.  If a full file path is specified, and if that file has kind==Kustomize, then we kustomize, else no.

So the only way to get a mix of kustomized trees and non-kustomized trees is by using multiple `-f` args, and i just wanted to call out the result explicitly.

I want to disallow dispatching deeper in the tree (perhaps in multiple locations) based on content, because I think it would be too surprising, too clever.

**Comment by liggitt** [comment]
> We still agree that the command line is the dispatch point. If a full file path is specified, and if that file has kind==Kustomize, then we kustomize, else no.

The current contract of -f pointed at a file is "process this file". In 1.13, processing a kustomize file errors. Teaching kubectl to process a kustomize file by expanding it is a coherent behavior. 

The current contract of -f pointed at stdin is "behave as if -f was pointed at a file containing everything read from stdin". If kubectl -f can handle kustomize content, then it would make sense for the stdin handling to as well, as it is encountered. 

The current contract of -f pointed at a directory is "behave as if -f was specified for each json and yaml file in the directory". If kubectl -f can handle kustomize content, then it would make sense for the directory scan to as well, as it is encountered. 

In fact, if kustomize content handling was integrated in the filevisitor as suggested in 
https://github.com/kubernetes/kubectl/issues/570#issuecomment-452485993, it would inherit that capability automatically… you'd have to work against the visitor to exempt that case.

I think treating content as consistently as possible, no matter the source, is important to be able to reason about how kubectl behaves.

**Comment by monopole** [comment]
I understand and agree with your concerns.

Consider this file layout:
```
foo/
  a.yaml
  b.yaml
  kustomization.yaml
```
where `kustomization.yaml` contains
```
nameprefix: foo
resources:
- b.yaml
``` 
The output of
```
kustomize build foo
```
is one resource, named `foo-b`.

The output (to the cluster) of 
```
kubectl apply -f foo
```
depends on visitor dispatch.  If we dispatch from the existing visitor (dispatch kustomize code upon encountering the kustomization Kind), then the output will be three resources, `a`, `b` and `foo-b`.  

Kubectl has a visitor, Kustomize has a visitor.  A third or fourth approach could introduce their own visitors too.  This is different from new objects that accept a visitor - it's new rules about how to do visitation (hence contract change).

anyhoo, yeah, we're converging.

**Comment by bgrant0607** [comment]
Quick comment regarding kustomization.yaml: I view that file as component config file, similar to kubeconfig, rather than as a resource file. Kubeconfig is also read from an implicit location by default. I'm not sure what happens if it's an implicit target of a `-f .`.

(Do we document the kubeconfig schema anywhere?)
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config

I agree more error checking is needed.

As with .kube/config, we could rename it (e.g., `Kustomization`) so that it's not accidentally snagged by the default `*.yaml *.json` globs.

**Comment by liggitt** [comment]
Agreed. The more we discussed the behavior, the less it seemed to make sense to have this treated as a resource file, which points to an alternate entry point than `-f ...`

**Comment by bgrant0607** [comment]
If we think it would be less ambiguous and less surprising (and potentially less vulnerable to mischief) to make invoking kustomize explicit, a new flag (e.g., `--kustomize <file | directory>`) seems fine.

**Comment by Liujingfang1** [comment]
+1 on `--kustomize `

**Comment by monopole** [comment]
Well, we agree it's a UX question anyway - not on how to resolve it.

Why not allow `-f` to do different things based on the _command line argument_?

Like `ls` does (for example).

Then `-f` becomes an extension point for things that generate resources.

If overloading -f is disallowed, then we have to introduce new flags for new resource generators.  Yuck.

**Comment by monopole** [comment]
If we disallow overloading `-f`,then i'd rather just go the route of a distinct command, with usage
```
kubectl kustomize foo | kubectl apply -f -
kubectl kustomize foo | kubectl delete -f -
...
```
 * less to explain
 * allows other things in the pipe
 * can use Well-Known file name without debate
 * future compatible - we can still overload `-f` later if more people than i want it

And yes it could be a plugin, if we had automatic plugin downloading done and matured.

But - last pitch - a main reason we started this (per DAM bible) was to encourage best practices in declarative resource management.  Since `-f` is the "resource generator", putting it there drops the barrier to usage / best practices about as far as we can lower it.

**Comment by liggitt** [comment]
> If we disallow overloading `-f`,then i'd rather just go the route of a distinct command, with usage
> 
> ```
> kubectl kustomize foo | kubectl apply -f -
> kubectl kustomize foo | kubectl delete -f -
> ...
> ```
> * less to explain
> * allows other things in the pipe
> * can use Well-Known file name without debate
> * future compatible - we can still overload `-f` later if more people than i want it

that sounds good to me, at least as step 1, for all of those reasons

**Comment by bgrant0607** [comment]
I am not sure we want to add more preprocessors or make it pluggable. Previous discussions:
https://github.com/kubernetes/kubernetes/issues/13241
https://github.com/kubernetes/kubernetes/pull/14993
https://github.com/kubernetes/kubernetes/pull/14918

I'm fine with starting as a subcommand.

**Comment by bgrant0607** [comment]
The subcommand UX should still be made as consistent with other kubectl commands as possible

**Comment by smarterclayton** [comment]
I in general agree (have been following along and talking with Jordan) about the separate subcommand.  The issues raised about partially interacting with the resource.builder were concerning to me and the simpler approach is still advantageous.
