### ISSUE TITLE
better apply --prune

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes/kubectl#572]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

While `kubectl apply` is widely used in different workflows, users need `kubectl apply --prune` to sync the resources on cluster with configuration saved in files, directories or repos. 

Currently `kubectl apply --prune` is still in Alpha. It prunes objects by matching labels. Users must be really careful when they use this command so that they don't delete objects unintentionally. There are a list of issues with current pruning behavior: https://github.com/kubernetes/kubernetes/issues/69879, https://github.com/kubernetes/kubernetes/issues/68400, https://github.com/kubernetes/kubernetes/issues/66430, https://github.com/kubernetes/kubernetes/issues/40635, https://github.com/kubernetes/kubectl/issues/555

We need better `kubectl apply --prune` so that it will meet the users' requirement of syncing resources and get rid of current issues.

**Comment by Liujingfang1** [comment]
@pwittrock

**Comment by crimsonfaith91** [comment]
@Liujingfang1 
We definitely have to make `kubectl apply --prune` better. Alternatively, as @seans3 pointed out during by-person sync, we should also support dry-run of the command too.

Perhaps we can make `kubectl apply --prune` a 2-step command? The first step is to show all resource changes (dry-run), and second step is for users to input y/n (performing real changes).

**Comment by rdxmb** [comment]
> and the second step is for users to input y/n (performing real changes).
This is good for starting with prune. However, for running `--prune` in CI there has to be a way to run it non-interactively.

**Comment by lentus** [comment]
I am currently working with a company to move their infrastructure to a kubernetes environment, and we are currently trying to solve the issue that certain resources (such as ingress) are not deleted when just `apply`ing the new version of a yml file. Prune seems to be exactly what we need, but we are hesitant to implement it in our CI/CD pipeline since prune is still in alpha. 

This issue is still very relevant, we could really use this!

**Comment by m1o1** [comment]
We're considering options like Tanka for jsonnet based deployments, but haven't found anything like helm in terms of "packaging" a release in kubernetes. Pruning seems to be the only option to apply these manifests as a single package that deletes resources that are no longer in the manifest files. Looking forward to this feature becoming stable

**Comment by ivan4th** [comment]
@m1o1 I didn't try Tanka yet, but [qbec](https://qbec.io) does its own pruning quite well

**Comment by jwurm** [comment]
It woud also be great to have --prune work with custom resources, instead of just native kubernetes ones.

I don't know for sure about 1.19 right now (using 1.16 at work), but there it seems to ignore e.g. Istio objects despite being labeled.

**Comment by rdxmb** [comment]
Are there any plans working on `prune` ?

**Comment by rdxmb** [comment]
A great enhancement would be to prune within the namespace, when running

`kubectl apply --namespace --prune` 

This is not the case when I remember right.

**Comment by jicki** [comment]
Are there any plans working on prune ?
