### ISSUE TITLE
Regression: [Plugin] [1.12] plugin binaries are overshadowed by themselves if they appear in PATH twice

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#575]
Issue https://github.com/kubernetes/kubectl/issues/539 has started to repeat itself in kubectl 1.13.1:

I get this error 
```
$ kubectl plugin list
/Users/ahmetb/.krew/bin/kubectl-krew
  - warning: /Users/ahmetb/.krew/bin/kubectl-krew is overshadowed by a similarly named plugin: /Users/ahmetb/.krew/bin/kubectl-krew
```

when I duplicate dirs in my $PATH by doing `export PATH="$PATH:$PATH"`.

/kind bug
/priority P1
/cc @juanvallejo

**Comment by juanvallejo** [comment]
Wait, why are you adding duplicate dirs in your PATH? :)

**Comment by ahmetb** [comment]
> Wait, why are you adding duplicate dirs in your PATH? :)

That shouldn't matter. It's not illegal. :) But my zshrc file does `PATH=stuff1:stuff2:$PATH`, so when I start a shell inside another shell it inherits its PATH.

**Comment by juanvallejo** [comment]
Fix + test to avoid future regression: https://github.com/kubernetes/kubernetes/pull/73144
