### ISSUE TITLE
Unable to to access k8s in aws eks

### ISSUE THREAD

**Issue by kuengnee** [kubernetes/kubectl#578]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

Yes but unable to find the relevance troubleshooting guide

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

EKS AWS
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

v1.13.2"

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): macOS Mojave 10.14.2 (18C54)
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
- **Install tools**: kubectl aws-iam-authenticator brew
- **Others**:

**What happened**:

When configuration is done using aws eks update-kubeconfig --name=clustername follow by
"kubectl get all"

It show the below message
error: the server doesn't have a resource type "all"

**What you expected to happen**:

list of pods and services

**How to reproduce it** (as minimally and precisely as possible):
Install aws-iam-authenticator using brew
Install kubectl using brew
aws eks update-kubeconfig --name=clustername
kubectl get all

**Anything else we need to know**:

**Comment by shyamjvs** [comment]
@kuengnee This seems like kubectl issue. Are you:

- sure that `get all` is a supported command?
- is your kubectl version compatible with that command?

**Comment by shyamjvs** [comment]
Assigning SIG properly...
/remove-sig aws
/sig cli
