### ISSUE TITLE
Verify that kubectl can parse openapi

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#58]
Since https://github.com/kubernetes/kube-openapi/pull/10 is moving parsing code for `openapi` from the main repo to https://github.com/kubernetes/kube-openapi/, we need to verify that the full swagger openapi file can still be parsed.

This is just a reminder that we need to do that.
In other word, we need to add a test in the main repo that verifies that the parsing code can parse the openapi swagger.

**Comment by seans3** [comment]
@apelisse Have we accomplished this? Can I close this?

**Comment by apelisse** [comment]
I'd keep it open for now.

**Comment by seans3** [comment]
Moved this issue to the kube-openapi repo: https://github.com/kubernetes/kube-openapi/issues/103.

Closing here.
