### ISSUE TITLE
go-template should accept stdin

### ISSUE THREAD

**Issue by jamielennox** [kubernetes/kubectl#581]
I just found out about --output=go-template and want to use it within a script to read some secrets and set them into local environment variables. I'm essentially using a kube secret as a place to communicate values between multiple processes. I was expecting to basically be able to do: 

```
kubectl get secret --namespace "$NAMESPACE" mysecret -o go-template=- << EOF > ./test-output
export DB_USER={{ .data.dbuser | b64decode }}
...
EOF
source ./test-output
```

What i end up with in my `./test-output` is `-`. I haven't gone through the code yet, but I haven't found any obvious way to use a go-template from stdin. 

I can accomplish this in other ways, but this would be good to have as well.

`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by jamielennox** [comment]
Oh, also using `-o go-template-file=-` gives 
```
error: error reading --template -, open -: no such file or directory
```
However, given that there is a file interface we can use a workaround at the moment with 
```
kubectl get secret mysecret -o go-template-file=/dev/stdin
```
but it would always be nice to have a real command there.

**Comment by jamielennox** [comment]
just in case someone stumbles across this looking for the same thing, my current solution is basically: 
```
#!/bin/bash 

source <(
kubectl get secret mysecret -o go-template-file=/dev/stdin << EOF
export DB_USER="{{ .data.dbuser | base64decode }}"
export DB_PASSWORD="{{ .data.dbpassword | base64decode }}"
EOF
)

echo "USER IS $DB_USER"
```
I'm sure there are ways to make that a bit prettier but we're past pretty at the point we need this.

**Comment by jamielennox** [comment]
/remove-lifecycle stale

I think this is an easy addition and an easy first timers issue. Going to refresh in the hopes of just an acknowledgement.

**Comment by shiywang** [comment]
I'll take a look
