### ISSUE TITLE
Support bash-like parameter expansion

### ISSUE THREAD

**Issue by ncouture** [kubernetes/kubectl#583]
For instance, it would be nice to be able to execute:
```
kubectl apply -f nginx-{dep,svc}.yaml
```

or

```
kubectl apply -f nginx-*.yaml
```

instead of having to execute:
```
kubectl apply -f nginx-dep.yaml
kubectl apply -f nginx-svc.yaml
```

**Comment by ncouture** [comment]
Title should probably read "support multiple files as argument to `kubectl apply -f`"

**Comment by superbrothers** [comment]
You can use multiple files as arguments even now:

```
kubectl apply -f nginx-dep.yaml -f nginx-svc.yaml
```
