### ISSUE TITLE
Completion for kubectl plugins

### ISSUE THREAD

**Issue by weibeld** [kubernetes/kubectl#585]
**FEATURE REQUEST**

**Kubernetes version** (use `kubectl version`): 1.13

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): macOS 10.14
- **Kernel** (e.g. `uname -a`): `Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64`

**What happened**:

Having installed a kubectl [plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) `kubectl-test`:

~~~bash
$ kubectl t[tab][tab]
taint top
~~~

You can't complete plugin commands as you can complete built-in commands. 

**What you expected to happen**:

~~~bash
$ kubectl t[tab][tab]
taint test top
~~~

~~~bash
$ kubectl te[tab]  # Completes to 'kubectl test'
~~~

**Anything else we need to know**:

Completion for plugin names could be implemented in the kubectl completion script. But completion for arguments of plugins are plugin-dependent and can't be implemented in the kubectl completion script. In this case, plugin creators could provide completion scripts for their plugins which can then be invoked by the kubectl completion script when it detects that the user is using a plugin command.

**Comment by superbrothers** [comment]
I try to implement completion for kubectl plugins.
