### ISSUE TITLE
Allow kubeconfig to be Base64 encoded string

### ISSUE THREAD

**Issue by webdeb** [kubernetes/kubectl#588]
**FEATURE REQUEST**

kubectl --kubeconfig=$K8S_CONFIG_BASE64 [do something]

Would be nice, if you could just pass the whole kubeconfig as base64 string to kubectl command.
The main reason for this is to use kubectl in CI/CD pipelines, where people are storing their kubeconfig in some sort of settings/variables (like gitlabs secrets). Also if you use some kind of kubectl container to run kubectl.

AFAIK the mainly used workaround is to decode that string, create a tmp/file, and then executing the command.

**Comment by webdeb** [comment]
Just an idea that could be implemented very easily: 

```
--kubeconfig="base64:$K8S_CONFIG"
```

**Comment by waldbeerlein** [comment]
+1

**Comment by webdeb** [comment]
@seans3 please check out my PR

**Comment by mishushakov** [comment]
You could just:

1. Copy your kubeconfig to clipboard as base64 string:
`cat ~/.kube/config | base64 | pbcopy `

2. On your CI pipeline, create a environment variable `kube_config` and paste your base64 string
3. Encode your base64 variable back to kubeconfig environmental variable:
`echo ${kube_config} | base64 -d > ${KUBECONFIG}`

4. Set context with kubectl:
`kubectl config use-context <name of your context>`
5. Execute your commands
6. Done!

**Comment by webdeb** [comment]
@mishushakov yes, thats exactly what I already wrote. these are 4 commands you have to put inside your ci/cd scripts, and **unfortunately this method does not work if you store the variable in gitlab secrets** because it prevents secrets to be printed.

**Comment by mishushakov** [comment]
@webdeb on GitLab you can connect your cluster and have access to k8s environment variables (https://gitlab.com/help/user/project/clusters/index#deployment-variables), in this case we actually need the `KUBECONFIG` variable:

<img width="1230" alt="Screenshot 2019-04-05 at 02 05 26" src="https://user-images.githubusercontent.com/10400064/55596102-4a28e780-5747-11e9-9b0e-70b905eb983b.png">

**Comment by cbluth** [comment]
I have been looking for something like this, to execute `kubectl` commands against different clusters progamatically without having to deal with KUBECONFIG files on the filesystem.

**Comment by unixfox** [comment]
Can someone reopen this issue? Some people are still interested into this feature.

**Comment by webdeb** [comment]
Just a hint for everyone who needs this for the GitLab CI.

You can define your **Variable** as **File**
https://docs.gitlab.com/ee/ci/variables/#custom-environment-variables

The Variable can then be used directly with `kubectl`
 without creating a file manually in the scripts.

```
kubectl ... --kubeconfig="${K8S_CONFIG}"
```
