### ISSUE TITLE
Password with special charts being stripped down while depoying pod

### ISSUE THREAD

**Issue by josefkorbel** [kubernetes/kubectl#589]
This is not duplicate to #46 

I was following [this][1] tutorial for deploying Django App to Kubernetes Cluster. I've created cloudsql credentials and exported them as in the tutorial

```
export DATABASE_USER=<your-database-user>
export DATABASE_PASSWORD=<your-database-password>
```
However my password was generated by LastPass and contains special characters, which are striped out in Kubernetes Pod thus making the password incorrect.

This is my password (altered, just showing the special chars)
`5bb4&sL!EB%e`

So i've tried various ways of exporting this string, echoing it out always show correct password, however in Kubernetes Dashboard the password is always incorrect (Also altered in DevTools, but some chars are just stripped out)

[![enter image description here][2]][2]

Things I've tried

```
export DATABASE_PASSWORD=$'5bb4&sL\!EB\%e'
export DATABASE_PASSWORD='5bb4&sL!EB%e'
```

Echoing is always good but kubernetes is always stripping it.

Deploying with `skaffold deploy`

  [1]: https://cloud.google.com/python/django/kubernetes-engine
  [2]: https://i.stack.imgur.com/yR5o9.png

**Comment by josefkorbel** [comment]
Got answer on SO to base64 encode the password, which is smart, but only works in local development as the credential files for cloudsql proxy still contains the original string.

**Comment by josefkorbel** [comment]
Moving to SO and closing as I am starting to think that this is not kubectl related, more like gke related.

**Comment by sftim** [comment]
@josefkorbel it looks like you may have found a genuine bug with `kubectl` and `&` within Secret values for `kubectl create`.
If you've the capacity, consider reopening the issue.
