### ISSUE TITLE
output on create/update/delete to contain namespace

### ISSUE THREAD

**Issue by briansan** [kubernetes/kubectl#593]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?**: namespace

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

When a resource is modified in someway, the typical output from kubectl looks like the following:
```deployment.apps/nginx created```
It would be nice if the output would also contain the namespace like:
```deployment.apps/nginx created in default```

**Comment by almiche** [comment]
This sounds like a good idea I'd be happy to work on this if anyone thinks it's a worthwhile addition to kubectl 😄

**Comment by advissor** [comment]
+1 Sounds like a good idea
