### ISSUE TITLE
"error: unexpected EOF" when following logs

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kubectl#595]
**Kubernetes version** (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
AWS EC2 via kops

**What happened**:
After approx 10 mins, following a log bails out with "error: unexpected EOF". The pod is not generating output during this time, so feels like the log follow gives up if its not receiving data often enough.

**What you expected to happen**:
Logs should be followed indefinitely, even if the pod has quiet periods.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl logs <podname> -f`

**Comment by cortex3** [comment]
Did you ever find a solution to this? I've been having this issue for months.

**Comment by kaiivoschneider** [comment]
Same problem here

**Comment by tsafs** [comment]
I also experience this problem

**Comment by msw1996** [comment]
Same problem here

**Comment by Donkeyotee** [comment]
Same problem here

**Comment by Donkeyotee** [comment]
I wrote this very stupid work around.

`#!/bin/bash
nameofpod=$1

#execute k log forever or until you hit CTRL+C
while true
do
   kubectl logs -f $nameofpod $2
   echo "\n\n\n\n\n\n"
done
`
Save this as ktaillogs and then run.
`chmod +x ktaillogs`
`./ktaillogs $thenameofthepod`

For extra credit copy that to /usr/local/sbin and if its in your path you can then run it anywhere by just dropping the ./ like the following

`ktaillogs $thenameofthepod`
This could allow a number of things as I do not sanitize the input of the variable so use at your own risk.
