### ISSUE TITLE
AAD with MFA Error while retrieving OAuth token: Unknown Error

### ISSUE THREAD

**Issue by tehho** [kubernetes/kubectl#596]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Sort of.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
AAD, OAuth token, Failed to acquire a token

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):
Client: 1.13.3
Server: 1.12.6

**Environment**:
- **Cloud provider or hardware configuration**: AKS
- **OS** (e.g. from /etc/os-release): Windows and Mac
- **Kernel** (e.g. `uname -a`): Windows 10 1809 and Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- **Install tools**: Choco for windows, brew install
- **Others**: Love the tool and kubernetes

**What happened**:
We are unable to login to kubernetes with MFA enabled. 
Our office is permitted without MFA so that work but an outside site gets error:

"To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CUKXHW3AG to authenticate.
E0304 10:00:31.778179    3212 azure.go:127] Failed to acquire a token: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Unknown Error
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C83X9S8QB to authenticate.
E0304 10:01:03.795739    3212 round_trippers.go:174] CancelRequest not implemented by *azure.azureRoundTripper"

**What you expected to happen**:
Work... No but a better error message why and yes work with MFA. 

**How to reproduce it** (as minimally and precisely as possible):
AKS with AAD integration MFA on the user logging in. 

**Anything else we need to know**:
AAD app is setup using https://docs.microsoft.com/en-us/azure/aks/aad-integration.

**Comment by digeler** [comment]
Did you got this issue resolved?

**Comment by raftAtGit** [comment]
what is the solution for this issue?
