### ISSUE TITLE
SECURITY_CONTACTS: please include developers of kubectl

### ISSUE THREAD

**Issue by philips** [kubernetes/kubectl#597]
The current SECURITY_CONTACTS document in kubectl simply includes the Kubernetes Product Security Team. Please replace this list with kubectl developers who should be contacted by the Kubernetes Product Security Team in case of a security disclosure.

For example you might choose a subset of the approvers from OWNERS

**Comment by philips** [comment]
never mind, this is fixed. https://github.com/kubernetes/kubectl/blob/master/SECURITY_CONTACTS

**Comment by philips** [comment]
gah, it is not fixed, the kubernetes security commitee is still listed as the security contact. Please fix!

**Comment by philips** [comment]
@pwittrock @soltysh any recommendation on what to do here? kubectl really deserves to have SECURITY_CONTACTS I think.

**Comment by soltysh** [comment]
@philips sorry, I missed this issue earlier, fix in https://github.com/kubernetes/kubernetes/pull/82261
