### ISSUE TITLE
Unresolved issue mistakenly closed, please reopen

### ISSUE THREAD

**Issue by sassanh** [kubernetes/kubectl#599]
This is not a bug report nor question, it's a meta issue to reopen another issue.

https://github.com/kubernetes/kubectl/issues/151 is about:

1. Bad documentation (which is solved now)
2. Kubernetes not having a reasonably simple API to query "ALL" resources in a namespace (which is not resolved yet.)

As many commented there that command doesn't work for me too with the same error they reported.

As that issue is not resolved yet and adding comments to a closed issue doesn't bring any attention I create this issue to ask you kindly reopen that issue (and do not close it nor any other issues until they're solved).

**Comment by dims** [comment]
done!

/close

**Comment by sassanh** [comment]
Thanks
