### ISSUE TITLE
kubectl proxy --reject-methods flag is non-functional

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubectl#6]
The flag is registered, but the specified value is never read or used

This means all http methods are allowed by default (despite the help saying PUT/POST/PATCH being disallowed), and users have no way to control which methods are accepted

**Comment by adohe** [comment]
@liggitt Thanks for reporting this, I will fix this today.

**Comment by pwittrock** [comment]
@adohe Any updates?
