### ISSUE TITLE
'kubectl desc' shortcut for 'kubectl describe'

### ISSUE THREAD

**Issue by HariSekhon** [kubernetes/kubectl#605]
**Kubernetes version** (use `kubectl version`): 1.8

Feature Request to have `kubectl describe` to support the shorted form `kubectl desc`, in a similar way that you can `kubectl get po` instead of `kubectl get pods`.

**Comment by superbrothers** [comment]
You can use kubectl plugin as follows:

```
$ cat <<'EOL' >kubectl-desc
#!/bin/sh
exec kubectl describe $@
EOL
$ chmod +x kubectl-desc
$ sudo mv kubectl-desc /usr/local/bin/
$ kubectl desc po nginx
```

kubectl plugin was implemented in kubectl 1.12, so you need to upgrade kubectl. See https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ for more details.

**Comment by HariSekhon** [comment]
Thanks

**Comment by brunzefb** [comment]
Hi -- I think this would be something easy to implement, and regret this being rejected. The proposed solution via a plugin works, but needs to be done for each machine running kubectl.  

Save our fingers!

F.

**Comment by Stenstromen** [comment]
I agree @brunzefb, but you have to love the workaround @superbrothers is suggesting!
