### ISSUE TITLE
Create Key Agent Integration for kubectl

### ISSUE THREAD

**Issue by aauren** [kubernetes/kubectl#62]
**Feature Description**
For those that don't want to have an unencrypted set of x509 keys on their system for kubectl to use, it would be helpful if kubectl were able to retrieve the x509 keys from a secure agent such as gpg-agent. That way, instead of having the certificates either specified by path or within the kubectl context itself in an insecure manner, kubectl could reference and retrieve them by name from the agent for use.

A fallback request from this would be to add a parameter to kubectl, something liked: `--client-key-passphrase` which would tell kubectl to prompt the user for a decryption passphrase, decrypt the x509 certificate, and then use it for authentication to the kube-apiserver. While I think that this would likely be simpler to implement, it would put a higher burden on the user because they would have to supply a passphrase for the certificate for each command.

However, I believe that both of these ideas would be an improvement to the current security model.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+922a86cfcd659", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"not a git tree", BuildDate:"2017-08-16T21:21:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+793658f2d7ca7", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"not a git tree", BuildDate:"2017-08-28T23:44:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): Gentoo
- **Kernel** (e.g. `uname -a`): Linux 4.9.40-vanilla-base-2
- **Install tools**: N/A
- **Others**: N/A

**Comment by apelisse** [comment]
CC @cjcullen

**Comment by liggitt** [comment]
an interesting alternative could be an "exec for key" that could invoke a separate command to retrieve unencrypted pem key content. That command could possibly take advantage of an active ssh-agent or gpg-agent session to provide key content

**Comment by liggitt** [comment]
/close
in favor of exec-obtained credentials
@ericchiang is there an issue tracking x509 expansion of the exec interface?

**Comment by ericchiang** [comment]
Issue for tracking x509 client certs https://github.com/kubernetes/kubernetes/issues/61421
