### ISSUE TITLE
ANSI escape sequences aren't terminated by kubectl logs

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubectl#63]
Partial ANSI sequences escape `kubectl logs` (at least on my OS X terminal).  I *think* we may need to look at what other tools like head and tail do.

**Comment by apelisse** [comment]
I really doubt any of these tools are smart. 

Maybe: `PS1="\[\033[0m\]$PS1"` :-)

**Comment by apelisse** [comment]
Feel free to re-open if needed. Thanks
