### ISSUE TITLE
kubectl --help exit code 0

### ISSUE THREAD

**Issue by pplu** [kubernetes/kubectl#637]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Not needed
- **OS** (e.g. from /etc/os-release): Linux

**What happened**:
```
pplu@beezelbot:~/$ kubectl
kubectl controls the Kubernetes cluster manager.
[...]
pplu@beezelbot:~/$ echo $?
0

pplu@beezelbot:~/$ kubectl get pods --help
Display one or many resources
[...]
pplu@beezelbot:~/$ echo $?
0
```

**What you expected to happen**:

I would expect a non-zero exit code from the command when help is displayed.

**Comment by prksu** [comment]
hi @pplu why you expect a non-zero exit code when displaying help?
the command successful termination, so it's normal to exit with zero code.

**Comment by asalkeld** [comment]
```
$ cut --help >/dev/null
$ echo $?
0
$ grep --help >/dev/null
$ echo $?
0
$ vi --help >/dev/null
$ echo $?
0
$ systemctl --help >/dev/null
$ echo $?
0
```

**Comment by seans3** [comment]
As pointed out in the previous two comments, `kubectl --help` terminates successfully, so it should return exit code 0. Closing this issue.

/close
