### ISSUE TITLE
when EXTERNAL-IP too long

### ISSUE THREAD

**Issue by yangnaihua** [kubernetes/kubectl#646]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
```
Darwin PauldeMacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
- **Install tools**: zsh

**What happened**:
when use AKS in AWS, the ip too long ,so can not be found the ip
 EX:
```
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)          AGE
redis-master     LoadBalancer   10.100.6.182     a98068ce56515...   3000:31686/TCP   36m
```

**Comment by brianpursley** [comment]
@naihuayang Can you provide more info to reproduce?  Do you have a yaml file you used to create redis-master?  Are you using IPv6?

I created an AKS cluster and the deployment using the [aks quickstart](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough#run-the-application) and did not observe the problem like you did:

```
$ k get services
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)        AGE
azure-vote-back    ClusterIP      10.0.96.3      <none>           6379/TCP       14m
azure-vote-front   LoadBalancer   10.0.191.223   104.45.185.250   80:31875/TCP   8m12s
kubernetes         ClusterIP      10.0.0.1       <none>           443/TCP        25m
```

**Comment by brianpursley** [comment]
Without being able to reproduce it, I just happened to find where it truncates the external IP to 13 bytes + "..." when it is longer than 16 bytes.

https://github.com/kubernetes/kubernetes/blob/ea5cef1c65b5890011bdd258f5c61dcf197ee5e3/pkg/printers/internalversion/printers.go#L1018

```
const (
	loadBalancerWidth = 16
	...
}
```
```
func loadBalancerStatusStringer(s api.LoadBalancerStatus, wide bool) string {
	...
	if !wide && len(r) > loadBalancerWidth {
		r = r[0:(loadBalancerWidth-3)] + "..."
	}
	return r
}
```
```
func getServiceExternalIP(svc *api.Service, wide bool) string {
	switch svc.Spec.Type {
	...
	case api.ServiceTypeLoadBalancer:
		lbIps := loadBalancerStatusStringer(svc.Status.LoadBalancer, wide)
	...
}

```

It looks like that in order to support full display of IPv6 in table format, `loadBalancerWidth` would [need to be changed from 16 to 48](https://github.com/torvalds/linux/blob/11a48a5a18c63fd7621bb050228cebf13566e4d8/include/linux/inet.h#L50)

**Comment by naihuayang** [comment]
Hi, 
I think can be try use 
```
kubectl get svc -o wide
```

**Comment by brianpursley** [comment]
> ```
> kubectl get svc -o wide
> ```
@yangnaihua does that show the entire address for you?

**Comment by yangnaihua** [comment]
> > ```
> > kubectl get svc -o wide
> > ```
> 
> @yangnaihua does that show the entire address for you?

in fact, i am not sure. if not , it is a bug
