### ISSUE TITLE
Kustomize set image validating CRDs and fails

### ISSUE THREAD

**Issue by dweidenfeld** [kubernetes/kubectl#650]
The `kubectl` command is currently validating CRDs in the context of Kustomize + set image.

The following command should work for my expectation, but since we're using Istio and Kubeseal it is failing.

```
kubectl set image -k .deployment/production myapp=myapp:1.1.1 --local --dry-run
unable to decode ".deployment/production": no kind "SealedSecret" is registered for version "bitnami.com/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
unable to decode ".deployment/production": no kind "ServiceRole" is registered for version "rbac.istio.io/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
unable to decode ".deployment/production": no kind "ServiceRoleBinding" is registered for version "rbac.istio.io/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

**Comment by dpoetzschke** [comment]
We are still interested in this.

/remove-lifecycle stale

**Comment by cbrintnall** [comment]
It seems to apply to anything the kustomize flag would apply - is this expected behavior? For instance, we also see it "failing" on services and HPAs. 

Would be nice if the `-k` flag behaved like `kustomize edit set image`.

**Comment by soltysh** [comment]
This issue is about kustomize not kubectl. Most importantly the kustomize version in kubectl is rather old due to problems with dependencies, see https://github.com/kubernetes/kubectl/issues/818. I'd suggest using latest binary release of standalone kustomize.
/close
