### ISSUE TITLE
Bug in InitClientAndConfig

### ISSUE THREAD

**Issue by maxb** [kubernetes/kubectl#651]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): home

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**What happened**:

Whilst perusing code in this repository, I spotted a bug at https://github.com/kubernetes/kubectl/blob/master/pkg/pluginutils/plugin_client.go#L42 :

```
func InitClientAndConfig() (*restclient.Config, clientcmd.ClientConfig, error) {
	// resolve kubeconfig location, prioritizing the --config global flag,
	// then the value of the KUBECONFIG env var (if any), and defaulting
	// to ~/.kube/config as a last resort.
	home := os.Getenv("HOME")
	if runtime.GOOS == "windows" {
		home := os.Getenv("HOMEDRIVE") + os.Getenv("HOMEPATH")     <-- BUG
		if home == "" {
			home = os.Getenv("USERPROFILE")
		}
	}
```
Since the := operator is used on the BUG line, a new variable called home shadows the definition of home in the outer scope, and all the logic inside the "windows" case is an effective no-op.

**Anything else we need to know**:

This logic isn't quite the same as https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/homedir/homedir.go in some edge cases. It might be worth considering aligning them exactly.

**Comment by pswica** [comment]
Good catch. I don't think this exists in the source code anymore, however.

I ran:
```
grep -ir 'home := os.Getenv' -A 5
```

**Comment by pswica** [comment]
I also cannot find `InitClientAndConfig()`.

/close

**Comment by maxb** [comment]
I concur that the affected code is no longer here since this repository was emptied and migrated to the staging process, so I'll close the issue.


Using GitHub search for InitClientAndConfig, it does seem there are various projects out there still depending on the removed code, though - might it be worth putting a note in this repo's README.md to explain the deletion of the k8s.io/kubectl/pkg/pluginutils package?
