### ISSUE TITLE
kubectl exec does not accept pod/ resource type prefix

### ISSUE THREAD

**Issue by jorisroovers** [kubernetes/kubectl#656]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** : kubectl exec

---

**Is this a BUG REPORT or FEATURE REQUEST?** : FEATURE REQUEST
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
---
When passing a podname with the ```pod/``` resource type to ```kubectl exec```, an error occurs:

```sh
# This works
$ kubectl exec "my-pod" hostname
my-pod-name

# This doesn't
$ kubectl exec "pod/my-pod" hostname
error: invalid resource name "pod/my-pod": [may not contain '/']
```

It's clear ```kubectl exec``` only takes a pod name and that the ```pod/``` specifier is thus redundant, but not allowing the prefix makes ```kubectl exec``` inconsistent with other ```kubectl``` subcommands such as ```kubectl describe```, ```kubectl delete```, etc.

This becomes a bit of nuisance when scripting:
```sh
# Get pod name
POD_NAME=$(kubectl get pod -o name -l foo=bar)
echo $POD_NAME
pod/my-pod

# These work fine:
kubectl describe $PODNAME
kubectl delete $PODNAME
kubectl get $PODNAME
kubectl label $PODNAME hur=dur

# kubectl exec doesn't
kubectl exec $PODNAME hostname
error: invalid resource name "pod/my-pod": [may not contain '/']
```

It would be nice if ```kubectl exec``` would accept the ```pod/``` prefix. Thanks for considering!

**Comment by prksu** [comment]
Hi @jorisroovers this feature will be release in v1.15
it's already added in [v1.15-alpha2](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#v1150-alpha2)

please be patient until v1.15 release in June 17th. thanks
