### ISSUE TITLE
Kubectl cp error using kubectl version 1.14.2

### ISSUE THREAD

**Issue by Reinkaos** [kubernetes/kubectl#659]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

error: open is a directory

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

kubernetes 1.11.7

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): ubuntu
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kops
- **Others**:

**What happened**:

kubectl cp from a pod to a destionation directory on your machine does not copy the file and results in this error `error: open <destination> is a directory`

**What you expected to happen**:

The file is copied from the pod to my machine. 

**How to reproduce it** (as minimally and precisely as possible):

install kubectl version 1.14.2 and attempt to copy a file from a pod to your local machine. 

**Anything else we need to know**:

kubectl cp command works correctly on 1.14.1.

**Comment by pswica** [comment]
I tested and had this issue as well. I tried to address in my PR here: https://github.com/kubernetes/kubernetes/pull/78785

**Comment by danton721** [comment]
Any solution? Having the same issue over here

**Comment by LeszekChojnacki** [comment]
Any solution? Having the same issue over here
