### ISSUE TITLE
Kubectl port-forward doesn't warn about used port?

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kubectl#664]
eg. I have a service on local machine run under port `5555`. 
Why then the command: `kubectl port-forward {{pod_name}} 5555:{{some_port}}` is allowed?

Isn't it supposed to warn the user about: `port 5555 is already used`?

**Comment by pswica** [comment]
I tested and found this as well. I tried to fix here: https://github.com/kubernetes/kubernetes/pull/78802

**Comment by brianpursley** [comment]
Is this still an issue?  If so, can you provide steps to reproduce.  Also, what is your kubectl version?

Here is what I tried.

My kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Setup:
```
$ kubectl run nginx --image=nginx --restart=Never
```

Confirm port forward works (`curl -I 127.0.0.1:5555` to verify):
```
$ kubectl port-forward nginx 5555:80
Forwarding from 127.0.0.1:5555 -> 80
Forwarding from [::1]:5555 -> 80
Handling connection for 5555
^C
```
Stop port forwarding.

Start ncat on port 5555:
```
ncat -l 5555
```

Try port forwarding again:
```
$ kubectl port-forward nginx 5555:80
Unable to listen on port 5555: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use]
error: unable to listen on any of the requested ports: [{5555 80}]
```

So the message looks to me like it is telling me port 5555 is already in use.

**Comment by Aracki** [comment]
I tested with client 1.17 and server 1.15 version and it does warn about used port! Thanks @brianpursle,y I'm gonna close this one.
