### ISSUE TITLE
Error when trying to run kubectl create command on yaml files

### ISSUE THREAD

**Issue by iamcaleberic** [kubernetes/kubectl#67]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`
**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

- **Kernel** (e.g. `uname -a`): 4.13.3-1-ARCH
- **Install tools**: 
- **Others**:

**What happened**:
Created a manual secrets file and while trying to create this error is thrown
`$ kubectl create -f ./file.yaml`
 
`error: error validating "./file.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"Secret"}; if you choose to ignore these errors, turn validation off with --validate=false`

Retried with the the secrets file in the documentation just to confirm it was not a syntax mistake but same outcome.

`kubectl create -f redis.yaml`

Also happens with the rest of the service files other than secrets  

**What you expected to happen**:
the expectation was a confirmation that the secret "file" created

or 

service "redis" created
replicationcontroller "redis" created

**How to reproduce it** (as minimally and precisely as possible):
`$ kubectl create -f ./file.yaml`

**Anything else we need to know**:

if i turn the validation off everything seems to be fine with the flag validate=false

**Comment by apelisse** [comment]
@iamcaleberic Could you tell me more about the Kubernetes environment that you're using? is it a minikube server? There is a known limitation against minikube servers https://github.com/kubernetes/minikube/issues/1996 (cf [1.8 release note](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#known-issues) too)

Let me know if that's NOT what it is.

Thank you,

**Comment by pwittrock** [comment]
@mbohlool can you follow up on this

cc @k8s-mirror-api-machinery-bugs

**Comment by mbohlool** [comment]
@pwittrock Sure. I will wait for @apelisse question to be answered. Most probably this is minikube but will look further if it is not.

**Comment by iamcaleberic** [comment]
@apelisse yes I am running a minikube server

**Comment by apelisse** [comment]
I'm so glad to hear that! :-)

I'm closing this issue, let's follow up on https://github.com/kubernetes/kubectl/issues/67

Thank you
