### ISSUE TITLE
Getting an error while using kubectl get nodes command from Windows 10 PowerShell

### ISSUE THREAD

**Issue by rmalwade** [kubernetes/kubectl#670]
Hi, I am trying to connect to my K8s cluster. While verifying connection using 'kubectl get nodes', I get an error : error: You must be logged in to the server (Unauthorized) I have tried removing kubectl and re-installing. Nothing works. When I use : PS C:\Users\RajeshMalwade> kubectl config view command..it does show my ICP cluster but not the IBM Public Cloud Cluster. PS C:\Users\RajeshMalwade> kubectl config view apiVersion: v1 clusters: - cluster: insecure-skip-tls-verify: true server: https://compute.data.zc2.ibm.com:8001 name: compute.data.zc2.ibm.com contexts: - context: cluster: compute.data.zc2.ibm.com namespace: cdo-dnbmastr-dev user: raj.malwade@us.ibm.com name: compute.data.zc2.ibm.com-context current-context: compute.data.zc2.ibm.com-context kind: Config preferences: {} users: - name: raj.malwade@us.ibm.com user: token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMXkzcmdob3NkM3o2MG9xMnd5ZnQiLCJyZWFsbU5hbWUiOiJjdXN0b21SZWFsbSIsInVuaXF1ZVNlY3VyaXR5TmFtZSI6InJhai5tYWx3YWRlQHVzLmlibS5jb20iLCJpc3MiOiJodHRwczovL2NvbXB1dGUuZGF0YS56YzIuaWJtLmNvbTo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiIwZmU4YjgzYTZjZTRlMjNlOTMzYTBiN2Q5NzdlZjg0MyIsImV4cCI6MTUzOTg3ODIzNSwiaWF0IjoxNTM5ODc4MjM1LCJzdWIiOiJyYWoubWFsd2FkZUB1cy5pYm0uY29tIiwidGVhbVJvbGVNYXBwaW5ncyI6WyJpY3A6Y2RvLWRuYm1hc3RyLWRldjphZG1pbiIsImljcDpkZWZhdWx0Om1lbWJlciIsImljcDpkZWZhdWx0OnRlYW1hZG1pbiJdfQ.qqq8pfSP3RUWKanFTGdjxxTnJ4ZSoPJENsMnjdowgHATwKhRz6EJCUD0yHCBYpEgW2x-5QHS8heZ4aL5OVtuXxF2x7xT7nVf3qXQmRGDhf3wqM6ppgo_iM6FXtaE7s4oIh8zpMzWheK0c9_hCdiXjk2FkZHawyZIuKcFZa4hd1Y0XE6NYjRRJNM9A9Wuj_n5lvkk5JgDBAQpDFQ4WrEdjEM-g0jEfgjsS24mj6mj-A9PwkOKRJnA559lSz7GTcND_R3c8nLEax3IyClLblilL1Xfky9Vl7_6saNjhlpWB6Ef0bZaLI8KeHOs_m76622Ky_hUTUaFF7dp9lD7bdLo2g PS C:\Users\RajeshMalwade>

**Comment by pswica** [comment]
To me, this is more of a IBM cloud issue than a kubectl one. Have you tried making an issue with their support? (notice that you are getting authorization issues, and not getting bugs from the `kubectl` command.
