### ISSUE TITLE
Add flag for foregroundDeletion

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubectl#672]
There are three kinds of deletions apiserver supports: orphan, background, and foreground. Right now kubectl supports only orphan (--cascade=false) and background (--cascade=true). But there's no way to do a "foreground" deletion. In some cases foreground is required, for example when dependent resources need to be cleaned up for owner deletion to succeed.

I'd like to see `--propegation-policy=foreground` for this use case.

**Comment by liztio** [comment]
possibly related: https://github.com/kubernetes/kubernetes/issues/59850

**Comment by jonnylangefeld** [comment]
@liztio I think this would be actually super useful, as the only way currently is through an unintuitive curl command. Can you reopen?
