### ISSUE TITLE
How to contribute to the kubectl book is confusing

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubectl#676]
### question summary

1. Which repository should we open an issue on?
1. Which source code should we modify?

### my opinion

1. [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes)
1. [kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/docs/book](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/docs/book)

### details

[Introduction - the Kubectl Book](https://kubectl.docs.kubernetes.io/) has a link to [CONTRIBUTING](https://github.com/kubernetes/kubectl/blob/master/docs/book/CONTRIBUTING.md) on top of the page. The linked page is a part of kubernetes/kubectl repo and the content is like following.

> Fixing Issues
> 1. Open an Issue
> 1. Create a PR
> 1. Email PR to sig-cli@googlegroups.com with subject Kubectl Book: Fix Issue <Issue> in <PR>
> 1. Optional: Come to sig-cli meeting to discuss

Given this message, it seems we should open an issue on kubernetes/kubctl repo. However, [PULL_REQUEST_TEMPLATE](https://github.com/kubernetes/kubectl/blob/master/.github/PULL_REQUEST_TEMPLATE.md) indicates PRs aren't expected in this repo. It's confusing (e.g. https://github.com/kubernetes/kubectl/pull/673).

**Comment by apelisse** [comment]
> 1. kubernetes/kubernetes

Kubectl issues are typically opened in kubernetes/kubectl.

> 2. kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/docs/book

That's correct.

> Given this message, it seems we should open an issue on kubernetes/kubctl repo. However, PULL_REQUEST_TEMPLATE indicates PRs aren't expected in this repo. It's confusing (e.g. #673).

Yeah, we open issues here, but the code is in k/k. I'll leave this issue open if you want to fix the CONTRIBUTING page to clarify.

**Comment by oke-py** [comment]
Thanks for your reply. I'll try to fix the CONTRIBUTING page.

**Comment by oke-py** [comment]
@apelisse I opened PR last week. PTAL. Thanks in advance.
