### ISSUE TITLE
A copy of your changes has been stored to "/tmp/kubectl-edit-4jyoa.yaml" error: Edit cancelled, no valid changes were saved. 

### ISSUE THREAD

**Issue by Warok21** [kubernetes/kubectl#677]
### Environment
Installation method:
Kubernetes version: client : 1.14, server 1.14
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
### Steps to reproduce
When i want to edit my file to use the public IP of my server, I get the error in the tittle:
`sudo kubectl -n kubernetes-dashboard edit service kubernetes-dashboard
`
### Observed result
`A copy of your changes has been stored to "/tmp/kubectl-edit-4jyoa.yaml" error: Edit cancelled, no valid changes were saved.
`
Expected result
Comments

**Comment by Warok21** [comment]
Had to reinstall all the things :(

**Comment by Aech1977** [comment]
thanks.  I've gotten past that error but discovered my AKS cluster has been upgraded past the point kube-lego is working so now I'm trying to figure out how to get cert-manager working.  Kubernetes is confusing enough but trying to get cert manager working is kicking my ass.

**Comment by root21cuib** [comment]
Make sure the indentations are right especially where the hyphens "-" are found
