### ISSUE TITLE
kubectl delete ns has inconsistent behavior

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/kubectl#678]
**What happened**:
When passing multiple namespaces to `kubectl delete ns`, it blocks if the given parameters exist, but it does not block if one of the parametes does not exist. 

**What you expected to happen**:
In order to be consistent, if we're blocking on multiple parameters, we should block until all events finish regardless if one of them errors.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
> kubectl create ns n1
> kubectl create ns n2
> kubectl create ns n3
# this blocks until both finish deleting
> kubectl delete ns n2 n3
namespace "n2" deleted
namespace "n3" deleted
# blocking...
# returns once all given namespaces finish terminating

> kubectl create ns n2
# this does not block as `n3` does not exist
> kubectl delete ns n2 n3 n1
namespace "n2" deleted
namespace "n1" deleted
Error from server (NotFound): namespaces "n3" not found
# returns immediately

# namespaces still in terminating state
> kc get ns
NAME          STATUS        AGE
n1            Terminating   12s
n2            Terminating   10s
```

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by yashbhutwala** [comment]
So, I see there is a `--ignore-not-found` flag, which will not cause this.  Still I would've expected `kubectl` to print out the error, but not return immediately.  So, perhaps still a bug in that there should be no `--ignore-not-found` flag, and it should always print the NotFound error, but continue to block until the remaining Found ones finish terminating.

**Comment by soltysh** [comment]
The fact that we have `--ignore-not-found` is why this is working this way, if you prefer to ignore errors you have an option to do so, if not the default behaviour is to fail fast. This is not a bug but it's working as designed.
/close
