### ISSUE TITLE
shell completion is intolerably slow on medium-to-large clusters

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kubectl#683]
My kubectl:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:52:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

My shell:
```
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

We have a cloud-hosted Kubernetes cluster located geographically very close to us which has about 2250 pods in our main deployment namespace. I don't know for sure, but I suspect that this isn't a particularly huge cluster, relatively speaking; maybe medium to medium-large sized.

Tab completion for `get pod` takes 6-7 seconds. It's so slow that it's basically not worth using at all.

I added set -x to my shell and found that the main place the command hangs is on this command:

```
kubectl get -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' pod
```

So I timed that:

```
$ time kubectl get -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' pod > /dev/null

real    0m5.793s
user    0m4.997s
sys     0m0.237s
```

Since it's templating the name value, I also thought to see if `-o name` would improve it, but it doesn't:

```
$ time kubectl get -o name pod > /dev/null

real    0m5.269s
user    0m4.526s
sys     0m0.239s
```

That's probably using a similar templating step under the hood.

Compare to `kubectl get pod` with regular output:

```
$ time kubectl get pod > /dev/null

real    0m0.897s
user    0m0.387s
sys     0m0.032s
```

And here's one approach to client-side processing of the regularly-formatted output to get a list of pod names:

```
$ time kubectl get pod --no-headers | awk '{print $1}' > /dev/null

real    0m1.238s
user    0m0.545s
sys     0m0.130s
```

This is much better than what the server is currently providing.

I thought about trying to time jsonpath output of the name, too, but I can never get jsonpath right, so I'll leave that for someone else to fiddle with.

**Comment by brianpursley** [comment]
Seems like the problem is that the entire json representation of the resource (including spec, status, etc) is returned for every pod, when only the name is needed.

As @geekofalltrades says, doing `kubectl get pod -o name` doesn't help because even in that case, it still receives the entire json payload for each pod and the name is just extracted client-side.

awk-ing the name out of the table is faster because the table is constructed on the server-side and so much less data needs to come back.

It would be nice if there were some way to make a request to the API and have it return only the names, so the overhead would be minimal.

**Comment by geekofalltrades** [comment]
Still an issue:

```
$ time kubectl get pod --no-headers | wc -l
5556

real    0m7.141s
user    0m3.941s
sys     0m0.250s
```
```
$ time kubectl get -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' pod > /dev/null

real    0m17.037s
user    0m15.623s
sys     0m0.307s
```

**Comment by eddiezane** [comment]
You might see a speed up on master now that https://github.com/kubernetes/kubernetes/pull/96087 is merged.
