### ISSUE TITLE
kubectl should have a version skew warning 

### ISSUE THREAD

**Issue by clehene** [kubernetes/kubectl#685]
See https://github.com/kubernetes/kubectl/issues/675

As per @seans3 
> Please note that Kubernetes version skew policy is to provide a kubectl that is guaranteed to work against an API Server that is +/- 1 version.

In this case, it would be appropriate to warn when this is the case.

**Comment by clehene** [comment]
Just saying, having blog posts about this is a good argument for the feature https://www.benpickles.com/articles/72-downgrading-kubectl-with-homebrew

**Comment by thapakazi** [comment]
Agreed !! needed proper warning message for lame users like us.
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

I updated kubectl for `rollout restart` but got ingress describe broken :(

**Comment by brianpursley** [comment]
@seans3 are you thinking this warning would occur only when you do `kubectl version` or after any kubectl command that makes a call to the server?

**Comment by seans3** [comment]
@brianpursley I was imagining it would happen for every command that makes a call to the server. It would be very intrusive; but I think that's the point.

**Comment by brianpursley** [comment]
@seans3 agreed, otherwise people won't see it.

Is there any way to know the server version without making a call to explicitly retrieve it?

What do you think about the API adding a header to the response that indicates the server version, something like `X-Kubernetes-Version: 1.19.0` so that after each call the client can check the skew, without having to make a separate call to get it?  

Or do you think we should just use the existing method in DiscoveryClient to get the server version?

**Comment by brianpursley** [comment]
@seans3 Maybe this is or isn't the direction to go, but I wanted to learn a little more about how the API works so I decided to go down this path a little.  

I'm thinking it could be done without too much work by adding a filter to set the response header. like this PR in my repo shows:
https://github.com/brianpursley/kubernetes/pull/1/files

Running that locally, the debug output looks like this:
```
...
I0408 21:36:38.975916   15159 round_trippers.go:443] GET https://localhost:6443/apis/batch/v1beta1/namespaces/default/cronjobs?limit=500 200 OK in 1 milliseconds
I0408 21:36:38.975928   15159 round_trippers.go:449] Response Headers:
I0408 21:36:38.975934   15159 round_trippers.go:452]     Content-Length: 2253
I0408 21:36:38.975939   15159 round_trippers.go:452]     Date: Thu, 09 Apr 2020 01:36:38 GMT
I0408 21:36:38.975943   15159 round_trippers.go:452]     Audit-Id: 4e5c28f1-585e-42f0-8a9a-7923c26e76db
I0408 21:36:38.975947   15159 round_trippers.go:452]     Content-Type: application/json
I0408 21:36:38.975952   15159 round_trippers.go:452]     Kubernetes-Version: v1.19.0-alpha.1.440+4c3790efd2f1df
...
```

I'm not sure if the API team would go for this or not, but it would make the version available to kubectl without having to make an extra call to get it.

**Comment by jglick** [comment]
> It would be very intrusive; but I think that's the point.

Maybe this could be opt-out, or printed at most once per day, or something? I run `kubectl` from the Snap (typically very new) against a variety of clusters, some significantly older (EKS…), and have rarely encountered an _actual_ problem. I think there was one obscure issue with `top` sort order or something. Having `kubectl` print a warning after every command, with no option to suppress this, would just be irritating.

**Comment by soltysh** [comment]
Opt-in is already there, and it's matching the exact version, @brianpursley look into the code behind `--match-server-version` flag, we'll use something similar but warning on +/- 2 because we want a clear information for users they are outside of supported boundaries for now. 

/priority critical-urgent

**Comment by brianpursley** [comment]
Thanks @soltysh I wasn't aware of the `--match-server-version` flag.

**Comment by brianpursley** [comment]
@soltysh are you working on this or are you looking for someone to work on it?  Just curious what the critical-urgent label means.

**Comment by dty1er** [comment]
Agreed on this issue. I actually developed a kubectl plugin for this purpose, (https://github.com/dty1er/kubectl-skew), but it would be much better if it is integrated in kubectl core.

**Comment by eddiezane** [comment]
This was closed by https://github.com/kubernetes/kubernetes/pull/98250

/close
