### ISSUE TITLE
Service port forwarding recovery on restarted pods

### ISSUE THREAD

**Issue by balopat** [kubernetes/kubectl#686]
When I start `kubectl port-forward svc/leeroy-app 50053:50051 ` it works the first time. 
If I kill the pod behind the service, kubernetes restarts the pod, and then the port forwarding starts failing: 

```
Handling connection for 50053
Handling connection for 50053
E0722 16:21:00.929687  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured
E0722 16:21:00.969972  155541 portforward.go:362] error creating forwarding stream for port 50053 -> 50051: Timeout occured
E0722 16:21:02.989783  155541 portforward.go:362] error creating forwarding stream for port 50053 -> 50051: Timeout occured
E0722 16:21:03.998054  155541 portforward.go:362] error creating forwarding stream for port 50053 -> 50051: Timeout occured
E0722 16:21:04.598329  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured
E0722 16:21:05.577799  155541 portforward.go:362] error creating forwarding stream for port 50053 -> 50051: Timeout occured
Handling connection for 50053
E0722 16:21:06.166770  155541 portforward.go:362] error creating forwarding stream for port 50053 -> 50051: Timeout occured
E0722 16:21:35.578937  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured
Handling connection for 50053
Handling connection for 50053
E0722 16:21:40.688533  155541 portforward.go:400] an error occurred forwarding 50053 -> 50051: error forwarding port 50051 to pod 6b8250b5be8d3e65ed5d9c900cb87966bed006b57cc81617d27b6ba271742815, uid : Error: No such container: 6b8250b5be8d3e65ed5d9c900cb87966bed006b57cc81617d27b6ba271742815
E0722 16:22:10.606373  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured
Handling connection for 50053
Handling connection for 50053
E0722 16:22:40.712581  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured
E0722 16:22:40.712668  155541 portforward.go:340] error creating error stream for port 50053 -> 50051: Timeout occured

```
If I kill manually kubectl port forwarding and restart, it works. 

I would love to see the recovery automatically instead of having to parse the output and restart manually. 

We are building portforwarding into our application through kubectl and this would help a lot with the integration.

**Comment by jjfmarket** [comment]
I also see this behavior, my port forwards start failing after I restart the pod that was being forwarded to.

**Comment by pvsousalima** [comment]
Isn't there any suggested implementation to implement this automatic recovery?

**Comment by brianpursley** [comment]
I was taking a look at this a little bit today and I think this is a legitimate issue.

The root problem seems to be that port forwarding enters some sort of unrecoverable state after it is no longer able to communicate with the pod it was connected to, and yet it does not fail with an exit code either.

### Here are my steps to reproduce (use two terminals)

**terminal 1**
```
kubectl run sysinfo --image=brianpursley/system-info
```

**terminal 2**
```
kubectl port-forward sysinfo 8080:80
```

Open a browser or curl to make some requests to http://localhost:8080 and verify that port forwarding is working

**terminal 1**
```
kubectl delete pod sysinfo
```

Open a browser or curl to make some requests to http://localhost:8080 and verify that port forwarding is no longer working

**terminal 2**
You will see some errors like these:
```
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1002 15:12:34.808176  125749 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod e2cb7d04631d95df43a87ad38952a027074a146da9ff85c43866c4e2b2806009, uid : exit status 1: 2020/10/02 15:12:34 socat[2905824] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
Handling connection for 8080
E1002 15:12:34.822191  125749 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod e2cb7d04631d95df43a87ad38952a027074a146da9ff85c43866c4e2b2806009, uid : exit status 1: 2020/10/02 15:12:34 socat[2905825] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
Handling connection for 8080
E1002 15:12:34.835750  125749 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod e2cb7d04631d95df43a87ad38952a027074a146da9ff85c43866c4e2b2806009, uid : exit status 1: 2020/10/02 15:12:34 socat[2905826] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
```

The problem is that kubectl never exits, and even if I do `kubectl run sysinfo --image=brianpursley/system-info` it is not able to connect, so it is sort of stuck in some invalid state.

**NOTE:**  My example above is for a single pod, but you can port-forward to a service or deployment, in which case it will select a single pod within the deployment and forward to that pod only. You can follow similar steps to reproduce the issue with a deployment, but you have to find the pod it is connect to and delete that pod to see the effect.

### Ideas on possible solutions

1. Detect connection errors and exit with a nonzero exit code
2. Detect connection errors and automatically attempt to re-establish a new port forwarding connection

**Comment by dougsland** [comment]
let try to reproduce this report and work on it.

**Comment by dougsland** [comment]
Hey @soltysh, I am wondering if we can discuss this one in the sig meeting. Should os.Exit(1) enough for this one ? Just tested a local patch and it works.

**Comment by soltysh** [comment]
> Hey @soltysh, I am wondering if we can discuss this one in the sig meeting. Should os.Exit(1) enough for this one ? Just tested a local patch and it works.

@dougsland just open a PR and pls ping me on slack with it, I'll review

**Comment by deads2k** [comment]
> > Hey @soltysh, I am wondering if we can discuss this one in the sig meeting. Should os.Exit(1) enough for this one ? Just tested a local patch and it works.
> 
> @dougsland just open a PR and pls ping me on slack with it, I'll review

Spoke on slack.  We don't exit from library code.  The library code in client-go is starting a server to forward requests, so it's behavior is like `ListenAndServe`.  We don't expect it to exit on failures, the same way we don't expect to have an http server exit on errors.  Anything that gets added would need coordination in a high layer of logic in kubectl.

If someone actively pursues it, I think it will be important to write down the conditions for behavior changes in kubectl and then provide a way to expose the information from the port-forwarding server back to kubectl.  I don't expect it to be a small fix, since there are many different reasons for failures.

**Comment by justinmchase** [comment]
Any suggested workarounds? This is still an issue despite this ticket being closed and I'm considering observing the stdout of the port-forward process and then detecting and text such as `Error: No such container` and then killing the process and re-creating it. I sort of hate this idea but I can't see any flags to auto re-create the port forward to a new pod nor can I see any signals from the process itself other than these error messages.

**Comment by brianpursley** [comment]
Issue has a lot of 👍s and a PR.  Reopening...

/reopen

**Comment by aojea** [comment]
@brianpursley is this happening to you with containerd (i.e. not using dockershim)?
Since we removed the socat dependencies I think this should not happen ... at least I can't reproduce it

**Comment by brianpursley** [comment]
> is this happening to you with containerd 

I was indeed still using docker.

However, I changed to use containerd now:
```
NAME           STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION           CONTAINER-RUNTIME
k8s-master     Ready    control-plane,master   32d   v1.21.2   192.168.200.11   <none>        Ubuntu 20.04.2 LTS   5.10.32-051032-generic   containerd://1.4.6
k8s-worker-1   Ready    <none>                 32d   v1.21.2   192.168.200.12   <none>        Ubuntu 20.04.2 LTS   5.10.32-051032-generic   containerd://1.4.6
k8s-worker-2   Ready    <none>                 32d   v1.21.2   192.168.200.13   <none>        Ubuntu 20.04.2 LTS   5.10.32-051032-generic   containerd://1.4.6
```

Even using containerd, I do still experience the problem of `kubectl port-forward` getting into a "zombie" state where it has not failed even though the pod was deleted.

Below is my `kubectl port-forward` output where it handled a couple of calls, but then when I deleted the pod, it logged errors but did not fail.

```
~ $ k port-forward sysinfo 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E0720 11:35:48.866369  250601 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c, uid : network namespace for sandbox "c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c" is closed
E0720 11:35:48.866866  250601 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c, uid : network namespace for sandbox "c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c" is closed
Handling connection for 8080
E0720 11:35:48.877079  250601 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c, uid : network namespace for sandbox "c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c" is closed
Handling connection for 8080
Handling connection for 8080
E0720 11:35:49.621004  250601 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c, uid : network namespace for sandbox "c13d0688619fe49a143d15792bb8ae387daeaa418ae7ab4ad78c227b67fc7a9c" is closed
E0720 11:36:19.615035  250601 portforward.go:362] error creating forwarding stream for port 8080 -> 80: Timeout occurred
Handling connection for 8080
E0720 11:36:49.619156  250601 portforward.go:340] error creating error stream for port 8080 -> 80: Timeout occurred
```

Restarting the pod still doesn't allow port-forward to resume.  However re-running the port-forward command it is able to forward ports to the restarted pod.

**Comment by aojea** [comment]
The socat replacement happened in 1.5.x  https://github.com/containerd/containerd/commit/7361cf86217573819ad210891a552060275730a6

**Comment by eddiezane** [comment]
Can confirm there's still an issue with containerd v1.5.4.

```
eddiezane@ubuntu:~$ kubectl get nodes -o wide
NAME     STATUS   ROLES                  AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
ubuntu   Ready    control-plane,master   4h14m   v1.21.3   192.168.79.60   <none>        Ubuntu 20.04.2 LTS   5.4.0-77-generic   containerd://1.5.4


eddiezane@ubuntu:~$ kubectl create deployment nginx --image nginx --replicas 3 --port 80
deployment.apps/nginx created


eddiezane@ubuntu:~$ kubectl expose deployment nginx --port 8080 --target-port 80
service/nginx exposed

eddiezane@ubuntu:~$ curl 10.101.229.137:8080
<!DOCTYPE html>
<html>
...

eddiezane@ubuntu:~$ kubectl port-forward svc/nginx 8080:8080 &
[1] 100413
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
eddiezane@ubuntu:~$ curl localhost:8080
Handling connection for 8080
<!DOCTYPE html>
<html>
...

eddiezane@ubuntu:~$ kubectl rollout restart deployment nginx
deployment.apps/nginx restarted


eddiezane@ubuntu:~$ curl localhost:8080
Handling connection for 8080
E0721 01:30:31.909924  100413 portforward.go:340] error creating error stream for port 8080 -> 80: Timeout occurred
curl: (56) Recv failure: Connection reset by peer
```

I need to have a look at the port forward code.

**Comment by aojea** [comment]
The curl is going to fail until the pod is restarted and running again, the problem here is the reconnection, have you verified the pod is running when the second curl failed?

**Comment by eddiezane** [comment]
> The curl is going to fail until the pod is restarted and running again, the problem here is the reconnection, have you verified the pod is running when the second curl failed?

Yea the pods are definitely running. If you try to hit it too early you get this immediately instead of the timeout.

```
eddiezane@ubuntu:~$ curl localhost:8080
curl: (52) Empty reply from server

Handling connection for 8080
E0721 14:23:30.904100  312202 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod a63298cf581dbd4da9b0fcb155a6f281d8d324399c13ee4448b8cc088655a312, uid : network namespace for sandbox "a63298cf581dbd4da9b0fcb155a6f281d8d324399c13ee4448b8cc088655a312" is closed
```

I can also hit the service cluster ip directly while the port forward is timing out.

```
eddiezane@ubuntu:~$ curl 10.105.192.16:8080
<!DOCTYPE html>
<html>

eddiezane@ubuntu:~$ curl localhost:8080
curl: (56) Recv failure: Connection reset by peer

Handling connection for 8080
E0721 14:26:32.721165  312202 portforward.go:362] error creating forwarding stream for port 8080 -> 80: Timeout occurred
```

**Comment by brianpursley** [comment]
Upgraded containerd to 1.5.2 and kubernetes to 1.22.0-beta and still see same behavior.

The pod is running.  Stopping and restarting the port forward will allow it to work again.

---

I'm not very familiar with how port-forwarding works on the server-side, but I wonder if there is a way for the server to close the connection if the pod terminates.  Then the client can decide what the right course of action is: Either attempt a reconnection or exit with an error code.

The [PR I opened](https://github.com/kubernetes/kubernetes/pull/103526) approaches the problem from the client-side... detect something received on the error stream and close the connection returning an error so that kubectl can decide what to do. 

I'm definitely open to other suggestions though or other PRs to fix the issue.  Perhaps the server could close the connection when it detects the pod is gone for example.

**Comment by justinmchase** [comment]
As someone who is encountering this issue, I can say if you close the connection and then kubectl either reconnects or exits the process at that point, that would totally work fine. I have an app which is basically firing up a number of port forwards all at once and if kubectl just exited I would just run it again after a delay and that would be totally fine. As it is right now, there is just no signal other than some text through stderr that i want to avoid parsing.

If kubectl automatically reconnects, so much the better.

**Comment by aojea** [comment]
let me try to put a reproducer so all of us test the same thing :smile: , there are many moving parts that can affect this (a loadbalancer in front of the apiserver per example) but we'll figure it out, ideally port-forward should reconnect without having to exit the client, let's aim for that

(I'm testing this with kind:)
1. Create pod `kubectl run test --image=httpd`
2. In one terminal enable port forwardinng `kubectl port-forward pod/test2 8888:80                                  │<html><body><h1>It works!</h1></body></html>
Forwarding from 127.0.0.1:8888 -> 80                                                         │[aojea@juanan ~]$ curl localhost:8888
Forwarding from [::1]:8888 -> 80

**Comment by justinmchase** [comment]
From that output it looks like its establishing a new connection to the new pod but keeping the old dead one as well and round-robin-ing requests, sometimes to the dead connection and sometimes to the new pod.

**Comment by rthamrin** [comment]
I still not found the best solution for this problem

**Comment by saerdnaer** [comment]
@[rthamrin](https://github.com/rthamrin) upgrade  `kubectl` to v1.23 or higher, c.f. https://github.com/kubernetes/kubernetes/pull/103526

**Comment by michalschott** [comment]
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

still does not work properly:
```
E0704 11:58:28.913863   80574 portforward.go:406] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 0273cdedf82900269c30f08db7936e813987f19487d1ccdb67533c51fd1466e7, uid : failed to find sandbox "0273cdedf82900269c30f08db7936e813987f19487d1ccdb67533c51fd1466e7" in store: not found
E0704 11:58:28.915076   80574 portforward.go:234] lost connection to pod
```

never recovers

**Comment by justinmchase** [comment]
Those error messages are ok, assuming it eventually recovers. Otherwise returning a consistent error code would be helpful.

**Comment by gustaff-weldon** [comment]
@aojea @dougsland @soltysh 

This is still a problem, `kubectl port-forward` is unable to recover from lost connection but does not exit either. 
Eg. At this point it is defunct:

![Screenshot 2022-11-18 at 15 04 13](https://user-images.githubusercontent.com/411756/202727104-154cbdab-f8c5-4cae-9ee6-c616205f3f98.png)


If adding resilient port-forwarding to `kubectl` is hard, can we at least make sure it exists with non 0, so userland wrapper can be added?

**Comment by mbigras** [comment]
I ran into this issue and I would also like kubectl port-forward command with a retry option; however, to work around the issue, I put kubectl port-forward in a Bash loop like the following procedure illustrates. **Gotcha:** This workaround isn't perfect since the first request after redeploy fails.


1. Deploy an example app.

   ```
   kubectl apply --kustomize git@gist.github.com:9e12a2027374569073eb979b17994f69.git?ref=v1-1
   ```

   Your output should look like the following

   ```
   $ kubectl apply --kustomize git@gist.github.com:9e12a2027374569073eb979b17994f69.git?ref=v1-1
   configmap/blueapp-28b5f8ch92 created
   deployment.apps/blueapp created
   ```

1. Run kubectl port-forward command in a loop.

   ```
   bash <<Port-forward-with-retry
   trap exit SIGINT
   while true
   do
   	kubectl port-forward deployment/blueapp 8080:8080
   done
   Port-forward-with-retry
   ```

   **Gotcha:** Run with trap handler so SIGINT with control-c keystroke works.

1. In a different terminal, send a request to your app.

   ```
   curl blueapp.localdev.me:8080
   ```

   Your output should look like the following.

   ```
   $ curl blueapp.localdev.me:8080
   {"color":"blue","corners":"sharp","widgets":"w1,w2,w3"}
   ```

   **Note:** Consider using that localdev.me excellent domain that I learned about in the [Local testing](https://kubernetes.github.io/ingress-nginx/deploy/#local-testing) ingress-nginx documentation.


1. Redeploy your app with a configuration change.

   ```
   kubectl apply --kustomize git@gist.github.com:9e12a2027374569073eb979b17994f69.git?ref=v1-2
   ```

   Your output should look like the following.

   ```
   $ kubectl apply --kustomize git@gist.github.com:9e12a2027374569073eb979b17994f69.git?ref=v1-2
   configmap/blueapp-mg8ft62k9f created
   deployment.apps/blueapp configured
   ```

1. Send another request to your app—expected failure.

   ```
   curl blueapp.localdev.me:8080
   ```

   Your output should look like the following.

   ```
   $ curl blueapp.localdev.me:8080
   curl: (52) Empty reply from server
   ```

   **Gotcha:** This workaround isn't perfect since the first request after redeploy fails.

1. Try again—send another request to your app.

   ```
   curl blueapp.localdev.me:8080
   ```

   Your output should look like the following.

   ```
   $ curl blueapp.localdev.me:8080
   {"color":"cornflowerblue","corners":"rounded","widgets":"w2,w1,w3"}
   ```

   Notice the corners changed and the UI widgets moved around—usual cyclic change.

1. In your Bash loop terminal, shut down your loop.

   Press control-c.

   Your output should look like the following.

   ```
   $ bash <<Port-forward-with-retry
   > trap exit SIGINT
   > while true
   > do
   >     kubectl port-forward deployment/blueapp 8080:8080
   > done
   > Port-forward-with-retry
   Forwarding from 127.0.0.1:8080 -> 8080
   Forwarding from [::1]:8080 -> 8080
   Handling connection for 8080
   Handling connection for 8080
   E0207 22:27:21.406207   27015 portforward.go:406] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod bc74af06707bec5945969e9ae4b68a2165bc106a065ed121b0e8478a0b57bbe1, uid : container not running (bc74af06707bec5945969e9ae4b68a2165bc106a065ed121b0e8478a0b57bbe1)
   E0207 22:27:21.406625   27015 portforward.go:234] lost connection to pod
   Forwarding from 127.0.0.1:8080 -> 8080
   Forwarding from [::1]:8080 -> 8080
   Handling connection for 8080
   ^C
   ```

**Comment by knight42** [comment]
@mbigras Hi, you might be interested in [krelay](https://github.com/knight42/krelay), which behaves similar to `kubectl port-forward`, and also survives rolling update. The usage is simple, after installation, you could simply run

```
kubectl relay deployment/blueapp 8080:8080
```

the port forwarding still works even after you update the deployment

**Comment by justinmchase** [comment]
It would be nice if the native portforward adopted the same solution as krelay in this case :)

**Comment by c3-clement** [comment]
I ran into the same issue.
I wrote the below script to work-around the issue, with inspiration from @mbigras work around.
It works even in no-interactive mode, so it can be used in CI/CD or other automations and doesn't require to install third-party tool such as `krelay`.

```
#!/usr/bin/env bash

PID=""

exit_handler() {
    echo "Received SIGTERM or SIGINT. Shutting down..."
    kill -TERM "$PID"
    wait "$PID"
    exit 0
}

trap exit_handler SIGTERM SIGINT
echo "Starting port-forwarding for $SVC_NAME in namespace $NAMESPACE"

while true
do
    kubectl port-forward svc/"$SVC_NAME" "$HOST_PORT":"$REMOTE_PORT" -n "$NAMESPACE" &
    PID=$!
    wait $PID
done

```
