### ISSUE TITLE
kubectl apply from git remote repo

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes/kubectl#692]
Is it possible to `create` or `apply` from a remote git repository, the same way that it currently works on `kustomize build`?

**Comment by richardmarshall** [comment]
Hi @benjamin-bergia, yes a git repo url can be used anywhere the `-k` flag is supported as well as the `kustomize` sub-command.

**Comment by benjamin-bergia** [comment]
Hi @richardmarshall, thank you for your reply.

The question was, is it possible to get the same thing without using -k?
I would like to `kubectl apply -f $gitRemoteRepo`

**Comment by richardmarshall** [comment]
Ah yes, misunderstood your question. So what you'd like to see is for the `-f` flag to be extended to support handling a git url in a way similar to how a local directory is handled.

In my opinion given that `-f` already supports fetching files via HTTP adding git repo support as well would overload the flag too much. Also there isn't enough information in a URL to accurately distinguishing between a file and a git repo from the URL string alone making a single flag supporting both error prone.

An argument could be made for a new flag (similar to how the `-k` flag was added to support kustomization files) for this purpose.

/area kubectl
/sig cli
/kind feature

**Comment by kivagant-ba** [comment]
Looks also generally related to https://github.com/kubernetes/kubectl/issues/703 
So people want kubectl to support different protocols but where to stop?

**Comment by richardmarshall** [comment]
@kivagant-ba Agree.

After thinking about it more I don't think it makes sense to incorporate the git logic from kustomize into kubectl directly either as another flag or as part of `-f`.

@benjamin-bergia If this functionality would improve your workflow you could always make a kubectl plugin that wraps apply and includes the git clone logic.

**Comment by benjamin-bergia** [comment]
@richardmarshall understood.
