### ISSUE TITLE
Error text printed by kubectl when kubectl plugin takes too long

### ISSUE THREAD

**Issue by distortedsignal** [kubernetes/kubectl#700]
I'm writing a kubectl plugin, and it seems like there's a confusion in the codebase about the lifecycle of a request. If the plugin does not complete in fewer than about 30 seconds, the kubectl plugin appears to believe that a server request has timed out and prints a message like in this image:

![Screen Shot 2019-08-13 at 1 55 57 PM](https://user-images.githubusercontent.com/2186874/62976925-8f82b300-bdd2-11e9-9e69-d055a945d5c5.png)

I'm curious if I'm doing something wrong, here, or if kubectl has a malformed expectation.

I think this can be replicated with the following script and kube config file:

Script, to be `chmod +x`'d, placed on PATH, and named `kubectl-testlongplugin`:
```py
#! /usr/bin/python

import time

time.sleep(60)
```

Kubectl config file (usually found in ~/.kube/config):
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://kube-server-location:6443
  name: managed_k8s
contexts:
- context:
    cluster: managed_k8s
    user: my_user
  name: new_context
current-context: new_context
kind: Config
preferences: {}
users:
- name: my_user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - testlongplugin
      command: kubectl
      env: null

**Comment by distortedsignal** [comment]
Wait, no, don't rot!

**Comment by seans3** [comment]
Please add the version information: `kubectl version`

**Comment by distortedsignal** [comment]
I'll do ya one better and filter out the kubernetes cluster version -

```sh
>  kubectl version --client=true -o yaml
clientVersion:
  buildDate: "2019-06-20T04:49:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.6
  major: "1"
  minor: "15"
  platform: darwin/amd64
```

**Comment by distortedsignal** [comment]
Oh no! Don't let me go stale!

**Comment by distortedsignal** [comment]
Thanks @seans3!

**Comment by distortedsignal** [comment]
Just tried to repro this and could not. This might be fixed in the following version:

```
clientVersion:
  buildDate: "2019-12-13T11:51:44Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: darwin/amd64
```
