### ISSUE TITLE
kubectl version command throwing error

### ISSUE THREAD

**Issue by rameshpuruganti** [kubernetes/kubectl#701]
I have executed **kubectl version** command after installation in windows 10 pro 64 bit operating system.
Below is the output i am getting.

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: read tcp 127.0.0.1:63069->127.0.0.1:6443: wsarecv: An established connection was aborted by the software in your host machine.

Can you tell me how to resolve this issue?

**Comment by richardmarshall** [comment]
Hi @rameshpuruganti! By default `kubectl version` will output version information both for kubectl itself and the server defined in the current configuration context. If it is unable to reach the API server for some reason you will see this error.

If you want to just get the version of the client you can use: `kubectl version --client`

**Comment by rameshpuruganti** [comment]
PS C:\agent> kubectl version --client
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc19c0dec8434867e69b04a25d8ae0ff1", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}

Is this the expected output?

**Comment by rajalokan** [comment]
I'm going to answer on behalf of Richard. Yes @rameshpuruganti . This is expected. 

Typical output is 
```
kubectl version
Client Version:  XXXXXXX
Server Version: XXXXXXX
```

But since you can't reach your kube server (as per your issue), running `kubectl version` shows Client version and unable to connect for second part. So to get only client version you can run just `kubectl version --client`.

**Comment by MohamedAminebenhmida** [comment]
no update about the server issue please ? 
Is it resolved ?
