### ISSUE TITLE
All kubectl commands should have JSON output

### ISSUE THREAD

**Issue by guibirow** [kubernetes/kubectl#702]
I am opening this issue to request an improvement in the CLI in order to make it more flexible when setup CD pipelines that requires checking the output of some commands.

Commands like the below:
```kubectl rollout status -n kube-system deploy/kubernetes-dashboard```

Can generate different outputs:
- deployment "kubernetes-dashboard" successfully rolled out
- Error from server (NotFound): deployments.extensions "kubernetes-dashaboard" not found
- Waiting for deployment "xyz" rollout to finish: 1 old replicas are pending termination...

These outputs are text based and are not friendly for automation, in case I try to get the deployment like below:
```kubectl describe -n kube-system deploy/kubernetes-dashboard``` 
I also can't get the JSON output of it.

the CLI would be much more convenient if we had a JSON output for every command using the `-o JSON` option.

**Comment by christophercarney** [comment]
In this case I believe that `kubectl get` could supply all of your needs, no?

In your case `kubectl get -n kube-system deploy/kubernetes-dashboard -o json -w` should watch the status while outputting only json, but I haven't tested it personally. 

Some commands are newer than others which accounts for their varying levels of robustness. `kubectl get` is one of those more robust commands.
