### ISSUE TITLE
I want kubectl  support ftp curl.

### ISSUE THREAD

**Issue by sober-wang** [kubernetes/kubectl#703]
when I run 
```shell
kubctl apply -f ftp://myftp-user:myftp-password@myftphost.com/my-claim-yaml.yaml -n mynamespace
```
it tell me 
error: the path "ftp://myftp-user:myftp-password@myftphost.com/my-claim-yaml.yaml " does not exist

-----------------------------------
if community not have contributor to do the function ,I want do it.

**Comment by richardmarshall** [comment]
Seems to me that using curl and a pipe would solve for this need without requiring additional protocol support to be maintained in kubectl.

```shell
curl ftp://myftp-user:myftp-password@myftphost.com/my-claim-yaml.yaml | kubectl apply -f - -n mynamespace
```

/area kubectl
/sig cli
/kind feature

**Comment by seans3** [comment]
I agree with @richardmarshall. We don't want to add unneeded complexity into kubectl if there is already a way to accomplish this task. I'll leave this issue open for a couple weeks; if there is no more input, I'll close this issue then.

**Comment by sober-wang** [comment]
oh,ok . I know ,please close this issue
