### ISSUE TITLE
lock file

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubectl#708]
When using KUBECONFIG with multiple items, you can have a writeable file in your home directory and a shared config in a shared location. If the directory where the shared config file is, is not writeable, updates that should only write to the first file fail with a permission denied:
```
export KUBECONFIG=~/.kube/test.config:/shared/k8s/kube.config
kubectl config set-context --current --namespace=test
error: open /shared/k8s/kube.config.lock: permission denied
```

If the shared directory is writeable, then only the ~/.kube/test.config is updated as documented.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/32606

**Comment by kfox1111** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/67676
