### ISSUE TITLE
Print a warning when the kubectl/server version skew is outside the support window

### ISSUE THREAD

**Issue by seans3** [kubernetes/kubectl#709]
Kubernetes allows the version between the client kubectl and the APIServer to differ by +/- 1 minor releases. For example, a 1.13 kubectl will be guaranteed to work with API Servers 1.12, 1.13, and 1.14. But when this difference is greater than the +/- 1 version support window, there is no warning. This lack of notification makes it difficult to determine the actual cause of problems. So I suggest we print a warning whenever the +/- 1 support window is violated. A sophisticated user that knows he wants to interact outside the support window can pass a flag (e.g. --ignore-version-skew) to remove the warning.

**Comment by lindhe** [comment]
Is it possible to implement this from the server side? Because otherwise, only new client versions would have the warning, I assume. If the server could push a message to the client, older clients too could put up the warning...
