### ISSUE TITLE
dry-run validation on new CRD fails

### ISSUE THREAD

**Issue by yarinm** [kubernetes/kubectl#711]
Hey,

I'm trying to use : kubectl apply --validate=true --dry-run -f <file> 

The manifest file contains the CRD definition + an instance that uses the CRD. It seems that kubectl doesn't recognize that and I get the following error:

```customresourcedefinition.apiextensions.k8s.io/test.acme.k8s.io created (dry run)
error: unable to recognize "test.yaml": no matches for kind "Test" in version "test.acme.k8s.io/v1"
```

If I apply first the CRD file before running the validation it works fine. 

The example manifest file:
```---
// test.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  name: test.acme.k8s.io
  namespace: infra
spec:
  group: acme.k8s.io
  names:
    kind: Test
    plural: tests
  scope: Namespaced
  version: v1
  
---
apiVersion: test.acme.k8s.io/v1
kind: Test
metadata:
  name: my-obj
  namespace: infra
spec:
  value: some-value
```

I've also ran with --server-dry-run flag and it yielded the same results:
```
kubectl apply --validate=true --server-dry-run -f test.yaml
customresourcedefinition.apiextensions.k8s.io/tests.acme.k8s.io created (server dry run)
error: unable to recognize "test.yaml": no matches for kind "Test" in version "tests.acme.k8s.io/v1"
```

Is this a bug? intended? I'm baffled on what to do here.

**Comment by glothriel** [comment]
I also have this problem and it happens not only with dry runs.

We hacked this around, by introducing retries in a parent command that runs kubectl.

**Comment by seans3** [comment]
This is expected behavior. It is not currently possible to apply a CRD and create an instance of the custom resource in the same apply. We would like to eventually get this to work, but it does not work now. Details: the apply uses discovery to create a RESTMapper that understands API resources. This RESTMapper will not have an entry for the CRD (even after the apply), hence the failure.

Keeping closed.
