### ISSUE TITLE
Fail if missing/wrong cluster role or role ref

### ISSUE THREAD

**Issue by ezgambac** [kubernetes/kubectl#714]
When creating a role binding or cluster role binding, if you apply this operation and the role/cluster role referenced doesn't exist, the operation works anyway.

It would be nice for the operation to fail if the role referenced doesn't exist.

**Comment by ezgambac** [comment]
kubectl should validate against the cluster when creating the role binding that the things it points to actually exists, or fail if not.

**Comment by seans3** [comment]
Please see `kubectl auth reconcile`.

/sig cli
/area kubectl

Closing

/close

**Comment by ezgambac** [comment]
This doesn't solve the issue.
kubectl auth reconcile will create missing objects.
My point here is that creating new role bindings which point to non existent roles should fail, or at least have an option to force failure if the role is missing.

Let's say that you have role bobby which handles secrets, but then in the role binding you have the role ref point to bo**b**y. kubectl will happily create this without even a warning, and then when your user/service account tries to handle secrets because of the binding, it fails.

kubectl should have an option when creating this to at least warn and say: 
"Hey, just an fyi, I've noticed you are referencing this binding to boby, but that role doesn't exist in this cluster"

Otherwise, in your deployment, to verify that you have no typos or some other silly error, you have to add a check just after creating the role binding to verify if the user can perform the actions with kubectl auth can-i .
