### ISSUE TITLE
kubectl apply should work with multiple files, `kubectl apply -f *.yaml`

### ISSUE THREAD

**Issue by sallyom** [kubernetes/kubectl#718]
yes, `kubectl apply -f .` is an option but you should also be able to
`kubectl apply -f *.yaml`  

this is inconvenient:
`for f in *.yaml; do kubectl apply -f $f; done`

**Comment by seans3** [comment]
Usually, we apply multiple resources by applying either a directory or the output of kustomize (-k). I'm going to close this one. 
/close
