### ISSUE TITLE
kubectl run supports --privileged

### ISSUE THREAD

**Issue by bradmwalker** [kubernetes/kubectl#721]
The `docker run` command provides a --privileged flag to run a container in privileged mode. In v1.15 `kubectl` doesn't. A large --overrides flag can badly workaround this. Running a privileged container with -it requires something like this:

`k run wanmap-fake-wan --image=bradmwalker/wanmap -it --rm --overrides='{"spec": {"metadata": {"name": "wanmap-fake-wan"}, "template": {"spec": {"containers": [{"name": "wanmap-fake-wan", "image": "bradmwalker/wanmap", "command": ["/bin/sh"], "tty": true, "stdin": true, "securityContext": {"privileged": true} }]}}}}'`

[brad@x220 ~]$ kubectl version  
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mindw** [comment]
This is especially useful for debugging network issues via specialized images.

/remove-lifecycle rotten
