### ISSUE TITLE
Issue with kubectl describe ingress in 1.15.3

### ISSUE THREAD

**Issue by franitel** [kubernetes/kubectl#722]
After upgrade kubectl from 1.14.6 to 1.15.3 we detect that we can not describe the ingress object.
With the following kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

we can describe the ingress object
kubectl describe ingresses.extensions keycloak

but when we upgrade to 1.15.3

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

give us the following error:

kubectl describe ingresses.extensions keycloak
Error from server (NotFound): the server could not find the requested resource

using get ingresses we can read the description, but not using get description

kubectl get ingresses.extensions keycloak -o yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
flux.weave.works/antecedent: management:helmrelease/keycloak
ingress.kubernetes.io/custom-request-headers: X-Forwarded-Proto:https
creationTimestamp: "2019-09-10T14:19:03Z"
generation: 1
labels:
app: keycloak
chart: keycloak-4.0.4
heritage: Tiller
release: keycloak
.......

R,
Francisco Rodriguez

**Comment by prksu** [comment]
dup of kubernetes/kubectl#675 please see https://github.com/kubernetes/kubectl/issues/675#issuecomment-511996430
