### ISSUE TITLE
bash completion does not work for apply -k

### ISSUE THREAD

**Issue by dewe** [kubernetes/kubectl#723]
Bash completion for `kubectl apply -k` does not work. 

I would expect it to work exactly like `kubectl apply -f`, where folders and files are completed as usual.

Current workaround is to amend the output from `kubectl completion bash` by inserting a line 988:

```
flags_with_completion+=("-k")
```

**Comment by thomasheller** [comment]
@dewe 
> I would expect it to work exactly like `kubectl apply -f`
The completion for `-f` is limited to file extensions `.json`, `.yaml`, `.yml`. `-k` needs a directory, though. I've opened a corresponding PR.

**Comment by dewe** [comment]
I often use `kubectl --recursive -f <tab>` and it works nice with directories. I ask for nothing more. :-)
