### ISSUE TITLE
'couldn't find any field with path "..." in the list of objects' when there are no results

### ISSUE THREAD

**Issue by groner** [kubernetes/kubectl#724]
The `--sort-by` functionality in `kubectl get` generates this error when sorting an empty result list.

```
:; kubectl get deploy -lrelease -Lrelease --sort-by='{.metadata.labels.release}'
error: couldn't find any field with path "{.metadata.labels.release}" in the list of objects
```

I guess the error is to help detect typos in sort keys.  Assuming this is the reason, I don't think it makes sense to infer this when there are no results.

**Comment by brianpursley** [comment]
Can you do a `kubectl version` and post the output?

I tried reproducing on several client/server version combinations and did not get an error, just:
```
No resources found in default namespace.
```
