### ISSUE TITLE
Plugin not found when configuration file given on command line

### ISSUE THREAD

**Issue by datacticapertti** [kubernetes/kubectl#727]
I assume this is kubectl issue rather than krew issue. It appears that the"krew" plugin and plugins installed with krew are not found when the kubeconfig location is given with the --kubeconfig command line flag, but are found if given using an environment variable.

    $ kubectl krew list
    PLUGIN VERSION
    krew   dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a
    sniff  71102253eded8900c8f7b0d0624c65b3c77ecd6bcd28fabc9a200daac502282a
    $ kubectl --kubeconfig ~/.kube/config krew list
    Error: unknown command "krew" for "kubectl"
    Run 'kubectl --help' for usage.
    $ kubectl --kubeconfig ~/.kube/config plugin list
    The following compatible plugins are available:

    /home/pertti/.krew/bin/kubectl-krew
    /home/pertti/.krew/bin/kubectl-sniff
    $ KUBECTL=~/.kube/config kubectl krew list
    PLUGIN VERSION
    krew   dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a
    sniff  71102253eded8900c8f7b0d0624c65b3c77ecd6bcd28fabc9a200daac502282a

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0",  GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by JTarasovic** [comment]
I am seeing the same thing with context as well.

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

```
kubectl krew version
OPTION        VALUE
GitTag        v0.3.0
GitCommit     641920a
IndexURI      https://github.com/kubernetes-sigs/krew-index.git
BasePath      /Users/jason/.krew
IndexPath     /Users/jason/.krew/index
InstallPath   /Users/jason/.krew/store
DownloadPath  /var/folders/mm/qvttnlw17td63vwldt5cqqb40000gn/T/krew-downloads
BinPath       /Users/jason/.krew/bin
```

```
kubectl --context=dev krew version
Error: unknown command "krew" for "kubectl"
Run 'kubectl --help' for usage.
```

**Comment by oke-py** [comment]
https://github.com/kubernetes/kubernetes/blob/cf16e4988f58a5b816385898271e70c3346b9651/pkg/kubectl/cmd/cmd.go#L402-L404

This `if` block drops all arguments after first flag.
```
# OK
$ kubectl krew list
=> remainingArgs: [%!t(string=krew) %!t(string=list)]

# NG
$ kubectl --kubeconfig ~/.kube/config krew list
=> remainingArgs: []
```

**Comment by oke-py** [comment]
I patched kubectl as below.
```diff
diff --git a/pkg/kubectl/cmd/cmd.go b/pkg/kubectl/cmd/cmd.go
index 76c5a8f8f4..c25c8c4f89 100644
--- a/pkg/kubectl/cmd/cmd.go
+++ b/pkg/kubectl/cmd/cmd.go
@@ -398,9 +398,20 @@ func (h *DefaultPluginHandler) Execute(executablePath string, cmdArgs, environme
 func HandlePluginCommand(pluginHandler PluginHandler, cmdArgs []string) error {
        remainingArgs := []string{} // all "non-flag" arguments
 
+       flag := false
        for idx := range cmdArgs {
+               if flag {
+                       flag = false
+                       continue
+               }
+               if strings.HasPrefix(cmdArgs[idx], "--") {
+                       if !strings.Contains(cmdArgs[idx], "=") {
+                               flag = true
+                       }
+                       continue
+               }
                if strings.HasPrefix(cmdArgs[idx], "-") {
-                       break
+                       continue
                }
                remainingArgs = append(remainingArgs, strings.Replace(cmdArgs[idx], "-", "_", -1))
        }
@@ -424,7 +435,15 @@ func HandlePluginCommand(pluginHandler PluginHandler, cmdArgs []string) error {
        }
 
        // invoke cmd binary relaying the current environment and args given
-       if err := pluginHandler.Execute(foundBinaryPath, cmdArgs[len(remainingArgs):], os.Environ()); err != nil {
+       newCmdArgs := []string{}
+       for _, v := range cmdArgs {
+               for _, v2 := range remainingArgs {
+                       if v != v2 {
+                               newCmdArgs = append(newCmdArgs, v)
+                       }
+               }
+       }
+       if err := pluginHandler.Execute(foundBinaryPath, newCmdArgs, os.Environ()); err != nil {
                return err
        }
```

Then, I get an `unknown flag` error.

```
$ ./_output/local/bin/darwin/amd64/kubectl --kubeconfig ~/.kube/config krew list
F1130 21:44:44.680107   14931 root.go:58] unknown flag: --kubeconfig
```

It might be krew's bug or specification.

**Comment by ahmetb** [comment]
It’s expected this will fail:

    kubectl krew —context=..

Because plugins  don’t inherit kubectl flags. 

Similarly when you do

    kubectl —context=... plugin-name

It doesn’t surprise me this fails, too. Cobra probably rearranges flags to the end and at the end the flag isn’t going to be found again.

**Comment by ahmetb** [comment]
I just realized in latter case the plugin is not found. That appears to be a bug, yes.

**Comment by tsuna** [comment]
/reopen

Bug still exists in v1.19.1

I often create aliases like `alias fooctl kubectl --context=foo` and this bug makes it impossible to use `kubectl` plugins through the alias.
