### ISSUE TITLE
usage seems incorrect for -A claiming it sets --all-namespace=false, when it actually sets it to true

### ISSUE THREAD

**Issue by aleks-mariusz** [kubernetes/kubectl#728]
When doing a `get` on one of the api-resources, for example, `kubectl get pods`, i've learned there's a short-cut to do `--all-namespaces` the same with just `-A`

So I read the _usage_ section of `kubectl get pods --help` output to understand it better, and see that it is seems _backwards_ from the actual behavior:

```
Options:
  -A, --all-namespaces=false: If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even if specified with --namespace.
```

However, doing `kubectl get pods -A` does NOT do `--all-namespaces=false` when you specify `-A`.... it is _actually_ the equivalent of `--all-namespaces=true`

This should be corrected in the _usage_ (as well as any docs that could perhaps also be mistaken) as it's currently misleading.  In case it helps, I'm using kubectl v1.16.0 at the moment

**Comment by jameogle** [comment]
This is actually expected behaviour. If you run `kubectl get --help` you will see a list of available flags, with the default values after the equals signs.

e.g ` --show-labels=false: When printing, show all labels as the last column (default hide labels column)`

**Comment by aleks-mariusz** [comment]
Ok, so then i am just confused on how to read the usage.. I didn't realize the default values were displayed, i thought the two values were equivalent (in which case by default -A is not used).  Am i the only who have has been mislead by the way it's not only explaining the option but also showing a default (without mentioning the the default)

**Comment by jameogle** [comment]
Its pretty standard in the Go Flags package, but from memory this uses cobra- which I assume follows that precedent.

Boolean flags really only check the flag exists, which is why -A and --all-namespaces are equivalent, however, the underlying default value (which is what's referred to as 'zero value' in go) is false, so it appears as '=false'
