### ISSUE TITLE
Replace type "switch" statements with KindVisitor

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#73]
Time commitment: 5-10 hours (assuming knowledge of Go)

These sorts of type switches are brittle and break when new groups are added.

https://github.com/kubernetes/kubernetes/blob/28857a2f02ef1490bb6b0109dc1fd7fa5ecae11b/pkg/kubectl/history.go#L56

Instead we should use a common library that is updated, so we don't have to update the code in a dozen places:

https://github.com/kubernetes/kubernetes/blob/e8e617f31dfbfe2ad8ad4743cfcc17ebd6f283a1/pkg/kubectl/apps/kind_visitor.go#L27

**Comment by pwittrock** [comment]
@mahdix can you take this one?

**Comment by pwittrock** [comment]
cc @mengqiy @seans3

**Comment by mahdix** [comment]
Sure.

**Comment by smarterclayton** [comment]
These should all be behind the factory interface, not exposed to kubectl directly.  How will someone extend these for non core resources?

**Comment by pwittrock** [comment]
> These should all be behind the factory interface, not exposed to kubectl directly. How will someone extend these for non core resources?

We shouldn't be compiling into types to kubectl at all, but instead use a combination of duck-typing (via discovery API and openapi) and polymorphic subresources to support dynamic types.  This approach will provide support for CRDs and version skew in addition to other non-core types.

If we need to support compiling in non core resources before this, I expect that is complex enough to warrant its own issue to discuss what the factory interface might look like, how the factories are initialized, and how they are injected.

We should move forward with removing these without blocking on introducing support for non-core types as these are problematic for the following reasons:

- they are brittle and break when existing resources are introduced into new groups
- they have dependencies on internal kubernetes types preventing us from move code outside of k/k

**Comment by janetkuo** [comment]
> These sorts of type switches are brittle and break when new groups are added.
https://github.com/kubernetes/kubernetes/blob/28857a2f02ef1490bb6b0109dc1fd7fa5ecae11b/pkg/kubectl/history.go#L56

The type switches in `GroupKindElement.Accept()` are brittle too:
https://github.com/kubernetes/kubernetes/blob/33f873dbbee58caffcff9e7b44f174a32ec1df92/pkg/kubectl/apps/kind_visitor.go#L51-L52

ReplicaSet exists in "apps" group as well.

**Comment by janetkuo** [comment]
> These sorts of type switches are brittle and break when new groups are added.
https://github.com/kubernetes/kubernetes/blob/28857a2f02ef1490bb6b0109dc1fd7fa5ecae11b/pkg/kubectl/history.go#L56

The type switches in `GroupKindElement.Accept()` are brittle too:
https://github.com/kubernetes/kubernetes/blob/33f873dbbee58caffcff9e7b44f174a32ec1df92/pkg/kubectl/apps/kind_visitor.go#L51-L52

ReplicaSet exists in "apps" group as well.

**Comment by mahdix** [comment]
@janetkuo AS these two (`ReplicaSet` and `CronJob`) are not used in `HistoryViewerFor` method, can we do these fixes in another PR?

**Comment by janetkuo** [comment]
> AS these two (ReplicaSet and CronJob) are not used in HistoryViewerFor method, can we do these fixes in another PR?

Yes, that's a separate issue (a bug in KindVisitor, instead of replacing something with KindVisitor) and should be fixed in a another PR. 

Btw, based on the description, this issue is more general than just HistoryViewer? For example, rollback.go uses type switches too: https://github.com/kubernetes/kubernetes/blob/33f873dbbee58caffcff9e7b44f174a32ec1df92/pkg/kubectl/rollback.go#L59-L69

**Comment by mahdix** [comment]
I would suggest we keep this issue open and after PR#55257 was merged, open refactor `rollback` in a follow-up PR. Then close this issue.
