### ISSUE TITLE
status updation while watching pods 

### ISSUE THREAD

**Issue by chetanyachopra** [kubernetes/kubectl#734]
`kubectl get pods -w` 
```
NAME                   READY   STATUS              RESTARTS   AGE
foo-69d6cc756f-l5xzg   1/1     Running             0          32m
foo-69d6cc756f-mbxkm   1/1     Running             0          32m
foo-69d6cc756f-w6p7g   1/1     Running             0          32m
hitter                 0/1     ContainerCreating   0          4s
NAME                   AGE
hitter                 6s
hitter                 2m10s
hitter                 2m10s
hitter                 2m10s
```
* hitter is a temp pod created with ` kubectl run hitter --image=busybox --restart=Never --rm -it -- /bin/sh`

Really feel that status should be visible inspite of just Name and Age something like:
```
NAME        STATUS              AGE
hitter     RUNNING            6s
hitter     TERMINATING     2m10s
hitter     TERMINATED     2m10s                
```
kubectl version for reference :  `kubectl version` 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-07T14:30:40Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

discussion on this would be really appreciated  :+1:

**Comment by litaxc** [comment]
I think this affect UX badly.
Now I have to use `watch kubectl ...` to get what I want to see.

**Comment by SeanTurner026** [comment]
Came here to raise this issue. 

I frequently used `alias kgpwnt="kubectl get pods -w | grep -v Terminating"` to blacklist the status "Terminating", and it made it easier for me to see when my deploy was fully ready.

**Comment by nbkrause** [comment]
Also want to raise the issue. I am seeing this in all `v1.16.x` versions of `kubectl`. The hit to UX of not being able to use the `--watch` flag has kept me from upgrading from `v1.15.3`

**Comment by jonasdebeukelaer** [comment]
+1 

Any thoughts from the maintainers?

**Comment by val1715** [comment]
+ 1 to this issue. 

The same situation from myself. 

Kubectl Version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

I used `kubectl` a 6-7 month ago (version  1.13) and it worked fine for me, as expected:
- when run `kubectl get pod --watch` : 
  get updates in default format
- when run `kubectl get pod -o wide --watch` : 
  get updates in wide format

I don't remember exact kubectl version for that binary file.

**Comment by soltysh** [comment]
This was fixed in a recent release, you need to have a 1.17 server matching your client.
/close
