### ISSUE TITLE
patch method issue

### ISSUE THREAD

**Issue by xuil** [kubernetes/kubectl#735]
I created a deployment, exposed port as follows:

`{containerPort: 8080,name: "tcp" , protocol: "TCP"}`

then i use kubectl patch method, expected to add a new port(named udp) in ports, but got the original port replaced.

`
kubectl patch deployments test-port -p '{"spec":{"template":{"spec":{"containers":[{"name":"test-port","ports":[{"protocol":"UDP","containerPort":8080,"name":"udp"}]}]}}}}'
`

/kind bug
/area kubectl
/sig cli

**Comment by zwwhdls** [comment]
Hi,

I reproduced it and found that the original port is replaced. But I think it's because the port named "udp" uses the same port with "tcp" and apiserver think it's the same port and replaced it.

Maybe you can try to use another port when patching port in this way.

THX.
