### ISSUE TITLE
`kubectl rollout status` does not stop when a pod enters CrashLoopBackOff

### ISSUE THREAD

**Issue by FooBarWidget** [kubernetes/kubectl#738]
When I use `kubectl rollout status` to wait for a rollout (either a Deployment or a StatefulSet), I expect it to stop when the one of the pods enters a CrashLoopBackOff state. Yet this does not happen. Why is that? Wouldn't there be no more point in waiting once a pod enters CrashLoopBackOff?

For Deployments I can still kind of understand, because Deployments can have the ProgressDeadlineExceeded condition (and `kubectl rollout status` does stop when ProgressDeadlineExceeded is encountered). But StatefulSets have no such feature.

**Comment by harshavardhanc** [comment]
@FooBarWidget I'm also facing the same issue, I want to send a notification if the deployment fails. Did you find any solution?

**Comment by FooBarWidget** [comment]
@harshavardhanc I ended up writing my own `kubectl rollout status` alternative.

**Comment by harshavardhanc** [comment]
@FooBarWidget Thanks for the response, How are you doing it? Can you please share it, it would very helpful for us.

**Comment by FooBarWidget** [comment]
It's proprietary code, so I'm afraid I cannot share it. The approach is to poll all relevant Deployment, StatefulSets and Pods and to inspect their situation, until the number of Ready states have reached the goal, or until a pod enters CrashLoopBackOff or some other undesirable state that we know it's unlikely to recover from.

**Comment by harshavardhanc** [comment]
Cool, Thanks @FooBarWidget. Will try to write my own.

**Comment by span** [comment]
I also find this confusing and to add `rollout status` actually seems to exit gracefully and successfully although the pod is stuck in `CrashLoopBackOff `.

Example:

```
$ kubectl rollout -n test status deployment my-service
Waiting for deployment "my-service" rollout to finish: 0 of 1 updated replicas are available...
deployment "my-service" successfully rolled out
                                                                                                                                                                                                            
$ echo $?
0
                                                                                                                                                                                                          
$ kubectl rollout -n test status deployment my-service
Waiting for deployment "my-service" rollout to finish: 0 of 1 updated replicas are available...
```

What actually defines "...status of the latest rollout until it's done." [0] ? I expected it to be a successful rollout where pods are started, alive and ready.

[0] https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-status-em-

**Comment by mcouthon** [comment]
I definitely think this should be reopened. Is there a workaround using `kubectl wait`, perhaps?
