### ISSUE TITLE
Transition ownership of tests that tests resource specific logic to SIG apps

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#74]
Per-discussion with @erictune, SIG apps should own kubectl tests that primarily test generators and logic for specific resources.

**Comment by erictune** [comment]
I can't tell exactly what the "set" and "create" tests are.  Can we get a list or pointer to the code?

**Comment by pwittrock** [comment]
@seans3 Can you figure out which of the tests on the [sig-cli](https://k8s-testgrid.appspot.com/sig-cli#gce) test grid page are concerned with details specific to specific resource types or workloads?
