### ISSUE TITLE
Broken doc links in kubectl explain

### ISSUE THREAD

**Issue by prashcr** [kubernetes/kubectl#740]
**Repro**
`kubectl explain service`
Click https://git.k8s.io/community/contributors/devel/api-conventions.md#resources

**Actual**
Leads to a 404

**Expected**
Leads to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources

**Comment by busser** [comment]
@prashcr What version of kubectl are you using?

**Comment by christianreddington** [comment]
> @prashcr What version of kubectl are you using?

I can repro this in kubectl Version 1.13.0. The link mentioned aobve appears under the apiVersion field, but I'm also having issues with the links under kind, metadata, spec and status. 

Each link seems to point to the same base URL and markdown file, but a different section of the doc.

**Comment by soltysh** [comment]
This is fixed in recent versions.
/close

**Comment by junaid-ali** [comment]
@soltysh is this fixed? I can still see the broken links in kubectl built from master:
```
_output/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-beta.0.201+882266f67ad75f", GitCommit:"882266f67ad75f70e4688235f60e569a4d913fd6", GitTreeState:"clean", BuildDate:"2020-05-27T00:56:09Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
_output/bin/kubectl explain pod.metadata.creationTimestamp
KIND:     Pod
VERSION:  v1

FIELD:    creationTimestamp <string>

DESCRIPTION:
     CreationTimestamp is a timestamp representing the server time when this
     object was created. It is not guaranteed to be set in happens-before order
     across separate operations. Clients may not set this value. It is
     represented in RFC3339 form and is in UTC. Populated by the system.
     Read-only. Null for lists. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata

     Time is a wrapper around time.Time which supports correct marshaling to
     YAML and JSON. Wrappers are provided for many of the factory methods that
     the time package offers.
```

**Comment by junaid-ali** [comment]
@soltysh If no one is working on this, I can take this to fix.

**Comment by junaid-ali** [comment]
@soltysh please ignore my above replies, my context was configured wrong. It looks fixed.
