### ISSUE TITLE
All operations modifying resources (patch, replace) should take --resource-version

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubectl#742]
kubectl's annotate, label and scale operations take `--resource-version`. This allows to prevent a change overwriting another change that happens between reading a resource and updating it.

The same reasoning applies to all operations that update a resource, like `patch` and `replace`.

Specifically for me the use case to modify values in a configmap but while making sure there were no changes between getting the configmap and writing the changes back.

**Comment by eloyekunle** [comment]
From https://github.com/kubernetes/kubernetes/pull/87951#issuecomment-584235273 and https://github.com/kubernetes/kubernetes/pull/87951#issuecomment-583750522, `resourceVersion` can be specified as part of the manifest for `patch` and `replace` operations. Specifying them as flags could be ambiguous if the flag and manifest conflict on this.

/close

**Comment by discordianfish** [comment]
Why do we even have annotate, label and scale operations in the first place? All this can be specified in a manifest, like the resource version. I expected that is to improve the UX, same applies to `--resource-version`.

Just my 2 cent.
