### ISSUE TITLE
Setup tools for an oncall rotation for SIG cli

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#75]
We need to be able field setup a rotation for fielding support and keeping tests healthy

**Comment by seans3** [comment]
An on-call rotation has been implemented for SIG CLI. The document which describes this on-call is here: https://docs.google.com/document/d/1Z3teqtOLvjAtE-eo0G9tjyZbgNc6bMhYGZmOx76v6oM/edit#heading=h.bo8ocy72prya. Marking closed.
