### ISSUE TITLE
The documentation of kubectl wait is a bit miss-leading 

### ISSUE THREAD

**Issue by eranreshef** [kubernetes/kubectl#754]
The `--timeout` option for `kubectl wait` says: 

"The length of time to wait before giving up" .

I personally understand this as the timeout for the entire command but after experimenting with it a bit I realised that the value of this option is **per resource**. For example, if I am waiting for a set of 10 pods to be `Ready` and used `--timeout=60s`, I might end up waiting for 10 minutes before the command exits, and not just 1 minute as I assumed.

So as I see it, there are 2 possible solutions here:

1. Improve the documentation.
2. Change the implementation so that the `--timeout` value will be for the entire command duration (preferable solution in my opinion).

**Comment by zhouya0** [comment]
Actually the `kubectl wait` will do the `watch` request for every single resource and do the request one by one:
```
GET https://10.6.192.3:6443/api/v1/namespaces/default/pods?fieldSelector=metadata.name%3Dmy-busybox&resourceVersion=5594455&watch=true
```
But watch request is actually a unlimited connection so every request has a timeout(default is 30s in wait).

 So the only way to do your second solution is average time for the timeout, but seems not very good to do that.

**Comment by eranreshef** [comment]
I implemented sort of a wrapper for internal use with the following logic:

1. run `kubectl wait <resources> --timeout=0`
2. parse the output from step 1 to get a list of unready_pods
3. while (command_elapsed_time < command_timeout and len(unready_pods) > 0)
    a. run `kubectl wait <unready_pods> --timeout=0`
    b. parse the output from step 3.a to get a list of unready_pods
4. if len(unready_pods) > 0
     a. raise a command_timeout exception.

IMHO, this logic fits better to the use cases kubernetes users encounter on the day to day work but again, my opinion only. I'm not a go developer so I can't submit a PR with this logic but I would definitely like to hear more opinions about this logic.

**Comment by pjh** [comment]
/remove-lifecycle rotten

I just experienced exactly the issue described in the OP, and found it very confusing. I noticed these log messages from my e2e test:

```
+ kubectl wait --for=condition=ready pod -l prepull-test-images=e2e --timeout 30m
timed out waiting for the condition on pods/prepull-test-containers-gxjhh
timed out waiting for the condition on pods/prepull-test-containers-mqf4j
timed out waiting for the condition on pods/prepull-test-containers-r96tp
+ kubectl get pods -o wide
NAME                            READY   STATUS             RESTARTS   AGE   IP          NODE                                           NOMINATED NODE   READINESS GATES
prepull-test-containers-gxjhh   14/17   CrashLoopBackOff   85         92m   10.64.2.3   e2e-726b009feb-d872a-windows-node-group-ltb5   <none>           <none>
prepull-test-containers-mqf4j   14/17   CrashLoopBackOff   84         92m   10.64.1.3   e2e-726b009feb-d872a-windows-node-group-0qdq   <none>           <none>
prepull-test-containers-r96tp   14/17   CrashLoopBackOff   82         92m   10.64.3.3   e2e-726b009feb-d872a-windows-node-group-lc19   <none>           <none>
```

The age of the pods is 90 minutes rather than the 30 minutes I expected, because `kubectl wait` is applying the timeout to each selected pod sequentially. This is very unintuitive to me. If this default behavior can't be changed, perhaps a flag can be added to change the behavior to enforce the timeout across all selected pods/conditions.

**Comment by carlossg** [comment]
This is easy to see with a small timeout if you have more than one resource

For example with a 2s timeout it takes approximately `number of pods * 2s` to timeout, not 2s

```shell
$ kubectl get pods -l release=myrelease -o name | wc -l
      17

$ time kubectl wait --for=delete pods -l release=myrelease  --timeout=2s
timed out waiting for the condition on pods/myrelease-c66pr
timed out waiting for the condition on pods/myrelease-8tgq6
timed out waiting for the condition on pods/myrelease-gx5mn
timed out waiting for the condition on pods/myrelease-6xb9b
timed out waiting for the condition on pods/myrelease-s9cbv
timed out waiting for the condition on pods/myrelease-qtwx7
timed out waiting for the condition on pods/myrelease-qk842
timed out waiting for the condition on pods/myrelease-l6wq2
timed out waiting for the condition on pods/myrelease-zv25k
timed out waiting for the condition on pods/myrelease-diss0
timed out waiting for the condition on pods/myrelease-mh8h2
timed out waiting for the condition on pods/myrelease-cb2zn
timed out waiting for the condition on pods/myrelease-q879p
timed out waiting for the condition on pods/myrelease-skggg
timed out waiting for the condition on pods/myrelease-4mklb
timed out waiting for the condition on pods/myrelease-pn94r
timed out waiting for the condition on pods/myrelease-r2226
kubectl wait --for=delete pods -l release=myrelease --timeout=2s  0.23s user 0.09s system 0% cpu 40.267 total
```

**Comment by mgabeler-lee-6rs** [comment]
ok, fine, https://github.com/kubernetes/kubectl/issues/1219
