### ISSUE TITLE
Add support to skip TLS verification when applying yaml from a server using self-signed certificates

### ISSUE THREAD

**Issue by aaronjwood** [kubernetes/kubectl#755]
Assuming `https://mystuff.com` has a valid, self-signed certificate:
```
kubectl apply -f https://mystuff.com/mydeployment.yaml
Unable to connect to the server: x509: certificate has expired or is not yet valid
```

There's already `--insecure-skip-tls-verify` for the API server. I propose that we add a new, similar flag to support bypassing TLS verification for the deployment file URL.

**Comment by mateeyow** [comment]
Still need support to apply yaml file for self-signed certificate sites.
