### ISSUE TITLE
when i used kubectl get pods, i just could saw name and age

### ISSUE THREAD

**Issue by Martin8023** [kubernetes/kubectl#756]
when i used kubectl get pods, i just could saw name and age .
like is

NAMESPACE        NAME                                    AGE
istio-system     istio-init-crd-10-kn5ws                 9d
istio-system     istio-init-crd-11-6v54d                 9d

no status and more.what's my wrong?

**Comment by damienstanton** [comment]
Same issue. This is my env:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
on macOS 10.14.6

**Comment by Martin8023** [comment]
You can change a kubectl the version same as k8s.i think is because the version mismatched.

**Comment by damienstanton** [comment]
Right, but I would imagine users are expecting that the latest Docker desktop app (with Kubernetes enabled) will work with the latest version of kubectl.

The issues above occurred with latest Docker/kubectl on macOS.

In other words, why should users be expected to randomly try older versions of kubectl until one works?
