### ISSUE TITLE
Misleading not found output 

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubectl#757]
Currently `kubectl get $KIND` for non-namespaced resource returns an output like `No resources found in default namespace.` which I found misleading because the resource I get is not namespaced.
Example:
```bash
$ k get nodes
No resources found in default namespace.
```

```bash
$ k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

/kind bug

**Comment by zhouya0** [comment]
I can't reproduce this bug. The code is done in :

**Comment by zhouya0** [comment]
Sorry I can't reproduce this bug in my k8s 1.16.0. The code is written in:
https://github.com/kubernetes/kubernetes/blob/f23dd405f18f23dda4d00820ab20ec49852e5727/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L957
```
if mapping.Scope.Name() != meta.RESTScopeNameNamespace {
        selectorNamespace = ""
```
The `node` is scope of `root` so it won't have `namespace`.
I tested it and it works well.

**Comment by donggangcj** [comment]
The bug really exists.

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
~ kubectl get mutatingwebhookconfigurations
No resources found in default namespace.
```

The v1.1.5.1 version kubectl has no such problem.and i will resolve this bug.
```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
➜  ~ kubectl get mutatingwebhookconfigurations
No resources found.
```

**Comment by ialidzhikov** [comment]
@donggangcj, should I assign to you (i.e are you willing to work on this issue)?

**Comment by donggangcj** [comment]
I‘m very happy to fix this bug . 😀
