### ISSUE TITLE
kubectl get svc not working in AWS cloud 9 

### ISSUE THREAD

**Issue by bakkiung** [kubernetes/kubectl#759]
Hi, team,  I am using the same `aws configure` credentials for both my PC Win 10 and the AWS cloud 9.
When i ran `kubectl get svc`, it is working in win 10 but in cloud 9 it is getting the "error: You must be logged in to the server (Unauthorized)".

I tried the https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#unauthorized.

Any help will be appreciated. 

Thanks,

A

**Comment by roytmanpiccoli** [comment]
Hi @bakkiung  
Also had this problem I installed Kubectl, eksctl in IDE cloud9.
Admin manager root access credentials.
 

Already tried to change user aws and Credentials configuration, it doesn't work, when changing credential as root for another user with group access IAM the Cluster, returns message.
<not authorized to perform sts:AssumeRole on resource>

I created police for AssumeRole in the admim group, but still continues.

In short, I gave up looking for the solution and created another IDE Cloud9, and another Cluster EKS.

But now you have this problem of <The connection to the server localhost:8080 was refused - did you specify the right host or port?>

I've tried these commands but it doesn't work.

My question is it possible to only use packages that I installed? or is something missing.

Installed packages.
AWS CLI 2
KUBECTL
EKSCTL
DOCKER
DOCKER-COMPOSE

**Comment by meetreks** [comment]
Cloud9 overrides aws creds and the only way to get this workign is to enforce env variables with the right values..
I did something like this and it works
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
export AWS_DEFAULT_REGION=eu-west-1

**Comment by lakshaygaur** [comment]
same for me, why cant I access the EKS cluster from cloud9. I am able to access it outside cloud9 instances and from my local machine as well.
