### ISSUE TITLE
Move kubectl tests in common test jobs into their own jobs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#76]
The test results on the [test grid page](https://k8s-testgrid.appspot.com/sig-cli) show the results of test jobs running both non-cli tests and cli tests.  Isolate the signal for cli tests from non-cli tests, we should move the cli tests into their own test jobs.

**Comment by Lion-Wei** [comment]
If you want, I can help do this, seems lots time passed. :-)
