### ISSUE TITLE
get resource in multiple namespace

### ISSUE THREAD

**Issue by jjmengze** [kubernetes/kubectl#763]
folks , is Kubernetes CLI `kubectl` support get resource (Pod,Deployment,e.t.c.) from multiple namespace?
just like 

```bash
$kubectl get pod -n default,kube-system
No resources found in default,kube-system namespace.
```

But it seems not support now

**Comment by donggangcj** [comment]
It's  not supported currently. There are some reasons why it is not easy to implement.
1. auth.
2. mutiple api call
3. how to output

**Comment by jjmengze** [comment]
Is it possible like to query other resources (eg pod server...etc.)

```bash
$kubectl get pod,svc
NAME                         READY   STATUS             RESTARTS   AGE
pod/nginx-7db9fccd9b-6ntpx   0/1     ImagePullBackOff   3          18d

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   31d
```

**Comment by soltysh** [comment]
Based on the previous answer I'd encourage you to write a kubectl plugin, for now I'm going to close this.
/close

**Comment by btwatanabe** [comment]
@ischorr No the benefit is for larger clusters to get rid of all the system and support resources when you're looking at your app resources across multiple namespaces.

**Comment by samlaf** [comment]
As @btwatanabe mentioned, I would love to have this feature.
