### ISSUE TITLE
"kubectl version" broken: error: unable to parse the server version: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by kevinsullivan** [kubernetes/kubectl#764]
Running on AWS EC2's Marketplace GitLab VM, Ubuntu 16.

To reproduce: run "kubectl version"

Output (see last line):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
error: unable to parse the server version: invalid character '<' looking for beginning of value

Nothing much else is working either. Get similar errors trying to set up admin users per AWS tutorial on integrating GitLab with an AWS-based plain Kubernetes cluster.

**Comment by zhouya0** [comment]
Could you show what is the output of `kubectl version -v 11` ?

**Comment by juliantaylor** [comment]
that there is a `<` in the return sounds like the apiserver is returning a html result. Probably some wrongly configured loadbalancer or proxy in front the apiserver and not a kubectl issue.

Check `kubectl -v 10 version` for the curl requests and the return values you are getting from the apiserver.

**Comment by ricochet** [comment]
If you're getting a `<` back then you're likely getting html back (probably 404). The URL to the API server is likely incorrect.

**Comment by VanBantam** [comment]
I just performed a fresh install of k8 and got this exact same error.  So it's unclear to me how this can be a load balancer or proxy error.

**Comment by winkee01** [comment]
I encountered this error when I execute this command on a k8s worker node, and I didn't aware that I started a docker container (MySQL's db manager: adminer) that serves on port 8080, the coincidence is that `kubectl version` command will try to get information from `localhost:8080`, thus got this error.
