### ISSUE TITLE
Feature: Easier pod and logs access with kubectl

### ISSUE THREAD

**Issue by kaplanelad** [kubernetes/kubectl#769]
Hi :) 

I would like to work on a feature that solves a problem in my opinion. 
But, before I start working on it I want to validate that it is indeed a problem and that none else is working on it already. 

Accessing a Pod logs or SSHing into a Pod can be done with fewer steps.
In order to SSH into a pod the exact name is required and the namespace as well, something like:
1. `kubectl get pods -n <namespace>` 
2. `kubectl exec -it <pod name> ...` 

I would like to create a new flag that will allow fuzzy searching of some pod name and ssh/see logs easier. 

For example, let's say I want to SSH into a pod under the deployment name `my-deployment`. 

kubectl exec **_--like_** my

This would return an **interactive** output table that will look something like this: 

```
# NAME                              READY   STATUS    RESTARTS   AGE
1 my-app-6f598fb7bc-2kfjr           1/1     Running   0          40h
2 my-pod-6f598fb7bc-t5qrz           1/1     Running   0          40h
3 my-deployment-6f598fb7bc-zgqmp    1/1     Running   0          40h

Enter pod number: _
```
The user will choose **3** in this case and hit `Enter`. This will SSH into the pod directly. 

Same `-like` functionality can be applied for logs.

Please let me know what you think, I would love to work on that :) 

Thank 
Elad

**Comment by ricochet** [comment]
Cool idea. For something like this, it helps to first write a [plugin](https://github.com/kubernetes-sigs/krew).

This also reminds me a little bit of [kui](https://github.com/IBM/kui).

**Comment by eddiezane** [comment]
To echo @ricochet getting this started as a plugin would be the right approach if it's something you're truly interested in working on! Would be great to demo at the SIG CLI bi-weekly meeting.

There's hesitation around adding any interactivity to existing commands since it would break existing scripts and what not.

**Comment by soltysh** [comment]
Yup, plugin to start with is a good approach.
/close
