### ISSUE TITLE
Feature: kubectl command for toggling cronjob suspension

### ISSUE THREAD

**Issue by Yoni-Mantzur** [kubernetes/kubectl#771]
Abstract the patch command for toggling the suspension of a cronjob with a kubectl command. For example:
`kubectl suspend/unsuspend cronjob/<job-name>`

WDYT?

**Comment by ricochet** [comment]
A [krew plugin](https://github.com/kubernetes-sigs/krew) may be a better fit for this.

**Comment by soltysh** [comment]
Yeah, plugin is the right direction.
/close
