### ISSUE TITLE
kubectl create secret not working, but same with yaml works

### ISSUE THREAD

**Issue by gireeshp** [kubernetes/kubectl#772]
This is the same issue raised [here](https://github.com/kubernetes/website/issues/17597) in the kubernetes website repo.

I'm following [this](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service) documentation. Secret gets created when tried using yaml, but not using "kubectl create secret" command. 

Thought this is the right forum to raise this issue.

**Comment by zhouya0** [comment]
/assign
It's because when using `kubectl create secret tls nginxsecret --key /tmp/nginx.key --cert /tmp/nginx.crt`, it creats Data with :
```
Data
====
tls.crt:  1143 bytes
tls.key:  1704 bytes
```
But when using yaml we defines the data:
```
Data
====
nginx.crt:  1143 bytes
nginx.key:  1704 bytes
```
Which would lead `no such file or directory` error.

**Comment by zhouya0** [comment]
@gireeshp I hope this PR would help that :)https://github.com/kubernetes/website/pull/17810
