### ISSUE TITLE
allow configuring queries per second/qps

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubectl#773]
kubectl currently has a hardcoded query per second value of 5. This can make for example pruning resources extremely slow as it will pretty much immediately start throttling.

It would be useful when the queries per second would be configurable so one could for some usecases like apply and pruning increase it.

**Comment by gkarthiks** [comment]
@juliantaylor do you have list of commands that you wanted to propose the qps flag for?

**Comment by juliantaylor** [comment]
can't it be a generic option that applies to all subcommands like timeouts? all commands should be instantiating the same client-go instance?

If not apply is most relevant as often does a lot of api requests when applying many resources as it needs to get the resources first for patching and then create a patch. And apply --prune does even more requests.

**Comment by eddiezane** [comment]
This is roughly related to discussions we had around #866.

/priority backlog
