### ISSUE TITLE
zsh completion syntactically broken

### ISSUE THREAD

**Issue by JamesYeoman** [kubernetes/kubectl#776]
As seen in the below screenshot, the bash to zsh function is missing a closing brace. I don't know whether this is the only instance of such a syntactical error. What I do know is that this script wouldn't execute successfully.
![image](https://user-images.githubusercontent.com/21042602/69804318-2fbfe480-11d6-11ea-983e-d17474565162.png)

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
...
```

**Comment by eddiezane** [comment]
:wave: Hi @JamesYeoman!

This definitely tripped me up the first time I took a look at the generated zsh completion code.

The line in your screenshot of `<<'BASH_COMPLETION_EOF'` is what's known as a [heredoc](https://en.wikipedia.org/wiki/Here_document#Unix_shells) which is another (somewhat unintuitive  way) of writing multiline strings. If you scroll to the very bottom you'll see another `BASH_COMPLETION_EOF` followed by the closing brace you're looking for.

That whole block is stored as one big string for input to the `sed` command in your screenshot. That is the generated bash code that needs to be modified to be compatible with zsh—which is what `sed` is doing substitution on.

Does that make sense?

**Comment by JamesYeoman** [comment]
Ah yes. I see now. It's rather trippy. I don't understand though, why the completions have to be dynamic. It prevents caching because the zcompdump is based on completion files, rather than dynamically loaded completions.

**Comment by seans3** [comment]
This is how completion works with cobra--closing this.

/close
