### ISSUE TITLE
Kubectl on windows cannot create deployment objects without a full path 

### ISSUE THREAD

**Issue by CalvinHartwell** [kubernetes/kubectl#777]
Hi all, 

I recently encountered a strange issue when using kubectl on windows.  I'm setup is as follows:
- Latest Windows 10
- Kubernetes 1.6.3 (running as Microk8s)
- Kubectl for windows 1.6.3, added binary to my windows path. 

When creating objects like ReplicaSets or services, kubectl works fine. But when attempting to create Deployment objects either using kubectl apply or kubectl create deployment, I have to use the fully qualified path to the binary, otherwise it doesn't work. 

The errors I am seeing can be seen here: https://github.com/ubuntu/microk8s/issues/407

When using kubectl apply, I get the same schema errors: 
> error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta): invalid object doesn't have additional properties

...and when using kubectl create deployment, it tells me that the deployment object does not belong to the v1betav1 api. I've seen this error before when using mismatched versions of kubectl/kubernetes due to changes in the API between kubernetes versions, but they are both matched this time. 

The current workaround is to use a full qualified path in windows to the kubectl binary for creating deployments. 

Any ideas? It seems to me like the kubectl client on Windows has some buggy code around deployment objects. 

Cheers,

- Calvin

**Comment by brianpursley** [comment]
Hi @CalvinHartwell 

Can you post the output of running `kubectl version`?
