### ISSUE TITLE
kubectl run fails

### ISSUE THREAD

**Issue by jjangga0214** [kubernetes/kubectl#778]
**kubectl version**

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**error**
When I run `kubectl run`, an error occurs.

```
$ kubectl run nginx --image=nginx
WARNING: New generator "deployment/apps.v1" specified, but it isn't available. Falling back to "run/v1".
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
error: no matches for kind "Deployment" in version "apps/v1"
```

**Comment by prksu** [comment]
it seem because your cluster not really up.
please make sure your cluster is running, and if your cluster running on localhost:8080 make sure no service other than k8s cluster running on that.

i see in your edited comment
> Error from server (NotFound): the server could not find the requested resource

**Comment by jjangga0214** [comment]
@prksu What do you mean by the error message? The error message does not appear from my issue description. If you responded through email, then it might contain outdated content, which I mistakenly posted regardless of this issue.

**Comment by jjangga0214** [comment]
@prksu 

> Error from server (NotFound): the server could not find the requested resource
This was because of the cluster not running at the moment, as you pointed. 
However, as like my edited description, the error still occurs while the cluster is actually running.
I initialized the cluster by minikube by the way.

**Comment by soltysh** [comment]
With https://github.com/kubernetes/kubernetes/pull/87077 (removing kubectl run generators other than pod creation) I'm going to close this.
/close
