### ISSUE TITLE
Got "the server doesn't have a resource type "pods"" instead of "Unauthorized" or something like this when kubeconfig is not configured

### ISSUE THREAD

**Issue by emahnovets** [kubernetes/kubectl#781]
Hi.

I'm passing kubeconfig file through --kubeconfig option in my CI job. Default kubeconfig is not using. When `--kubeconfig` option forgotten in `kubectl get pods` command kubectl throws an error: `the server doesn't have a resource type "pods"` which are not so convenient and understandable.

`kubectl` version: `v1.16.3`

**Expected result:**
Some understandable error.

**Comment by eddiezane** [comment]
@emahnovets I'm unable to reproduce what you're seeing. Are you able to provide any sort of test case?

I've encountered that error before when trying to use a version of `kubectl` that is "dramatically" different from the server—i.e. client `1.16.3` server `1.13.2`.

**Comment by seans3** [comment]
Hello @emahnovets. Can you please show the entire results of the `kubectl version` command, so we can see the version of the client AND the server? If the client and server are more than one version apart, then there are no guarantees. So a 1.16 kubectl is guaranteed to work against a 1.15, 1.16, and 1.17 API Server. This may be the cause, but we don't know until you report the server version. Thanks.

**Comment by emahnovets** [comment]
Ho @seans3, @eddiezane. I can't reproduce this issue now, may be my global kubeconfig was been broken or version of client and server was been different. I think this ticket can be closed now.

**Comment by joshunger** [comment]
If you're missing a `.kube/config` you'll get this error.
