### ISSUE TITLE
documentation about dependency management is outdated

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubectl#782]
Written as below in https://github.com/kubernetes/kubectl#dependencies
> Dependencies are managed using dep. Please refer to its documentation if needed.

However, this repository has `go.mod` and `go.sum` on the root.
It's using Go Modules instead of dep, right?

**Comment by ricochet** [comment]
The `README.md` should point to the main kubernetes repo. There's an ongoing effort to move commands out of the main repo (kubectl main is in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes)).

**Comment by soltysh** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/87550
/close
