### ISSUE TITLE
docs to install from source?

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [kubernetes/kubectl#784]
The installation instructions at https://kubernetes.io/docs/tasks/tools/install-kubectl/ and in this repository do not explain how to install by compiling from source.

I tried `go get k8s.io/kubectl`, `go get k8s.io/kubernetes/kubectl` and `go get github.com/kubernetes/kubectl` but none of them are finding the sources. I also wasn't able to compile by doing a `go install` from this repository.

**Comment by DanielCalvo** [comment]
I've successfully built kubectl from source following the steps described here: https://github.com/kubernetes/kubernetes/blob/master/build/README.md

I also found the community repository to be very helpful while getting started in general: https://github.com/kubernetes/community/tree/master/contributors/devel

Hopefully those two links help you out!

**Comment by seans3** [comment]
Hi @symbiont-sam-halliday. Compiling kubectl is done within the main kubernetes (this will change when kubectl is moved out of kubernetes core). From kubernetes root, the command is simple:

`make kubectl`

It is not currently possible to build from the kubectl repository alone...so I'm going to close this.

/close
