### ISSUE TITLE
`kubectl proxy` not working with gRPC or HTTP/2(?)

### ISSUE THREAD

**Issue by Dominik-K** [kubernetes/kubectl#785]
We want to locally test calls to a gRPC `Service` with the `kubectl proxy &` command. I.e. the call goes through the [API-server proxy method](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls). As an example:

* `kubectl proxy &`
  > Starting to serve on 127.0.0.1:8001
* `curl -v localhost:8001/api/v1/namespaces/default/services/my-service:grpc/proxy/`
  > Error: 'net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"'

**Comment by brianpursley** [comment]
@Dominik-K I wonder if the problem is caused by the unescaped `:` in your url.  What if you try this instead?  (Replacing `:` with `%3A`)
```
curl -v localhost:8001/api/v1/namespaces/default/services/my-service%3Agrpc/proxy/
```

**Comment by Dominik-K** [comment]
You can `port-forward` a `Service`, as well: `kubectl port-forward service/my-service grpc`.

That's sufficient for us. Don't remember the specific use-case for using `kubectl proxy` here. Therefore closing this issue.

**Comment by ernsheong** [comment]
Leave this open? It would be useful to have `kubectl proxy` proxy to every service, regardless of HTTP or gRPC for easy debugging purposes?
