### ISSUE TITLE
kubectl should wait on the creation of the first pod for a deployment

### ISSUE THREAD

**Issue by szegedim** [kubernetes/kubectl#786]
```
root@:~# kubectl run --rm -t -i bash --image=bash
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps "bash" deleted
Error from server (NotFound): pods "" not found
root@:~# kubectl run --rm -t -i bash --image=bash
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
bash-5.0#
```
I get the following error occasionally running kubectl against an EKS cluster. I guess kubectl should wait longer for a pod to get created. I get the error in less than 1 second, when it happens.
`Error from server (NotFound): pods "" not found`

**Comment by seans3** [comment]
Hello @szegedim. Thanks for reporting this. Can you run `kubectl version` and put the result in this issue? Thanks.

**Comment by szegedim** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by soltysh** [comment]
This will become not valid any more after https://github.com/kubernetes/kubernetes/pull/87077 lands, which will remove all the generators except for one creating a pod.
/close
