### ISSUE TITLE
List of available binaries?

### ISSUE THREAD

**Issue by Zebradil** [kubernetes/kubectl#788]
Is there somewhere a list of all available binaries of `kubectl` or at least supported architectures?
From the docs, I understand that there is a kubectl binary for every version and for {linux,darwin,windows}, but which architectures, except of `amd64` (as it is shown in example: `https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/darwin/amd64/kubectl`)?

**Comment by dims** [comment]
@Zebradil see https://gcsweb.k8s.io/gcs/kubernetes-release/release/v1.17.0/ - browsable URL for the GCS buckets.
