### ISSUE TITLE
kubectl kustomize versioning

### ISSUE THREAD

**Issue by nicks** [kubernetes/kubectl#797]
**Expected behavior:**

```
kubectl kustomize version
```

should print information about the version of Kustomize templates that `kubectl kustomize` accepts

**Actual behavior**

```
kubectl kustomize version
``` 

doesn't work. 

The kubectl command only accepts kustomize version 2+, but the main kustomize repo is on version 3+. This has caused some confusion for our users, because they thought that they should be using the "new way" of preferring `kubectl kustomize` over `kustomize`

Obviously, we could work around this by keeping a map from kubectl versions to compatible kustomize versions, but it would be nice if we could get this info from `kubectl kustomize`

Relatedly, what's the plan for upgrading `kubectl` to kustomize 3?

**Comment by dlipovetsky** [comment]
Regardless of the future of `kubectl kustomize`, it would help to know which kustomize version is used.

**Comment by ricochet** [comment]
Please close and reopen this on [kustomize](https://github.com/kubernetes-sigs/kustomize/issues).

**Comment by nicks** [comment]
great filed as https://github.com/kubernetes-sigs/kustomize/issues/2142. 

though i think the change has to happen in this repo, since it's about what subcommands are registered? https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/kustomize/kustomize.go#L59

**Comment by pwittrock** [comment]
FYI: updating the FAQ with this:


https://github.com/kubernetes-sigs/kustomize/pull/2749

**Comment by MaisaDaoud** [comment]
kubectl apply -k doesnt work with kustomization.yaml with  generators and transformers. Any help

**Comment by MaisaDaoud** [comment]
update: the built in kustomize doesn't work with generators and transfomers plugins (as per mentioned in one of the open questions). The best place to install kustomize and set the path in azure is https://www.kubeflow.org/docs/other-guides/kustomize/ ... solved my issue. thanks

**Comment by KrisJohnstone** [comment]
RE: Version Upgrade for those whom stumble across this:
https://github.com/kubernetes/kubernetes/pull/98946

**Comment by eddiezane** [comment]
Looks like `kubectl kustomize --version` didn't make it in with the 1.21 changes.

@natasha41575 is this something y'all can take on?

**Comment by natasha41575** [comment]
will discuss with @monopole

**Comment by eddiezane** [comment]
Let's track this at https://github.com/kubernetes-sigs/kustomize/issues/1424

/close
