### ISSUE TITLE
Umbrella Issue: Remove kubectl dependencies on kubernetes/kubernetes

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#80]
Remove from:
- [x] pkg/kubectl/resources #81 

To Remove:
- [ ] pkg/apis #83

**Comment by shubheksha** [comment]
@seans3, are there any more changes left under this umbrella issue or were you able to get them all? If not, I can help out :smile:

**Comment by seans3** [comment]
@shubheksha Unfortunately, there are is still quite a bit to be done to complete this. I am estimating at least a couple months. Thanks for removing the frozen lifecycle.

**Comment by shubheksha** [comment]
@seans3, no problem! Are we tracking who is working on what on a file/package basis? I would love to help out but I see you've sent a few PRs already, so I was wondering what can I pick up?

**Comment by seans3** [comment]
@shubheksha Here is the spreadsheet I am using to track the dependencies which need to be removed:

https://docs.google.com/spreadsheets/d/1zTzjBBXK8SyYMr35Azb39WABvCKB4gF8rVwA4PhBuj0/edit#gid=974040405

The first rows are dependencies on an internal version of a resource. We're going to replace all dependencies on internal versions of resources with external versions of a resource. Please let me know if you can open the spreadsheet.

**Comment by soltysh** [comment]
Closing as duplicate of https://github.com/kubernetes/kubectl/issues/83
/close

**Comment by seans3** [comment]
/reopen

I think this should be re-opened, since https://github.com/kubernetes/kubectl/issues/83 only captures a subset of the items necessary for `kubectl` independence. This issue is more general and it should be used as an umbrella issue for `kubectl` independence items which are not related to internal versions of resources.

**Comment by soltysh** [comment]
@seans3 I still think we should have only, small or big I don't care. It's easier to have a single source of this. Having multiple will only lead to confusion. If need to just copy the items to the other issue.

**Comment by seans3** [comment]
/remove-lifecycle stale

...we're still working on this.

**Comment by cflewis** [comment]
How close is this? I am investigating porting a tool to remove its dependency on the k8s monorepo, and the big blocker right now is a dependency on some `kubectl` packages. It would be nice to be able to not have to do some copy-pasty hackiness :)

**Comment by seans3** [comment]
CL for first move of kubectl code into staging: https://github.com/kubernetes/kubernetes/pull/75787
