### ISSUE TITLE
CRD short-name ghosting deleted CRD

### ISSUE THREAD

**Issue by alewitt2** [kubernetes/kubectl#800]
After deleting a CRD, the short name "sticks around" at the last known corresponding version.

Kube Version: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5"
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6+IKS"
```

steps to reproduce:
1. create a CRD with some short name like `xyz`. ie. `kubectl apply -f yourCRD.yaml` -> `customresourcedefinition.apiextensions.k8s.io/your.xyz.crd.io created`
2. verify kube recognizes your resource. ie. `kubectl get xyz` -> `No resources found.`
3. delete the crd. ie. `kubectl delete crd your.xyz.crd.io` -> `customresourcedefinition.apiextensions.k8s.io "your.xyz.crd.io" deleted`
4. very crd deleted. ie. `kubectl get crd` -> `No resources found.`
5. get the short name again and see it is still looking for the crd. ie. `kubectl get xyz` -> `Error from server (NotFound): Unable to list "xyz.crd.io/v1alpha1, Resource=your": the server could not find the requested resource (get your.xyz.crd.io)`
6. WORK AROUND:
    a. do a search directly on the CRD. ie. `kubectl get your.xyz.crd.io` -> `error: the server doesn't have a resource type "your"`
    b. now getting expected result when search for short name again. ie. `kubectl get xyz` -> `error: the server doesn't have a resource type "your"`

Reason for issue: This isnt a huge problem when you dont expect use the crd anymore, but when doing version upgrades of a crd (ie. alpha1 to alpha2), kube can get confused because the short name is stuck on the old version when it should be looking for the new version.

**Comment by soltysh** [comment]
What's the time between the 3 and 5, we have a cache of resources, I can't remember of to of my head how long, but either wait for 30min or try removing `.kube/cache`.

**Comment by alewitt2** [comment]
interesting. yeah time between is only a few min. Ok, as long as the cache gets cycled at some point, then im happy.
