### ISSUE TITLE
Kubectl changes current folder to perm 600

### ISSUE THREAD

**Issue by pcarinhas** [kubernetes/kubectl#801]
Running
`gcloud container clusters get-credentials my-cluster --zone us-central1-f --project my-project`

when KUBECONFIG has a missing configuration folder (~/.kube/missingfolder) will change whatever the current folder permissions to 600. This will lock you out of your own $HOME if executed from there.

**Comment by pcarinhas** [comment]
Should provide at warning and abort if folders are missing in ~.kube.

**Comment by soltysh** [comment]
This look like a problem with gcloud, so I'm going to close it. If you can provide kubectl issue feel free to reopen.
/close
