### ISSUE TITLE
`kubectl drain node` doesn't warn nor include pods with local volumes in the eviction list

### ISSUE THREAD

**Issue by creation-shin-chan** [kubernetes/kubectl#803]
I am a newbie here. 

`kubectl drain node` doesn't warn daemonset pods nor pods with local volumes attached. 
It looks like the filter is completely ignored.  

https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain.go#L174-L182

I made a change like below and it seems fixed it. 
```
diff --git a/pkg/drain/drain.go b/pkg/drain/drain.go
index 0ade8ebe..11d89781 100644
--- a/pkg/drain/drain.go
+++ b/pkg/drain/drain.go
@@ -177,6 +177,10 @@ func (d *Helper) GetPodsForDeletion(nodeName string) (*podDeleteList, []error) {
                                // short-circuit as soon as pod is filtered out
                                // at that point, there is no reason to run pod
                                // through any additional filters
+                               pods = append(pods, podDelete{
+                                       pod:    pod,
+                                       status: status,
+                               })
                                break
                        }
                }
```

Can anyone commit the change since I don't know the manner of committing changes.

**Comment by zhouya0** [comment]
/assign 

I think the problem is to figure out why this PR is needed?
https://github.com/kubernetes/kubernetes/pull/84562

**Comment by creation-shin-chan** [comment]
@zhouya0 
That's true. The change is unnecessary but it's merged.
