### ISSUE TITLE
[feature request] delete namespaces with prompt Y/N when with `--all`

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes/kubectl#804]
Could we change the default behave when delete customized namespaces?

I knew currently namespace `default`, `kube-public`, `kube-system` are protected. 

```
master $ kubectl delete ns --all
namespace "ab" deleted
namespace "kube-node-lease" deleted
Error from server (Forbidden): namespaces "default" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-public" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-system" is forbidden: this namespace may not be deleted
```
But could we have a prompt for `Y/N` when we delete a customized namespace? Especially when with `--all` options. Otherwise, it will clean the whole cluster with one shot. 

Unless with option `--force`? 

Second, should we not delete namespaces, if there are any resources running in it? I understand to add `--ignore-daemonsets`, but should we wait for all other resources to be cleaned, then we can delete that namespace as default behave, unless with option `--force`?

**Comment by nutchalum** [comment]
`kubectl` should have a confirmation when `delete` any resources
or at least default with `--dry-run` because it is a destructive action 
this will provide a better user experience that said `User must confirm a delete action `

human error always happens, a lot

**Comment by mwmix** [comment]
@seans3 - I am going to take a swing at this solving this one assuming there is no objections to that.

**Comment by soltysh** [comment]
See https://github.com/kubernetes/kubernetes/pull/62167 for explanation why this won't happen.
/close
