### ISSUE TITLE
kubectl api-versions flag options are not clear in the help

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/kubectl#809]
### Description
is there any flag options available for the `kubectl api-versions` command?

### What happened?
When I run the `kubectl api-versions -h`, the response will be the following, which is not clear on the flags and/or options.

```sh
Print the supported API versions on the server, in the form of "group/version"

Examples:
  # Print the supported API versions
  kubectl api-versions

Usage:
  kubectl api-versions [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

### Expected
If there are any flags and/or options available, that should also been displayed along with the usage format.

### Misc:
If there is a potential fix for formatting/adding/removing the help message, I would like to work on this.

**Comment by gkarthiks** [comment]
sig/cli

**Comment by m1kola** [comment]
It doesn't looks like the command has any flags:

https://github.com/kubernetes/kubectl/blob/b5db31b03232870830b4197e9c7176130dcc733d/pkg/cmd/apiresources/apiversions.go#L53-L67

But I a gree that `[flags] [options]` in help text is a bit confusing. Not sure if it's somethin that can to be changed in kubectl itself to hide or in https://github.com/spf13/cobra.
