### ISSUE TITLE
kubectl logs command with label selector cuts logs

### ISSUE THREAD

**Issue by jasiu001** [kubernetes/kubectl#812]
**Kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**
When *kubectl logs* command is used with full pod name then all logs are displays
```
kubectl logs -n <namespace> <pod-name>
```
When the same command is used with label selector instead full pod name then logs are cut:
```
kubectl logs -n <namespace> -l <labelKey>=<labelValue>
```

**How to reproduce it**
Use above commands to any pod with longer (more than e.g. 50 lines) logs content

**Expected results**
Full logs content should be displayed or logs with labels should be not allowed (as in previous versions with `-l` and `-f` flags) and proper information should be shown.

**Comment by brianpursley** [comment]
It appears to be working as intended (see below from the help).  Whether or not this limit makes sense is up for debate I suppose.
```
--tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all
log lines otherwise 10, if a selector is provided.
```
You can use `--tail=-1` to get the behavior you want using a label.
```
kubectl logs -l <labelKey>=<labelValue> --tail=-1
```

**Comment by soltysh** [comment]
This was discussed yesterday during sig-cli bug call and we've decided that this will not be changed for now. Users have options to specify a higher limit.
/close

**Comment by kasterma** [comment]
Adding a note here for other people experiencing this issue in the same way I did; it appears that when you use 

    kubectl logs --since=4h --all-containers=true -lapp=consul --prefix

the implicit `--tail=10` is still in force, taking the minimum implied by the `--since` and `--tail` commands.  Hence the correct way to get 4 hours of logs is by

    kubectl logs --since=4h --tail=-1 --all-containers=true -lapp=consul --prefix

(added `--tail=-1`)
