### ISSUE TITLE
kubectl apply -k . --prune doesn't create generated resources

### ISSUE THREAD

**Issue by edthorne** [kubernetes/kubectl#815]
I wonder if I've found a bit of an edge case with `kustomize` composition, `apply`, and `prune`.

Environment:
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

After a bit of trial and error I was able to reproduce the problem and a possible workaround to the issue. The behavior I was experiencing was related to executing a command similar to the following:

```
kubectl apply -k . --prune --prune-whitelist=core/v1/ConfigMap -l app.kubernetes.io/name=prune-test
```

My reason for doing this is for development into a remote cluster and forcing image pulls with a fixed tag value. By constantly updating the config map contents with an ever changing value, every `apply` results in a fresh deployment.

I believe the problem is due to applying my `kustomization.yaml` on top of one or more bases. The secret generator is in my top level `kustomization.yaml` file and not in the base. I've produced the following case in a [gist](https://gist.github.com/edthorne/160842a2b45196c0ae24b9631f8dfeb0):

`temp/deployment.yaml`
`temp/kustomization.yaml`
`temp2/kustomization.yaml`

The gist names use hyphens as path separators, so adjust accordingly or use the files from
[test-case.zip](https://github.com/kubernetes/kubectl/files/4161940/test-case.zip)

If the secret generator is not declared in the base (temp folder) it will not be created when `--prune` is used. I've verified this by using `--server-dry-run` and through direct observation. The secret will be created if `--prune` is not used.

The work around is to include the secret generator in the base file and simply merge content into it from a higher level `kustomization.yaml` file. This applies to both `configMapGenerator` and `secretGenerator` usage.

**Comment by ricochet** [comment]
I wonder if this case is better handled by changing your development `kustomization.yaml` to disable hashes. 

```yaml
generatorOptions:
  disableNameSuffixHash: true
```

See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md

**Comment by edthorne** [comment]
Unfortunately, I'm relying on the suffix hash to change from build to build to force a deployment. It was the only way I could find to trigger a new deployment when nothing but the image contents changed without a corresponding change in the image tag.

**Comment by luca-esse** [comment]
Hello,
Apparently when using `--prune`, resources the don't match the label selector are ignored. (I don't know if this is the intended behavoir since the documentation is very poor for this feature).
You can verify this by removing the `commonLabels` field and checking the output of your command, it should say: "error: no objects passed to apply"

In this case, since you are specifying the `commonLabels` field in the base, every resource declared on the top level won't get the label and will be ignored.
If you move the `commonLabels` field on the top level it works as expected
