### ISSUE TITLE
Errors become uncomprehendable in plugin list

### ISSUE THREAD

**Issue by d2iq-shadowbq** [kubernetes/kubectl#817]
## Version: 

Master 
Tested 1.17.0+

## Problem:

All through the Error sequences of `plugin.go` there are no newline statements. 

This produces errors that become very difficult to read as STDERR is used interchangeably to also show verbose information. 

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/plugin/plugin.go

https://github.com/kubernetes/kubectl/blob/08c1f25495df730ea63fa7bb6b282e08ac4cd74e/pkg/cmd/plugin/plugin.go#L119

https://github.com/kubernetes/kubectl/blob/08c1f25495df730ea63fa7bb6b282e08ac4cd74e/pkg/cmd/plugin/plugin.go#L136

## Reference: 

https://github.com/kubernetes/kubernetes/commit/de015167a9c3a54d554fb05a338c685932e5dd90

https://github.com/kubernetes/kubernetes/commit/1c71a2312b8ecc7070a51b8b7f02f1c033146ab5

## Example Problematic output:

```
$> kubectl plugin list
Unable read directory "/Users/johnsmith/.cargo/bin" from your PATH: open /Users/johnsmith/.cargo/bin: no such file or directory. Skipping...Unable read directory "/Users/johnsmith/.gopath" from your PATH: open /Users/johnsmith/.gopath: no such file or directory. Skipping...Unable read directory "/Users/johnsmith/.gopath/bin" from your PATH: open /Users/johnsmith/.gopath/bin: no such file or directory. Skipping...Unable read directory "/opt/local/bin" from your PATH: open /opt/local/bin: no such file or directory. Skipping...Unable read directory "/opt/local/sbin" from your PATH: open /opt/local/sbin: no such file or directory. Skipping...The following compatible plugins are available:

/usr/local/bin/kubectl-kudo
Unable read directory "~/.dotnet/tools" from your PATH: open ~/.dotnet/tools: no such file or directory. Skipping...
```

Note the "The following compatible plugins are available:" is intermixed into the STDERR. 

The verbosity flags `-v=3` was dropped, which could of explained the errors or 'The following compatible plugins...' better.

## Current Workaround

```
kubectl -v=3 plugin list 2>/dev/null
/usr/local/bin/kubectl-kudo 
```

**Comment by brianpursley** [comment]
I saw the same thing and fixed in this pending PR...
https://github.com/kubernetes/kubernetes/pull/87633

**Comment by d2iq-shadowbq** [comment]
resolved by merge.
