### ISSUE TITLE
kubectl get should return non-zero value if not found

### ISSUE THREAD

**Issue by shahar-klein** [kubernetes/kubectl#821]
kubectl get returns 0 weather it finds or doesn't the requested resource.

```
# kubectl -n kube-system get pod -l app=foo
No resources found in kube-system namespace.
# echo $?
0
# kubectl -n kube-system get pod -l component=etcd 
NAME             READY   STATUS    RESTARTS   AGE
etcd-sdn-test1   1/1     Running   0          23h
# echo $?
0
```

ENV: 
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zhouya0** [comment]
Because `no resources found` actually has  no error in your command and no error in the process of API request. It just returns an empty table. For example the request `api/v1/namespaces/default/pods` should not have no error even there's no pods.

**Comment by seans3** [comment]
Because this is not an error--closing.

/close

**Comment by cupdike** [comment]
It's not an error in the _command ran successfully_ sense, but it's also not *nix like either.  Observe how grep returns 1 when it can't match the text, even though it ran without error:

```
% echo 'sample text' | grep 'NA'                            
% echo $?
1
% echo 'sample text' | grep 'ample'
sample text
% echo $?                          
0
```

**Comment by cupdike** [comment]
Just to make this more obvious... the inconsistency is, when nothing is found, a simple `get pod` is unix-like with RC of 1.  But a filtered get unexpectedly returns an RC of 0, even when the `--ignore-not-found=false` is applied (although that is the default).
```
# Simple get on non-existing pod has RC of 1
$ kubectl get pod NULL && echo 'SURPRISE (RC == 0)' || echo 'EXPECTED (RC == 1)'
Error from server (NotFound): pods "NULL" not found
EXPECTED (RC == 1)

# Label filtered get on non-existing label surprisingly has RC of 0
$ kubectl -n kube-system get pod -l app=NULL && echo 'SURPRISE (RC == 0)' || echo 'EXPECTED (RC == 1)'                 
No resources found in kube-system namespace.
SURPRISE (RC == 0)

# Label filtered get on non-existing label cannot be fixed by explicitly applying --ignore-not-found=false (the flag default).
$ kubectl -n kube-system get pod -l app=NULL --ignore-not-found=false && echo 'SURPRISE (RC == 0)' || echo 'EXPECTED (RC == 1)'
No resources found in kube-system namespace.
SURPRISE (RC == 0)
```

**Comment by brianthelion** [comment]
Just got bit by this. A `--failhard` flag would be ideal here.

**Comment by djmcgreal-cc** [comment]
Hi. I'm surprised this is closed with no rationale to counter https://github.com/kubernetes/kubectl/issues/821#issuecomment-1062945452

**Comment by jdunhamvrtx** [comment]
Yeah - This needs to be addressed (at some point). Along with the grep example above this even fails basic HTTP status code behavior (which the excuse 'it 's not an error' supposedly falls under). If you request `kubectl get node -l app=awesomeapp -o name` and it comes back empty that's a 404. If I ask a friend to pass a can of soda and they come back with an empty cooler - that's a faux pas. In both cases the command did not return the requested info and should exit non-zero.

In the meantime - for anyone affected it works well for me to pipe to yq e.g. `| yq -e .items[].metadata.name`. I needed this for CICD to bail out correctly.

**Comment by PauloGDPeixoto** [comment]
+1
Trying to automate operations that are conditioned to the existence of resources is completely non-trivial without proper exit codes.

**Comment by GBT55** [comment]
> Yeah - This needs to be addressed (at some point). Along with the grep example above this even fails basic HTTP status code behavior (which the excuse 'it 's not an error' supposedly falls under). If you request `kubectl get node -l app=awesomeapp -o name` and it comes back empty that's a 404. If I ask a friend to pass a can of soda and they come back with an empty cooler - that's a faux pas. In both cases the command did not return the requested info and should exit non-zero.
> 
> In the meantime - for anyone affected it works well for me to pipe to yq e.g. `| yq -e .items[].metadata.name`. I needed this for CICD to bail out correctly.

Based on this I made a little script to retrieve **all** kubernetes objects within a namespace based on on whether they exist.
```bash
#!/usr/bin/env bash
# file: Scripts/kgetall.sh

for i in $(kubectl api-resources --verbs=list --namespaced -o name | grep -v "events.events.k8s.io" | grep -v "events" | sort | uniq); do 
    kubectl ${1} ${2} get ${i} -o json | jq -e '.items[].metadata.name' &> /dev/null
    if [ "$?" -eq 0 ];
    then
        echo -e " \n[FOUND] Object Name: ${i}"
        kubecolor ${1} ${2} get ${i}
    fi     
done
```
