### ISSUE TITLE
Hook into `kubectl apply/create` lifecycle

### ISSUE THREAD

**Issue by amitsaha** [kubernetes/kubectl#827]
Is it possible to "hook" into the `kubectl apply` command so that I can run a custom command/program before "apply" is invoked? The workflow i have in mind with such a hook would be:

1. User runs `kubectl apply`
2. Custom command runs
3. If (2) succeeds, (1) continues, else exits

I was hoping plugin would be the answer, but it seems like that's not the case. If this was possible, I could use (2) to run linters/custom checks, etc before I try to apply something to the cluster.

Any thoughts/suggestions appreciated in advance.

**Comment by brianpursley** [comment]
Maybe you can accomplish this using the shell's `&&` operator, like this example:

Only run apply if a local directory called example exists:
```
[ -d /example ] && kubectl apply -f test.yaml
```

Or for a more complex example, if you want to hit an endpoint successfully before running apply, something like this:
```
curl http://example.com &> /dev/null && kubectl apply -f test.yaml
```

**Comment by seans3** [comment]
In `kubectl` version >= 1.18.1 there is a pre-processing hook in `apply`. Using this path, you would have to write go code, importing the `kubectl` code (from staging), and setting the `PreProcessorFn()` in the `ApplyOptions` to run before the `apply`. The `PreProcessorFn()` is here:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L102

Contact me on Slack if you need more information.

**Comment by amitsaha** [comment]
great @seans3 - thank you. As a `kubectl` user would I have to write my custom `kubectl` client then?

**Comment by seans3** [comment]
@amitsaha Yes. For the fix that I suggested, you would have to compile your own kubectl binary.

If you want to use the command-line, then many commands (including `kubectl apply`) allow the use of `stdin` as an argument using `-`. So an example command is the following:

kustomize build <DIR> | kubectl apply -f -

You can also do the following:

cat <MANIFEST OF RESOURCES SEPARATED BY ---> | kubectl apply -f -

So as long as you can generate the resource config in a separate, previous command-line call, you can pipe it into `kubectl apply`.
