### ISSUE TITLE
Kubectl Book: Use canonical URL for krew

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes/kubectl#829]
As pointed out by @ahmetb, we should always use the canonical URL sigs.k8s.io/krew when linking to krew.

We should not use
- krew.dev which is just a privately owned redirect
- github.com/kubernetes-sigs/krew which is not the official URL either.

I messed this up a bit in https://github.com/kubernetes/kubernetes/pull/88577, so I'd like to fix it :roll_eyes:

**Comment by ahmetb** [comment]
Thank you. 🙏 got a PR?

**Comment by corneliusweig** [comment]
incoming
