### ISSUE TITLE
Update `kubectl top` error message to mention not heapster but metrics server

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubectl#831]
`kubectl top` returns an error below if metrics-server is not installed.
```
$ kubectl top pods 
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)

$ kubectl top nodes
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

It should be `Error from server (NotFound): the server could not find the requested resource (get services metrics-server`.

I'm using Kubernetes v1.17.3.

**Comment by zhouya0** [comment]
The logic is written in:
https://github.com/kubernetes/kubernetes/blob/cadd51783bd463b3fdd6c1416e596493a717fe83/staging/src/k8s.io/kubectl/pkg/cmd/top/top_pod.go#L179-L189
It will use `heapster` if no metrics-server is not provided.
Since `heapster` is not totally removed from the code, so this is not a bug, I'am right about this?

**Comment by oke-py** [comment]
> `heapster` is not totally removed from the code

Oh, I see. It might be another issue...?
heapster was deprecated in v1.11 and remove in v1.13.
https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md

**Comment by zhouya0** [comment]
If removing existing `heapster` code, there might be a lot of work to do and need to discuss with the community. I see some places like HPA still using `heapster`:
https://github.com/kubernetes/kubernetes/blob/cadd51783bd463b3fdd6c1416e596493a717fe83/cmd/kube-controller-manager/app/autoscaling.go#L70

**Comment by oke-py** [comment]
Ah, removing code might have a big impact. It might need KEP?

**Comment by zhouya0** [comment]
I found this is dup of https://github.com/kubernetes/kubernetes/pull/87498/files.

**Comment by eddiezane** [comment]
Fixed via https://github.com/kubernetes/kubernetes/pull/87498. This will ship with 1.19.

/close
