### ISSUE TITLE
Improve Error Message from Using kubectl apply with generateName

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/kubectl#835]
Version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Currently, if `kubectl apply -f` is used with `generateName` specified but no `name` specified in the metadata of an object, the resulting error will be similar to the following:

```
error: error when retrieving current configuration of:
Resource: "tekton.dev/v1alpha1, Resource=taskruns", GroupVersionKind: "tekton.dev/v1alpha1, Kind=TaskRun"
Name: "", Namespace: "default"
Object: &{...}
from server for: "taskrun.yaml": resource name may not be empty
```

The issue of the error message has come up in a number of places:
* #197 
* https://github.com/kubernetes/kubernetes/issues/44501
* https://github.com/tektoncd/pipeline/issues/2113
* https://github.com/tektoncd/pipeline/issues/2170

The solution to this error, very often, is to run `kubectl create -f` instead of using `kubectl apply`, but the error message makes it challenging for users to understand what the problem is.

I am proposing adjusting the error message in the case of using `kubectl apply` with `generateName` specified but no `name` specified to be something along the lines of `try running kubectl create -f instead`. 

I think this would provide greater clarity to users for how to use `generateName` with `kubectl` and help users address the problem on their own much better.

**Comment by zhouya0** [comment]
/assign 
I'll try to improve this. :)

**Comment by seans3** [comment]
/sig cli
/area kubectl
/kind bug
/priority P2

@zhouya0 Please feel free to modify the priority as you see fit

**Comment by zhouya0** [comment]
I tried to send a PR, I don't know if this could solve your porblem. https://github.com/kubernetes/kubernetes/pull/88998

I didn't add some message like `try running kubectl create -f instead` because you will never know what future changes for `kubectl create` and other commands.

**Comment by danielhelfand** [comment]
@zhouya0 Thanks! Added feedback to your pr.
