### ISSUE TITLE
Any official docs around Kind: List?

### ISSUE THREAD

**Issue by slmingol** [kubernetes/kubectl#837]
Couldn't find any information on how to make use of `kubectl explain list`.

```
$ kubectl explain list
error: Couldn't find resource for "/v1, Kind=List"
```

**Comment by andyfeller** [comment]
Kubernetes documentation has [examples](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-custom-objects) that use this, however there is nothing explicitly about it as @slmingol mentioned.
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: stable.example.com/v1
  kind: CronTab
  metadata:
    creationTimestamp: 2017-05-31T12:56:35Z
    generation: 1
    name: my-new-cron-object
    namespace: default
    resourceVersion: "285"
    uid: 9423255b-4600-11e7-af6a-28d2447dc82b
  spec:
    cronSpec: '* * * * */5'
    image: my-awesome-cron-image
metadata:
  resourceVersion: ""
```

**Comment by brianpursley** [comment]
I think this is because List is not actually a "resource". Each resource can have an associated list type, PodList or CronJobList, but those are not actually resources.

If you do a `kubectl api-resources` you should see a list of resources and kubectl explain should work for any of these:
```
$ kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
bindings                                                                      true         Binding
componentstatuses                 cs                                          false        ComponentStatus
configmaps                        cm                                          true         ConfigMap
endpoints                         ep                                          true         Endpoints
events                            ev                                          true         Event
limitranges                       limits                                      true         LimitRange
namespaces                        ns                                          false        Namespace
nodes                             no                                          false        Node
persistentvolumeclaims            pvc                                         true         PersistentVolumeClaim
persistentvolumes                 pv                                          false        PersistentVolume
pods                              po                                          true         Pod
podtemplates                                                                  true         PodTemplate
replicationcontrollers            rc                                          true         ReplicationController
resourcequotas                    quota                                       true         ResourceQuota
secrets                                                                       true         Secret
serviceaccounts                   sa                                          true         ServiceAccount
services                          svc                                         true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io   false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io   false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io           false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io         false        APIService
controllerrevisions                            apps                           true         ControllerRevision
daemonsets                        ds           apps                           true         DaemonSet
deployments                       deploy       apps                           true         Deployment
replicasets                       rs           apps                           true         ReplicaSet
statefulsets                      sts          apps                           true         StatefulSet
tokenreviews                                   authentication.k8s.io          false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io           true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io           false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io           false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io           false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling                    true         HorizontalPodAutoscaler
cronjobs                          cj           batch                          true         CronJob
jobs                                           batch                          true         Job
certificatesigningrequests        csr          certificates.k8s.io            false        CertificateSigningRequest
leases                                         coordination.k8s.io            true         Lease
endpointslices                                 discovery.k8s.io               true         EndpointSlice
events                            ev           events.k8s.io                  true         Event
ingresses                         ing          extensions                     true         Ingress
ingresses                         ing          networking.k8s.io              true         Ingress
networkpolicies                   netpol       networking.k8s.io              true         NetworkPolicy
runtimeclasses                                 node.k8s.io                    false        RuntimeClass
poddisruptionbudgets              pdb          policy                         true         PodDisruptionBudget
podsecuritypolicies               psp          policy                         false        PodSecurityPolicy
clusterrolebindings                            rbac.authorization.k8s.io      false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io      false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io      true         RoleBinding
roles                                          rbac.authorization.k8s.io      true         Role
priorityclasses                   pc           scheduling.k8s.io              false        PriorityClass
csidrivers                                     storage.k8s.io                 false        CSIDriver
csinodes                                       storage.k8s.io                 false        CSINode
storageclasses                    sc           storage.k8s.io                 false        StorageClass
volumeattachments                              storage.k8s.io                 false        VolumeAttachment
```

**Comment by andyfeller** [comment]
@brianpursley : While the explanation why nothing has been done before, what should be done to document this somewhere going forward?

**Comment by ph-One** [comment]
I literally just went searching for the exact same thing. Would be nice if there was _something_ mentioned about `Kind: List` in the documentation.

**Comment by soltysh** [comment]
I think Brian's explanation nicely covers the topic. 
/close

**Comment by andyfeller** [comment]
The explanation is only part of the issue; the lack of documenting it is the premise.

**Comment by sftim** [comment]
BTW I'd document this detail in https://kubernetes.io/docs/reference/using-api/api-concepts/ and have kubectl just _link_ there.

That said, if `kubectl explain list` (and also perhaps `kubectl explain watch`) could somehow let people know they are trying the wrong approach, that'd be handy.

**Comment by robozb** [comment]
> I think this is because List is not actually a "resource". Each resource can have an associated list type, PodList or CronJobList, but those are not actually resources. And each of those lists is represented in yaml by `kind: List`.
> 
> If you do a `kubectl api-resources` you should see a list of resources and kubectl explain should work for any of these:
> 
> ```
> $ kubectl api-resources
> NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
> bindings                                                                      true         Binding
> componentstatuses                 cs                                          false        ComponentStatus
> configmaps                        cm                                          true         ConfigMap
> endpoints                         ep                                          true         Endpoints
> events                            ev                                          true         Event
> limitranges                       limits                                      true         LimitRange
> namespaces                        ns                                          false        Namespace
> nodes                             no                                          false        Node
> persistentvolumeclaims            pvc                                         true         PersistentVolumeClaim
> persistentvolumes                 pv                                          false        PersistentVolume
> pods                              po                                          true         Pod
> podtemplates                                                                  true         PodTemplate
> replicationcontrollers            rc                                          true         ReplicationController
> resourcequotas                    quota                                       true         ResourceQuota
> secrets                                                                       true         Secret
> serviceaccounts                   sa                                          true         ServiceAccount
> services                          svc                                         true         Service
> mutatingwebhookconfigurations                  admissionregistration.k8s.io   false        MutatingWebhookConfiguration
> validatingwebhookconfigurations                admissionregistration.k8s.io   false        ValidatingWebhookConfiguration
> customresourcedefinitions         crd,crds     apiextensions.k8s.io           false        CustomResourceDefinition
> apiservices                                    apiregistration.k8s.io         false        APIService
> controllerrevisions                            apps                           true         ControllerRevision
> daemonsets                        ds           apps                           true         DaemonSet
> deployments                       deploy       apps                           true         Deployment
> replicasets                       rs           apps                           true         ReplicaSet
> statefulsets                      sts          apps                           true         StatefulSet
> tokenreviews                                   authentication.k8s.io          false        TokenReview
> localsubjectaccessreviews                      authorization.k8s.io           true         LocalSubjectAccessReview
> selfsubjectaccessreviews                       authorization.k8s.io           false        SelfSubjectAccessReview
> selfsubjectrulesreviews                        authorization.k8s.io           false        SelfSubjectRulesReview
> subjectaccessreviews                           authorization.k8s.io           false        SubjectAccessReview
> horizontalpodautoscalers          hpa          autoscaling                    true         HorizontalPodAutoscaler
> cronjobs                          cj           batch                          true         CronJob
> jobs                                           batch                          true         Job
> certificatesigningrequests        csr          certificates.k8s.io            false        CertificateSigningRequest
> leases                                         coordination.k8s.io            true         Lease
> endpointslices                                 discovery.k8s.io               true         EndpointSlice
> events                            ev           events.k8s.io                  true         Event
> ingresses                         ing          extensions                     true         Ingress
> ingresses                         ing          networking.k8s.io              true         Ingress
> networkpolicies                   netpol       networking.k8s.io              true         NetworkPolicy
> runtimeclasses                                 node.k8s.io                    false        RuntimeClass
> poddisruptionbudgets              pdb          policy                         true         PodDisruptionBudget
> podsecuritypolicies               psp          policy                         false        PodSecurityPolicy
> clusterrolebindings                            rbac.authorization.k8s.io      false        ClusterRoleBinding
> clusterroles                                   rbac.authorization.k8s.io      false        ClusterRole
> rolebindings                                   rbac.authorization.k8s.io      true         RoleBinding
> roles                                          rbac.authorization.k8s.io      true         Role
> priorityclasses                   pc           scheduling.k8s.io              false        PriorityClass
> csidrivers                                     storage.k8s.io                 false        CSIDriver
> csinodes                                       storage.k8s.io                 false        CSINode
> storageclasses                    sc           storage.k8s.io                 false        StorageClass
> volumeattachments                              storage.k8s.io                 false        VolumeAttachment
> ```

But this lists all the actual kind in the system?

**Comment by sebastian-philipp** [comment]
To anyone else stumbling across this. Official documentation for `kind: List` exists here: 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds : 

> Note that `kubectl` and other tools sometimes output collections of resources as `kind: List`. Keep in mind that `kind: List` is not part of the Kubernetes API; it is exposing an implementation detail from client-side code in those tools, used to handle groups of mixed resources.

**Comment by sftim** [comment]
Also see the note in https://kubernetes.io/docs/reference/using-api/api-concepts/#collections

**Comment by bodograumann** [comment]
As the jsonnet documentation refers to using `kind: List` to *apply* ressources, it would be nice to have some documentation around it in kubectl:

> Fortunately, there are three ways to configure sets of Kubernetes objects: Use YAML [stream](https://jsonnet.org/learning/getting_started.html#stream) output, [multi-file](https://jsonnet.org/learning/getting_started.html#multi) output, or a single kubectl list object. This latter option is provided by Kubernetes without requiring any special support from Jsonnet. It allows us to group several Kubernetes objects into a single object. This is the most popular option because it does not require intermediate files, and other tools don't always reliably support YAML streams.

See https://jsonnet.org/articles/kubernetes.html and also https://devops.stackexchange.com/q/18440/52694
