### ISSUE TITLE
SIG CLI Leads Tasks

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#84]
- [ ] Routinely check [maintainers tasks](https://github.com/kubernetes/kubectl/blob/master/docs/maintainers/MAINTAINERS.md)
- [ ] Identify new contributor for SIG CLI and provide them opportunities and guidance
- [x] Setup on call rotation for maintainers tasks - @shiywang is starting to look into this
- [ ] Clean up reviewers / approvers, remove old entries
  - Who has left the project in the contributor capacity?
  - Who is still part of the project, but no longer active in SIG CLI
    - Need to define "active"
  - Who is active in SIG CLI but no longer wants to be a reviewer 
- [x]  Identify and document expectations for SIG CLI members
  - Who are the "members" today?
  - Helping with maintenance tasks?
  - Periodically having an all-hands SIG CLI meeting to resolve issues and get consensus on things
  - Should we have members who are not reviewers / approvers?
- [x]  Identify process for accepting change proposals
  - How do we ensure everyone in the SIG knows a proposal is being considered
  - What is the appropriate time to discuss and respond to comments? - we should time box this so things don't drag on and fizzle out
  - Use [kep](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/0000-kep-template.md)
  - Figure out where the decision is made, and who is part of the lazy consensus quorum (members of SIG cli?)
- [ ] Report to the community meeting every quarter about SIG cli ongoings

**Comment by pwittrock** [comment]
cc @fabianofranz @adohe @mengqiy

**Comment by seans3** [comment]
* The SIG CLI charter describing specific roles within the SIG has been accepted and merged: https://github.com/kubernetes/community/blob/master/sig-cli/charter.md
* The SIG CLI charter describes the process for technical decision making: https://github.com/kubernetes/community/blob/master/sig-cli/charter.md
* The SIG CLI charter describes the process for creating new sub-projects:  https://github.com/kubernetes/community/blob/master/sig-cli/charter.md
* The SIG CLI on-call rotation has been created. It is documented here: https://docs.google.com/document/d/1Z3teqtOLvjAtE-eo0G9tjyZbgNc6bMhYGZmOx76v6oM/edit#heading=h.bo8ocy72prya

Still yet to do:

* Clean-up the current reviewers and contributors in OWNERS_ALIASES

This task will be created in another issue. Closing this.
