### ISSUE TITLE
Typo in kubectl exec Deprecation Message

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/kubectl#840]
As pointed out in this [comment](https://github.com/kubernetes/kubernetes/pull/88460/files#r387949242) in https://github.com/kubernetes/kubernetes/pull/88460, the deprecation messages for `kubectl exec [POD] [COMMAND]` shows `Use kubectl kubectl exec [POD] -- [COMMAND] instead.` for suggesting to the user how to use the command in the future. The message says `kubectl` twice, and can be changed to as follows:

* `Use kubectl exec [POD] -- [COMMAND] instead.`

The typo is mentioned twice:

https://github.com/kubernetes/kubectl/blob/9a3954bf653c874c8af6f855f2c754a8e1a44b9e/pkg/cmd/exec/exec.go#L177
 https://github.com/kubernetes/kubectl/blob/9a3954bf653c874c8af6f855f2c754a8e1a44b9e/pkg/cmd/exec/exec.go#L180

**Comment by sshishov** [comment]
This is completely misleading. Please fix this and how it could not be caught during testing?

**Comment by jglick** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/89919 AFAICT.
