### ISSUE TITLE
kubectl exec, accent or specials chars showing problem

### ISSUE THREAD

**Issue by TOTOleHero** [kubernetes/kubectl#841]
Hello, 

I'm french and i use fr_FR.UTF-8 charset encoding. I need to use accents in console mode with 'kubectl exec'. 
But I try every combination of locale code (in host or on container), I'm not able to show accent chars.

I just use 'kubectl exec -it <pod-name> bash'
```
[root@<pod-name> /]# locale       
LANG=fr_FR.UTF-8                                 
LC_CTYPE="fr_FR.UTF-8"                           
LC_NUMERIC="fr_FR.UTF-8"                         
LC_TIME="fr_FR.UTF-8"                            
LC_COLLATE="fr_FR.UTF-8"                         
LC_MONETARY="fr_FR.UTF-8"                        
LC_MESSAGES="fr_FR.UTF-8"                        
LC_PAPER="fr_FR.UTF-8"                           
LC_NAME="fr_FR.UTF-8"                            
LC_ADDRESS="fr_FR.UTF-8"                         
LC_TELEPHONE="fr_FR.UTF-8"                       
LC_MEASUREMENT="fr_FR.UTF-8"                     
LC_IDENTIFICATION="fr_FR.UTF-8"                  
LC_ALL=                                          
```
And no accent chars like éàâèç... is printed or show on console.

I use Windows with kubectl-1.17.0.exe.

What's wrong ?

Thomas

**Comment by brianpursley** [comment]
Hi Thomas.

Can you provide some steps to reproduce the problem?

I tried to reproduce it like this and was unable to:
```
$ kubectl exec nginx -- echo "éàâèç"
éàâèç
```

And using interactive exec
```
$ kubectl exec nginx -it -- /bin/sh
# echo "éàâèç"
éàâèç
```

**Comment by eddiezane** [comment]
Closing this but please reopen it if we are able to reproduce.

/close

**Comment by AntonOfTheWoods** [comment]
Same here -> I can't copy/paste anything UTF-8 (Chinese characters) but only in certain containers. Eg., the debian (and -slim) varieties that you get for Python are fine, the Bitnami images aren't, and will either print char codes (when pasting to bash) or just nothing at all (when pasting to an interactive mysql session).
