### ISSUE TITLE
Kubectl completion script doesn't support busybox

### ISSUE THREAD

**Issue by tnimni** [kubernetes/kubectl#844]
When installing kubectl completion script on BusyBox it will not work.
The reason is completion.go file line 276
Replacing the regex from 'GNU' to 'GNU\\|BusyBox' will solve the issue
This was already fixed in helm https://github.com/helm/helm/blob/master/cmd/helm/completion.go

**Comment by tnimni** [comment]
Updated the regex, as github removed '\'

**Comment by brianpursley** [comment]
Hi @wangrzneu 
Just checking if you have an update on this, or if you have any questions or need help.

**Comment by brianpursley** [comment]
It looks like this was already done in [this PR that was merged](https://github.com/kubernetes/kubernetes/pull/82181) and will be fixed in v1.19.0:

https://github.com/kubernetes/kubernetes/commit/6885919986250c33af63933d95b30d1896a8dd07

/close
