### ISSUE TITLE
Where is the documentation for "-listio"

### ISSUE THREAD

**Issue by JCzz** [kubernetes/kubectl#854]
Just wanted to look for a description of "-listio" - like kubectl get pods -listio=name

`kubectl get pods -listio=resourcename`

**Comment by brianpursley** [comment]
You're looking for the `-l` (or `--selector`) option.  [Kubectl Reference Docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get)  

Your example is a selector for pods that have a label of `istio` with a value of `resourcename` and it is equivalent to this:
```
kubectl get pods -l istio=resourcename
```

**Comment by JCzz** [comment]
Ahh cool, thanks :-)
