### ISSUE TITLE
Add AuditSink object support to explain command

### ISSUE THREAD

**Issue by developer-guy** [kubernetes/kubectl#856]
When I issued command like following :
`k explain auditsink `

it says that server does not have a resource type "auditsink".

![Screen Shot 2020-04-13 at 11 15 48](https://user-images.githubusercontent.com/16693043/79104933-44ada680-7d78-11ea-9bb8-60e5c3995787.png)

**Comment by developer-guy** [comment]
I want do develop this feature but I don’t find where to add necessary files for AuditSink

**Comment by brianpursley** [comment]
Does auditsink show in the output of `kubectl api-resources`?

**Comment by developer-guy** [comment]
nope, I think I need to enable first right I remember it
