### ISSUE TITLE
kubectl logs error message not easily handled

### ISSUE THREAD

**Issue by kyprifog** [kubernetes/kubectl#857]
When I run kubectl logs against a pod ID that doesn't exist it seems to return stdout  of "" and no stderr, and then at some point much later it returns a server error as a callback saying the pod id does not exist.  It would be more ideal if it returned an error message earlier as would be expected with a 404 status http request rather than blank stdout

**Comment by brianpursley** [comment]
Hi @kyprifog . What is your version? Can you run `kubectl version` and paste the output?

Is your cluster self-hosted or a cloud provider and if so, which one?

I ran the command locally using kubectl 1.18.0 and a kind cluster and it completed pretty much instantly:
```
$ time kubectl logs foo
Error from server (NotFound): pods "foo" not found

real	0m0.045s
user	0m0.077s
sys	0m0.000s
```

But in this case, a local kind cluster may not be comparable.

**Comment by kyprifog** [comment]
Nevermind, i was expecting the error to be surfaced back to the main thread of kubectl but this should not be the case.
