### ISSUE TITLE
Add flag k to kubectl wait

### ISSUE THREAD

**Issue by AljoschaP** [kubernetes/kubectl#858]
In order to check if the whole deployment is ready or deleted, it would be awesome if `kubectl wait` would support kustomize using the `-k` flag.

For example:
`kubectl wait --for=condition=Available --timeout=1h -k .`

Thank you very much !

**Comment by ksaritek** [comment]
@zhouya0, are you working on that issue? is it a good first start issue?

**Comment by zhouya0** [comment]
Yes. I submit this PR.https://github.com/kubernetes/kubernetes/pull/90357. But no response for a long time.

**Comment by eddiezane** [comment]
Getting this on your radar, Jeff.

/assign @monopole

**Comment by oblogic7** [comment]
I have a use case where I need to wait for a collection of rollouts where the manifests are generated through kustomize.  Would be very nice if the wait command supported such a use case.
