### ISSUE TITLE
Support generating CA and self signed certs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#86]
Time commitment: 30-60 hours (assuming knowledge of Go and crypto libraries)

We need to be able to generate CA's and self signed certificates and provide them to the Kubernetes apiserver for creating certain resources.

Currently this is done by users who need to run shell commands to generate the certificates.  Kubectl should support generating canonical certs for users.

We should write a go library that generates the CA and certs for users

1. create a library that takes the subject and days as arguments (in a go struct) and returns the 6 results in a datastructure (as []bytes)
2. add functions to the result struct to get the fields as base64 encoded []byte or string
3. write a library that can take the result and write out files
4. expose the library as a cobra command under the `kubectl alpha create certificates`

Required research:
- go crypto cert creation libraries
- cobra libraries

The library should duplicate the functionality of the following commands

```sh
openssl req -x509 -newkey rsa:2048 -keyout certificates/apiserver_ca.key -out certificates/apiserver_ca.crt -days 365 -nodes -subj /C=/ST=/L=/O=/OU=/CN=test-certificate-authority

openssl req -out certificates/apiserver.csr -new -newkey rsa:2048 -nodes -keyout certificates/apiserver.key -subj /C=/ST=/L=/O=/OU=/CN=test.default.svc

openssl x509 -req -days 365 -in certificates/apiserver.csr -CA certificates/apiserver_ca.crt -CAkey certificates/apiserver_ca.key -CAcreateserial -out certificates/apiserver.crt
```

Library should probably be in kubernetes/common

**Comment by pwittrock** [comment]
@samanthakem can you take this issue?

**Comment by samanthakem** [comment]
Yes @pwittrock. Thank you!

**Comment by pwittrock** [comment]
Excellent.  Reach out if you need help.

**Comment by pwittrock** [comment]
@samanthakem Any updates?

**Comment by samanthakem** [comment]
@pwittrock sorry for the delay, yes... in fact there are some follow up questions I should have done before. 

- Where the ```certificates``` folder would be located within the k8s context? 

- Would you like the ```kubectl alpha create certificates``` to abstract all of the three mentioned commands **at once** or would be something like ```kubectl alpha create certificates X```, ```kubectl alpha create certificates Y```, ```kubectl alpha create certificates Z``` for each?

 Lemme know if you have any questions about what I just said.

**Comment by liggitt** [comment]
what is the intended use here?

**Comment by samanthakem** [comment]
@liggitt from my understanding, it is supposed to make the process of creating certs more automatic... read [this](https://kubernetes.io/docs/concepts/cluster-administration/certificates/). Let me know if you could answer the questions I made above. Thanks in advance!

**Comment by liggitt** [comment]
I'm not sure cert-generating functionality belongs in kubectl...

**Comment by samanthakem** [comment]
@liggitt it will probably be in ```kubernetes/common``` as suggested by @pwittrock but the functionality will be used by running ```kubectl alpha create certificates```. Let's wait to see if he get back to us! :smile: What do you have in mind?

**Comment by pwittrock** [comment]
@liggitt Generating certs is necessary for installing aggregated API servers and something we need common infrastructure for.  Apimachinery might be a better spot for these, but there is precedence for creating resource config in kubectl (e.g. `kubectl create deployment`)

**Comment by pwittrock** [comment]
cc @droot

**Comment by liggitt** [comment]
> there is precedence for creating resource config in kubectl (e.g. kubectl create deployment)

API resources sure, but not non-API artifacts, right?

**Comment by pwittrock** [comment]
> API resources sure, but not non-API artifacts, right?

apiregistration.k8s.io/v1beta1/APIService is a resource right?

**Comment by liggitt** [comment]
sure... kubectl could consume a CA to produce that resource (like `create configmap --from-file=...`), but producing the CA seems out of scope

**Comment by pwittrock** [comment]
> producing the CA seems out of scope

Out of scope for the Kubernetes project or out of scope for this repo?  Why wouldn't we do this for the user?  It isn't terribly complicated for us to build but greatly improves the UX.

**Comment by pwittrock** [comment]
>  kubectl could consume a CA to produce that resource (like create configmap --from-file=...),

create configmap also supports `--from-literal=key1=config1`

**Comment by liggitt** [comment]
sure... in both cases, kubectl is not creating the value, it is consuming one provided to it

**Comment by pwittrock** [comment]
> I don't think we want a full-blown CA command subtree in kubectl proper.

Lets make it a plugin

**Comment by pwittrock** [comment]
We already need to support this for production use cases, and had to build this for installing Service Catalog.  We might as well solve it in one place, instead of making everyone come up with a bespoke solution.  Folks can always choose not to use it if it doesn't work for them.  That is the reality of developing porcelain.

**Comment by anguslees** [comment]
I encountered the need to do this just now, also while trying to install Service Catalog.  I'd **much** rather we fixed APIService to no longer require the `caBundle` inline in the actual k8s resource.  (ie: make it possible to separate the declaration of intent from the secret material, so the latter can be generated on initial install by some sort of in-cluster controller)

I mention this here, only because I suspect the _real_ fix to this issue is to rephrase the question and remove the originating need.  This of course assumes we don't have a whole list of _other_ use cases that also want CA certs (and I believe that's the case).

**Comment by nikhita** [comment]
/remove-lifecycle rotten

This still looks relevant.

**Comment by seans3** [comment]
@pwittrock Where are we on this issue now?

**Comment by shnkr** [comment]
/reopen
/remove-lifecycle rotten

What's the conclusion here? Looks like it got ignored and closed. Can we close it with proper remarks if there is no plan to add the support? 

I guess a link to a documentation would work.
