### ISSUE TITLE
kubectl drain should have an option to not cordon the node

### ISSUE THREAD

**Issue by deedf** [kubernetes/kubectl#860]
Currently, `kubectl drain` unconditionally cordons the node. 

This might not always be desirable, for instance if the operator wants to use a different type of taint than the default, using `kubectl taint` for example.

So `kubectl drain` should have a flag to leave out the cordoning.

**Comment by knight42** [comment]
I have filed a PR https://github.com/kubernetes/kubernetes/pull/91943 to solve this problem. If it got merged, we can disable cordon by `kubectl drain --disable-cordon`

**Comment by deedf** [comment]
> I have filed a PR [kubernetes/kubernetes#91943](https://github.com/kubernetes/kubernetes/pull/91943) to solve this problem. If it got merged, we can disable cordon by `kubectl drain --disable-cordon`

Awesome, thank you very much !
