### ISSUE TITLE
Job duration equals age when all pod failed

### ISSUE THREAD

**Issue by loganmzz** [kubernetes/kubectl#868]
When all pod associated to a job have failed, displayed duration is equal to age. I think it should be equal to one of:

* duration between first pod start & last pod end
* duration of last pod

**Comment by brianpursley** [comment]
Possibly related to https://github.com/kubernetes/kubernetes/pull/87564

@loganmzz Is the example below what you're talking about?

Run a job that fails.  This one runs for 30 seconds then fails
```
kubectl create job testjob --image brianpursley/error
```

Wait 15 minutes, and then run `kubectl get all`
```
NAME                READY   STATUS   RESTARTS   AGE
pod/testjob-cvmcb   0/1     Error    0          15m
pod/testjob-r8tq8   0/1     Error    0          13m
pod/testjob-t822p   0/1     Error    0          11m
pod/testjob-wgj6b   0/1     Error    0          15m
pod/testjob-xcc69   0/1     Error    0          13m
pod/testjob-xsx46   0/1     Error    0          14m
pod/testjob-zb69s   0/1     Error    0          9m12s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   25m

NAME                COMPLETIONS   DURATION   AGE
job.batch/testjob   0/1           15m        15m
```

The job retried several times, but each time failed after 30 seconds.  However the total duration of the job is showing as 15 minutes, which is actually just the age.

**Comment by loganmzz** [comment]
Yes, it is exactly that.

**Comment by loganmzz** [comment]
Is there any spec/documentation about `kubectl get` columns per resource type ?

**Comment by loganmzz** [comment]
I took a look to Job and in `.status.conditions`, you have entry with `.type` equals to `Failed` or `Complete` with associated `lastTransitionTime` that can be used instead of `completionTime` (that make non-sense for non-`Complete` job)

**Comment by eddiezane** [comment]
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/86436. Please reopen if not.

/traige duplicate
/close
