### ISSUE TITLE
Link to v1.16.5 is returning v1.16.6-beta.0

### ISSUE THREAD

**Issue by aquilesb** [kubernetes/kubectl#869]
Not sure if this is the right place to post that, but Is correct the link to version `v1.16.5` be returning the `v1.16.6-beta.0`?

`curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.5/bin/darwin/amd64/kubectl`

**Comment by soltysh** [comment]
@kubernetes/release-team-leads this sounds like a problem in the release artifacts.
I'm closing this here, since it's not a kubectl bug, per se.
/close
