### ISSUE TITLE
Support integration test framework that brings up a new control plane

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#87]
Time commitment: 30-60 hours (assuming knowledge of Go and the Ginkgo test framework)

We need a way to write integration tests for kubectl and point it at a control plane (apiserver, controller-manager, etcd, scheduler) running locally.

As a kubectl developer, when I write an integration test for kubectl, there should be a ginkgo test framework that launches a new control plane, and provides a kubeconfig to the test both as a tmp file and as a datastructure.

Framework should take the control plane binaries as flags instead of compiling them from source.

See example of a test framework that brings up the control plane [here](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/pkg/test/server.go).

[Link](https://k8s-testgrid.appspot.com/sig-cli-master#gke) to existing e2e tests

**Comment by yland** [comment]
@pwittrock Could I be assigned to this issue, I would like to work on it.

**Comment by pwittrock** [comment]
I won't be able to officially assign it to you until we add you as a collaborator, but will remove it from the open pool.  We can do this once you complete this first task.  @yland

**Comment by pwittrock** [comment]
Please reach out if you later discover that you need more direction on this task.

**Comment by pwittrock** [comment]
Also note that this task, while encapsulated, is a bit large in scope.  Feel free to tackle a smaller one for your first contribution instead.

**Comment by pwittrock** [comment]
@yland unassigning since you picked up a different task

**Comment by apelisse** [comment]
@pwittrock wrote somewhere else:

> **User story:**
> As a developer of CLIs that talk to Kubernetes APIs, I want to be able to write integration tests for my commands and libraries that run hermetically and locally in my development environment.  I want these tests to experience what happens when run against a real apiserver and control plane, but run fast and locally.
>
> **Solution:**
> Provide a test harness that will bring up the Kubernetes control plane locally (apiserver, etcd, controller-manager) locally for each tests.
>
> **Individual steps:**
> - Write a library to bring up etcd from a binary
> - Write a library to bring up apiserver from a binary, talk to the local etcd, and provide a kubeconfig file to talk to the apiserver from kubectl or client-go
> - Write a library to bring up the controller-manager from a binary and have it talk to the apiserver
> - Wrap the libraries in a test harness that will bring them up / tear them down for each test suite
> - Setup the pull / merge tests run against kubernetes/kubectl PRs so that the correct binaries are present and flags are provided to support the harness
> - Support brining up other pieces of the system such as the scheduler and faking out nodes
> - Build helper test libraries for forcing error states
>
> As a high level goal, I would like to be able to publish the framework for any Kubernetes clients to use when testing so that tools such as helm could also benefit.

The goal is to deprecate `test-cmd.sh` for the many reasons that makes it a bad thing (it's very hard to debug, it's monolithic, and much more)

**Comment by apelisse** [comment]
> As a developer of CLIs

I think it might be useful to think broader. If I work on nodes, wouldn't I need to test against these components too? Let's just say we should have composable testing components, that let's a kubernetes engineer, or even an engineer working on a kubernetes solution, test his software easily, **reliably** and quickly.

**Comment by pwittrock** [comment]
Agreed, the next big step for this is helping folks test their CRDs, which would mean some way of loading the CRD and controller from the harness as well.

**Comment by totherme** [comment]
This looks awesome. @hoegaarden and I would like to have a crack at it. We chatted with @pwittrock about it on a call, and have a good idea where to start.

cc @seans3 @mengqiy I would like to take this

**Comment by shiywang** [comment]
@totherme cool, since I can't assign to you now, assign myself as a placeholder : )

**Comment by pwittrock** [comment]
+1

**Comment by mengqiy** [comment]
This has been done. It's at https://github.com/kubernetes-sigs/testing_frameworks
