### ISSUE TITLE
Uninstall kubectl [client as well as server]

### ISSUE THREAD

**Issue by 9kranti** [kubernetes/kubectl#870]
How to uninstall kubectl (client and server) completely?

I tried `sudo rm /usr/local/bin/kubectl` 
Then installed particular version using `kubectl binary` with `curl`
`kubectl version`
Client is updated but Server showing previous installed version 
Client and Server mismatched

OS: Ubuntu 18.04

**Comment by eddiezane** [comment]
Hey @9kranti!

The server version that you are getting reported back from kubectl is actually from the Kubernetes API server. You'll need to do a upgrade of your master deployment.

/close
