### ISSUE TITLE
Patching reports success when it did not do anything

### ISSUE THREAD

**Issue by aleb** [kubernetes/kubectl#872]
I'm running the command below and it reports success but the finalizers remain unchanged ("Finalizers: [kubernetes.io/pvc-protection]"):

```
kubectl patch pvc pvc1 -p '{"metadata":{"finalizers": []}}' --type=merge
```

This happens with some service account. If I run the patch command on my laptop, it works fine. 

The patch command should report an error when it fails to apply the patch.

**Comment by brianpursley** [comment]
Just a quick thought, I haven’t had a chance to try it, but what if you use `null` or `[null]` instead of `[]`.

I wonder if it reported success because it didn’t think there was anything to do... not sure how Json merge patch interprets [], maybe the same as {} which would be to do nothing.

**Comment by brianpursley** [comment]
@aleb Sorry, I missed the part where you said it works find from your laptop.

I tested and it works fine for me too.

Can you provide your OS (e.g. `cat /etc/os-release`) and the output of `kubectl version` on the machine that doesn't work and also for your laptop?

**Comment by aleb** [comment]
The OS is "Debian GNU/Linux 9 (stretch)".

The kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aleb** [comment]
If I use the service account credentials on my laptop with **kubectl v1.18.0** I get a proper failure:

```
$ kubectl patch pvc pvc-1 -n namespace-1 -p '{"metadata":{"finalizers": []}}' --type=merge           
Error from server (Forbidden): persistentvolumeclaims "pvc-1" is forbidden: User "serviceaccount1@a-b-1.iam.gserviceaccount.com" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "namespace-1": requires one of ["container.persistentVolumeClaims.get"] permission(s).
```
