### ISSUE TITLE
Ability to run command against context parameter

### ISSUE THREAD

**Issue by ukimpact** [kubernetes/kubectl#873]
I've listed issue is stackoverflow as well:

https://stackoverflow.com/questions/61966552/gurantee-context-for-kubectl-command-kubectl-get-po-use-context-bla

If you write a simple bash script with` kubectl config use-context cluster-a` and infinite loop which does:
`kubectl get po`
and run it in terminal A, then open terminal B. In terminal B you switch context to context `cluster-b`. The command in terminal A will start polling pods from another cluster. Now imagine my script is getting pod candidates and then deleting them. If context switch happens elsewhere, my script is going to wreck havoc in wrong context. This renders local script invocation quite dangerous particularly as developer often has several terminal windows open and I can forget about long running script and go her own business switching context and checking another cluster, unaware that this very moment a catastrophe is going on :-).

I am not sure if this is intended behaviour, but even if it is, I think there should be ability to do:

`kubectl get po use-context bla`

What do you people think? 

(unless I am using some obvious already existing feature, in that case soz, target cluster with different contexts is **EKS**)

Thanks,

**Comment by brianpursley** [comment]
@ukimpact check out the `--context` option and see if it does what you want.

Example:
```
kubectl get pod --context foo
```

As you found out, there is only one "set" context at any given time and the context is actually stored in the shared configuration, so even if your kubectl's are operating in a different terminal, they will share the same context, unless you explicitly specify the context using `--context`
