### ISSUE TITLE
Connect pod through SSH protocol

### ISSUE THREAD

**Issue by FrelDX** [kubernetes/kubectl#875]
![image](https://user-images.githubusercontent.com/32826879/83704451-b3a2cf80-a644-11ea-8145-2749f83def45.png)
https://github.com/FrelDX/kube-console-on-ssh

**Comment by eddiezane** [comment]
@FrelDX thanks for sharing you neat project!

I'm going to close this issue as it doesn't appear to be something that warrants specific work to be done on kubectl.

Perhaps consider adding it to an [awesome list](https://github.com/ramitsurana/awesome-kubernetes) or turning it into a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).

/close

**Comment by FrelDX** [comment]
> @FrelDX感谢您分享整洁的项目！
> 
> 我要解决这个问题，因为它似乎并不能保证需要在kubectl上进行特定的工作。
> 
> 也许考虑将其添加到[很棒的列表中](https://github.com/ramitsurana/awesome-kubernetes)或将其变成[kubectl插件](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/)。
> 
> /关

Can you add my project to https://github.com/ramitsurana/awesome-kubernetes ？

**Comment by FrelDX** [comment]
> @FrelDX thanks for sharing you neat project!
> 
> I'm going to close this issue as it doesn't appear to be something that warrants specific work to be done on kubectl.
> 
> Perhaps consider adding it to an [awesome list](https://github.com/ramitsurana/awesome-kubernetes) or turning it into a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).
> 
> /close

Can you add my project to https://github.com/ramitsurana/awesome-kubernetes ？

**Comment by FrelDX** [comment]
> @FrelDX thanks for sharing you neat project!
> 
> I'm going to close this issue as it doesn't appear to be something that warrants specific work to be done on kubectl.
> 
> Perhaps consider adding it to an [awesome list](https://github.com/ramitsurana/awesome-kubernetes) or turning it into a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).
> 
> /close

![image](https://user-images.githubusercontent.com/32826879/88497340-a249c400-cff2-11ea-8b50-e58e56923c14.png)
