### ISSUE TITLE
Verb validation when creating role not in line with API

### ISSUE THREAD

**Issue by teoincontatto** [kubernetes/kubectl#876]
I would like to know why there is a verb validation when creating roles using `kubectl` when this validation is not enforced by the kubernetes API. In particular this is something that could be very useful in order to use kubernetes RBAC on CRDs created by users:

```shell
$ kubectl create role test --verb myaction --resource mycrd
error: invalid verb: 'myverb'
```

As mentioned [here](https://github.com/kubernetes/kubernetes/issues/87180#issuecomment-574217538) using custom verb is something user can do to extend the kubernetes RBAC system.

**Comment by eddiezane** [comment]
Hardcoded list of verbs https://github.com/kubernetes/kubectl/blob/72276045eef3534d49e1f9431ed8b07a7ddf395e/pkg/cmd/create/create_role.go#L60

Is the fix to simply remove the list? Does the server provide a way to validate the verb? Do we need to?

/kind bug 
/priority P2
/area kubectl
/area extensibility
/sig cli

**Comment by eddiezane** [comment]
@zhouya0 any thoughts here?

**Comment by eddiezane** [comment]
Discussed this on [Slack](https://kubernetes.slack.com/archives/C0EN96KUY/p1593022547361100).

Opening a PR to warn instead of error here.

/assign
