### ISSUE TITLE
Update doc for kustomize configMapGenerator

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes/kubectl#877]
Change from `env` to `envs`.

**What happened**:

Currently the doc in kubectl is using `env` in configMapGenerator.

**What you expected to happen**:

`env` has been deprecated and `envs` should be used.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by nick-jones** [comment]
I believe the docs are correct for the version of kustomize currently bundled with `kubectl`. `envs` was introduced in kustomize v3, `kubectl` currently uses v2 - see https://github.com/kubernetes/kubectl/issues/818

**Comment by Shell32-Natsu** [comment]
@nick-jones Thanks for pointing out.

**Comment by eddiezane** [comment]
These docs will come with the updated version of kustomize.

/close
