### ISSUE TITLE
C-p is bound over

### ISSUE THREAD

**Issue by her** [kubernetes/kubectl#878]
kubectl doesn't pass through `detach-keys` options

for docker `--detach-keys ctrl-q,ctrl-q` https://docs.docker.com/engine/reference/commandline/attach/#override-the-detach-sequence

This means that `C-p` is effectively broken in running containers.

**Comment by eddiezane** [comment]
Hard coded list of allowed verbs at staging/src/k8s.io/kubectl/pkg/cmd/create/create_role.go

**Comment by her** [comment]
@seans3 what type of information are you looking for? Happy to provide. 

The basic thing here is that if you shell into a running container managed by kube, readline shortcuts are bound over,  like, <C-p>. 

Are you familiar with <C-p> in bash?

**Comment by eddiezane** [comment]
@her do you have a way to reproduce what you're seeing?

I created a deployment with `nginx:latest` and exec'd in with `kubectl exec -it nginx-59d7cd6545-cw87p -- /bin/bash`. `<C-r>` and `<C-p>` are both working for me.

**Comment by her** [comment]
I beg you to try again and take a close look. `<C-p>` is actually the start of the [detach sequence](https://docs.docker.com/engine/reference/commandline/attach/#extended-description) in docker.

>you can detach from a container and leave it running using the CTRL-p CTRL-q key sequence.

@eddiezane if you run a command in your test container `$ echo 'foo'` and then issue `<C-p>`  you'll trigger the `detach sequence` _and you won't access entries in history_ **unless you issue the command again (`<C-p>`)**.

Indeed, if you issue `<C-p>` and follow that with `<C-q>` you'll detach from the container. Docker by default provides a configuration to override the `detach sequence` but **kubectl** does not honor it. [Override the detach sequence](https://docs.docker.com/engine/reference/commandline/attach/#override-the-detach-sequence)

**Comment by eddiezane** [comment]
@her ahh got it. Thanks for the explanation!

/remove-triage-needs-information
/priority backlog

**Comment by her** [comment]
Awesome thanks for taking a second look @eddiezane really appreciate that!

**Comment by her** [comment]
Does stale mean, "won't do"?
