### ISSUE TITLE
Create test library that emulates a node

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#88]
As a kubectl contributor, I want to be able to run integration tests against a control plane without real nodes.

We want to be able to support the following in kubectl tests using a real apiserver + etcd + controll-ermanager + schedule, but without any real node:
- testing`describe nodes`
  - needs to register itself as a node with the apiserver
  - needs to support multiple nodes
- testing `logs` for Pods
- testing `exec` & `attach` for Pods
- node going down

Step 1: Figure out if we can reuse what [kubemark](https://github.com/eBay/Kubernetes/blob/master/docs/devel/kubemark-guide.md) does with [hollow kubelet](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubemark/hollow_kubelet.go) which is already close to what we want, but for a very different purpose.  If we can just use theirs, lets do that.
Step 2: If we can't use kubemark, figure out how to register a fake "Node" with an apiserver using client-go and get the scheduler to schedule to it.  Make sure it periodically updates anything needed for liveness checks done by the apiserver.
Step 3: Given a clientconfig pointing at an apiserver build an interface to start a new "fake" Node with set CPU & Memory and "start it".

**Comment by shiywang** [comment]
@totherme  is your testing framework covered this part ? if not @vfreex and me would like to work on this.
