### ISSUE TITLE
`kubectl certificate deny` should have clear output

### ISSUE THREAD

**Issue by prankul88** [kubernetes/kubectl#880]
**What happened**:
I am trying to create a csr. Using the command `kubectl certificate deny <csr name>` it had an output `certificatesigningrequest.certificates.k8s.io/my-svc.my-namespace approved`. This becomes confusing at times.

**What you expected to happen**:
I would expect it to have a clear output, something like "certificatesigningrequest.certificates.k8s.io/my-svc.my-namespace denied."

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.18.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu

**Comment by knight42** [comment]
duplicated https://github.com/kubernetes/kubernetes/issues/91876#issuecomment-641533097

**Comment by prankul88** [comment]
@knight42 Thanks for pointing out
