### ISSUE TITLE
port-forward to Service always go to first pod

### ISSUE THREAD

**Issue by ibmboy19** [kubernetes/kubectl#881]
**What happened**:
   port-forward the service on local 8080 port, and access to localhost 8080 port the request always go to the first pod. 
  `kubectl port-forward services/xxx 8080:8080` 

**What you expected to happen**:
   Should be the behavior as Service

**How to reproduce it (as minimally and precisely as possible)**:
Do port-forward and access the service

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by zhouya0** [comment]
Hope this could answer your question: https://github.com/kubernetes/kubernetes/issues/15180#issuecomment-410798267

**Comment by ibmboy19** [comment]
> Hope this could answer your question: [kubernetes/kubernetes#15180 (comment)](https://github.com/kubernetes/kubernetes/issues/15180#issuecomment-410798267)

Thanks!
So, this is a TODO item.
