### ISSUE TITLE
kubectl create clusterrolebinding don't honor `--user` global flag

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubectl#885]
**What happened**:
Like this comment said:
https://github.com/kubernetes/kubernetes/pull/91372#issuecomment-633467779

**What you expected to happen**:
Find a way to honor both `--user` in clusterrolebinding and global `--user` flag.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
Is there an easy way to reproduce this?

/triage needs-information

**Comment by SaiHarshaK** [comment]
The global flag --user is used for authentication purpose, while the --user flag for clusterrolebinding (or the other sub-commands which also use --user flag) is to create ClusterRoleBinding for a user using a particular clusterRole.
For example:
```shell
$ cluster/kubectl.sh create clusterrolebinding cluster-admi --clusterrole=cluster-admin --user=user1 --user=user2 --group=group1 
clusterrolebinding.rbac.authorization.k8s.io/cluster-admi created
```
In this example, --user flag is consumed by clusterrolebinding.
But someone might also want to specify "global --user flag" for choosing a user for authentication.
