### ISSUE TITLE
kubectl error validating data: apiVersion not set (apiversion already set to v1)

### ISSUE THREAD

**Issue by Danish864** [kubernetes/kubectl#886]
while creating yaml file with kubectl i am getting error of apiversion not set. but i have already set it to v1.

kubectl create -f myfirstpod.yaml
error: error validating "myfirstpod.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false

cat myfirstpod.yaml
kind: Pod
apiversion: v1
metadata:
  name: myfirstpod
spec:
  containers:
  - name: container1
  image: aamirpinger/helloworld:latest
  ports:
  - containerPort: 80

i am using these versions
minikube version: v1.11.0
kubectl is version 1.8.4
Kubernetes 1.18.3
Docker 19.03.11

**Comment by Danish864** [comment]
I did typo in writing apiversion instead of apiVersion. Issue is resolved.

**Comment by vagdevik** [comment]
In my case, I am deploying my project on GKE via Travis. In my travis file, I am calling a shell file (deploy.sh).

In the deploy.sh file, I have written all the steps to create kubernetes resources:

```
### Deploy

# Apply k8s config
kubectl apply -f .
```
So here, I replaced kubectl apply -f . with the individual file names as follows:

```
### Deploy

# Apply k8s config
kubectl apply -f namespace.yaml
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
kubectl apply -f ingress.yaml
```
And then, the error is fixed!

**Comment by Pooja-Y-G** [comment]
Please check the NOTES.txt file under charts->template path. 
Solution: file name is case sensitive, not suppose to give as Notes.txt, caps is a must because helm will be trying to interpret that file and it tries to  generate object for kubernetes.

**Comment by anishp264** [comment]
Thanks Danish
Typos are scary

**Comment by Akshay-c-bhoyar** [comment]
in manifest file where i have to do changes that's why issue is resolve, should I have to write typo in place of apiversion
