### ISSUE TITLE
v1-18-Issue - "kubectl exec -t -i" command help comments are not correct.

### ISSUE THREAD

**Issue by manojnirania** [kubernetes/kubectl#887]
Output of below command have typo error for "Use" comments.

master $ kubectl exec -t -i webapp tail -f /log/app.log
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use **kubectl kubectl exec [POD] -- [COMMAND] instead**.

It should be 

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use **kubectl exec [POD] -- [COMMAND] instead**.

Cluster node details

master $ kubectl get node -o wide
NAME     STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
master   Ready    master   15m   **v1.18.0**   172.17.0.14   <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.6
node01   Ready    <none>   14m   **v1.18.0**   172.17.0.26   <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.6
master $

**Kubectl version =  Major:"1", Minor:"18", GitVersion:"v1.18.0"**

master $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by zhouya0** [comment]
Already fixed by https://github.com/kubernetes/kubernetes/pull/89919

**Comment by eddiezane** [comment]
Closing as this appears to already be fixed but please reopen if not.

/close
