### ISSUE TITLE
Explicit verbosity options.

### ISSUE THREAD

**Issue by sheeeng** [kubernetes/kubectl#889]
Currently, kubectl offers current option.

```console
$ kubectl options | grep verbosity
  -v, --v=0: number for the log level verbosity
```

**What would you like to be added**:

```console
$ kubectl options | grep verbosity
  -v, --verbosity=0: number for the log level verbosity
```

**Why is this needed**:

Currently, there are no distinct differences between shorthand `-v` and explicit `--v` options. By using `--verbosity` as explicit options, it is a clear and unambiguous option for kubectl.

**Comment by sheeeng** [comment]
Did I understand correctly that kubectl uses [Cobra](https://github.com/spf13/cobra#create-additional-commands) to create additional command line arguments?

**Comment by eddiezane** [comment]
I think this would need to be changed over in klog https://github.com/kubernetes/klog/blob/b5c3182dac44f851522e32c97c86ac32755c296d/klog.go#L432 as that's where this flag originates.

**Comment by eddiezane** [comment]
@sheeeng thanks for opening a PR over there.

Going to close this and let it be tracked there.

/close

**Comment by joe-devops-aptw** [comment]
Any updates?!
