### ISSUE TITLE
`kubectl logs -f` is not working correctly on 1.8

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubectl#89]
/kind bug

`kubectl logs -f ` is not working on Kubernetes 1.8. It gets stuck and only returns when the container exits.

I tested it in GKE 1.6.11 and 1.7.8 and it works there. But doesn't work on GKE 1.8.0.

Here's a simple reproduction:
1. Create a 1.8.0 or 1.8.1 cluster.
2. Run a simple busybox container and `echo "hello"`.
```
$ kubectl run -i -t busybox --image=busybox --restart=Never
If you don't see a command prompt, try pressing enter.
/ # echo "hello"
hello
```
3. In another terminal, try `kubectl logs` without `-f`. It works.
```
$ kubectl logs po/busybox
/ # echo "hello"
hello
```

4. Try `kubect logs -f` now. It gets stuck.
```
$ kubectl logs po/busybox -f
```

5. Enter more commands in the busybox terminal but there are still no logs in the `-f` terminal.
```
...
/ # echo "hello"
hello
/ # echo "hi"
hi
```

6. In another terminal try `kubectl logs` without `-f` again. That still works.
```
$ kubectl logs po/busybox
/ # echo "hello"
hello
/ # echo "hi"
hi
```
7.  Exit the busybox container:
```
...
/ # echo "hi"
hi
/ # exit
```

8. Logs would show up on the `-f` terminal now.

/sig cli

cc - @pwittrock 
https://github.com/kubernetes/kubernetes/issues/54205

**Comment by dixudx** [comment]
@mindprince I did not reproduce this.

Both v1.7 and v1.8 work well.

**Comment by mindprince** [comment]
Tried to reproduce it with @mengqiy. We were not able to reproduce it on normal GKE clusters.

But we were able to reproduce it on [GKE alpha clusters](https://cloud.google.com/container-engine/docs/alpha-clusters) (`--enable-kubernetes-alpha`). This flag enables all alpha features in Kubernetes.

**Comment by mindprince** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go lists all the alpha features we have, I wonder which one is conflicting with following logs.

**Comment by mengqiy** [comment]
@mindprince 
I tried in a version skew env:
kubectl 1.8.2 vs GKE1.7.8 work
kubectl 1.7.6 vs GKE1.8.1-gke.0 NOT work

I think this means the bug is in the apiserver. Where is your original issue in main repo?

**Comment by mindprince** [comment]
@mengqiy https://github.com/kubernetes/kubernetes/issues/54205

**Comment by vishh** [comment]
@jlewi FYI

**Comment by mengqiy** [comment]
Reopened kubernetes/kubernetes#54205.

**Comment by mindprince** [comment]
/close
This is not a kubectl issue. https://github.com/kubernetes/kubernetes/issues/54205#issuecomment-346176210
