### ISSUE TITLE
Autocomplete for container name in kubectl exec

### ISSUE THREAD

**Issue by thomas-riccardi** [kubernetes/kubectl#890]
**What would you like to be added**:
Auto-completion for container name in `kubectl exec`. 
`kubectl exec -it mypod -c [TAB]`

Currently it proposes pod names after `-c` (in fact after anything ~unknown it seems).

More generally, it should stop proposing pod names after the first pod name in cmdline, especially after `--`.

(tested with kubectl v1.18.3)

**Why is this needed**:
Autocompletion allow smooth workload exploration and usage: no need to explicitly discover with `kubectl describe pod mypod` then copy/paste the container name in `kubectl exec` cmdline.

(container name autocompletion already works great for `kubectl logs mypod`)

**Comment by rayw000** [comment]
Hi @thomas-riccardi @eddiezane 
I opened a PR https://github.com/kubernetes/kubernetes/pull/94219 to fix this issue.
Would you please review it when you're free?
Any suggestions or questions are welcomed. 🙂

**Comment by guillenotfound** [comment]
Any updates?

**Comment by marckhouzam** [comment]
This issue has a duplicate in the kubernetes repo: https://github.com/kubernetes/kubernetes/issues/94927

A fix has been proposed in https://github.com/kubernetes/kubernetes/pull/106755
