### ISSUE TITLE
Kubectl docs on Kustomize use "bases", which was deprecated a year ago

### ISSUE THREAD

**Issue by max-sixty** [kubernetes/kubectl#891]
The [kubectl docs on kustomize](https://kubectl.docs.kubernetes.io/pages/app_customization/bases_and_variants.html) prominently discuss `bases`, though this was [deprecated a year ago](https://github.com/kubernetes-sigs/kustomize/blob/661743c7e5bd8c3d9d6866b6bc0a6f0e0b0512eb/site/content/en/blog/releases/v2.1.0.md).

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/5635139/86302028-5c007100-bbbc-11ea-9b78-d9158934201e.png">

**Comment by eddiezane** [comment]
/priority backlog

@seans3 @pwittrock @monopole any thoughts on this one? Do we remove that page from the kubectl book?

**Comment by pwittrock** [comment]
Need to update Kustomize first

**Comment by Markus-ipse** [comment]
Has anything happened regarding this issues?

**Comment by DavidGrinberg** [comment]
Bases are still even used on the main [readme](https://github.com/kubernetes-sigs/kustomize#2-create-variants-using-overlays) - 

![image](https://user-images.githubusercontent.com/13791262/97366517-d2b52e80-187d-11eb-98a0-ec56155cbf83.png)

Very unclear what the suggested method is given [this comment](https://github.com/kubernetes-sigs/kustomize/issues/2243#issuecomment-651751009)

**Comment by timhughes** [comment]
https://kubernetes-sigs.github.io/kustomize/blog/2019/06/18/v2.1.0/#resources-expanded-bases-deprecated

**Comment by Markus-ipse** [comment]
I don't think this issue is stale or rotten, it's just a lack of updates.

**Comment by m1o1** [comment]
Maybe this issue is worth reopening? I see "bases" is deprecated, but I'm curious what else I might be missing.

**Comment by obecker** [comment]
I just encountered https://kubectl.docs.kubernetes.io/references/architecture/field_merge_semantics/#when-are-fields-merged which still contains a link "bases" that points to the above mentioned (and meanwhile removed) page.

**Comment by madalinignisca** [comment]
This issue was closed by a bot, but the official docs still only instruct to use `bases`.

Is there a reason why a "bot" really wants human users to be confused?

**Comment by highb** [comment]
I've [opened a PR to update all the references to `bases` that I could find in the docs](https://github.com/kubernetes/website/pull/40761/files).
