### ISSUE TITLE
Kubectl describe prefix match feature

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubectl#892]
In `kubectl describe` we actually have this prefix match feature:
```
kubectl describe secret default
Name:         default-token-d5dff
Namespace:    default
```
Which is not in `kubectl get`:
```
kubectl get secret default 
Error from server (NotFound): secrets "default" not found
```
The logic is written in https://github.com/kubernetes/kubernetes/blob/180af4240c42906f072112e7ac7818f4b3574c5a/staging/src/k8s.io/kubectl/pkg/cmd/describe/describe.go#L240-L253

But for this feature I have couple of questions:
1. Should `kubectl get` , `kubectl logs`, `kubect edit`...behave the same?
2. This feature doesn't work for resource tuple like `kubectl describe secrets/default`
3. This feature only works for one resource as the [logic](https://github.com/kubernetes/kubernetes/blob/180af4240c42906f072112e7ac7818f4b3574c5a/staging/src/k8s.io/kubectl/pkg/cmd/describe/describe.go#L169) is kind of hack.
4. Most strange thing is the original [PR](https://github.com/kubernetes/kubernetes/pull/7467) seems not designed to solve the prefix match problem.
5. For prefix use cases like deployment name, replicas name(`nginx-deployment` to match `nginx-deployment-6f6cf6d4db-9dxxb`), wa can use label selector to get the resources(kubectl describe po -l name=myLabel).

It seems not a bug, just I think the feature we have here is not complete and not strong enough. For example, move the prefix mathing logic to builder as other commands can use it. 

PS: similiar issue found:https://github.com/kubernetes/kubernetes/issues/10674

**Comment by dougsland** [comment]
@zhouya0  it seems in the original PR was focused in the describe command not for global commands.
Not sure about others in the development group but I would just deprecate such generic match for describe. As you mentioned  it can be achieved by labels or even with kubectl autocomplete.

**Comment by apelisse** [comment]
Yes, I'd be fairly opposed to seing `kubectl get` with that behavior. `describe` is probably fine because it's meant for humans rather than machines, but we can't have `kubectl get` return arbitrary objects in scripts, it has to do exactly what it is asked. Just my two cents.
