### ISSUE TITLE
kubectl run should generate a name for the pod by default

### ISSUE THREAD

**Issue by giuscri** [kubernetes/kubectl#893]
**What would you like to be added**: Allow the user to launch
```
kubectl run -ti --rm --image=alpine
```
That is, not requiring the user to specify a name for the pod.

**Why is this needed**: I feel that many user could just call their pod as the name of the image, like `kubectl run --image=alpine alpine`, `kubectl run --image=nginx nginx`, ... Why not generating a random name for the pod fror the name of the image + something unique like an id?

**Comment by soltysh** [comment]
We require naming created resources to ensure the user know what was created, and is also responsible for making the resource name unique. 
/close
