### ISSUE TITLE
Support private git repos 

### ISSUE THREAD

**Issue by musabmasood** [kubernetes/kubectl#894]
(apologies if this a duplicate request)

**What would you like to be added**:

`kubectl apply -f git@my.private.host/my-repo.git/branch/dir/`

**Why is this needed**:

Currently unable to directly apply use private git repos

**Comment by eddiezane** [comment]
@musabmasood a starting point for this would be to start with a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).

/priority backlog

**Comment by olegsu** [comment]
@musabmasood I have created a plugin for it. The [PR](https://github.com/kubernetes-sigs/krew-index/pull/730) is not merged yet as it is in review and API refine.
If you can give it a try it would be great feedback.
You can give it a try by:
* install it by `kubectl krew install --manifest-url https://raw.githubusercontent.com/olegsu/kubectl-fetch-yaml/master/krew.yaml`
* run it by `kubectl fetch-yaml git --repo REPO --branch main --revision abcdefg --path dir --key-file /path | kubectl apply -f -`
