### ISSUE TITLE
Let kubectl not to use a proxy

### ISSUE THREAD

**Issue by OuSatoru** [kubernetes/kubectl#895]
I installed a kubernetes cluster in local servers based on the offical docs, when downloading packages and docker images, I uses a proxy (yyy.yyy.yyy.yyy), after installed, I cleared the envs. Now kubectl automatically uses the proxy. I don't want to open the proxy every time I use the kubectl command.

**What happened**:
`kubectl logs _somepod_`
got
> Error from server: Get https://xxx.xxx.xxx.xxx:10250/containerLogs/default/_somepod_/_podname_: proxyconnect tcp: dial tcp yyy.yyy.yyy.yyy:38080: connect: connection refused

**What you expected to happen**:
see the logs of the pod

**How to reproduce it (as minimally and precisely as possible)**:

Trying to get resourses of pods in the other nodes, kubectl uses a proxy which I don't want to use with kubectl.

**Anything else we need to know?**:
env | grep -i proxy
Blank

docker info | grep Proxy
 HTTP Proxy: http://yyy.yyy.yyy.yyy:38080/
 HTTPS Proxy: http://yyy.yyy.yyy.yyy:38080/
 No Proxy: zzz.zzz.zzz.zzz,localhost,127.0.0.1 # zzz.zzz.zzz.zzz is the ip of local docker registry

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Own bare metal servers in local room uses Intranet

- OS (e.g: `cat /etc/os-release`):
CentOS 7

**Comment by eddiezane** [comment]
@OuSatoru can you please provide detailed steps and examples to reproduce this from a generic environment?

/triage needs-information

**Comment by OuSatoru** [comment]
because there is http_proxy env when `kubeadm init`, reinstall with http_proxy cleaned before `kubeadm init` solved the problem.
