### ISSUE TITLE
Contradicting kubectl apply documentation

### ISSUE THREAD

**Issue by SebStrug** [kubernetes/kubectl#896]
Originally filed at: https://github.com/kubernetes/website/issues/22465 (now closed)

**Contradicting kubectl apply documentation**

**Problem**:
The `kubectl apply` documentation here:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

Says that the `-k` flag should be used for a directory.

However the documentation here for the kubectl overview:
https://kubernetes.io/docs/concepts/configuration/overview/#using-kubectl

Suggests using the `-f` flag for a directory. Why is there a discrepancy?

**Proposed Solution**:
Clarification is needed that `-f` can take a file, a manifest URL, or a local directory containing manifests. If there are any particular reasons why `-f` is best practice, these should be stated.

**Pages to Update**:
One of the following pages should be updated or clarified:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply
or
https://kubernetes.io/docs/concepts/configuration/overview/#using-kubectl

**Comment by seans3** [comment]
@SebStrug Hello Seb. The `-f <DIR>` flag is for regular resource config (e.g. yaml) within the directory, and it can be combined with the `-R` recursive flag. The `-k <DIR>` flag is for directories of kustomize configuration that needs the extra step of `kustomize build`. You can tell if a directory has kustomize configuration if there is a `kustomization.yaml` file in the directory. The `-k` flag can not be used with `-f` or `-R`. All of this is flag information is available in `kubectl apply -h`. If we should update other sources, we should probably track that in another issue. I will close this issue shortly.

/assign
/kind support
/sig cli
/area kubectl
