### ISSUE TITLE
Enhance kubectl create (Add useful flags from kubectl run e.g. replicas, labels, requests, limits, env, port etc.)

### ISSUE THREAD

**Issue by armujahid** [kubernetes/kubectl#898]
`kubectl create` is currently too limited. `kubectl run` gave a-lot flexibility in creating deployments and jobs via command-line. 
We can do very little with kubectl create without editing yaml file. In my opinion it was a very bad idea to [remove generators in kubectl run](https://github.com/kubernetes/kubernetes/pull/87077) without providing similar functionality in `kubectl create`.

**What would you like to be added:**
Add the functionality lost as a result of generators removal from `kubectl run`. We should be able to add labels, replicas, requests, limits or any other functionality that is supported by `kubectl run`. 
Flags required:
- replicas
- labels
- requests
- limits
- env
- port
- serviceaccount

**Why is this needed:**
The current `kubectl create` is way too limited!! It really hinders what can be done via command-line.

Related issue: https://github.com/kubernetes/kubernetes/issues/88888

**Comment by armujahid** [comment]
Related PRs:
Replicas: https://github.com/kubernetes/kubernetes/pull/91562

**Comment by eddiezane** [comment]
@armujahid there's a discussion that needs to be had about enhancing kubectl create/run and their intended goals. I've added it to the agenda for our next SIG-CLI meeting and it would be great to have you join us.

Next meeting is August 12th at 9:00 AM Pacific Time.

https://github.com/kubernetes/community/tree/master/sig-cli#meetings

/priority awaiting-more-evidence

**Comment by eddiezane** [comment]
@armujahid are you ok closing this after the SIG-CLI discussion?

As a note of historical reference it was discussed that `create/run` commands are not going to be expanded to push folks to use other tools and best practices. We will be spinning up a new SIG subproject to attempt to tackle a `kubectl generate`.

Will link to recording when it's uploaded.

**Comment by armujahid** [comment]
Sure. I would love to contribute to `kubectl generate`

**Comment by bbugh** [comment]
It's been some time, was anything moved forward on `generate` or adding resurrecting command line arguments?

**Comment by armujahid** [comment]
Linking https://github.com/eddiezane/kubectl-generate repo. Currently in WIP.
