### ISSUE TITLE
Retrieve Kubernetes API uri for current context

### ISSUE THREAD

**Issue by gwkunze** [kubernetes/kubectl#899]
**What would you like to be added**:

I'm trying to retrieve the current contexts API url but I have found no convenient way of getting it, `kubectl cluster-info` displays it but not in a machine readable way (including ANSI color codes that show up regardless of whether a PTY is there). I ended up using the following script to get it:
```
function get_cluster_api_url {
    local CONTEXT
    local CLUSTER
    CONTEXT=$(kubectl config current-context)
    CLUSTER=$(kubectl config view -o json | jq -r --arg context "${CONTEXT}" '.contexts[] | select(.name == $context) | .context.cluster')
    kubectl config view -o json | jq -r --arg cluster "${CLUSTER}" '.clusters[] | select(.name == $cluster) | .cluster.server'
}
```

But that is rather verbose, and potentially fragile.

I would like to be able to get this information from `kubectl` more easily, I can think of a couple of different ways:

1. Give `kubectl cluster-info` a `--output json` option
2. Make the information of the current context available through `kubectl config current-context --output json`

**Why is this needed**:
In our CI/CD pipeline we have a current context set by kops which is an administrator (cluster-admin), and we want to create a store the cluster api uri in a configuration database

**Comment by hpedrorodrigues** [comment]
I think you can use something like this: 

```bash
kubectl config view --minify --output jsonpath="{.clusters[*].cluster.server}"
```

**Comment by gwkunze** [comment]
Thanks! I read so many `--help` outputs for different commands but must've missed that option :\
