### ISSUE TITLE
Enhancement: envvar in ~/.kube/config

### ISSUE THREAD

**Issue by NelsonJeppesen** [kubernetes/kubectl#902]
**What would you like to be added**:
The ability to use envars inside the kubectl config

**Why is this needed**:
When using iam auth it gives the ability to share the same config to the entire company by inserting the username

for example, using the USERNAME envvar
```- name: dev.apptentive.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "somecluster"
        - "-s"
        - "${USERNAME}"
        - "-r"
        - "arn:aws:iam::0000000000:role/KubeAdmin"
```

**Comment by eddiezane** [comment]
@NelsonJeppesen this change would actually scope beyond kubectl to [client-go](https://github.com/kubernetes/client-go) as that's how configs are loaded. It's also the same mechanism used by most Kubernetes daemons/tools so the change could have wide reaching implications and require some coordination i.e. [KEP](https://github.com/kubernetes/enhancements/tree/master/keps).

If this is something you'd like to pursue I'd open it under client-go or the main kubernetes repo.

That said I didn't realize that the env vars from the host OS are merged in. I think a better solution for you would be to have the [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) add support for that flag as an env var.

https://github.com/kubernetes/client-go/blob/5ab99756f65dbf324e5adf9bd020a20a024bad85/tools/clientcmd/api/v1/types.go#L203-L207

/close
