### ISSUE TITLE
no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1"

### ISSUE THREAD

**Issue by sinethra** [kubernetes/kubectl#904]
**What happened**: I've installed the cert-manager via Helm and Static Manifests and all the resources in the cert-manager namespace are up and running. But the logs for CRD shows this " error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28" ". When I created an issue in cert-manager, I was told that this is bug in kubectl.

I followed the official cert-manager guide "https://cert-manager.io/docs/installation/kubernetes/" and used "kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.0/cert-manager.yaml" to install CRD and cert-manager. The same issue is shown in the play with K8s 

![image](https://user-images.githubusercontent.com/48240014/89454983-32b89f00-d77f-11ea-97f2-b801c8d6deba.png)

The API group for the kind CustomResourceDefinition in kubectl (kubectl api-resources) is apiextensions.k8s.io
![image](https://user-images.githubusercontent.com/48240014/89455182-86c38380-d77f-11ea-94e5-b09247f5a54e.png)

Also, apiextensions.k8s.io should support both v1 and v1beta1 according to "kubectl api-versions"
![image](https://user-images.githubusercontent.com/48240014/89455238-9ba01700-d77f-11ea-97fa-7c3fa6152146.png)

**What you expected to happen**: The CRDs to deploy and not to show any errors in logs

**How to reproduce it (as minimally and precisely as possible)**:
Install cert-manager using regular manifests "kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.0/cert-manager.yaml" and check logs for CRD.

```
[node1 ~]$ kubectl get crd
NAME                                  CREATED AT
certificaterequests.cert-manager.io   2020-08-04T11:35:35Z
certificates.cert-manager.io          2020-08-04T11:35:35Z
challenges.acme.cert-manager.io       2020-08-04T11:35:35Z
clusterissuers.cert-manager.io        2020-08-04T11:35:36Z
issuers.cert-manager.io               2020-08-04T11:35:36Z
orders.acme.cert-manager.io           2020-08-04T11:35:36Z

[node1 ~]$ kubectl logs crd/clusterissuers.cert-manager.io
error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

[node1 ~]$ kubectl logs crd/certificaterequests.cert-manager.io
error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

[node1 ~]$ kubectl logs crd/certificates.cert-manager.io
error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

[node1 ~]$ kubectl logs crd/challenges.acme.cert-manager.io
error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

[node1 ~]$ kubectl logs crd/issuers.cert-manager.io
error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: vmware
- OS (e.g: `cat /etc/os-release`): Centos 7
- cert-manager version (e.g. v0.4.0): v0.16
- Install method (e.g. helm or static manifests): both

**Comment by eddiezane** [comment]
@sinethra the errors you are seeing are intended albeit a little confusing.

Custom Resource Definitions (CRDs) cannot directly create logs.

You can however get the logs directly from the pod.

```
$ kubectl -n cert-manager get pods
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-bd9d585bd-shxtj               1/1     Running   0          22m
cert-manager-cainjector-76c6657c55-mch6r   1/1     Running   0          22m
cert-manager-webhook-64b9b4fdfd-htdv8      1/1     Running   0          22m

$ kubectl -n cert-manager logs cert-manager-bd9d585bd-shxtj
I0805 19:48:46.969205       1 start.go:74] cert-manager "msg"="starting controller"  "git-commit"="b14a7f2dfbc16b5a1228173f1a4de8985e66dbf3" "version"="v0.16.0"
...
```

Or from the deployment/service

```
$ kubectl -n cert-manager get deployments.apps
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager              1/1     1            1           23m
cert-manager-cainjector   1/1     1            1           23m
cert-manager-webhook      1/1     1            1           23m

$ kubectl -n cert-manager logs deployment.apps/cert-manager
I0805 19:48:46.969205       1 start.go:74] cert-manager "msg"="starting controller"  "git-commit"="b14a7f2dfbc16b5a1228173f1a4de8985e66dbf3" "version"="v0.16.0"
...
```

Does that make sense?

This might help https://kubernetes.io/docs/concepts/cluster-administration/logging/.

**Comment by sinethra** [comment]
@eddiezane Same kind of error shows for the logs of clusterissuer or issuer.

```
[root@kube-manager cert-manager]# kubectl logs clusterissuer/letsencrypt-staging
error: no kind "ClusterIssuer" is registered for version "cert-manager.io/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

This is my ClusterIssuer Manifest

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  creationTimestamp: null
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: sinethraks@gmail.com
    privateKeySecretRef:
      name: example-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status: {}
```

**Comment by eddiezane** [comment]
@sinethra `ClusterIssuer` is a CRD along with all of the resources created by cert-manager. **CRDs do not directly have logs**.

You'll need to get the logs for whichever deployment works with the `ClusterIssuer` resource which I believe is just `cert-manager`.

```
$ kubectl -n cert-manager logs deployment/cert-manager

...
I0805 20:51:39.516237       1 setup.go:165] cert-manager/controller/clusterissuers "msg"="skipping re-verifying ACME account as cached registration details look sufficient" "related_resource_kind"="Secret" "related_resource_name"="example-issuer-account-key" "related_resource_namespace"="cert-manager" "resource_kind"="ClusterIssuer" "resource_name"="letsencrypt-staging" "resource_namespace"=""
I0805 20:51:39.516325       1 controller.go:162] cert-manager/controller/clusterissuers "msg"="finished processing work item" "key"="letsencrypt-staging"
```

You can also use `kubectl describe` to learn more about a specific resource and get the events.

```
$ kubectl describe clusterissuers.cert-manager.io letsencrypt-staging

...
Status:
  Acme:
    Last Registered Email:  sinethraks@gmail.com
    Uri:                    https://acme-staging-v02.api.letsencrypt.org/acme/acct/15029420
  Conditions:
    Last Transition Time:  2020-08-05T20:51:35Z
    Message:               The ACME account was registered with the ACME server
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
```

/close

**Comment by RyanSquared** [comment]
hi! i know this probably isn't the best place but i don't know of how else to reach out to @sinethra - if you're using a GitOps management system I believe the issue you may be having is that cert-manager has MASSIVE CRDs, which *I THINK* exceed the Kubernetes limit.

I will be working on a way to slim this down. Feel free to contact me using the links on my profile and I'll send you regular status updates :)
