### ISSUE TITLE
Add support for passing yaml or json files in kubectl patch

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [kubernetes/kubectl#905]
**What would you like to be added**: capability of passing the patch in the form of  a yaml or a json file, instead of just plain hardcoding the patch in the `kubectl patch` command itself

**Why is this needed**: Right now, the `kubectl patch` command only allows the patch to be passed directly in the command itself after the `-p` flag. But in case of applying large patches, the entire command could become extremely long and unclean. So, in that case, it would be extremely convenient to, instead of writing the entire patch in the command itself (after the -p flag), the user can actually write the patch in a separate JSON file (the exact same json he would have originally passed in the command) and just pass the path to that JSON file in the `kubectl patch` command.
And behind the scenes, kubectl can read that JSON file and simply apply it as a patch as it normally does.
So, to exemplify this,

Say, the user wants to update the node `my-node` with the patch `'{"spec": {"unschedulable": true}}'`.

So, right now, he can only do this,

`kubectl patch node my-node -p '{"spec": {"unschedulable": true}}'`

But with the feature I suggested: the user can create a file called `patch.json`
```
{
"spec": {
         "unschedulable": true
   }
}
```
And just run the following command
`kubectl patch node my-node -p patch.json`

This might seem unnecessary from the above example because of its simplicity, but this feature would be extremely useful if we considering large and convoluted patches.

**Comment by eddiezane** [comment]
@yashvardhan-kukreja it looks like a portion of this is in progress at https://github.com/kubernetes/kubernetes/pull/93548.

Let's have you sync up with @smarterclayton. Looks like their PR doesn't have support for JSON files yet.

Since I don't see an attached issue on that PR we can keep this issue for tracking.

/priority backlog

**Comment by smarterclayton** [comment]
The PR is exactly the same behavior as `-p` - adding more formats that aren't the JSON patch formats would be a feature change to both flags.

**Comment by yashvardhan-kukreja** [comment]
@smarterclayton , @eddiezane  so , what formats you'd suggest to further implement? I ll hop onto them
