### ISSUE TITLE
kubectl edit pods to add security context fails

### ISSUE THREAD

**Issue by harsha-s** [kubernetes/kubectl#907]
**What happened**:
master $ kubectl edit pods/ubuntu-sleeper
Edit cancelled, no changes made.

When I tried to add the below line to the while editing in the spec: section for the pod attached.
  securityContext:
    runAsUser: 1000
[k8s-pod-yml.txt](https://github.com/kubernetes/kubectl/files/5046251/k8s-pod-yml.txt)

**What you expected to happen**:

edit of the pod declaration to succeed without cancellation.

**How to reproduce it (as minimally and precisely as possible)**:

1) create a pod using the attached file 
2) Try to edit the pod to add a security context as shown below on the spec section 
  securityContext:
    runAsUser: 1000

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
master $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
master $
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
master $ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
master $

**Comment by knight42** [comment]
Currently it is intended that the spec of a Pod could not be updated after its creation except for the `containers.image` field.

/remove-kind bug
/close

**Comment by darshandkd** [comment]
Could you edit the SecurityContext in Deployment (at a Pod or Container level)?
