### ISSUE TITLE
Ensure we're using i18n where possible

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/kubectl#910]
There is a scattered usage of `i18n.T()` throughout descriptions and flags. Let's make future translations easier by ensuring we're using i18n where feasible.

Examples:

https://github.com/kubernetes/kubectl/blob/19b50d838ed2e2a7389a3fb467b259982c772b73/pkg/cmd/apply/apply.go#L171
https://github.com/kubernetes/kubectl/blob/19b50d838ed2e2a7389a3fb467b259982c772b73/pkg/cmd/annotate/annotate.go#L153

/sig cli
/kind cleanup
/priority backlog
/good-first-issue

**Comment by Evalle** [comment]
I think I can help with that. 
/assign

**Comment by jayendra13** [comment]
What kind of pattern should I follow to internationalise the strings, is it applicable to only the help text for commands ?

**Comment by eddiezane** [comment]
@jayendra13 let's aim to get command and flag descriptions wrapped and then evaluate what else you find.

**Comment by jayendra13** [comment]
> @jayendra13 let's aim to get command and flag descriptions wrapped and then evaluate what else you find.

👍 got it.

**Comment by HerrNaN** [comment]
@jayendra13 @eddiezane It seems like nothing has happened here for a while, is it ok if I take over?

**Comment by jayendra13** [comment]
yes sure I got busy with some other stuff, and I almost forgot this.
you can continue on this.

**Comment by jayendra13** [comment]
may be this can help https://github.com/kubernetes/kubectl/pull/916

**Comment by HerrNaN** [comment]
Somehow adding i18n translations on every single `Short` and `Long` line seems a bit micromanaging in a way. Wouldn't it be easier to go through all the commands and add that separately? This would allow the code that describe how the commands should work less cluttered, more consise and easier to read and we can ensure that all commands get these translations.

WDYT @eddiezane?

**Comment by rikatz** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/97610
