### ISSUE TITLE
Optionally search for and merge config files from a directory

### ISSUE THREAD

**Issue by tedtramonte** [kubernetes/kubectl#911]
**What would you like to be added**: Kubectl should optionally search for and merge config files from a directory (~/.kube/configs/ ?)

**Why is this needed**: Perhaps my ignorance is showing, but I find managing multiple configs a hassle. I'm aware of the `$KUBECONFIG` env variable, but that doesn't seem sufficient to me. Having to make configuration changes to my shell scripts just to persist the clusters that I'm working on for the day or week is clunky.
Rather, if kubectl searched through ~/.kube/configs/ and used any valid config in that directory as part of its merge process, I wouldn't need to customize any variables and could add and remove clusters from all of my tools and terminals very easily.

**Comment by eddiezane** [comment]
Good request. We're tracking this over at #569. There are a few suggestions in that thread that might hold you over in the meantime.

/triage duplicate
/close
