### ISSUE TITLE
port-forwarding for services should favour choosing newer pods over older pods

### ISSUE THREAD

**Issue by briandealwis** [kubernetes/kubectl#920]
**What would you like to be added**:

`kubectl port-forward svc/xxx` is actually implemented internally by choosing and forwarding to a pod that matches the service's label selector. The pod selection algorithm is implemented in [`polymorphichelpers.attachablePodForObject()`](https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/attachablepodforobject.go#L32), the meat of which is in these three lines:
https://github.com/kubernetes/kubectl/blob/6871e8f43aae732a236bde58615dedbc282e01e3/pkg/polymorphichelpers/attachablepodforobject.go#L51-L53
  - `GetFirstPod` fetches the list of pods and sorts them according to the provided sorter, and then returns the first pod
  - key however is that the list of active pods is reversed (line 51), such that the pod selected by `GetFirstPod()` is actually the _greatest_ as defined by `ActivePods#Less()` https://github.com/kubernetes/kubectl/blob/6871e8f43aae732a236bde58615dedbc282e01e3/pkg/polymorphichelpers/helpers.go#L53-L56
  - [`ActivePods#Less()`](https://github.com/kubernetes/kubectl/blob/2b775f287352b3191b0e52cc4231941cd8e337bf/pkg/util/podutils/podutils.go#L129) favours older pods:
    - Step 3: sorts ready pods as "greater" than not-quite-ready pods
    - Step 4: sorts pods that have been as ready for longer as "greater"
    - Step 6: sorts older pods (by creation time) as "greater" than younger pods

As a result, `kubectl port-forward svc/xxx` forwards to older pods.

My proposal is to reverse Step 6 to [favour younger pods over older pods](https://github.com/GoogleContainerTools/skaffold/issues/4522#issuecomment-662690790).  On the rollout of a new deployment, younger pods are more likely to be associated with the new deployment definition than the older pods.

What's interesting is that the godoc for `ActivePods` says: https://github.com/kubernetes/kubectl/blob/2b775f287352b3191b0e52cc4231941cd8e337bf/pkg/util/podutils/podutils.go#L123

So `ActivePods#Less()`'s behaviour makes sense in this context as it's likely that a controller would want to delete older pods in favour of newer pods.  But there does not seem to be any such uses of `ActivePods`.

**Why is this needed**:

[Skaffold](https://skaffold.dev) is a local-development tool that offers a tight feedback loop during development by rebuilding and redeploying applications to for Kubernetes on source changes.  Skaffold supports establishing port-forwards to pods and services (via `kubectl port-forward`), and re-establishes port-forwards after a redeploy.  This generally works well, but we noticed that [users would occasionally hit stale data from forwarded service ports](https://github.com/GoogleContainerTools/skaffold/issues/4522) for several seconds after a redeploy.  We then had an example brought to our attention where stale  data continued to be returned for up to 30 seconds.  We discovered that this stale data arose as `kubectl port-forward svc/xxx` was [forwarding to an old pod that was in the process of being replaced by a newer pod](https://github.com/GoogleContainerTools/skaffold/issues/4522#issuecomment-662690790), and that the old pod was slow in being terminated as [the underlying containerized application ignored SIGINT](https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/385).

We have since implemented our [own pod-selection strategy that favours selecting new pods](https://github.com/GoogleContainerTools/skaffold/pull/4590) in Skaffold.  But `kubectl`'s selection algorithm will affect users who roll-out deployment updates and use port-forward to access services.

**Comment by eddiezane** [comment]
@briandealwis great writeup.

This would make sense to me and it doesn't seem like a breaking change with regards to `port-forward`.

@soltysh @seans3 @pwittrock thoughts?

**Comment by soltysh** [comment]
This particular use-case seems reasonable, but I assume you're targeting the default and not adding additional capability. If that's the case then I hate to say but we can't break backwards compatibility doing so. I'm happy you were able to bypass your problem by implementing your own pod selection algorithm.
/close
