### ISSUE TITLE
--all should ask for confirmation

### ISSUE THREAD

**Issue by jmreid** [kubernetes/kubectl#921]
**What would you like to be added**:

There are legit cases to use `--all` when using kubectl, especially when you're working in a smaller cluster or for personal uses. But, a command like `kubectl delete namespace --all` is quite dangerous and currently offers zero confirmation before doing it's job. This can lead to accidentally deleting/annotating resources. A simple confirmation of "You've specified the `--all` flag on this command, this will affect all resources across the cluster. Do you want to continue? N/y?" would go a long way to preventing accidents.

**Why is this needed**:

I command like `kubectl delete namespace --context=my_context --namespace=my_namespace` results in the message:
```
error: resource(s) were provided, but no name, label selector, or --all flag specified
```

This can be confusing as the user provided a namespace (even though this isn't the correct flag for this command). If that user added `--all`, then the command would immediately start deleting all namespaces in that context without any confirmation.

This is obviously a user-error, but a simple confirmation would go a long way to ensuring that the user in fact intended to affect all namespaces.

**Comment by eddiezane** [comment]
This has come up a few times before and has been a "no" because it's a breaking change.

Most recently - https://github.com/kubernetes/kubectl/issues/804.

**Comment by eddiezane** [comment]
We're working on posting an FAQ to hold historical knowledge and decisions. Here's the relevant excerpt:

> Introducing `--all` would be a breaking change. We’ve made an attempt in the past (see https://github.com/kubernetes/kubernetes/pull/62167) and we’ve decided that the suggested approach is to encourage cluster owners to implement something like https://github.com/kubernetes/kubernetes/pull/17740 or currently using validating webhooks (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io) but no such effort will be undertaken in kubectl itself.

/close

**Comment by abhiTamrakar** [comment]
This may still be worked, think about the behaviour of `rm -i` command in Linux. By default there is no confirmation, but with `-i`
