### ISSUE TITLE
Add validation in container spec for resource quantity suffix.

### ISSUE THREAD

**Issue by kaushik229** [kubernetes/kubectl#924]
**What happened**:
The suffix allowed to denote resource quantity for resource reservation in container spec has options to specify units.  However if use wrong suffix for resource, if might result resource to go in bad state. We need to be careful about using the right suffix for right resource. For example, if we specify suffix `m` for storage resource, there is no validation at the client side and this get processed by api-server and later messes with quota calculation logic, ultimately resulting blocking update on quota object(status) forever due to bad value of resource quantity.

**What you expected to happen**:
Bad request should be rejected at client with proper error message.
Add validation of resource suffix. For example, storage can only have Mi, Gi or Ti suffix. CPU can have `m` (milli) unit. etc.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a resource quota object in namespace with storage limits enforced.
2. Mention following in container spec.
```
spec:
    resources:
      requests:
        storage: 10m
```
As there is no validation currently, we will be able to launch the deployment with above spec. However after some time, the quota object will not be able to update status.
We see following error message.

ResourceQuota "<quota-object-name>" is invalid: status.used[xxxxxx.storageclass.storage.k8s.io/requests.storage]: Invalid value: resource.Quantity{i:resource.int64Amount{value:<large integer value>, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"<large integer value>m", Format:"DecimalSI"}: must be an integer

**Anything else we need to know?**: No

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", 
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", 
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Darwin(client)

**Comment by eddiezane** [comment]
@kaushik229 thanks for reporting this.

kubectl purposefully doesn't do client side validation and instead relies on the API server to validate.

I believe this "m" issue has actually been reported on the main kubernetes repo.

https://github.com/kubernetes/kubernetes/issues/79950

/close
