### ISSUE TITLE
vbom.ml has gone

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubectl#925]
**What happened**:

$ go get k8s.io/kubectl@v0.19.0
go: k8s.io/kubernetes@v1.19.0 requires
	k8s.io/kubectl@v0.0.0 requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml: No address associated with hostname

**What you expected to happen**:

The import should have been replaced with the non-vanity name as per 

https://github.com/fvbommel/util/commit/c69461e88a3651040fa9fe17c444462f587a751a

https://github.com/fvbommel/util

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Comment by eddiezane** [comment]
@NeilW thanks for the heads up on this!

I've opened a PR to fix this.

https://github.com/kubernetes/kubernetes/pull/94451
