### ISSUE TITLE
Port forwarding fails after restarting the pod that is being forwarded to

### ISSUE THREAD

**Issue by jjfmarket** [kubernetes/kubectl#926]
**What happened**:
I forward a port into a service in my cluster, then restart the pod that the service points to with `kubectl rollout restart`. The port is still open, but is not being forwarded correctly. It now throws an error 
`E0904 22:55:29.177715    5088 portforward.go:400] an error occurred forwarding 8082 -> 80: error forwarding port 80 to pod 517661763edca90a6910587dfefee2055dec798392c8ba2d49461dca3548a8b8, uid : Error: No such container: 517661763edca90a6910587dfefee2055dec798392c8ba2d49461dca3548a8b8`

**What you expected to happen**:
The port continues to be forwarded into the service correctly

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl --kubeconfig=$MY_CONFIG port-forward svc/$MY_SERVICE 8082:80 &`
`curl localhost:8082` #works
`kubectl --kubeconfig=$MY_CONFIG rollout restart $MY_NAMESPACE/$MY_POD`
`curl localhost:8082` #this times out, and a port forwarding error appears

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS EC2
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04 Bionic Beaver

**Comment by eddiezane** [comment]
Let's track this at #686 now that it's reopened.

/close

**Comment by jjfmarket** [comment]
Thank you @eddiezane

**Comment by joebone** [comment]
Looks like #686 has been closed again.

**Comment by brianpursley** [comment]
> Looks like #686 has been closed again.

I just reopened it.

**Comment by trollkarlen** [comment]
Nothing new on this for 3 years ?
