### ISSUE TITLE
Add --tokenfile flag

### ISSUE THREAD

**Issue by jlpettersson** [kubernetes/kubectl#927]
**What would you like to be added**:

Today it is possible to authenticate with `kubectl` using the `--token` to provide a token as a parameter. I would like to have a flag `--tokenfile <path>` that is similar but reads the token from a file.

**Why is this needed**:

This is useful for doing `kubectl apply -f manifest.yaml --tokenfile '/var/run/secrets/kubernetes.io/serviceaccount/token'` similar to how [client-go read the token from file](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L474) from within a pod in the cluster.

A typical use-case for this is when deploying from a CI/CD-system like [Tekton Pipelines](https://github.com/tektoncd/pipeline) and use the newer, more secure tokens, provided by [Service Account Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) - where the token exists on a path - but is regularly renewed.

**Comment by eddiezane** [comment]
@jlpettersson would `kubectl apply -f manifest.yaml --token $(cat '/var/run/secrets/kubernetes.io/serviceaccount/token')` work for you here?

/triage needs-information

**Comment by jlpettersson** [comment]
> @jlpettersson would `kubectl apply -f manifest.yaml --token $(cat '/var/run/secrets/kubernetes.io/serviceaccount/token')` work for you here?
> 
> /triage needs-information

That is surely one way to do it.

But:
* That token is shown in the shell output/logs(?) - at least in the environment I have used it in.
* The image needs to have a shell (so a more secure CI/CD environment is not possible). I would prefer to have a `kubectl` static binary in a Dockerfile built `FROM scratch` or using distroless.

Therefore, I currently do:

`cat '/var/run/secrets/kubernetes.io/serviceaccount/token' | xargs -I % kubectl apply -f manifest.yaml --token %`

but I would prefer a native way to do it, without using a shell and `xargs` (to pass it via stdin).

**Comment by soltysh** [comment]
@jlpettersson by default kubectl looks for in-cluster config (see [Authenticating inside the cluster](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/in-cluster-client-configuration/README.md#authenticating-inside-the-cluster) for more info) which means that it checks for `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` envs present and for `/var/run/secrets/kubernetes.io/serviceaccount/token` and `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` files present. If it finds them it knows it's running within a cluster and can use that to talk with the cluster. Does this mechanism could address your problem?

**Comment by jlpettersson** [comment]
This sounds interesting and a possible solution @soltysh thank you!

I will close this issue. I will try with this proposed solution, I did not know that `kubectl` used `client-go` internally, but that sounds reasonable.
