### ISSUE TITLE
Do Not Show Deletion Flags Under kubectl apply Options

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/kubectl#928]
I was recently looking into if `kubectl apply` offered a similar shorthand as `kubectl delete` does for `--wait` to avoid needing to run a `kubectl wait` command after to verify all pods become available in a namespace after an apply is run.

Looking further at the documentation for `kubectl apply -h`, it displays options like `--wait` and `--timeout`, and the descriptions seem to be in the context of `kubectl delete`:

```
--timeout=0s: The length of time to wait before giving up on a delete, zero means determine a timeout from the
size of the object
...
--wait=false: If true, wait for resources to be gone before returning. This waits for finalizers.
```

Not sure what the reasoning is for displaying these options with apply since they aren't supported options, but was wondering if there are any plans in place to either support these options with apply or to remove the non-applicable options. 

**What happened**:

Delete options like `--timeout` and `--wait` are displayed for `kubectl apply -h`:

```
--timeout=0s: The length of time to wait before giving up on a delete, zero means determine a timeout from the
size of the object
...
--wait=false: If true, wait for resources to be gone before returning. This waits for finalizers.
```

**What you expected to happen**:

These options should not be displayed with `kubectl apply`.

**How to reproduce it (as minimally and precisely as possible)**:

Run `kubectl apply -h`

**Environment**:

- Kubernetes client and server versions (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

N/A

- OS (e.g: `cat /etc/os-release`):

N/A

**Comment by danielhelfand** [comment]
Making a note here that the original issue description seems to miss. `wait` and `timeout` are supported with `kubectl apply`, but a more appropriate description for the options with apply may have been removed in https://github.com/kubernetes/kubernetes/pull/62487. It looks like the apply command is currently using the delete command options, but it should possibly have it's own descriptions like it did previously.

**Comment by eddiezane** [comment]
This should be fixed at some point.

/reopen
/remove-lifecycle rotten

**Comment by rikatz** [comment]
/lifecycle active
/assign

Let me try to take a look :)

**Comment by rikatz** [comment]
/lifecycle active
This week is the week I'm gonna do this :)
