### ISSUE TITLE
portforward: error: UDP protocol is not supported for...

### ISSUE THREAD

**Issue by amorenoz** [kubernetes/kubectl#929]
**What happened**:

There has been a regression in port `kubectl portforward`.

When a service is exported on both TCP and UDP using the same port
```
$ kubectl get --namespace ovn-kubernetes service/skydive-analyzer 
NAME               TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                        AGE
skydive-analyzer   NodePort   10.96.16.173   <none>        8082:32579/TCP,8082:32579/UDP,12379:31058/TCP,12380:31937/TCP,9200:32198/TCP   27m
```
... you *can* (I'll clarify later) get:

- Using kubectl-1.18.8-0:
```
$ kubectl port-forward --namespace ovn-kubernetes service/skydive-analyzer 8082:8082
Forwarding from 127.0.0.1:8082 -> 8082
Forwarding from [::1]:8082 -> 8082
```
- Using kubectl-1.19.0-0:
```
$ kubectl port-forward --namespace ovn-kubernetes service/skydive-analyzer 8082:8082
error: UDP protocol is not supported for 8082
```

**What you expected to happen**:

To still be able to forward a the TCP port

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce it consistently as shown above. However, as I'll clarify below, it might depend in how the ports are ordered in the Pod spec.

**Anything else we need to know?**:

It all comes from:
https://github.com/kubernetes/kubectl/commit/5ee889da0a7b88157a4e24136a2f68fc07b35b6c

The reason, I believe, lies in this function:
https://github.com/kubernetes/kubectl/blob/e6a1485bc955308c0d5757c458a1049c9c0aff0f/pkg/cmd/portforward/portforward.go#L278-L291

More specifically, in the fact that the loop does not consider the fact that the TCP port might appear before the UDP one in the iteration.

In fact, just swapping the below two elements of the unit test, makes it fail:
https://github.com/kubernetes/kubectl/blob/e6a1485bc955308c0d5757c458a1049c9c0aff0f/pkg/cmd/portforward/portforward_test.go#L924-L932

The fix is not complicated so I'll send a PR soon.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
The regression happens between 1.18.8 and 1.19.0
I'm trying with server version v1.19.0 but I doubt that's relevant in this case

**Comment by amorenoz** [comment]
Posted https://github.com/kubernetes/kubernetes/pull/94728

**Comment by dmitry-mightydevops** [comment]
Same issue in kubectl 1.21

```
➜ k poo                                                      
NAME                                        IMG                                                                                                                   PODIP          NODE                                          NODEIP        PORTS                     STATE     QOS         STARTED
ingress-nginx-controller-5d9548879f-9298h   k8s.gcr.io/ingress-nginx/controller:v0.47.0@sha256:a1e4efc107be0bb78f32eaec37bef17d7a0c81bec8066cdf2572508d21351d0b   10.110.11.86   ip-10-110-9-113.us-west-2.compute.internal   10.110.9.113   80,443,10254,8443,10000   Running   Burstable   2021-07-31T23:58:31Z
ingress-nginx-controller-66d4b645cb-lb8qr   k8s.gcr.io/ingress-nginx/controller:v0.47.0@sha256:a1e4efc107be0bb78f32eaec37bef17d7a0c81bec8066cdf2572508d21351d0b   10.110.9.195   ip-10-110-9-113.us-west-2.compute.internal   10.110.9.113   80,443,10254,8443,10000   Running   Burstable   2021-08-01T02:24:30Z

➜ kgsvc | grep 10000
ingress-nginx-controller-udp         LoadBalancer   172.20.136.205   aecb645d6dbf0457082cd885c807b54c-9d05e6441a01ff81.elb.us-west-2.amazonaws.com   10000:30622/UDP              4m12s

➜ k port-forward svc/ingress-nginx-controller-udp 10000:10000
error: UDP protocol is not supported for 10000

```

kubectl version:

```
➜ k version                                                  
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T00:59:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
