### ISSUE TITLE
Kustomize Documentation - Typo in the newName parameter in image section

### ISSUE THREAD

**Issue by yogendra** [kubernetes/kubectl#933]
**What happened**:
newImage parameter is incorrectly statted as nameName parameter in the documentation for kustomize https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#
**What you expected to happen**:
Parameter name should be newName

**How to reproduce it (as minimally and precisely as possible)**:

Visit - https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#

**Anything else we need to know?**:
Its only a change int he documentation. 

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A

**Comment by eddiezane** [comment]
Will be closed by https://github.com/kubernetes/kubernetes/pull/89086

/priority backlog
