### ISSUE TITLE
cpu request/limit differ in value in describe node and describe pod

### ISSUE THREAD

**Issue by kmmanto** [kubernetes/kubectl#934]
**What happened**:
I'm trying to programatically retrieve resource requests/limits using the Python API and found out that some pods differ in the returned values from kubectl describe no node

`kubectl describe no node`
```
  Namespace                  Name                             CPU Requests  CPU Limits   Memory Requests  Memory Limits  AGE
  ---------                  ----                             ------------  ----------   ---------------  -------------  ---
  default                    fluentd-86cb78bdc4-sbcb2         250m (0%)     500m (1%)    512Mi (0%)       1Gi (0%)       15d
```

`kubectl describe pod fluentd-86cb78bdc4-sbcb2`
```
Limits:
  cpu:     200m
  memory:  1Gi
Requests:
  cpu:      100m
  memory:   512Mi
```

**What you expected to happen**:
Same values should be reported

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a `stable/fluentd` helm chart

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by knight42** [comment]
Are there multiple containers in pod `fluentd-86cb78bdc4-sbcb2`? If so, `kubectl describe pod` would display the resource requests and limits for individual container, while `kubectl describe node` would display the sum.

**Comment by kmmanto** [comment]
@knight42 There is only one container and one init-container which I believe is not included in the sum. However, there are other pods in that node that have 1+ containers but are reported correctly.

**Comment by knight42** [comment]
> There is only one container and one init-container which I believe is not included in the sum.

https://github.com/kubernetes/kubectl/blob/d70ead5fcaa0e8f8246715584147ba3bfd081411/pkg/util/resource/resource.go#L40-L44
The resource requests and limits of init-containers define the minimum resource of a Pod, so I think the init-container actually requests `250m` cpu and the limit is `500m`, right? If so, then this is expected behavior.

/remove-kind bug

**Comment by kmmanto** [comment]
Yes, that's what the init-container is set to.

So this would only apply if the resource requests/limits of the init-container is more than any of the containers in the pod right?

**Scenario A**

`describe node`
```
Limits:
  cpu:     500m  -> init-container
  memory:  1Gi   -> container-a
Requests:
  cpu:     250m  -> init-container
  memory:  512Mi -> container-a
```
`init-container`
```
Limits:
  cpu:     500m
  memory:  128Mi
Requests:
  cpu:     250m
  memory:  64Mi
```
`container-a`
```
Limits:
  cpu:     200m
  memory:  1Gi
Requests:
  cpu:      100m
  memory:   512Mi
```

**Scenario B**

`describe node`
```
Limits:
  cpu:     600m  -> container-a + container-b
  memory:  2Gi   -> container-a + container-b
Requests:
  cpu:     400m  -> container-a + container-b
  memory:  1Gi -> container-a + container-b
```
`init-container`
```
Limits:
  cpu:     500m
  memory:  128Mi
Requests:
  cpu:     250m
  memory:  64Mi
```
`container-a`
```
Limits:
  cpu:     200m
  memory:  1Gi
Requests:
  cpu:      200m
  memory:   512Mi
```
`container-b`
```
Limits:
  cpu:     400m
  memory:  1Gi
Requests:
  cpu:      200m
  memory:   512Mi
```

**Comment by kmmanto** [comment]
I guess it's answered by [init-container-resources](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources)
