### ISSUE TITLE
Unexpected behavior when using multiple contexts in kubeconfig

### ISSUE THREAD

**Issue by oz123** [kubernetes/kubectl#936]
When using a config with multiple contexts, one might see a surprising message if there is no context set.
Let me demostrate:
```
$ k config get-contexts 
CURRENT   NAME               CLUSTER            AUTHINFO         NAMESPACE
          coldsweet          microk8s-cluster   admin-microk8s   coldsweet
          devops             devops-calico      admin            
          devops-cilium      devops-cilium      admin-cilium     
*         microk8s-context   microk8s-cluster   admin-microk8s   
```

Here, I have a context set. So `kubectl get pods` or any other command works fine.
If there is no current-context, kubectl says it can't connect to localhost (that's reasonable if you know k8s, more on that below).
```
sed -i '/current-context/d' ~/.kube/config
 $ k config get-contexts 
CURRENT   NAME               CLUSTER            AUTHINFO         NAMESPACE
          coldsweet          microk8s-cluster   admin-microk8s   coldsweet
          devops             devops-calico      admin            
          devops-cilium      devops-cilium      admin-cilium     
          microk8s-context   microk8s-cluster   admin-microk8s   
$ k get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
**What would you like to be added**:
The above message is baffling if you encounter this for the first time. A better message would be something like this:
```
Mutliple contexts found but no context is set. Which cluster shall I use? Please set an active context
```
**Why is this needed**:
I give Kubernetes workshops, where students use multiple clusters. As we go through setting `~/.kube/confing` for usage with multiple clusters, some students will rush to try stuff, and forget to set a context. This results in frustration and funny facial  expressions staring at the screen. We explain that `kubectl`, uses localhost per default - and that older versions of kubernetes where not secured on localhost. A much better UI will be simply telling the user he didn't set up a context.

I'm willing to send a PR for improving this UI. This should not be hard to fix (I have already submitted code to k8s/k8s).

/sig usability

**Comment by oz123** [comment]
I believe this is #737 is related.

**Comment by oz123** [comment]
Validation of the configuration is done here:

https://github.com/kubernetes/kubernetes/blob/ba35704b510f918254c3ba826fb63608f6ed2dd6/staging/src/k8s.io/client-go/tools/clientcmd/validation.go#L152

The is already a validaor that checks that the context `foo` exists. 
```
$ grep foo ~/.kube/config
current-context: foo
 $ k get pods
Error in configuration: context was not found for specified context: foo
```

To fix this issue, a validator that checks that the configuration has `current-context` set should be added.

**Comment by noahi** [comment]
Your suggested error content looks good to me. Is there a situation where localhost is desired?
