### ISSUE TITLE
Add KUBECTL_EXTERNAL_DIFF_OPTIONS env var to set custom diff command options

### ISSUE THREAD

**Issue by julienvey** [kubernetes/kubectl#937]
**What would you like to be added**:

I'd like an environment variable `KUBECTL_EXTERNAL_DIFF_OPTIONS` to be added in order to be able to customize the options when using a diff command other than `diff` when using `kubectl`

The related part of the code https://github.com/kubernetes/kubectl/blob/f00cf713934555e6edd635bd7477f028056eda50/pkg/cmd/diff/diff.go#L168

**Why is this needed**:

When using the default diff command, the options `-u` and `-N` are set by default. I'd like to have these same options when using `colordiff`, and also be able to add any other options that might be necessary

**Comment by dougsland** [comment]
I think make sense. Let me try to prepare a patch.

**Comment by dougsland** [comment]
With the provided patch the following commands work:

```
 $ export KUBECTL_EXTERNAL_DIFF="colordiff -N -u"
 $ kubectl diff -f filename.yaml  
```

**Comment by seans3** [comment]
@julienvey Please note an environment variable already exists for choosing the `diff` program. According to `kubectl diff -h`:
```
KUBECTL_EXTERNAL_DIFF environment variable can be used to select your own diff command. By default, the "diff" command
available in your path will be run with "-u" (unified diff) and "-N" (treat absent files as empty) options.
```

An example is:
```
export KUBECTL_EXTERNAL_DIFF=meld; kubectl diff -k ./dir/
```

Closing

**Comment by dougsland** [comment]
patch is merged, thanks for the report.
/close

**Comment by armingerten** [comment]
There is still a small gap: When using GNU diffutils, some commands (e.g. `--color[=WHEN]`) require an equal sign, which is excluded by the specified regex (`^[a-zA-Z0-9-]+$`)
