### ISSUE TITLE
`kubectl run` does not fail when you do not pass a NAME, when you pass a --command

### ISSUE THREAD

**Issue by sallyom** [kubernetes/kubectl#943]
**What happened**:
```console
$ kubectl run --image fedora --command -- sleep 100
pod/sleep created
```
the pod is created, then crashloops with
```console
container create failed: time="2020-10-02T16:28:22Z" level=error msg="container_linux.go:366: starting container process caused: exec: \"100\": executable file not found in $PATH"
```
this should instead error w/ the msg,
```
error: NAME is required for run
See 'kubectl run -h' for help and examples
```
**How to reproduce it (as minimally and precisely as possible)**:
`$ kubectl run --image fedora --command -- sleep 100`
the pod/sleep is created, and if you 
`kubectl get pod/sleep -o yaml` you'll see the error noted above.

**Environment**:
latest master build

**Comment by sallyom** [comment]
oh i came across this: https://github.com/kubernetes/kubernetes/issues/13004#issuecomment-140405582  this was a previous issue but fix was never implemented AFAICT

**Comment by eddiezane** [comment]
@sallyom any update on this one?

**Comment by sallyom** [comment]
I should finally have time to look at this, will report back

**Comment by dougsland** [comment]
Hi Sally,

Just faced this one recently. Here some thoughts, hope it helps. :)

Having --name as required argument now would break scripts/tools but IMO is the best option for a long term solution (see below).

Based on above, I would be in favor to have a message to users (for now) informing that --name is available and ask them to update the command line arguments/scripts/tools. At the same time,  open a KEP about this topic that **after 'X' releases** the --name **will be required for run** but, for now, just inform users with this message/blog post/documentation.

On the other hand, it's possible to keep investing time in more complex parsing for --command but, at least, I am not in favor for increasing complexity. From what I see, the modern tools usually have flags for all options.

Here some snip code:
```
diff --git a/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go b/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
index b8ef46b619e..1e3a51e2dfa 100644
--- a/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
+++ b/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
@@ -125,6 +125,7 @@ type RunOptions struct {
        Schedule       string
        TTY            bool
        fieldManager   string
+       Name           string
 
        Namespace        string
        EnforceNamespace bool
@@ -150,7 +151,7 @@ func NewCmdRun(f cmdutil.Factory, streams genericclioptions.IOStreams) *cobra.Co
        o := NewRunOptions(streams)
 
        cmd := &cobra.Command{
-               Use:                   "run NAME --image=image [--env=\"key=value\"] [--port=port] [--dry-run=server|client] [--overrides=inline-json] [--command] -- [COMMAND] [args...]",
+               Use:                   "run [--name] NAME --image=image [--env=\"key=value\"] [--port=port] [--dry-run=server|client] [--overrides=inline-json] [--command] -- [COMMAND] [args...]",
                DisableFlagsInUseLine: true,
                Short:                 i18n.T("Run a particular image on the cluster"),
                Long:                  runLong,
@@ -176,6 +177,7 @@ func addRunFlags(cmd *cobra.Command, opt *RunOptions) {
        cmd.Flags().StringArray("annotations", []string{}, i18n.T("Annotations to apply to the pod."))
        cmd.Flags().StringVar(&opt.Generator, "generator", opt.Generator, i18n.T("The name of the API generator to use, see http://kubernetes.io/docs/user-guide/kubectl-conventions/#generators for a list."))
        cmd.Flags().MarkDeprecated("generator", "has no effect and will be removed in the future.")
+       cmd.Flags().StringVar(&opt.Name, "name", opt.Name, i18n.T("The name for the container to run."))
        cmd.Flags().StringVar(&opt.Image, "image", opt.Image, i18n.T("The image for the container to run."))
        cmd.MarkFlagRequired("image")
        cmd.Flags().String("image-pull-policy", "", i18n.T("The image pull policy for the container. If left empty, this value will not be specified by the client and defaulted by the server"))
@@ -272,6 +274,10 @@ func (o *RunOptions) Run(f cmdutil.Factory, cmd *cobra.Command, args []string) e
                return cmdutil.UsageErrorf(cmd, "%v", err)
        }
 
+       if o.Name == "" {
+               fmt.Println("The option --name was not specified. Please update the kubectl command to specify --name")
+       }
+
```

Probably good topic for sig-cli weekly meeting.

**Comment by sallyom** [comment]
thanks for your input, @dougsland! See, the name is already set as "required" with kubectl run:
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/run/run.go#L266-#L268  
However, the cmd gets confused only when you pass a --command.
With this cmd, you get the proper error:
```console
$ kubectl run --image fedora
error: NAME is required for run
```
But with this cmd you get a pod created stuck with Status `CreateContainerError` and with the name pod/sleep:
```console
$ kubectl run --image fedora --command -- sleep 100
Error from server (AlreadyExists): pods "sleep" already exists
$ oc get pods
NAME    READY   STATUS                 RESTARTS   AGE
sleep   0/1     CreateContainerError   0          2m13s
```
We can discuss during next CLI bug-call and/or sig-CLI!

**Comment by dougsland** [comment]
Hey @sallyom,

> thanks for your input, @dougsland! See, the name is already set as "required" with kubectl run:
> https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/run/run.go#L266-#L268

I believe that's not enough for a validation. :( 

> However, the cmd gets confused only when you pass a --command.

Agreed. I noticed the same. 

> With this cmd, you get the proper error:
> 
> ```
> $ kubectl run --image fedora
> error: NAME is required for run
> ```
> 
> But with this cmd you get a pod created stuck with Status `CreateContainerError` and with the name pod/sleep:
> 
> ```
> $ kubectl run --image fedora --command -- sleep 100
> Error from server (AlreadyExists): pods "sleep" already exists
> $ oc get pods
> NAME    READY   STATUS                 RESTARTS   AGE
> sleep   0/1     CreateContainerError   0          2m13s
> ```
> 
> We can discuss during next CLI bug-call and/or sig-CLI!

Sure thing! Thanks!

**Comment by rikatz** [comment]
@dougsland anything in this one that I can help?

**Comment by dougsland** [comment]
> Hi @sallyom,
> 
> Just faced this one recently. Here some thoughts, hope it helps. :)
> 
> Having **--name** as required argument now would break scripts/tools but IMO is the best option for a long term solution (see below).
> 
> Based on above, I would be in favor to have a message to users (for now) informing that --name is available and ask them to update the command line arguments/scripts/tools. At the same time, open a KEP about this topic that **after 'X' releases** the --name **will be required for run** but, for now, just **inform users with this message/blog post/documentation**.
> 
> On the other hand, it's possible to keep investing time in more complex parsing for --command but, at least, I am not in favor for increasing complexity. From what I see, the recent tools out there usually have flags for all options anyway.
> 
> Here some snip code:
> 
> ```
> diff --git a/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go b/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
> index b8ef46b619e..1e3a51e2dfa 100644
> --- a/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
> +++ b/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
> @@ -125,6 +125,7 @@ type RunOptions struct {
>         Schedule       string
>         TTY            bool
>         fieldManager   string
> +       Name           string
>  
>         Namespace        string
>         EnforceNamespace bool
> @@ -150,7 +151,7 @@ func NewCmdRun(f cmdutil.Factory, streams genericclioptions.IOStreams) *cobra.Co
>         o := NewRunOptions(streams)
>  
>         cmd := &cobra.Command{
> -               Use:                   "run NAME --image=image [--env=\"key=value\"] [--port=port] [--dry-run=server|client] [--overrides=inline-json] [--command] -- [COMMAND] [args...]",
> +               Use:                   "run [--name] NAME --image=image [--env=\"key=value\"] [--port=port] [--dry-run=server|client] [--overrides=inline-json] [--command] -- [COMMAND] [args...]",
>                 DisableFlagsInUseLine: true,
>                 Short:                 i18n.T("Run a particular image on the cluster"),
>                 Long:                  runLong,
> @@ -176,6 +177,7 @@ func addRunFlags(cmd *cobra.Command, opt *RunOptions) {
>         cmd.Flags().StringArray("annotations", []string{}, i18n.T("Annotations to apply to the pod."))
>         cmd.Flags().StringVar(&opt.Generator, "generator", opt.Generator, i18n.T("The name of the API generator to use, see http://kubernetes.io/docs/user-guide/kubectl-conventions/#generators for a list."))
>         cmd.Flags().MarkDeprecated("generator", "has no effect and will be removed in the future.")
> +       cmd.Flags().StringVar(&opt.Name, "name", opt.Name, i18n.T("The name for the container to run."))
>         cmd.Flags().StringVar(&opt.Image, "image", opt.Image, i18n.T("The image for the container to run."))
>         cmd.MarkFlagRequired("image")
>         cmd.Flags().String("image-pull-policy", "", i18n.T("The image pull policy for the container. If left empty, this value will not be specified by the client and defaulted by the server"))
> @@ -272,6 +274,10 @@ func (o *RunOptions) Run(f cmdutil.Factory, cmd *cobra.Command, args []string) e
>                 return cmdutil.UsageErrorf(cmd, "%v", err)
>         }
>  
> +       if o.Name == "" {
> +               fmt.Println("The option --name was not specified. Please update the kubectl command to specify --name")
> +       }
> +
> ```
> 
> Probably good topic for a new round in sig-cli weekly meeting.

@rikatz how about the approach above?

@sallyom still working in this issue? Should we ask for contributors in the sig-cli meeting join this effort ?
