### ISSUE TITLE
Let us port forward services rather than just pods

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubectl#946]
During software development, it slows everything down to have to adjust port forwards as the new pods roll out.

Some third party tools like kubefwd may help, but they're flakey at best.

Please allow port forwarding of services, instead of being forced to target specific pods, which are ephemeral.

**Comment by eddiezane** [comment]
@mcandre you should be able to port forward to a service directly with `kubectl port-forward svc/nginx 8080:80`

We currently have #686 open to fix an issue with pods being restarted.

**Comment by dougsland** [comment]
Agreed @eddiezane. Probably good idea to close this one.

Reference:
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
