### ISSUE TITLE
kubectl logs cronjob support

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubectl#949]
**What would you like to be added**:

`kubectl logs cronjob/mycj` support

**Why is this needed**:

A convenient way to inspect the logs of the latest execution of a cron job.

@kubernetes/sig-cli-feature-requests

**Comment by soltysh** [comment]
I've explained this already in the past here https://github.com/kubernetes/kubernetes/issues/67070#issuecomment-414252984
The questions posted in the other comment are still valid and are main reason why this is not considered.
