### ISSUE TITLE
Document k8s.io/kubernetes/pkg/kubectl/resource

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#95]
The [kubectl/resource](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/doc.go) package has almost no documentation

- Write the doc.go with overview of what the package does and how to use it. Include examples.
  - Look at how it is already used to help figure this out
- Document the code for types and functions
- Write a CONTRIBUTING.md for this package with anything you discover
  - Include TODOs for any clean up items
  - Include tips, pitfalls and anything you learn that you wish was written down

**Comment by alessbn** [comment]
@pwittrock I'll pick up this issue

**Comment by pwittrock** [comment]
cc @seans3 @mengqiy

**Comment by pwittrock** [comment]
@alessbn ACK

**Comment by apelisse** [comment]
Awesome @alessbn ! Feel free to assign me when you're done! :-) Thank you

**Comment by alessbn** [comment]
Hi @apelisse I will split this issue into three PR as follows:
- [ ] Write a CONTRIBUTING.md.
- [ ] Document the code.
- [ ] Write the doc.go with overview and examples.

**Comment by apelisse** [comment]
@alessbn Sounds like a good plan to me!

For that last point, you can use #54572 as an example.
