### ISSUE TITLE
Add kubectl kustomize --version

### ISSUE THREAD

**Issue by strangiato** [kubernetes/kubectl#952]
**What would you like to be added**:

It would be great to have a `version` flag for kustomize in order to know which version of kustomize you are leveraging through kubectl.

For example:

```sh
kubectl kustomize --version
```

or 

```sh
kubectl kustomize version
```

**Why is this needed**:

Currently there is no way to know which version of kustomize you are using through kubectl other than external documentation.  

As far as I can tell the version shipping with kubectl is 2.0.3 but there appear to be plans to upgrade the version in future releases of kubectl.  As newer versions of kustomize become available it is important to be able to validate which version of kustomize you using for compatibility checks.

**Comment by eddiezane** [comment]
We're tracking this at https://github.com/kubernetes/kubectl/issues/797

/close
