### ISSUE TITLE
kubectl apply -k works different as kustomize build

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubectl#955]
**What happened**:
When using `kubectl apply -k` there is an error, while `kustomize build` works.

**What you expected to happen**:
They should work the same way.

**How to reproduce it (as minimally and precisely as possible)**:

```
.
├── base
│   ├── kustomization.yaml
│   └── longhorn.yaml
└── k4
    ├── kustomization.yaml
    └── longhorn.yaml
```

```
# cat k4/kustomization.yaml 
patchesStrategicMerge:
- longhorn.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
```

```
# kubectl apply --dry-run=client -k k4 
error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/tmp/test/base')
```

```
kustomize build k4   # (works)
```

**Anything else we need to know?**:

**Environment**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
kustomize version
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}
```

**Comment by soltysh** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/82905
/close

**Comment by balagithu** [comment]
hi Team , i am getting below error any help will be appreciated 

sh-4.4$ ./kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.6"
error: rawResources failed to read Resources: Load from path ./ecr-public failed: './ecr-public' must be a file (got d='/tmp/kustomize-095653624/deploy/kubernetes/overlays/stable/ecr-public')


lient Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
