### ISSUE TITLE
Upgrade cobra to 1.1.0

### ISSUE THREAD

**Issue by knrt10** [kubernetes/kubectl#956]
**What would you like to be added**:

Cobra released their new version yesterday https://github.com/spf13/cobra/releases/tag/v1.1.0 which included `ValidArgsFunction` for zsh completion. This means all the code needed for zsh here https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/completion/completion.go#L157 can be removed and converted to `GenZshCompletion`

**Why is this needed**:

So that completion can work fine with new features

**Comment by eddiezane** [comment]
This can be tracked at https://github.com/kubernetes/kubernetes/pull/95571. It has been a bit of an ordeal.

/close
