### ISSUE TITLE
About the signal handler in t.Safe()

### ISSUE THREAD

**Issue by g0dA** [kubernetes/kubectl#958]
I want to send an http request when my cli program exits unexpectedly, but it is found that the signal handler cannot be  executed correctly after using t.Safe()，So I made a demo：
```
package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"syscall"
	"time"

	"k8s.io/kubernetes/pkg/kubectl/util/term"
)

func setupTTY() term.TTY {
	var out io.Writer
	var in io.Reader
	t := term.TTY{
		Out: out,
	}
	t.In = in
	t.Raw = true
	stdin := os.Stdin
	stdout := os.Stdout
	in = stdin
	t.In = stdin
	if out != nil {
		out = stdout
		t.Out = stdout
	}
	return t
}

func main() {
	c := make(chan os.Signal)
	signal.Notify(c, syscall.SIGHUP)
	go func() {
		<-c
		cmd := exec.Command("curl", "http://127.0.0.1:9898")
		cmd.Run()
		os.Exit(0)
	}()

	t := setupTTY()
	fn := func() error {
		fmt.Println("process start...")
		sum := 0
		for {
			sum++
			fmt.Println("sum:", sum)
			time.Sleep(time.Second)
		}
		return nil //for return only
	}

	t.Safe(fn)
}
```
after run, I will execute `nc -lvvp 9898` locally and send SIGHUP(kill -1 PID), but i did not receive this request

So how can I handle the signal correctly?

**Comment by soltysh** [comment]
It doesn't look like this question is related to kubectl, but rather to signal handling in go. 
/close

**Comment by g0dA** [comment]
No, later investigation found that the problem was in this place
[pkg/util/interrupt/interrupt.go](https://github.com/kubernetes/kubectl/blob/master/pkg/util/interrupt/interrupt.go#L28)
Will handle these signals by default
