### ISSUE TITLE
The connection to the server was refused

### ISSUE THREAD

**Issue by LemonSpike** [kubernetes/kubectl#960]
**What happened**:
Ran `kubectl get node -o wide` after installing k3sup on my Mac using the IP Address of my Raspberry Pi node, and got this error:

`The connection to the server x.x.x.x:6443 was refused - did you specify the right host or port?`

**What you expected to happen**:
List of node details.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the install steps as outlined here: https://medium.com/@alexellisuk/walk-through-install-kubernetes-to-your-raspberry-pi-in-15-minutes-84a8492dc95a.

Enable all connections via `ufw` to the Pi, and enable SSH server mode using `sudo raspi-config`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration:
Pi 4B in SSH server mode, and MacBook Pro
- OS (e.g: `cat /etc/os-release`):
1. MacOS Catalina
2. Pi 4B OS:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by eddiezane** [comment]
@LemonSpike hopefully you figured this out.

My guess is this was an issue with requiring the cgroup kernel parameters on the Pi. K3s might have failed to start because they were missing. Looks like Alex updated the guide recently as well.

/triage support
/close
