### ISSUE TITLE
Option for kubectl to render messaging using structured output

### ISSUE THREAD

**Issue by briandealwis** [kubernetes/kubectl#963]
**What would you like to be added**:

Would be beneficial to have `kubectl` be able to deliver output in a structured form that can be consumed by other tools.

Minikube, for example, supports outputting information [as a stream of CloudEvents events](https://minikube.sigs.k8s.io/docs/contrib/json_output/).

**Why is this needed**:

Kubectl is increasingly being used as an implementation tool.  In Skaffold, kubectl is our main deployer, but we also use it to initiate port-forwarding (`kubectl port-forward`), and to synchronize changes files (via `kubectl exec`).  Separately, other tools use `kubectl get` and `kubectl apply`, instead of using the Client APIs, as kubectl transparently handles proxying.  And generally kubectl works great.

But we're increasingly having to parse output from kubectl to detect when errors have occurred ([example](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/resource/deployment.go#L34-L47)).  And the irony is that these messages are the result of [kubectl helpfully converting structured errors into a meaningful form for human consumption](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/util/helpers.go#L132).

It would be beneficial to have the output be deliverable in a structured form.

**Comment by dty1er** [comment]
`kubectl get` already have --output=json but others don't.

**Comment by briandealwis** [comment]
`get -o json` affects the normal output, but doesn't affect error output:
```
$ kubectl get all -o json
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by eddiezane** [comment]
@briandealwis Historically we have said that kubectl output is not versioned and have discouraged it being parsing.

I put it on the agenda for the next meeting (2020-12-02) if you'd like to join.

https://github.com/kubernetes/community/tree/master/sig-cli#meetings

**Comment by eddiezane** [comment]
We discussed this a few times and decided it will be good to have an output in the future that is machine parsable.

The first step here is to identify if anyone wants this enough to work on it for 9 months+. If so we want to enable you to do so. Will need a KEP, etc.
