### ISSUE TITLE
describe output is broken if all annotations are skipped (last-applied-configuration)

### ISSUE THREAD

**Issue by lalyos** [kubernetes/kubectl#966]
**What happened**:
In `kubectl describe` output, at the end of the line  **Annotations:** the newline char is missing , therefore the next line is slipping in.

Se how Annotations and Selector is in the same line:
```diff
$kubectl describe svc -n default kubernetes 
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
+ Annotations:       Selector:  <none>
Type:              ClusterIP
...
```

**What you expected to happen**:

I would expect either a `<none>` in the line of the Annotations, or maybe `<filtered>`. (discussion needed)
But the Selector: should be on a new line for sure.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl patch svc -n default kubernetes  --patch='{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"anything"}}}'
$ kubectl describe svc -n default kubernetes
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
kubectl version --short
Client Version: v1.18.2
Server Version: v1.18.9+k3s1
```
- Cloud provider or hardware configuration: Tested on GKE and on k3d and the same happened.

**Comment by lalyos** [comment]
This is already fixed/merged in upstream https://github.com/kubernetes/kubernetes/pull/91405

I've tested recent releases:
```
$ ./kubectl-v1.20.0-beta.0 describe svc kubernetes|grep Anno
Annotations:       <none>
$ ./kubectl-v1.19.3 describe svc kubernetes|grep Anno
Annotations:       <none>
$ ./kubectl-v1.19.0 describe svc kubernetes|grep Anno
Annotations:       <none>
$ ./kubectl-v1.18.9 describe svc kubernetes|grep Anno
Annotations:       Selector:  <none>
```
So **v1.18.9 is still broken** but above v1.19.0 every version is fixed.

**Comment by lindhe** [comment]
@lalyos I get the error still in 1.18.12
