### ISSUE TITLE
klog flags such as "--log_dir" are advertised but not usable.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubectl#967]
while `kubectl options` advertises that these flags are available but when I try to use them, they don't work,
for example --log-file or --log-dir

```
$ kubectl options
The following options can be passed to any command:

      --log-dir='': If non-empty, write log files in this directory
      --log-file='': If non-empty, use this log file
      --log-file-max-size=1800: Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0,
```

using --log_dir flag
```
kubectl version --log_dir="/tmp/m1/"
W1026 19:51:19.967493   51518 flags.go:39] log_dir is DEPRECATED and will be removed in a future version. Use log-dir instead.
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
the log dir is empty. but I expect to see log files
```
$ ls /tmp/m1/
```

 in minikube we have simmilar problem since we use kubectl's templates for grouping the cobra flags
https://github.com/kubernetes/minikube/issues/9521#issuecomment-716934748

**Comment by eddiezane** [comment]
@brianpursley do you remember this coming up recently?

**Comment by dougsland** [comment]
talked with @eddiezane over slack. Let me give a try in this report.

**Comment by brianpursley** [comment]
I don't recall it coming up, but looked at it and here is what I found:
You have to specify `--logtostderr=false` or else it won't write to a file.

So for example:
```
kubectl get nodes -v9 --log-dir /tmp/logs --logtostderr=false
```
(in the example above, the directory needs to exist already)

Similarly:
```
kubectl get nodes -v9 --log-file /tmp/mylog.txt --logtostderr=false
```

**Comment by eddiezane** [comment]
From bug scrub there also exists a `--alsologtostderr`

**Comment by eddiezane** [comment]
/triage accepted
/priority backlog
/assign @seans3 

> It might be good to add a prompt. Better documentation.

**Comment by medyagh** [comment]
@seans3 I am curious are u still working on this ? the fejta-bot is going to close it
