### ISSUE TITLE
localsubjectaccessreviews doesn't appear when listing api-resources

### ISSUE THREAD

**Issue by andras-gerendas** [kubernetes/kubectl#969]
**What happened**:

localsubjectaccessreviews didn't appear as an api resource when querying namespaced api-resources from kubectl.

**What you expected to happen**:

localsubjectaccessreviews should have appeared in the list of api resources.

**How to reproduce it (as minimally and precisely as possible)**:

I have called kubectl to retrieve namespaced api-resources with the following command:
kubectl api-resources --verbs=list --namespaced -o name

In the result localsubjectaccessreviews didn't appear even though it's visible in the list of resources in the json output.

**Anything else we need to know?**:

This is the relevant part of the result of the query (by running the above command with --v=8):

{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"authorization.k8s.io/v1","resources":[{"name":"localsubjectaccessreviews","singularName":"","namespaced":true,"kind":"LocalSubjectAccessReview","verbs":["create"]},{"name":"selfsubjectaccessreviews","singularName":"","namespaced":false,"kind":"SelfSubjectAccessReview","verbs":["create"]},{"name":"selfsubjectrulesreviews","singularName":"","namespaced":false,"kind":"SelfSubjectRulesReview","verbs":["create"]},{"name":"subjectaccessreviews","singularName":"","namespaced":false,"kind":"SubjectAccessReview","verbs":["create"]}]}

You can see that there are several "namespaced false" resource types, but localsubjectaccessreviews is not one of them.

**Environment**:

Kubernetes versions:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-16T17:47:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

OS version:

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by carlory** [comment]
@andras-gerendas localsubjectaccessreviews doesn't support the list verb.

```shell
(⎈ |ik8s:opensource)➜  kubernetes git:(master) kubectl api-resources  --namespaced -o name
...
localsubjectaccessreviews.authorization.k8s.io
...
```
