### ISSUE TITLE
Add conflict detection to pkg/kubectl/apply/strategy

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#97]
Time commitment: 5-15 hours

First read the apply documentation:
https://kubernetes.io/docs/tutorials/object-management-kubectl/declarative-object-management-configuration/

Apply is being rewritten under `pkg/kubectl/apply/strategy`.  The new merge and replace code should check for conflicts between the last seen value and the current value, and optionally return an error if they do not match with the field and details.

strategy.Options already has a field to fail on conflicts.
A conflict is if the same field is specified in BOTH the recorded and the remote values of an object, but does not match.

1. Update the [merge visitor](https://github.com/kubernetes/kubernetes/blob/4ff6ef4a378748d4c1667f352fb5d300170e4429/pkg/kubectl/apply/strategy/merge_visitor.go) functions to check for conflict if the options are enabled, and return an error if a conflict is detected
2. Update the tests to verify the new behavior
3. update the [replace visitor](https://github.com/kubernetes/kubernetes/blob/41568a060234c62742cd751c046de622fedb14ce/pkg/kubectl/apply/strategy/replace_visitor.go)  functions to check for conflict if the options are enabled, and return an error if a conflict is detected
4. Update the tests to verify the new behavior

**Comment by julianvmodesto** [comment]
I'm interested in giving this a shot – I'll need some examples of conflicts for tests. Will try finding some.

**Comment by julianvmodesto** [comment]
@pwittrock cc @seans3 @mengqiy 

I've an initial handle on this, but i'm a new contributor fyi so i might need some coaching if that's ok :)

>  A conflict is if the same field is specified in BOTH the recorded and the remote values of an object, but does not match.

Seems like we need something for field equality that's not `reflect.DeepEqual`, is there something for field equality available in apimachinery? I'll poke around.

**Comment by pwittrock** [comment]
@julianvmodesto Sorry for the late response.  Have you started this?

**Comment by julianvmodesto** [comment]
@pwittrock no worries, sorry, I dropped off on this. Feel free to re-assign to someone else!

**Comment by pwittrock** [comment]
SGTM

**Comment by lukahartwig** [comment]
If this issue isn't taken then I would like to try this.

**Comment by seans3** [comment]
Apply is moving to the server side. We will not be doing anymore work on apply within kubectl on the client side. This is obsolete. Marking closed.
