### ISSUE TITLE
Node Events update on Node failure

### ISSUE THREAD

**Issue by anwesh-b** [kubernetes/kubectl#971]
When we use `kubectl describe node <node_name>`, in the Events section there is no event listing if a running node fails. 
It would be better if we could see the events such as shut down of node. It does have event for reboot, but not for shutdown.

**Comment by eddiezane** [comment]
This would be a better fit for the [main kubernetes repo](https://github.com/kubernetes/kubernetes/issues) since kubectl simply pulls events from the server and displays them.

Looks like https://github.com/kubernetes/kubernetes/pull/96129 might actually bring this.

/close
