### ISSUE TITLE
Offer a silent flag or apply flag for kubectl create namespace

### ISSUE THREAD

**Issue by timurista** [kubernetes/kubectl#972]
**What would you like to be added**:
An flag to silence errors `--slient` or `--apply` flag to make`kubectl create` not complain when creating a resource that already exists (just like how apply works)

**Why is this needed**:
When creating a namespace using `kubectl create namespace` command you get an Error that the resource already exists. However, to get the error to not show up you can use kubectl apply -f namespace.yaml / inline file. This is hard to remember and awkward for developers to use when they are usually using the namespace creation here to ensure that the namespace exists. 

For creating a namespace which is a 1 line command it seems a bit overkill to have to create a namespace file or wrap the logic in an if-else block if you want to ensure the namespace resource is created.

*Possible Solutions*
- You could add a silent or quiet flag so the developer can ignore output if they need to.
- Or you could allow for a kubectl create --apply flag so that the create process works like apply which will not error if the resource exists.

I have seen a few issues of developers complaining about this specific case. And it leads us to have to write a lot of custom logic to accomplish something simple which is to check a namespace exists and create it if it isn't there.

**Comment by eddiezane** [comment]
@timurista could you please share more about your use case here and the need for silencing these errors?

The declarative approach is most always favored over the imperative in the Kubernetes world.

**Comment by timurista** [comment]
sure. Here's my use case we have a need to upgrade istio and associated components in our app. We also want to ensure that a namespace exists and add a default one if it is there.

Here's what we are doing currently to make this happen (with a prometheus helm chart install):
```echo '{"apiVersion": "v1", "kind": "Namespace", "metadata": {"name": "istio-system"}}' | $KUBECTL apply -f -
...
$HELM upgrade --install --namespace istio-system prometheus \
	 --set server.nodeSelector.node_type=$(NODE_SELECTOR) \
```
The apply -f- wors as intended in the line above by only adding the resource if it doesnt exist but ignoring it otherwise. However as you can see there's more info we don't necessary need or care about (apiVersion etc). It'd be nice to be able to apply a simple `kubectl apply namepsace istio-system` or something similar as we might have a number of places were we want to quickly ensure a namespace exists or add it so that the components can be installed.

**Comment by eddiezane** [comment]
Helm provides the `--create-namespace` flag which will create the namespace if it doesn't exist. Does that solve your use case?

https://helm.sh/docs/faq/#automatically-creating-namespaces

**Comment by eddiezane** [comment]
We discussed this and decided it's not something we'd want upstream.

/close
