### ISSUE TITLE
--since flag for kubectl get events

### ISSUE THREAD

**Issue by phisco** [kubernetes/kubectl#977]
**What would you like to be added**:
A `--since` flag for `kubectl get events`, similar to the one in the `logs` subcommand.
**Why is this needed**:
Given the nature of events, more similar to logs than real resources, it would make sense to have an easy way to filter events by timestamp without recurring to `jq` or custom scripts. 

I've tried to implement it using `-o jsonpath|gotemplate=", but it doesn't seem possible, let me know if that's not the case.

Personally I would need this in a CI/CD pipeline to print a bit more context in case of failure of the `helm upgrade --install` command, but i think it would be a useful feature.

**Comment by eddiezane** [comment]
@phisco valid request but I don't think we would add this to `kubectl get` as it would be very specific to events.

There's currently a KEP open for a new `kubectl events` command. Please take a look and add your thoughts there!

https://github.com/kubernetes/enhancements/issues/1440

/close

**Comment by phisco** [comment]
Definitely agree it would be better to have a dedicated subcommand, I'll check the proposal, thanks @eddiezane!
