### ISSUE TITLE
Repetitive messages in kubectl rollout status

### ISSUE THREAD

**Issue by harjas27** [kubernetes/kubectl#979]
**What would you like to be added**:
When using the `rollout status` command, the output contains repetitive messages. For example:

`Waiting for deployment "nginx-deployment" rollout to finish: 1 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 1 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 1 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 2 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 2 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 2 out of 3 new replicas have been updated...
Waiting for deployment "nginx-deployment" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "nginx-deployment" rollout to finish: 1 old replicas are pending termination...
deployment "nginx-deployment" successfully rolled out`

The reason it occurs is because there is no change in the `deployment.Status.UpdatedReplicas`, instead there is an increment in the `deployment.Status.AvailableReplicas`

**Why is this needed**:
Reducing the repetitive lines in the output

**Comment by eddiezane** [comment]
@harjas27 which version of kubectl and server are you using?

/triage needs-information
/assign @dougsland

**Comment by harjas27** [comment]
**Version details**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1401", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-25T01:04:47Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by dougsland** [comment]
Not sure if this is real issue as this is a watching/monitoring task. The best is discuss in the SIG-CLI meeting.
@eddiezane

**Comment by dougsland** [comment]
This issue has been discussed in the SIG-CLI meeting and agreed that the current behavior is working as expected.
I am closing this issue for now, feel free to re-open this issue and join the SIG CLI meetings to raise your point of view with us.

More info about the meeting: 
https://github.com/kubernetes/community/tree/master/sig-cli

/close
