### ISSUE TITLE
Document pkg/kubectl/cmd/util/env

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#98]
Document [pkg/kubectl/cmd/util/env](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/util/env).
- Add a `doc.go` describing what the package is for and providing examples on how to use it
- Improve type and function code-comment documentation

**Comment by ellenkorbes** [comment]
I'll take this one :)

**Comment by pwittrock** [comment]
@ellenkorbes Thanks.  Assigned to seans3 as a placeholder until you are added to the repo.

**Comment by ellenkorbes** [comment]
This was mostly solved on [this PR](https://github.com/kubernetes/kubernetes/pull/54572) except for the GetEnvVarRefString and GetEnvVarRefValue functions, as explained there.
