### ISSUE TITLE
Official documentation on the usage of kind List

### ISSUE THREAD

**Issue by vio-f** [kubernetes/kubectl#984]
**What would you like to be added**:
Could official documentation be created on the usage of kind List?

**Why is this needed**:
While [brianpursley's comment](https://github.com/kubernetes/kubectl/issues/837#issuecomment-632092853) on issue #837 kind of explained it, that does not represent official documentation, plus it does not properly address the purpose of it (only some use cases). Is it just a custom resource list? More explanation and examples are needed.
**NOTE** - this is a request for a documentation update, so please don't close it like #837 was. That being said, explanations, use cases, examples are welcome.

I would be happy to do it myself  if someone points me to the right direction.

**Comment by eddiezane** [comment]
This issue is scoped beyond kubectl and probably belongs elsewhere.

Leaving this open until I chat with sig-apimachinery.

**Comment by brianpursley** [comment]
@viorelflorian When you say official documentation, can you clarify what are you referring to?  Are you asking for something to be added to https://kubernetes.io?

**Comment by eddiezane** [comment]
@brianpursley I Googled and followed the tree of linked issues for https://github.com/kubernetes/kubectl/issues/837 (especially the Helm one - https://github.com/helm/helm/issues/8615) and `kind: List` seems to be a source of confusion for folks all around.

We should probably have some actual info about it since it only appears in that example and not in the the main docs or the API Reference.

I put in on the agenda for apimachinery tomorrow to get their take.

**Comment by eddiezane** [comment]
I checked in with apimachinery and `kind: List` is more of an internal resource that wasn't meant to be exposed. We currently use this inside kubectl when dealing with lists of mixed resources.

How to proceed is currently being discussed.

**Comment by viorelflorian** [comment]
I found usages of it in third party helm charts (traefik v2.3) and i was wondering what is the original intended usage of such a thing (it's not a resource, is it?)
For the record yes kubernetes.io sounds like a good place to document it. I believe there is a mention of it in the custom resources section.

**Comment by eddiezane** [comment]
@viorelflorian we're still not sure about the proper solution as this internal type was not meant to be exposed.

For now though we'd gladly accept documentation on it to https://github.com/kubernetes-sigs/cli-experimental/tree/master/site if you're still interested.

https://kubectl.docs.kubernetes.io/

**Comment by viorelflorian** [comment]
Sure. I would love to as soon as someone assigns this to me.

**Comment by eddiezane** [comment]
You should be able to `/assign` yourself. GitHub doesn't let us assign folks out of the org.

(Unless this works because you opened the issue)

/assign @viorelflorian

**Comment by sftim** [comment]
I'd be happy to move this issue to [k/website](https://github.com/kubernetes/website) but only a few people have access to move issues between repos.

**Comment by eddiezane** [comment]
Let's track this over at https://github.com/kubernetes/website/issues/25944

/close
