### ISSUE TITLE
kubectl port-forward fails when using a proxy with rancher

### ISSUE THREAD

**Issue by electrical** [kubernetes/kubectl#985]
**What happened**:
kubectl port-forward command throws an error when running with a socks5 proxy configured in the kube config file.
All other commands work fine so far.

I'm not 100% confident if this is a problem with kubectl or with the rancher implementation.

**What you expected to happen**:
Not to fail

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl port-forward pod/traefik-ingress-5f7dfcd6c-5t8fz  8080:8080
error: error upgrading connection: error sending request: Post "https://my.rancher.host.com/k8s/clusters/c-p4rhf/api/v1/namespaces/default/pods/traefik-ingress-5f7dfcd6c-5t8fz/portforward": EOF
```

**Anything else we need to know?**:

**Environment**:
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
Kubernetes version: 1.19.4
Rancher version: 2.5.2

**Comment by dims** [comment]
Can you please open this in https://github.com/rancher/rancher ?

/close

**Comment by eddiezane** [comment]
@electrical socks5 support is still a work in progress.

https://github.com/kubernetes/kubernetes/issues/58065
https://github.com/kubernetes/kubernetes/pull/84205
https://github.com/kubernetes/kubernetes/pull/72943

**Comment by electrical** [comment]
@eddiezane thank you so much for linking those :-) Looking forward to see that working.
