### ISSUE TITLE
Support of Apple Silicon 

### ISSUE THREAD

**Issue by ameukam** [kubernetes/kubectl#988]
**What would you like to be added**:

Provide full compatibility for Apple Silicon (AArch64/Arm64).
Support of those architectures in Golang is targeted for 1.16 : https://github.com/golang/go/issues/42756.

**Why is this needed**:
Apple has [announced](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/) transition of the Mac hardware line to Apple Silicon. It would be great to have this new architecture supported in the new releases.

**Comment by ameukam** [comment]
In progess: https://github.com/kubernetes/kubernetes/pull/97743

**Comment by billinghamj** [comment]
Seems that PR got merged :) This one may be ready to close?

**Comment by eddiezane** [comment]
Looks like! Thanks.

/close
