### ISSUE TITLE
cannot download v1.17.15

### ISSUE THREAD

**Issue by taishin** [kubernetes/kubectl#989]
**What happened**:

When I tried to download 1.17.15, 1.17.16-rc0 was downloaded.

**What you expected to happen**:

I expect 1.17.15 to be downloaded

**How to reproduce it (as minimally and precisely as possible)**:
```
$ curl -O https://storage.googleapis.com/kubernetes-release/release/v1.17.15/bin/linux/amd64/kubectl 
$ chmod +x kubectl
$ ./kubectl version --short
Client Version: v1.17.16-rc.0
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Alpine Linux v3.12

**Comment by eddiezane** [comment]
Thanks for reporting. Looks like folks are working on addressing it.

https://github.com/kubernetes/kubernetes/issues/97178

Let's track there.

/close
