### ISSUE TITLE
Document pkg/kubectl/cmd/util/editor package

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#99]
Document the [pkg/kubectl/cmd/util/editor](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/util/editor) package

- Add a `doc.go` with overview of the package and examples for usage
- Audit and improve type and function code comments.  Improve documentation.

**Comment by yuexiao-wang** [comment]
@pwittrock I would like to work on it.

**Comment by mengqiy** [comment]
This has been done. It's at https://github.com/kubernetes-sigs/testing_frameworks

**Comment by mengqiy** [comment]
Accidentally closed a wrong issue.
Reopening...

**Comment by wesley-ramos** [comment]
@nikhita  is anybody working on it ? If not I would like to take this issue

**Comment by wesley-ramos** [comment]
cc @seans3 @mengqiy

**Comment by nikhita** [comment]
> @nikhita is anybody working on it ? If not I would like to take this issue

No, it's all yours! :tada:

**Comment by wesley-ramos** [comment]
Ok I'll start

**Comment by kasisnu** [comment]
I'm interested in working on this.
