### ISSUE TITLE
Error while proxying request: connection reset by peer

### ISSUE THREAD

**Issue by MicDeDuiwel** [kubernetes/kubectl#990]
**What happened**:
Mentioned in this issue on kubernetes https://github.com/kubernetes/kubernetes/issues/97125 but will give a quick rundown here:

When using `kubectl` to port-forward, proxy, or tail logs we will eventually get a `connection reset by peer` issue. This does not seem to impact inter-pod or inter-node communication, only communications via `kubectl`. 
This issue started when I expanded and upgraded my bare-metal kubernetes cluster to 1.19.4 (was previously running 1.18.3)

I've done some deep dives into networking but this issue only seems to appear on our development machines, when doing similar tests on the master nodes themselves they never timeout or get reset. Example outputs from the api-server pod:

```
E1211 08:55:25.690288       1 watch.go:251] unable to encode watch object *v1.WatchEvent: write tcp 172.23.138.10:6443->172.23.138.119:47194: write: connection reset by peer (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc0094e05a0), encoder:(*versioning.codec)(0xc020a82460), buf:(*bytes.Buffer)(0xc008d42990)})
E1211 08:55:32.886828       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
I1211 08:55:34.822409       1 client.go:360] parsed scheme: "passthrough"
I1211 08:55:34.822824       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>} 
....
I1211 08:59:40.072171       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
E1211 08:59:54.321951       1 watch.go:251] unable to encode watch object *v1.WatchEvent: client disconnected (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc01a713fe0), encoder:(*versioning.codec)(0xc0150ccdc0), buf:(*bytes.Buffer)(0xc00a4da720)})
I1211 09:00:18.270353       1 trace.go:205] Trace[757390492]: "cacher list" type:*node.RuntimeClass (11-Dec-2020 09:00:15.270) (total time: 3000ms):
Trace[757390492]: [3.000186753s] [3.000186753s] END
error: read tcp 172.23.0.201:60814->172.23.138.10:8443: read: connection reset by peer
```

When proxying:
```
$ kubectl proxy                                                               
Starting to serve on 127.0.0.1:8001
E1211 09:20:54.196928    4143 proxy_server.go:144] Error while proxying request: read tcp 172.23.0.201:53710->172.23.138.10:8443: read: connection reset by peer
E1211 09:21:02.176601    4143 proxy_server.go:144] Error while proxying request: read tcp 172.23.0.201:53780->172.23.138.10:8443: read: connection reset by peer
```

When port-forwarding:
```
$ kubectl port-forward                   
Forwarding from [::1]:8001 -> 8080
E1211 09:21:04.551775    4157 portforward.go:233] lost connection to pod
```

**What you expected to happen**:
Kubectl should be able to handle invalid packets or minor disruptions (if this turns out to be a network issue)

**How to reproduce it (as minimally and precisely as possible)**:
Run a HA cluster with 3 master nodes with 2 cpu cores and 6 gig of RAM, use keepalived for HA, deploy 10 slaves with 4 cpu and 15 gig off RAM each. All running on Proxmox on different servers in the same datacenter. Use Flannel as the pod-network.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: bare-metal kubernetes deployed with kubeadm on Proxmox VM's, Keepalived v2.0.19 for HA.
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS, 5.4.0-56-generic kernel

**Comment by skulos** [comment]
hi @eddiezane, I'm helping @MicDeDuiwel with this problem. And it seems to be that the cluster works fine with `kubectl` commands, but anything needing a connection, like port-forward and proxy (for kubernetes dashboard) gets a sort-of time-out with a "peer reset" error. My suspicion is packets are being dropped or invalidated along the network.

It's hard to make this a feasible way to reproduce the err. Still not 100 sure what the error is and why the CLI is no longer keeping connections.

Regards

**Comment by MicDeDuiwel** [comment]
Update: We managed to find the issue, it was a result of two of our keepalived instances sharing the same id and being able to see each other on the subnet causing connection timeouts.
