### ISSUE TITLE
custom-columns stops abruptly when hitting a non-existent array index

### ISSUE THREAD

**Issue by fwolter** [kubernetes/kubectl#996]
**What happened**:
When the get pods command with custom-columns option hits an array index that doesn't exist for a pod, the command is aborted:
```
# kubectl get pods -o=custom-columns=STATUS:.status.conditions[1].status
STATUS
True
True
error: array index out of bounds: index 1, length 1
```

**What you expected to happen**:
That the non-existent array element is replaced e.g. by `<none>` in the output. And that the remaining pods are printed:
```
# kubectl get pods -o=custom-columns=STATUS:.status.conditions[1].status
STATUS
True
True
<none>
True
True
True
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:58:11Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:59:05Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-premises microk8s
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS

**Comment by dougsland** [comment]
> **What happened**:
> When the get pods command with custom-columns option hits an array index that doesn't exist for a pod, the command is aborted:
> 
> ```
> # kubectl get pods -o=custom-columns=STATUS:.status.conditions[1].status
> STATUS
> True
> True
> error: array index out of bounds: index 1, length 1
> ```
> 
> **What you expected to happen**:
> That the non-existent array element is replaced e.g. by `<none>` in the output. And that the remaining pods are printed:
> 
> ```
> # kubectl get pods -o=custom-columns=STATUS:.status.conditions[1].status
> STATUS
> True
> True
> <none>
> True
> True
> True
> ```
> 
> **Environment**:
> 
> * Kubernetes client and server versions (use `kubectl version`):
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:58:11Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:59:05Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> * Cloud provider or hardware configuration: on-premises microk8s
> * OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS

Hi @fwolter , I cannot reproduce the report in my env. Could you please provide more details how to reproduce it?

**Comment by fwolter** [comment]
Basically you can reproduce it with any cluster that contains at least one pod in the default namespace by specifying an array index which surely doesn't exist:
```
# kubectl get pods -o=custom-columns=STATUS:.status.conditions[99].status
STATUS
error: array index out of bounds: index 99, length 4
```

**Comment by dougsland** [comment]
> kubectl get pods -o=custom-columns=STATUS:.status.conditions[99].status

oh sure, reproduced, thanks!

**Comment by pacoxu** [comment]
I tried to fix it in https://github.com/kubernetes/kubernetes/pull/99579

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/pull/99579#pullrequestreview-702086882 here why the pull request was declined.
