### ISSUE TITLE
Binary data not shown in kubectl describe configmap

### ISSUE THREAD

**Issue by schollii** [kubernetes/kubectl#997]
To reproduce:

Create a config map from 2 files: one file is text, the other is a png. The text file will become a key in data field, whereas the png will become a key in binaryData field (this partially answers #20849).
Example:
```
$ kubectl create cm test-bin --from-file vimrc=.vimrc --from-file binary.png=/var/lib/docker/.../screenshots/basic-usage-with-colors.png
configmap/test-bin created
$ kubectl get cm test-bin -o json | jq '.data | keys'
[
  "vimrc"
]
$ kubectl get cm test-bin -o json | jq '.binaryData | keys'
[
  "binary.png"
]
```
The kubectl describe cm only shows data, not binaryData:
```
$ kubectl describe cm test-bin
Name:         test-bin
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
vimrc:
----
set expandtab
...
set paste

Events:  <none>
$ 
```

Proposed Solution:

How about I submit a PR that fixes the describe command so it shows a `binaryData` section, with key names and the number of bytes of each value (the actual bytes does not have much practical value)

**Comment by sftim** [comment]
I suggest deleting:
> How about I submit a PR that updates https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object:

from this issue. This repository is for issues about the kubectl code more than about its docs.

**Comment by schollii** [comment]
@sftim deleted

**Comment by eddiezane** [comment]
@schollii Would be happy to have you work on this!

/triage accepted
/priority backlog

**Comment by lauchokyip** [comment]
@eddiezane I can try to take a look at this 
/assign
