### ISSUE TITLE
The --local flag require valid kubeconfig to be present

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubectl#999]
**What happened**:

I'm trying to use `kubectl` to add label to local YAML manifests, howerver I found that you have to specify a kubeconfig even when you use the `--local` flag which should prevent `kubectl` talk to remote server.
As a workaround, one can set `KUBERNETES_MASTER=localhost`  and the command will work, but it is ugly and require env var that is here since stone age.

**What you expected to happen**:

I expect the command to run against local files without requiring kubeconfig. In addition (this is probably separate issue), I would expect the command to modify the local files (you can use `find --exec` or something to do this today).

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl label  --dry-run=client --local -R -f manifests/ foo=bar -o yaml -v=10
F0106 13:22:04.084503   36422 helpers.go:115] error: Missing or incomplete configuration info.  Please point to an existing, complete config file:


  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

```
**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by soltysh** [comment]
This is already being discussed in https://github.com/kubernetes/kubernetes/issues/93188
/close
